#include "IntrepidInterface.h"
#include "ModelTopology.h"
#include "VSet.h"
#include "LinearTetrahedron.h"

using namespace std;

namespace csmp {

/**

     Reads tetra-triangle meshes generated by the GeoModeller - CGAL interface.
     Model regions are identified by integer codes associated with
     the finite elements.
     
     Example Mesh
     
MeshVersionFormatted 1
Dimension 3
Vertices
8
0 0 0 0
1 0 0 0
0 1 0 0
0 0 1 0
1 1 1 0
2 2 0 0
3 2 0 0
2 3 0 0
Triangles
2
1 2 3 1      ---> pay attention element indexes start from 1
6 7 8 1
Tetrahedra
1
1 2 3 4 2
End

     Construct the model by:
     
     	Model<3U> model(model_topology, vset, "*-variables.txt", false );

*/
void IntrepidInterface::Read( const char* filename, VSet<3U>& vset, ModelTopology& model_topology ) const
{
	string s;
	int dimension;

	map< string, std::set<std::string> > fem_types;
	map< string, vector<size_t> >        regions; // key: name of the region, value: list of vertices
	vector<int8_t>                       element_types;
	deque< vector< size_t  > >           elements;
	vector<int8_t>                       element_type;
	deque<uint32_t>                      mixed_ele_plist;      // number of nodes per element
	deque<uint32_t>                      mixed_ele_pfverts;    // number of neighbours per element
	std::deque<std::vector<int64_t> > pfverts; // neighbour elements

	size_t n_vertices = 0;
	size_t n_elements = 0;

	ifstream file(filename);
  string str("IntrepidInterface::Read: ");
	if (!file.is_open()) throw invalid_argument(str + filename + " file not found");

	getline(file, s);

	file >> s >> dimension;
	if (dimension != 3) throw out_of_range(str + "dimension <> 3");

	file >> s;
	if (s != "Vertices") throw invalid_argument(str + "bad file format");
	file >> n_vertices;
	if (n_vertices <= 0) throw logic_error(str + "value not expected");

	vset.ResizeNodes(n_vertices);

	double px, py, pz;
	int unknown;
	for ( size_t i = 0; i<n_vertices; i++)
	{
		file >> px >> py >> pz >> unknown;
		vset.Px(i, px);
		vset.Py(i, py);
		vset.Pz(i, pz);
	}

	size_t region, n_elem;
  uint32_t npe, fpe, inode;
	string stype;
	int8_t etype;
	size_t elem_idx = 0;
  
	while (true)
	{
		string fem_string, csmp_fem;
		file >> stype;
		if (stype == "End") break;
		npe = 0; // nodes per element
		fpe = 0; // faces per element
		if (stype == "Triangles") {
        npe = 3;
        fpe = 3;
        etype = ISOPARAMETRIC_LINEAR_TRIANGLE;
        fem_string = "TRI_3";
        csmp_fem = "ISOPARAMETRIC_LINEAR_TRIANGLE";
      }
		if (stype == "Tetrahedra") {
         npe = 4;
         fpe = 4;
         etype = ISOPARAMETRIC_LINEAR_TETRAHEDRON;
         fem_string = "TETRA_4";
         csmp_fem = "ISOPARAMETRIC_LINEAR_TETRAHEDRON";
      }
		if (npe == 0) throw out_of_range(str + "number of nodes");
		element_types.push_back(etype);

		file >> n_elem;
		if (n_elem <= 0) throw out_of_range(str+"value not expected");
		n_elements += n_elem;

		vector<size_t> elem(npe);

		for (size_t i = 0; i<n_elem; i++)
      {
        for (uint32_t j = 0; j<npe; j++) {
            file >> inode;
            elem[j] = inode - 1; // intrepid files node index starts from 1 (apparently)
          }
        file >> region;

        std::stringstream region_name;
        region_name << "Region " << stype << " " << region;
        regions[region_name.str()].push_back(elem_idx);
        fem_types[region_name.str()].insert(csmp_fem);

        elements.push_back(elem);
        element_type.push_back(etype);
        mixed_ele_plist.push_back(npe);
        mixed_ele_pfverts.push_back(fpe);

        elem_idx++;
      }

	}
	file.close();
  cout <<"\nIntrepidInterface:Read: '"<< filename <<"' successfully.\n";

	// mixed_ele_plist: size=n_elements, each item contains the number of nodes of the corresponding element
	vset.ResizePlist(mixed_ele_plist);
	// plist: deque of vector<uint32_t>, one per element, vector contains idx of nodes of the elem
	vset.AddPlist(elements.begin(), elements.end());

	// element_types: deque of size_t, one per element, contains the type of the element (CSMP_FEM_TYPE)
	vset.AddElementTypes(element_type.begin(), element_type.end());


	// mixed_ele_pfverts: size=n_elements, each item contains the number of face of the corresponding element
	vset.ResizePfverts(mixed_ele_pfverts);

	vector<int64_t> neighbours;
	for ( size_t i = 0; i<n_elements; i++)
	{
		fpe = mixed_ele_pfverts[i];
		neighbours.resize(fpe, -1);
		pfverts.push_back(neighbours);
	}

	// pfvert: neighbor elements adjacent to the faces of each element
	// for each element contains for each face the neighbour element
	vset.AddPfverts(pfverts.begin(), pfverts.end());

	vector<std::int8_t> pbflags; // boundary type
  pbflags.reserve(n_vertices);
	for ( size_t i = 0ul; i<n_vertices; i++)
		pbflags.push_back(IRREGULAR_OUTSIDE);
	vset.AddBFlags(pbflags.begin(), pbflags.end());
	
	// vset.OutASCII("c:\\test\\test");

  model_topology.ModelName( filename );
	for ( const auto &pair : regions )
    {
       //cout << "\n\ttopology created for region: " << pair.first.c_str() << endl;
       model_topology.AddDomain( pair.first.c_str(), (*fem_types.find(pair.first.c_str())).second, pair.second );
    }
	//model_topology.Out();
  
  // fixing misnumbered elements
  RepairElementOrientations( vset );

//	Model<3U>(model_topology, vset, "compressible_flow-variables.txt", varbinaryfile);
}






/*

Model<3U>* IntrepidInterface::Read(const char* filename, const char* element_var) const
{
	string s;
	int dimension;

	map< string, std::set<std::string> > fem_types;
	map< string, vector<uint32_t> > regions; // key: name of the region, value: list of vertices
	vector<int> element_types;
	deque< vector< size_t> > elements;
	vector<int32_t> element_type;
	deque<uint32_t> mixed_ele_plist;      // number of nodes per element
	deque<uint32_t> mixed_ele_pfverts;    // number of neighbours per element
	std::deque<std::vector<int64_t> > pfverts; // neighbour elements

	VSet<3U> vset;

	size_t n_vertices = 0;
	size_t n_elements = 0;

	ifstream file(filename);
  string str("IntrepidInterface: ");
	if (!file.is_open()) throw invalid_argument(str + filename + " file not found");

	getline(file, s);

	file >> s >> dimension;
	if (dimension != 3) throw out_of_range(str + "dimension <> 3");

	file >> s;
	if (s != "Vertices") throw invalid_argument("bad file format");
	file >> n_vertices;
	if (n_vertices <= 0) throw logic_error("value not expected");

	vset.ResizeNodes(n_vertices);

	double px, py, pz;
	int unknown;
	for (int i = 0; i<n_vertices; i++)
	{
		file >> px >> py >> pz >> unknown;
		vset.Px(i, px);
		vset.Py(i, py);
		vset.Pz(i, pz);
	}

	size_t region, npe, fpe, n_elem, inode;
	string stype;
	int etype;
	int elem_idx = 0;
	while (true)
	{
		string fem_string;
		file >> stype;
		if (stype == "End") break;
		npe = 0; // nodes per element
		fpe = 0; // faces per element
		if (stype == "Triangles")  { npe = 3; fpe = 3; etype = ISOPARAMETRIC_LINEAR_TRIANGLE;  fem_string = "TRI_3"; }   
		if (stype == "Tetrahedra") { npe = 4; fpe = 4; etype = ISOPARAMETRIC_LINEAR_TETRAHEDRON; fem_string = "TETRA_4"; } 
		if (npe == 0) throw out_of_range(str + "number of nodes");
		element_types.push_back(etype);

		file >> n_elem;
		if (n_elem <= 0) throw out_of_range(str+"value not expected");
		n_elements += n_elem;

		vector<uint32_t> elem(npe);

		for (int i = 0; i<n_elem; i++)
		{
			for (int j = 0; j<npe; j++)
			{
				file >> inode;
				elem[j] = inode - 1; // intrepid files node index starts from 1 (apparently)
			}
			file >> region;

			std::stringstream region_name;
			region_name << "Region " << stype << " " << region;
			regions[region_name.str()].push_back(elem_idx);
			fem_types[region_name.str()].insert(fem_string);

			elements.push_back(elem);
			element_type.push_back(etype);
			mixed_ele_plist.push_back(npe);
			mixed_ele_pfverts.push_back(fpe);

			elem_idx++;
		}

	}
	file.close();

	// mixed_ele_plist: size=n_elements, each item contains the number of nodes of the corresponding element
	vset.ResizePlist(mixed_ele_plist);
	// plist: deque of vector<uint32_t>, one per element, vector contains idx of nodes of the elem
	vset.AddPlist(elements.begin(), elements.end());

	// element_types: deque of size_t, one per element, contains the type of the element (CSMP_FEM_TYPE)
	vset.AddElementTypes(element_type.begin(), element_type.end());


	// mixed_ele_pfverts: size=n_elements, each item contains the number of face of the corresponding element
	vset.ResizePfverts(mixed_ele_pfverts);

	vector<int64_t> neighbours;
	for (int i = 0; i<n_elements; i++)
	{
		size_t fpe = mixed_ele_pfverts[i];
		neighbours.resize(fpe, -1);
		pfverts.push_back(neighbours);
	}

	// pfvert: neighbor elements adjacent to the faces of each element
	// for each element contains for each face the neighbour element
	vset.AddPfverts(pfverts.begin(), pfverts.end());

	vector<std::int8_t> pbflags; // boundary type
  pbflags.reserve(n_vertices);
	vset.AddBFlags(pbflags.begin(), pbflags.end());
	
	// vset.OutASCII("c:\\test\\test");


	bool isoparametric = true;
	bool varbinaryfile = false;

	ModelTopology model_topology("Model", isoparametric);
	for (const auto &pair : regions)
	{
		//cout << "topology created  " << fem_types[pair.first] << endl;
		model_topology.AddDomain(pair.first.c_str(), fem_types[pair.first], pair.second);
	}

	// model_topology.Out("c:\\test\\model_topology.txt");

	cout << "creating model... " << endl;
	return new Model<3U>(model_topology, vset, "compressible_flow-variables.txt", varbinaryfile); 
}
*/




/**
    Constructing tetrahedra from the tetrahedral element specifications inside of the VSet
    this method determines by volume computation whether the node numbering is incorrect.
    If so, the node order is reverted.
*/
void IntrepidInterface::RepairElementOrientations( VSet<3U>& vset ) const
 {
     cout <<"nIntrepidInterface::RepairElementOrientations: checking the right-hand-rule numbering of the tetrahedral elements...\n";
     LinearTetrahedron tet;
     vector<uint32_t>  ids;
     size_t            repaired_elmts(0U);
   
     for ( size_t elmt=0ul; elmt<vset.Elements(); ++elmt )
       if ( vset.ElementType(elmt) == ISOPARAMETRIC_LINEAR_TETRAHEDRON )
         {
            // initialising a tetrahedral element
            tet.CurrentID(elmt);
            const uint32_t nodes(4U);
            for ( uint32_t node=0; node<nodes; ++node ) {
                 tet.XYZ( node, 0U, vset.Px( vset.Plist( elmt, node ) ) ); // X
                 tet.XYZ( node, 1U, vset.Py( vset.Plist( elmt, node ) ) ); // Y
                 tet.XYZ( node, 2U, vset.Pz( vset.Plist( elmt, node ) ) ); // Z
              }
         
            // detecting negative volumes and flipping the nodes in case
            if ( tet.Volume() < 0. ) {
                tet.CounterClockwiseNodes( ids );
                // reassigning the nodes to the plist in opposite order (first getting the global node numbers
                for ( auto it=ids.begin(); it!=ids.end(); ++it ) (*it) = vset.Plist( elmt, (*it) );
                size_t counter(0U);
                for ( auto nit=vset.PlistBegin(elmt); nit!=vset.PlistEnd(elmt); ++nit )
                  (*nit) = ids[counter++];
                repaired_elmts++;
              }
         }
   
    if ( repaired_elmts > 0 )
      cout <<"nIntrepidInterface::RepairElementOrientations: "<< repaired_elmts <<" were detected and renumbered.\n";
 
 } // end RepairElementOrientations






} // csmp
