//
//  Intrepid_Example.cpp
//  CSMP_API_library2014
//
//  Created by Stephan Matthai on 1/27/14.
//  Copyright (c) 2014 Stephan Matthai. All rights reserved.
//

#include "CSMP_definitions.h"
#include "Intrepid_Example.h"
#include "compareFloats.h"
#include "ANSYS_Model3D.h"
#include "ModelTopology.h"
#include "NumIntegral_dNT_op_dN_dV.h"
#include "NumIntegral_NT_op_N_dV.h"
#include "PDE_Integrator.h"
#include "Model.h"
#include "Boundary.h"

#include "NumIntegral_NT_op_N_dS.h"
#ifdef CSMP_WITH_SAMG_SOLVER
#include "SAMG_Solver.h"
#else
#include "LinearSolver.h"
#endif
#ifdef CSMP_WITH_MESCHACH
#include "LinearSolver.h"
#endif

#include "InputDataManager.h"
#include "VTK_Interface.h"
#include "VTU_Interface.h"
#include "IntrepidInterface.h"


// include any header files that you need here...

using namespace std;

namespace csmp {

void Intrepid_Example::Specifications()
{
   SetTitle( "Intrepid_Example" );
   SetDifficulty( 1 );
   SetCategory( "Software Interfaces" );
   AddAuthor( "Stephan Matthai" );
   AddDescription( "source in: Intrepid_Example.cpp" );
   AddDescription( "How to use input files generated by Geomodeller (FEM output)" );
   AddRequirement( "input files from GeoModeller (by default: Mansfield_H8_NoOrphans.mesh)" );
   AddRequirement( "Geomodeller_test-variables.txt" );
}


/** 
    This is the documentation format that can be read by DOxygen automatically.
*/
void Intrepid_Example::Run()
{
  // Model name
  string model_name;
  cout << "\nPlease enter the name of input model, or press ENTER to use the default model 'Mansfield_H8_NoOrphans':" << endl;
  cin.ignore();
  getline(cin, model_name);
  if (model_name.length() == 0) model_name = "Mansfield_H8_NoOrphans";

  // Load Model
  std::string variables_file("Geomodeller_test-variables.txt");

  // create a working directory with current example name, go into this directory, and copy input files into it.
  CopyInputFiles(model_name, variables_file);
 
  IntrepidInterface  geomodel;
  VSet<3U>           vset;
  ModelTopology      model_topology(true);
  string full_model_name = model_name + ".mesh";
  geomodel.Read( full_model_name.c_str(), vset, model_topology );
  
  Model<3U>  model(model_topology, vset, variables_file.c_str(), false );

  printModelDimensions( model, true );
  
  cout<<"\ncurrent model boundaries:\n";
  for ( BoundaryInterface<3U,Boundary>::boundaryConstIterator it=model.BoundariesBegin(); it!=model.BoundariesEnd(); it++ )
    cout <<"\n\t"<< (*it).first;
  
  cout<<"\ncurrent model regions:\n";
  for ( map<string,Region<3U> >::const_iterator it=model.UniqueRegionsBegin(); it!=model.UniqueRegionsEnd(); it++ )
    cout <<"\n\t"<< (*it).first;
  
  InputDataManager<3U>().ConfigureFromFile( model, model_name.c_str(),
                                            false, true, true, true, true, true );

  printRangeOfVariable(model, "thermal conductivity");
  VTK_Interface<3U>  vtk_output;
  vtk_output.OutputRegionByRegionToVTK( model, model_name, "element volume", 0., true );
  
#ifdef CSMP_WITH_SAMG_SOLVER
  SAMG_Solver solver;
#else
  CSMP_DEFAULT_LINEAR_SOLVER solver;
#endif
  PDE_Integrator<3U,Element>  heat_conductor(solver);

  NumIntegral_dNT_op_dN_dV<3U> conductance (model.Database(), "thermal conductivity", "temperature", "temperature");
  
  NumIntegral_NT_op_N_dV<3U>  heat_source( model.Database(), "heat source", "temperature" );
  
//  NumIntegral_NT_op_N_dS<3U,Face >  basal_hfu( model.Database(), "basal heat flow", "temperature" );
//  basal_hfu.LumpedFormulation();
  
  heat_conductor.Add( &conductance );
  heat_conductor.Add( &heat_source );
  // heat_conductor.AddBoundaryIntegrals( &basal_hfu );
  
  Region<3U>& region(model.Region("Model"));
  
  heat_conductor.IntegrateOver( region, false );
  
  printRangeOfVariable(model, "temperature");

  list<string>  output_variables;
  output_variables.push_back("temperature");
  output_variables.push_back("thermal conductivity");
//  output_variables.push_back("basal heat flow");
  
  VTU_Interface<3U> vtu_output( model );
  vtu_output.OutputDataToVTU( model_name.c_str(), output_variables, "Model", static_cast<int>(0) );

  cout <<"\nIntrepid_Example: That's it!\n";

  fs::current_path("../../example_inputs/");
  
} // end Run

  void Intrepid_Example::CopyInputFiles(std::string& model_name, std::string& variable_file) {
    //find the name of current example source file
    string example_name = GetExampleFileName(__FILE__);
    //create a working directory with the name of this example and go into it
    fs::create_directory("../example_outputs");
    fs::current_path("../example_outputs");
    if (fs::is_directory(example_name)) fs::remove_all(example_name); //if directory already exists, delete it
    fs::create_directory(example_name);
    fs::current_path(example_name);

    string input_directory = (fs::current_path().parent_path().parent_path()).string();
    input_directory += "/example_inputs/input_meshes/";

    //copy Eclipse model files into working directory
    string path = "../../example_inputs/input_meshes/";
    string name = model_name + ".mesh";
    string file_name = path + name;
    if (fs::exists(file_name)) fs::copy(file_name, "./");
    else {
      string error_message = "\n\nError: file '";
      error_message += (name + "' does not exist in directory " + input_directory);
      error_message += (", example cannot run, please copy this file into this directory\n");
      throw std::runtime_error(error_message);
    }

    //copy variable file into working directory
    input_directory = (fs::current_path().parent_path().parent_path()).string();
    input_directory += "/example_inputs/variables_and_configuration_files/";

    path = "../../example_inputs/variables_and_configuration_files/";
    file_name = path + variable_file;
    if (fs::exists(file_name)) fs::copy(file_name, "./");
    else {
      string error_message = "\n\nError: file '";
      error_message += (variable_file + "' does not exist in directory " + input_directory);
      error_message += (", example cannot run, please copy this file into this directory\n");
      throw std::runtime_error(error_message);
    }
  }

} // csmp
