#include "PressureDiffusion_Example.h"

#include "Region.h"
#include "Model.h"
#include "PDE_Integrator.h"
#include "PropertyAtPointVisitor.h"
#include "ConstantFactor.h"

// interfaces
#include "Standard_IO_Handler.h"
#include "VSetConverter.h"
#include "TRIANGLE_Interface.h"
#include "VTK_Interface.h"

// fluid pressure algorithm and velocity computation
#include "NumIntegral_NT_op_N_dV.h"
#include "NumIntegral_dNT_op_dN_dV.h"
#include "NumIntegral_NT_lhsop_N_dV.h"
#include "VelocityAndVolumeFlux.h"

// utilities
#include "CSMP_definitions.h"
#include "CSMP_highLevelUtilities.h"
#include "ModelTime.h"

using namespace std;

namespace csmp {

void PressureDiffusion_Example::Specifications()
{
   SetTitle( "Transient pressure diffusion in a rectangular domain" );
   SetDifficulty( 3 );
   SetCategory( "Simulation of Physical Processes" );
   AddAuthor( "SKM" );
   AddDescription( "2D transient calculation of fluid pressure distribution" );
   AddDescription( "isoparametric quadratic finite element formulation" );
   AddDescription( "source in: PresureDiffusion_Example.cpp" );
   AddRequirement( "file set: 'frac30.1'");
}



/** *****************************************************************************************

   (3) 2D transient calculation of fluid pressure distribution using a triangular element
       mesh generated by the program Triangle (file set: frac30.1).
       Quadratic finite element interpolation is used and Dirichlet essential conditions
       are applied. After computing an initial left-right fluid pressure gradient, 
       the pressure on the left is dropped to a low value and the response of the model 
       is computed in a time stepping loop.
 
       Use VTK example_viewer.tcl or Paraview to visualize vtk output.
 
       Exercise: Vary the fluid pressure and input different hydraulic diffusivity /
       storativity values to observe how these influence fluid pressure requilibratation.
 
      @todo  (3) Re-include surface integral for boundary fluxes into PDE_Integrator

   *****************************************************************************************
*/
void PressureDiffusion_Example::Run()
{
    double64& model_time( ModelTime::Instance().modelTime );
     cout<<"\n First Try (Hani) \n";
    // 1. Set up interface and mesh container needed to read in a 'Triangle' FE mesh
    // -----------------------------------------------------------------------------
    TRIANGLE_Interface  mesh_interface;
    VSet<2U>            mesh_container;


    // Read in the Triangle input file and convert them to triangles with
    // quadratic interpolation functions
    // ------------------------------------------------------------------
    char  file_name[200];
    cout <<"\nmain: Enter name of 'Triangle' input file set: ";
    cin >> file_name;
    mesh_interface.ReadTriangle2DMesh( file_name, mesh_container );

    // changing element type to numerically integrated one
    // (in this mono-element-type mesh there is just one type stored in entry 0)
    // (all element types are defined as enumeration in FiniteElement.h)
    mesh_container.ElementType( 0, ISOPARAMETRIC_LINEAR_TRIANGLE );

    Standard_IO_Handler stdio;
    if ( stdio.YesNo("main: Do you want to run this example with quadratic finite elements?") ) {
         // converter from linear- to quadratic finite elements
         VSetConverter<2U>  mesh_converter;
         mesh_converter.ConvertLinearToQuadraticTriangles( mesh_container );
         // notice that converter is destructed here at the end of this code block
      }


    // 2. Building model
    // boolean determines that isoparametric elements will be used
    // -----------------------------------------------------------
    const bool isoparametric(true);
    Model<2U>  model( mesh_container, "example3.txt", isoparametric );
    mesh_container.Erase();
    printModelDimensions( model, true );


    // 3.  Form a Group named "fracture"
    // ---------------------------------
    cout << "\nFORMING THE REGION FRACTURE: " << endl;
    model.FormRegionFrom( "fracture", "permeability", 1.0e-12, 1.0 );


    // 4.  Input the initial Conditions
    // --------------------------------
    model.InputPropertyValue( "permeability", 	     makeScalar(PLAIN,1.0e-13) );
    model.InputPropertyValue( "fluid volume source", makeScalar(PLAIN,0.0) );
    model.InputPropertyValue( "porosity",            makeScalar(PLAIN,0.2) );
    model.InputPropertyValue( "fluid pressure",      makeScalar(PLAIN,0.0) );

    // Change the porosity to 1 everywhere within region "fracture"
    model.Region("fracture").InputPropertyValue( "porosity", makeScalar(PLAIN,1.0) );
    model.Region("fracture").InputPropertyValue( "permeability", makeScalar(PLAIN,1.0e-11) );


    // 5.  Assign Dirichlet boundary conditions for the fluid pressure
    //     at the left and right boundary of the model
    // ---------------------------------------------------------------
    /// @todo SKM: to fix: method cannot handle element input variables
    //model.InputBoundaryValue( LEFT,  "influx", makeScalar(NEUMANN,1.0) );
    const double64 pressure_left(6.0e6); // create pressure drop of 50 bars/500 m
    const double64 pressure_right(1.0e6); // create pressure drop of 50 bars/500 m
    model.InputBoundaryValue( LEFT,  "fluid pressure", makeScalar(DIRICH,pressure_left) );
    model.InputBoundaryValue( RIGHT, "fluid pressure", makeScalar(DIRICH,pressure_right) );


    // 6.  Calculating hydraulic conductivity: 1e-3 / 1e-3 = 1.
    // --------------------------------------------------------
    const double64 fluid_viscosity(1.0e-03);
    ConstantFactor<2U,divides>  conductivity( model.Database(),
                                             "conductivity", "permeability",
                                              fluid_viscosity );
    model.Apply( conductivity );
    printRangeOfVariable( model, "conductivity" );


    // 7.  Building the steady-state FE Algorithm "fluid_pressure"
    // -----------------------------------------------------------
#ifdef CSMP_WITH_SAMG_SOLVER
    SAMG_Settings  settings;
    settings.Set_eps(0.);
    SAMG_Solver  samg_solver(&settings);
    PDE_Integrator<2U,Region>  fluid_pressure(samg_solver);
#else
    CSMP_DEFAULT_LINEAR_SOLVER  linear_solver;
    PDE_Integrator<2U,Region>  fluid_pressure(linear_solver);
#endif

    NumIntegral_dNT_op_dN_dV<2U,Element<2U> > conductance( model.Database(), "conductivity", "fluid pressure",  "fluid pressure" );
    NumIntegral_NT_op_N_dV<2U,Element<2U> >   source( model.Database(),  "fluid volume source", "fluid pressure" );
  /// @todo influx surface integral: NumIntegral_NT_op_N_dS<2U>   influx( model.Database(), "influx", "fluid pressure" );
    VelocityAndVolumeFlux<2U,Element<2U> >    velocity( model,  "conductivity", "porosity", "fluid pressure", false );

    // add PDE_Operators and post-processor to the FE Algorithm
    fluid_pressure.Add( &conductance );
    fluid_pressure.Add( &source );
  //  fluid_pressure.Add( &influx );
    fluid_pressure.AddPostProcess( &velocity );


    // 8.  Pass the FE algorithm to the Model and reset it after the solution
    // ----------------------------------------------------------------------
    model.Apply( fluid_pressure );


    // 9.  Output the initial range of the variables
    // ---------------------------------------------
    printRangeOfVariable( model, "fluid pressure" );
    printRangeOfVariable( model, "velocity" );
    printRangeOfVariable( model, "pore velocity" );
    printRangeOfVariable( model, "volume flux" );


    // 10.  Output the initial conditions to VTK
    // -----------------------------------------

    // VTK
    VTK_Interface<2U>  vtk_output;
    vtk_output.OutputDataToVTK( model, "fluid-pressure", "fluid pressure", 0, true );
    vtk_output.OutputDataToVTK( model, "velocity",       "velocity",       0, true );
    vtk_output.OutputDataToVTK( model, "volume-flux",    "volume flux",    0, true );


    // 11.  Let the user define the runtime and time increment for the transient calculation
    // -------------------------------------------------------------------------------------
    double64  maxtime, time_increment;
    size_t      timestep(1);

    printModelDimensions( model );
    cout << "\nEnter the run-time in seconds: "<< endl;
    cin  >> maxtime;
    cout << "\nEnter the time increment in seconds: "<< endl;
    cin  >> time_increment;

    // issue a warning if more than 100 timesteps are needed
    if ( rint(maxtime/time_increment) > 100 ) {
        cout << "\nWith the current time increment of " << time_increment << " you will need ";
        cout << rint(maxtime/time_increment) << " timesteps. " << endl;
        cout << "\nChange time increment to a larger value: " << endl;
        cin  >> time_increment;
      }
    else cout << "\nComputing " << rint(maxtime/time_increment) << " timesteps. "<< endl;


    // 12.  Let the user define storativity and change of the left-hand side fluid pressure
    //      and input the new storativity value and fluid pressure dirichlet boundary conditions
    // -----------------------------------------------------------------------------------------
    double64 storativity, pressure_change, new_pressure;
    cout << "\nEnter the storativity in m3 m-3 Pa-1 (physically meaningful values are in the range of 1.0e-06 to 1.0e-12): "<< endl;
    cin  >> storativity;
    // input the storativity to the Model
    model.InputPropertyValue( "storativity", makeScalar(PLAIN,storativity) );

    cout << "\nEnter the pressure change on the left side of the model in percent: "<< endl;
    cin  >> pressure_change;
    new_pressure = pressure_change * (pressure_left/100.);
    cout << "\nNew pressure on the left-hand side boundary is " << new_pressure << " Pa " << endl;
    // input the new righthand side 1=bar pressure boundary condition
    model.InputBoundaryValue( LEFT, "fluid pressure", makeScalar(PLAIN,new_pressure) );
    vtk_output.OutputDataToVTK( model, "fluid-pressure", "fluid pressure", 999, true );



    // 13.  Build a transient fluid pressure algorithm using Backward-Euler time-stepping
    //      that equates to: ([C] + dt[K]){p}t+dt = [C]{p}t + dt {Q}t+dt
    //                or
    //                       ([C]/dt + [K]){p}t+dt = [C]/dt {p}t + {Q}t+dt
    //
    //      the latter formulation is preferred because it reduces the error due to
    //      the lumping of the storativity matrices such that their contribution to
    //      the righthandside is equivalent to that in the lefthandside.
    // ------------------------------------------------------------------------------------
    // conductance matrix dt * [K] at pressure t+dt is already there

    // left-hand side capacitance matrix [C] at pressure d+dt
    NumIntegral_NT_lhsop_N_dV<2U,Element<2U> > capacitance_lhs( model.Database(),
                                               "storativity",  "fluid pressure", "fluid pressure" );
                                               capacitance_lhs.LumpedFormulation(true);
                                               capacitance_lhs.MultiplyWithTimeIncrement(true);

    // right-hand side capacitance matrix [C] at current pressure
    NumIntegral_NT_op_N_dV<2U,Element<2U> >    capacitance_rhs( model.Database(),
                                               "storativity",  "fluid pressure" );
                                               capacitance_rhs.LumpedFormulation(true);
                                               capacitance_rhs.MultiplyWithTimeIncrement(true);

    // source term at dt * {Q} at current pressure needs to be accumulated later
    source.AddAccumulateLater();
    source.LumpedFormulation(true);


    // add PDE_Operators and post-processor to the FE Algorithm
    // and multiply with time-increment
    fluid_pressure.Add( &conductance );
    fluid_pressure.Add( &capacitance_lhs );
    fluid_pressure.Add( &capacitance_rhs );
    fluid_pressure.Add( &source );
    fluid_pressure.AddPostProcess( &velocity );
    fluid_pressure.TimeIncrement( 1. / time_increment ); // see equation above



    // 14. Transient loop: Compute fluid pressure during each time-step and output the results for each time step
    // -----------------------------------------------------------------------------------------------------------
    // iout: for the transient loop, the screen output from SAMG solver is reduced
    #ifdef CSMP_WITH_SAMG_SOLVER
    settings.Set_iout1( 0 );
    settings.Set_iout2( 0 );
    settings.Set_idmp( -1 );
    #endif

    while ( model_time <= maxtime )
      {
        cout << "\n\nmain: COMPUTING TIMESTEP " << timestep << endl;

        // transient pressure
        model.Apply( fluid_pressure );

        // output variables to file and screen
        printRangeOfVariable( model, "fluid pressure" );
        printRangeOfVariable( model, "velocity" );
        printRangeOfVariable( model, "pore velocity" );
        printRangeOfVariable( model, "volume flux" );

        // VTK
        vtk_output.OutputDataToVTK( model, "fluid-pressure", "fluid pressure",    timestep );
        vtk_output.OutputDataToVTK( model, "velocity",       "velocity",          timestep);
        vtk_output.OutputDataToVTK( model, "volume-flux",    "volume flux",       timestep );

        // Preparing next Time Step
        model_time += time_increment;
        timestep++;

        cout << "\nmain: ELAPSED TIME " << model_time << " seconds." << endl;
     }

    cout <<"\nmain: That's it..."<< endl;
    
} // end Run

} // csmp
