#include "QuadraticPressure_parallelPlatePermeability_Example.h"

#include "Model.h"
#include "Region.h"
#include "PDE_Integrator.h"
#include "ConstantFactor.h"

// interfaces
#include "TRIANGLE_Interface.h"
#include "VSetConverter.h"
#include "VTK_Interface.h"

// fluid pressure algorithm and velocity computation
#include "NumIntegral_NT_op_N_dV.h"
#include "NumIntegral_dNT_op_dN_dV.h"
#include "VelocityAndVolumeFlux.h"

// utilities
#include "CSMP_definitions.h"
#include "CSMP_highLevelUtilities.h"
#include "parallelPlatePermeabilityFromChannelWidth.h"

using namespace std;

namespace csmp{

void QuadraticPressure_parallelPlatePermeability_Example::Specifications()
{
  SetTitle( "parallelPlatePermeabilityFromChannelWidth: fracture permeability, pressure and flow computed with quadratic FEM in 2D" );
  SetDifficulty( 2 );
  SetCategory( "Simulation of Physical Processes" );
  AddAuthor( "SKM" );
  AddDescription( "Two regions: FRACTURE and MATRIX, steady state pf and velo output to VTK" );
  AddDescription( "Quadratic finite element interpolation, Dirichlet essential conditions" );
  AddDescription( "Region saved to a binary vset, then a second Region is built from it" );
  AddDescription( "source in: QuadraticPressure_parallelPlatePermeability_Example.cpp" );
  AddRequirement( "file set: 'veins_20k.1'");
}





/** *****************************************************************************************
  
      2D calculation of steady-state fluid pressure distribution using triangular element
      meshes generated by program Triangle (file set: veins_20k.1).
      Quadratic finite elements are used and Dirichlet essential conditions
      are applied.
 
      Use Paraview (VTK) or Tcl/Tk 'example_viewer.tcl' to visualize output.
 
    *****************************************************************************************
*/
void QuadraticPressure_parallelPlatePermeability_Example::Run()
{
     // 1. Reader for Shewchuk's 'Triangle' FE meshes
    //     et up the converter that converts the linear input triangles to
    //     quadratic (6 nodes) traingular finite elements
    // -----------------------------------------------------------------------------
    TRIANGLE_Interface  mesh_interface;

    // reading of mesh and conversion into quadratic 6-noded triangular finite elements
    char  file_name[200] = {"veins_20k.1"};
    const bool isoparametric(true), extra_checks(true);
    VSet<2U>   mesh_container;
    mesh_interface.ReadTriangle2DMesh( file_name, mesh_container, isoparametric, extra_checks );
    VSetConverter<2U>().ConvertLinearToQuadraticTriangles( mesh_container );


    // 2. model construction using IsoarametricQuadraticTriangle elements
    // -------------------------------------------------------------------
    Model<2U>  model( mesh_container, "example2.txt" );
    mesh_container.Erase();
  

    // 3. Input of material properties and initial conditions
    // (the permeability is read in from the 'Triangle' input files)
    // -------------------------------------------------------------
    model.InputPropertyValue( "fluid volume source", makeScalar(PLAIN,0.0) );
    model.InputPropertyValue( "porosity",            makeScalar(PLAIN,0.1) );
    model.InputPropertyValue( "fluid pressure",      makeScalar(PLAIN,0.0) );


    // 4. Creation of regions named "matrix" and "fracture" from
    //    finite elements in specific permeability ranges
    // ---------------------------------------------------------------
    printRangeOfVariable( model, "permeability", true );
    cout << "\nFORMING THE REGION 'fracture': " << endl; // unique group = true
    model.FormRegionFrom( "fracture", "permeability", 1.0e-12, 1.0e-08, true );
    cout << "\nFORMING THE REGION 'matrix': " << endl;
    model.FormRegionFrom( "matrix", "permeability", 1.0e-16, 1.0e-14, true );

    // 4.1 Adjustment of porosity of "fracture" to 1.0 and "matrix" to 0.25
    // --------------------------------------------------------------------
    model.Region("fracture").InputPropertyValue( "porosity", makeScalar(PLAIN,1.0) );
    model.Region("matrix").InputPropertyValue( "porosity",   makeScalar(PLAIN,0.25) );


    // 4.2 Computing fracture permeability from the aperture
    //    (note that this works variably well depending on number of FEs that span across
    //     the fracture)
    // -------------------------------------------------------------------------------------
    parallelPlatePermeabilityFromChannelWidth( model, "fracture", "aperture" );
    printRangeOfVariable( model, "permeability" );


    // 5. Dirichlet essential (boundary( conditions for the fluid pressure
    //   (these are the integration constants to find unique solution of PDE)
    // ----------------------------------------------------------------------
    model.InputBoundaryValue( LEFT,  "fluid pressure", makeScalar(DIRICH,1.0e+4) );
    model.InputBoundaryValue( RIGHT, "fluid pressure", makeScalar(DIRICH,1.0e+0) );


    // 6. Calculating hydraulic conductivity from permeability using Interrelation subclass
    // ------------------------------------------------------------------------------------
    const double fluid_viscosity(1.0e-03);
    ConstantFactor<2U,divides>  conductivity( model.Database(),
                                             "conductivity", "permeability",
                                              fluid_viscosity );
    model.Apply( conductivity );
    printRangeOfVariable( model, "conductivity" );


    // 7. Building the FE Algorithm "total_pressure_quadratic" by applying the PDE_Operator
    //    subclasses such that the Algorithm equates to [K]{p} = {Q}
    //    A post processing operation is added to compute the fluid velocities and
    //    fluid fluxes (by setting the boolean variable in the constructor of the post-
    //    processor to true, the element velocities are averaged to the nodes)
    // --------------------------------------------------------------------------------------
#ifdef CSMP_WITH_SAMG_SOLVER
    SAMG_Settings  settings; // all settings according to Klaus
    settings.Set_ncgtyp(5);
    settings.Set_nxtyp(0);
    settings.Set_ndefault(40);
    SAMG_Solver  samg_solver(&settings);

    PDE_Integrator<2U,Region>  total_pressure_quadratic(samg_solver);
#else
    CSMP_DEFAULT_LINEAR_SOLVER  linear_solver;
    PDE_Integrator<2U,Region>  total_pressure_quadratic(linear_solver);
#endif

    // conductance matrix [K] on the left-hand side
    NumIntegral_dNT_op_dN_dV<2U,Element<2U> > conductance( model.Database(),"conductivity","fluid pressure","fluid pressure" );
    // source vector {Q} on the right-hand side
    NumIntegral_NT_op_N_dV<2U,Element<2U> >   source( model.Database(),"fluid volume source","fluid pressure" );
    // post-processing operation to compute flow velocities
    VelocityAndVolumeFlux<2U,Element<2U> >    velocity( model, "conductivity","porosity","fluid pressure", true );

    // add PDE_Operators to the FE Algorithm
    total_pressure_quadratic.Add( &conductance );
    total_pressure_quadratic.Add( &source );
    // add post-process to the FE Algorithm
    total_pressure_quadratic.AddPostProcess( &velocity );


    // 8.0 Pass the FE algorithm to the Region and solve [K]{p} = {Q}
    // --------------------------------------------------------------------
    model.Apply( total_pressure_quadratic );


    // 9.0 Output the range of the variables "fluid pressure", "velocity",
    //    "pore velocity", and "volume flux"
    // -------------------------------------------------------------------
    printRangeOfVariable( model, "fluid pressure" );
    printRangeOfVariable( model, "velocity" );
    printRangeOfVariable( model, "pore velocity" );
    printRangeOfVariable( model, "volume flux" );
    printRangeOfVariable( model, "conductivity" );


    // 10.0 Output the results to VTK and JPG files
    // --------------------------------------------
    VTK_Interface<2U>  vtk_output;

    // VTK output
    vtk_output.OutputDataToVTK( model, "permeability",   "permeability",      0 );
    vtk_output.OutputDataToVTK( model, "fluid-pressure", "fluid pressure",    0 );
    vtk_output.OutputDataToVTK( model, "velocity",       "velocity",          0 );
    vtk_output.OutputDataToVTK( model, "nvelocity",      "nodal velocity",    0 );
    vtk_output.OutputDataToVTK( model, "volume-flux",    "volume flux",       0 );
    vtk_output.OutputDataToVTK( model, "nvolume-flux",   "nodal volume flux", 0 );

} // end Run

} // csmp
