//
//  SKUA_Example.cpp
//  CSMP_API_library2022
//
//  Created by Anlor Tertois on 2022-02-15.
//  Copyright (c) 2014 Stephan Matthai. All rights reserved.
//

#include "CSMP_definitions.h"
#include "SKUA_Example.h"
#include "ModelTopology.h"
#include "GaussJordan_Solver.h"

#include "Boundary.h"
#include "Model.h"
#include "Region.h"
#include "VSet.h"

#include "TextFileIO.h"

#include <filesystem>

using namespace std;

namespace fs = std::filesystem;

namespace csmp {

void SKUA_Example::Specifications()
{
   SetTitle( "SKUA_Example" );
   SetDifficulty( 1 );
   SetCategory( "Software Functionality" );
   AddAuthor( "Anlor Tertois" );
   AddDescription( "source in: SKUA_Example.cpp" );
   AddDescription( "How to use input files generated by SKUA" );
   AddRequirement( "input files from SKUA" );
}


void SKUA_Example::Run()
{
  string input;
  do{
      cout << endl << "Please enter model name, 'q' to exit or anything else to list available models: ";
      cin >> input;
      if( input == string( "q" ) || input == string( "Q" ) ) {
          return;
      }
      if( !fs::exists( input ) ) {
          ListModels();
          continue;
      }
      break;
  } while( true );

  // Read VSet binary file generated by SKUA
  VSet<3U> vset;
  double time = 0.0;
  vset.InputFrom( input.c_str(), time );

  // Read ModelTopology file generated by SKUA
  ModelTopology model_topology(true);
  model_topology.InputFromTextFile( input.c_str() );
  
  // Build Model using variables file generated by SKUA
  const string variables_file = input + "-variables.txt";
  Model<3U>  model( model_topology, vset, variables_file.c_str(), false );

  // Checks...
  printModelDimensions( model, true );
  
  cout<<"\ncurrent model boundaries:\n";
  for ( BoundaryInterface<3U,Boundary>::boundaryConstIterator it=model.BoundariesBegin(); it!=model.BoundariesEnd(); it++ )
    cout <<"\n\t"<< (*it).first;
  
  cout<<"\ncurrent model regions:\n";
  for ( map<string,Region<3U> >::const_iterator it=model.UniqueRegionsBegin(); it!=model.UniqueRegionsEnd(); it++ )
    cout <<"\n\t"<< (*it).first;
  
  cout <<"\nSKUA_Example: That's it!\n";
  
} // end Run

void SKUA_Example::ListModels() {
    fs::path cur_dir = fs::current_path();
    cout << endl << "Searching for SKUA models in " << cur_dir.string() << endl;

    for( const fs::directory_entry& dir_entry : fs::directory_iterator{ cur_dir } ) {
        if( !dir_entry.is_regular_file() && !dir_entry.is_symlink() ) {
            continue;
        }
        string filename = dir_entry.path().filename().string();
        if(
            filename.find( string( "SKUA" ) ) == string::npos &&
            filename.find( string( "skua" ) ) == string::npos
        ) {
            continue;
        }
        if( filename.rfind( string( "asc" ) ) != filename.length() - 3 ) {
            continue;
        }
        cout << endl << "'" << dir_entry.path().stem().string() << "'" << endl;

        ifstream ifs( filename.c_str() );

        if( !ifs.is_open() ) {
            cout << "Failed to read file " << filename << endl;
            continue;
        }

        char text_line[NAME_STRING];

        do {
            ifs.getline( text_line, 256 );
            string text_str( text_line );
            if( text_str.find( string( "ModelTopology::Out" ) ) == 0 ) {
                break;
            }
            text_str.insert( 0, 2, ' ' );
            cout << text_str << endl;
        } while ( (isCommentLine(text_line) && !ifs.eof()) );

    }
}

} // namespace csmp

