//
//  SKUA_Example.cpp
//  CSMP_API_library2022
//
//  Created by Anlor Tertois on 2022-02-15.
//  Copyright (c) 2014 Stephan Matthai. All rights reserved.
//

#include "CSMP_definitions.h"
#include "SKUA_Example.h"
#include "ModelTopology.h"
#include "GaussJordan_Solver.h"

#include "Boundary.h"
#include "Model.h"
#include "Region.h"
#include "VSet.h"

using namespace std;

namespace csmp {

void SKUA_Example::Specifications()
{
   SetTitle( "SKUA_Example" );
   SetDifficulty( 1 );
   SetCategory( "Software Functionality" );
   AddAuthor( "Anlor Tertois" );
   AddDescription( "source in: SKUA_Example.cpp" );
   AddDescription( "How to use input files generated by SKUA" );
   AddRequirement( "input files from SKUA" );
}


void SKUA_Example::Run()
{
  std::string model_name( "box_75");
  cout<< "\nPlease input model name: ";
  cin >> model_name;
 
  // Read VSet binary file generated by SKUA
  VSet<3U> vset;
  double time = 0.0;
  vset.InputFrom( model_name.c_str(), time );

  // Read ModelTopology file generated by SKUA
  ModelTopology model_topology(true);
  model_topology.InputFromTextFile( model_name.c_str() );
  
  // Build Model using variables file generated by SKUA
  const string variables_file = model_name + "-variables.txt";
  Model<3U>  model( model_topology, vset, variables_file.c_str(), false );

  // Checks...
  printModelDimensions( model, true );
  
  cout<<"\ncurrent model boundaries:\n";
  for ( BoundaryInterface<3U,Boundary>::boundaryConstIterator it=model.BoundariesBegin(); it!=model.BoundariesEnd(); it++ )
    cout <<"\n\t"<< (*it).first;
  
  cout<<"\ncurrent model regions:\n";
  for ( map<string,Region<3U> >::const_iterator it=model.UniqueRegionsBegin(); it!=model.UniqueRegionsEnd(); it++ )
    cout <<"\n\t"<< (*it).first;
  
  cout <<"\nSKUA_Example: That's it!\n";
  
} // end Run

} // namespace csmp

