#include "SteadyStatePressureToVset_Example.h"

#include "Model.h"
#include "ModelTopology.h"
#include "Region.h"
#include "PDE_Integrator.h"
#include "ConstantFactor.h"

// interfaces
#include "ANSYS_Interface.h"
#include "TRIANGLE_Interface.h"
#include "VSetConverter.h"
#include "VTK_Interface.h"

// fluid pressure algorithm and velocity computation
#include "NumIntegral_NT_op_N_dV.h"
#include "NumIntegral_dNT_op_dN_dV.h"
#include "VelocityAndVolumeFlux.h"

// utilities
#include "CSMP_definitions.h"
#include "CSMP_highLevelUtilities.h"
#include "parallelPlatePermeabilityFromChannelWidth.h"
#include "ModelTime.h"
#include "StatisticalAnalyzer.h"

using namespace std;

namespace csmp {

void SteadyStatePressureToVset_Example::Specifications()
{
  SetTitle( "Parallel-plate-fracture permeability and fluid pressure distribution" );
  SetDifficulty( 3 );
  SetCategory( "Simulation of Physical Processes" );
  AddAuthor( "SKM" );
  AddDescription( "Quadratic finite element interpolation, Dirichlet essential conditions" );
  AddDescription( "Model then gets saved to a binary file, and then rebuilt from it" );
  AddDescription( "source in: SteadyStatePressureToVset_Example.cpp" );
  AddRequirement( "file set: 'veins_20k.1'");
}


/** *****************************************************************************************
 
   2D steady-state calculation of parallel-plate permeability in a fracture set that
   is represented by a surface mesh.
   Subsequently, fluid pressure distribution is computed using a quadratic finite-element
   approximation. Dirichlet essential conditions
   are applied at left and right boundaries.

   Later, the model is saved to a binary file and a new model
   is built from the vset file. The Dirichlet pressure boundary conditions
   are changed, the pressure is recomputed and the results are written to file

   Use input mesh file set: veins_20k.1 as generated by program Triangle.

   You can use either Paraview of the TCL/TK viewer 'example_viewer.tcl' to visualize output.
   
   @todo SKM:  REWRITE: simplify the example to VSet operations: input and output only

***************************************************************************************** */
void SteadyStatePressureToVset_Example::Run()
{
    cout<< "\nSteadyStatePressureToVset_Example::Run: 2D Steady-state fluid pressure distribution in a fractured rock."<< endl;
    cout<< "\n\tUse input mesh from Triangle (1)='veins_20k.1' or ANSYS (2)=any model with a region called 'fractures'?  ";
    int option1(1);
    cin >> option1;
    char  file_name[200];
    cout <<"\n\tEnter name of input file set: ";
    cin >> file_name;
    const bool isoparametric(true), extra_checks(true);
  
    cout <<"\n\tChoose either a linear (1) or quadratic (2) finite element approximation: ";
    int option2(1);
    cin >> option2;

    // 1.0 Set up the storage containers to read in a 'Triangle' Finite Element Mesh
    //     Also set up the converter that converts the linear input triangles to
    //     quadratic (6 nodes) traingular finite elements
    // -----------------------------------------------------------------------------
    VSet<2U>       mesh_container;
    ModelTopology  mesh_topology(isoparametric);
    Model<2U>*     model(0);
  
    // 1.1 Now read in a Triangle or ANSYS input mesh and convert linear triangles
    //     into ones with quadratic interpolation functions if so requested
    // --------------------------------------------------------------------------
    if ( option1 == 1 ) {
         TRIANGLE_Interface  mesh_interface;
         mesh_interface.ReadTriangle2DMesh( file_name, mesh_container, isoparametric, extra_checks );
         if ( option2 == 2 ) VSetConverter<2U>().ConvertLinearToQuadraticTriangles( mesh_container );
         model = new Model<2U>( mesh_container, "example2.txt" );
      }
    // or else use an ANSYS mesh
    else {
         ANSYS_Interface  mesh_interface(isoparametric);
         const bool binary_file( true );
         mesh_interface.Read_ANSYS_Mesh( file_name, mesh_container, mesh_topology, binary_file, true );
      mesh_topology.ReduceToDomains( file_name );
         map<size_t,size_t>  old_and_new_elmtids;
         mesh_topology.CreateNewCellNumbers( old_and_new_elmtids );
         mesh_container.ReduceTo( old_and_new_elmtids );
         old_and_new_elmtids.clear();
         // optional: scaling the model to a target size
         // mesh_container.ScaleCoordinateToRange( 'x', 0., 0.005 );
         // mesh_container.ScaleCoordinateToRange( 'y', 0., 0.007 );
         if ( option2 == 2 ) VSetConverter<2U>().ConvertLinearToQuadraticTriangles( mesh_container );
         model = new Model<2U>( mesh_topology, mesh_container, "example2.txt", true );
      }
    mesh_container.Erase();
  
    printModelDimensions( *model );
  

    // 2. Input the initial Conditions (the permeability is read in
    //    from the 'Triangle' input files)
    // -------------------------------------------------------------
    model->InputPropertyValue( "fluid volume source", makeScalar(PLAIN,0.0) );
    model->InputPropertyValue( "porosity",            makeScalar(PLAIN,0.1) );
    model->InputPropertyValue( "fluid pressure",      makeScalar(PLAIN,0.0) );


    // 3. Triangle input: Form a region named "fractures" from high permeability
    //    finite elements in permeability range 1.0e-12 to
    //     1.0e-08 m2
    // -----------------------------------------------------
    if ( option1 == 1 ) {
         printRangeOfVariable( *model, "permeability", true );
         cout << "\nFORMING THE REGION 'fractures': " << endl; // unique region = true
         model->FormRegionFrom( "fractures", "permeability", 1.0e-12, 1.0e-08, true );
         cout << "\nFORMING THE REGION 'matrix': " << endl;
         model->FormRegionFrom( "matrix", "permeability", 1.0e-16, 1.0e-14, true );
      }

    // Changing porosity to 1.0 in region "fractures" and 0.25 in "matrix"
    model->Region("fractures").InputPropertyValue( "porosity",  makeScalar(PLAIN,1.0) );
    model->Region("matrix").InputPropertyValue( "porosity",     makeScalar(PLAIN,0.25) );
    model->Region("matrix").InputPropertyValue( "permeability",  makeScalar(PLAIN,1.0e-14) );


    // 4. Computing the fracture permeability from the aperture
    //   (note that this works variably well depending on the number of FE that span across
    //    the fractures)
    // -------------------------------------------------------------------------------------
    const double minimum_channel_width( 1.0e-6 ); // one micrometer
    parallelPlatePermeabilityFromChannelWidth( *model, "fractures", "aperture", minimum_channel_width );
    printRangeOfVariable( *model, "permeability" );


    // 5.  Assign Dirichlet boundary conditions for the fluid pressure
    //     at the left and right boundary of the model
    // ---------------------------------------------------------------
    model->InputBoundaryValue( LEFT,  "fluid pressure", makeScalar(DIRICH,1.01e+5) );
    model->InputBoundaryValue( RIGHT, "fluid pressure", makeScalar(DIRICH,1.00e+5) );


    // 6. Calculating hydraulic conductivity from permeability using Interrelation subclass
    // ------------------------------------------------------------------------------------
    const double fluid_viscosity(1.0e-03);
    ConstantFactor<2U,divides>  conductivity( model->Database(),
                                             "conductivity", "permeability",
                                              fluid_viscosity );
    model->Apply( conductivity );
    printRangeOfVariable( *model, "conductivity" );


    // 10. Output the boundary conditions and initial values to VTK
    // ------------------------------------------------------------
    VTK_Interface<2U>  vtk_output;

    // VTK output
    vtk_output.OutputDataToVTK( *model, "permeability",   "permeability",   0 );
    vtk_output.OutputDataToVTK( *model, "fluid-pressure", "fluid pressure", 0 );


    // 7.  Building the PDE Integrator "total_pressure_quadratic" adding PDE_Operator
    //     subclasses such that the Algorithm equates to [K]{p} = {Q}
    //     A post processing operation is added to compute fluid velocities and
    //     fluxes (by setting the boolean variable in the constructor of the post-
    //     processor to true, the element velocities are averaged to the nodes)
    // --------------------------------------------------------------------------------------
#ifdef CSMP_WITH_SAMG_SOLVER
    SAMG_Solver                samg_solver;
    PDE_Integrator<2U,Region>  total_pressure_quadratic(samg_solver);
#else
    CSMP_DEFAULT_LINEAR_SOLVER  linear_solver;
    PDE_Integrator<2U,Region>  total_pressure_quadratic(linear_solver);
#endif

    // conductance matrix [K] on the left-hand side
    NumIntegral_dNT_op_dN_dV<2U,Element<2U> > conductance( model->Database(),"conductivity","fluid pressure","fluid pressure" );
    // source vector {Q} on the right-hand side
    NumIntegral_NT_op_N_dV<2U,Element<2U> >   source( model->Database(),"fluid volume source","fluid pressure" );
    // post-processing operation to compute flow velocities
    VelocityAndVolumeFlux<2U,Element<2U> >    velocity( *model, "conductivity","porosity","fluid pressure", false );

    // add PDE_Operators to the FE Algorithm
    total_pressure_quadratic.Add( &conductance );
    total_pressure_quadratic.Add( &source );
    // add post-process to the FE Algorithm
    total_pressure_quadratic.AddPostProcess( &velocity );


    // 8. Pass the FE algorithm to the Region and solve [K]{p} = {Q}
    // --------------------------------------------------------------------
    model->Apply( total_pressure_quadratic );
    model->ExtrapolateElementToNodeProperty("velocity", "nodal velocity");


    // 9. Output the range of the variables "fluid pressure", "velocity",
    //    "pore velocity", and "volume flux"
    // -------------------------------------------------------------------
    printRangeOfVariable( *model, "fluid pressure" );
    printRangeOfVariable( *model, "velocity" );
    printRangeOfVariable( *model, "nodal velocity" );
    printRangeOfVariable( *model, "pore velocity" );
    printRangeOfVariable( *model, "volume flux" );
    printRangeOfVariable( *model, "conductivity" );


    // 10. Output the results to VTK and JPG files
    // --------------------------------------------
    vtk_output.OutputDataToVTK( *model, "fluid-pressure", "fluid pressure",    1 );
    vtk_output.OutputDataToVTK( *model, "velocity",       "velocity",          1 );
    vtk_output.OutputDataToVTK( *model, "nvelocity",      "nodal velocity",    1 );
    vtk_output.OutputDataToVTK( *model, "volume-flux",    "volume flux",       1 );


    // 11. Write the entire model to a CSMP binary VSet file
    // ------------------------------------------------------
    double& model_time( ModelTime::Instance().modelTime );
    VSet<2U> saved_model, input_model;
    cout << "\nSaving model to VSet... " << endl;
    model->Region("Model").OutputTo( saved_model );
    saved_model.OutputTo( "example2", model_time=1. );


    // 12. Read in VSet file and build a second Region named 'example1_from_vset'
    // ---------------------------------------------------------------------------
    input_model.InputFrom( "example2", model_time );
    Model<2U>  model_from_vset( input_model, "example2.txt" );


    // 13. Change Dirichlet boundary condition on the left side and assing pressure
    //     that varies linearly from 1.0e+02 to 1.0e+05
    // ---------------------------------------------------------------------------
    model_from_vset.InputBoundaryValue( LEFT, "fluid pressure", makeScalar(DIRICH,1.0e+5) );


    // 14. Reuse the fluid pressure algorithm and compute new fluid pressure
    //     for new Region, then reset algorithm
    // ----------------------------------------------------------------------
    model_from_vset.Apply( total_pressure_quadratic );


    // 15. Output the range of the variables "fluid pressure", "velocity",
    //     "pore velocity", and "volume flux" for new Region
    // --------------------------------------------------------------------
    printRangeOfVariable( model_from_vset, "fluid pressure" );
    printRangeOfVariable( model_from_vset, "velocity" );
    model_from_vset.ExtrapolateElementToNodeProperty("velocity", "nodal velocity");
    printRangeOfVariable( model_from_vset, "nodal velocity" );
    printRangeOfVariable( model_from_vset, "pore velocity" );
    printRangeOfVariable( model_from_vset, "volume flux" );
    printRangeOfVariable( model_from_vset, "conductivity" );


    // 16. Output the results of new Region to VTK and CSMP binary formats
    // --------------------------------------------------------------------
    // VTK output
    vtk_output.OutputDataToVTK( model_from_vset, "fluid-pressure", "fluid pressure", 2 );
    vtk_output.OutputDataToVTK( model_from_vset, "velocity",       "velocity",       2 );
    vtk_output.OutputDataToVTK( model_from_vset, "nvelocity",      "nodal velocity", 2 );
    vtk_output.OutputDataToVTK( model_from_vset, "volume-flux",    "volume flux",    2 );


    // 17. Analysis of results using StatisticalAnalyzer
    // ------------------------------------------------------------------------------------
    StatisticalAnalyzer<2U>                  flux_histogram( *model );
    HistogramBins                            bins;
    map<string,pair<HistogramBins,size_t> >  results;

    flux_histogram.DefineBins( "flux_histogram.bins", bins );
    flux_histogram.RegionPropertyHistograms( "volume flux", bins, results );
    const bool  take_log10_of_data(true);
    flux_histogram.OutputRegionPropertyHistogramsMaple( "volume flux", bins,
                                                         results, take_log10_of_data );
    cout <<"\nExample: That's it..."<< endl;
    delete model;

} // end Run

} // csmp
