#include "Triangulator_Example.h"

// inclusion of class declarations necessary for this simulation
#include "CSMP_definitions.h"

// main library
#include "Model.h"
#include "Region.h"
#include "TextInterface.h"
#include "CSMP_highLevelUtilities.h"
#include "convertColorToPermeability.h"
#include "PropertyAtPointVisitor.h"

// pde operator library
#include "Integral_NT_op_N_dV.h"
#include "Integral_dNT_op_dN_dV.h"
#include "VelocityAndVolumeFlux.h"

// algebraic multigrid solvers
#include "PDE_Integrator.h"
#include "LinearSolver.h"
#include "Matrix.h"

// interrelations library
#include "ConstantFactor.h"

// interface library
#include "Triangulator.h"
#include "JPEG_Interface.h"
#include "VTK_Interface.h"
#include "TextInterface.h"

#ifdef DEBUG
#ifdef CSMP_WITH_IMAGE_OUTPUT   // there is a memory bug in the JPEG library that is picked up by address sanitizer (left-shift of negative value)
#undef CSMP_WITH_IMAGE_OUTPUT   // not commented out when running in release mode
#endif
#endif

using namespace std;

namespace csmp {

void Triangulator_Example::Specifications()
{
  SetTitle( "Triangulator based meshing of image files" );
  SetDifficulty( 1 );
  SetCategory( "Software Interfaces" );
  AddAuthor( "SKM" );
  AddDescription( "Uses Triangular to make 2D triangular FE mesh from color-coded image in text file");
  AddDescription( "Perform steady-state fluid pressure computation on mesh" );
  AddDescription( "source file in: Triangulator_Example" );
  AddRequirement( "image(granite_model1), configuration(example1.txt)" );
}





/** 

2D steady-state calculation of fluid pressure distribution using structured triangular
element meshes generated by CSMP's Triangulator from color-coded bitmaps.
Linear finite element interpolation is used and Dirichlet essential conditions  are applied.

To learn how to create text matrices from the 256-color coded images, read User Guide,
Chapter 6 (input and output from CSMP).

@note Build your own model or use 'granite_model1' as input geometry (needs fast solver)

@code
// undefined to avoid  a memory overwrite problem in the legacy JPEG library
#ifdef CSMP_WITH_IMAGE_OUTPUT
#undef CSMP_WITH_IMAGE_OUTPUT
#endif
@endcode

*/
void Triangulator_Example::Run()
{
  // 0. Building a triangular element mesh from a pixelated image
  // ------------------------------------------------------------
  cout <<"\nmain: Please specify 256-color-coded geometry input file (text): ";
  string model_name;
  cin >> model_name;

  // 0.1 Reading a pixelated permeability image ASCII file into the
  //    new Matrix 'pixelcolors'
  size_t m, n;
  TextInterface().SizeofPixelTextImage256( model_name.c_str(), m, n );
  cout <<"\nmain: The size (in pixels) of the input image is: "<< n <<"h x "<< m;
  cout <<"v"<< endl;
  Matrix  pixelcolors(m,n);
  TextInterface().ReadPixelTextImage256( model_name.c_str(), pixelcolors );

  // 0.2 Converting the 256-color values into permeabilities
  convertColorToPermeability( 1., pixelcolors );

  // 0.3 Building a 2d mesh of triangular elements, incorporating the
  //    permeability data and the boundary conditions. The mesh is
  //    stored in the VSet object 'vset'
  VSet<2U>  vset;
  Triangulator().TrianglesFromRegularGrid( pixelcolors, vset );

  // 0.4 Scaling the geometrical input object that will become the Region
  //    The origin of the object is assumed to be zero.
  cout <<"\nmain: Enter the horizontal and vertical dimensions that you want to scale the model to (m): ";
  double extent1, extent2;
  cin >> extent1 >> extent2;
  double zero(0.);
  vset.ScaleCoordinateToRange( 'x', zero, extent1 );
  vset.CoordinateRange( 'x', zero, extent1 );
  cout <<"\nAssigned X range: "<< zero <<" to "<< extent1 << " meter." << endl;
  vset.ScaleCoordinateToRange( 'y', zero, extent2 );
  vset.CoordinateRange( 'y', zero, extent2 );
  cout <<"\nAssigned Y range: "<< zero <<" to "<< extent2 << " meter." << endl;

  // 1. A Region named "model" is built
  //    from a mesh based on a color coded image
  // -------------------------------------------
   Model<2U>  model( vset, "example1.txt" );
   vset.Erase();
   stripDomainEdgesFor( model, "permeability" );

  // 2. Assignment of material properties & initial conditions
  // ---------------------------------------------------------
  model.InputPropertyValue( "porosity",            makeScalar(PLAIN,0.1) );
  model.InputPropertyValue( "fluid volume source", makeScalar(PLAIN,0.0) );
  model.InputPropertyValue( "fluid pressure",      makeScalar(PLAIN,0.0) );

  // 3. Assignment of Dirichlet fluid pressure conditions
  //    at top and bottom boundary of the model
  // ---------------------------------------------------------------
  model.InputBoundaryValue( TOP,    "fluid pressure", makeScalar(DIRICH,1.0e+5) );
  model.InputBoundaryValue( BOTTOM, "fluid pressure", makeScalar(DIRICH,1.0e+7) );

  // 4. Calculation of hydraulic conductivity from permeability using Interrelation subclass
  // ---------------------------------------------------------------------------------------
  //  model.OutputVariableToScreen("permeability");
  const double fluid_viscosity(1.0e-03);
  ConstantFactor<2U,divides>  conductivity( model.Database(),
                                           "conductivity", "permeability",
                                            fluid_viscosity );
  model.Apply( conductivity );
  printRangeOfVariable( model, "conductivity" );

  // 5. Output results to VTK, ASCII Text, and JPEG binary files
  // -----------------------------------------------------------
  VTK_Interface<2U>  vtk_output;

  vtk_output.OutputDataToVTK( model, "fluid-pressure", "fluid pressure", 0 );
  vtk_output.OutputDataToVTK( model, "conductivity", "conductivity",     0 );

  TextInterface text_output;

  text_output.OutputDataAsTextColumnsNumbered( model, "fluid-pressure", "fluid pressure" );
  text_output.OutputDataAsTextColumnsNumbered( model, "conductivity", "conductivity" );

#ifdef CSMP_WITH_IMAGE_OUTPUT
  JPEG_Interface jpg_output;
// undefined behaviour caused here!
  jpg_output.OutputDataToJPG( model, "conductivity", "conductivity", 0 );
#endif

  // 6. Building PDE_Integrator "total_pressure" by applying the PDE operator subclasses
  //    A post processing operation is added to compute the fluid velocities and
  //    fluid fluxes (by setting the boolean variable in the constructor of the post-
  //    processor to true, the element velocities are averaged to the nodes)
  // --------------------------------------------------------------------------------------
#ifdef CSMP_WITH_SAMG_SOLVER
  SAMG_Settings  settings;  settings.Set_iout1(2);
  SAMG_Solver    samg_solver(&settings);

  PDE_Integrator<2U,Element>  total_pressure(samg_solver);
#else
  CSMP_DEFAULT_LINEAR_SOLVER  linear_solver;
  PDE_Integrator<2U,Element>  total_pressure(linear_solver);
#endif

  // conductance matrix [K] on the left-hand side
  Integral_dNT_op_dN_dV<2U>    conductance( model.Database(), "conductivity", "fluid pressure",  "fluid pressure" );
  // source vector {Q} on the right-hand side
  Integral_NT_op_N_dV<2U>      source( model.Database(),  "fluid volume source", "fluid pressure" );
  // post-processing operation to compute flow velocities
  const bool interpolate_values_to_nodes(true);
  VelocityAndVolumeFlux<2U>    velocity( model,  "conductivity", "porosity", "fluid pressure", interpolate_values_to_nodes );

  // add PDE_Operators to the FE Algorithm
  total_pressure.Add( &conductance );
  total_pressure.Add( &source );
  // add post-process to the FE Algorithm
  total_pressure.AddPostProcess( &velocity );

  // Solve [K]{p} = {Q} by passing the algorithm to the model
  model.Apply( total_pressure );


  // 7. Screen ranges of computed variables
  // --------------------------------------
  printRangeOfVariable( model, "fluid pressure" );
  printRangeOfVariable( model, "velocity" );
  printRangeOfVariable( model, "pore velocity" );
  printRangeOfVariable( model, "volume flux" );
  printRangeOfVariable( model, "nodal volume flux" );

  // VTK output
  vtk_output.OutputDataToVTK( model, "fluid-pressure", "fluid pressure",    0 );
  vtk_output.OutputDataToVTK( model, "velocity",       "velocity",          0 );
  vtk_output.OutputDataToVTK( model, "nvelocity",      "nodal velocity",    0 );
  vtk_output.OutputDataToVTK( model, "volume-flux",    "volume flux",       0 );
  vtk_output.OutputDataToVTK( model, "nvolume-flux",   "nodal volume flux", 0 );

  // JPG output (only scalar variables can be visualized)
#ifdef CSMP_WITH_IMAGE_OUTPUT
  jpg_output.OutputDataToJPG( model, "fluid-pressure", "fluid pressure",    0 );
  jpg_output.OutputDataToJPG( model, "volume-flux",    "volume flux",       0 );
#endif


  // 8. Form a Group named "granite" in order to access
  //    intrusion in the center of the model.
  //    Group granite is build from finite elements in
  //    the permeability range between 1.0e-21 to 1.0e-18 m2
  // -------------------------------------------------------
  cout << "\nFORMING A REGION CALLED 'granite'" << endl;
  model.FormRegionFrom( "granite", "permeability", 1.0e-21, 1.0e-18 );
  Region<2>& granite_domain(model.Region("granite"));

  // add fluid volume source term to region granite and repeat computation
  const double source_term(1.0e-13); // m3 m-2 s-1
  granite_domain.InputPropertyValue( "fluid volume source", makeScalar(PLAIN,source_term) );

  // fixing pressure at perimeter of group
  granite_domain.ChangePropertyStatus( "fluid pressure", DIRICH, PERIMETER );

  // recomputing fluid pressure in the granite taking into account the source term
  const bool debug{false};
  total_pressure.IntegrateOver( model, granite_domain, debug );

  printRangeOfVariable( model, "granite", "fluid pressure" );
  printRangeOfVariable( model, "granite", "velocity" );
  printRangeOfVariable( model, "granite", "pore velocity" );
  printRangeOfVariable( model, "granite", "volume flux" );
  printRangeOfVariable( model, "granite", "nodal volume flux" );

#ifdef CSMP_WITH_IMAGE_OUTPUT
  jpg_output.OutputDataToJPG( model, "fluid-pressure", "fluid pressure", 1 );
  jpg_output.OutputDataToJPG( model, "volume-flux",    "volume flux",    1 );
#endif

  // output of the region "granite"
  vtk_output.OutputDataToVTK( model, "granite", "fluid-pressure", "fluid pressure", 1, true );
  vtk_output.OutputDataToVTK( model, "granite", "velocity",       "velocity",       1, true );

  // ---------------------------------------------------------------------------------------
  // 9. finding the pressure value at a point of interest
  // ---------------------------------------------------------------------------------------
  map<size_t,std::vector<double> >  points;
  vector<double>  point1(2);
  point1[0] = 5000.; point1[1] = 2000.;
  cout <<"\nmain: Please enter the x and y coordinates of a point at which you would like to know the 'fluid pressure' (m): ";
  cin >> point1[0] >> point1[1];
  points[1] = point1;

  PropertyAtPointVisitor<2U>  point_probe( model, points, "fluid pressure" );
  model.Accept( point_probe );
  Element<2U>*  eptr(point_probe.ElementThatContains(1));
  if ( eptr != NULL ) cout <<"\nmain: element "<< eptr->Idx() <<" contains searched point.\n";
  else cout <<"\nmain: point not found.\n";
  
  const csmp::Index pf_key = model.Database().StorageKey("fluid pressure");
  cout <<"\nmain: Fluid pressure pressure at point: "<< eptr->PropertyValueAtBaryCenter( pf_key );

  cout <<"\nmain: That's it..."<< endl;
  
} // end Run

} // csmp
