.TH "source/includes/model/binaryReadWrite.h" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/includes/model/binaryReadWrite.h
.SH SYNOPSIS
.br
.PP
\fR#include 'CSMP_definitions\&.h'\fP
.br
\fR#include 'PropertyDatabase\&.h'\fP
.br
\fR#include 'ArrayVariable\&.h'\fP
.br
\fR#include 'FlaggedArrayVariable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcsmp::BinaryFileSectionRead\fP"
.br
.ti -1c
.RI "class \fBcsmp::BinaryFileSectionWrite\fP"
.br
.RI "Helper class to write sections to a binary file\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsmp\fP"
.br
.RI "Complex System Modeling Platform\&. "
.ti -1c
.RI "namespace \fBcsmp::femDataOutputDispatch\fP"
.br
.RI "additions by P\&. Lang (2012); SKM "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr size_t \fBcsmp::CSMP_BINARY_FILE_HDR_SIZE\fP (8+1)"
.br
.ti -1c
.RI "size_t \fBcsmp::readContainerSize\fP (std::fstream &fp)"
.br
.RI "checks whether the integer value fits within the range of a size_t and returns it "
.ti -1c
.RI "template<class T> bool \fBcsmp::binaryFileWrite\fP (std::fstream &fp, const std::vector< T > &stl_ctner)"
.br
.ti -1c
.RI "template<class T> bool \fBcsmp::binaryFileRead\fP (std::fstream &fp, std::vector< T > &stl_ctner)"
.br
.ti -1c
.RI "template<typename T> bool \fBcsmp::binaryFileWrite\fP (std::fstream &fp, const std::deque< T > &stl_ctner)"
.br
.RI "deque version "
.ti -1c
.RI "template<typename T> bool \fBcsmp::binaryFileRead\fP (std::fstream &fp, std::deque< T > &stl_ctner)"
.br
.RI "deque version "
.ti -1c
.RI "template<class T> bool \fBcsmp::binaryFileWrite\fP (std::fstream &fp, const std::deque< std::vector< T > > &stl_ctner)"
.br
.ti -1c
.RI "template<class T> bool \fBcsmp::binaryFileRead\fP (std::fstream &fp, std::deque< std::vector< T > > &stl_ctner)"
.br
.ti -1c
.RI "template<class M, class T> bool \fBcsmp::binaryFileWrite\fP (std::fstream &fp, const std::map< M, T > &stl_ctner)"
.br
.ti -1c
.RI "template<class M, class T> bool \fBcsmp::binaryFileWrite\fP (std::fstream &fp, const std::unordered_map< M, T > &stl_ctner)"
.br
.ti -1c
.RI "template<class M, class T> bool \fBcsmp::binaryFileRead\fP (std::fstream &fp, std::map< M, T > &stl_ctner)"
.br
.ti -1c
.RI "template<class M, class T> bool \fBcsmp::binaryFileWrite\fP (std::fstream &fp, const std::map< M, std::vector< T > > &stl_ctner)"
.br
.ti -1c
.RI "template<class M, class T> bool \fBcsmp::binaryFileRead\fP (std::fstream &fp, std::map< M, std::vector< T > > &stl_ctner)"
.br
.ti -1c
.RI "bool \fBcsmp::binaryFileWrite\fP (std::fstream &fp, const std::string &)"
.br
.ti -1c
.RI "bool \fBcsmp::binaryFileRead\fP (std::fstream &fp, std::string &)"
.br
.ti -1c
.RI "bool \fBcsmp::binaryFileWrite\fP (std::fstream &fp, const char *str)"
.br
.ti -1c
.RI "bool \fBcsmp::binaryFileRead\fP (std::fstream &fp, char str[])"
.br
.ti -1c
.RI "template<class Var> void \fBcsmp::femDataOutputDispatch::initVariable\fP (\fBcsmp::Index\fP, Var &)"
.br
.ti -1c
.RI "template<> void \fBcsmp::femDataOutputDispatch::initVariable\fP (\fBcsmp::Index\fP key, \fBArrayVariable\fP &var)"
.br
.ti -1c
.RI "template<> void \fBcsmp::femDataOutputDispatch::initVariable\fP (\fBcsmp::Index\fP key, \fBFlaggedArrayVariable\fP &var)"
.br
.ti -1c
.RI "template<class V, class D, uint32_t dim> bool \fBcsmp::variablesOut\fP (std::fstream &fp, const D &domain, const \fBPropertyDatabase\fP< dim > &pref, \fBVARIABLE_TYPE\fP vtype)"
.br
.RI "domain (\fBModel\fP, \fBRegion\fP\&.\&.\&.) variables binary IO "
.ti -1c
.RI "template<class V, class D, uint32_t dim> bool \fBcsmp::variablesIn\fP (std::fstream &fp, D &domain, const \fBPropertyDatabase\fP< dim > &pref, \fBVARIABLE_TYPE\fP)"
.br
.ti -1c
.RI "template<class D, uint32_t dim> bool \fBcsmp::domainVariablesOut\fP (std::fstream &fp, const D &domain, const \fBPropertyDatabase\fP< dim > &pref)"
.br
.ti -1c
.RI "template<class D, uint32_t dim> bool \fBcsmp::domainVariablesIn\fP (std::fstream &fp, D &domain, const \fBPropertyDatabase\fP< dim > &pref)"
.br
.ti -1c
.RI "template<class V, class D, uint32_t dim> bool \fBcsmp::selectedVariablesIn\fP (std::fstream &fp, D &domain, const \fBPropertyDatabase\fP< dim > &pref, \fBVARIABLE_TYPE\fP, const std::set< std::string > &selection)"
.br
.ti -1c
.RI "template<class D, uint32_t dim> bool \fBcsmp::selectedDomainVariablesIn\fP (std::fstream &fp, D &domain, const \fBPropertyDatabase\fP< dim > &pref, const std::set< std::string > &selection)"
.br
.ti -1c
.RI "template<class M, class T> bool \fBcsmp::binaryFileRead\fP (std::fstream &fp, std::unordered_map< M, T > &stl_ctner)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
