.TH "source/includes/math/compareFloats.h" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/includes/math/compareFloats.h
.SH SYNOPSIS
.br
.PP
\fR#include <limits>\fP
.br
\fR#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsmp\fP"
.br
.RI "Complex System Modeling Platform\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcsmp::approximatelyEqual\fP (double a, double b)"
.br
.ti -1c
.RI "bool \fBcsmp::essentiallyEqual\fP (double a, double b)"
.br
.ti -1c
.RI "bool \fBcsmp::definitelyGreaterThan\fP (double a, double b)"
.br
.ti -1c
.RI "bool \fBcsmp::definitelyLessThan\fP (double a, double b)"
.br
.ti -1c
.RI "bool \fBcsmp::approximatelyEqual\fP (double a, double b, double epsilon)"
.br
.ti -1c
.RI "bool \fBcsmp::essentiallyEqual\fP (double a, double b, double epsilon)"
.br
.ti -1c
.RI "bool \fBcsmp::definitelyGreaterThan\fP (double a, double b, double epsilon)"
.br
.ti -1c
.RI "bool \fBcsmp::definitelyLessThan\fP (double a, double b, double epsilon)"
.br
.in -1c
.SH "Detailed Description"
.PP 
"math/compareFloats\&.h" 
.br

.PP
\fBAuthor\fP
.RS 4
Thomas Driesner, ETH Zuerich 
.br
 
.RE
.PP
.SH "Contact"
.PP

.br
 thomas.driesner@erdw.ethz.ch 
.br

.PP
@changes changes Latest Changes 
.br
 Oct\&. 6, 2012: ported to CSMP++
.SH "Motivation"
.PP

.br
 A selection of inline functions for float comparisons that account for numerical precision\&. Function names should be self-explanatory\&. Functions can be traced back to Knuth's book and were found on: http://stackoverflow.com/questions/17333/most-effective-way-for-float-and-double-comparison
.SH "Testing"
.PP

.br
 code was taken as is without further testing 
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
