.TH "csmp::H2OFluidProperties" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::H2OFluidProperties
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <H2OFluidProperties\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBH2OFluidProperties\fP (const double &externaltemperature_in_C, const double &externalpressure_in_Pa, const double &external_fluid_enthalpy_in_J_per_kg, const double &external_cp_rock, const double &external_rho_rock, const double &external_phi)"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBLiquidPropertiesFromTHP\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBVaporPropertiesFromTHP\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBBulkPropertiesFromTHP\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBLiquidPropertiesFromTP\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBVaporPropertiesFromTP\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBBulkPropertiesFromTP\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBReportLiquidProperties\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBReportVaporProperties\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBReportBulkProperties\fP ()"
.br
.ti -1c
.RI "States \fBStateFromTHP\fP ()"
.br
.ti -1c
.RI "States \fBStateFromTP\fP ()"
.br
.ti -1c
.RI "bool \fBEquilibrated\fP ()"
.br
.ti -1c
.RI "void \fBPrintProperties\fP ()"
.br
.ti -1c
.RI "void \fBReportAllProperties\fP ()"
.br
.ti -1c
.RI "void \fBInitializeToBogus\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Thomas Driesner, ETH Zuerich 
.RE
.PP
.SH "Contact"
.PP
thomas.driesner@erdw.ethz.ch
.SH "Motivation"
.PP
\fBH2OFluidProperties\fP is an single interface to pure water single- and twophase properties in a porous medium via an equation of state\&. Information about pure water properties might also be obtained from \fBH2OLookup\fP but would require a reasonable knowledge of the thermodynamics involved (e\&.g\&., how to compute liquid-vapor saturations in the case of a twophase fluid) and would be incomplete because some properties vary with the exact properties of the rock matrix (e\&.g\&., the compressibility of a twophase liquid+vapor mixture is a function of the rock's heat capacity and porosity, see Grant&Sorey (1979), The Compressibility and Hydraulic Diffusivity of a Water-Steam Flow, \fBWater\fP Resources Research, 15, 3, 684-686)\&.

.PP
\fBH2OFluidProperties\fP eliminates the need of such a detailed implementation in terms of the interface of \fBH2OLookup\fP by the user\&.
.SH "Usage"
.PP
A \fBH2OFluidProperties\fP is instantiated with six constrcutor arguments\&. These are temperature in Celsius, pressure in bar, specific fluid enthalpy (in J/kg), the rock's heat capacity in J/kg/K, the rock's density in kg/m3, and the porosity (dimensionless)\&. These are passed as const references to the respective existing objects in the user's code\&. \fBH2OFluidProperties\fP has an internal mechanism that makes sure that whenever it is queried (except for the Report\&.\&.\&. functions, see below) it checks and updates its internal placeholders to the current values of these variables, i\&.e\&., the user does NOT have to trigger an update\&. Although \fBH2OFluidProperties\fP can be used standalone, it is most often applied as a member of H2OPropertiesVisitor\&.

.PP
The most important interfaces return objects of type \fBFluidproperties\fP\&. These are:

.PP
(1) LiquidPropertiesFromTHP(), VaporPropertiesFromTHP(), and BulkPropertiesFromTHP()\&. These determine the fluid state and properties primarily at the given temperature and pressure\&. If these conditions fall - within 5 x the available numerical precision of double on the given platform - very close to the boiling curve, sepcific enthalpy is used as an additional criterion to distinguish between liquid, vapor and twophase\&. In the case of twophase liquid+vapor, the actual enthalpy value is use to compute the saturations and mass fractions, respectively\&. If one of these member functions is invoked, all properties are computed\&. To avoid re-computation(*), properties of the other two may the also be extracted via the respective Report\&.\&.\&. functions described below\&.

.PP
(2) LiquidPropertiesFromTP(), VaporPropertiesFromTP(), and BulkPropertiesFromTP()\&. These determine the fluid state and properties at the given temperature and pressure\&. Where enthalpy is needed - again if t is within 5 x the available numerical precision of double on the given platform - the critical enthalpy is used, which always enforces a twophase state\&. This may be useful for initial and boundary conditions\&. The user should, however, be aware that this is an arbitrary value\&. If one of these member functions is invoked, all properties are computed\&. To avoid re-computation, properties of the other two may the also be extracted via the respective Report\&.\&.\&. functions described below\&.

.PP
(3) ReportLiquidProperties(), ReportVaporProperties(), ReportBulkProperties()\&. These should be used with care\&. These functions bypass the internal automatic update of temperature etc\&. and will hence return the fluid properties as they were computed after the last internal update\&. This is likely to disagree with the current values of temperature, pressure etc\&. in the user's code\&. However, if one of the above \&.\&.\&.FreomTHP() or \&.\&.\&.FromTP() functons has been called, properties for the other two calls have already been computed and might equally well be extracted via the respective Report\&.\&.\&. functions (e\&.g\&.: if you called BulkPropertiesFromTHP(), you can safely extract vapor and liquid properties by immediately afterwards calling ReportVaporProperties() and ReportLiquidProperties()\&.

.PP
(*) This has changed from previous versions: the \&.\&.\&.FromTHP and \&.\&.\&.FromTP() functions used to have an internal check that avoided re-computation in case that t,p,h,cp_rock,rho_rock and phi didn't change\&. This has currently been disabled and may be re-activated after intense testing of this new version has been done\&. 
.SH "Dependencies"
.PP
.SH "Known issues"
.PP
.IP "\(bu" 2
Rather than cp_rock etc\&. provide reference to a rock class or struct or function to allow for simple handling of t-dependent heat capacity etc\&.?
.IP "\(bu" 2
Have slightly improved the latter in TwoPhaseCompressibility but it needs re-check
.IP "\(bu" 2
maybe do two constructors with/without rock?
.IP "\(bu" 2
or re-check compressibility kieffer1977 vs\&. GrantSorey1979
.IP "\(bu" 2
implement a true FromHP formulation once requests emerge
.IP "\(bu" 2
avoid re-computation in FromTHP and FromTP functions
.PP
.SH "Testing"
.PP
Testing is in progress\&.
.SH "Changes"
.PP
\fBH2OFluidProperties\fP is an essentially completely changed and re-written version of what used to be FluidLookupWater\&. Thomas Driesner, Jan-Feb 2011

.PP
\fBTodo\fP
.RS 4
.IP "\(bu" 2
check faster equilibration route for twophase conditions via enthalpy check
.IP "\(bu" 2
lots of assignments in UpdatePropertiesXXX not needed anymore? 
.PP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
