.TH "csmp::IndexTracker" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::IndexTracker \- Keeps track of all \fBIndex\fP objects once they have been registered\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IndexTracker\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::map< \fBcsmp::Index\fP *, std::string >::const_iterator \fBIndicesBegin\fP () const"
.br
.ti -1c
.RI "std::map< \fBcsmp::Index\fP *, std::string >::const_iterator \fBIndicesEnd\fP () const"
.br
.ti -1c
.RI "void \fBAttach\fP (\fBcsmp::Index\fP *newIndex, std::string parameterName)"
.br
.RI "Called when a new \fBIndex\fP is issued\&. "
.ti -1c
.RI "void \fBAttach\fP (\fBcsmp::Index\fP *newIndex, const \fBcsmp::Index\fP *existingIndex)"
.br
.RI "Called when a new \fBIndex\fP is copied using an existing \fBIndex\fP\&. "
.ti -1c
.RI "void \fBDetach\fP (const \fBcsmp::Index\fP *existingIndex)"
.br
.RI "Called when an existing \fBIndex\fP is destroyed\&. "
.ti -1c
.RI "void \fBDetach\fP (std::string parameterName)"
.br
.RI "Called when an existing \fBIndex\fP is destroyed\&. "
.ti -1c
.RI "void \fBDetachFromAll\fP ()"
.br
.RI "Detaches itself from all \fBIndex\fP objects; this method is called upon destruction\&. "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "print all currently registered \fBIndex\fP objects "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexTracker\fP (const \fBIndexTracker\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keeps track of all \fBIndex\fP objects once they have been registered\&. 

Serves \fBPropertyDatabase\fP to keep all existing \fBIndex\fP objects objects up to date, which is necessary when new variables are created at runtime\&.

.PP
\fBNote\fP
.RS 4
index tracking is necessary because some classes have indices as members\&. These objects can get invalidated when new variables of the same kind and place\&. are created\&. If so, for instance, the 5th scalar on the node might become the 10th\&.
.RE
.PP
By tracking all \fBIndex\fP objects that exist in a model, these can be updated by the \fBPropertyDatabase\fP everytime a variable is created or deleted\&.

.PP
\fBNote\fP
.RS 4
this implementation is based on the "Observer" design pattern\&.
.RE
.PP
\fBAuthor\fP
.RS 4
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
9/25/2012
.RE
.PP
TODO: 
.PP
\fBTodo\fP
.RS 4
SKM 2/2017 - The \fBIndexTracker\fP -> update methodology seems to fail if \fBArrayVariable\fP objects of different length are created at runtime; fix or rethink approach\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void csmp::IndexTracker::Attach (\fBcsmp::Index\fP * newIndex, const \fBcsmp::Index\fP * existingIndex)"

.PP
Called when a new \fBIndex\fP is copied using an existing \fBIndex\fP\&. Attaches an existing index object to a new index\&. Reports if the existing index object is orphan, i\&.e\&. has no name because it has not been tracked before\&.

.PP
In this case, the parameter is called 'unspecified'\&. This will be picked up by the property database at the next update attempt\&. 
.SS "void csmp::IndexTracker::Detach (const \fBcsmp::Index\fP * existingIndex)"

.PP
Called when an existing \fBIndex\fP is destroyed\&. Detach index object as identified by a (unique) pointer to it\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
