.TH "csmp::Point< 1U >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Point< 1U >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP (double=0\&.)"
.br
.RI "explicit keyword is not required because conversion is desired "
.ti -1c
.RI "\fBPoint\fP (const std::array< double, 1 > &)"
.br
.ti -1c
.RI "\fBPoint\fP (const std::vector< double > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator=\fP (double)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator+\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator\-\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator*\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator/\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator+\fP (double) const"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator\-\fP (double) const"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator*\fP (double) const"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator/\fP (double) const"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator+=\fP (const \fBPoint\fP< 1U > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator\-=\fP (const \fBPoint\fP< 1U > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator*=\fP (const \fBPoint\fP< 1U > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator/=\fP (const \fBPoint\fP< 1U > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator+=\fP (double)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator\-=\fP (double)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator*=\fP (double)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > & \fBoperator/=\fP (double)"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (uint32_t)"
.br
.ti -1c
.RI "const double & \fBoperator[]\fP (uint32_t) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "void \fBSet\fP (const std::array< double, 1U > &)"
.br
.ti -1c
.RI "void \fBSet\fP (const std::vector< double > &)"
.br
.ti -1c
.RI "double \fBLength\fP () const"
.br
.ti -1c
.RI "double \fBSquaredLength\fP () const"
.br
.ti -1c
.RI "void \fBNormalizeLengthTo\fP (double len=1\&.)"
.br
.ti -1c
.RI "double \fBDistanceTo\fP (const \fBPoint\fP< 1U > &) const"
.br
.ti -1c
.RI "bool \fBCoincidesWithWithinTolerance\fP (const \fBPoint\fP< 1U > &, double tolerance=1\&.0e\-5) const"
.br
.ti -1c
.RI "bool \fBIsBetween\fP (const \fBPoint\fP &pt1, const \fBPoint\fP &pt2)"
.br
.ti -1c
.RI "std::vector< double > \fBCoordinates\fP () const"
.br
.ti -1c
.RI "std::array< double, 1U > \fBCoordinateArray\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBx_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator\-\fP (double val, const \fBPoint\fP< 1U > &pt)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator+\fP (double val, const \fBPoint\fP< 1U > &pt)"
.br
.ti -1c
.RI "\fBPoint\fP< 1U > \fBoperator*\fP (double val, const \fBPoint\fP< 1U > &pt)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
