.TH "csmp::variables::VariableSet_TwoPhaseFlow" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::variables::VariableSet_TwoPhaseFlow
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<uint32_t dim> \fBVariableSet_TwoPhaseFlow\fP (const \fBPropertyDatabase\fP< dim > &db)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_XCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_XH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_YCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_YH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_xCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_xH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_xSalt\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_yCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_yH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_CO2aq\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_H2Og\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_msalt\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_cCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_cH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_rhoCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_rhoH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_diffCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_diffH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_rhom\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_IFT\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_muCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_muH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_eC\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_KH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Qh\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_KCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Kr\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Qe\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_T\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Bio\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_BioT\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_nu\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_E\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_rhob\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_coh\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_cR\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Vdef\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_dil\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, NODE > \fBkey_displ\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_rhod\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Se\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_fail\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, NODE > \fBkey_F\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_frica\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_SSmax\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Smean\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACE > \fBkey_Sn\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_op\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_Sv\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACE > \fBkey_Ss\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_sig1\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_sig2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_sig3\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_e\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_e1\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_e2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_e3\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_S\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Sy\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_fail1\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_dV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_kV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_diffpc\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_K\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_pd\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, FACE > \fBkey_fgt\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACE > \fBkey_flt\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_pf\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_mum\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_nQV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_QV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_fb\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_gt\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_siH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_laCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_laH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_sCO2_1\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_srCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_srH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_sCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_sH2O\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_TDS\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_lat\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_ct\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_vt\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_kh\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_qf\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_t\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_bcp\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_Fg\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_dip\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, SECTOR_INTEGRATION_POINT > \fBkey_sPV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_kfn\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, FACET_INTEGRATION_POINT > \fBkey_fAk\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_fA\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, FACET_INTEGRATION_POINT > \fBkey_fn\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_qft\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_qfCO2\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_fvPV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_cfl\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_dt\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_Ne\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, FACE > \fBkey_dipf\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_Nn\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< ARRAY, MODEL > \fBkey_t_out\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_pf0\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_QV0\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_nQV0\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_TMAX\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_thi\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_V\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_g\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_kFbr\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, REGION > \fBkey_Fs\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_kf\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_k\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_k_cal\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_phi\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_RRT\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, REGION > \fBkey_AS\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
