.TH "csmp::FiniteVolumeStencil_Test" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FiniteVolumeStencil_Test
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFiniteVolumeStencil_Test\fP (bool verbose=true)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBdisplayReferenceCoordinates\fP ()"
.br
.ti -1c
.RI "void \fBfacetAndSectorNumbersTest\fP ()"
.br
.ti -1c
.RI "void \fBsectorFacetConnectivityTest\fP ()"
.br
.ti -1c
.RI "void \fBorientationAndLengthOfNormalsTest\fP ()"
.br
.ti -1c
.RI "void \fBnormalTransformationTest\fP ()"
.br
.ti -1c
.RI "void \fBlocationOfSectorIntegrationPointsTest\fP ()"
.br
.ti -1c
.RI "void \fBweightsAndFacetIntegrationPointsTest\fP ()"
.br
.ti -1c
.RI "void \fBweightsOfSectorIntegrationPointsTest\fP ()"
.br
.ti -1c
.RI "void \fBshapeFunctionsTest\fP ()"
.br
.ti -1c
.RI "void \fBshapeFunctionDerivativesTest\fP ()"
.br
.ti -1c
.RI "template<uint32_t dim> \fBvector\fP< \fBPoint\fP< dim > > \fBGetPointsOfFacet\fP (const uint32_t &iFacet, const \fBCSMP_FEM_TYPE\fP &elType, const \fBFiniteVolumeStencil\fP< dim > &fvs, const \fBFiniteElement\fP &fe)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::FiniteVolumeStencil_Test::FiniteVolumeStencil_Test (bool verbose = \fRtrue\fP)\fR [explicit]\fP"
Method:

.PP
\fBFiniteVolumeStencil_Test::FiniteVolumeStencil_Test( )\fP

.PP
Description:

.PP
Constructor\&. This function initializes the objects which will be used during the test\&.
.SH "Input Arguments"
.PP
None\&. 
.SH "Application Examples"
.PP
The idea of this function is to specify the characteristics of the objects to be tested\&.

.PP
tested: is a test function 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::FiniteVolumeStencil_Test::displayReferenceCoordinates ()"
void \fBFiniteVolumeStencil_Test::displayReferenceCoordinates()\fP

.PP
Description: This test function displays the reference coordinates of each type of element\&.
.SH "Application Examples"
.PP
The idea of this function is to provide insight of how elements are being constructed\&.

.PP
tested: is a test function\&. 
.SS "void csmp::FiniteVolumeStencil_Test::facetAndSectorNumbersTest ()"
Method:

.PP
void \fBFiniteVolumeStencil_Test::facetAndSectorNumbersTest()\fP

.PP
Description: Tests for each finite element type supported if the basic query functionality of the class is correct\&. 
.SH "Input Arguments"
.PP
.SH "Application Examples"
.PP
The idea is to test the following member functions: size_t Facets() const; size_t Sectors() const; size_t IntegrationPointsPerFacet() const; size_t IntegrationPointsPerSector() const; void FacetEdgeNodes( size_t facet, size_t& inside_node, size_t& outside_node ) const; FV_FACET_TYPE FacetType() const;

.PP
tested: is a test funtion 
.SS "void csmp::FiniteVolumeStencil_Test::normalTransformationTest ()"
void \fBFiniteVolumeStencil_Test::normalTransformationTest()\fP

.PP
Description:

.PP
This test checks for each facet normal transformation, and ensures that it matches the computed facet normal\&.
.SH "Input Arguments"
.PP
.SH "Application Examples"
.PP
The idea is to test the following member functions:

.PP
wp FacetNormalTransformationNodeWeights( size_t facet, size_t node ) const; 
.SS "void csmp::FiniteVolumeStencil_Test::orientationAndLengthOfNormalsTest ()"
void \fBFiniteVolumeStencil_Test::orientationAndLengthOfNormalsTest()\fP

.PP
Description:

.PP
This test checks for each element type, that the corresponding normal vector is in fact normalized\&. 
.SH "Input Arguments"
.PP
.SH "Application Examples"
.PP
The idea is to test the following member functions: 
.PP
.nf
void   UnitParametricNormalTo( size_t facet, vector<fT>& nrml ) const;
fT   UnitParametricNormalComponent( size_t facet, size_t x_or_y_or_z ) const;

.fi
.PP
 
.SS "void csmp::FiniteVolumeStencil_Test::run ()\fR [virtual]\fP"

.PP
Implements \fBcsmp::Test\fP\&.
.SS "void csmp::FiniteVolumeStencil_Test::sectorFacetConnectivityTest ()"
void \fBFiniteVolumeStencil_Test::sectorFacetConnectivityTest()\fP
.SS "void csmp::FiniteVolumeStencil_Test::shapeFunctionDerivativesTest ()"
template<uint32_t dim> void IsoparametricQuadraticElements_Test<dim>::shapeFunctionDerivativesTest()

.PP
Tests if the shape functions sum to zero at the integration points\&.
.SH "Application Examples"
.PP
Runs the test for all Isoparametric Quadratic elements, for any dimensions\&. 
.SS "void csmp::FiniteVolumeStencil_Test::shapeFunctionsTest ()"
template<uint32_t dim> void IsoparametricQuadraticElements_Test<dim>::shapeFunctionsTest()

.PP
Tests if the shape functions sum to one at the integration points\&.
.SH "Application Examples"
.PP
Runs the test for all Isoparametric Quadratic elements, for any dimensions\&. 
.SS "void csmp::FiniteVolumeStencil_Test::weightsAndFacetIntegrationPointsTest ()"
void \fBFiniteVolumeStencil_Test::weightsAndFacetIntegrationPointsTest()\fP
.SH "Description"
.PP
Check if the area of the facet corresponds to the weight of the integration point\&. These should match\&. Check if the centroid of the facet corresponds to the integration point\&.
.SH "Application Examples"
.PP
The idea is to test the following member functions: fT FacetIntegrationWeight( size_t facet, size_t ip ) const; // = facet area fT FacetProjectionWeight( size_t facet, size_t ip ) const; // equal to scaling of normal length fT FacetIntegrationPoint( size_t facet, size_t ip, size_t r_or_s_or_t ) const; void FacetIntegrationPoint( size_t facet, size_t ip, vector<fT>& rst ) const; 
.SS "void csmp::FiniteVolumeStencil_Test::weightsOfSectorIntegrationPointsTest ()"
void \fBFiniteVolumeStencil_Test::weightsOfSectorIntegrationPointsTest()\fP

.PP
Verifies if the sum of weights corresponds to the volume of the finite element\&.
.SH "Application Examples"
.PP
The idea is to test the following member functions: 
.PP
.nf
fT  SectorIntegrationWeight( size_t sector, size_t ip ) const;

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
