.TH "csmp::Variables_Test" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Variables_Test
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Variables_Test\&.h>\fP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVariables_Test\fP (const char *)"
.br
.RI "takes the name of a test model as argument; this model should contain \fBBoundary\fP and \fBSplitBoundary\fP objects "
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests Read(), Store() and Status() operations for all variable placements and types with the FracBox model which contains \fBBoundary\fP objects\&. The operations are performed twice: 1) on the live model and 2) on a model recovered form disk\&.

.PP
\fBTodo\fP
.RS 4
Add tests for variables placed on \fBSplitBoundary\fP objects\&.
.RE
.PP

.PP
\fBAuthor\fP
.RS 4
Phillip Lang 
.RE
.PP
\fBDate\fP
.RS 4
9/24/2012 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::Variables_Test::Variables_Test (const char * prefix)\fR [explicit]\fP"

.PP
takes the name of a test model as argument; this model should contain \fBBoundary\fP and \fBSplitBoundary\fP objects 
.PP
\fBParameters\fP
.RS 4
\fIprefix\fP is the model name\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void csmp::Variables_Test::run ()\fR [virtual]\fP"

.PP
\fBTodo\fP
.RS 4
(2-F) \fBTest\fP for \fBInterFace\fP and \fBSplitBoundary\fP properties
.RE
.PP

.PP
\fBAuthor\fP
.RS 4
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
9/24/2012 
.RE
.PP

.PP
Implements \fBcsmp::Test\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
