.TH "csmp::SourceVisitor< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SourceVisitor< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SourceVisitor\&.h>\fP
.PP
Inherits \fBcsmp::Visitor< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourceVisitor\fP (\fBModel\fP< dim > &, std::vector< std::string > *to_initialize_keys=nullptr)"
.br
.ti -1c
.RI "\fBSourceVisitor\fP (\fBModel\fP< dim > &, \fBIndex\fP porosityKey, \fBIndex\fP densityDiffKey, \fBIndex\fP nfvsKey, \fBIndex\fP thicknessKey)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBElement\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBModel\fP< dim > *)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBVisitor\fP (\fBPLACEMENT\fP level=MODEL, \fBPLACEMENT\fP target=ELEMENT)"
.br
.ti -1c
.RI "void \fBApplicationLevel\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApplicationTarget\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationTarget\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetInitialProperties\fP (\fBModel\fP< dim > *model)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBRegion\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBSplitBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBInterFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBEdge\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBNode\fP< dim > *)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_target_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::SourceVisitor< dim >"
.PP
\fBAuthor\fP
.RS 4
Thomas Driesner, ETH Zuerich \fRthomas.driesner@erdw.ethz.ch\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::SourceVisitor\fP< dim >::Visit (\fBElement\fP< dim > * e)\fR [virtual]\fP"
if lower dimension elements are included in transport calculation thickness needs to be taken into account 
.PP
\fBTodo\fP
.RS 4
need to find a more efficient way to perform this calculation\&. Julian 19\&.02\&.2016 
.RE
.PP

.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::SourceVisitor\fP< dim >::Visit (\fBModel\fP< dim > * model)\fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
