.TH "csmp::TwoPhaseImplicitNodeCenteredFVTransport< dim, STP >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TwoPhaseImplicitNodeCenteredFVTransport< dim, STP >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TwoPhaseImplicitNodeCenteredFVTransport\&.h>\fP
.PP
Inherits \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTwoPhaseImplicitNodeCenteredFVTransport\fP (const char *group_name, \fBModel\fP< dim > &, const char *porosity='porosity', const char *viscosity_n='viscosity carbonic phase', const char *viscosity_w='viscosity aqueous phase', const char *density_n='density carbonic phase', const char *density_w='density aqueous phase', const char *phase1='saturation aqueous phase', const char *phase2='saturation carbonic phase', const char *transp_velocity='velocity', const char *nodal_source='nodal fluid volume source', bool with_capillary_spreading=false, bool with_gravitational_forces=false, const char *reference_variable_to_no_flow_bc='fluid pressure', bool nonlinear_scheme=false)"
.br
.RI "First-order two-phase flow constructor, no capillary spreading, wetting phase=phase1\&. "
.ti -1c
.RI "\fBTwoPhaseImplicitNodeCenteredFVTransport\fP (const char *group_name, \fBModel\fP< dim > &, bool second_order_in_space, bool second_order_in_time, const char *porosity='porosity', const char *viscosity_n='viscosity carbonic phase', const char *viscosity_w='viscosity aqueous phase', const char *density_n='density carbonic phase', const char *density_w='density aqueous phase', const char *phase1='saturation aqueous phase', const char *phase2='saturation carbonic phase', const char *transp_velocity='velocity', const char *nodal_source='nodal fluid volume source', bool with_capillary_spreading=false, bool with_gravitational_forces=false, const char *reference_variable_to_no_flow_bc='fluid pressure', bool nonlinear_scheme=false)"
.br
.RI "Second-order two-phase flow constructor, no capillary spreading, wetting phase=phase1\&. "
.ti -1c
.RI "\fBTwoPhaseImplicitNodeCenteredFVTransport\fP (const char *group_name, \fBModel\fP< dim > &, const char *porosity, const char *diffusivity, const char *viscosity_n, const char *viscosity_w, const char *density_n, const char *density_w, const char *phase1, const char *phase2, const char *transp_velocity, const char *nodal_source, bool with_capillary_spreading=false, bool with_gravitational_forces=false, const char *reference_variable_to_no_flow_bc='fluid pressure', bool nonlinear_scheme=false)"
.br
.RI "First-order two-phase flow constructor, with capillary spreading modelled as non-linear diffusion\&. "
.ti -1c
.RI "\fBTwoPhaseImplicitNodeCenteredFVTransport\fP (const char *group_name, \fBModel\fP< dim > &, bool second_order_in_space, bool second_order_in_time, const char *porosity, const char *diffusivity, const char *viscosity_n, const char *viscosity_w, const char *density_n, const char *density_w, const char *phase1, const char *phase2, const char *transp_velocity, const char *nodal_source, bool with_capillary_spreading=false, bool with_gravitational_forces=false, const char *reference_variable_to_no_flow_bc='fluid pressure', bool nonlinear_scheme=false)"
.br
.RI "Second-order two-phase flow constructor, with capillary spreading modelled as non-linear diffusion\&. "
.ti -1c
.RI "\fBTwoPhaseImplicitNodeCenteredFVTransport\fP (const char *group_name, \fBModel\fP< dim > &, bool second_order_in_space, bool second_order_in_time, const char *transp_velocity, bool with_capillary_forces, const char *thickness_low_dim_elmt='thickness', bool nonlinear_scheme=false)"
.br
.RI "for field-scale simulation: with standard variables, gravity and thickness attribute for lower-dim elements "
.ti -1c
.RI "virtual \fB~TwoPhaseImplicitNodeCenteredFVTransport\fP ()"
.br
.ti -1c
.RI "virtual double \fBTransportPhase\fP (\fBTwoPhaseModel\fP< dim > &, double time_interval)"
.br
.RI "transport of a non-wetting phase in 2-phase flow "
.ti -1c
.RI "virtual double \fBAnisotropicCourantIncrement\fP (\fBTwoPhaseModel\fP< dim > &, double max_time_increment)"
.br
.RI "two-phase, takes into account element shape in 2D and 3D unless one deals with 1D domain "
.ti -1c
.RI "virtual void \fBAdjustSolverSettings\fP ()"
.br
.RI "add extra functionality for laternative solver "
.ti -1c
.RI "void \fBDisableCapillarySpreading\fP ()"
.br
.RI "add extra functionality for alternative solver if needed "
.ti -1c
.RI "void \fBEnableCapillarySpreading\fP ()"
.br
.ti -1c
.RI "void \fBDisableGravitationalForces\fP ()"
.br
.ti -1c
.RI "void \fBEnableGravitationalForces\fP ()"
.br
.ti -1c
.RI "void \fBSetNoFlowBoundaryConditionKey\fP (\fBModel\fP< dim > &, const char *no_flow_bc='fluid pressure')"
.br
.ti -1c
.RI "void \fBApplyLinearScheme\fP ()"
.br
.ti -1c
.RI "void \fBApplyNonlinearScheme\fP ()"
.br
.ti -1c
.RI "void \fBMaxNewtonRahsonIterations\fP (size_t max_newton_raphson_iterations)"
.br
.ti -1c
.RI "void \fBMaxLineSearchIterations\fP (size_t max_line_search_iterations)"
.br
.ti -1c
.RI "void \fBTargetNewtonRaphsonResidual\fP (double target_newton_raphson_residual)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP
.in +1c
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeTransport\fP (const char *group_name, \fBModel\fP< dim > &, const char *porosity, const char *advected_prop, const char *transp_velocity, const char *nodal_source, bool second_order_in_space, bool second_order_in_time, const char *elmt_thickness_attribute=NULL, const char *velocity_multiplier=NULL)"
.br
.RI "single-phase solute advection-ONLY constructor, 1st-order method "
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeTransport\fP (const char *group_name, \fBModel\fP< dim > &, const char *porosity, const char *diffusivity, const char *advected_prop, const char *transp_velocity, const char *nodal_source, bool second_order_in_space, bool second_order_in_time, const char *elmt_thickness_attribute=NULL, const char *velocity_multiplier=NULL)"
.br
.RI "single-phase solute advection-diffusion constructor, 1st-order method "
.ti -1c
.RI "virtual double \fBAdvectVariable\fP (double time_interval, double cfl_multiplication_factor=1\&., bool apply_flux_balance_correction=true, bool update_pore_volumes=false)"
.br
.RI "single-phase passive advection, returns Courant increment "
.ti -1c
.RI "virtual void \fBAdvectVariableSingleStep\fP (double time_increment, bool apply_flux_balance_correction=true, bool update_pore_volumes=false)"
.br
.ti -1c
.RI "virtual double \fBAnisotropicCourantIncrement\fP ()"
.br
.RI "evaluation of Courant-Friedrich-Levy condition, i\&.e\&., grid Courant number "
.ti -1c
.RI "void \fBCFL_Multiplier\fP (double desired_value)"
.br
.RI "to set scaling (default=1) "
.ti -1c
.RI "double \fBCFL_Multiplier\fP () const"
.br
.ti -1c
.RI "void \fBWithLsmGradientLimiter\fP (\fBModel\fP< dim > &)"
.br
.RI "to apply the gradient limiter "
.ti -1c
.RI "void \fBMaxNonlinear2ndOrderIterations\fP (size_t max_nonlinear_iterations)"
.br
.ti -1c
.RI "void \fBTargetNonlinear2ndOrderResidual\fP (double target_residual)"
.br
.ti -1c
.RI "double \fBModelInflow\fP () const"
.br
.ti -1c
.RI "double \fBModelOutflow\fP () const"
.br
.ti -1c
.RI "double \fBBoundaryFluxes\fP (double &inflow, double &out_flow, bool box_shaped_model=true, bool use_advected_variable=false, const char *advected_variable='no advected variable', const char *variable_to_determine_no_flow='fluid pressure', \fBVARIABLE_FLAG\fP exclude_flag=\fBANY\fP) const"
.br
.RI "returns inflow, outflow, and mismatch between these; calculation can FVs where variable is flagged with exclude_flag "
.ti -1c
.RI "void \fBFluxBalance\fP (double &fmin, double &fmax) const"
.br
.RI "for each finite volume it sums up incoming and outgoing fluxes reporting the extrema "
.ti -1c
.RI "void \fBDivergence\fP (const char *div_property, const char *result_prop) const"
.br
.RI "as previous method, but assigns surface integrals to the result property "
.ti -1c
.RI "void \fBMultiplyScalarNodePropertyByFiniteVolume\fP (const char *property)"
.br
.RI "integrates nodal scalar properties finite volume by finite volume "
.ti -1c
.RI "double \fBVolumeIntegrateScalarFiniteVolumeVariable\fP (const char *property, bool consider_porosity) const"
.br
.RI "integrates scalar node and element variables "
.ti -1c
.RI "double \fBVolumeIntegrateScalarFiniteElementVariable\fP (const char *property, bool take_porosity_into_account=false, const char *region=NULL) const"
.br
.ti -1c
.RI "double \fBVolumeIntegrateScalarFiniteVolumeVariable\fP (const char *group, const \fBModel\fP< dim > &, const char *property, bool consider_porosity) const"
.br
.RI "integrates target property over a region of interest, result can be scaled by porosity "
.ti -1c
.RI "void \fBVolumeIntegrate\fP (const char *integrand_property, const char *result_prop) const"
.br
.RI "integrals for finite-element computations "
.ti -1c
.RI "void \fBVolumeIntegrate\fP (const char *integrand_property, const char *integrand_multiplier, const char *result_prop) const"
.br
.ti -1c
.RI "void \fBMultiplyScalarBoundaryValuesByFiniteVolumeCrossSectionalArea\fP (\fBModel\fP< dim > &, \fBBOX_BOUNDARY\fP, const char *property)"
.br
.RI "conversion of values already assigned to the nodes (only possible if nodes comprise model boundary) "
.ti -1c
.RI "void \fBTransformScalarBoundaryValuesIntoNeumannConditions\fP (\fBBOX_BOUNDARY\fP boundary, const char *node_property, const char *propertionality_constant, bool distribute_total_amount)"
.br
.RI "computation and assignment of Neumann boundary gradients to target boundary "
.ti -1c
.RI "void \fBAssignScalarBoundaryValues\fP (\fBBOX_BOUNDARY\fP, const char *property, \fBVARIABLE_FLAG\fP bcond, double val, bool distribute_total_amount)"
.br
.RI "assignment of a single specific value that is projected on outward point normal "
.ti -1c
.RI "double \fBFiniteVolume\fP (const char *volume_property) const"
.br
.RI "returns the actual volume of the finite volume i "
.ti -1c
.RI "double \fBPoreVolume\fP (size_t iFv_cell) const"
.br
.ti -1c
.RI "virtual CSMP_DEFAULT_LINEAR_SOLVER_SETTINGS & \fBGetSolverSettings\fP ()"
.br
.RI "Access to advector's solver settings\&. "
.ti -1c
.RI "virtual CSMP_DEFAULT_LINEAR_SOLVER * \fBGetSolver\fP ()"
.br
.ti -1c
.RI "virtual void \fBOut\fP () const"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP
.in +1c
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeTransport\fP (const \fBNodeCenteredFiniteVolumeTransport\fP< dim > &)"
.br
.ti -1c
.RI "void \fBInitializeFiniteVolumeData\fP (bool multiply_pore_volumes_with_thickness_attribute=false)"
.br
.ti -1c
.RI "void \fBInitializeFiniteVolumeDataParametricToPhysical\fP (bool store_normals)"
.br
.ti -1c
.RI "void \fBInitializeSectorPoreVolumeData\fP (bool multiply_pore_volumes_with_thickness_attribute)"
.br
.ti -1c
.RI "bool \fBInitializeArraysForFirstOrderMethod\fP ()"
.br
.ti -1c
.RI "bool \fBInitializeArraysForSecondOrderMethod\fP (bool second_order_in_space, bool second_order_in_time)"
.br
.ti -1c
.RI "virtual size_t \fBMeasureAllocatedMemory\fP () const"
.br
.ti -1c
.RI "bool \fBSecondOrderInTime\fP () const"
.br
.ti -1c
.RI "bool \fBSecondOrderInSpace\fP () const"
.br
.ti -1c
.RI "void \fBInitialAdvectedPropertyValues\fP (const \fBcsmp::Index\fP &adv_key)"
.br
.ti -1c
.RI "void \fBInitialAdvectedPropertyValues\fP (const \fBcsmp::Index\fP &adv_key, double &smin, double &smax)"
.br
.ti -1c
.RI "void \fBMinMaxAdvectedProperty\fP ()"
.br
.ti -1c
.RI "void \fBBackupFacetFluxes\fP ()"
.br
.ti -1c
.RI "void \fBUpdateProjectedVelocitiesAndFluxBalances\fP ()"
.br
.ti -1c
.RI "bool \fBFluxThroughBoundaryFiniteVolume\fP (const \fBNode\fP< dim > *fv_ptr, double &inflow, double &flux_balance) const"
.br
.ti -1c
.RI "void \fBAssignFluxBoundaryConditions\fP (\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > &advection_algorithm, bool use_t0_saturation) const"
.br
.ti -1c
.RI "void \fBRecordFluxBalances\fP (const char *balance_var, double &total_surplus, double &total_deficit) const"
.br
.ti -1c
.RI "void \fBAdvectVariable1stOrder\fP (\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > &, double time_interval, bool with_flux_balance_correction)"
.br
.ti -1c
.RI "void \fBAdvectVariable2ndOrder\fP (\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > &, double time_increment, bool with_flux_balance_correction)"
.br
.ti -1c
.RI "void \fBAdvectVariable2ndOrderInSpaceAndTime\fP (\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > &, double time_increment, bool with_flux_balance_correction)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP
.in +1c
.ti -1c
.RI "const \fBPropertyDatabase\fP< dim > & \fBpref_\fP"
.br
.ti -1c
.RI "\fBRegion\fP< dim > & \fBgref_\fP"
.br
.ti -1c
.RI "\fBModel\fP< dim > & \fBmref_\fP"
.br
.ti -1c
.RI "bool \fBverbose_\fP"
.br
.ti -1c
.RI "std::vector< \fBFV_Parameter\fP > \fBSTENCIL_DATA\fP"
.br
.RI "finite-volume data for fast calculations "
.ti -1c
.RI "std::vector< double > \fBFVPOREVOL\fP"
.br
.RI "pore volumes of finite-volume cells for theta calculation etc\&. "
.ti -1c
.RI "std::vector< double > \fBSAT0\fP"
.br
.RI "advected variable at t0 "
.ti -1c
.RI "std::vector< double > \fBFLUX_BALANCE\fP"
.br
.RI "for each FV, but excluding truncated FV at global model boundaries "
.ti -1c
.RI "std::vector< std::pair< double, double > > \fBSMINMAX\fP"
.br
.RI "min, max values of advected property at neighbor FV's of current FV "
.ti -1c
.RI "std::vector< std::vector< double > > \fBFACETFLUXES0\fP"
.br
.RI "at time, t (at last time step) "
.ti -1c
.RI "std::vector< std::vector< double > > \fBLTDSATS0\fP"
.br
.RI "ltd values of advected property "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBphi_key_\fP"
.br
.RI "porosity "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBdiff_key_\fP"
.br
.RI "diffusivity of advected variable (only in 2nd-order method) "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBadv1_key_\fP"
.br
.RI "transported variable "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBvel_key_\fP"
.br
.RI "transport velocity "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBsrc_key_\fP"
.br
.RI "nodal fluid volume source "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBthi_key_\fP"
.br
.RI "thickness multiplier for lower dimensional elements "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBvelo_mult_key_\fP"
.br
.RI "velocity multiplier key "
.ti -1c
.RI "\fBcsmp::Index\fP \fBmass_center_key_\fP"
.br
.RI "center of mass for each CV "
.ti -1c
.RI "\fBcsmp::Index\fP \fBgrad_advprop_key_\fP"
.br
.RI "gradient of the advacted property "
.ti -1c
.RI "\fBcsmp::Index\fP \fBgrad_advprop_limiter_key_\fP"
.br
.RI "limiter for the gradient of the advected property "
.ti -1c
.RI "std::string \fBadvected_variable_\fP"
.br
.ti -1c
.RI "double \fBcfl_multiplier_\fP"
.br
.ti -1c
.RI "size_t \fBvar_ncomponents_\fP"
.br
.ti -1c
.RI "\fBStencilProcessor\fP< dim > \fBstencil_\fP"
.br
.RI "default size is 1 if only a scalar is being advected\&. (Julian) "
.ti -1c
.RI "bool \fBfirstCall_\fP"
.br
.ti -1c
.RI "bool \fBwith_lsmgrad_limiter_\fP"
.br
.ti -1c
.RI "double \fBtarget_nonlinear_limiting_case_residual_\fP"
.br
.RI "targed residual in order to get correct 2nd order approximations "
.ti -1c
.RI "size_t \fBmax_nonlinear_limiting_case_iterations_\fP"
.br
.RI "maximum number of nonlinear iterations in 2nd order scheme "
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > * \fBbaseAdvector_\fP = nullptr"
.br
.ti -1c
.RI "\fBGenericNodePropertyGradientLimiter\fP< dim > * \fBgrad_advprop_limiter_\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class STP>
.br
class csmp::TwoPhaseImplicitNodeCenteredFVTransport< dim, STP >""generic_node_centered_finite_volumes/TwoPhaseImplicitNodeCenteredFVTransport\&.h"

.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei 
.RE
.PP
\fBDate\fP
.RS 4
2002
.RE
.PP
.SH "Motivation"
.PP
The \fBTwoPhaseImplicitNodeCenteredFVTransport\fP module is provided to allow users to perform passive advection and advection of a single non-wetting phase in two-phase flow simulations\&. It represents the fastest but CFL dependent transport scheme for arbitrary FE meshes including different FE types and mixes of volume and surface elements\&. 
.br

.PP
The scheme is also very tolerant in that no specific boundary conditions need to be applied\&. The value of the advected variable at inflow boundaries is not modified and governs what gets transported into the model domain\&. 
.br
.SH "Design Intent"
.PP
The scheme has been designed to capitalize on the new generic polytype CVFE technology that is part of CSMP\&. 
.br
.SH "Applicability"
.PP
Use the scheme if the transport velocity field is rapidly changing or invalidated by the transport itself\&. In this case the scheme is faster that the implicit scheme embodied in the FiniteVolumeTransport module which starts to pay off at about CFL=20 or greater\&. 
.br

.PP
Do not use this scheme when the CFL condition based transport increment leads global advection steps that are smaller than about 1/1,000 of the model length in the direction of the flow\&. In this case the computations would be prohibitively slow\&.
.SH "Structure"
.PP
The user will only interact with the \fBTwoPhaseImplicitNodeCenteredFVTransport\fP module, but the FiniteVolumeAlgorithm is used to manage the accumulation and output of the solution in each transport step, and the FiniteVolumeProcessor class facilitates the generation of the finite-volume stencils from each finite element, so that the accumulation can proceed on an element by element basis and no FV mesh needs to be stored\&.
.SH "Collaboration"
.PP
The scheme collaborates with the finite elements of the current model\&.
.SH "Consequences"
.PP
This implementation of the scheme cannot be restricted to Regions, but always needs to be applied to the entire model, i\&.e\&. \fBModel\fP\&. 
.br

.PP
Currently it also only works for 3D models\&. Surface computations can still be done if the mesh consists entirely of surface elements in 3D space\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class STP> \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransport\fP< dim, STP >::TwoPhaseImplicitNodeCenteredFVTransport (const char * group_name, \fBModel\fP< dim > & sg, const char * porosity = \fR'porosity'\fP, const char * viscosity_n = \fR'viscosity carbonic phase'\fP, const char * viscosity_w = \fR'viscosity aqueous phase'\fP, const char * density_n = \fR'density carbonic phase'\fP, const char * density_w = \fR'density aqueous phase'\fP, const char * phase1_to_update = \fR'saturation aqueous phase'\fP, const char * phase2_to_advect = \fR'saturation carbonic phase'\fP, const char * transp_velocity = \fR'velocity'\fP, const char * nodal_source = \fR'nodal fluid volume source'\fP, bool with_capillary_spreading = \fRfalse\fP, bool with_gravitational_forces = \fRfalse\fP, const char * reference_variable_to_reference_variable_to_no_flow_bc = \fR'fluid pressure'\fP, bool nonlinear_scheme = \fRfalse\fP)"

.PP
First-order two-phase flow constructor, no capillary spreading, wetting phase=phase1\&. Constructor for the modelling of two-phase slightly compressible flow with fluid density and viscosity variations\&. The properties fluid density and viscosity are expected to be node variables and are interpolated to the FV facet integration points to carry out the computations\&. The transport scheme is setup for the non-wetting phase\&. The onus is on the user to update the second phase saturations after each advection step, i\&.e\&., calculate sw=1-sn\&. 
.br

.PP
The \fBTwoPhaseImplicitNodeCenteredFVTransport\fP can be constructed for first- and second order calculations\&. 
.br

.PP
Diffusion is only taken into account if second-order is chosen, because the first-order scheme already is so diffusive that adding an extra diffusion term makes little sense\&. 
.br
.SH "Input Arguments"
.PP
The \fBTwoPhaseImplicitNodeCenteredFVTransport\fP gains access via reference to the model to which it is applied to\&. The user needs to specify the piecewise constant element variables porosity, diffusivity and transport velocity\&. These must be defined in the CSP_variables\&.txt file\&. The variables fluid density and viscosity of the wetting and non-wetting phases must be nodal variables as well\&. They are interpolated to the facet and sector integration points using the finite element basis functions\&. 
.br

.PP
The transported variable must be nodal since this explicit transport scheme is based on node-centered finite volumes\&. 
.br
.SH "Implementation"
.PP
This constructor creates a minor storage array for repetitively used variables like the finite (pore) volumes, the flux balance for each FV cell and a \fBvector<double>\fP of FV_parameters called FV_stencil_data that holds the FV sector volumes, facet areas and facet normal fluxes which are always updated before the first advection step, when the CFL criterion is computed\&. This \fBvector<double>\fP will become redundant when the generic FV scheme has been optimized for speed\&. 
.br
.SH "Application Examples"
.PP
Use \fBTwoPhaseImplicitNodeCenteredFVTransport\fP as constructed with this particular constructor for two-phase flow in a rapidly evolving flow field that necessitates frequent updates of the velocity fields\&. 
.br

.PP
For a weak coupling between phase saturations and total mobility, use the implicit transport module FiniteVolumeTransport\&. 
.br
.SH "Messages"
.PP
The memory that is consumed during the construction process is reported\&.

.PP
Constructor for first-order scheme\&. 
.SS "template<uint32_t dim, template< uint32_t > class STP> \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransport\fP< dim, STP >::TwoPhaseImplicitNodeCenteredFVTransport (const char * group_name, \fBModel\fP< dim > & sg, const char * porosity, const char * diffusivity, const char * viscosity_n, const char * viscosity_w, const char * density_n, const char * density_w, const char * phase1_to_update, const char * phase2_to_advect, const char * transp_velocity, const char * nodal_source, bool with_capillary_spreading = \fRfalse\fP, bool with_gravitational_forces = \fRfalse\fP, const char * reference_variable_to_no_flow_bc = \fR'fluid pressure'\fP, bool nonlinear_scheme = \fRfalse\fP)"

.PP
First-order two-phase flow constructor, with capillary spreading modelled as non-linear diffusion\&. Constructor for the modelling of two-phase slightly compressible flow with fluid density and viscosity variations\&. The properties fluid density and viscosity are expected to be node variables and are interpolated to the FV facet integration points to carry out the computations\&. The transport scheme is setup for the non-wetting phase\&. The onus is on the user to update the second phase saturations after each advection step, i\&.e\&., calculate sw=1-sn\&.

.PP
The \fBTwoPhaseImplicitNodeCenteredFVTransport\fP can be constructed for first- and second order calculations\&.

.PP
Diffusion is only taken into account if second-order is chosen, because the first-order scheme already is so diffusive that adding an extra diffusion term makes little sense\&.
.SH "Input Arguments"
.PP
The \fBTwoPhaseImplicitNodeCenteredFVTransport\fP gains access via reference to the model to which it is applied to\&. The user needs to specify the piecewise constant element variables porosity, diffusivity and transport velocity\&. These must be defined in the CSP_variables\&.txt file\&. The variables fluid density and viscosity of the wetting and non-wetting phases must be nodal variables as well\&. They are interpolated to the facet and sector integration points using the finite element basis functions\&.

.PP
The transported variable must be nodal since this explicit transport scheme is based on node-centered finite volumes\&.
.SH "Implementation"
.PP
This constructor creates a minor storage array for repetitively used variables like the finite (pore) volumes, the flux balance for each FV cell and a \fBvector<double>\fP of FV_parameters called FV_stencil_data that holds the FV sector volumes, facet areas and facet normal fluxes which are always updated before the first advection step, when the CFL criterion is computed\&. This \fBvector<double>\fP will become redundant when the generic FV scheme has been optimized for speed\&.
.SH "Application Examples"
.PP
Use \fBTwoPhaseImplicitNodeCenteredFVTransport\fP as constructed with this particular constructor for two-phase flow in a rapidly evolving flow field that necessitates frequent updates of the velocity fields\&.

.PP
For a weak coupling between phase saturations and total mobility, use the implicit transport module FiniteVolumeTransport\&.
.SH "Messages"
.PP
The memory that is consumed during the construction process is reported\&. 
.SS "template<uint32_t dim, template< uint32_t > class STP> \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransport\fP< dim, STP >::TwoPhaseImplicitNodeCenteredFVTransport (const char * group_name, \fBModel\fP< dim > & sg, bool second_order_in_space, bool second_order_in_time, const char * porosity, const char * diffusivity, const char * viscosity_n, const char * viscosity_w, const char * density_n, const char * density_w, const char * phase1_to_update, const char * phase2_to_advect, const char * transp_velocity, const char * nodal_source, bool with_capillary_spreading = \fRfalse\fP, bool with_gravitational_forces = \fRfalse\fP, const char * reference_variable_to_no_flow_bc = \fR'fluid pressure'\fP, bool nonlinear_scheme = \fRfalse\fP)"

.PP
Second-order two-phase flow constructor, with capillary spreading modelled as non-linear diffusion\&. Second-order constructor, with capillary spreading 
.SS "template<uint32_t dim, template< uint32_t > class STP> \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransport\fP< dim, STP >::TwoPhaseImplicitNodeCenteredFVTransport (const char * group_name, \fBModel\fP< dim > & sg, bool second_order_in_space, bool second_order_in_time, const char * transp_velocity, bool with_capillary_forces, const char * thickness_low_dim_elmt = \fR'thickness'\fP, bool nonlinear_scheme = \fRfalse\fP)"

.PP
for field-scale simulation: with standard variables, gravity and thickness attribute for lower-dim elements Constructor for field-scale simulation:

.PP
with standard variables, gravity and thickness attribute for lower-dim elements, no-pc 
.SS "template<uint32_t dim, template< uint32_t > class STP> \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransport\fP< dim, STP >::~\fBTwoPhaseImplicitNodeCenteredFVTransport\fP ()\fR [virtual]\fP"
Frees all the allocated memory\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class STP> void \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransport\fP< dim, STP >::AdjustSolverSettings ()\fR [virtual]\fP"

.PP
add extra functionality for laternative solver add extra functionality for laternative solver
.PP
Reimplemented from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class STP> double \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransport\fP< dim, STP >::AnisotropicCourantIncrement (\fBTwoPhaseModel\fP< dim > & relperm, double max_time_increment)\fR [virtual]\fP"

.PP
two-phase, takes into account element shape in 2D and 3D unless one deals with 1D domain Computes the Courant time increment (CFL citerion) taking into account viscous, gravitational and capillary fluid displacements using the contraints from the provided relative permeability model\&. The CFL criterion is calculated using the element diameter in the direction of the flow but not account for the deviation from this \fBvector<double>\fP of the flow of the considered phase\&. 
.br

.PP
For the viscous flow the shock speed is used as a multiplier for the total velocity\&. This may lead to a too tight constraint but is safe for the case where CFL is computed only once at the onset of series of advection steps with an explicit scheme\&. 
.br
.SH "Input Arguments"
.PP
First, a const reference to the current model, a reference to the \fBTwoPhaseModel\fP used (this will be a subclass), and, third, the maximum time-increment imposed by external constraints\&. 
.br

.PP
\fBReturns\fP
.RS 4
The CFL criterion\&.
.RE
.PP
.SH "Implementation"
.PP
The criterion is computed sector by sector for all the finite elements in the entire model\&. 
.br
.SH "Application Examples"
.PP
Method has been designed primarily to give stability to an explicit transport scheme but it also serves as a guide for the timestepping using an implicit approach\&.
.SH "Messages"
.PP
The method alerts the user to the case where CFL is larger than the input max_time_increment which may be the case if there is no flow at all in the domain\&. Equally, the user is informed if the CFL increment is less than a millisecond (usually a prohibitively small increment)\&. 
.PP
Reimplemented from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class STP> double \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransport\fP< dim, STP >::TransportPhase (\fBTwoPhaseModel\fP< dim > & relperm, double time_interval)\fR [virtual]\fP"

.PP
transport of a non-wetting phase in 2-phase flow The method is the equivalent to \fBAdvectVariable()\fP for 2-phase flow\&. Thus, it advects the transport variable for the user-specified time interval and writes the results back to the current \fBModel\fP object\&. 
.br
.SH "Input Arguments"
.PP
The method takes a reference to the \fBModel\fP object which contains the transport variable field that shall be advected\&. The relative permeabilities and other 2-phase properties are obtained via the supplied 'AdvectionDiffusionTwoPhaseModel'\&. The onus is on the user to make sure that the necessary variables are defined and initialized\&. The third method argument is the time interval over which the transport variable shall be advected\&. 
.br

.PP
\fBReturns\fP
.RS 4
The advected variable field is written back into the supplied \fBModel\fP\&. The method returns the CFL condition that it determined before the onset of the advection\&.
.RE
.PP
.SH "Implementation"
.PP
The CFL_FACTOR is a multiplier that represents the maximum factor by which the diameter of the idealized spherical FV can be multiplied while the transport scheme is stable\&. 
.PP
Reimplemented from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
