.TH "csmp::CompressedRowMatrix" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CompressedRowMatrix \- CSMP's implementation of a compressed-row storage container for sparse matrices\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CompressedRowMatrix\&.h>\fP
.PP
Inherited by \fBcsmp::CompressedRowMatrixParallel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompressedRowMatrix\fP (\fBcsmp::SparseMatrix\fP &)"
.br
.ti -1c
.RI "\fBCompressedRowMatrix\fP (std::vector< int32_t > &&\fBia\fP, std::vector< int32_t > &&\fBja\fP, std::vector< double > &&\fBa\fP)"
.br
.RI "custom move constructor "
.ti -1c
.RI "double \fBoperator()\fP (uint32_t, uint32_t) const"
.br
.RI "standard accessor of matrix elements (asserts i,j in debug mode) "
.ti -1c
.RI "double \fBAt\fP (uint32_t, uint32_t) const"
.br
.RI "range-checked accessor for matrix elements "
.ti -1c
.RI "void \fBAssign\fP (uint32_t i, uint32_t j, double val)"
.br
.RI "use to assign matrix elements during accumulation; "
.ti -1c
.RI "void \fBMultiplyEntryWith\fP (uint32_t i, uint32_t j, double val)"
.br
.ti -1c
.RI "void \fBAdd\fP (uint32_t i, uint32_t j, double val)"
.br
.ti -1c
.RI "void \fBZeroRow\fP (size_t row)"
.br
.ti -1c
.RI "void \fBZero\fP ()"
.br
.ti -1c
.RI "void \fBAddRowByAnotherRow\fP (uint32_t i, uint32_t j)"
.br
.ti -1c
.RI "void \fBAssignRowByAnotherRow\fP (uint32_t i, uint32_t j)"
.br
.ti -1c
.RI "void \fBInitialize\fP (const \fBcsmp::SparseMatrix\fP &)"
.br
.ti -1c
.RI "void \fBInitializePointBased\fP (const \fBSparseMatrix\fP &, size_t nsys)"
.br
.ti -1c
.RI "uint32_t \fBRows\fP () const"
.br
.ti -1c
.RI "uint32_t \fBCols\fP () const"
.br
.ti -1c
.RI "size_t \fBTotalExistingEntries\fP () const"
.br
.ti -1c
.RI "size_t \fBNonZeroEntries\fP () const"
.br
.RI "total number of available storage sites for non-zero matrix elements "
.ti -1c
.RI "void \fBErase\fP ()"
.br
.RI "this function erases all elements in ia, ja and a "
.ti -1c
.RI "bool \fBIsFormattedForSAMG\fP () const"
.br
.RI "check whether matrix has been converted to SAMG format "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP (const std::string &outfile) const"
.br
.ti -1c
.RI "void \fBConvertFromSparseMatrix\fP (const \fBcsmp::SparseMatrix\fP &)"
.br
.RI "this function converts the supplies sparse matrix to compressed row matrix, but does not convert it to SAMG format "
.ti -1c
.RI "void \fBConvertToSAMGFormat\fP ()"
.br
.RI "this function converts a compressed row matrix to SAMG format "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< int32_t > \fBia\fP"
.br
.RI "\fBia(ilo)\fP and the last row ends at position ia(ihi+1)-1 (see next)\&. "
.ti -1c
.RI "std::vector< int32_t > \fBja\fP"
.br
.RI "ja - pointer array pointing to the column indices\&. that is, for each matrix element \fBa(j)\fP with \fBia(ilo)\fP<=j<=ia(ihi+1)-1, \fBja(j)\fP contains the column index of that element\&. since, within each row, the diagonal element is stored first (see above), we always have \fBja(ia(i))\fP=i\&. "
.ti -1c
.RI "std::vector< double > \fBa\fP"
.br
.RI "array containing the rows of the matrix, one after the other, each row starting with its diagonal element\&. the first row starts at position "
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBverbose_\fP = true"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEigenSolver\fP"
.br
.ti -1c
.RI "class \fBSAMG_Solver\fP"
.br
.ti -1c
.RI "class \fBCompressedRowMatrix_Test\fP"
.br
.ti -1c
.RI "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBgenerateSparsityPatternEliminatingEssentialConditions\fP (\fBCompressedRowMatrix\fP &G, const std::map< \fBParameter\fP, size_t > &test_operands, std::vector< size_t > &DOF_indexes, const \fBModelSubDomain\fP< dim, CELLTYPE > &gref)"
.br
.RI "this standalone function generates sparsity pattern for a compressed row matrix from supplied test_operands_, DOF_indexes_ and computational domain, taking into account elimination of essential conditions "
.in -1c
.SH "Detailed Description"
.PP 
CSMP's implementation of a compressed-row storage container for sparse matrices\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
SS\&. Geiger 

.PP
Coumou, D\&. 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
2006 
.RE
.PP
\fBAuthor\fP
.RS 4
Qi Shao 
.RE
.PP
\fBDate\fP
.RS 4
2022(modified)
.RE
.PP
This class implements the classic condensed row storage format for sparse matrices that is common to many linear algebra packages\&. This matrix is always square\&.

.PP
Currently used to convert \fBcsmp::SparseMatrix\fP objects before they are passed to the SAMG solver\&. Now also directly used in \fBPDE_Integrator\fP (2022, Qi Shao) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::CompressedRowMatrix::CompressedRowMatrix (\fBcsmp::SparseMatrix\fP & spmat)\fR [explicit]\fP"
this constructor constructs a compressed row matrix from the supplied sparse matrix by calling the Initialise function the constructed compressed row matrix is in SAMG format which has the diagonal term at the beginning of each row and fortran indexes\&. 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::CompressedRowMatrix::Assign (uint32_t i, uint32_t j, double val)"

.PP
use to assign matrix elements during accumulation; 
.PP
\fBAttention\fP
.RS 4
matrix sparsity pattern must be established before 
.RE
.PP

.SS "double csmp::CompressedRowMatrix::At (uint32_t i, uint32_t j) const"

.PP
range-checked accessor for matrix elements range checked random access function that reports out of bound and missing element errors 
.PP
\fBParameters\fP
.RS 4
\fIi\fP row index 
.br
\fIj\fP column index 
.RE
.PP
\fBReturns\fP
.RS 4
double matrix element 
.RE
.PP

.SS "void csmp::CompressedRowMatrix::Initialize (const \fBcsmp::SparseMatrix\fP & A)"
Initialize function called by constructor to initialize a compressed row matrix from a supplied sparse matrix it also converts the matrix to SAMG format which has the diagonal term at the beginning of each row and fortran indexes\&.

.PP
Initialises the public \fBCompressedRowMatrix\fP vectors ia, ja, a from the given \fBcsmp::SparseMatrix\fP\&. 
.br

.PP
\fBParameters\fP
.RS 4
\fIA\fP The fully accumulated global solution matrix\&.
.RE
.PP
.SH "Implementation"
.PP
If nnu denotes the number of rows (variables), the non-zero entries of the i-th row (1 ≤ i ≤ nnu) are stored in \fBa(j)\fP where

.PP
\fBia(i)\fP ≤ j ≤ ia(i+1)-1\&.

.PP
In particular, according to the above-mentioned convention about the location of the diagonal element, \fBa(ia(i))\fP contains the diagonal entry of row i\&. Note that \fBia(1)\fP = 1 and ia(nnu+1) = nna+1 where nna denotes the total number of matrix entries stored\&.

.PP
ia, ja define the order of the off-diagonal elements in the solution matrix storage vector a (that holds them row by row)\&.

.PP
The pointer vector ja has to be defined so that \fBja(j)\fP (1 ≤ j ≤ nna) equals the original matrix’ column index of \fBa(j)\fP, ie, \fBa(j)\fP corresponds to the variable u(ja(j))\&. In particular, since \fBa(ia(i))\fP contains the diagonal entry of row i, we have \fBja(ia(i))\fP=i\&.

.PP
While, in the compressed row format, all diagonal entries must be stored, off-diagonal entries are only stored if they are non-zero\&. 
.br
.SH "Application Examples"
.PP
Transfer of the global solution matrix to conventional solvers\&. 
.br
.SH "Messages"
.PP
Reports if the solution matrix contains zero diagonal entries\&. 
.SS "void csmp::CompressedRowMatrix::InitializePointBased (const \fBSparseMatrix\fP & A, size_t nsys)"
Initialises the public \fBCompressedRowMatrix\fP vectors ia, ja, a for given \fBSparseMatrix\fP in case the Point-based approach is selected\&. 
.SS "bool csmp::CompressedRowMatrix::IsFormattedForSAMG () const"

.PP
check whether matrix has been converted to SAMG format Check whether the compressed row matrix has been converted into SAMG format\&. 
.SS "void csmp::CompressedRowMatrix::Out () const"
Outputs matrix to screen\&. 
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void generateSparsityPatternEliminatingEssentialConditions (\fBCompressedRowMatrix\fP & G, const std::map< \fBParameter\fP, size_t > & test_operands, std::vector< size_t > & DOF_indexes, const \fBModelSubDomain\fP< dim, CELLTYPE > & gref)\fR [friend]\fP"

.PP
this standalone function generates sparsity pattern for a compressed row matrix from supplied test_operands_, DOF_indexes_ and computational domain, taking into account elimination of essential conditions generates sparsity pattern based on mesh connectivity information (i\&.e\&., neighbouring nodes) manifold nodes are also taken into account ia and ja are initialised, and values in a are initialised to zeros elimination of essential conditions is taken into account 
.SH "Member Data Documentation"
.PP 
.SS "std::vector<int32_t> csmp::CompressedRowMatrix::ia\fR [protected]\fP"

.PP
\fBia(ilo)\fP and the last row ends at position ia(ihi+1)-1 (see next)\&. ia stores the starting point/index for each row; its size equals num_rows + 1 ja stores the column indices of all non-zero entries a stores the values of all non-zero entries 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
