.TH "csmp::CGNS_ElementSpecifications" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CGNS_ElementSpecifications
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCGNS_Type\fP (const std::string &FEtype) const"
.br
.ti -1c
.RI "std::string \fBCGNS_TypeName\fP (int) const"
.br
.ti -1c
.RI "int \fBCGNS_TypeFrom_CSMP_Type\fP (int CSMP_finite_element_type) const"
.br
.RI "from csmp to cgns "
.ti -1c
.RI "int \fBCGNS_TypeFrom_CSMP_TypeName\fP (const std::string &CSMP_finite_element_type) const"
.br
.ti -1c
.RI "std::string \fBCGNS_TypeNameFrom_CSMP_Type\fP (int CSMP_finite_element_type) const"
.br
.ti -1c
.RI "std::string \fBCGNS_TypeNameFrom_CSMP_TypeName\fP (const std::string &CSMP_finite_element_type) const"
.br
.ti -1c
.RI "\fBcsmp::CSMP_FEM_TYPE\fP \fBCSMP_TypeFrom_CGNS_Type\fP (int CGNS_finite_element_type, bool isoparametric, uint32_t dim) const"
.br
.RI "from cgns to csmp "
.ti -1c
.RI "\fBcsmp::CSMP_FEM_TYPE\fP \fBCSMP_TypeFrom_CGNS_TypeName\fP (const std::string &CGNS_finite_element_type, bool isoparametric, uint32_t dim) const"
.br
.ti -1c
.RI "std::string \fBCSMP_TypeNameFrom_CGNS_Type\fP (int CGNS_finite_element_type, bool isoparametric, uint32_t dim) const"
.br
.ti -1c
.RI "std::string \fBCSMP_TypeNameFrom_CGNS_TypeName\fP (const std::string &CGNS_finite_element_type, bool isoparametric, uint32_t dim) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
R\&.Manasipov 
.RE
.PP
\fBDate\fP
.RS 4
2015 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int csmp::CGNS_ElementSpecifications::CGNS_Type (const std::string & cgns_FEtype) const"
Map between CGNS integer flag corresponding to the CGNS element name string\&. 
.SS "\fBcsmp::CSMP_FEM_TYPE\fP csmp::CGNS_ElementSpecifications::CSMP_TypeFrom_CGNS_Type (int etype, bool isoparametric, uint32_t dim) const"

.PP
from cgns to csmp Returns the CSP finite element type enum identifier that corresponds to the CGNS type as identified by an integer identifier\&. The user needs to specify whether an isoparametric or globally interpolated element shall be returned because CGNS elements can be converted into both\&.

.PP
Note however that CGNS fits quadratic or cubic elements to the bounding curves\&. Thus, global interpolation will give incorrect results as it works only for straight-sided elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
