.TH "csmp::IsoparametricQuadraticTetrahedron_Test" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::IsoparametricQuadraticTetrahedron_Test
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IsoparametricQuadraticTetrahedron_Test\&.h>\fP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsoparametricQuadraticTetrahedron_Test\fP (bool verbose)"
.br
.ti -1c
.RI "\fB~IsoparametricQuadraticTetrahedron_Test\fP ()"
.br
.RI "releasing the dynamic memory "
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.ti -1c
.RI "bool \fBTestIntegrationPointPlacement\fP ()"
.br
.ti -1c
.RI "void \fBTestInterpolationFunctionValues\fP (const \fBElement\fP< 3U > &)"
.br
.ti -1c
.RI "void \fBTestSumOfInterpolationFunctionValuesEqualTo1\fP (const \fBElement\fP< 3U > &)"
.br
.ti -1c
.RI "void \fBCheckElementFaceConsistency\fP (const \fBElement\fP< 3U > &)"
.br
.ti -1c
.RI "void \fBCheckInterpolation\fP (const \fBElement\fP< 3U > &)"
.br
.ti -1c
.RI "void \fBOutputIntegrationPointsToVTK\fP (const char *file, const \fBElement\fP< 3U > &) const"
.br
.ti -1c
.RI "void \fBOutputFaceNormalsToVTK\fP (const char *file, const \fBElement\fP< 3U > &) const"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Testing:

.PP
.IP "1." 4
Interpolation functions at all nodes = 1; 0 at all other nodes
.IP "2." 4
Placement of integration points is correct
.IP "3." 4
Interpolation functions at up to 1 at all integration points 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::IsoparametricQuadraticTetrahedron_Test::IsoparametricQuadraticTetrahedron_Test (bool verbose)\fR [explicit]\fP"
building a quadratic tetrahedron 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::IsoparametricQuadraticTetrahedron_Test::CheckElementFaceConsistency (const \fBElement\fP< 3U > & e)"
Checks that the face normals are pointing correctly and computes face flux balance over all faces of the element\&. This should be zero\&.

.PP
\fBTodo\fP
.RS 4
check how accurate this result can be expected to be? 
.RE
.PP

.SS "void csmp::IsoparametricQuadraticTetrahedron_Test::CheckInterpolation (const \fBElement\fP< 3U > & e)"
Assigns a nodal field of variable values that then gets interpolated across the element\&. The values of this field variable are equivalent to the position ot the integration points in physical space\&. This relationship is used for the testing\&.

.PP
\fBTest\fP
.RS 4
OK SKM 3/9/14 
.RE
.PP

.SS "void csmp::IsoparametricQuadraticTetrahedron_Test::OutputFaceNormalsToVTK (const char * file, const \fBElement\fP< 3U > & e) const"
Loops over the faces of the element, collecting the (outward-pointing) face normals for display in VTK\&. Each normal is scaled by the sqrt of the element volume and placed with its origin on the barycenter of the corresponding face\&. 
.SS "void csmp::IsoparametricQuadraticTetrahedron_Test::OutputIntegrationPointsToVTK (const char * file, const \fBElement\fP< 3U > & e) const"
The integration points are coloured by number and are then output to VTK file\&. \fBPoint\fP 1=0, point2=1\&.\&.\&.n-1\&. 
.SS "void csmp::IsoparametricQuadraticTetrahedron_Test::run ()\fR [virtual]\fP"
Running the tests:

.PP
.IP "1." 4
Correct representation of element in physical space (node numbering and VTK output)
.IP "2." 4
Correct location of integration points
.IP "3." 4
Interpolation functions
.IP "  \(bu" 4
must be 1 at their node and 0 everywhere else
.IP "  \(bu" 4
their sum should be 1 at any point inside of element
.PP

.IP "4." 4
Interpolation function derivatives
.IP "  \(bu" 4
correct location (consistency with interpolation functions)
.IP "  \(bu" 4
correct orientation in parametric space
.IP "  \(bu" 4
correct orientation in physical space
.PP

.IP "5." 4
Jacobian transformation
.IP "  \(bu" 4
all scaling parameters should be one for an element in physical space with same coordinates as in parametric space
.IP "  \(bu" 4
lower to higher dim Jacobians
.IP "  \(bu" 4
efficiency of Jacobian calculations
.PP

.IP "6." 4
Volume correctness in parametric and physical space
.IP "7." 4
Interpolation of integration point values to nodes 
.PP

.PP
Implements \fBcsmp::Test\fP\&.
.SS "void csmp::IsoparametricQuadraticTetrahedron_Test::TestInterpolationFunctionValues (const \fBElement\fP< 3U > & e)"
Testing the interpolation functions:

.PP
Are the 1 at the corresponding node and zero everywhere else? 
.SS "void csmp::IsoparametricQuadraticTetrahedron_Test::TestSumOfInterpolationFunctionValuesEqualTo1 (const \fBElement\fP< 3U > & e)"
Tests that interpolation function values sum up to one at:
.IP "\(bu" 2
integration points
.IP "\(bu" 2
barycentre
.PP

.PP
\fBAttention\fP
.RS 4
IPOL values at the nodes are tested by TestInterpolationFunctionValues 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
