.TH "csmp::SandPropertiesFor_VE_Model" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SandPropertiesFor_VE_Model
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SandPropertiesFor_VE_Model\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSandPropertiesFor_VE_Model\fP (const \fBModel\fP< 2U > &model, const std::string &dimM1_region_name, double bcp, double swr, double snr)"
.br
.RI "original properties that the model returns the distributed parameters to once the specific computation has been done "
.ti -1c
.RI "\fBSandPropertiesFor_VE_Model\fP (const \fBModel\fP< 3U > &model, const std::string &dimM1_region_name, double bcp, double swr, double snr)"
.br
.ti -1c
.RI "void \fBCompute2PhaseFlowPropertiesForSandLayer\fP (\fBModel\fP< 2U > &)"
.br
.RI "specific version that only works for line elements in a two dimensional model "
.ti -1c
.RI "bool \fBHasLineElementRepresentation\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class is used to initialise uniform properties of lower-dimensional sandbodies so that an application of the Brooks-Corey model will yied the correct input parameters for an element with a certain dip etc\&.

.PP
While the model needs 'total velocity' as an input, all other properties are calculated locally\&. 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::SandPropertiesFor_VE_Model::Compute2PhaseFlowPropertiesForSandLayer (\fBModel\fP< 2U > & model)"

.PP
specific version that only works for line elements in a two dimensional model Computes multiphase flow parameters for the finite volumes associated with the line elements of the lower-dimensional region associated with the sand properties object\&.

.PP
\fBAttention\fP
.RS 4
method must be called after the standard multiphase properties were calculated because it uses these property values\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
