.TH "csmp::PolygonGridManager" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::PolygonGridManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolygonGridManager\fP (const \fBPolygonGridManager\fP &)"
.br
.ti -1c
.RI "\fBPolygonGridManager\fP & \fBoperator=\fP (const \fBPolygonGridManager\fP &)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "size_t \fBGetNumNodes\fP () const"
.br
.RI "nodes "
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetPoint\fP (size_t nid) const"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetNode\fP (size_t nid)"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetNode\fP (const \fBcsmp::Point\fP< 3U > &)"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBAddNode\fP (const \fBcsmp::Point\fP< 3U > &)"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "prints object state to screen "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBGridNode\fP * csmp::PolygonGridManager::AddNode (const \fBcsmp::Point\fP< 3U > & pt)"
Methods dynamically allocates nodes on the heap, storing the pointers to them in the grid_nodes_ array, but also returning them to its caller\&.

.PP
\fBTodo\fP
.RS 4
SKM: when vector is resized all the stored pointers will be invalidated during rereconstruction; avoid! 
.RE
.PP

.SS "void csmp::PolygonGridManager::Clear ()"
deleting the grid nodes that the pointers in the grid_nodes vector point to\&. delete nodes

.PP
clear points

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
