.TH "csmp::SmallSet< T, N >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SmallSet< T, N >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SmallSet\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::vector< T >::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef std::vector< T >::const_iterator \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::pair< iterator, bool > \fBinsert\fP (const value_type &value)"
.br
.ti -1c
.RI "std::pair< iterator, bool > \fBinsert\fP (value_type &&value)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "const_iterator \fBend\fP () const"
.br
.ti -1c
.RI "iterator \fBfind\fP (const value_type &value)"
.br
.ti -1c
.RI "const_iterator \fBfind\fP (const value_type &value) const"
.br
.ti -1c
.RI "void \fBerase\fP (const value_type &value)"
.br
.ti -1c
.RI "size_t \fBcount\fP (const value_type &value) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, unsigned N = 32>
.br
class csmp::SmallSet< T, N >"A small set of trivial types, represented as a sorted vector\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
