.TH "csmp::Box" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Box \- brings together all functionality needed to deal with \fBBox\fP shaped models whose boundaries are identified by \fBBOX_BOUNDARY\fP flags\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Box\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUnitNormalTo\fP (\fBBOX_BOUNDARY\fP bdry, uint32_t dim, std::vector< double > &nrml) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
brings together all functionality needed to deal with \fBBox\fP shaped models whose boundaries are identified by \fBBOX_BOUNDARY\fP flags\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
