.TH "csmp::HeterogeneityAndRateAwareSaturationFunctions< dim, USER >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::HeterogeneityAndRateAwareSaturationFunctions< dim, USER >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeterogeneityAndRateAwareSaturationFunctions\fP ()"
.br
.ti -1c
.RI "double \fBEffectiveSaturation_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.RI "get seff from the supplied saturation value "
.ti -1c
.RI "double \fBpc_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBpc_at_BrookCorey\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBpc_at_VanGenuchten\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdpcds_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdpcds_at_BC\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdpcds_at_VG\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBkrw_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBkrn_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdkrwds_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdkrnds_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdpcds_at_Numerical\fP (\fBElement\fP< dim > *const, double sw, double \fBh\fP=0\&.00001) const"
.br
.ti -1c
.RI "double \fBdpcds_at_Numerical_BC\fP (\fBElement\fP< dim > *const, double sw, double \fBh\fP=0\&.00001) const"
.br
.ti -1c
.RI "double \fBdpcds_at_Numerical_VG\fP (\fBElement\fP< dim > *const, double sw, double \fBh\fP=0\&.00001) const"
.br
.ti -1c
.RI "double \fBdkrwds_at_Numerical\fP (\fBElement\fP< dim > *const, double sw, double delta_s=0\&.001) const"
.br
.ti -1c
.RI "double \fBdkrnds_at_Numerical\fP (\fBElement\fP< dim > *const, double sw, double delta_s=0\&.001) const"
.br
.ti -1c
.RI "double \fBEffectiveSaturation\fP (\fBElement\fP< dim > *const) const"
.br
.RI "get seff at the element barycentre "
.ti -1c
.RI "double \fBpc\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBpc_BrookCorey\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBpc_VanGenuchten\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBdpcds\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBdpcds_BC\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBdpcds_VG\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBkrw\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBkrn\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBdkrwds\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBdkrnds\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBMaxCapillaryPressure\fP () const"
.br
.RI "maximum value of pc (Pa) "
.ti -1c
.RI "double \fBdkrwds_Numerical\fP (\fBElement\fP< dim > *const, double delta_s=0\&.001) const"
.br
.RI "Numerical derivatives of first derivatives of relative permeability of water and CO2\&. "
.ti -1c
.RI "double \fBdkrnds_Numerical\fP (\fBElement\fP< dim > *const, double delta_s=0\&.001) const"
.br
.ti -1c
.RI "double \fBdpcds_Numerical\fP (\fBElement\fP< dim > *const, double \fBh\fP=0\&.00001) const"
.br
.ti -1c
.RI "double \fBdpcds_Numerical_BC\fP (\fBElement\fP< dim > *const, double \fBh\fP=0\&.00001) const"
.br
.ti -1c
.RI "double \fBdpcds_Numerical_VG\fP (\fBElement\fP< dim > *const, double \fBh\fP=0\&.00001) const"
.br
.ti -1c
.RI "void \fBInitilizeRockProperties\fP (\fBElement\fP< dim > *const e) const"
.br
.RI "New functions\&. "
.ti -1c
.RI "double \fBGetSwr\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetSnr\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetK\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetKV\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetPhi\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetSwiPc\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetmVG\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetmLow\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetPd\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetPd_VG\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetPdLow\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetBcp\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetKrw\fP (\fBElement\fP< dim > *const e, double Sw) const"
.br
.ti -1c
.RI "double \fBGetKrn\fP (\fBElement\fP< dim > *const e, double Sw) const"
.br
.ti -1c
.RI "double \fBGetKrwParallelDrainage\fP (\fBElement\fP< dim > *const e, double Sw) const"
.br
.ti -1c
.RI "double \fBGetKrwParallelDrainage\fP (\fBElement\fP< dim > *const e, double Sw, double vt_magnitude) const"
.br
.ti -1c
.RI "double \fBGetKrwCrossDrainage\fP (\fBElement\fP< dim > *const e, double Sw) const"
.br
.ti -1c
.RI "double \fBGetKrwCrossDrainage\fP (\fBElement\fP< dim > *const e, double Sw, double vt_magnitude) const"
.br
.ti -1c
.RI "double \fBGetKrnParallelDrainage\fP (\fBElement\fP< dim > *const e, double Sw) const"
.br
.ti -1c
.RI "double \fBGetKrnParallelDrainage\fP (\fBElement\fP< dim > *const e, double Sw, double vt_magnitude) const"
.br
.ti -1c
.RI "double \fBGetKrnCrossDrainage\fP (\fBElement\fP< dim > *const e, double Sw) const"
.br
.ti -1c
.RI "double \fBGetKrnCrossDrainage\fP (\fBElement\fP< dim > *const e, double Sw, double vt_magnitude) const"
.br
.ti -1c
.RI "double \fBGetLYLow\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetLYHigh\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetKLow\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBGetKHigh\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "int32_t \fBRockType\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "bool \fBIsComposite\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBBcp\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBBcp_low\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "\fBVectorVariable\fP< dim > \fBInitializeVelocity\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBkrw_parallel\fP (\fBElement\fP< dim > *const e, int direction) const"
.br
.ti -1c
.RI "double \fBkrw_crossflow\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBkrw_parallel_at\fP (\fBElement\fP< dim > *const e, double Sw, int direction) const"
.br
.ti -1c
.RI "double \fBkrw_crossflow_at\fP (\fBElement\fP< dim > *const e, double Sw) const"
.br
.ti -1c
.RI "double \fBPermeabilityPerpendicularToLaminations\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBPermeabilityParallelToLaminations\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBPermeabilityInFlowDirection\fP (\fBElement\fP< dim > *const e, const \fBTensorVariable\fP< dim > &KK) const"
.br
.ti -1c
.RI "double \fBK_reduction_in_flow_direction\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBkrn_parallel\fP (\fBElement\fP< dim > *const e, int direction) const"
.br
.ti -1c
.RI "double \fBkrn_crossflow\fP (\fBElement\fP< dim > *const e) const"
.br
.ti -1c
.RI "double \fBkrn_parallel_at\fP (\fBElement\fP< dim > *const e, double Sw, int direction) const"
.br
.ti -1c
.RI "double \fBkrn_crossflow_at\fP (\fBElement\fP< dim > *const e, double Sw) const"
.br
.ti -1c
.RI "void \fBWriteRelativePermeabilityTable\fP (const char *filename, long RT, \fBElement\fP< dim > *const e)"
.br
.ti -1c
.RI "void \fBOutputTestingResults\fP (\fBElement\fP< dim > *const e)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class USER> \fBcsmp::HeterogeneityAndRateAwareSaturationFunctions\fP< dim, USER >::HeterogeneityAndRateAwareSaturationFunctions ()"
The default constructor of Brooks \fBCorey\fP Saturation Functions class 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::HeterogeneityAndRateAwareSaturationFunctions\fP< dim, USER >::dkrnds (\fBElement\fP< dim > * const e) const"
calculating the 1st derivative of oil relative permeability 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::HeterogeneityAndRateAwareSaturationFunctions\fP< dim, USER >::dkrnds_at (\fBElement\fP< dim > * const e, double sw) const"
calculating the 1st derivative of oil relative permeability for any water saturations 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::HeterogeneityAndRateAwareSaturationFunctions\fP< dim, USER >::dkrwds (\fBElement\fP< dim > * const e) const"
calculating the 1st derivative of water relative permeability 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::HeterogeneityAndRateAwareSaturationFunctions\fP< dim, USER >::dkrwds_at (\fBElement\fP< dim > * const e, double sw) const"
calculating the 1st derivative of water relative permeability for any water saturation 
.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::HeterogeneityAndRateAwareSaturationFunctions\fP< dim, USER >::WriteRelativePermeabilityTable (const char * filename, long RT, \fBElement\fP< dim > *const e)"
writes textfile with sw, krw(sw,Nc), krn(sw,Nc), and pc(sw) values computed for (composite) rocktype in 0\&.005 saturation increments 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
