.TH "csmp::H2OLookup" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::H2OLookup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBVaporProperty\fP (const long &it, const int &property_index)"
.br
.ti -1c
.RI "double \fBLiquidProperty\fP (const long &it, const int &property_index)"
.br
.ti -1c
.RI "double \fBVaporProperty\fP (const double &t, const int &property_index)"
.br
.ti -1c
.RI "double \fBLiquidProperty\fP (const double &t, const int &property_index)"
.br
.ti -1c
.RI "double \fBSinglePhaseProperty\fP (const long &it, const long &ip, const int &property_index)"
.br
.ti -1c
.RI "double \fBSinglePhaseProperty\fP (const double &t, const double &p, const int &property_index)"
.br
.ti -1c
.RI "double \fBTfromP\fP (const double &press)"
.br
.ti -1c
.RI "double \fBSaturationTemperatureFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBLiquidDensityFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBVaporDensityFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBLiquidEnthalpyFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBVaporEnthalpyFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBLiquidHeatCapacityFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBVaporHeatCapacityFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBLiquidViscosityFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBVaporViscosityFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBLiquidCompressibilityFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBVaporCompressibilityFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBSaturationPressureFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBDSaturationPressureFromTDT\fP (double t)"
.br
.ti -1c
.RI "double \fBLiquidDensityFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBVaporDensityFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBLiquidEnthalpyFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBVaporEnthalpyFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBLiquidHeatCapacityFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBVaporHeatCapacityFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBLiquidViscosityFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBVaporViscosityFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBLiquidCompressibilityFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBVaporCompressibilityFromT\fP (double t)"
.br
.ti -1c
.RI "double \fBDensity\fP (double t, double p)"
.br
.ti -1c
.RI "double \fBHeatCapacity\fP (double t, double p)"
.br
.ti -1c
.RI "double \fBEnthalpy\fP (double t, double p)"
.br
.ti -1c
.RI "double \fBViscosity\fP (double t, double p)"
.br
.ti -1c
.RI "double \fBCompressibility\fP (double t, double p)"
.br
.ti -1c
.RI "double \fBMolarVolume\fP (double t, double p)"
.br
.ti -1c
.RI "double \fBLiquidMolarVolumeFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBVaporMolarVolumeFromP\fP (double p)"
.br
.ti -1c
.RI "double \fBDvdt\fP (double t, double p)"
.br
.ti -1c
.RI "double \fBDvdpbar\fP (double t, double p)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
