.TH "csmp::femDataOutputDispatch" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::femDataOutputDispatch \- additions by P\&. Lang (2012); SKM  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Var> void \fBinitVariable\fP (\fBcsmp::Index\fP, Var &)"
.br
.ti -1c
.RI "template<> void \fBinitVariable\fP (\fBcsmp::Index\fP key, \fBArrayVariable\fP &var)"
.br
.ti -1c
.RI "template<> void \fBinitVariable\fP (\fBcsmp::Index\fP key, \fBFlaggedArrayVariable\fP &var)"
.br
.in -1c
.SH "Detailed Description"
.PP 
additions by P\&. Lang (2012); SKM 


.PP
\fBTodo\fP
.RS 4
explain what this is good for 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
