.TH "csmp::PARDISO_Solver" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::PARDISO_Solver
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PARDISO_Solver\&.h>\fP
.PP
Inherits \fBcsmp::Solver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPARDISO_Solver\fP (\fBPARDISO_SolverSettings\fP &)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Solver\fP
.in +1c
.ti -1c
.RI "\fBSolver\fP ()"
.br
.ti -1c
.RI "\fBSolver\fP (\fBSolverSettings\fP *settings)"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verb)"
.br
.ti -1c
.RI "bool \fBVerbose\fP () const"
.br
.ti -1c
.RI "void \fBSolve\fP (\fBSparseMatrix\fP &G, std::vector< double > &rh, std::vector< double > &x, size_t no_unknowns=1U)"
.br
.ti -1c
.RI "void \fBSolve\fP (\fBCompressedRowMatrix\fP &G, std::vector< double > &rh, std::vector< double > &x, size_t no_unknowns=1U)"
.br
.ti -1c
.RI "void \fBOut\fP (const \fBSparseMatrix\fP &mat, const char *fname='SparseMatrix') const"
.br
.ti -1c
.RI "void \fBOut\fP (const std::vector< double > &vec, const char *fname='CSP_Vec') const"
.br
.ti -1c
.RI "double \fBCalculateResidual\fP (const \fBSparseMatrix\fP &A, const std::vector< double > &b, const std::vector< double > &x) const"
.br
.ti -1c
.RI "virtual void \fBInputSolverSettings\fP (\fBSolverSettings\fP &settings)"
.br
.ti -1c
.RI "virtual \fBSolverSettings\fP * \fBGetSolverSettings\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSolveMatrixEquation\fP (\fBcsmp::SparseMatrix\fP &A, std::vector< double > &b, std::vector< double > &x, double solver_tolerance)"
.br
.in -1c

Protected Member Functions inherited from \fBcsmp::Solver\fP
.in +1c
.ti -1c
.RI "virtual void \fBSolveMatrixEquation\fP (\fBSparseMatrix\fP &A, std::vector< double > &b, std::vector< double > &x, size_t no_unknowns)=0"
.br
.ti -1c
.RI "virtual void \fBSolveMatrixEquation\fP (\fBCompressedRowMatrix\fP &A, std::vector< double > &b, std::vector< double > &x, size_t no_unknowns)=0"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Solver\fP
.in +1c
.ti -1c
.RI "\fBSolverSettings\fP * \fBsolver_settings_\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface to the direct PARDISO solver from the MKL library\&. Derived from \fBSolver\fP class, following CSMP's strategy design pattern for the solution of linear algebraic systems of equations\&.

.PP
\fBNote\fP
.RS 4
works only if there is access to the MKL library\&.
.RE
.PP
\fBAuthor\fP
.RS 4
draft SKM 
.RE
.PP
\fBDate\fP
.RS 4
30/7/2019 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void csmp::PARDISO_Solver::SolveMatrixEquation (\fBcsmp::SparseMatrix\fP & A, std::vector< double > & b, std::vector< double > & x, double tolerance)\fR [protected]\fP, \fR [virtual]\fP"
Some notes (SKM):

.PP
.IP "\(bu" 2
Since PARDISO is written in C, extern "C" declarations are needed for MKL functions\&. For example
.IP "\(bu" 2
good news: PARDISO is free for academic user, just register and download
.IP "\(bu" 2
parameters are rather similar to those used by SAMG, so much of the code can be copied from SAMG_Solver\&.cpp
.IP "\(bu" 2
C++ examples in mklroot\\solverc\\source\\ directory
.IP "\(bu" 2
Intel MKL PARDISO is a direct sparse solver based on Parallel Direct Sparse \fBSolver\fP PARDISO*), an iterative sparse solver, and supporting sparse BLAS (level 1, 2, and 3) routines for solving sparse systems of equations, as well as a distributed version of Intel MKL PARDISO solver provided for use on clusters\&.
.IP "\(bu" 2
See PARDISO User's Guide and http://www.pardiso-project.org (Olaf Schenk, supercomputer center, Mano, Lugano)
.IP "\(bu" 2
PARDISO is defined in MKL_DOMAIN_PARDISO of the mkl\&.h header file\&.
.IP "\(bu" 2
is there another sparse direct solver? - mkl_dss\&.h
.IP "\(bu" 2
solver uses LaPack / libmkl_lapack\&.dylib 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
