.TH "csmp::Quadrilaterator" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Quadrilaterator \- Creates a quadrilateral finite-element mesh from the input bitmap\&. The node and element numbering is from 0\&.\&.n-1; negative numbers identify missing neighbor elements and corresponding model boundary identifiers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Quadrilaterator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuadrilaterator\fP (bool harmonic_permeability_averaging=false)"
.br
.ti -1c
.RI "void \fBQuadrilateralsFromRegularGrid\fP (\fBVSet\fP< 2U > &vset, bool from_bitmap=true)"
.br
.RI "prompts user for color-coded permeability values (0\&.\&.256) matrix in ascii text file and creates a regular quadrilateral mesh from this data "
.ti -1c
.RI "void \fBQuadrilateralsFromRegularGrid\fP (\fBVSet\fP< 2U > &vset, const char *file_name, double x_extend, double y_extend, bool from_bitmap=true)"
.br
.RI "reads 0\&.\&.256 valued point matrix of color-coded permeability values from ascii text file and creates a regular, yet scaled quadrilateral mesh from it "
.ti -1c
.RI "void \fBQuadrilateralsFromRegularGrid\fP (\fBVSet\fP< 2U > &vset, double x_extend, double y_extend, size_t row_nodes, size_t column_nodes)"
.br
.RI "creates a regular quadrilateral mesh with row_nodes-1 elements in the vertical, anr column_nodes-1 elements in the horizontal direction "
.in -1c
.SH "Detailed Description"
.PP 
Creates a quadrilateral finite-element mesh from the input bitmap\&. The node and element numbering is from 0\&.\&.n-1; negative numbers identify missing neighbor elements and corresponding model boundary identifiers\&. 


.PP
\fBAuthor\fP
.RS 4
Stephan K\&. Matthaei 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1999
.RE
.PP
.SH "Motivation"
.PP
Have a simple procedure to go from a geometry drawn with a pixel-type tool or defined by a processed image, to go to a simple triangular finite-element mesh for CSMP computations\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::Quadrilaterator::Quadrilaterator (bool harmonic_permeability_averaging = \fRfalse\fP)"
Constructor\&. By setting the boolean to true (default is false), the bitmap entires corresponding to a nodal permeability value are harmonically averaged for each quadrilateral finite element\&. 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::Quadrilaterator::QuadrilateralsFromRegularGrid (\fBVSet\fP< 2U > & vset, bool from_bitmap = \fRtrue\fP)"

.PP
prompts user for color-coded permeability values (0\&.\&.256) matrix in ascii text file and creates a regular quadrilateral mesh from this data A pixel bitmap image is used to generate 2D straightsided isoparametric quadrilateral elements to which a permeability is assigned\&. The permeability is chosen to be that of the lower left pixel of four pixels that are converted into 4 nodes of the quadrilateral elements\&. Alternatively, by setting the boolean of the constructor to true, the harmonic permeability average is calculated for each element from the four nodes\&. 
.br

.PP
The method automatically assigns the boundary flags for nodes and elements and prompts the user to scale the model to the physical dimensions\&. The finite element mesh is stored in a \fBVSet\fP object that can be used to construct the \fBModel\fP\&. 
.br

.PP
The nodes are ordered in a counter-clockwise fashion with the first node being the lower left corner of the quadrilateral\&.

.PP
\fBParameters\fP
.RS 4
\fIvset\fP The reference to the \fBVSet\fP that will be used to construct the \fBModel\fP object later on\&. 
.RE
.PP

.SS "void csmp::Quadrilaterator::QuadrilateralsFromRegularGrid (\fBVSet\fP< 2U > & vset, double x_extend, double y_extend, size_t x_nodes, size_t y_nodes)"

.PP
creates a regular quadrilateral mesh with row_nodes-1 elements in the vertical, anr column_nodes-1 elements in the horizontal direction 
.PP
\fBAttention\fP
.RS 4
x_nodes actually refers to the number of rows in the matrix, i\&.e\&. nodes along the Y (vertical) axes, y_nodes are the number of nodes in the horizontal=x direction\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
