.TH "csmp::MaximumDifference< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::MaximumDifference< dim >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::Interrelation< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaximumDifference\fP (const \fBPropertyDatabase\fP< dim > &p, const char *variable1, const char *variable2)"
.br
.ti -1c
.RI "void \fBCalculate\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "double \fBValue\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "\fBInterrelation\fP (const \fBPropertyDatabase\fP< dim > &p)"
.br
.ti -1c
.RI "void \fBName\fP (const char *s)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApply\fP (\fBModel\fP< dim > &)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBApply\fP (\fBModelSubDomain\fP< dim, CELL > &)"
.br
.RI "a simplex is any geometrical association of points "
.ti -1c
.RI "bool \fBResultWithinRange\fP ()"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::const_iterator \fBOperandsBegin\fP () const"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::const_iterator \fBOperandsEnd\fP () const"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::iterator \fBResult\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "\fBOperand\fP< dim > & \fBGlobalProperty\fP (const char *var)"
.br
.ti -1c
.RI "void \fBResultProperty\fP (const char *var)"
.br
.ti -1c
.RI "void \fBOutputCondition\fP (\fBOperand\fP< dim > &var, \fBVARIABLE_FLAG\fP output)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "const \fBPropertyDatabase\fP< dim > & \fBp_ref\fP"
.br
.ti -1c
.RI "std::string \fBname_\fP"
.br
.ti -1c
.RI "std::string \fBresult_property_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > > \fBoperand_list_\fP"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::iterator \fBresult_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::MaximumDifference\fP< dim >::Calculate ()\fR [virtual]\fP"
Pure virtual function that the user overrides to express the interrelation between variables mathematically\&. A more detailed description of this inheritance process is given in the introduction to the class above\&.
.SH "Implementation"
.PP
Within \fBCalculate()\fP the user has access to Operands defined in the private data section of the \fBInterrelation\fP subclass\&. These Operands can be used in mathematical and logical expressions, or associated variables can be assigned to local variables of double, scalar, vector or tensor type\&. Please refer to the documentation of the \fBOperand\fP interface to learn about the overloaded operators\&. 
.br
.SH "Application Examples"
.PP
To calculate local (element-restricted) interdependencies of physical variables inside of the CSP model\&.
.SH "Messages"
.PP
Use the method PrintValue() of the \fBOperand\fP class to output computed property values to screen\&. 
.PP
Reimplemented from \fBcsmp::Interrelation< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
