.TH "source/modules/math/CSMP_mathUtilities.cpp" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/modules/math/CSMP_mathUtilities.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'CSMP_mathUtilities\&.h'\fP
.br
\fR#include 'ScalarVariable\&.h'\fP
.br
\fR#include 'VectorVariable\&.h'\fP
.br
\fR#include 'TensorVariable\&.h'\fP
.br
\fR#include <chrono>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsmp\fP"
.br
.RI "Complex System Modeling Platform\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBcsmp::rsqrt\fP (double val)"
.br
.RI "Reciprocal square root function\&. "
.ti -1c
.RI "double \fBcsmp::vector_norm1\fP (\fBvector\fP< double > &x, \fBvector\fP< double > &scale)"
.br
.RI "L1 norm\&. "
.ti -1c
.RI "double \fBcsmp::vector_norm2\fP (\fBvector\fP< double > &x, \fBvector\fP< double > &scale)"
.br
.RI "L2 norm\&. "
.ti -1c
.RI "void \fBcsmp::dN_To2DOF\fP (uint32_t nodes, \fBDenseMatrix\fP< DM_MIN > &DN)"
.br
.RI "FEM matrix transformations, for the case where the solution variable is a vector in 2D, Zienkewicz, volume 1, p\&. 22\&. "
.ti -1c
.RI "void \fBcsmp::dN_To3DOF\fP (uint32_t nodes, \fBDenseMatrix\fP< DM_MIN > &DN)"
.br
.RI "FEM matrix transformations, for the case where the solution variable is a vector in 3D, Zienkewicz, volume 1, p\&. 133\&. "
.ti -1c
.RI "double \fBcsmp::vector_norm_inf\fP (\fBvector\fP< double > &x, \fBvector\fP< double > &scale)"
.br
.RI "L-infinity norm\&. "
.ti -1c
.RI "void \fBcsmp::vector_randomize\fP (\fBvector\fP< double > &x, double scale_fac)"
.br
.RI "randomly perturbs the values stored in the supplied floating-point vector "
.ti -1c
.RI "template<typename Var> void \fBcsmp::out\fP (const Var &obj)"
.br
.RI "console output of arguments like STL vectors etc\&. "
.ti -1c
.RI "template void \fBcsmp::out\fP (const \fBvector\fP< size_t > &)"
.br
.ti -1c
.RI "template void \fBcsmp::out\fP (const \fBvector\fP< uint32_t > &)"
.br
.ti -1c
.RI "template void \fBcsmp::out\fP (const \fBvector\fP< int32_t > &)"
.br
.ti -1c
.RI "template void \fBcsmp::out\fP (const \fBvector\fP< double > &)"
.br
.ti -1c
.RI "double \fBcsmp::erfc_Chebyshev\fP (double x)"
.br
.RI "approximation of the complementary error function using a Chebyshev polynomial "
.ti -1c
.RI "double \fBcsmp::erf_Chebyshev\fP (double)"
.br
.RI "for conversion of numbers to strings use to_string() function "
.ti -1c
.RI "template<typename Var> void \fBcsmp::average\fP (const \fBvector\fP< Var > &var_vec, Var &var)"
.br
.RI "calculates arithmetic average of variables "
.ti -1c
.RI "template void \fBcsmp::average\fP (const \fBvector\fP< \fBScalarVariable\fP > &, \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "template void \fBcsmp::average\fP (const \fBvector\fP< \fBVectorVariable\fP< 1U > > &, \fBVectorVariable\fP< 1U > &)"
.br
.ti -1c
.RI "template void \fBcsmp::average\fP (const \fBvector\fP< \fBVectorVariable\fP< 2U > > &, \fBVectorVariable\fP< 2U > &)"
.br
.ti -1c
.RI "template void \fBcsmp::average\fP (const \fBvector\fP< \fBVectorVariable\fP< 3U > > &, \fBVectorVariable\fP< 3U > &)"
.br
.ti -1c
.RI "template void \fBcsmp::average\fP (const \fBvector\fP< \fBTensorVariable\fP< 1U > > &, \fBTensorVariable\fP< 1U > &)"
.br
.ti -1c
.RI "template void \fBcsmp::average\fP (const \fBvector\fP< \fBTensorVariable\fP< 2U > > &, \fBTensorVariable\fP< 2U > &)"
.br
.ti -1c
.RI "template void \fBcsmp::average\fP (const \fBvector\fP< \fBTensorVariable\fP< 3U > > &, \fBTensorVariable\fP< 3U > &)"
.br
.ti -1c
.RI "double \fBcsmp::splineValue\fP (double x, double x1, double x2, double y1, double y2, double k1, double k2)"
.br
.RI "auxiliary functions for spline interpolation "
.ti -1c
.RI "double \fBcsmp::splineDerivative\fP (double x, double x1, double x2, double y1, double y2, double k1, double k2)"
.br
.ti -1c
.RI "double \fBcsmp::splineSecondDerivative\fP (double x, double x1, double x2, double y1, double y2, double k1, double k2)"
.br
.ti -1c
.RI "double \fBcsmp::secant_method\fP (double xmin, double xmax, double(*function)(double), double tolerance)"
.br
.RI "finding root of function f(x) by Secant method within the x range [xmin,xmax] "
.ti -1c
.RI "double \fBcsmp::maximum_of_function\fP (double xmin, double xmax, double(*function)(double), double tolerance)"
.br
.RI "finding the x value, in the range [xmin,xmax], where function f(x) is maximum by using golden-section search "
.ti -1c
.RI "double \fBcsmp::minimum_of_function\fP (double xmin, double xmax, double(*function)(double), double tolerance)"
.br
.RI "finding the x value, in the range [xmin,xmax], where function f(x) is minimum by using golden-section search "
.ti -1c
.RI "double \fBcsmp::g\fP (double x, double x1, double(*function)(double), double(*dfunction)(double))"
.br
.RI "finding the x value, in the range [xmin,xmax], where function the "df(x)/dx=(f(x)-f(x1))/(x-x1)"\&.\&. this line is the secant and tangent to f(x) at that point "
.ti -1c
.RI "double \fBcsmp::secant_line\fP (double x_intercept, double xmin, double xmax, double(*flinear)(double), double(*fnonlinear)(double), double tolerance)"
.br
.RI "in the range [xmin,xmax], finds the intersection of the nonlinear function (flinear) with a linear function (fnonlinear) with the given x-axis intercept "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
