.TH "csmp::TupleHash" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TupleHash
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <JaggedArray3D\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::size_t \fBoperator()\fP (const std::tuple< uint32_t, uint32_t, uint32_t > &t) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
custom hash for std::tuple<int, int, int>

.PP
The STL uses just uses the function 
.PP
.nf
std::size_t operator()(const std::tuple<int, int, int>& t) const {
    std::size_t h1 = std::hash<int>{}(std::get<0>(t)); // Hash of the first element
    std::size_t h2 = std::hash<int>{}(std::get<1>(t)); // Hash of the second element
    std::size_t h3 = std::hash<int>{}(std::get<2>(t)); // Hash of the third element
    // Combine the hashes using XOR and bit\-shifting
    return h1 ^ (h2 << 1) ^ (h3 << 2);
  }

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
