.TH "csmp::TwophaseLiquid" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TwophaseLiquid \- Composition of liquid phase on twophase vapor+liquid envelope\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'eos/h2o_nacl/TwophaseLiquid\&.h'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTwophaseLiquid\fP (const double &externaltemperature, const double &externalpressure, const double &ph2o)"
.br
.ti -1c
.RI "\fB~TwophaseLiquid\fP ()"
.br
.ti -1c
.RI "double \fBMassFractionNaCl\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Composition of liquid phase on twophase vapor+liquid envelope\&. 


.PP
\fBAuthor\fP
.RS 4
Thomas Driesner, ETH Zuerich, thomas.driesner@erdw.ethz.ch
.RE
.PP
.SH "Motivation"
.PP
"TwophaseLiquid" is legacy code from Thomas Driesner's developments for the H2O-NaCl system, and computes the composition of liquid on the twophase liquid+vapor envelope as a function of temperature and pressure\&. It can be used standalone if only this information is needed\&. Otherwise, it is only used in the CSMP++ context for building accurate lookup tables for the H2O-NaCl system, which are significantly faster if the full system properties are needed\&.

.PP
Details of the underlying formulation can be found in

.PP
Driesner T\&. and Heinrich C\&.A\&. (2007): The system H2O-NaCl\&. Part I: Correlation formulae for phase relations in temperature-pressure-molefraction space from 0 to 1000oC, 0 to 5000 bar, and 0 to 1 XNaCl\&. Geochimica et Cosmochimica Acta 71, 4880-4901\&.
.SH "Usage"
.PP
Construct an instance of "TwophaseLiquid" with the temperature ("externaltemperature", in C), fluid pressure ("externalpressure", in Pa) and water boiling pressure ("ph2o", in Pa, see attention remark below) as constructor arguments\&.

.PP
"TwophaseLiquid" has an internal mechanism to make sure that it always uses the current value of temperature, fluid pressure, and water boiling pressure as they exist in your code\&. Public member names should be self-explanatory, I hope\&.

.PP
The NaCl concentration can be retrieved in units of mass fraction\&. If you want to convert these or need values for molar masses of NaCl and H2O, please use \fBConvertConcentrationUnitsNaCl\&.h\fP to stay consistent\&.

.PP
\fBAttention\fP
.RS 4
The water boling pressure as constructor argument requires that a \fBWater\fP object is being instantiated before twophase liquid, with the same temperature and fluid pressure as its constructor arguments\&. Also, before querying \fBTwophaseLiquid::MassFractionNaCl()\fP, one has to makie sure that ph2o has been updated\&. See code example\&. I apologize for this odd design but for performance reasons it made sense when created originally\&.
.RE
.PP
.PP
.nf
double t(somevalue);          // temperature [C] in user's application
double p(anothervalue);       // fluid pressure [in Pa] in user's application
double ph2o(yetanothervalue); // water boling pressure [in Pa] in user's application
\&.\&.\&.
Water          water(t,p);
TwophaseLiquid twophase_liquid(t,p,ph2o); 
\&.\&.\&.
// Updating t,p,ph2o:
t    = my_new_t_value;
p    = my_new_p_value;
ph2o = water\&.SaturationPressure();
// And retrieving the new value of mass fraction NaCl in TwophaseLiquid:
x = twophase_liquid\&.MassFractionNaCl(); // compute and assign to x the mass fraction of NaCl of TwophaseLiquid at t and p
\&.\&.\&.
.fi
.PP
.SH "Testing"
.PP
Tested manually against CSP version OK 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::TwophaseLiquid::TwophaseLiquid (const double & externaltemperature, const double & externalpressure, const double & ph2o)"
custom constructor

.PP
\fBAttention\fP
.RS 4
Use only this conctructor\&. \fBTwophaseLiquid\fP computes the NaCl concentration of liquid on the twophase liquid+vapor surface as a function of temperature and pressure\&. These are typically computed somewhere outside this class\&. By using const refs to those external variables as constructor argument, \fBTwophaseLiquid\fP is able to decipher their current values when being queried for the NaCl concentration\&. Only this constructor is allowed to ensure that functionality, default constructor has been made private\&. See reamrks on thirs constructor variable in full class documentation and code example\&. 
.RE
.PP

.SS "csmp::TwophaseLiquid::~TwophaseLiquid ()"
destructor 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::TwophaseLiquid::MassFractionNaCl ()"
Value of mass fraction of dissolved NaCl in liquid on twophase liquid+vapor surface 
.PP
\fBAttention\fP
.RS 4
The value is based on converting the mole fraction computed from equation 11 in Driesner & Heinrich (2007)\&. Conversion is based on \fBConvertConcentrationUnitsNaCl\&.h\fP; to stay consistent, use values and functions provide therein for further computations if you need unit conversion\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
