.TH "csmp::NumIntegral_BT_D_B_dV< dim, CELL >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::NumIntegral_BT_D_B_dV< dim, CELL >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <NumIntegral_BT_D_B_dV\&.h>\fP
.PP
Inherits \fBcsmp::MathOperatorLHS< dim, Element >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNumIntegral_BT_D_B_dV\fP (const \fBPropertyDatabase\fP< dim > &, const char *oper1, const char *oper2, const char *basic, const char *test, bool plane_strain=true)"
.br
.ti -1c
.RI "void \fBGetOperands\fP (const CELL< dim > &) override final"
.br
.ti -1c
.RI "void \fBComputeContribution\fP (const CELL< dim > &) override final"
.br
.ti -1c
.RI "void \fBPlaneStress\fP (bool yes_no=true)"
.br
.ti -1c
.RI "\fBNumIntegral_BT_D_B_dV\fP< dim, CELL > * \fBclone\fP () const override final"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::MathOperatorLHS< dim, Element >\fP
.in +1c
.ti -1c
.RI "\fBMathOperatorLHS\fP (const \fBPropertyDatabase\fP< dim > &, const char *basic, const char *test)"
.br
.ti -1c
.RI "\fBMathOperatorLHS\fP & \fBoperator=\fP (const \fBMathOperatorLHS\fP &)"
.br
.ti -1c
.RI "std::string \fBName\fP () const"
.br
.RI "\fBOperand\fP Functions\&. "
.ti -1c
.RI "virtual void \fBOut\fP () const"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBMaterialOperand\fP () const"
.br
.ti -1c
.RI "const \fBIndex\fP & \fBMaterialOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBMaterialOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBMaterialOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBMaterialOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBMaterialOperandDataDepth\fP () const"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBBasicOperand\fP () const"
.br
.ti -1c
.RI "const \fBIndex\fP & \fBBasicOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBBasicOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBBasicOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBBasicOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBBasicOperandDataDepth\fP () const"
.br
.ti -1c
.RI "size_t \fBBasicOperandOffset\fP () const"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBTestOperand\fP () const"
.br
.ti -1c
.RI "const \fBIndex\fP & \fBTestOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBTestOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBTestOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBTestOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBTestOperandDataDepth\fP () const"
.br
.ti -1c
.RI "size_t \fBTestOperandOffset\fP () const"
.br
.ti -1c
.RI "bool \fBAdd\fP () const"
.br
.RI "Accumulation Process Settings\&. "
.ti -1c
.RI "bool \fBSubtract\fP () const"
.br
.ti -1c
.RI "bool \fBAddLater\fP () const"
.br
.ti -1c
.RI "bool \fBSubtractLater\fP () const"
.br
.ti -1c
.RI "bool \fBMultiply\fP () const"
.br
.ti -1c
.RI "bool \fBLumpedFormulation\fP () const"
.br
.ti -1c
.RI "uint32_t \fBApplicationCycle\fP () const"
.br
.ti -1c
.RI "uint32_t \fBApplicationCycles\fP () const"
.br
.ti -1c
.RI "double \fBMultiplyBy\fP () const"
.br
.ti -1c
.RI "bool \fBMultiplyWithTimeIncrement\fP () const"
.br
.ti -1c
.RI "bool \fBDivideByTimeIncrement\fP () const"
.br
.ti -1c
.RI "void \fBAddAccumulate\fP ()"
.br
.RI "Set flags and properties\&. "
.ti -1c
.RI "void \fBSubtractAccumulate\fP ()"
.br
.ti -1c
.RI "void \fBAddAccumulateLater\fP ()"
.br
.ti -1c
.RI "void \fBSubtractAccumulateLater\fP ()"
.br
.ti -1c
.RI "void \fBMultiplyAccumulate\fP ()"
.br
.ti -1c
.RI "void \fBPropertyAtIntegrationPoint\fP (const \fBElement\fP< dim > &, const \fBcsmp::Index\fP &, uint32_t ip, \fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "interpolation of property if isoparametric elements are used "
.ti -1c
.RI "virtual void \fBGetOperands\fP (const \fBElement\fP< dim > &)"
.br
.RI "getting data from the \fBElement\fP, \fBFace\fP, \fBInterFace\fP "
.ti -1c
.RI "virtual void \fBWriteOperands\fP (\fBElement\fP< dim > &)"
.br
.RI "writing data to the \fBElement\fP, \fBFace\fP, \fBInterFace\fP "
.ti -1c
.RI "virtual void \fBMultiplyWithTimeFactor\fP (double dt)"
.br
.RI "multiply with time increment if this is desired "
.ti -1c
.RI "virtual void \fBAssignToGlobal\fP (const \fBElement\fP< dim > &, \fBSparseMatrix\fP &)"
.br
.RI "assigment to the left hand side global matrix (after everything was calculated ) "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::MathOperatorLHS< dim, Element >\fP
.in +1c
.ti -1c
.RI "std::string \fBname_\fP"
.br
.RI "name of operator "
.ti -1c
.RI "\fBParameter\fP \fBop\fP"
.br
.RI "material property operand "
.ti -1c
.RI "std::pair< \fBParameter\fP, size_t > \fBbop\fP"
.br
.RI "basic function operand and calculation offset "
.ti -1c
.RI "std::pair< \fBParameter\fP, size_t > \fBtop\fP"
.br
.RI "test function operand and calculation offset "
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBLHS\fP"
.br
.RI "solution matrix to be accumulated "
.ti -1c
.RI "std::vector< \fBDenseMatrix\fP< DM_MIN > > \fBMTRL\fP"
.br
.RI "material property matrix(es) needed for PDE operand "
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBDERIV\fP"
.br
.RI "shape function derivative matrix "
.ti -1c
.RI "std::vector< double > \fBIPOL\fP"
.br
.RI "shape function vector "
.ti -1c
.RI "double \fBfactor_\fP"
.br
.RI "constant scaling factor "
.ti -1c
.RI "bool \fBadd_accumulate_\fP"
.br
.ti -1c
.RI "bool \fBsubtract_accumulate_\fP"
.br
.ti -1c
.RI "bool \fBadd_accumulate_later_\fP"
.br
.ti -1c
.RI "bool \fBsubtract_accumulate_later_\fP"
.br
.ti -1c
.RI "bool \fBmultiply_accumulate_\fP"
.br
.ti -1c
.RI "bool \fBlump_matrices_\fP"
.br
.ti -1c
.RI "uint32_t \fBapplication_cycles_\fP"
.br
.ti -1c
.RI "uint32_t \fBapplication_cycle_\fP"
.br
.ti -1c
.RI "bool \fBtime_multiply_\fP"
.br
.ti -1c
.RI "bool \fBtime_divide_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class CELL = Element>
.br
class csmp::NumIntegral_BT_D_B_dV< dim, CELL >"
.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei 

.PP
S\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1999 vector solution variable: stiffness matrix with 2(2D) or 3(3D) nodal degrees of freedon
.RE
.PP
\fBAttention\fP
.RS 4
special case: if nu=0\&.5 a purely viscous (incompressible) fluid is modeled this requires a special material property matrix, see Zienkiewicz Vol II 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class CELL = Element> \fBNumIntegral_BT_D_B_dV\fP< dim, CELL > * \fBcsmp::NumIntegral_BT_D_B_dV\fP< dim, CELL >::clone () const\fR [inline]\fP, \fR [final]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBcsmp::MathOperatorLHS< dim, Element >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class CELL> void \fBcsmp::NumIntegral_BT_D_B_dV\fP< dim, CELL >::ComputeContribution (const CELL< dim > & e)\fR [final]\fP, \fR [override]\fP, \fR [virtual]\fP"
Computes the 2D spatial integral over the matrix product:

.PP
[B]^T [JI]^T [D] [B] [JI] detJ

.PP
as the elements lefthand contribution to the global stiffness matrix\&. The integration is performed numerically using a 3 Gauss-Point scheme in the case of the quadratic triangular finite element\&. 
.br
.SH "Input Arguments"
.PP
A reference to element, the contribution of which is to be aquired and the time-increment over which the deformation shall occur\&.

.PP
The result of the computation is returned into the base class protected member matrix [C]\&. 
.br
.SH "Application Examples"
.PP
In linear elasticity computations\&. 
.PP
Reimplemented from \fBcsmp::MathOperatorLHS< dim, Element >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class CELL> void \fBcsmp::NumIntegral_BT_D_B_dV\fP< dim, CELL >::GetOperands (const CELL< dim > & e)\fR [final]\fP, \fR [override]\fP"
While Poisson's ratio must be an element variable, this method allows for Young's modulus to be a node variable\&. Thus, a continuous loss of strength can be modeled\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELL> void \fBcsmp::NumIntegral_BT_D_B_dV\fP< dim, CELL >::PlaneStress (bool yes_no = \fRtrue\fP)"
default is plane strain

.PP
Allows to toggle between plane stress and plane strain computations in two-dimensional models\&. Clearly, this method only has an effect in 2D calculations and the chosen computation must match the preceding Algorithm\&. 
.br
.SH "Input Arguments"
.PP
A boolean variable specifying whether the material property matrix used shall be initialized for plane strain or plane stress\&. 
.br
.SH "Messages"
.PP
If the method is called in a 3D calculation, the user is warned that it will have no effect\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
