.TH "csmp::GlobalVerbose" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::GlobalVerbose \- Globally visible switch to turn console output from classes on/off\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <GlobalVerbose\&.h>\fP
.PP
Inherits \fBcsmp::GenericSingleton< GlobalVerbose >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBglobalVerbose\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBGenericSingleton< GlobalVerbose >\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBcsmp::GenericSingleton< GlobalVerbose >\fP
.in +1c
.ti -1c
.RI "static \fBSingletonType\fP & \fBInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Globally visible switch to turn console output from classes on/off\&. 


.PP
\fBAuthor\fP
.RS 4
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
Aug 2011
.RE
.PP
To improve global status of the verbose variable\&. No explicit instantiation required any more\&.

.PP
Usage:

.PP
.PP
.nf
#include "GlobalVerbose\&.h"
\&.\&.\&.
bool& global_verbose( GlobalVerbose::Instance()\&.globalVerbose );
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
