.TH "csmp::ConvexPolygon< dim >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ConvexPolygon< dim >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConvexPolygon\fP (const std::vector< \fBPoint\fP< dim > > &)"
.br
.ti -1c
.RI "template<typename Iterator> \fBConvexPolygon\fP (Iterator begin, Iterator end)"
.br
.ti -1c
.RI "\fBPoint\fP< dim > \fBUnitNormal\fP (const \fBPoint\fP< dim > &inside_point) const"
.br
.RI "construct the normal at the point of interest inside of the polygon (like at a hub vertex thinking of the polygon as a wheel) "
.ti -1c
.RI "bool \fBIsPointInside\fP (const \fBPoint\fP< dim > &point) const"
.br
.ti -1c
.RI "void \fBPrint\fP () const"
.br
.ti -1c
.RI "std::vector< \fBPoint\fP< dim > > \fBGetCounterClockwiseVertices\fP () const"
.br
.ti -1c
.RI "std::vector< \fBPoint\fP< dim > >::const_iterator \fBCounterClockwiseVerticesBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBPoint\fP< dim > >::const_iterator \fBCounterClockwiseVerticesEnd\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP (const std::string &filename) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBConvexPolygon_Test\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
