.TH "csmp::DiffusionLHS< dim >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::DiffusionLHS< dim > \- accumulates finite-element stencils for diffusion into a sparse solution matrix\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DiffusionLHS\&.h>\fP
.PP
Inherits \fBcsmp::MatrixOperator< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiffusionLHS\fP (const \fBINDEX\fP< SCALAR, ELEMENT > &diffusivity_key, const \fBINDEX\fP< SCALAR, NODE > &transported_variable_key)"
.br
.ti -1c
.RI "virtual void \fBAccumulateFiniteVolume\fP (const \fBNode\fP< dim > &, \fBSparseMatrix\fP &) const"
.br
.RI "not available for this Element-based stencil "
.ti -1c
.RI "virtual void \fBAccumulateStencil\fP (const \fBElement\fP< dim > &, \fBSparseMatrix\fP &) const"
.br
.RI "element-by-element accumulation of matrix terms "
.in -1c

Public Member Functions inherited from \fBcsmp::MatrixOperator< dim >\fP
.in +1c
.ti -1c
.RI "void \fBMultiplyWithTimeIncrement\fP (double dt)"
.br
.RI "includes the time increment in the multiplication factor for this operator "
.ti -1c
.RI "void \fBFactor\fP (double value)"
.br
.RI "set factor to achieve multiplication with time increment (fac=dt), subtraction (fac=-1), multiplication or division (fac=1/value) "
.ti -1c
.RI "double \fBFactor\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::DiffusionLHS< dim >"accumulates finite-element stencils for diffusion into a sparse solution matrix\&. 


.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
6/12/2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::DiffusionLHS\fP< dim >::AccumulateFiniteVolume (const \fBNode\fP< dim > & , \fBSparseMatrix\fP & ) const\fR [virtual]\fP"

.PP
not available for this Element-based stencil 
.PP
Implements \fBcsmp::MatrixOperator< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::DiffusionLHS\fP< dim >::AccumulateStencil (const \fBElement\fP< dim > & fe, \fBSparseMatrix\fP & A) const\fR [virtual]\fP"

.PP
element-by-element accumulation of matrix terms Uses the finite element framework of CSMP to compute the FE diffusion integral term and accumulate it into the solution matrix A of Ax=b\&. 
.PP
Implements \fBcsmp::MatrixOperator< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
