.TH "csmp::Matrix" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Matrix \- Experimental implementation of class for a dense matrix greater than 50x50 matrix that can change its size\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Matrix\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrix\fP (size_t m, size_t n)"
.br
.RI "constructor (i,j) "
.ti -1c
.RI "\fBMatrix\fP (size_t m, size_t n, double val)"
.br
.ti -1c
.RI "size_t \fBRows\fP () const"
.br
.RI "returns number of rows "
.ti -1c
.RI "size_t \fBCols\fP () const"
.br
.RI "returns number of columns "
.ti -1c
.RI "void \fBResize\fP (size_t m, size_t n)"
.br
.ti -1c
.RI "double & \fBoperator()\fP (size_t m, size_t n)"
.br
.RI "accessors M(i,j) "
.ti -1c
.RI "const double & \fBoperator()\fP (size_t m, size_t n) const"
.br
.RI "operator (i,j) const "
.ti -1c
.RI "\fBMatrix\fP & \fBoperator=\fP (double val)"
.br
.RI "assignment "
.ti -1c
.RI "\fBMatrix\fP & \fBoperator+=\fP (const \fBMatrix\fP &M)"
.br
.ti -1c
.RI "\fBMatrix\fP & \fBoperator\-=\fP (const \fBMatrix\fP &M)"
.br
.ti -1c
.RI "\fBMatrix\fP & \fBoperator*=\fP (const \fBMatrix\fP &M)"
.br
.RI "matrix - matrix multiplication -> M(A\&.rows,B\&.cols) (operator creates temporary M) "
.ti -1c
.RI "\fBMatrix\fP & \fBoperator*=\fP (double val)"
.br
.ti -1c
.RI "\fBMatrix\fP & \fBoperator*=\fP (const std::vector< double > &v)"
.br
.RI "matrix vector multiplication "
.ti -1c
.RI "\fBMatrix\fP \fBoperator+\fP (const \fBMatrix\fP &M) const"
.br
.RI "adding of same-size matrices "
.ti -1c
.RI "\fBMatrix\fP \fBoperator\-\fP (const \fBMatrix\fP &M) const"
.br
.ti -1c
.RI "\fBMatrix\fP \fBoperator*\fP (const \fBMatrix\fP &M) const"
.br
.RI "C = A B, matrix - matrix multiplication -> M(A\&.rows,B\&.cols) "
.ti -1c
.RI "void \fBIdentity\fP ()"
.br
.ti -1c
.RI "void \fBRowCondenseTo\fP (std::vector< double > &vec) const"
.br
.RI "returns vec = Mat * unity vector "
.ti -1c
.RI "void \fBZero\fP ()"
.br
.ti -1c
.RI "void \fBZeroRow\fP (size_t row)"
.br
.ti -1c
.RI "void \fBZeroCol\fP (size_t col)"
.br
.ti -1c
.RI "void \fBFill\fP (double val)"
.br
.ti -1c
.RI "void \fBFillRow\fP (size_t row, double val)"
.br
.ti -1c
.RI "void \fBFillCol\fP (size_t col, double val)"
.br
.ti -1c
.RI "std::vector< double > \fBReturnRow\fP (size_t row) const"
.br
.ti -1c
.RI "std::vector< double > \fBReturnCol\fP (size_t col) const"
.br
.ti -1c
.RI "void \fBAssignToRow\fP (size_t row, std::vector< double > &vec)"
.br
.ti -1c
.RI "void \fBAssignToCol\fP (size_t row, std::vector< double > &vec)"
.br
.ti -1c
.RI "void \fBTransposed\fP (\fBMatrix\fP &RES) const"
.br
.RI "RES = M^T into its argument\&. "
.ti -1c
.RI "void \fBTransposedProduct\fP (\fBMatrix\fP &RES) const"
.br
.RI "RES = M^T M\&. "
.ti -1c
.RI "void \fBMultiplyWithTransposedOf\fP (const \fBMatrix\fP &B, \fBMatrix\fP &RES) const"
.br
.RI "RES = A B^T\&. "
.ti -1c
.RI "void \fBMultiplyTransposedOfWith\fP (const \fBMatrix\fP &B, \fBMatrix\fP &RES) const"
.br
.RI "RES = A^T B\&. "
.ti -1c
.RI "double \fBRowSum\fP (size_t row) const"
.br
.ti -1c
.RI "double \fBColSum\fP (size_t col) const"
.br
.ti -1c
.RI "double \fBNormL1\fP () const"
.br
.RI "unscaled matrix norms "
.ti -1c
.RI "double \fBNormL_Infinity\fP () const"
.br
.RI "unscaled L_infinity matrix norm ||A||inf = max_i * sum_j |aij| "
.ti -1c
.RI "\fBMatrix\fP \fBMinor\fP (const size_t row, const size_t col)"
.br
.ti -1c
.RI "void \fBIn\fP ()"
.br
.ti -1c
.RI "void \fBOut\fP (long digits=5L) const"
.br
.ti -1c
.RI "void \fBLUDecomposition\fP (std::vector< uint32_t > &index, double &d)"
.br
.RI "LU decomposition and back-substitution\&. "
.ti -1c
.RI "void \fBLUBackSubstitution\fP (std::vector< uint32_t > &index, std::vector< double > &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Experimental implementation of class for a dense matrix greater than 50x50 matrix that can change its size\&. 

Supported operations (M = dense matrix, v = vector, _T = transposed, T = tensor matrix(dim,dim), default vector is a column vector (v = { c0,c2\&.\&.cn-1 }, vc = \fBvector(dim)\fP )

.PP
\fBAuthor\fP
.RS 4
S\&. K\&. Matthai 

.PP
S\&. Geiger 

.PP
S\&. G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
2001
.RE
.PP
\fBTodo\fP
.RS 4
SKM - implement non-member global methods for multiplication etc\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBMatrix\fP csmp::Matrix::Minor (const size_t row, const size_t col)"
Returns a submatrix of the matrix with the dimensions row x col 
.SS "double csmp::Matrix::NormL1 () const"

.PP
unscaled matrix norms unscaled L1 matrix norm ||A1|| = max_j * sum_i |aij| 
.SS "double & csmp::Matrix::operator() (size_t m, size_t n)"

.PP
accessors M(i,j) operator (i,j) 
.SS "\fBMatrix\fP & csmp::Matrix::operator*= (const \fBMatrix\fP & mat)"

.PP
matrix - matrix multiplication -> M(A\&.rows,B\&.cols) (operator creates temporary M) 
.PP
\fBWarning\fP
.RS 4
creates a temporary 
.RE
.PP

.SS "void csmp::Matrix::RowCondenseTo (std::vector< double > & vec) const"

.PP
returns vec = Mat * unity vector vec = Mat * unity vector 
.SS "void csmp::Matrix::TransposedProduct (\fBMatrix\fP & RES) const"

.PP
RES = M^T M\&. RES = A^T A\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
