.TH "csmp::TensorVariable< 2U >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TensorVariable< 2U > \- 2D full specialization of tensor-type variable template (other tensors are declared in files #1, #)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TensorVariable2\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTensorVariable\fP ()"
.br
.ti -1c
.RI "\fBTensorVariable\fP (\fBVARIABLE_FLAG\fP f, double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP (\fBVARIABLE_FLAG\fP f, double v11, double v12, double v21, double v22)"
.br
.ti -1c
.RI "\fBTensorVariable\fP (const \fBVARIABLE_FLAG\fP &f11, const \fBVARIABLE_FLAG\fP &f22, const double &v11, const double &v12, const double &v21, const double &v22)"
.br
.ti -1c
.RI "double & \fBoperator()\fP (uint32_t i, uint32_t j)"
.br
.ti -1c
.RI "const double & \fBoperator()\fP (uint32_t i, uint32_t j) const"
.br
.ti -1c
.RI "void \fBComponent\fP (uint32_t, double)"
.br
.ti -1c
.RI "double \fBComponent\fP (uint32_t i) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator+\fP (double val) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator\-\fP (double val) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator*\fP (double val) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator/\fP (double val) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator+=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator\-=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator*=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator/=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator+=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator\-=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator*=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator/=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator+\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator\-\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator*\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 2U > \fBoperator*\fP (const \fBVectorVariable\fP< 2U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 2U > \fBoperator*\fP (const \fBPoint\fP< 2U > &) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator/\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator+=\fP (const \fBTensorVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator\-=\fP (const \fBTensorVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator/=\fP (const \fBTensorVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator*=\fP (const \fBTensorVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator=\fP (const \fBVectorVariable\fP< 2U > &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "bool \fBIsWithinRange\fP (double vmin, double vmax) const"
.br
.ti -1c
.RI "bool \fBHas_NaN_Values\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_FLAG\fP & \fBFlag\fP (uint32_t i=0)"
.br
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBFlag\fP (uint32_t i=0) const"
.br
.ti -1c
.RI "uint32_t \fBSize\fP () const"
.br
.ti -1c
.RI "void \fBIdentity\fP ()"
.br
.ti -1c
.RI "double \fBMinElement\fP () const"
.br
.ti -1c
.RI "double \fBMaxElement\fP () const"
.br
.ti -1c
.RI "double \fBDeterminant\fP () const"
.br
.ti -1c
.RI "double \fBTrace\fP () const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBAdjoint\fP () const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBInverse\fP () const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBTransposed\fP () const"
.br
.ti -1c
.RI "bool \fBEigen\fP (\fBVectorVariable\fP< 2U > &vvEigenvalues, \fBTensorVariable\fP< 2U > &tvEigenvectors, bool bNormalize) const"
.br
.ti -1c
.RI "bool \fBEigenValues\fP (\fBVectorVariable\fP< 2U > &vvEigenvalues) const"
.br
.ti -1c
.RI "bool \fBEigenValues\fP (std::vector< double > &vecEigenvalues) const"
.br
.ti -1c
.RI "bool \fBEigenNonSymmetric\fP (\fBVectorVariable\fP< 2U > &eigenVals, \fBTensorVariable\fP< 2U > &eigenVecs) const"
.br
.ti -1c
.RI "void \fBDiagonalValues\fP (double f_00, double f_11)"
.br
.ti -1c
.RI "void \fBDiagonalValues\fP (const std::vector< double > &vecDiags)"
.br
.ti -1c
.RI "void \fBDiagonalValues\fP (const \fBVectorVariable\fP< 2U > &vecDiags)"
.br
.ti -1c
.RI "void \fBAssignToRow\fP (uint32_t i, \fBVectorVariable\fP< 2U > &vc)"
.br
.ti -1c
.RI "void \fBAssignToColumn\fP (uint32_t j, \fBVectorVariable\fP< 2U > &vc)"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 2U > \fBRow\fP (uint32_t iRow) const"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 2U > \fBColumn\fP (uint32_t iCol) const"
.br
.ti -1c
.RI "void \fBIn\fP ()"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.ti -1c
.RI "bool \fBIn\fP (std::fstream &fp)"
.br
.ti -1c
.RI "bool \fBOut\fP (std::fstream &fp) const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr \fBVARIABLE_TYPE\fP \fBVariableType\fP = TENSOR"
.br
.in -1c
.SH "Detailed Description"
.PP 
2D full specialization of tensor-type variable template (other tensors are declared in files #1, #) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcsmp::TensorVariable\fP< 2U >::TensorVariable ()"

.PP
\fBTodo\fP
.RS 4
SKM initialise array elements in the initialiser list 
.RE
.PP

.SS "\fBcsmp::TensorVariable\fP< 2U >::TensorVariable (\fBVARIABLE_FLAG\fP f, double val)"
initialises variable as diagonal isotropic tensor with flag and value SKM 17/6/2015 
.SH "Member Function Documentation"
.PP 
.SS "bool \fBcsmp::TensorVariable\fP< 2U >::Eigen (\fBVectorVariable\fP< 2U > & evals, \fBTensorVariable\fP< 2U > & evecs, bool bNormalize) const"
Computes eigenvalues and eigenvectors assuming that the tensor variable is symmetric\&. If not symmetric, off-diagonal elements are averaged\&. No check of symmetry is performed\&. 
.br

.PP
By default the length of the eigenvectors is equivalent to the eigenvalues but it can be normalized to one\&. 
.br
.SH "Input Arguments"
.PP
Flag to normalize length of eigenvectors\&. 
.br

.PP
\fBReturns\fP
.RS 4
Eigenvalues and vectors are returned into the supplied Vector and TensorVariables, respectively\&.
.RE
.PP
Will return false if the rank of the matrix is zero\&. 
.br
.SH "Implementation"
.PP
Just uses the normal binomial root formula\&. 
.SS "bool \fBcsmp::TensorVariable\fP< 2U >::Has_NaN_Values () const"
Checks only the diagonal\&. 
.SS "bool \fBcsmp::TensorVariable\fP< 2U >::IsWithinRange (double vmin, double vmax) const"

.PP
\fBTest\fP
.RS 4
re-tested: SKM 29-9-2001 
.RE
.PP

.SS "double \fBcsmp::TensorVariable\fP< 2U >::MaxElement () const"

.PP
\fBTest\fP
.RS 4
re-tested: SKM 29-9-2001 
.RE
.PP

.SS "double \fBcsmp::TensorVariable\fP< 2U >::MinElement () const"

.PP
\fBTest\fP
.RS 4
re-tested: SKM 29-9-2001 
.RE
.PP

.SS "void \fBcsmp::TensorVariable\fP< 2U >::Out () const"

.PP
\fBTest\fP
.RS 4
tested: O\&.K\&. 
.RE
.PP

.SS "\fBTensorVariable\fP< 2U > \fBcsmp::TensorVariable\fP< 2U >::Transposed () const"

.PP
\fBTest\fP
.RS 4
tested: O\&.K\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
