.TH "csmp::JaggedArray3D_Comparison_Test" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::JaggedArray3D_Comparison_Test
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBComparePerformanceWithVectorOfVectors\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBverbose_\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void csmp::JaggedArray3D_Comparison_Test::ComparePerformanceWithVectorOfVectors ()"
\fBTest\fP Parameters: • The test creates both Jagged3DArray and \fBvector<vector<vector<double>>>\fP structures with dimensions 6x4x3 and populates them with sequential values starting from 1\&.0\&.
.IP "2." 4
Random Access: • A loop performs 1,000,000 random accesses to elements in both structures\&. • Random indices are generated using mt19937 and uniform_int_distribution\&.
.IP "3." 4
Timing: • The chrono::high_resolution_clock is used to measure the duration of the random access for both structures\&.
.IP "4." 4
Volatile Keyword: • The volatile keyword is used to prevent the compiler from optimizing away the loop by assuming the results are unused\&.
.IP "5." 4
Output: • The program prints the time taken (in microseconds) for both the vector and Jagged3DArray\&. 
.PP

.SS "void csmp::JaggedArray3D_Comparison_Test::run ()\fR [virtual]\fP"

.PP
Implements \fBcsmp::Test\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
