.TH "csmp::BrooksCoreySaturationFunctionsWithHysteresis< dim, USER >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::BrooksCoreySaturationFunctionsWithHysteresis< dim, USER > \- The Brooks-Corey capillary pressure model and the Corey-Burdine relative permeability and their first derivatives\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <BrooksCoreySaturationFunctionswithHysteresis\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFLUID_PHASE\fP { \fBH2O\fP, \fBCO2\fP }"
.br
.ti -1c
.RI "enum \fBTWO_PHASE_FLOW_PROCESS\fP { \fBDRAINAGE\fP, \fBIMBIBITION\fP, \fBCO_CURRENT_FLOW\fP, \fBCOUNTER_CURRENT_FLOW\fP }"
.br
.ti -1c
.RI "enum \fBHYSTERIC_MODEL_PARAMETERS\fP : uint32_t { \fBAWD\fP =0U, \fBAOD\fP =1U, \fBCWD\fP =2U, \fBCOD\fP =3U, \fBAWI\fP =4U, \fBAOI\fP =5U, \fBCWI\fP =6U, \fBCOI\fP =7U }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBrooksCoreySaturationFunctionsWithHysteresis\fP (\fBPropertyDatabase\fP< dim > &)"
.br
.RI "accesses the model to create or attach to associated variable storage "
.ti -1c
.RI "double \fBEffectiveSaturation\fP (\fBElement\fP< dim > *const) const"
.br
.RI "Effective saturation function\&. "
.ti -1c
.RI "double \fBEffectiveSaturation_at\fP (\fBElement\fP< dim > *const, double s1) const"
.br
.RI "Effective saturation function for saturation S\&. "
.ti -1c
.RI "double \fBpc\fP (\fBElement\fP< dim > *const) const"
.br
.RI "Capillary pressure Eq\&. (2) from Skjaeveland et al\&. 2000\&. "
.ti -1c
.RI "double \fBpc_at\fP (\fBElement\fP< dim > *const, double s1) const"
.br
.RI "Capillary pressure Eq\&. (2) from Skjaeveland et al\&. 2000 for saturation S\&. "
.ti -1c
.RI "double \fBdpcds\fP (\fBElement\fP< dim > *const) const"
.br
.RI "First derivative of capillary pressure as a function of saturation\&. "
.ti -1c
.RI "double \fBdpcds_at\fP (\fBElement\fP< dim > *const, double) const"
.br
.ti -1c
.RI "double \fBkrw\fP (\fBElement\fP< dim > *const) const"
.br
.RI "The water relative Permeability is evaluated from the Brooks \fBCorey\fP Capillary Pressure model\&. See the Skaevland et al\&. 2000 at page 65\&. "
.ti -1c
.RI "double \fBkrw_at\fP (\fBElement\fP< dim > *const, double S) const"
.br
.ti -1c
.RI "double \fBkrn\fP (\fBElement\fP< dim > *const) const"
.br
.RI "The CO2 relative Permeability is evaluated from the Brooks \fBCorey\fP Capillary Pressure model\&. See the Skaevland et al\&. 2000 at page 65\&. "
.ti -1c
.RI "double \fBkrn_at\fP (\fBElement\fP< dim > *const, double S) const"
.br
.ti -1c
.RI "double \fBdkrwds\fP (\fBElement\fP< dim > *const) const"
.br
.RI "The first relative of water relative Permeability is evaluated from the Brooks \fBCorey\fP Capillary Pressure model\&. See the Skaevland et al\&. 2000 at page 65\&. "
.ti -1c
.RI "double \fBdkrwds_at\fP (\fBElement\fP< dim > *const, double S) const"
.br
.ti -1c
.RI "double \fBdkrnds\fP (\fBElement\fP< dim > *const) const"
.br
.RI "The first relative of CO2 relative Permeability is evaluated from the Brooks \fBCorey\fP Capillary Pressure model\&. See the Skaevland et al\&. 2000 at page 65\&. "
.ti -1c
.RI "double \fBdkrnds_at\fP (\fBElement\fP< dim > *const, double S) const"
.br
.ti -1c
.RI "double \fBdkrwds_Numerical\fP (\fBElement\fP< dim > *const, double delta_s) const"
.br
.RI "Numerical derivatives of first derivatives of relative permeability of water and CO2\&. "
.ti -1c
.RI "double \fBdkrwds_at_Numerical\fP (\fBElement\fP< dim > *const, double sw, double delta_s) const"
.br
.ti -1c
.RI "double \fBdkrnds_Numerical\fP (\fBElement\fP< dim > *const, double delta_s) const"
.br
.ti -1c
.RI "double \fBdkrnds_at_Numerical\fP (\fBElement\fP< dim > *const, double sw, double delta_s) const"
.br
.ti -1c
.RI "double \fBOilResidualSaturation\fP (\fBElement\fP< dim > *const) const"
.br
.RI "Oil residual saturation estimated from Land's formula\&. "
.ti -1c
.RI "double \fBWaterResidualSaturation\fP (\fBElement\fP< dim > *const, double Sor) const"
.br
.RI "\fBWater\fP residual saturation estimated from the intersection of capillary pressures from Dranage and Imbibition curves in Imbibition process\&. "
.ti -1c
.RI "void \fBWaterAndOilResidualSaturationImbibitionToDrainage\fP (\fBElement\fP< dim > *const e, double &Swr, double &Sor) const"
.br
.RI "Estimate the residual of water and oil for the target saturations for the Dranaige process from the Imbibitions curve\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class USER>
.br
class csmp::BrooksCoreySaturationFunctionsWithHysteresis< dim, USER >"The Brooks-Corey capillary pressure model and the Corey-Burdine relative permeability and their first derivatives\&. 


.SH "Introduction"
.PP
This class contains modelling the hysteresis relative permeability curves for mixed wet 2 phase model\&.

.PP
Firstly, we model relative permeability curves suggested by Skjaeveland et al\&.(2000)\&. They introduce a capillary pressure model for mixed- wet reservoir rock based on the Brooks-Corey capillary pressure model\&. By using these new correlations, they show the ability of modelling the Hysteresis loop logic\&. Also, using the Land's empirical equations one can estimate the residual's saturation of Non-wet phase (oil, or CO2), which can create first Imbibition curve etc\&.\&. We follow the same logic presented in the paper (page 61, and 62 in the paper), and implement the algorithm to do Drainage and Imbibition process\&.

.PP
In this class, we also calculate the relative permeability of the wet, and non-wet phase\&.

.PP
In the modelling, we check the capillary pressure of any process (Imbibitions, or Drainage) to be bound in the main Drainage and Imbibitions\&. Moreover, also all other functions, also calculated from the proper state of phases, either they are Imbibing or Draining\&.

.PP
The input parameters are, "aw, ao, cw, co" parameters, and residual saturation of wet and non-wet (oil, CO2) phase\&. We have these parameters as the property of elements\&.\&.\&.They can be read from configuration file as:

.PP
with key(key_kri_param) as described as "Hysteresis relative permeability model Parameters"\&.

.PP
They are ordered as: HYSTERIC_MODEL_PARAMETERS { AWD=0, AOD=1, CWD=2, COD=3, AWI=4, AOI=5, CWI=6, COI=7} ;

.PP
The results are relative permeabilities, derivatives\&.\&.\&. which they will be used in the FlowFunctions class\&.

.PP
\fBAttention\fP
.RS 4
: To have Primary Drainage, we need just use non-autamatic and use the forced intialize by set the :
.RE
.PP
c_[H2O][DRAINAGE] = entery pressure c_[CO2][DRAINAGE] = 0

.PP
and set the ProcessPath= DRAINAGE

.PP
\fBAttention\fP
.RS 4
relies on sw(sH2O), swr(srH2O), sor(srCO2) and so(sCO2) variable values stored by the USER\&. 

.PP
needs the Brooks-Corey constants (a's and c's)
.RE
.PP
\fBNote\fP
.RS 4
The Brooks-Corey capillary pressure model and the Corey-Burdine relative permeability has been implemented from the Skjaeveland et al\&. 2000\&.
.RE
.PP
\fBAttention\fP
.RS 4
current implementation is suitable only for slightly compressible flow computations, but could be extended to compositional modelling\&.
.RE
.PP
.SH "Reference"
.PP
Svein M\&. Skjaeveland, L\&. M\&. Siqveland, A\&. Kjosavik, W\&. L\&. Hammervold and G\&. A\&. Virnovsky, (2000)\&. Capillary Pressure Correlation for Mixed-Wet Reservoirs\&. SPE Reservoir Evaluation & Engineering\&. 3\&. 10\&.2118/39497-MS\&.

.PP
\fBAuthor\fP
.RS 4
Mahyar Madadi 

.PP
Stephan Matthai 
.RE
.PP
\fBDate\fP
.RS 4
May, 2019 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dkrnds (\fBElement\fP< dim > * const e) const"

.PP
The first relative of CO2 relative Permeability is evaluated from the Brooks \fBCorey\fP Capillary Pressure model\&. See the Skaevland et al\&. 2000 at page 65\&. calculating the 1st derivative of oil relative permeability 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dkrnds_at (\fBElement\fP< dim > * const e, double S) const"
calculating the 1st derivative of oil relative permeability for any water saturations 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dkrnds_at_Numerical (\fBElement\fP< dim > * const e, double sw, double h) const"
Numerical derivative of relative co2 permeability at specific saturation 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dkrnds_Numerical (\fBElement\fP< dim > * const e, double h) const"
Numerical derivative of relative co2 permeability 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dkrwds (\fBElement\fP< dim > * const e) const"

.PP
The first relative of water relative Permeability is evaluated from the Brooks \fBCorey\fP Capillary Pressure model\&. See the Skaevland et al\&. 2000 at page 65\&. calculating the 1st derivative of water relative permeability 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dkrwds_at (\fBElement\fP< dim > * const e, double S) const"
calculating the 1st derivative of water relative permeability for any water saturation 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dkrwds_at_Numerical (\fBElement\fP< dim > * const e, double sw, double h) const"
Numerical derivative of relative water permeability at specific saturation 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dkrwds_Numerical (\fBElement\fP< dim > * const e, double h) const"

.PP
Numerical derivatives of first derivatives of relative permeability of water and CO2\&. Numerical derivative of relative water permeability 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::dpcds (\fBElement\fP< dim > * const e) const"

.PP
First derivative of capillary pressure as a function of saturation\&. The first derivative of Brooks & \fBCorey\fP capillary pressure formula by assuming the variation of CO2 saturation is opposite of H2O saturations Here we also check the capillary function bound, and then if it ois out of bound the derivative\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::EffectiveSaturation (\fBElement\fP< dim > * const e) const"

.PP
Effective saturation function\&. get seff at the element barycentre 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::EffectiveSaturation_at (\fBElement\fP< dim > * const e, double s1) const"

.PP
Effective saturation function for saturation S\&. get seff from the supplied saturation value 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::krn (\fBElement\fP< dim > * const e) const"

.PP
The CO2 relative Permeability is evaluated from the Brooks \fBCorey\fP Capillary Pressure model\&. See the Skaevland et al\&. 2000 at page 65\&. For calculating the oil relative permeability, we use notation which it has been inherated from the Skjaeveland et al\&. 2000 The relative permeability has been calculated from the Brooks \fBCorey\fP Capillary pressure\&. These formula has been called as the Corey-Burdine realative permeablity equations\&.\&.\&. for further information see the page 65 in Skjaeveland et al\&. 2000\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::krn_at (\fBElement\fP< dim > * const e, double S) const"
Second form of the oil relative permeability\&.\&. the same as previous function for any saturation\&.\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::krw (\fBElement\fP< dim > * const e) const"

.PP
The water relative Permeability is evaluated from the Brooks \fBCorey\fP Capillary Pressure model\&. See the Skaevland et al\&. 2000 at page 65\&. For calculating the water relative permeability, we use notation which it has been inherated from the Skjaeveland et al\&. 2000 The relative permeability has been calculated from the Brooks \fBCorey\fP Capillary pressure\&. These formula has been called as the Corey-Burdine realative permeablity equations\&.\&.\&. for further information see the page 65 in Skjaeveland et al\&. 2000\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::krw_at (\fBElement\fP< dim > * const e, double S) const"
Second form of the water relative permeability\&.\&. the same as previous function for any saturation\&.\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::OilResidualSaturation (\fBElement\fP< dim > * const e) const"

.PP
Oil residual saturation estimated from Land's formula\&. Oil residual saturation has been estimated from Land's formula based on the initial oil saturations\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::pc (\fBElement\fP< dim > * const e) const"

.PP
Capillary pressure Eq\&. (2) from Skjaeveland et al\&. 2000\&. Brooks & \fBCorey\fP capillary pressure formula, here on spot the capilary pressure is bound to main drainage and imbibition curves\&. If it is out of bound will be replaced with the Drainage (Or Imbibition) capillary pressure\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::WaterAndOilResidualSaturationImbibitionToDrainage (\fBElement\fP< dim > *const e, double & Swr_, double & Sor_) const"

.PP
Estimate the residual of water and oil for the target saturations for the Dranaige process from the Imbibitions curve\&. Here , I calculate the residual water saturation and residual oil saturation for the transit process from imbibition to drainage\&.

.PP
These residual saturation has been estimated from the intersection of imbibition curve with drianage curve\&. We assume the rock properties are constant, i\&.e\&. aw, ao, co, and cw are constant\&. Just we need to estimate the water and oil residual saturations\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctionsWithHysteresis\fP< dim, USER >::WaterResidualSaturation (\fBElement\fP< dim > * const e, double Sro) const"

.PP
\fBWater\fP residual saturation estimated from the intersection of capillary pressures from Dranage and Imbibition curves in Imbibition process\&. This is residual water saturation for the transit process from drainage to imbibition \fBWater\fP residual saturation has been estimated from the intersection of imbibition curve with drainage curve We assume the rock properties are constant, i\&.e\&. aw, ao, co, and cw are constant\&. We need to estimate the residual water saturation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
