.TH "csmp::OtwayRockTypes" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::OtwayRockTypes \- Tuple container to return rocktype by number (std::get<1>(rocktypes_);\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <OtwayCRC3_RockTypes_Version_2\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsComposite\fP (int RT) const"
.br
.ti -1c
.RI "bool \fBIsComposite\fP (int RT) const"
.br
.ti -1c
.RI "bool \fBIsComposite\fP (int RT) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::tuple< \fBCRC3_RockType0\fP, \fBCRC3_RockType1\fP, \fBCRC3_RockType2\fP, \fBCRC3_RockType3\fP, \fBCRC3_RockType4\fP, \fBCRC3_RockType5\fP, \fBCRC3_RockType6\fP, \fBCRC3_RockType7\fP, \fBCRC3_RockType8\fP, \fBCRC3_RockType9\fP, \fBCRC3_RockType10\fP, \fBCRC3_RockType11\fP, \fBCRC3_RockType12\fP, \fBCRC3_RockType13\fP, \fBCRC3_RockType14\fP, \fBCRC3_RockType15\fP, \fBCRC3_RockType16\fP > \fBrocktype_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tuple container to return rocktype by number (std::get<1>(rocktypes_);\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
