.TH "csmp::PDE_Integrator_Attorney< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::PDE_Integrator_Attorney< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PDE_Integrator_Test\&.h>\fP
.PP
Inherits \fBcsmp::Attorney< class PDE_Integrator< dim > >\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBcsmp::Attorney< class PDE_Integrator< dim > >\fP
.in +1c
.ti -1c
.RI "\fBAttorney\fP (class \fBPDE_Integrator\fP< dim > &client)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::PDE_Integrator_Attorney< dim >"\fBAttorney\fP design pattern gives access to protected / private member variables and methods of \fBPDE_Integrator\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
