.TH "csmp::ANSYS_Interface" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ANSYS_Interface \- File based interface between ANSYS and CSMP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ANSYS_Interface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBANSYS_Interface\fP (bool create_isoparametric_element_mesh=true)"
.br
.ti -1c
.RI "template<uint32_t dim> void \fBRead_ANSYS_Mesh\fP (const std::string &mesh_file_set, \fBVSet\fP< dim > &, \fBModelTopology\fP &, bool binary_input_file, bool reassign_boundary_flags=true)"
.br
.RI "Reading function\&. "
.ti -1c
.RI "template<uint32_t dim> void \fBRead_ANSYS_Mesh\fP (const string &filename, \fBVSet\fP< dim > &vset, \fBModelTopology\fP &mesh_topology, bool binary_input_file, bool reassign_boundary_flags)"
.br
.RI "Builds \fBModel\fP after it was constructed with the default constructor\&. "
.ti -1c
.RI "template<uint32_t dim> void \fBReadMeshBinary\fP (const string &meshfile, \fBVSet\fP< dim > &vset, \fBModelTopology\fP &mesh_topology, bool reassign_boundary_flags)"
.br
.ti -1c
.RI "template<uint32_t dim> void \fBReadMeshASCII\fP (const string &meshfile, \fBVSet\fP< dim > &vset, \fBModelTopology\fP &mesh_topology, bool reassign_boundary_flags)"
.br
.ti -1c
.RI "template<uint32_t dim> bool \fBReadNodeCoordinatesASCII\fP (ifstream &ifs, \fBVSet\fP< dim > &vset)"
.br
.RI "ASCII DATA FILE\&. "
.ti -1c
.RI "template<uint32_t dim> bool \fBReadBoundaryFlagsAndConditionsASCII\fP (ifstream &ifs, \fBVSet\fP< dim > &vset)"
.br
.ti -1c
.RI "template<uint32_t dim> bool \fBReadPelementASCII\fP (ifstream &ifs, \fBVSet\fP< dim > &vset)"
.br
.ti -1c
.RI "template<uint32_t dim> bool \fBReadPlistASCII\fP (ifstream &ifs, \fBVSet\fP< dim > &vset)"
.br
.ti -1c
.RI "template<uint32_t dim> bool \fBReadPfvertsASCII\fP (ifstream &ifs, \fBVSet\fP< dim > &vset)"
.br
.ti -1c
.RI "template<uint32_t dim> bool \fBReadPmaterialASCII\fP (ifstream &ifs, \fBVSet\fP< dim > &vset)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "template<uint32_t dim> void \fBReadMeshASCII\fP (const std::string &meshfile, \fBVSet\fP< dim > &, \fBModelTopology\fP &, bool reassign_boundary_flags=true)"
.br
.RI "ascii format "
.ti -1c
.RI "template<uint32_t dim> void \fBReadMeshBinary\fP (const std::string &meshfile, \fBVSet\fP< dim > &, \fBModelTopology\fP &, bool reassign_boundary_flags)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File based interface between ANSYS and CSMP\&. 

To provide a file-based interface between the TETRA meshing tool from ANSYS Technologies Inc\&. and CSMP which also allows to extract parts of the input mesh selectively, assign material properties, boundary conditions and to rigorously test the incorporated mesh for its compliance with CSMP requirements\&.

.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
S\&. Geiger 

.PP
S\&.G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
2001
.RE
.PP
.SH "Design Intent"
.PP
File reading has been broken up into modules such that with possible changes only small bits of code must be recreated\&. Also files have been separated into text and binary input, such that the user-readable part is readily accessible in textformat while the bulk of the data reside in an efficiently readable binary file\&.
.SH "Applicability"
.PP
To files which have been written with a specific output module created specifically for CSP by ANSYS technologies (Ulrike Wolf, Berlin)\&.
.SH "Participants"
.PP
The ANSYS interface uses the classes \fBVSet\fP, FEM_Primitive and \fBModelTopology\fP to store the information in which has been retrieved from file\&.
.SH "Implementation"
.PP
Two files: one human readable text (\&.asc = ASCII) file and a binary (\&.dat) file that can be transferred across platforms (Windows OSX, linux etc/)\&.

.PP
The regions and material file ('*\&.asc'):

.PP
.IP "\(bu" 2
model name (line break)
.IP "\(bu" 2
Comment line (header): 1\&. filename, 2\&. date of generaton
.IP "\(bu" 2
Number of labelled objects
.IP "\(bu" 2
Table with objects, element types, material ID values (rock types), number of elements (cells)
.PP

.PP
.PP
.nf
Object   element\-type   material ID   number\-of\-elements
LIV          TETRA_4      3                  760
BOXS         TRI_3        0                  2030
CURVES       BAR_2        0                  20
.fi
.PP

.PP
The material ID facilitates the association of 'rock types' with model regions\&.

.PP
.IP "\(bu" 2
List of elements making up each region (numbered 0\&.\&.\&.n-1), preceded by region name and number of elements of region\&.
.PP

.PP
.PP
.nf
LIV_SMALL 6
12 13 14 15 16 17
.fi
.PP

.PP
The binary file ('*\&.dat') contains:

.PP
.IP "1." 4
NODE COORDINATE DATA (double):
.PP

.PP
PX, PY, PZ records: preceded by a single unsigned long indicating the size of these records which (individually) contain (with or without line breaks):

.PP
px: -> x-coordinates of the nodes 
.br
 py: -> y-coordinates of the nodes pz: -> z-coordinates of the nodes

.PP
(all entries in these records have the format double and the node-IDs are implicit from 0 to nodes-1):

.PP
Such records could be written as shown in the C++ code example below:

.PP
.PP
.nf
double*        ptr; // data pointer
\&.\&.\&.
unsigned long  n0(0), n1(1);

if ( (records=px\&.size()) > 0 && (ptr=const_cast<double*>(px\&.Data())) != NULL ) 
  {
     fwrite( (void*) &records, sizeof(unsigned long), 1, fp );
     fwrite( (void*) ptr, sizeof(double), records, fp );
  }
else fwrite( (void*) &n0, sizeof(unsigned long), 1, fp );
.fi
.PP

.PP
.IP "2." 4
NODE FLAGS (int)
.PP

.PP
PBFLAGS: Same record length as the record set above but in int32_t format\&.

.PP
.IP "\(bu" 2
if a node lies on a model boundary, a negative integer value is assigned to identify that boundary uniquely in terms of the named surface it belongs to\&. If the node is not located on a model boundary, its int value is set to zero\&. If lines or curves were specified on the model boundaries, edge nodes along these lines are flagged by unique negative integers by analogy to the identifiers for the edges in the ANSYS topology\&.

.PP
A boundary and edge numbering scheme for box-shaped models in CSP has the following values (adhering to a righthand-rule coordinate system where x points to the right, y points upward and z points to the front:
.PP

.PP
.PP
.nf
#define BACK_BOTTOM       \-16 // BACK and BOTTOM
#define BACK_RIGHT        \-17 // BACK and RIGHT
#define BACK_TOP          \-18 // BACK and TOP
#define BACK_LEFT         \-19 // BACK and LEFT
#define BOTTOM_RIGHT      \-20 // BOTTOM and RIGHT
#define TOP_RIGHT         \-21 // TOP and RIGHT
#define TOP_LEFT          \-22 // TOP and LEFT
#define BOTTOM_LEFT       \-23 // BOTTOM and LEFT
#define FRONT_BOTTOM      \-24 // FRONT and BOTTOM
#define FRONT_RIGHT       \-25 // FRONT and RIGHT
#define FRONT_TOP         \-26 // FRONT and TOP
#define FRONT_LEFT        \-27 // FRONT and LEFT
.fi
.PP

.PP
.IP "3." 4
BOUNDARY CONDITIONS APPLIED TO NODES (double)
.PP

.PP
PBVALS: Analogous to the record sets above but in double format:

.PP
.IP "\(bu" 2
Corresponding to the non-zero flags from above, where a node is located at a model boundary, a boundary value as previously assigned to the ANSYS topological model can be stored in this data record\&. If no value was assigned, this record will just hold zeroes\&.
.PP
.IP "4." 4
TYPE OF FINITE ELEMENTS (enum -> unsigned int)
.PP

.PP
PELMT (0\&.\&.\&.e-1): Record is preceded by an unsigned long indicating record size (=number of finite elements in the mesh)\&. 'pelmt' consists of a single record of (all as unsigned longs):

.PP
.IP "\(bu" 2
element-type identifiers (unsigned int) for each finite element in the mesh\&. How they correspond to element type strings is specified further below\&.

.PP
Dieser Eintrag vermeidet Doppeldeutigkeiten, die dadurch entstehen koennten, dass es verschiedene Elementtypen mit der gleichen Anzahl von Knotenpunkten gibt\&. 
.br

.PP
.IP "5." 4
MESH CONNECTIVITY (unsigned long)
.PP

.PP
PLIST: Record preceded by an unsigned long indicating record size, a single record follows containing (all as unsigned longs):

.PP
.IP "\(bu" 2
node ids of each element in counter-clockwise order (according to node numbering on reference elements)\&. The enlisted node numbers range from 0\&.\&.\&.nodes-1 as above\&.
.PP

.PP
The elements are numbered implicitly and continuously by their position in the plist (there must be no jumps in the element ids)\&.

.PP
PFVERTS: Record preceded by unsigned long indicating record size, then a single record (all long, where negative numbers denote model boundaries):

.PP
.IP "\(bu" 2
neighbour elements of each element in an order defined for each existing element type (see further below, for tetrahedra and triangles, neighbors are those elements touching the element's faces opposite of its corner nodes)\&. Neighbor elements are denoted 0\&.\&.\&.element-1\&. Where there are no neighbour elements adjacent to the element's faces because the element lies on a model boundary, a negative long is used to identify this boundary surface\&. 
.br

.PP
.IP "6." 4
MATERIAL IDENTIFIER FOR EACH ELEMENT = ROCK TYPE
.PP

.PP
PMTRL: preceded by number of elements, associates each element with the material flag from the '*\&.asc' file such that properties can be assigned\&. 
.br

.PP
Comments: leading hash key (# everything thereafter is ignored)
.SH "Application Examples"
.PP
Human readable geometry descrition file (*\&.asc):

.PP
.PP
.nf
icem_example1
'icem1\&.asc' generated by SKM on 8/6/2001
7 # Anzahl Families
# Objektname   Elementtyp   Materialkennzahl   Anzahl\-Elemente
soil                 TRI_3                  1                   6
rock                 TRI_3                  2                   1
air                  TRI_3                  3                   5
left_boundary    BAR_2                  1                   2
right_boundary BAR_2                    3                   2
top_boundary     BAR_2                  3                   2
bottom_boundary BAR_2                   1                   2
# now the elements which make up each object are listed in sequence
soil 6
2 4 7 8 9 10
rock 1
5
air 5
0 1 3 6 11
left_boundary 2
12 13
right_boundary 2
18 19
top_boundary 2
14 15
bottom_boundary 2
16 17
.fi
.PP

.PP
Mesh connectivity file (*\&.dat) in text ASCII version:

.PP
.PP
.nf
11 # px, py, pz
0\&. 5\&. 10\&. 0\&. 5\&. 10\&. 2\&.5 7\&.5 0\&. 5\&. 10\&.
10\&. 10\&. 10\&. 6\&. 7\&. 5\&. 4\&. 4\&. 0\&. 0\&. 0\&.
0\&. 0\&. 0\&. 0\&. 0\&. 0\&. 0\&. 0\&. 0\&. 0\&. 0\&.
# pbflags
\-13 \-5 \-14 \-2 0 \-3 0 0 \-8 \-4 \-10
# pbvals
0\&. 5\&. 10\&. 0\&. 0\&. 10\&. 0\&. 0\&. 0\&. 5\&. 10\&.
20 # pelements
3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2
42 # plist
0 4 1  1 4 2  0 3 4  3 6 4  4 6 7  4 7 5  3 8 6
6 8 9  6 9 7  7 9 10  7 10 5  0 3  3 8  0 1  1 2
8 9  9 10  2 5  5 10
42 # pfverts
1 \-5 2  3 \-5 0  4 0 \-2  5 2 7  9 6 4  11 3 5  \-3 1 6
8 4 \-2  \-4 9 7  10 5 8  11 9 \-4  \-3 6 10
\-2 2  \-2 7  0 \-5  1 \-5  \-4 8  \-4 10  3 \-3  11 \-3
20 # pmaterial
3 3 1 3 1 2 3 1 1 1 1 3 1 1 3 3 1 1 3 3
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::ANSYS_Interface::ANSYS_Interface (bool create_isoparametric_element_mesh = \fRtrue\fP)\fR [explicit]\fP"
Constructs the \fBANSYS_Interface\fP interface object\&.
.SH "Input Arguments"
.PP
The default argument of the constructor (false) means that it will try to output finite elements using a global interpolation coordinate system to the client objects\&. However there are currently only line, triangular and tetrahedral elements with linear basis functions available in CSMP because the elements must be straight-sided for such an approach to work\&. Instead isoparametric elements can be used\&. 
.br

.PP
In order to create isoparametric element models use 'true'\&. 
.br

.PP
At the moment, CSMP supports analytical element forms only for tetra-triangular poly-element type meshes\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void csmp::ANSYS_Interface::Read_ANSYS_Mesh (const std::string & mesh_file_set, \fBVSet\fP< dim > & , \fBModelTopology\fP & , bool binary_input_file, bool reassign_boundary_flags = \fRtrue\fP)"

.PP
Reading function\&. needed when users do not properly assign them in ANSYS 
.SS "template<uint32_t dim> void csmp::ANSYS_Interface::Read_ANSYS_Mesh (const string & filename, \fBVSet\fP< dim > & vset, \fBModelTopology\fP & mesh_topology, bool binary_input_file, bool reassign_boundary_flags)"

.PP
Builds \fBModel\fP after it was constructed with the default constructor\&. read ansys mesh
.SS "template<uint32_t dim> bool csmp::ANSYS_Interface::ReadBoundaryFlagsAndConditionsASCII (ifstream & ifs, \fBVSet\fP< dim > & vset)"
The method reads the boundary condition and flag records from the input stream and stores them in the pbound and pbcond records in the \fBVSet\fP\&. 
.br
.SH "Input Arguments"
.PP
A reference to the initialized ASCII input file stream\&. 
.br

.PP
\fBReturns\fP
.RS 4
The boundary flags and values at where nodes were flagged as boundary nodes are stored in the second method argument\&. 
.RE
.PP

.SS "template<uint32_t dim> void csmp::ANSYS_Interface::ReadMeshASCII (const string & meshfile, \fBVSet\fP< dim > & vset, \fBModelTopology\fP & mesh_topology, bool reassign_boundary_flags)"
Reads ANSYS '\fI\&.asc' and '\fP\&.dat' files as created by the Input module in the MED interface\&. The dat files which store the mesh connectivity must be in ASCII format\&.

.PP
This method reads models of an arbitrary shape and returns them into the supplied \fBVSet\fP and mesh topology file\&. In order to assign boundary conditions to irregular shaped models one can use the outer surfaces if they are named appropriately\&. This must be done using the CAD and ANSYS tools\&.
.SH "Input Arguments"
.PP
The method needs the model name which it will automatically expand into the names of the '\fI\&.asc' and '\fP\&.dat' files\&.
.SH "Application Examples"
.PP
To read the ASCII file '*dat' specifications that make sense for small box-shaped models for which the mesh data are to be transferred between different platforms so that binary files cannot be used\&.
.SH "Messages"
.PP
The output is rather verbose, alerting the user to all potential errors that may have occurred in the reading and processing phase of the input data\&. check topology
.SS "template<uint32_t dim> void csmp::ANSYS_Interface::ReadMeshBinary (const std::string & meshfile, \fBVSet\fP< dim > & , \fBModelTopology\fP & , bool reassign_boundary_flags)\fR [protected]\fP"
binary format use the binary interfaces for efficient reading of large files 
.SS "template<uint32_t dim> void csmp::ANSYS_Interface::ReadMeshBinary (const string & meshfile, \fBVSet\fP< dim > & vset, \fBModelTopology\fP & mesh_topology, bool reassign_boundary_flags)"
Reads ANSYS finite element meshes created by any of the tools accessible through MED\&. If box shaped model geometry is assumed the method will attempt to set flags that will later be used to assign boundary counditions in CSMP (see method documentation for Model::AssignBoundaryValues3D() )\&. 
.br
.SH "Input Arguments"
.PP
The method needs the filename (without extension) of the '\fI\&.asc', '\fP\&.dat' file pair that is output by the Input utility in the ANSYS mesher\&. 
.br

.PP
\fBParameters\fP
.RS 4
\fIvset\fP The correctly read mesh and the family definitions are returned into the user supplied vset and model topology objects, respectively\&. 
.br
.br
\fImesh_topology\fP the elements that make up the different model regions
.RE
.PP
.SH "Implementation"
.PP
Reads Ulrike's binary output from Tetra 30/7/2003 which is written as follows: 
.br

.PP
.PP
.nf
// 32 bit integers and unsigned integers
unsigned int nnodes;
unsigned int records;
unsigned int lplist, lpfverts; // overall length of plist, pfvert records
unsigned int lelem;

// 32 bit integers and unsigned integers arrays
int          *pbflags, *pfverts;
unsigned int *pelmt, *pmtrl, *plist;

// 64 bit double arrays
double *pnts, *px, *py, *pz;
double *pbvals;

records = (unsigned int) nnodes; // changed

// writing the nnodes\-sized data blocks to file
// size = nnodes (Knotenpunkte)
fwrite(&records, sizeof(unsigned int), 1, fdat); 
fwrite(px, sizeof(double), nnodes, fdat);
fwrite(py, sizeof(double), nnodes, fdat);
fwrite(pz, sizeof(double), nnodes, fdat);
fwrite(pbflags, sizeof(int), nnodes, fdat);
fwrite(pbvals, sizeof(double), nnodes, fdat);
// size = nelements (Finite Elemente)
fwrite(&lelem, sizeof(unsigned int), 1, fdat);
fwrite(pelmt, sizeof(int), lelem, fdat);
// size = sum over nodes per element
fwrite(&lplist, sizeof(unsigned int), 1, fdat);
fwrite(plist, sizeof(unsigned int), lplist, fdat);
// size = sum over neighbors per element
fwrite(&lpfverts, sizeof(unsigned int), 1, fdat);
fwrite(pfverts, sizeof(int), lpfverts, fdat);
// size = nelements (Finite Elemente)
fwrite(&lelem, sizeof(unsigned int), 1, fdat);
fwrite(pmtrl, sizeof(int), lelem, fdat);
.fi
.PP

.PP
NB: \fBElement\fP IDs in the ANSYS dataset are 0\&.\&.n-1 by default\&.
.SH "Application Examples"
.PP
Creates an interface the ANSYS suite of meshing tools\&. This interface can also be used for mixed (poly-element type meshes)\&. 
.br
.SH "Messages"
.PP
To protect the user against the erratic reading of transferred binary files a detailed reporting of the reading progress is output and errors are raised is encountered\&. 
.SS "template<uint32_t dim> bool csmp::ANSYS_Interface::ReadNodeCoordinatesASCII (ifstream & ifs, \fBVSet\fP< dim > & vset)"

.PP
ASCII DATA FILE\&. The method reads the node coordinate block from the supplied file stream\&. 
.br
.SH "Input Arguments"
.PP
A reference to the initialized ASCII input file stream\&. 
.br

.PP
\fBReturns\fP
.RS 4
The node coordinates are stored in the px, py, and pz records of the \fBVSet\fP\&. 
.RE
.PP

.SS "template<uint32_t dim> bool csmp::ANSYS_Interface::ReadPelementASCII (ifstream & ifs, \fBVSet\fP< dim > & vset)"
Reads element-type integer-based identifiers for each element which are later parsed to determine the number of nodes per element and neighbors per element for the reading process\&.
.SH "Input Arguments"
.PP
A reference to the initialized ASCII input file stream\&. 
.SS "template<uint32_t dim> bool csmp::ANSYS_Interface::ReadPfvertsASCII (ifstream & ifs, \fBVSet\fP< dim > & vset)"
The 'pfverts' record stores the IDs of the finite elements that sit opposite to the faces of the current finite element\&. If the face is located at the model boundary a negative boundary flag is stored in stead of the neighbor ID\&. 
.br
.SH "Input Arguments"
.PP
A reference to the initialized ASCII input file stream\&. 
.br

.PP
\fBReturns\fP
.RS 4
The pfvert information is added to the second argument \fBVSet\fP\&. 
.RE
.PP

.SS "template<uint32_t dim> bool csmp::ANSYS_Interface::ReadPlistASCII (ifstream & ifs, \fBVSet\fP< dim > & vset)"
The method reads the 'plist' record from the supplied ASCII file\&. The plist contains the nodel id's of the consecutive finite elements that make up the mesh\&. These are output to the \fBVSet\fP\&. 
.br
.SH "Input Arguments"
.PP
A reference to the initialized ASCII file stream that points to the beginning of the plist data block\&. 
.br

.PP
\fBReturns\fP
.RS 4
The \fBVSet\fP into which the plist data shall be stored is supplied as the second method argument\&. 
.RE
.PP

.SS "template<uint32_t dim> bool csmp::ANSYS_Interface::ReadPmaterialASCII (ifstream & ifs, \fBVSet\fP< dim > & vset)"
Method reads the material ID record from the file stream and assigns the data to the argument \fBVSet\fP\&. 
.br
.SH "Input Arguments"
.PP
A reference to the initialized ASCII input file stream\&. 
.br

.PP
\fBReturns\fP
.RS 4
The material information is assigned to the supplied \fBVSet\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
