.TH "csmp::StressInvariants" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::StressInvariants \- standard decompositions of stress tensor, see Smith & Griffith  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'main_library/constitutive_relationships/mechanics/'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStressInvariants\fP (const \fBTensorVariable\fP< 2U > &)"
.br
.RI "factors the upper triagonal of the symmetric tensor in terms of s, t, and theta "
.ti -1c
.RI "\fBStressInvariants\fP (const \fBTensorVariable\fP< 3U > &)"
.br
.ti -1c
.RI "double \fBLodeAngle\fP (const \fBTensorVariable\fP< 2U > &) const"
.br
.RI "theta angle in Mohr-Coulomb diagram that at which shear stresses are maximized "
.ti -1c
.RI "double \fBLodeAngle\fP (const \fBTensorVariable\fP< 3U > &) const"
.br
.ti -1c
.RI "double \fBMeanStress\fP () const"
.br
.RI "mean stress = average of principal stresses "
.ti -1c
.RI "double \fBDeviatoricStress\fP () const"
.br
.RI "maximum of the deviatoric stresses = nonisostatic stresses "
.ti -1c
.RI "double \fBMaximumPrincipalStress1\fP () const"
.br
.RI "sigma1 = maximum principal stress (Pa) "
.ti -1c
.RI "double \fBIntermediatePrincipalStress2\fP () const"
.br
.RI "sigma2 "
.ti -1c
.RI "double \fBLeastPrincipalStress3\fP () const"
.br
.RI "sigma3 "
.ti -1c
.RI "double \fBMohrCoulombYieldEnvelope\fP (double friction_angle_alpha) const"
.br
.RI "K(theta), see Zienkiewitz, volume 2, chapter 4\&.5\&.1, p\&. 233, alpha is in degrees\&. "
.ti -1c
.RI "double \fBSmoothMohrCoulombYieldEnvelope\fP (double friction_angle_alpha) const"
.br
.RI "K(theta), see Zienkiewitz, volume 2, chapter 4\&.5\&.11, alpha is in degrees\&. "
.in -1c
.SH "Detailed Description"
.PP 
standard decompositions of stress tensor, see Smith & Griffith 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei
.RE
.PP
.SH "Motivation"
.PP
To extract the standard engineering invariants s, t, and theta from the upper diagonal of a (symmetric diagonally dominant) Cartesian stress tensor, calculate the principal stresses, and evaluate a series of failure criteria\&.
.SH "Applicability"
.PP
CSMP geomechanics models\&.
.SH "Collaborations"
.PP
.SH "Implementation"
.PP
Follows Zienkiewitz volume 2 and Smith and Griffith\&.
.SH "Application Examples"
.PP
To get an \fBIndex\fP for a variable of interest in order to perform a computation, do the following:

.PP
\fBTest\fP
.RS 4
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::StressInvariants::StressInvariants (const \fBTensorVariable\fP< 2U > & ts)\fR [explicit]\fP"

.PP
factors the upper triagonal of the symmetric tensor in terms of s, t, and theta factors the upper triagonal of the symmetric tensor in terms of s, t, and theta

.PP
upper diagonal matrix:

.PP
sigmaxx = Cartesian_stress_(0,0); sigmayy = Cartesian_stress_(1,1); sigmaxy = Cartesian_stress_(0,1); 
.SS "csmp::StressInvariants::StressInvariants (const \fBTensorVariable\fP< 3U > & ts)\fR [explicit]\fP"
factors the upper triagonal of the symmetric tensor in terms of s, t, and theta

.PP
upper diagonal matrix:

.PP
sigmaxx = Cartesian_stress_(0,0); sigmayy = Cartesian_stress_(1,1); sigmazz = Cartesian_stress_(2,2); sigmaxy = Cartesian_stress_(0,1); sigmaxz = Cartesian_stress_(0,2); sigmayz = Cartesian_stress_(1,2); 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::StressInvariants::LodeAngle (const \fBTensorVariable\fP< 2U > & ts) const"

.PP
theta angle in Mohr-Coulomb diagram that at which shear stresses are maximized 2D version 
.SS "double csmp::StressInvariants::LodeAngle (const \fBTensorVariable\fP< 3U > & ts) const"
theta angle in Mohr-Coulomb diagram that at which shear stresses are maximized

.PP
\fBAttention\fP
.RS 4
original angle(theta), is in radians (Smith & Griffiths, eq\&. 6\&.3\&. p\&. 227 
.RE
.PP

.SS "double csmp::StressInvariants::MaximumPrincipalStress1 () const"

.PP
sigma1 = maximum principal stress (Pa) sigma1 = maximum principal stress (Pa) as obtained from the modified deviatoric and mean stresses, see Smith & Griffith, p\&. 234 
.SS "double csmp::StressInvariants::MohrCoulombYieldEnvelope (double alpha) const"

.PP
K(theta), see Zienkiewitz, volume 2, chapter 4\&.5\&.1, p\&. 233, alpha is in degrees\&. hexagonal K(theta), see Zienkiewitz, volume 2, chapter 4\&.5\&.1, p\&. 233

.PP
\fBAttention\fP
.RS 4
no material parameters (other than the friction angle) are contained in this assessment\&. However, these need to enter failure calculations that are handled in other classes, such as \fBBrittleFailure\fP\&. 
.RE
.PP

.SS "double csmp::StressInvariants::SmoothMohrCoulombYieldEnvelope (double alpha) const"

.PP
K(theta), see Zienkiewitz, volume 2, chapter 4\&.5\&.11, alpha is in degrees\&. Computing K_OfTheta = 1/G_OfTheta ( modified Mohr-Coulomb envelope with smooth boundaries ): Zienkiewitz, Finite element method for solid and structural mechanics, Chapter 4\&. Inelastic and non-linear materials 4\&.11\&. Non-uniqueness and localization in elasto-plastic deformations

.PP
\fBAttention\fP
.RS 4
no material parameters (other than the friction angle) are contained in this assessment\&. However, these need to enter failure calculations that are handled in other classes, such as \fBBrittleFailure\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
