.TH "csmp::LocalVariableStorage< dim, STOREE >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::LocalVariableStorage< dim, STOREE >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <LocalVariableStorage\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalVariableStorage\fP (const \fBLocalVariables\fP &)"
.br
.RI "Ctor for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "\fBLocalVariableStorage\fP (const \fBLocalVariables\fP &, const \fBIntegrationPointVariables\fP &)"
.br
.RI "Goto overload for storees with \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "\fBLocalVariableStorage\fP (const \fBLocalVariableStorage\fP< dim, STOREE > &)"
.br
.ti -1c
.RI "\fBLocalVariableStorage\fP (\fBLocalVariableStorage\fP< dim, STOREE > &&)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLocalVariableStorage\fP< dim, STOREE > &) const"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBResizePropertyStorage\fP (const \fBLocalVariables\fP &)"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBResizePropertyStorage\fP (const \fBLocalVariables\fP &, const \fBIntegrationPointVariables\fP &)"
.br
.RI "Goto overload for storees with \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBResizePropertyStorage\fP (int_type dataComponents, int_type flagComponents)"
.br
.RI "Resizes the storage preserving original values if any (this is where all ResizePropertyStorage end up) "
.ti -1c
.RI "void \fBAddProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Creates an empty space in the storage preserving the original variable values\&. \fBLocalVariables\fP in \fBIndex\fP have to reflect NEW state (incl added) "
.ti -1c
.RI "void \fBDeleteProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Deletes data and flags of property \fBLocalVariables\fP in \fBIndex\fP have to reflect CURRENT state (incl property to be removed) "
.ti -1c
.RI "bool \fBIsWithinRange\fP (const \fBcsmp::Index\fP &, double, double) const"
.br
.ti -1c
.RI "double \fBRead\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar variable value\&. "
.ti -1c
.RI "void \fBRead\fP (const \fBcsmp::Index\fP &, \fBScalarVariable\fP &) const"
.br
.RI "Scalar variable\&. "
.ti -1c
.RI "void \fBRead\fP (const \fBcsmp::Index\fP &, \fBVectorVariable\fP< dim > &) const"
.br
.RI "Vector variable\&. "
.ti -1c
.RI "void \fBRead\fP (const \fBcsmp::Index\fP &, \fBTensorVariable\fP< dim > &) const"
.br
.RI "Tensor variable\&. "
.ti -1c
.RI "void \fBRead\fP (const \fBcsmp::Index\fP &, \fBArrayVariable\fP &) const"
.br
.RI "Array variable\&. "
.ti -1c
.RI "void \fBRead\fP (const \fBcsmp::Index\fP &, \fBFlaggedArrayVariable\fP &) const"
.br
.RI "FlaggedArray variable\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBVectorVariable\fP< dim > &)"
.br
.RI "Vector variable\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBTensorVariable\fP< dim > &)"
.br
.RI "Tensor variable\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBArrayVariable\fP &)"
.br
.RI "Array variable\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBFlaggedArrayVariable\fP &)"
.br
.RI "FlaggedArray variable\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar & Array variable flag\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::Index\fP &, int_type) const"
.br
.RI "Vector, Tensor, FlaggedArray variable flag\&. "
.ti -1c
.RI "void \fBStatus\fP (const \fBcsmp::Index\fP &, \fBVARIABLE_FLAG\fP)"
.br
.RI "Scalar & Array variable flag\&. "
.ti -1c
.RI "void \fBStatus\fP (const \fBcsmp::Index\fP &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.RI "Vector,Tensor, FlaggedArray variable flag\&. "
.ti -1c
.RI "bool \fBIsWithinRange\fP (uint32_t ip, const \fBcsmp::Index\fP &, double, double) const"
.br
.ti -1c
.RI "double \fBRead\fP (uint32_t ip, const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar variable value at integration point\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t ip, const \fBcsmp::Index\fP &, \fBScalarVariable\fP &) const"
.br
.RI "Scalar variable at integration point\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t ip, const \fBcsmp::Index\fP &, \fBVectorVariable\fP< dim > &) const"
.br
.RI "Vector variable at integration point\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t ip, const \fBcsmp::Index\fP &, \fBTensorVariable\fP< dim > &) const"
.br
.RI "Tensor variable at integration point\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t ip, const \fBcsmp::Index\fP &, \fBArrayVariable\fP &) const"
.br
.RI "Array variables\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t ip, const \fBcsmp::Index\fP &, \fBFlaggedArrayVariable\fP &) const"
.br
.RI "FlaggedArray variables\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t ip, const \fBcsmp::Index\fP &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable at integration point\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t ip, const \fBcsmp::Index\fP &, const \fBVectorVariable\fP< dim > &)"
.br
.RI "Vector variable at integration point\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t ip, const \fBcsmp::Index\fP &, const \fBTensorVariable\fP< dim > &)"
.br
.RI "Tensor variable at integration point\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t ip, const \fBcsmp::Index\fP &, const \fBArrayVariable\fP &)"
.br
.RI "Array variable at integration point\&. "
.ti -1c
.RI "void \fBStoreArrayEntry\fP (const \fBcsmp::Index\fP &, double array_elmt_value, int_type)"
.br
.ti -1c
.RI "double \fBReadArrayEntry\fP (const \fBcsmp::Index\fP &, int_type array_elmt) const"
.br
.RI "reads single double element inside of the target array "
.ti -1c
.RI "void \fBStore\fP (uint32_t ip, const \fBcsmp::Index\fP &, const \fBFlaggedArrayVariable\fP &)"
.br
.RI "FlaggedArray variable at integration point\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t ip, const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar & Array variable flag at integration point\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t ip, const \fBcsmp::Index\fP &, int_type) const"
.br
.RI "Vector, Tensor, FlaggedArray variable flag at integration point\&. "
.ti -1c
.RI "void \fBStatus\fP (uint32_t ip, const \fBcsmp::Index\fP &, \fBVARIABLE_FLAG\fP)"
.br
.RI "Scalar & Array variable flag at integration point\&. "
.ti -1c
.RI "void \fBStatus\fP (uint32_t ip, const \fBcsmp::Index\fP &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.RI "Vector, Tensor, FlaggedArray variable flag at integration point\&. "
.ti -1c
.RI "bool \fBIsWithinRange\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, double, double) const"
.br
.ti -1c
.RI "double \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &) const"
.br
.ti -1c
.RI "void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, \fBScalarVariable\fP &) const"
.br
.RI "Scalar variable at facet or sector integration point\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, \fBVectorVariable\fP< dim > &) const"
.br
.RI "Vector variable at facet or sector integration point\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, \fBTensorVariable\fP< dim > &) const"
.br
.RI "Tensor variable at facet or sector integration point\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, \fBArrayVariable\fP &) const"
.br
.RI "Array variables at sector or facet integration points\&. "
.ti -1c
.RI "void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, \fBFlaggedArrayVariable\fP &) const"
.br
.RI "FlaggedArray variables\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable at facet or sector integration point\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, const \fBVectorVariable\fP< dim > &)"
.br
.RI "Vector variable at integration point\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, const \fBTensorVariable\fP< dim > &)"
.br
.RI "Tensor variable at sector or facet integration point\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, const \fBArrayVariable\fP &)"
.br
.RI "Array variable at sector or facet integration poin\&. "
.ti -1c
.RI "void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, const \fBFlaggedArrayVariable\fP &)"
.br
.RI "FlaggedArray variable at facet or sector integration point\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar & Array variable flag at facet or sector integration point\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, int_type) const"
.br
.RI "Vector, Tensor, FlaggedArray variable flag at integration point\&. "
.ti -1c
.RI "void \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, \fBVARIABLE_FLAG\fP)"
.br
.RI "Scalar & Array variable flag at facet or sector integration point (note that the Array has only a single flag) "
.ti -1c
.RI "void \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.RI "Vector, Tensor, FlaggedArray variable flag at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> double \fBRead\fP (const \fBcsmp::INDEX\fP< SCALAR, place > &) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (const \fBcsmp::INDEX\fP< SCALAR, place > &, \fBScalarVariable\fP &) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (const \fBcsmp::INDEX\fP< VECTOR, place > &, \fBVectorVariable\fP< dim > &) const"
.br
.RI "Vector variable\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (const \fBcsmp::INDEX\fP< TENSOR, place > &, \fBTensorVariable\fP< dim > &) const"
.br
.RI "Tensor variable\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (const \fBcsmp::INDEX\fP< ARRAY, place > &, \fBArrayVariable\fP &) const"
.br
.RI "Array variable (as a whole) "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, \fBFlaggedArrayVariable\fP &) const"
.br
.RI "FlaggedArray variable\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (const \fBcsmp::INDEX\fP< SCALAR, place > &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (const \fBcsmp::INDEX\fP< VECTOR, place > &, const \fBVectorVariable\fP< dim > &)"
.br
.RI "Vector variable\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (const \fBcsmp::INDEX\fP< TENSOR, place > &, const \fBTensorVariable\fP< dim > &)"
.br
.RI "Tensor variable\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (const \fBcsmp::INDEX\fP< ARRAY, place > &, const \fBArrayVariable\fP &)"
.br
.RI "Array variable (as a whole) "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, const \fBFlaggedArrayVariable\fP &)"
.br
.RI "FlaggedArray variable\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::INDEX\fP< SCALAR, place > &) const"
.br
.RI "Scalar & Array variable flag\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::INDEX\fP< ARRAY, place > &) const"
.br
.RI "\fBArrayVariable\fP\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::INDEX\fP< VECTOR, place > &, int_type) const"
.br
.RI "Vector, Tensor, FlaggedArray variable flag\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::INDEX\fP< TENSOR, place > &, int_type) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, int_type) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (const \fBcsmp::INDEX\fP< SCALAR, place > &, \fBVARIABLE_FLAG\fP)"
.br
.RI "Scalar & Array variable flag\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (const \fBcsmp::INDEX\fP< ARRAY, place > &, \fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (const \fBcsmp::INDEX\fP< VECTOR, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.RI "Vector variable flag\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (const \fBcsmp::INDEX\fP< TENSOR, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.RI "Tensor variable flag\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.RI "FlaggedArray variable flag\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> double \fBRead\fP (uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &) const"
.br
.RI "Scalar variable value at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &, \fBScalarVariable\fP &) const"
.br
.RI "Scalar variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t ip, const \fBcsmp::INDEX\fP< VECTOR, place > &, \fBVectorVariable\fP< dim > &) const"
.br
.RI "Vector variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t ip, const \fBcsmp::INDEX\fP< TENSOR, place > &, \fBTensorVariable\fP< dim > &) const"
.br
.RI "Tensor variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t ip, const \fBcsmp::INDEX\fP< ARRAY, place > &, \fBArrayVariable\fP &) const"
.br
.RI "Array variables\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t ip, const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, \fBFlaggedArrayVariable\fP &) const"
.br
.RI "FlaggedArray variables\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t ip, const \fBcsmp::INDEX\fP< VECTOR, place > &, const \fBVectorVariable\fP< dim > &)"
.br
.RI "Vector variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t ip, const \fBcsmp::INDEX\fP< TENSOR, place > &, const \fBTensorVariable\fP< dim > &)"
.br
.RI "Tensor variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t ip, const \fBcsmp::INDEX\fP< ARRAY, place > &, const \fBArrayVariable\fP &)"
.br
.RI "Array variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t ip, const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, const \fBFlaggedArrayVariable\fP &)"
.br
.RI "FlaggedArray variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &) const"
.br
.RI "Scalar & Array variable flag at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< ARRAY, place > &) const"
.br
.RI "Scalar & Array variable flag at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< VECTOR, place > &, int_type) const"
.br
.RI "Vector, Tensor, FlaggedArray variable flag at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< TENSOR, place > &, int_type) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, int_type) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &, \fBVARIABLE_FLAG\fP)"
.br
.RI "Scalar & Array variable flag at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< ARRAY, place > &, \fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< VECTOR, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.RI "Vector, Tensor, FlaggedArray variable flag at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< TENSOR, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t ip, const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> double \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &, \fBScalarVariable\fP &) const"
.br
.RI "Scalar variable at facet or sector integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< VECTOR, place > &, \fBVectorVariable\fP< dim > &) const"
.br
.RI "Vector variable at facet or sector integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< TENSOR, place > &, \fBTensorVariable\fP< dim > &) const"
.br
.RI "Tensor variable at facet or sector integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< ARRAY, place > &, \fBArrayVariable\fP &) const"
.br
.RI "Array variables at sector or facet integration points\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBRead\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, \fBFlaggedArrayVariable\fP &) const"
.br
.RI "FlaggedArray variables\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable at facet or sector integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< VECTOR, place > &, const \fBVectorVariable\fP< dim > &)"
.br
.RI "Vector variable at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< TENSOR, place > &, const \fBTensorVariable\fP< dim > &)"
.br
.RI "Tensor variable at sector or facet integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< ARRAY, place > &, const \fBArrayVariable\fP &)"
.br
.RI "Array variable at sector or facet integration poin\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStore\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, const \fBFlaggedArrayVariable\fP &)"
.br
.RI "FlaggedArray variable at facet or sector integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &) const"
.br
.RI "Scalar & Array variable flag at facet or sector integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< ARRAY, place > &) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< VECTOR, place > &, int_type) const"
.br
.RI "Vector, Tensor, FlaggedArray variable flag at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< TENSOR, place > &, int_type) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> \fBVARIABLE_FLAG\fP \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, int_type) const"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > &, \fBVARIABLE_FLAG\fP)"
.br
.RI "Scalar & Array variable flag at facet or sector integration point (note that the Array has only a single flag) "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< ARRAY, place > &, \fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< VECTOR, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.RI "Vector, Tensor, FlaggedArray variable flag at integration point\&. "
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< TENSOR, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "template<\fBPLACEMENT\fP place> void \fBStatus\fP (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< FLAGGEDARRAY, place > &, int_type, \fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "bool \fBEmptyLVS\fP () const"
.br
.ti -1c
.RI "void \fBOutLVS\fP () const"
.br
.ti -1c
.RI "void \fBAssertPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertFiniteVolumeIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBStoreLocalState\fP (const \fBLocalVariables\fP &lv)"
.br
.RI "We store in debug only\&. "
.ti -1c
.RI "void \fBLVS\fP (const \fBData\fP &data)"
.br
.RI "copy or move supplied data into storage "
.ti -1c
.RI "void \fBLVS\fP (\fBData\fP &&data)"
.br
.ti -1c
.RI "const \fBData\fP \fBLVS\fP () const"
.br
.RI "return copy of the data container for misc operations (will use rcopy elision "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class STOREE>
.br
class csmp::LocalVariableStorage< dim, STOREE >"CSMP local/physical variable storage

.PP
\fBAuthor\fP
.RS 4
P\&. Lang 

.PP
S\&.K\&. Matthai 
.RE
.PP
\fBDate\fP
.RS 4
2007-2012
.RE
.PP
\fBAttention\fP
.RS 4
CSMP runs should be performed at least once in DEBUG mode with conceptual models to check validity of Read/Store calls\&. For performance, these checks are omitted in RELEASE\&.
.RE
.PP
.SH "Storee Concept"
.PP
Storees have to follow:

.PP
.IP "\(bu" 2
providing a 
.PP
.nf
PLACEMENT Placement() const { return PLACEMENT; } 

.fi
.PP
 function, in which \fBPLACEMENT\fP is i\&.e\&. ELEMENT, NODE etc\&. (global csmp enum)
.IP "\(bu" 2
in the assignment operator (and copy ctor), add: 
.PP
.nf
this\->LVS( el\&.LVS() ); 

.fi
.PP

.PP
.SH "Design Intent"
.PP
We use CRT static polymorphism here to allow for non-virtual Placement() functions and exploit compile time type information\&. All methods specific to storees with integration points (\fBElement\fP, \fBFace\fP, \fBInterFace\fP) will fail AT COMPILE TIME when used for storees without integration points (\fBRegion\fP, \fBBoundary\fP, \fBSplitBoundary\fP)

.PP
\fBNote\fP
.RS 4
Ideally we would like to use type traits instead of crt, but this would require change of csmp interface and wouldn't provide any performance increase
.RE
.PP
.SH "Implementation"
.PP
We store always in order: all \fBScalarVariable\fP data/flags, then all \fBVectorVariable\fP data/flags, then all \fBTensorVariable\fP data/flags and finally all \fBArrayVariable\fP data/flags At integration points this holds, whith all ELEMENT_INTEGRATION_POINT variables first (storing all such values for the first integration point, then for the second and so forth), then all SECTOR_INTEGRATION_POINT and last all FACET_INTEGRATION_POINT (for each IP) We perform validity checks on Read/Store etc in debug mode only, that is with no 'NDEBUG' symbol\&. Additional checks are activated if 'VARIABLE_STORAGE_DEBUG' is set\&.

.PP
\fBAttention\fP
.RS 4
The variable storage is implicitly coupled with the \fBPropertyDatabase\fP through the \fBIndex\fP and its offset calculation performed there
.RE
.PP
\fBTodo\fP
.RS 4
(3-D) We could now even go for a single Read/Write function templatized on Variable type\&. Variable placement would then be needed to be available in variables\&. 
.RE
.PP
\fBNote\fP
.RS 4
It's probably not sensible to merge duplicated functionality here for performance reasons 
.RE
.PP
\fBTodo\fP
.RS 4
(2-D) DocMe (index arithmetic) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class STOREE> \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::LocalVariableStorage (const \fBLocalVariables\fP & lv, const \fBIntegrationPointVariables\fP & ipv)"

.PP
Goto overload for storees with \fBIntegrationPointVariables\fP\&. 
.PP
\fBAttention\fP
.RS 4
Will fail AT COMPILE TIME (very nice\&.\&.\&.) if used for an storee without integration points 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class STOREE> void \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::AddProperty (const \fBcsmp::Index\fP & prop_key)"

.PP
Creates an empty space in the storage preserving the original variable values\&. \fBLocalVariables\fP in \fBIndex\fP have to reflect NEW state (incl added) 
.PP
\fBTodo\fP
.RS 4
(2-F) Integration point properties not supported 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
(2-F) Asserts missing 
.RE
.PP

.PP
Roman, 2013: with ipvs support
.SS "template<uint32_t dim, template< uint32_t > class STOREE> void \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::DeleteProperty (const \fBcsmp::Index\fP & prop_key)"

.PP
Deletes data and flags of property \fBLocalVariables\fP in \fBIndex\fP have to reflect CURRENT state (incl property to be removed) 
.PP
\fBTodo\fP
.RS 4
(2-F) Asserts missing 
.RE
.PP

.PP
Roman, 2013: with ipvs support
.SS "template<uint32_t dim, template< uint32_t > class STOREE> bool \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::IsWithinRange (const \fBcsmp::Index\fP & idx, double vmin, double vmax) const"

.PP
\fBTodo\fP
.RS 4
replace this super wasteful method 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class STOREE> bool \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::IsWithinRange (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP & idx, double vmin, double vmax) const"
checks whether any value of the target variable is within the range supplied via the arguments vmin and vmax\&.

.PP
\fBAttention\fP
.RS 4
for a vector, tensor, or array this range check is performed on all their elements\&.
.RE
.PP
\fBTodo\fP
.RS 4
refactor: for vectors, tensors and array variables this method is terribly inefficient as it creates temporaries for the checking\&. 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class STOREE> void \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::OutLVS () const"
revised SKM 5/6/2020 - Michael Liem highlighted output problem; not tested for vectors and tensors yet

.PP
\fBAttention\fP
.RS 4
this method only outputs variables stored on the \fBModel\fP 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class STOREE> template<\fBPLACEMENT\fP place> double \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::Read (const \fBcsmp::INDEX\fP< SCALAR, place > & idx) const\fR [inline]\fP"
double Read( const csmp::INDEX<SCALAR,NODE>& ) const; 
.SS "template<uint32_t dim, template< uint32_t > class STOREE> template<\fBPLACEMENT\fP place> void \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::Read (const \fBcsmp::INDEX\fP< SCALAR, place > & idx, \fBScalarVariable\fP & sc) const\fR [inline]\fP"
void Read ( const \fBcsmp::INDEX<SCALAR,NODE>\fP&, \fBScalarVariable\fP& ) const; 
.SS "template<uint32_t dim, template< uint32_t > class STOREE> double \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::Read (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::Index\fP & idx) const"
Scalar variable value at sector or facet integration points only\&. ^^^^^^^^
.SS "template<uint32_t dim, template< uint32_t > class STOREE> template<\fBPLACEMENT\fP place> double \fBcsmp::LocalVariableStorage\fP< dim, STOREE >::Read (uint32_t sector_or_facet, uint32_t ip, const \fBcsmp::INDEX\fP< SCALAR, place > & idx) const\fR [inline]\fP"
Scalar variable value at sector or facet integration points only\&. ^^^^^^^^

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
