.TH "csmp::StressRegime" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::StressRegime
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStressRegime\fP (double Sv, double SH, double Sh, double trend)"
.br
.ti -1c
.RI "double \fBVerticalStressMagnitude\fP () const"
.br
.ti -1c
.RI "double \fBMaximumHorizontalStressMagnitude\fP () const"
.br
.ti -1c
.RI "double \fBMinimumHorizontalStressMagnitude\fP () const"
.br
.ti -1c
.RI "double \fBMaximumHorizontalStressTrend\fP () const"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 3U > \fBVerticalStressUnitVector\fP () const"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 3U > \fBMinimumHorizontalStressUnitVector\fP () const"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 3U > \fBMaximumHorizontalStressUnitVector\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
