.TH "csmp::PostProcessor< dim, USER >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::PostProcessor< dim, USER >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PostProcessor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPostProcess\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class USER>
.br
class csmp::PostProcessor< dim, USER >"Policy of the Implicit Transport for the post-processing of the computation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
