.TH "csmp::BrooksCoreySaturationFunctions< dim, USER >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::BrooksCoreySaturationFunctions< dim, USER >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBrooksCoreySaturationFunctions\fP ()"
.br
.ti -1c
.RI "double \fBEffectiveSaturation_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.RI "get seff from the supplied saturation value "
.ti -1c
.RI "double \fBpc_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdpcds_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBkrw_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBkrn_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdkrwds_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdkrnds_at\fP (\fBElement\fP< dim > *const, double sw) const"
.br
.ti -1c
.RI "double \fBdpcds_at_Numerical\fP (\fBElement\fP< dim > *const, double sw, double \fBh\fP=0\&.00001) const"
.br
.ti -1c
.RI "double \fBdkrwds_at_Numerical\fP (\fBElement\fP< dim > *const, double sw, double delta_s=0\&.001) const"
.br
.ti -1c
.RI "double \fBdkrnds_at_Numerical\fP (\fBElement\fP< dim > *const, double sw, double delta_s=0\&.001) const"
.br
.ti -1c
.RI "double \fBEffectiveSaturation\fP (\fBElement\fP< dim > *const) const"
.br
.RI "get seff at the element barycentre "
.ti -1c
.RI "double \fBpc\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBdpcds\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBkrw\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBkrn\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBdkrwds\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBdkrnds\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBMaxCapillaryPressure\fP () const"
.br
.RI "maximum value of pc (Pa) "
.ti -1c
.RI "double \fBdkrwds_Numerical\fP (\fBElement\fP< dim > *const, double delta_s=0\&.001) const"
.br
.RI "Numerical derivatives of first derivatives of relative permeability of water and CO2\&. "
.ti -1c
.RI "double \fBdkrnds_Numerical\fP (\fBElement\fP< dim > *const, double delta_s=0\&.001) const"
.br
.ti -1c
.RI "double \fBdpcds_Numerical\fP (\fBElement\fP< dim > *const, double \fBh\fP=0\&.00001) const"
.br
.ti -1c
.RI "double \fBseff_to_sw\fP (\fBElement\fP< dim > *const e, double \fBseff\fP) const"
.br
.RI "return wetting-phase saturation based on effective saturation "
.ti -1c
.RI "double \fBsw_from_pc_at\fP (\fBElement\fP< dim > *const e, double pc, double sw) const"
.br
.RI "inverse capillary pressure function "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class USER> \fBcsmp::BrooksCoreySaturationFunctions\fP< dim, USER >::BrooksCoreySaturationFunctions ()"
The default constructor of Brooks \fBCorey\fP Saturation Functions class 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctions\fP< dim, USER >::dkrnds (\fBElement\fP< dim > * const e) const"
calculating the 1st derivative of oil relative permeability 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctions\fP< dim, USER >::dkrnds_at (\fBElement\fP< dim > * const e, double sw) const"
calculating the 1st derivative of oil relative permeability for any water saturations 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctions\fP< dim, USER >::dkrwds (\fBElement\fP< dim > * const e) const"
calculating the 1st derivative of water relative permeability 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::BrooksCoreySaturationFunctions\fP< dim, USER >::dkrwds_at (\fBElement\fP< dim > * const e, double sw) const"
calculating the 1st derivative of water relative permeability for any water saturation 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
