.TH "csmp::VTK_Interface< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::VTK_Interface< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VTK_Interface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVTK_Interface\fP (const std::string &problemTitle='CSMP_Simulation', bool use_problem_title_as_output_folder_name=false)"
.br
.ti -1c
.RI "\fBVTK_Interface\fP (const std::string &problemTitle, const std::string &subFolderTitle, bool use_problem_title_as_output_folder_name=false)"
.br
.ti -1c
.RI "template<class T> void \fBOutputNodeDataToVTK\fP (const \fBModel\fP< dim > &, const std::string &file_name, T timestep)"
.br
.RI "for all node property data associated with \fBModel\fP object "
.ti -1c
.RI "template<class T> void \fBOutputNodeDataToVTK\fP (const \fBModel\fP< dim > &, const std::string &domain_name, const std::string &file_name, T timestep)"
.br
.RI "for all node property data associated with a specific region "
.ti -1c
.RI "template<class T> void \fBOutputDataToVTK\fP (const \fBModel\fP< dim > &, const std::string &file_name, const std::string &var_name, T timestep, bool update_topology=true)"
.br
.RI "for entire models represented by \fBModel\fP objects "
.ti -1c
.RI "template<class T> void \fBOutputDataToVTK\fP (const \fBModel\fP< dim > &, const std::string &domain_name, const std::string &file_name, const std::string &var_name, T timestep, bool update_topology=true)"
.br
.RI "for a specific subregion of a model "
.ti -1c
.RI "template<class T> void \fBOutputRegionByRegionToVTK\fP (const \fBModel\fP< dim > &, const std::string &file_name, const std::string &var_name, T timestep, bool update_topology=true)"
.br
.RI "all subregion of model, with file_name preface and var-name attached "
.ti -1c
.RI "bool \fBNodeOutputOfElementData\fP () const"
.br
.ti -1c
.RI "void \fBNodeOutputOfElementData\fP (bool yes_or_no)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::VTK_Interface< dim >"Outputs csmp data to VTK Ascii text format

.PP
Known problems:

.PP
\fBTodo\fP
.RS 4
(3) Outputs an inconsistent number of elements and number of points for a quadratic element in case of vector output (A) 

.PP
(3) Fails to output constraint point properties correctly (A) 

.PP
(3) Display quadratic FEM with the corresponding VTK primitives (A) 

.PP
(3) Display 2D regions using VTK polygons (A) 

.PP
(3) Save data as VTK binaries (A) 

.PP
(3) Create and store connectivity only once and then just add new data blocks to files (A) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> template<class T> void \fBcsmp::VTK_Interface\fP< dim >::OutputDataToVTK (const \fBModel\fP< dim > & sg, const std::string & group_name, const std::string & initial_file_name, const std::string & var_name, T timestep, bool update_topology = \fRtrue\fP)"

.PP
for a specific subregion of a model To output subregions of a model represented by \fBRegion\fP objects to a VTK file in text format\&. 
.br
.SH "Input Arguments"
.PP
The first method argument is a reference to the \fBModel\fP object representing the model from which data shall be output to VTK\&. The following string arguments give the names of (1) the region object inside the \fBModel\fP to which the interface is applied, (2) the name of outputfile, and (3) the name of the output variable\&. The fifth method argument further supplies the current timestep of the computation and the sixth argument tells the \fBVTK_Interface\fP whether the topology has to be updated or whether it can be re-used\&. The default value leads to updates\&. 
.br
.SH "Implementation"
.PP
.IP "1." 4
Makes a first map that contains a uniquely numbered list of the node coordinates abd the old node IDs
.IP "2." 4
Create a second map that contains new node IDs that correspond to the alreadzy existing node coordinates
.IP "3." 4
Build a third map for the Plist that contains the new node IDs of the new subtriangles
.PP

.PP
(4 subtriangles for the quadratic triangle , 6 subtriangles for the barycentric quadratic triangle) in a counter clockwise order
.SH "Application Examples"
.PP
To visualize CSMP models using the Visualization Toolkit\&. 
.SS "template<uint32_t dim> template<class T> void \fBcsmp::VTK_Interface\fP< dim >::OutputDataToVTK (const \fBModel\fP< dim > & sg, const std::string & file_name, const std::string & var_name, T timestep, bool update_topology = \fRtrue\fP)"

.PP
for entire models represented by \fBModel\fP objects OutputDataToVTK writes the values of the specified distributed \fBModel\fP variable to a VTK textfile of unstructured data\&. 
.br

.PP
Note that in order to display element variables in VTK, flat shading must be set\&. Otherwise the variable values are again smeared out across neighboring nodes\&. 
.br
.SH "Input Arguments"
.PP
The first method argument is a reference to the \fBModel\fP object from which the data shall be retrieved\&. The second and third string arguments specify the name of the output file and the physical variable which shall be output\&. The fourth argument specifies the simulation timestep which the dataset represents\&. This timestep is appended to the output file name\&. The fifth method argument specifies whether \fBOutputDataToVTK()\fP should update the internally stored mesh topology or whether it can use again one which it created at an earlier output step\&. The default value here tells the method to update the topology\&. 
.br
.SH "Implementation"
.PP
From a 'plist', a unique list of nodes is created which are renumbered from 0\&.\&.\&.n-1\&. 
.br

.PP
The original 'plist' is reassembled by braking more complex elements down into topological primitives which can be displayed in VTK\&. The new plist then also contains the new node IDs which the \fBVTK_Interface\fP uses internally\&. 
.SS "template<uint32_t dim> template<class T> void \fBcsmp::VTK_Interface\fP< dim >::OutputNodeDataToVTK (const \fBModel\fP< dim > & sg, const std::string & region, const std::string & initial_file_name, T timestep)"

.PP
for all node property data associated with a specific region output of variables placed on the nodes to VTK 
.SS "template<uint32_t dim> template<class T> template void \fBcsmp::VTK_Interface\fP< dim >::OutputRegionByRegionToVTK (const \fBModel\fP< dim > & , const std::string & file_name, const std::string & var_name, T timestep, bool update_topology = \fRtrue\fP)"

.PP
all subregion of model, with file_name preface and var-name attached Outputs all subregion of model, with file_name preface and var-name attached 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
