.TH "csmp::InterFaceParentElements< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::InterFaceParentElements< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SplitBoundary\&.h>\fP
.PP
Inherits std::vector< std::pair< std::pair< Element< dim > *, uint32_t >, std::pair< Element< dim > *, uint32_t > > >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBInterFaceParentElements\fP< dim >::const_iterator \fBifaceIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterFaceParentElements\fP (const std::vector< std::pair< std::pair< \fBElement\fP< dim > *, uint32_t >, std::pair< \fBElement\fP< dim > *, uint32_t > > > &data)"
.br
.ti -1c
.RI "\fBElement\fP< dim > * \fBInnerElement\fP (ifaceIterator it) const"
.br
.ti -1c
.RI "\fBElement\fP< dim > * \fBOuterElement\fP (ifaceIterator it) const"
.br
.ti -1c
.RI "uint32_t \fBInnerFaceID\fP (ifaceIterator it) const"
.br
.ti -1c
.RI "uint32_t \fBOuterFaceID\fP (ifaceIterator it) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
struct csmp::InterFaceParentElements< dim >"Vector of \fBInterFace\fP (higher-dim) \fBElement\fP - face idx pairs and \fBElement\fP co-located with \fBInterFace\fP (if present)\&. For each \fBInterFace\fP we have a pair or \fBElement\fP pointer - face ID pairs 1) inner higher-dim element pointer 2) local face number of element face that is located at interface to outer element 3) outer higher-dim element pointer 4) local face number of element face that is located at interface to innner element 5) pointer to potential lower-dimensional intervening \fBElement\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
