.TH "csmp::ColumnCell" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ColumnCell \- A column cell, in Eclipse convention ordering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Pillar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBk\fP"
.br
.ti -1c
.RI "bool \fBskew\fP = false"
.br
.ti -1c
.RI "ECLIPSE_CELL_CLASSIFICATION \fBclassification\fP"
.br
.ti -1c
.RI "size_t \fBz\fP [4][2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A column cell, in Eclipse convention ordering\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
