.TH "csmp::PDE_Integrator_CRM< dim, CELLTYPE >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::PDE_Integrator_CRM< dim, CELLTYPE > \- \fBAccumulator\fP and integrator for FEM or FVM-derived integral forms of PDEs and their solution in the form of linear algebraic sets of equations (system Ax=b)\&. Applicable to CSMP++ \fBModel\fP objects or their subregions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PDE_Integrator_CRM\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSIZES\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::map< \fBParameter\fP, size_t >::const_iterator \fBoperandsConstIterator\fP"
.br
.RI "constant iterator over solution variables "
.ti -1c
.RI "typedef std::map< \fBParameter\fP, size_t >::iterator \fBoperandsIterator\fP"
.br
.RI "iterator over solution variables "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPDE_Integrator_CRM\fP ()"
.br
.ti -1c
.RI "\fBPDE_Integrator_CRM\fP (\fBSolver\fP &)"
.br
.RI "create an integrator with a solver managed elsewhere "
.ti -1c
.RI "\fBPDE_Integrator_CRM\fP (const \fBPDE_Integrator_CRM\fP &)=delete"
.br
.RI "do not copy because of all the pointer ramificatons "
.ti -1c
.RI "\fBPDE_Integrator_CRM\fP & \fBoperator=\fP (const \fBPDE_Integrator_CRM\fP &)=delete"
.br
.RI "do not assign "
.ti -1c
.RI "void \fBAdd\fP (\fBMathOperatorLHS\fP< dim, CELLTYPE > *)"
.br
.RI "add desired integral terms (pde operators) to the left-hand side matrix of the algebraic system of equations "
.ti -1c
.RI "void \fBAdd\fP (\fBMathOperatorRHS\fP< dim, CELLTYPE > *)"
.br
.RI "add desired integral terms (pde operators) to the right-hand side vector of the algebraic system of equations "
.ti -1c
.RI "void \fBAddPostProcess\fP (\fBMathOperatorLHS\fP< dim, CELLTYPE > *)"
.br
.RI "adds math operators that will be applied in a second loop after the matrix has been inverted "
.ti -1c
.RI "void \fBAddBoundaryIntegral\fP (\fBMathOperatorRHS\fP< dim, \fBFace\fP > *)"
.br
.RI "adds integral terms on the boundary of the computational domain if any "
.ti -1c
.RI "void \fBAddSplitBoundaryIntegral\fP (\fBMathOperatorRHS\fP< dim, \fBInterFace\fP > *)"
.br
.RI "for the computation of fluxes across internal split boundaries "
.ti -1c
.RI "void \fBAddSplitBoundaryIntegral\fP (\fBMathOperatorLHS\fP< dim, \fBInterFace\fP > *)"
.br
.ti -1c
.RI "void \fBTimeIncrement\fP (double dt)"
.br
.RI "sets the time-increment for- and triggers a transient calculation (use 1/t if problem has been set up that way) "
.ti -1c
.RI "bool \fBTransient\fP () const"
.br
.RI "returns whether a finite-difference time increment has been set "
.ti -1c
.RI "void \fBIntegrateOver\fP (\fBModelSubDomain\fP< dim, CELLTYPE > &, bool debug=false)"
.br
.RI "accumulates, assembles, and solves PDEs in domain of interest; "
.ti -1c
.RI "void \fBIntegrateOver\fP (\fBModel\fP< dim > &, \fBModelSubDomain\fP< dim, CELLTYPE > &, bool debug=false)"
.br
.RI "also considers "dS" pde operators from \fBBoundary\fP or \fBSplitBoundary\fP objects if these share nodes with domain on which the solution is obtained "
.ti -1c
.RI "void \fBSetSolver\fP (\fBSolver\fP &)"
.br
.RI "switch to another solver deleting any dynamically allocated solver that was associated with integrator "
.ti -1c
.RI "\fBSolver\fP & \fBGetSolver\fP () const"
.br
.RI "returns a reference to the current solver object "
.ti -1c
.RI "virtual void \fBReset\fP (bool delete_math_operators=true)"
.br
.RI "returns PDE integrator into the state created by default constructor ( "
.ti -1c
.RI "void \fBSolutionVector\fP (std::vector< double > &) const"
.br
.RI "outputs solution vector; "
.ti -1c
.RI "void \fBFirstGuess\fP (const std::vector< double > &)"
.br
.RI "optional input of a solution vector with an initial guess of the result; for SAMG set ifirst=0 so that this vector is used "
.ti -1c
.RI "void \fBRetainGlobalSolutionMatrix\fP (bool yes_or_no)"
.br
.RI "if an evolutionary problem where only the right-hand side changes, the matrix needs to be assembled only once "
.ti -1c
.RI "void \fBTrimExcessCapacityOfVectors\fP (bool trim)"
.br
.RI "'swap trick' keeps size and capacity of solution and righthand vectors equal "
.ti -1c
.RI "void \fBWriteGlobalMatrixBitMapToText\fP (const char *file_name)"
.br
.RI "writes out the sparsity pattern of the solution matrix "
.ti -1c
.RI "void \fBListMathOperatorsLHS\fP () const"
.br
.ti -1c
.RI "void \fBListMathOperatorsRHS\fP () const"
.br
.ti -1c
.RI "void \fBOutputGlobals\fP (int precision=1)"
.br
.RI "outputs the system A x = b to the screen "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "prints current parameters settings and pde operators to screen "
.ti -1c
.RI "void \fBVerbose\fP (bool)"
.br
.RI "extra detailed screen output about the assembly solution progress "
.ti -1c
.RI "bool \fBVerbose\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::list< std::string > \fBIdentifySharedBoundaries\fP (const \fBModel\fP< dim > &, const \fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "checks whether any \fBBoundary\fP object in the model is a surface of the computational domain "
.ti -1c
.RI "std::list< std::string > \fBIdentifySharedSplitBoundaries\fP (const \fBModel\fP< dim > &, const \fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "checks whether any \fBSplitBoundary\fP object in the model has higher-dim elements on either side the computational domain "
.ti -1c
.RI "virtual void \fBEstablishMatrixSetup\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "resizes sparse solution matrix and establishes variable offsets if a system of equations will be solved "
.ti -1c
.RI "void \fBReduceSystemSizeEliminatingEssentialConditions\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &, size_t total_degrees_of_freedom)"
.br
.RI "for the elimination of Dirichlet constraints from the solution matrix; called after EstablishMatrixSetup but before accumulation "
.ti -1c
.RI "virtual void \fBAssignInitialConditions\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "in time-dependent calculations this method assigns initial conditions to the RHS; uses node numbering "
.ti -1c
.RI "virtual void \fBAssignEssentialConditions\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "modifies right-hand vector; adding Dirichlet condition terms that were elimitated before "
.ti -1c
.RI "virtual void \fBAccumulate\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "accumulates finite element integrals into solution matrix and right-hand side; uses node numbering "
.ti -1c
.RI "virtual void \fBAccumulateBoundaries\fP (\fBModel\fP< dim > &, \fBModelSubDomain\fP< dim, CELLTYPE > &, std::list< std::string > shared_boundaries)"
.br
.RI "accumulates finite element integrals for Faces into right-hand side for boundaries provided; uses node numbering "
.ti -1c
.RI "virtual void \fBAccumulateSplitBoundaries\fP (\fBModel\fP< dim > &, \fBModelSubDomain\fP< dim, CELLTYPE > &, std::list< std::string > shared_splitboundaries)"
.br
.RI "accumulates finite element integrals into solution matrix and right-hand side for all splitboundaries provided; uses node numbering "
.ti -1c
.RI "virtual void \fBAccumulateBoundaryIntegrals\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &, const \fBBoundary\fP< dim > &)"
.br
.RI "accumulates surface integrals from Neumann-flagged \fBFace\fP object variables representing those parts of all boundaries that delimit the computational domain "
.ti -1c
.RI "virtual void \fBAccumulateSplitBoundaryIntegrals\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &, const \fBSplitBoundary\fP< dim > &)"
.br
.RI "accumulation of Robin-type boundary conditions to \fBSplitBoundary\fP interfaces "
.ti -1c
.RI "virtual void \fBLateAccumulate\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "accumulates finite-element integrals to matrix and vector after the corresponding entries were already multiplied with the initial conditions; uses node numbering "
.ti -1c
.RI "virtual void \fBLateAccumulateBoundaryIntegrals\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &, const \fBBoundary\fP< dim > &)"
.br
.RI "late accumulates surface integrals from Neumann-flagged \fBFace\fP object variables representing those parts of all boundaries that delimit the computational domain "
.ti -1c
.RI "virtual void \fBLateAccumulateSplitBoundaryIntegrals\fP (const \fBModelSubDomain\fP< dim, CELLTYPE > &, const \fBSplitBoundary\fP< dim > &)"
.br
.ti -1c
.RI "void \fBCoupleDomainsAcrossSplitBoundary\fP (\fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "couples domains separated by SplitBoundaries using the information from NodeManifolds "
.ti -1c
.RI "virtual void \fBSolve\fP ()"
.br
.RI "calls connected solver object to find x in G x = rh problem "
.ti -1c
.RI "virtual void \fBPostProcess\fP (\fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "allows to apply pde operators to post-process the newly computed solution "
.ti -1c
.RI "virtual void \fBOutputResults\fP (\fBModelSubDomain\fP< dim, CELLTYPE > &)"
.br
.RI "transfers the results stored in solution vector onto the nodes of the computational domain; uses node numbering "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, \fBMathOperatorLHS\fP< dim, CELLTYPE > * > \fBlhs_operators_\fP"
.br
.RI "stencils for lefthand solution matrix "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorRHS\fP< dim, CELLTYPE > * > \fBrhs_operators_\fP"
.br
.RI "stencils for righthand vector "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorLHS\fP< dim, CELLTYPE > * > \fBpostpro_operators_\fP"
.br
.RI "post-processing: Darcy velocities, stresses from strains etc\&. "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorRHS\fP< dim, \fBFace\fP > * > \fBrhs_boundary_operators_\fP"
.br
.RI "surface integrals for accumulation over boundary "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorLHS\fP< dim, \fBInterFace\fP > * > \fBlhs_split_boundary_operators_\fP"
.br
.RI "implicit integral coupling terms for \fBSplitBoundary\fP "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorRHS\fP< dim, \fBInterFace\fP > * > \fBrhs_split_boundary_operators_\fP"
.br
.RI "explicit integral coupling terms for \fBSplitBoundary\fP "
.ti -1c
.RI "std::map< \fBParameter\fP, size_t > \fBbasic_operands_\fP"
.br
.ti -1c
.RI "std::map< \fBParameter\fP, size_t > \fBtest_operands_\fP"
.br
.RI "dependent variables in the solved system of equations "
.ti -1c
.RI "\fBCompressedRowMatrix\fP \fBG_\fP"
.br
.RI "solution matrix "
.ti -1c
.RI "std::vector< double > \fBrh_\fP"
.br
.RI "righthand vector "
.ti -1c
.RI "std::vector< double > \fBx_\fP"
.br
.RI "solution vector "
.ti -1c
.RI "std::vector< size_t > \fBDOF_indexes_\fP"
.br
.RI "indices of DOFs, but only of the non-Dirichlet dofs, size enumerated 0 - DOF-1 (including Dirich DOF) "
.ti -1c
.RI "std::vector< double > \fBpivotVector_\fP"
.br
.RI "mapping from DOFs to actual node numbers "
.ti -1c
.RI "\fBSolver\fP * \fBsolver_\fP = nullptr"
.br
.ti -1c
.RI "size_t \fBdof_per_node_\fP"
.br
.ti -1c
.RI "bool \fBsetup_established_\fP"
.br
.ti -1c
.RI "bool \fBretain_matrix_\fP"
.br
.ti -1c
.RI "bool \fBtrim_vectors_\fP"
.br
.RI "false, false, false to start with "
.ti -1c
.RI "bool \fBnewed_Solver_object_\fP"
.br
.ti -1c
.RI "double \fBtime_increment_\fP"
.br
.ti -1c
.RI "struct \fBcsmp::PDE_Integrator_CRM::SIZES\fP \fBtarget_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE = Element>
.br
class csmp::PDE_Integrator_CRM< dim, CELLTYPE >"\fBAccumulator\fP and integrator for FEM or FVM-derived integral forms of PDEs and their solution in the form of linear algebraic sets of equations (system Ax=b)\&. Applicable to CSMP++ \fBModel\fP objects or their subregions\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
Stephen G\&. Roberts 

.PP
various extra constributions (Adrian Burri, Julian Mindel, Kho Luat Tran)\&. 
.RE
.PP
\fBDate\fP
.RS 4
1997 

.PP
replaced by merge of \fBPDE_Integrator\fP 1/4/22
.RE
.PP
.SH "Motivation"
.PP
To encapsulate the integration and numerical solution of partial-differential equations (PDE) in their integral form\&. This process entails (1) the assembly of a sparse matrix with the contributions from finite elements or finite volumes, (2) the assembly of a right-hand vector with essential and initial conditions; elimination of Dirichlet constraints\&. (3) Inversion of the matrix equation Ax=b to find the solution vector x\&. The dependent physical \fBvariable(s)\fP stored in the solution vector are updated on the mesh\&.
.SH "Design Intent"
.PP
The intent of using a 'strategy' pattern for the design was to separate the PDE operator / integrator implementation from the the type of finite element(s) or FV's used and the solution method chosen\&. As a consequence, the same PDE operator objects and solution methods can be used for a range of computational cell types with different node numbers and so forth\&.

.PP
The \fBPDE_Integrator\fP class is a base class from which specific \fBPDE_Integrator\fP subclasses can be inherited to test improvements of its functionality\&.
.SH "Applicability"
.PP
\fBPDE_Integrator\fP objects can be used to carry out any 2D and 3D computation which are possible with CSMP++\&. These computations may either appy to entire \fBModel\fP objects or to Regions which form subsets thereof\&.
.SH "Participants"
.PP
Each \fBPDE_Integrator\fP contains maps of pointers to left and righthand operators that are inherited from the \fBMathOperatorLHS\fP and \fBMathOperatorRHS\fP base classes\&. Other variables set the state of the algorithm, the time_increment in transient calculations and so forth\&.

.PP
\fBPDE_Integrator\fP also contains or connects to a \fBSolver\fP object which inverts the sparse solution matrix\&.
.SH "Collaborations"
.PP
\fBPDE_Integrator\fP interact with \fBModel\fP, \fBRegion\fP, \fBBoundary\fP and \fBSplitBoundary\fP objects\&. It queries these objects for the data needed to setup the solution matrices and vectors\&.

.PP
\fBPDE_Integrator\fP also collaborates with the \fBMeshManager\fP and the \fBPropertyDatabase\fP to gain access to variables and finite elements (\fBElement\fP class instances)\&.

.PP
\fBPDE_Integrator\fP obtains the finite-element contributions from the \fBElement\fP class that in turn accesses the specific finite-element type which appears hidden behind the specific element that is assembled\&. This is implemented as a 'bridge' pattern\&.
.SH "Consequences"
.PP
The design as a full-function base class implies that to create a PDE operator subclass one only has to overwrite those methods that one wants to modify\&. Other code does not need to be modified\&. To create additional PDE operators, inherit these from \fBMathOperatorLHS\fP or \fBMathOperatorRHS\fP\&.
.SH "Implementation"
.PP
The \fBPDE_Integrator\fP is a stand-alone object, which is passed to the \fBModel\fP\&. The interaction with the \fBModel\fP follows a visitor like pattern\&. The \fBModel\fP passes the \fBPDE_Integrator\fP on to a region to which its application has been restricted\&. Inside the \fBModel\fP, the following steps take place when a \fBPDE_Integrator\fP is applied by calling \fBModel::Apply()\fP:

.PP
To start with, the \fBModel\fP checks whether the \fBPDE_Integrator\fP must be handed down to a specific region, boundary or split boundary\&. Then the \fBPDE_Integrator\fP builds or updates its vectors and matrices so that they can store a sufficient number of entries:

.PP
.PP
.nf
PDE_Integrator::EstablishMatrixSetup( mesh, phys_vars );
.fi
.PP

.PP
Now the \fBPDE_Integrator\fP accumulates the contributions to the global solution matrices seqentially:

.PP
.PP
.nf
PDE_Integrator::Accumulate ( mesh, property_collection );
.fi
.PP

.PP
If the computation is a transient one, initial conditions are added into the righthand vector:

.PP
.PP
.nf
PDE_Integrator::AssignInitialConditions( mesh, property_collection );
.fi
.PP

.PP
Then, the boundary conditions are applied to the lefthand and righthand side:

.PP
.PP
.nf
PDE_Integrator::AssignEssentialConditions( mesh, property_collection );
Here an elimination is performed, retaining, if so, the symmetric shape of the solution matrix\&.
.fi
.PP

.PP
If the computation is a transient one, and the solution method is Backward Euler implicit timestepping, righthand-side source terms (typically fluid source or other rates) are now multiplied with the time increment and added to the righthand vector\&.

.PP
.PP
.nf
PDE_Integrator::LateAccumulate( mesh, property_collection );
.fi
.PP

.PP
Now the solver is invoked to invert the solution matrix:

.PP
.PP
.nf
PDE_Integrator::Solve();
.fi
.PP

.PP
The results from the computation are mapped back into property storage:

.PP
.PP
.nf
PDE_Integrator::OutputResults( mesh, property_collection );
.fi
.PP

.PP
and post-processing operations are applied:

.PP
.PP
.nf
PDE_Integrator::PostProcess( mesh, property_collection );
.fi
.PP

.PP
Post-processing may be for instance, the computation of flow velocities from computed fluid-pressure gradients and permeability values\&.

.PP
Important is also the mapping from global node ID numbers to entry positions in the global solution matrix: In the simplemost case, of a single degree-of-freedom per node and a global computation, the mapping is:

.PP
G(n,n), rh(n) -> n = node-ID-1

.PP
For vector variables:

.PP
G(n,n), rh(n) -> n = (node-ID-1) * dimensions + j

.PP
where j is the index variable for the spatial dimensions x, y, z\&.

.PP
For tensor variables:

.PP
G(n,n), rh(n) -> n = (node-ID-1) * dimensions^2 i*dimensions + j

.PP
where i, j are the index variables corresponding to the rows and column indices of the tensor variable with the i_max = j_max = spatial dimensions\&.

.PP
In the case of \fBRegion\fP computations, an instance of the class IndexMapper transforms the global node ID numbers into the scaled ID numbers 1\&.\&.\&.n-nodes in group\&. Subsequently, the same transformations are applied for vector and tensor variables\&.
.SH "Application Examples"
.PP
The simple most computation with an \fBPDE_Integrator\fP is a 3D steady-state computation of fluid pressure\&. This involves the definition and instantiation of some PDE operators as first step:

.PP
.PP
.nf
// compute steady\-state fluid pressure from [K]{p} = {q}
PDE_Integrator<2U>  fluid_pressure;

NumIntegral_dNT_op_dN_dV<2U>  conductance( example_model\&.Database(), "conductivity",   "fluid pressure", "fluid pressure" );
NumIntegral_NT_op_N_dV<2U>    source( example_model\&.Database(), "fluid volume source", "fluid pressure" );
VelocityAndVolumeFlux<2U>     velo( example_model, "conductivity", "porosity", "fluid pressure", true );

fluid_pressure\&.Add( &conductance );
fluid_pressure\&.Add( &source );
fluid_pressure\&.AddPostProcess( &velo );
example_model\&.Apply( fluid_pressure );
.fi
.PP

.PP
A more advanced calculation of displacements, strains and stresses is done in the following example:

.PP
.PP
.nf
PDE_Integrator<2U>  deformation;
if ( restricted_to_rock ) deformation\&.RestrictApplicationTo("rock");

PT_op<2U>                    bforces( p_ref, "force", "displacement" );
NumIntegral_BT_D_B_dV<2U>    stiffness( p_ref, "Young's modulus", "Poisson's ratio", "displacement", "displacement");
if ( with_plane_stress ) stiffness\&.PlaneStress();
NumIntegral_PT_op_dS<2U>     bstresses( p_ref, "Neumann stress", "displacement" );
NumIntegral_PT_op_dV<2U>     bodyforce( p_ref, "gravity force", "displacement");
NumIntegral_BT_D_op_dV<2U>   volstrain( p_ref, "dilatation", "Young's modulus", "Poisson's ratio", "displacement");
NumIntegral_BT_op_dV<2U>     porepressure( p_ref, "fluid pressure", "displacement");

deformation\&.Add( &stiffness );
deformation\&.Add( &bforces );  // must always be there so that Dirichlet conditions are accumulated
if ( with_boundary_stresses ) deformation\&.Add( &bstresses );
if ( with_body_forces )       deformation\&.Add( &bodyforce );
if ( with_volume_strains )    deformation\&.Add( &volstrain );
if ( with_pore_pressure )     deformation\&.Add( &porepressure );

StressesAndStrains<2U>  postpro( example_model, "Young's modulus",
                                                         "Poisson's ratio", "displacement", true, true );

if ( with_plane_stress ) postpro\&.PlaneStress();
 deformation\&.AddPostProcess( &postpro );

example_model\&.Apply( deformation );
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::PDE_Integrator_CRM ()"
Default Constructor

.PP
The default constructor sets the computational domain equivalent to the \fBModel\fP\&. The default \fBSolver\fP is SAMG, without license, you only have access to a single level solver\&. The default computation is a steady-state computation\&. Thus, if you want to carry out a transient calculation you have to use the method \fBTransient()\fP\&.

.PP
\fBAttention\fP
.RS 4
CELLTYPE is used here because DOMAIN caused a clash with DOMAIN defined in <cmath> 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::Accumulate (const \fBModelSubDomain\fP< dim, CELLTYPE > & gref)\fR [protected]\fP, \fR [virtual]\fP"

.PP
accumulates finite element integrals into solution matrix and right-hand side; uses node numbering \fBAccumulate()\fP loops over the finite-elements in the \fBModel\fP or target \fBRegion\fP and accumulates their contributions to the solution matrix and the righthand vector\&. If the computation is part of a finite-difference time-stepping scheme this is accounted for by multiplying time-dependent contributions like source or sink rates with the time-icrement\&. The method retrieves information from the mesh and the property managers\&. If a group computation is carried out, the target group is accessed by a pointer\&.
.SH "Implementation"
.PP
The generation and addition of the element contributions to the solution matrix and righthand vector requires the execution of the math operator methods:

.PP
.PP
.nf
GetOperands();
ComputeContribution();
AssignToGlobal();
.fi
.PP

.PP
If a transient calculation is chosen the "grad-test function" terms and the Neumann boundary condition terms are multiplied with the time-increment\&.
.SH "Application Examples"
.PP
\fBAccumulate()\fP is executed internally when the \fBPDE_Integrator\fP is passed to the \fBModel\fP\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::AccumulateBoundaryIntegrals (const \fBModelSubDomain\fP< dim, CELLTYPE > & comp_domain, const \fBBoundary\fP< dim > & boundary)\fR [protected]\fP, \fR [virtual]\fP"

.PP
accumulates surface integrals from Neumann-flagged \fBFace\fP object variables representing those parts of all boundaries that delimit the computational domain For RHS vector accumulation of Neumann-flagged element integrals evaluated on \fBFace\fP objects\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::AccumulateSplitBoundaryIntegrals (const \fBModelSubDomain\fP< dim, CELLTYPE > & comp_domain, const \fBSplitBoundary\fP< dim > & splitboundary)\fR [protected]\fP, \fR [virtual]\fP"

.PP
accumulation of Robin-type boundary conditions to \fBSplitBoundary\fP interfaces Coupling conditions / surface integrals applied to \fBSplitBoundary\fP objects

.PP
TODO: include boundary conditions applied to LHS TODO: adopt method to handle \fBInterFace\fP objects (in split boundaries) as well 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::Add (\fBMathOperatorLHS\fP< dim, CELLTYPE > * op)"

.PP
add desired integral terms (pde operators) to the left-hand side matrix of the algebraic system of equations The \fBPDE_Integrator\fP object maintains a list of pointers to MathOperator instances which represent parts of the PDE which is being modeled by the \fBPDE_Integrator\fP\&. \fBAdd()\fP allows you to associate such operators_ (like dove^2) with the \fBPDE_Integrator\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIop\fP pointer to PDE operator objects (=Operands) which you defined earlier in your program\&. These are always subclasses derived from the MathOperatorLHSptr or MathOperatorRHSptr base classes\&.
.RE
.PP
.SH "Implementation"
.PP
The MathOperator pointers are stored in the lhs_operators_ and rhs_operators_ maps\&. Their functionality is accessed in the accumulation process of the solution matrix G and the righthand vector rh\&. The maps prevent, that multiple instances of the same MathOperator object with the same name are added\&.
.SH "Application Examples"
.PP
Each \fBPDE_Integrator\fP needs at least one left and one righthand math operator\&. Define these before you pass the \fBPDE_Integrator\fP to the \fBModel\fP\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::AssignEssentialConditions (const \fBModelSubDomain\fP< dim, CELLTYPE > & domain)\fR [protected]\fP, \fR [virtual]\fP"

.PP
modifies right-hand vector; adding Dirichlet condition terms that were elimitated before The Dirichlet constraints have already been eliminated, but their contributions to the non-Dirichlet rows have to be added to the RHS\&.

.PP
The guts of the elimation now live in EnumerateAndFixMatrixSize()\&.

.PP
\fBAuthor\fP
.RS 4
Luat Khoa Tran 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::AssignInitialConditions (const \fBModelSubDomain\fP< dim, CELLTYPE > & gref)\fR [protected]\fP, \fR [virtual]\fP"

.PP
in time-dependent calculations this method assigns initial conditions to the RHS; uses node numbering \fBAssignInitialConditions()\fP writes the present value of the dependent \fBvariable(s)\fP of the computation into the righthand vector\&. It is applied only in transient calculations\&. \fBAssignInitialConditions()\fP makes use of the mesh and property storage managers\&.
.SH "Implementation"
.PP
\fBAssignInitialConditions()\fP searches the dependent variable lists (basic operands) to retrieve those to accumulate them into the righthand vector\&. If there are multiple ones, the 'offset' variable is used to distinguish their placement\&. Dependent on the variable type (scalar, vector, tensor) the accumulation process differs since the degrees of freedom differ\&. Here the model dimension is used to determine the DOFs\&.
.SH "Application Examples"
.PP
\fBAssignInitialConditions()\fP is applied internally, when the \fBPDE_Integrator\fP is passed to the \fBModel\fP object\&. Initial conditions are only assigned if the model is transient\&.
.SH "Messages"
.PP
The following errors and warnings will be reported:

.PP
.PP
.nf
please call EstablishMatrixSetup() prior to this method\&.
.fi
.PP

.PP
If \fBEstablishMatrixSetup()\fP has not been executed so far\&.

.PP
.PP
.nf
No basic operands have been specified\&.\&.\&.
.fi
.PP

.PP
If there are no dependent variables defined !!!

.PP
.PP
.nf
Warning: So far no conditions are assigned to elements, faces, segments
.fi
.PP

.PP
The dependent variable must be placed on the nodes:

.PP
TODO: write alternative method that deals with the case when a boundary is only partially overlapping with the model domain\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::CoupleDomainsAcrossSplitBoundary (\fBModelSubDomain\fP< dim, CELLTYPE > & subdomain)\fR [protected]\fP"

.PP
couples domains separated by SplitBoundaries using the information from NodeManifolds Loops over the nodes of the \fBRegion\fP \fBBoundary\fP\&. If these are manifolds, the coupling is applied\&.

.PP
\fBNote\fP
.RS 4
whether the test function variable should be coupled across the interface is determined from the value of the test-function operand at the SplitBoudary\&. If it is flagged ANY or PLAIN, lke at any no-flow boundary, no coupling is created, if it is ROBIN, the nodes in the manifold are coupled\&.
.RE
.PP
\fBTodo\fP
.RS 4
perhaps introduce new flag called \fBVARIABLE_FLAG\fP : COUPLED to express the state of the variable at the internal \fBSplitBoundary\fP\&.
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::EstablishMatrixSetup (const \fBModelSubDomain\fP< dim, CELLTYPE > & gref)\fR [protected]\fP, \fR [virtual]\fP"

.PP
resizes sparse solution matrix and establishes variable offsets if a system of equations will be solved \fBEstablishMatrixSetup()\fP involves the following steps:

.PP
.IP "1." 4
The basic sizes of the solution matrix, solution vector and righthand vector are determined\&.
.IP "2." 4
Each MathOperator has a basic, and a test variable operand\&. Basic operands are checked for their type and compared among operations to identify what size the final solution matrix G should have\&.
.IP "3." 4
Offset are assigned to individual MathOperators to indicate to what positions in the solution matrix they must accumulate to\&. This applies when multiple dependent variables are being solved for in the solution process\&.
.IP "4." 4
The solution matrix G, the solution vector x and the righthand vector rh are resized according to the operator specifications and the application target (\fBRegion\fP or \fBModel\fP)\&.
.PP

.PP
\fBEstablishMatrixSetup()\fP takes information from the mesh and property managers and may query the property database for the type of variables\&. In the case of a group-restricted computation, the group interface is accessed via a pointer (gptr)\&.
.SH "Application Examples"
.PP
\fBEstablishMatrixSetup()\fP is applied internally when the \fBPDE_Integrator\fP is passed to the \fBModel\fP\&.
.SH "Messages"
.PP
\fBEstablishMatrixSetup()\fP can terminate emitting messages when:

.PP
.PP
.nf
computational domain not specified"
.fi
.PP

.PP
If the target group could not be found\&.

.PP
.PP
.nf
PDE_Integrator cannot add new variable to database
.fi
.PP

.PP
When you mispelled a variable name or if you tried to use a non-existant variable in your computation\&. \&.

.PP
.PP
.nf
righthand basic Operand's offset could not be resolved\&.\&.\&.
.fi
.PP

.PP
Again, when a physical variable is unknown to the \fBPropertyDatabase\fP object such that it cannot resolve its \fBcsmp::Index\fP\&.

.PP
The following Error won't terminate \fBPDE_Integrator\fP application:

.PP
.PP
.nf
There is no test operand for basic operand: x csmp::Index: idx
.fi
.PP

.PP
Here, the finite-element interpolation functions do not model the dependent variable\&.

.PP
Warning messages that can arise during the execution of \fBEstablishMatrixSetup()\fP are the following:

.PP
.PP
.nf
PDE_Integrator was used before, using same specifications again\&.\&.\&.
.fi
.PP

.PP
You forgot to call \fBReset()\fP before re-using an existing \fBPDE_Integrator\fP\&. You will now accumulate into the inverted solution matrix\&.

.PP
.PP
.nf
lefthand basic operand not found
.fi
.PP

.PP
Each \fBPDE_Integrator\fP needs a lefthand basic operand in order to define a PDE problem\&. Define one before applying the \fBPDE_Integrator\fP\&.

.PP
.PP
.nf
There is no test operand for basic operand:
.fi
.PP

.PP
Your element interpolation functions do not model your dependent variable\&.

.PP
.PP
.nf
Basic operand is an Element variable\&. Is this intended ?
.fi
.PP

.PP
Typically, the dependent variable in a finite-element computation, e\&.g\&., the basic operand is placed on the nodes\&. This lies in the very nature of the finite-element method\&. If you are doing a finite-volume or other computation, just ignore this warning\&.

.PP
TODO: consider case where one might want to retain the right-hand vector, but not the matrix TODO: rather than throwing the entire matrix away, one might just remove off-diagonal elements 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::FirstGuess (const std::vector< double > & guess)"

.PP
optional input of a solution vector with an initial guess of the result; for SAMG set ifirst=0 so that this vector is used Registers vector guess as first guess in the solution procedure for the algebraic multigrid solver\&.
.SH "Application Examples"
.PP
Use this method to supply a first guess solution different from the previous solution obtained with this algorithm\&.

.PP
NOTE: Make sure that you actually use an algebraic multigrid solver object and that the parameter ifirst in its \fBSAMG_Settings\fP object is set to 0\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> std::list< std::string > \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::IdentifySharedBoundaries (const \fBModel\fP< dim > & model, const \fBModelSubDomain\fP< dim, CELLTYPE > & subdomain)\fR [protected]\fP"

.PP
checks whether any \fBBoundary\fP object in the model is a surface of the computational domain Identifies the names of any model boundaries (standard and split ones), which are shared with the computational domain 'subdomain' by searching for the corresponding string in the boundaries\&. The identified boundaries are returned in the argument list\&.

.PP
\fBAttention\fP
.RS 4
method assumes that the names of the boundaries are composed of the strings BOUNDARY, the name of the volumetric boundary that is adjacent to them and their name, for instance, BOUNDARY_MATRIX_LANDSURFACE\&. The only other names that are handled are those of the boundaries in a box-shaped model\&.
.RE
.PP
\fBNote\fP
.RS 4
method is costly so that it should not be repeatedly applied, but results should be stored\&.
.RE
.PP
\fBAttention\fP
.RS 4
method also handles case, where the computational domain is the region '\fBModel\fP'\&.

.PP
internal model boundaries or edge boundaries are not handled yet\&.
.RE
.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::IntegrateOver (\fBModel\fP< dim > & model, \fBModelSubDomain\fP< dim, CELLTYPE > & domain, bool debug = \fRfalse\fP)"

.PP
also considers "dS" pde operators from \fBBoundary\fP or \fBSplitBoundary\fP objects if these share nodes with domain on which the solution is obtained Accumulates element integrals, but simultaneously considering potential \fBBoundary\fP objects associated with the simplicial complex\&. The domain is the computational domain to which the \fBPDE_Integrator\fP is applied\&.

.PP
\fBAttention\fP
.RS 4
costly element search; use only if there are boundary integrals on other domains present
.RE
.PP
\fBAuthor\fP
.RS 4
SKM 7/7/2015
.RE
.PP
TODO: detections of intersections between box boundaries and computational domains is missing TODO: avoid repeated check of whether faces or interfaces are contained in comp-domain, by remembering subset of these after first check 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::IntegrateOver (\fBModelSubDomain\fP< dim, CELLTYPE > & domain, bool debug = \fRfalse\fP)"

.PP
accumulates, assembles, and solves PDEs in domain of interest; 
.PP
\fBParameters\fP
.RS 4
\fIdebug\fP prompts output of solution matrices to file; uses node numbering
.RE
.PP
Assembly and solution of the system of linear algebraic equations, but without consideration of boundary integrals:

.PP
.IP "1." 4
Dimensionsing of the solution matrix (n-variables, scalar or vector etc\&.)
.IP "2." 4
Accumulation of the FE or FV integrals
.IP "3." 4
Multiplication of the initial conditions into the RHS in the case of the transient problem\&.
.IP "4." 4
Late accumulation to RHS
.IP "5." 4
Essential conditions (either with or without elimination of the Dirichlet constraints from the matrix)\&.
.IP "6." 4
Output matrix and vectors to get diagnostics
.IP "7." 4
Solution
.IP "8." 4
Output results back to moel
.IP "9." 4
Postprocessing (if respective pde operators were added to the \fBPDE_Integrator\fP) and writing related results to model\&. 
.PP

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::LateAccumulate (const \fBModelSubDomain\fP< dim, CELLTYPE > & gref)\fR [protected]\fP, \fR [virtual]\fP"

.PP
accumulates finite-element integrals to matrix and vector after the corresponding entries were already multiplied with the initial conditions; uses node numbering \fBLateAccumulate()\fP adds source and sink terms into the righthand vector after all other accumulations have occurred\&. This timing is required if an implicit time-stepping scheme is used\&. The method retrieves information from the mesh and the property managers\&. If a group computation is carried out, the target group is accessed by a pointer\&.
.SH "Implementation"
.PP
Those math operators which have been ear-marked for late accumulation are added by this method\&. Like in \fBAccumulate()\fP this addition requires the execution of the math operator methods:

.PP
.PP
.nf
GetOperands();
ComputeContribution();
AssignToGlobal();
.fi
.PP
.SH "Application Examples"
.PP
\fBLateAccumulate()\fP is executed only in time-dependent calculations\&. The execution is invoked internally, when the \fBPDE_Integrator\fP is passed to the \fBModel\fP\&. 
.PP
.nf
@attention Method relies on a 0\&.\&.n contiguous numbering of the finite element nodes\&.

.fi
.PP
 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::LateAccumulateBoundaryIntegrals (const \fBModelSubDomain\fP< dim, CELLTYPE > & comp_domain, const \fBBoundary\fP< dim > & boundary)\fR [protected]\fP, \fR [virtual]\fP"

.PP
late accumulates surface integrals from Neumann-flagged \fBFace\fP object variables representing those parts of all boundaries that delimit the computational domain For source terms on the surface that need to be added to the righthand side after time or other conditions were multiplied in the righthand vector\&.

.PP
\fBAttention\fP
.RS 4
Method relies on a 0\&.\&.n contiguous numbering of the finite element nodes\&. 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::ListMathOperatorsLHS () const"
Lists all MathOperator objects which have been defined for the \fBPDE_Integrator\fP\&. These are output by name in alphabetical order\&. For the output, the MathOperator interface method \fBOut()\fP is used\&. Thus, you influence the information that is output when you define your own PDE operator subclasses\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::Out () const"

.PP
prints current parameters settings and pde operators to screen Prints the state of the integrator to the screen\&.

.PP
std::map<std::string,\fBMathOperatorLHS<dim>\fP\fI> lhs_operators_; std::map<std::string,\fBMathOperatorRHS<dim>\fP\fP> rhs_operators_; std::map<std::string,\fBMathOperatorRHS<dim>\fP\fI> rhs_boundary_operators_; std::map<std::string,\fBMathOperatorLHS<dim>\fP\fP> postpro_operators_; std::map<Parameter,size_t> basic_operands_; std::map<Parameter,size_t> test_operands_;

.PP
\fBSparseMatrix\fP G_; std::vector<double> rh_; std::vector<double> x_; Solver* solver_;

.PP
const size_t dim2_; size_t dof_per_node_; bool setup_established_, retain_matrix_; const bool newed_Solver_object; double time_increment_;

.PP
struct \fBSIZES\fP { size_t nodes; size_t elements; } target_;

.PP
private:

.PP
double scale_factor_; ///< for essential conditions bool verbose_; 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE = Element> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::OutputGlobals (int precision = \fR1\fP)"

.PP
outputs the system A x = b to the screen Prints out the sparse solution matrix and the righthand vector

.PP
\&.\&.\&.which were accumulated by the \fBPDE_Integrator\fP\&. If you execute this method after passing the \fBPDE_Integrator\fP to the \fBModel\fP, the matrix will have been modified by the \fBSolver\fP object\&.
.SH "Application Examples"
.PP
To test the accumulation process by visual examination of the matrices, you must call it directly after executing \fBAccumulate()\fP, see below\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::OutputResults (\fBModelSubDomain\fP< dim, CELLTYPE > & gref)\fR [protected]\fP, \fR [virtual]\fP"

.PP
transfers the results stored in solution vector onto the nodes of the computational domain; uses node numbering Once a solution has been computed by the current \fBSolver\fP object, the results stored in the solution vector are written back to the \fBModel\fP or subregions thereof\&. The original variable flags are preserved\&.
.SH "Implementation"
.PP
The solution vector indices are re-translated into the temporary node ids\&.
.SH "Application Examples"
.PP
\fBOutputResults()\fP is executed internally, when a \fBPDE_Integrator\fP object is passed to the \fBModel\fP\&.

.PP
\fBAttention\fP
.RS 4
Method relies on an 0\&.\&.n contiguous node numbering in the region (computational domain)\&. 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::PostProcess (\fBModelSubDomain\fP< dim, CELLTYPE > & gref)\fR [protected]\fP, \fR [virtual]\fP"

.PP
allows to apply pde operators to post-process the newly computed solution \fBPostProcess()\fP is a virtual \fBPDE_Integrator\fP interface to be implemented in a subclass\&. You can use it for any kind of post-processing operations especially those which use data from the solution matrix\&. In sublclasses of the older \fBPDE_Integrator\fP class, post-processing is used to calculate flow velocities (Velocity, InterstitialVelocity subclasses) or stresses and strains from displacements (LinearElasticity subclass)\&. The method retrieves information from the mesh and the property managers\&. If a group computation is carried out, the target group is accessed by a pointer\&.
.SH "Implementation"
.PP
Define your own using the interfaces of the MeshManger, the MemoryManager, the \fBPropertyDatabase\fP and the \fBRegion\fP\&.
.SH "Application Examples"
.PP
\fBPostProcess()\fP is executed internally when the \fBPDE_Integrator\fP is passed to the \fBModel\fP\&.
.SH "Messages"
.PP
When you use the \fBPDE_Integrator\fP baseclass in your computations or if you do not define \fBPostProcess()\fP, you will get the info message:

.PP
"no post-processing operations for REGION were defined in derived PDE_Integrator" 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::ReduceSystemSizeEliminatingEssentialConditions (const \fBModelSubDomain\fP< dim, CELLTYPE > & gref, size_t total_degrees_of_freedom)\fR [protected]\fP"

.PP
for the elimination of Dirichlet constraints from the solution matrix; called after EstablishMatrixSetup but before accumulation Enumerate method must be applied AFTER establish matrix setup process\&. and BEFORE the accumulated proecess\&. When you assemble vector or tensor variables, you also have the option of only assembling one of their components\&. To do this just set the components that you do not want to assemble to DBL_MAX\&.

.PP
\fBAttention\fP
.RS 4
G matrix is erased by this method 

.PP
Method relies on a 0\&.\&.n contiguous numbering of the finite element nodes\&.
.RE
.PP
\fBAuthor\fP
.RS 4
Luat Khoa Tran
.RE
.PP
\fBAttention\fP
.RS 4
SKM - some refactoring 31/8/22 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::Reset (bool delete_math_operators = \fRtrue\fP)\fR [virtual]\fP"

.PP
returns PDE integrator into the state created by default constructor ( 
.PP
\fBTodo\fP
.RS 4
is Reset is this needed?) 
.RE
.PP

.PP
After an \fBPDE_Integrator\fP has been applied, the solution matrix G and the righthand vector rh contain data which need to be removed before a new accumulation can take place\&. This is done automatically by the \fBPDE_Integrator\fP, unless it has been asked to retain the solution matrix\&.

.PP
However, you may want to use new PDE operators, a new computational domain and/or computational method\&. In this case, \fBReset()\fP allows to restore the \fBPDE_Integrator\fP's default state and zero's the elements of its matrix and vector storage\&.
.SH "Application Examples"
.PP
Typically, you will reset an \fBPDE_Integrator\fP if you can just re-use it for another task\&. This is always recommended, since this permits to make use of the already initialized solution matrix, because the memory of it (owing to the Meschach implementation) is not de-allocated before the programme terminates\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::SetSolver (\fBSolver\fP & new_solver)"

.PP
switch to another solver deleting any dynamically allocated solver that was associated with integrator If a solver was allocated earlier it is deleted before the new_solver is connected to the \fBIntegrator\fP\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::SolutionVector (std::vector< double > & sol) const"

.PP
outputs solution vector; 
.PP
\fBAttention\fP
.RS 4
this produces meaningful results only after application of the PDE integrator
.RE
.PP
.SH "Application Examples"
.PP
Use this method to extract the solution vector from the algorithm, for instance to use it as initial guess in another time step\&. (Use method FirstGuess) 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::Solve ()\fR [protected]\fP, \fR [virtual]\fP"

.PP
calls connected solver object to find x in G x = rh problem Calls the \fBSolver\fP interface SolveMatrixEquation() and hands G, rh, x to the \fBSolver\fP which returns the solution into the vector x\&.
.SH "Application Examples"
.PP
The method \fBSolve()\fP is called internally, when the \fBPDE_Integrator\fP object is passed to the \fBModel\fP\&.

.PP
The solver reports a range of parameters in the solution process\&. These are described in detail in the CSMP User's guide\&. Important is that the final residue of the solution (which could be compared to a signal-to-noise ratio) is several orders of magnitude lower than the initial residue\&. Otherwise the obtained solution is useless\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::TimeIncrement (double dt)"

.PP
sets the time-increment for- and triggers a transient calculation (use 1/t if problem has been set up that way) Sets the time-icrement in a transient calculation\&.

.PP
If one forget to set the \fBPDE_Integrator\fP to transient, this is done as well\&.
.SH "Application Examples"
.PP
Set the time-increment of an \fBPDE_Integrator\fP before you Apply() it to the \fBModel\fP or target \fBRegion\fP objects\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> bool \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::Transient () const"

.PP
returns whether a finite-difference time increment has been set Transient \fBPDE_Integrator\fP

.PP
The accumulation process for a transient \fBPDE_Integrator\fP is different from a steady-state \fBPDE_Integrator\fP in that initial conditions must be assigned and matrices must be multiplied with the time_increment\&. This method sets the \fBPDE_Integrator\fP state to transient or retrieves its state\&.
.SH "Application Examples"
.PP
Every \fBPDE_Integrator\fP which you define in your program uses storage for G, x, and rhs\&. You should therefore always limit the number of A\&. to those essential\&. Use this method if you want to re-use a previously defined steady-state \fBPDE_Integrator\fP\&. 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::PDE_Integrator_CRM\fP< dim, CELLTYPE >::TrimExcessCapacityOfVectors (bool trim)"

.PP
'swap trick' keeps size and capacity of solution and righthand vectors equal Default = false, switch on if size matters more than speed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
