.TH "csmp::Interfaces_Example" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Interfaces_Example
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::Example\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBRun\fP ()"
.br
.ti -1c
.RI "virtual void \fBSpecifications\fP ()"
.br
.ti -1c
.RI "template<uint32_t dim> void \fBBuildFromSKUAModel\fP (const string &model_name)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Example\fP
.in +1c
.ti -1c
.RI "\fBExample\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "void \fBSetTitle\fP (const std::string &text)"
.br
.RI "Reporting interface\&. "
.ti -1c
.RI "void \fBSetCategory\fP (const std::string &text)"
.br
.ti -1c
.RI "void \fBSetDifficulty\fP (const int &difficulty)"
.br
.RI "set function, takes care that 0 < difficulty < 4 "
.ti -1c
.RI "void \fBAddDescription\fP (const std::string &text)"
.br
.RI "allows to add a descrtiption to an example "
.ti -1c
.RI "void \fBAddRequirement\fP (const std::string &text)"
.br
.RI "allows to add a requirement to an example (files etc\&.\&.) "
.ti -1c
.RI "void \fBAddAuthor\fP (const std::string &text)"
.br
.RI "allows to add an author to an example "
.ti -1c
.RI "std::string \fBGetTitle\fP () const"
.br
.RI "example title return function "
.ti -1c
.RI "int \fBGetDifficulty\fP () const"
.br
.RI "return function "
.ti -1c
.RI "std::string \fBGetCategory\fP () const"
.br
.RI "return function "
.ti -1c
.RI "std::list< std::string >::const_iterator \fBGetDescriptionsBegin\fP ()"
.br
.RI "return function "
.ti -1c
.RI "std::list< std::string >::const_iterator \fBGetDescriptionsEnd\fP () const"
.br
.RI "return function "
.ti -1c
.RI "std::list< std::string >::const_iterator \fBGetAuthorsBegin\fP ()"
.br
.RI "return function "
.ti -1c
.RI "std::list< std::string >::const_iterator \fBGetAuthorsEnd\fP () const"
.br
.RI "return function "
.ti -1c
.RI "std::list< std::string >::const_iterator \fBGetRequirementsBegin\fP ()"
.br
.RI "return function "
.ti -1c
.RI "std::list< std::string >::const_iterator \fBGetRequirementsEnd\fP () const"
.br
.RI "return function "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Example\fP
.in +1c
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.RI "assures db to contain data "
.ti -1c
.RI "std::ostream * \fBGetStream\fP ()"
.br
.ti -1c
.RI "void \fBSetStream\fP (std::ostream *ostream)"
.br
.ti -1c
.RI "std::string \fBGetExampleFileName\fP (const char *path)"
.br
.ti -1c
.RI "void \fBCreateWorkingDirectoryAndCopyInputModelFiles\fP (std::string &example_name, std::string &model_name, std::string &variable_file, std::string config_file='')"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void csmp::Interfaces_Example::Run ()\fR [virtual]\fP"
Builds CSMP native format models (binary files) using various interfaces, including ANSYS, SKUA, ECLIPSE, RHINO, TRIANGLE, etc\&. User can select which model to build or build all the models that shall be used in other examples\&. For this purpose, existing "default" files from the directory example_inputs/ will be used\&.

.PP
\fBAttention\fP
.RS 4
To run the OpenCSMP examples, please copy the 'example_inputs/' directory to a location outside of the open-csmp repository as you do not want the repository to track your experimentation with the examples\&.\&. Set this new directory as the working directory of your IDE (CLion, XCode, QT_Creator, MS Vis Studio etc\&.)\&. Look at the 3 sub directories of example_inputs/ after running the example\&. They should contain:
.RE
.PP
.IP "\(bu" 2
"input_meshes/" contains mesh files that can be read by OpenCSMP interfaces;
.IP "\(bu" 2
'csmp_native_format_models/' that contains OpenCSMP native format binary files (*\&.vset and *\&.dat files);
.IP "\(bu" 2
'variables_and_configuration_files/' (*\&.txt files) containing variable lists and model configuration files\&.
.PP

.PP
'bitmaps_and_other/' contains misc files that can serve the creation of CSMP native models

.PP
\fBNote\fP
.RS 4
Typically the name of these files represents the name of the model with an argument like '-variables\&.txt' of '-configuration\&.txt' see CSMP users guide\&.
.RE
.PP
Creating new subdirectories in your new working directory, this \fBRun()\fP functions will:

.PP
1) create an example directory from its name (i\&.e\&., 'example_outputs/example_name/');

.PP
2) recover default input files from the 'example_inputs/' directory, copy them into the example directory

.PP
3) produce all outputs in the created example directory (note: if an example directory already exists, it will be overwritten)\&.

.PP
\fBNote\fP
.RS 4
to use your own inputs, please copy the input files into corresponding sub directories of 'example_inputs/'
.RE
.PP
\fBAttention\fP
.RS 4
Again: do not create your working directory anywhere inside the cloned open-csmp repository! 
.RE
.PP

.PP
Implements \fBcsmp::Example\fP\&.
.SS "void csmp::Interfaces_Example::Specifications ()\fR [virtual]\fP"

.PP
Implements \fBcsmp::Example\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
