.TH "csmp::Region< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Region< dim > \- To associate and access elements which share certain properties\&. Once such a distinction has been made these can be drawn or output to specific visualization software\&. Examples: shale horizons, faults etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Region\&.h>\fP
.PP
Inherits \fBcsmp::ModelSubDomain< dim, Element >\fP, and \fBcsmp::LocalVariableStorage< dim, Region >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegion\fP (std::string regionname, const \fBPropertyDatabase\fP< dim > &)"
.br
.RI "construction of named empty region with appropriately sized property storage "
.ti -1c
.RI "\fBRegion\fP (const \fBRegion\fP &)"
.br
.ti -1c
.RI "\fBRegion\fP (\fBRegion\fP &&)"
.br
.ti -1c
.RI "\fBRegion\fP & \fBoperator=\fP (const \fBRegion\fP &)"
.br
.ti -1c
.RI "\fBRegion\fP (const \fBPropertyDatabase\fP< dim > &, \fBMeshManager\fP< dim > &, const \fBSubDomainInfo\fP &)"
.br
.RI "RECONSTRUCTOR for regions via the \fBMeshManager\fP (call only prior to deleting anythin from colonies) "
.ti -1c
.RI "\fBRegion\fP (const \fBPropertyDatabase\fP< dim > &, const std::deque< \fBNode\fP< dim > * > &, const std::deque< \fBElement\fP< dim > * > &, const \fBSubDomainInfo\fP &)"
.br
.RI "RECONSTRUCTOR for regions via the nodes and elements which are explored by the \fBMeshManager\fP\&. "
.ti -1c
.RI "void \fBSetRegion_ID\fP (int32_t region_id_for_non_unique_regions=UNSPECIFIED)"
.br
.RI "Sets the \fBRegion\fP ID to \fBModelSubDomain::domain_idx_\fP for all elements of unique region; override as is needed\&. "
.ti -1c
.RI "template<typename Var> void \fBInputPropertyValue\fP (const char *input_prop, const Var &new_value, \fBSUBDOMAIN_PART\fP sd=COMPLETE)"
.br
.RI "for the assignment of properties that are unique to the instance of this subclass "
.ti -1c
.RI "template<typename Var> void \fBInputPropertyValue\fP (const char *input_prop, const Var &new_value, \fBVARIABLE_FLAG\fP flag_of_values_to_be_preserved, \fBSUBDOMAIN_PART\fP=COMPLETE)"
.br
.RI "as InputPropertyValue, but with overwrite protection for variable components that have the flag 'do_not_overwrite' "
.ti -1c
.RI "virtual \fBPLACEMENT\fP \fBPlacement\fP () const override"
.br
.RI "Local variable storage interface\&. "
.ti -1c
.RI "virtual bool \fBValidVariable\fP (const char *variableName) const override"
.br
.RI "checks whether variable placement is compatible with placement on a region "
.ti -1c
.RI "void \fBOutputTo\fP (\fBVSet\fP< dim > &vset, bool with_properties=true) const"
.br
.RI "outputs region into \fBVSet\fP polygonal data container; all properties may be output as well "
.ti -1c
.RI "void \fBOutputTo\fP (\fBVSet\fP< dim > &vset, const std::map< std::string, \fBIndex\fP > &properties_to_be_output_for_region) const"
.br
.RI "outputs region into \fBVSet\fP polygonal data container, including a selected list of properties "
.ti -1c
.RI "void \fBOutputDataTo\fP (\fBVSet\fP< dim > &vset) const"
.br
.RI "output all distributed properties into the supplied \fBVSet\fP "
.ti -1c
.RI "void \fBOutputFvDataTo\fP (\fBVSet\fP< dim > &vset) const"
.br
.RI "outputs finite-volume sector and facet variables to \fBVSet\fP "
.ti -1c
.RI "\fBPropertyData\fP \fBOutputVariableTo\fP (const char *region_property) const"
.br
.RI "outputs distributed variable to variable storage container of type \fBPropertyData\fP "
.ti -1c
.RI "template<class Var> void \fBOutputVariableTo\fP (const char *property, \fBFEM_Data\fP< Var > &data_local) const"
.br
.RI "outputs distributed variable to \fBFEM_Data\fP container "
.ti -1c
.RI "template<class Var> void \fBInputVariableFrom\fP (const char *property, const \fBFEM_Data\fP< Var > &vdata)"
.br
.RI "inputs distributed variable from file into region; "
.ti -1c
.RI "size_t \fBAccumulateAll\fP (\fBMeshManager\fP< dim > &)"
.br
.RI "creates pointers to non const elements in the mesh directly from \fBMeshManager\fP; returns the number of elements of the new region "
.ti -1c
.RI "size_t \fBAccumulateByNumber\fP (\fBMeshManager\fP< dim > &, std::vector< size_t > &element_ids)"
.br
.RI "creates element pointers assuming that the order in which the elements are stored in the \fBMeshManager\fP matches that in the element_ids vector; no 'idx' searching "
.ti -1c
.RI "size_t \fBAccumulateByNumber\fP (typename std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator start, typename std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator end, std::vector< size_t > &element_ids)"
.br
.RI "accumulate those elements into a region whose id matches one of the numbers contained in vector 'element_ids' using binary_search; "
.ti -1c
.RI "size_t \fBAccumulate\fP (typename std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator start, typename std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator end)"
.br
.RI "accumulates range of elements into a region identified by constant pointers created by AccumulateAll; returns # of accumulated elements "
.ti -1c
.RI "size_t \fBAccumulate\fP (typename std::set< \fBcsmp::Element\fP< dim > * >::const_iterator start, typename std::set< \fBcsmp::Element\fP< dim > * >::const_iterator end)"
.br
.RI "accumulate a range of elements into a region identified by constant pointers created by AccumulateAll; returns # of accumulated elements "
.ti -1c
.RI "size_t \fBAccumulateWithinRange\fP (\fBMeshManager\fP< dim > &, const \fBPropertyConstraints\fP &)"
.br
.RI "accumulates region whose elements have properties in the ranges defined inside of the \fBPropertyConstraints\fP object; returns number of elements found "
.ti -1c
.RI "size_t \fBAccumulateWithinRange\fP (\fBMeshManager\fP< dim > &, const char *property, double min, double max)"
.br
.RI "accumulates elements where (at least one node) has 'property' values in the range defined by 'min/max', returns number of elements found "
.ti -1c
.RI "size_t \fBAccumulateRectangularRegion\fP (\fBMeshManager\fP< dim > &, const \fBPoint\fP< dim > &xyz_min, const \fBPoint\fP< dim > &xyz_max)"
.br
.RI "accumulates region of elements whose barycenter lies within the defined bounding box "
.ti -1c
.RI "void \fBAdd\fP (const \fBRegion\fP &)"
.br
.RI "merges supplied region with the current one "
.ti -1c
.RI "size_t \fBRemoveByNumber\fP (std::vector< size_t > &element_ids, std::vector< \fBcsmp::Element\fP< dim > * > &ptrs_to_removed_elements)"
.br
.RI "removes those elements in the region whose id matches one of the numbers contained in vector 'element_ids' "
.ti -1c
.RI "size_t \fBRemoveRange\fP (typename std::vector< \fBcsmp::Element\fP< dim > * >::iterator begin, typename std::vector< \fBcsmp::Element\fP< dim > * >::iterator end)"
.br
.RI "removes those elements from the target region whose pointers matches the ones in the range supplied and subsequently rebuilds the region "
.ti -1c
.RI "void \fBMoveNodeCoordinatesBy\fP (const char *vector_variable)"
.br
.RI "movement of the nodes in the region "
.ti -1c
.RI "virtual void \fBAccept\fP (\fBVisitor\fP< dim > &) override"
.br
.RI "Visitors\&. "
.ti -1c
.RI "bool \fBIncludes\fP (const \fBRegion\fP &) const"
.br
.RI "tests whether the current region includes the specified one "
.ti -1c
.RI "std::pair< int32_t, int32_t > \fBElementSpatialDimensions\fP () const"
.br
.RI "returns 1) elements of how many different spatial dimensions are contained, and 2) the highest element spatial dimension in subdomain "
.ti -1c
.RI "double \fBSurfaceArea\fP () const"
.br
.RI "returns either the lenght of the perimeter (2D) or the surface area of the region (3D) "
.ti -1c
.RI "double \fBVolume\fP (bool multiply_with_porosity=false) const"
.br
.RI "returns either the area of a surface region, the length of a line region or the region's volume "
.ti -1c
.RI "double \fBVolumeIntegral\fP (const char *property, bool multiply_with_porosity, bool verbose=true) const"
.br
.RI "integration over volume elements "
.ti -1c
.RI "double \fBVolumeIntegral_x_Thickness\fP (const char *property, bool multiply_with_porosity=false) const"
.br
.RI "integration over volume and surface elements using thickness attribute (=1 for volume elements) "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "no variables in addition to \fBModelSubDomain\fP "
.in -1c

Public Member Functions inherited from \fBcsmp::ModelSubDomain< dim, Element >\fP
.in +1c
.ti -1c
.RI "\fBModelSubDomain\fP (const std::string &subdomain_name, const \fBPropertyDatabase\fP< dim > &)"
.br
.RI "constructs incomplete subdomain for later initialisation with suitable methods in subclasses "
.ti -1c
.RI "\fBModelSubDomain\fP< dim, \fBElement\fP > & \fBoperator=\fP (const \fBModelSubDomain\fP &)"
.br
.ti -1c
.RI "std::string \fBName\fP () const"
.br
.ti -1c
.RI "void \fBApply\fP (\fBInterrelation\fP< dim > &)"
.br
.RI "modification via Operand-based relations between discretised properties that only modify a single result variable "
.ti -1c
.RI "void \fBRebuildSubDomainAfterChangeOfCellVector\fP ()"
.br
.RI "deletes nullptr cells, rebuilds node vector, sorts everything and re-establishes the perimeter face vectors after modifications of cells "
.ti -1c
.RI "void \fBRebuildSubDomainAfterChangeOfNodeVector\fP ()"
.br
.RI "rebuilds node vector, sorts everything and re-establishes interior and perimeter "
.ti -1c
.RI "void \fBUpdateCellMembershipApplyingConstraints\fP (typename std::vector< \fBElement\fP< dim > * >::const_iterator master_domain_start, typename std::vector< \fBElement\fP< dim > * >::const_iterator master_domain_end, const \fBPropertyConstraints\fP &)"
.br
.RI "rebuilds subdomain on the basis of the cells that will be selected according to the supplied property constraints "
.ti -1c
.RI "void \fBIdentifyPerimeter\fP ()"
.br
.RI "distinguishes PERIMETER simplices that have at least one face on domain boundary from INTERIOR ones; calls PartitionElementVector() "
.ti -1c
.RI "void \fBCreateNodePointerVector\fP ()"
.br
.RI "creates node pointer vector from cell vector, using a vector to achieve uniqueness via sort, unique, erase algorithms "
.ti -1c
.RI "void \fBSortVectors\fP (size_t interior_cells, size_t interior_nodes)"
.br
.RI "sorts the node and CELL vectors split into the interior and perimeter ranges (4 sorting operations) "
.ti -1c
.RI "void \fBBuildPerimeterFaceVector\fP (int64_t interior_cells)"
.br
.RI "assuming that a partitioned (and sorted) cell vector is in place, constructs the bd_face_vec_ by checking whether neighbor cells belong to the domain or not "
.ti -1c
.RI "void \fBScheduleForRebuild\fP ()"
.br
.RI "for rebuilding subdomains when nodes or cells changed: flag up for a rebuild using RebuildSubDomainAfterChangeOfCellVector "
.ti -1c
.RI "bool \fBNeedsRebuild\fP () const"
.br
.ti -1c
.RI "size_t \fBRebuildCellAndPerimeterFaceVector\fP ()"
.br
.RI "deletes 'nullptr' cells from cell vector, retaining the sorting into interior and perimeter elements, and rebuilding perimeter faces as necessary "
.ti -1c
.RI "size_t \fBRebuildNodeVector\fP ()"
.br
.RI "deletes 'nullptr' nodes from \fBNode\fP vector, retaining the sorting into interior and perimeter nodes "
.ti -1c
.RI "int32_t \fBDomainIndex\fP () const"
.br
.RI "reference counting-based unique domain identifier (0\&.\&.n-1) "
.ti -1c
.RI "size_t \fBRenumberNodes\fP () const"
.br
.RI "renumbers nodes in domain 0\&.\&.n-1 "
.ti -1c
.RI "size_t \fBRenumberCells\fP () const"
.br
.RI "renumbers cells in domain 0\&.\&.n-1 "
.ti -1c
.RI "void \fBUpdateMemberIndexes\fP () const"
.br
.RI "renumber cells and nodes consecutively from 0\&.\&.n-1 "
.ti -1c
.RI "std::vector< size_t > \fBMemberCellIndexes\fP () const"
.br
.RI "output current indices to vector "
.ti -1c
.RI "const std::vector< \fBElement\fP< dim > * > & \fBCellVector\fP () const"
.br
.RI "reference to container of finite cell pointers to either \fBElement\fP, \fBFace\fP or \fBInterFace\fP objects; "
.ti -1c
.RI "const std::vector< \fBNode\fP< dim > * > & \fBNodeVector\fP () const"
.br
.RI "reference to const \fBNode\fP pointer vector "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBNodesBegin\fP () const"
.br
.RI "const iterators (cell and node pointers cannot be modified but the nodes and cells can!) "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBPerimeterNodesBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBNodesEnd\fP () const"
.br
.ti -1c
.RI "std::vector< \fBElement\fP< dim > * >::const_iterator \fBCellsBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBElement\fP< dim > * >::const_iterator \fBPerimeterCellsBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBElement\fP< dim > * >::const_iterator \fBCellsEnd\fP () const"
.br
.ti -1c
.RI "size_t \fBSharedPerimeterNodes\fP (typename std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator start, typename std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator end) const"
.br
.RI "returns how many of the nodes in the supplied iterator range also form part of the current subdomain's perimeter "
.ti -1c
.RI "bool \fBEmpty\fP () const"
.br
.RI "check whether subdomain conatains any cells "
.ti -1c
.RI "size_t \fBNodes\fP () const"
.br
.ti -1c
.RI "size_t \fBInteriorNodes\fP () const"
.br
.ti -1c
.RI "size_t \fBPerimeterNodes\fP () const"
.br
.ti -1c
.RI "size_t \fBIntegrationPoints\fP () const"
.br
.ti -1c
.RI "size_t \fBSectorIntegrationPoints\fP () const"
.br
.ti -1c
.RI "size_t \fBFacetIntegrationPoints\fP () const"
.br
.ti -1c
.RI "size_t \fBCells\fP () const"
.br
.ti -1c
.RI "size_t \fBInteriorCells\fP () const"
.br
.ti -1c
.RI "size_t \fBPerimeterCells\fP () const"
.br
.ti -1c
.RI "bool \fBContains\fP (const \fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "bool \fBIsPerimeterNode\fP (const \fBcsmp::Node\fP< dim > *const) const"
.br
.ti -1c
.RI "bool \fBIsPerimeterCell\fP (const \fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "uint32_t \fBPerimeterFaces\fP (size_t eid) const"
.br
.RI "for looping over the perimeter faces of perimeter cell with #eid, method is used to travel across subdomain surface / outline "
.ti -1c
.RI "uint32_t \fBPerimeterFace\fP (size_t eid, uint32_t face) const"
.br
.RI "returns local face id of face #face that lies on perimeter of model subdomain "
.ti -1c
.RI "\fBcsmp::Node\fP< dim > * \fBN\fP (size_t n) const"
.br
.RI "pointer to node #n in subdomain; "
.ti -1c
.RI "\fBElement\fP< dim > * \fBE\fP (size_t n) const"
.br
.RI "pointer to cell #n of model subdomain "
.ti -1c
.RI "bool \fBIsContiguous\fP () const"
.br
.RI "checks whether all cells within the subdomain are interconnected (if the domain has multi-dimensional cells this is never the case) "
.ti -1c
.RI "std::pair< \fBCELL_SHAPE\fP, bool > \fBSingleCellShapeDomain\fP () const"
.br
.RI "if the model subdomain consists of a single cell shape (line, surface, volume) this method returns true revealing the type "
.ti -1c
.RI "std::pair< int32_t, int32_t > \fBSpatialDimensions\fP () const"
.br
.RI "returns 1) cells of how many different spatial dimensions are contained, and 2) the highest cell spatial dimension in subdomain "
.ti -1c
.RI "void \fBMinMaxCoordinates\fP (\fBPoint\fP< dim > &xyz_min, \fBPoint\fP< dim > &xyz_max) const"
.br
.RI "returns diagonally opposite points of bounding box "
.ti -1c
.RI "void \fBAssignNodeCoordinatesTo\fP (const char *vector_prop)"
.br
.RI "output coordinates to user-defined vector variable [x1,y1,z1,\&.\&.\&.xn,yn,zn] "
.ti -1c
.RI "void \fBAssignCellCharacteristicsTo\fP (const char *characteristic, const char *var)"
.br
.RI "characteristics like 'length', 'area', 'volume' , 'aspect ratio', 'inner radius' are assigned to user-defined variable "
.ti -1c
.RI "void \fBNodeAttributesToCSV\fP ()"
.br
.RI "writes a CSV (comma delimited ascii text) file with point coordinates, node-idx, \fBBOX_BOUNDARY\fP flags, and interior vs perimeter information "
.ti -1c
.RI "void \fBInputPropertyValue\fP (const char *input_prop, const Var &new_value, \fBSUBDOMAIN_PART\fP sd=COMPLETE)"
.br
.RI "assigns uniform (single) variable value to either the entire subdomain or its interior or perimeter "
.ti -1c
.RI "void \fBChangePropertyStatus\fP (const char *property, \fBVARIABLE_FLAG\fP new_status_of_scalar, \fBSUBDOMAIN_PART\fP=COMPLETE)"
.br
.RI "changes the flag of the scalar variable 'property' to new value; applied either in the entire subdomain or its interior or perimeter "
.ti -1c
.RI "void \fBChangePropertyStatusWhere\fP (const char *property, \fBVARIABLE_FLAG\fP new_status_of_scalar, double min_value_to_change, double max_value_to_change)"
.br
.RI "changes the flag of the scalar variable 'property' to new value if the scalar variable is withing the specified range "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBPropertyStatus\fP (const char *\fBvariable\fP, \fBSUBDOMAIN_PART\fP flag=COMPLETE, uint32_t i=0) const"
.br
.RI "by default (i=0) returns status of scalar variable or first component of a vector or tensor variable; if i>0 flag of corresponding component is returned "
.ti -1c
.RI "void \fBMinMaxOf\fP (const char *property, double &gmin, double &gmax) const"
.br
.RI "min/max property values (length of vectors and eigenvalues of tensors) "
.ti -1c
.RI "void \fBInterpolateNodeToCellProperty\fP (const char *nprop, const char *eprop)"
.br
.ti -1c
.RI "void \fBInterpolateNodeToIntegrationPointProperty\fP (const char *nprop, const char *eprop)"
.br
.ti -1c
.RI "void \fBInterpolateIntegrationPointToCellProperty\fP (const char *cprop, const char *eprop)"
.br
.ti -1c
.RI "void \fBExtrapolateCellToIntegrationPointProperty\fP (const char *eprop, const char *cprop)"
.br
.ti -1c
.RI "void \fBExtrapolateCellToFacetIntegrationPointProperty\fP (const char *eprop, const char *fipprop)"
.br
.ti -1c
.RI "void \fBExtrapolateCellToNodeProperty\fP (const char *eprop, const char *nprop, bool by_distance=true)"
.br
.ti -1c
.RI "void \fBExtrapolateIntegrationPointToNodeProperty\fP (const char *cprop, const char *nprop)"
.br
.ti -1c
.RI "double \fBAverage\fP (const char *property) const"
.br
.RI "arithmetic (number as opposed to volume weighted) average "
.ti -1c
.RI "bool \fBCopyGradientOfProperty_A_To_B\fP (const char *node_prop, const char *cell_prop)"
.br
.ti -1c
.RI "void \fBCopyReplace\fP (const char *from, const char *to)"
.br
.ti -1c
.RI "void \fBWriteDomainIndexesToBinaryFile\fP (std::fstream &) const"
.br
.RI "writes complete \fBModelSubDomain\fP specifications in terms of unique indices as block to binary file "
.ti -1c
.RI "void \fBOutputVariableToScreen\fP (const char *prop) const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::LocalVariableStorage< dim, Region >\fP
.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLocalVariableStorage\fP< dim, \fBRegion\fP > &) const"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBResizePropertyStorage\fP (const \fBLocalVariables\fP &)"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBAddProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Creates an empty space in the storage preserving the original variable values\&. \fBLocalVariables\fP in \fBIndex\fP have to reflect NEW state (incl added) "
.ti -1c
.RI "void \fBDeleteProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Deletes data and flags of property \fBLocalVariables\fP in \fBIndex\fP have to reflect CURRENT state (incl property to be removed) "
.ti -1c
.RI "bool \fBIsWithinRange\fP (const \fBcsmp::Index\fP &, double, double) const"
.br
.ti -1c
.RI "double \fBRead\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar variable value\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar & Array variable flag\&. "
.ti -1c
.RI "void \fBStoreArrayEntry\fP (const \fBcsmp::Index\fP &, double array_elmt_value, int_type)"
.br
.ti -1c
.RI "double \fBReadArrayEntry\fP (const \fBcsmp::Index\fP &, int_type array_elmt) const"
.br
.RI "reads single double element inside of the target array "
.ti -1c
.RI "bool \fBEmptyLVS\fP () const"
.br
.ti -1c
.RI "void \fBOutLVS\fP () const"
.br
.ti -1c
.RI "void \fBAssertPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertFiniteVolumeIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBStoreLocalState\fP (const \fBLocalVariables\fP &lv)"
.br
.RI "We store in debug only\&. "
.ti -1c
.RI "void \fBLVS\fP (const Data &data)"
.br
.RI "copy or move supplied data into storage "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBIntegrationPointVariables\fP \fBElementIntegrationPointVariables\fP () const"
.br
.RI "returns local variables for integration points "
.ti -1c
.RI "\fBLocalVariables\fP \fBElementVariables\fP () const"
.br
.RI "returns local variables for elements "
.in -1c

Protected Member Functions inherited from \fBcsmp::ModelSubDomain< dim, Element >\fP
.in +1c
.ti -1c
.RI "size_t \fBPartitionCellVector\fP ()"
.br
.RI "establishes interior vs\&. exterior simplices and nodes; returns index of first boundary cell "
.ti -1c
.RI "size_t \fBPartitionCellVectorForBoundary\fP ()"
.br
.ti -1c
.RI "size_t \fBPartitionCellVectorForSplitBoundary\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::ModelSubDomain< dim, Element >\fP
.in +1c
.ti -1c
.RI "const \fBPropertyDatabase\fP< dim > & \fBpref_\fP"
.br
.ti -1c
.RI "std::string \fBsubdomain_name_\fP"
.br
.RI "passed down when domain is created so that it can be referred to "
.ti -1c
.RI "std::vector< \fBElement\fP< dim > * > \fBcell_vec_\fP"
.br
.RI "doubly sorted, interior cells first "
.ti -1c
.RI "std::vector< std::vector< uint32_t > > \fBbd_face_vec_\fP"
.br
.RI "matching second sorted range of cell_vec_ "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * > \fBnode_vec_\fP"
.br
.RI "doubly sorted, interior nodes first "
.ti -1c
.RI "size_t \fBfirst_bd_node_\fP"
.br
.RI "begin of the perimeter nodes "
.ti -1c
.RI "int32_t \fBdomain_idx_\fP"
.br
.RI "created during construction from domain_count_ "
.ti -1c
.RI "bool \fBrebuilt_needed_\fP"
.br
.RI "parameter set when mesh gets modified by \fBMeshManager\fP so that update can be prompted "
.in -1c

Static Protected Attributes inherited from \fBcsmp::ModelSubDomain< dim, Element >\fP
.in +1c
.ti -1c
.RI "static int32_t \fBdomain_count_\fP"
.br
.RI "reference-counting to get unique identifier for subdomains "
.ti -1c
.RI "static constexpr bool \fBverbose_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::Region< dim >"To associate and access elements which share certain properties\&. Once such a distinction has been made these can be drawn or output to specific visualization software\&. Examples: shale horizons, faults etc\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1999
.RE
.PP
.SH "Consequences"
.PP
When a new group is formed a group internal flag will be assigned to each node, constraint point and element\&. There are two group-internal object flags, PLAIN and BOUNDARY\&. When a new group is formed, the \fBRegion\fP method IdentifyBoundaryAs() assigns the group-internal object flags, depending on whether the nodes, constraint points or elements in the group lie at the group boundary or inside of the group\&. Elements are assigned a boundary flag if at least one of their faces coincides with the region boundary\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::Region\fP< dim >::Region (const \fBPropertyDatabase\fP< dim > & pref, \fBMeshManager\fP< dim > & mesh, const \fBSubDomainInfo\fP & info)"

.PP
RECONSTRUCTOR for regions via the \fBMeshManager\fP (call only prior to deleting anythin from colonies) contains correctly partitioned vectors and boundary faces

.PP
.PP
.nf
RECONSTRUCTOR
.fi
.PP

.PP
for regions that were stored in the CSMP nativefile format\&.

.PP
Using the connectivity indices for the \fBRegion\fP as retrieved from the CSMP++ native binary file and stored in \fBSubDomainInfo\fP, the regions are recreated\&.

.PP
\fBAttention\fP
.RS 4
the numbering that is provided through the domain info must match the current state of the \fBMeshManager\fP\&.

.PP
the indices are just used to connect the element and node pointers of the region to the mesh storage, but, due to the sorting that this method will perform, they will not correspond to the indices used by the region accessors \fBN()\fP and \fBE()\fP\&.

.PP
this constructor initialises the data of the \fBModelSubDomain\fP from which the region is derived\&. This cannot be done by the subdomain itself because it does not know whether it will consist of elements, faces or interfaces\&. 
.RE
.PP

.PP
\fBParameters\fP
.RS 4
\fImesh\fP not constant because region shall later be able to modify elements and nodes  
.br
\fIinfo\fP information on how to connect pointers to mesh stored in \fBMeshManager\fP 
.RE
.PP

.SS "template<uint32_t dim> \fBcsmp::Region\fP< dim >::Region (const \fBPropertyDatabase\fP< dim > & , const std::deque< \fBNode\fP< dim > * > & , const std::deque< \fBElement\fP< dim > * > & , const \fBSubDomainInfo\fP & )"

.PP
RECONSTRUCTOR for regions via the nodes and elements which are explored by the \fBMeshManager\fP\&. contains correctly partitioned vectors and boundary faces 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::Region\fP< dim >::Accept (\fBcsmp::Visitor\fP< dim > & v)\fR [override]\fP, \fR [virtual]\fP"

.PP
Visitors\&. Recursive visitation of regions (or any other object) starts at application level and finishes at application target\&.

.PP
\fBTodo\fP
.RS 4
SKM provide methods for the new variable placements\&.
.RE
.PP

.PP
\fBTodo\fP
.RS 4
SKM refactor the loops using constants and pre-incrementation to speed them up
.RE
.PP

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP

.PP
Reimplemented from \fBcsmp::ModelSubDomain< dim, Element >\fP\&.
.SS "template<uint32_t dim> size_t \fBcsmp::Region\fP< dim >::Accumulate (typename std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator start, typename std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator end)"

.PP
accumulates range of elements into a region identified by constant pointers created by AccumulateAll; returns # of accumulated elements Accumulates range of elements supplied as a vector\&. Assumes that there are no duplicate \fBElement\fP pointers in vector\&. 
.PP
.nf
@attention needs the input elements to be interconnected correctly already\&.

.fi
.PP
 
.SS "template<uint32_t dim> size_t \fBcsmp::Region\fP< dim >::AccumulateAll (\fBMeshManager\fP< dim > & mesh)"

.PP
creates pointers to non const elements in the mesh directly from \fBMeshManager\fP; returns the number of elements of the new region Creates set of lower dimensional elements that have a face at the boundary of the model subdomain\&. Pointers to these elements are stored in supplied set, and their number is returned\&.

.PP
\fBAttention\fP
.RS 4
SKM method is not implemented yet\&.
.RE
.PP
template<uint32_t dim> size_t Region<dim>::IdentifyLowerDimensionalBoundaryElements( const std::pair<int32_t,int32_t>&,
set<Element<dim>*>& ldim_bdry_elmts ) const { throw logic_error("Region<dim>::IdentifyLowerDimensionalBoundaryElements: method is not implemented yet\&.");

.PP
ldim_bdry_elmts\&.clear();

.PP
size_t counter(0U);

.PP
for ( typename vector<\fBcsmp::Node<dim>\fP*>\fBconst_iterator\fP it=node_vec_\&.begin(); it!=node_vec_\&.end(); it++ ) (*it)->Idx( counter++ );

.PP
return ldim_bdry_elmts\&.size(); } ANDREW BROMAGE

.PP
SKM trying to make sense of Andrew Bromage's undocumented code: 12/08/18 AcculumateAll - but for all potentially disconnected \fBElement\fP patches that make up the model domain\&.

.PP
\fBAttention\fP
.RS 4
assumes that 'indexToPointerMapping' is unique and non empty\&. 
.RE
.PP

.SS "template<uint32_t dim> size_t \fBcsmp::Region\fP< dim >::AccumulateByNumber (\fBMeshManager\fP< dim > & mesh, std::vector< size_t > & element_ids)"

.PP
creates element pointers assuming that the order in which the elements are stored in the \fBMeshManager\fP matches that in the element_ids vector; no 'idx' searching 
.PP
\fBAuthor\fP
.RS 4
SKM revised 22/5/2021 
.RE
.PP

.SS "template<uint32_t dim> size_t \fBcsmp::Region\fP< dim >::AccumulateByNumber (typename std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator start, typename std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator end, std::vector< size_t > & element_ids)"

.PP
accumulate those elements into a region whose id matches one of the numbers contained in vector 'element_ids' using binary_search; 
.PP
\fBAttention\fP
.RS 4
use after mesh modification
.RE
.PP
Form a group from an array of elements supplied as an STL vector\&. The assumption made is that the element numbers are unique and method will sort the supplied number vector\&.
.SH "Input Arguments"
.PP
The supplied element pointer vector must be unique\&. The element numbers must be supplied using their global numbering somewhere in the range 0\&.\&.n-1\&. This numbering is expected to pre-exist\&.

.PP
The input vector is not passed by constant reference because it will be sorted and duplicates are removed when in debug mode\&.
.SH "Implementation"
.PP
The supplied element id vector must be unique and sorted\&. In the debug version, this is tested\&.
.SH "Messages"
.PP
Method will detect if the supplied \fBvector<double>\fP is empty or if a group by that name already exists\&. 
.SS "template<uint32_t dim> size_t \fBcsmp::Region\fP< dim >::AccumulateWithinRange (\fBMeshManager\fP< dim > & mesh, const char * feature, double min, double max)"

.PP
accumulates elements where (at least one node) has 'property' values in the range defined by 'min/max', returns number of elements found Accumulates those property-bearing elements into a region, whose property values are greater or equal to the lower bound of the specified range and smaller or equal to the upper bound of it\&.

.PP
\fBAttention\fP
.RS 4
if the target variable is a node property, by default at least one of the element's nodes must have a value inside of the target range\&. 
.RE
.PP

.SS "template<uint32_t dim> size_t \fBcsmp::Region\fP< dim >::AccumulateWithinRange (\fBMeshManager\fP< dim > & mesh, const \fBPropertyConstraints\fP & constraints)"

.PP
accumulates region whose elements have properties in the ranges defined inside of the \fBPropertyConstraints\fP object; returns number of elements found All those elements for which all property constraints are met are accumulated into this region\&. Returns the number of elements found\&.

.PP
\fBAttention\fP
.RS 4
assumes that the iterator range is unique\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::Region\fP< dim >::Add (const \fBRegion\fP< dim > & grp)"

.PP
merges supplied region with the current one Adds supplied region to the current region\&. 
.SS "template<uint32_t dim> pair< int32_t, int32_t > \fBcsmp::Region\fP< dim >::ElementSpatialDimensions () const"

.PP
returns 1) elements of how many different spatial dimensions are contained, and 2) the highest element spatial dimension in subdomain Detects of how many spatial dimensions element types are contained in model\&. It returns a pair: first value gives number of different spatial dimensions contained, second value returns the highest spatial dimension contained\&.

.PP
\fBAuthor\fP
.RS 4
SKM 1/11/2013 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::Region\fP< dim >::Includes (const \fBRegion\fP< dim > & g) const"

.PP
tests whether the current region includes the specified one If \fBRegion\fP contains all the elements of \fBRegion\fP 'g', \fBIncludes()\fP returns true\&. 
.SS "template<uint32_t dim> template<typename Var> void \fBcsmp::Region\fP< dim >::InputPropertyValue (const char * input_prop, const Var & new_value, \fBSUBDOMAIN_PART\fP sd = \fRCOMPLETE\fP)"

.PP
for the assignment of properties that are unique to the instance of this subclass for the assignment of properties that are unique to the instance of this subclass

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
7/6/2020 
.RE
.PP

.SS "template<uint32_t dim> template<class Var> template void \fBcsmp::Region\fP< dim >::InputVariableFrom< \fBTensorVariable\fP< 3U > > (const char * property, const \fBFEM_Data\fP< Var > & vdata)"

.PP
inputs distributed variable from file into region; 
.PP
\fBNote\fP
.RS 4
indices must match
.RE
.PP
Inputs geometry and property data from an \fBFEM_Data\fP object into this region\&.

.PP
The expectation is that nodes and element numbers in the \fBVData\fP set correspond to these in the current \fBRegion\fP and that elements / nodes in the model have the same ordering as in the input dataset!
.SH "Input Arguments"
.PP
The name of the property which shall be input to \fBVSet\fP\&.
.SH "Implementation"
.PP
The current element and node indices are used to retrieve the data from from the data container\&.
.SH "Application Examples"
.PP
Enable to store data to disk to faciliate persistance\&. 
.SS "template<uint32_t dim> void \fBcsmp::Region\fP< dim >::MoveNodeCoordinatesBy (const char * vector_variable)"

.PP
movement of the nodes in the region Displaces the node coordinates by displacements supplied as through the VECTOR variable (dim = dimensions of the model)\&. For each element, the nodes of which were displaced, the private boolean variable shape_to_date is set to false such that its volume is newly calculated once it is requested\&.

.PP
\fBParameters\fP
.RS 4
\fIvector_variable\fP The name of the nodal \fBvector<double>\fP variable which holds the node coordinate displacement\&.
.RE
.PP
.SH "Implementation"
.PP
After the assignment of the nodal displacements, \fBMoveNodeCoordinatesBy()\fP will set the \fBElement\fP state variable 'shape_to_data' to false\&. This will prompt re-calculation of elemental volumes if these are queried in subsequent computations\&.
.SH "Application Examples"
.PP
If a mesh shall be deformed using the diplacements of a deformation calculation stored in a \fBvector<double>\fP variable, ChangeNodeCoordinatesTo() can be used displace the node coordinates by these displacements\&.
.SH "Messages"
.PP
Due to the total garbage results that may arise, \fBMoveNodeCoordinatesBy()\fP will halt the simulation reporting a fatal error, if the target property is node a node or \fBvector<double>\fP type property\&. 
.SS "template<uint32_t dim> \fBRegion\fP< dim > & \fBcsmp::Region\fP< dim >::operator= (const \fBRegion\fP< dim > & g)"
Assignment does not affect the const reference to 'pref'\&. It remains the same as that before the assignment because it refers to the one \fBModel\fP in which all the Regions live\&. 
.SS "template<uint32_t dim> void \fBcsmp::Region\fP< dim >::OutputTo (\fBVSet\fP< dim > & vset, bool with_properties = \fRtrue\fP) const"

.PP
outputs region into \fBVSet\fP polygonal data container; all properties may be output as well Outputs geometry and property data from the region to a vset\&. The data of the region is copied as is\&. \fBBoundary\fP conditions will be copied if present\&. For unresolved boundaries, the flag IRREGULAR is set\&.

.PP
\fBAttention\fP
.RS 4
Relies on consecutively numbered indices
.RE
.PP
.SH "Implementation"
.PP
All data is copied into the vset\&. IDs are used in the current state\&.
.SH "Application Examples"
.PP
The idea is to create a vset that contains all the information of the region\&. This vset can, for example, later be used to create a new \fBModel\fP\&. 
.SS "template<uint32_t dim> template<class Var> void \fBcsmp::Region\fP< dim >::OutputVariableTo (const char * property, \fBFEM_Data\fP< Var > & data) const"

.PP
outputs distributed variable to \fBFEM_Data\fP container Outputs specific property data to a \fBFEM_Data\fP container\&. This function is a nested template: the outer template provides double = data type and dim = dimension, and Var the data type of the property (\fBScalarVariable\fP, \fBVectorVariable\fP, or \fBTensorVariable\fP)\&.

.PP
\fBNote\fP
.RS 4
The result is returned into \fBFEM_Data\fP container with the data that corresponds to the given property\&.
.RE
.PP
.SH "Implementation"
.PP
Only data pertinent to this local group is output\&. A new data container containing only group relevant data is returned\&.

.PP
Thus, the data extracted only corresponds to -this- group and is organized by local id numbers\&.
.SH "Application Examples"
.PP
The idea is to extract the property data that corresponds to this group only\&. 
.SS "template<uint32_t dim> \fBPropertyData\fP \fBcsmp::Region\fP< dim >::OutputVariableTo (const char * property) const"

.PP
outputs distributed variable to variable storage container of type \fBPropertyData\fP Any variable is moved to inline storage in the provided container\&.

.PP
\fBAuthor\fP
.RS 4
SKM 2016 
.RE
.PP

.SS "template<uint32_t dim> virtual \fBPLACEMENT\fP \fBcsmp::Region\fP< dim >::Placement () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Local variable storage interface\&. 
.PP
Implements \fBcsmp::ModelSubDomain< dim, Element >\fP\&.
.SS "template<uint32_t dim> size_t \fBcsmp::Region\fP< dim >::RemoveByNumber (std::vector< size_t > & element_ids, std::vector< \fBcsmp::Element\fP< dim > * > & ptrs_to_removed_elements)"

.PP
removes those elements in the region whose id matches one of the numbers contained in vector 'element_ids' Removes target elements from \fBRegion\fP, rebuilding it afterwards\&. Reporting the number of removed elements\&.

.PP
\fBAttention\fP
.RS 4
the elements are not deleted, but pointers to them are returned into the second argument\&. 
.RE
.PP

.SS "template<uint32_t dim> size_t \fBcsmp::Region\fP< dim >::RemoveRange (typename std::vector< \fBcsmp::Element\fP< dim > * >::iterator begin, typename std::vector< \fBcsmp::Element\fP< dim > * >::iterator end)"

.PP
removes those elements from the target region whose pointers matches the ones in the range supplied and subsequently rebuilds the region Removes those element pointers from the region which match the ones in the supplied range\&. 
.SS "template<uint32_t dim> void \fBcsmp::Region\fP< dim >::SetRegion_ID (int32_t region_id = \fRUNSPECIFIED\fP)"

.PP
Sets the \fBRegion\fP ID to \fBModelSubDomain::domain_idx_\fP for all elements of unique region; override as is needed\&. Sets the \fBRegion\fP ID to \fBModelSubDomain::domain_idx_\fP for all elements of the region\&. For unique non-spatially overlapping regions (including lower-dim node sharing regions) the value is used as is\&.

.PP
\fBAttention\fP
.RS 4
This mechanism does not apply to \fBFace\fP or \fBInterFace\fP objects since they have no region ID\&.

.PP
For non-unique regions, no assignment is made! 
.RE
.PP

.SS "template<uint32_t dim> double \fBcsmp::Region\fP< dim >::SurfaceArea () const"

.PP
returns either the lenght of the perimeter (2D) or the surface area of the region (3D) Computes the perimeter (2D) or the surface area (3D) of a model subdomain object\&. To compute the surface area, only elements of dim-1 are considered\&.

.PP
\fBAttention\fP
.RS 4
method assumes that the first nodes in higher-order elements are the corner nodes\&.
.RE
.PP
\fBTodo\fP
.RS 4
SKM: method will produce nonsense if line elements intersect the boundary\&.
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::Region\fP< dim >::ValidVariable (const char * variableName) const\fR [override]\fP, \fR [virtual]\fP"

.PP
checks whether variable placement is compatible with placement on a region 
.PP
Reimplemented from \fBcsmp::ModelSubDomain< dim, Element >\fP\&.
.SS "template<uint32_t dim> double \fBcsmp::Region\fP< dim >::Volume (bool multiply_with_porosity = \fRfalse\fP) const"

.PP
returns either the area of a surface region, the length of a line region or the region's volume Returns the area (2D) or the volume (3D) which is occupied by the sum of elements which constitute the \fBRegion\fP\&.

.PP
If regions consist of elements from multiple space dimensions, the highest ones are used only: Thus, the volume of a 3D group "Model" will exclude potential surface elements\&.
.SH "Implementation"
.PP
Sums elemental areas/volumes as calculated via the element interpolation functions of the current finite elements\&.
.SH "Application Examples"
.PP
For instance, if you want to ask your model which rock volume has been heated above 400oC at a certain timestep\&. 
.SS "template<uint32_t dim> double \fBcsmp::Region\fP< dim >::VolumeIntegral (const char * prop, bool multiply_with_porosity, bool verbose = \fRtrue\fP) const"

.PP
integration over volume elements Integrates variable over all elements contained in the \fBRegion\fP and returns the result as volume integral of the variable\&.

.PP
Optionally, the integrated variable can be multiplied with the 'porosity', assuming that this property is piecewise contant from element to element, i\&.e\&. an element property\&.

.PP
\fBAttention\fP
.RS 4
method should only be applied to volumetric regions\&. 
.RE
.PP

.SS "template<uint32_t dim> double \fBcsmp::Region\fP< dim >::VolumeIntegral_x_Thickness (const char * prop, bool multiply_with_porosity = \fRfalse\fP) const"

.PP
integration over volume and surface elements using thickness attribute (=1 for volume elements) Integrates property over the elements contained in the \fBRegion\fP and returns the volume integral of the variable multiplied with the local element thickness\&. \fBElement\fP thickness must be equal to one for volumetric elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
