.TH "csmp::CornerPointCell" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CornerPointCell \- \fBCornerPointCell\fP provides the necessary functionality to construct valid Finite Elements out of distorted hexahedrons\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CornerPointCell\&.h>\fP
.PP
Inherits \fBcsmp::PolygonCell\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCornerPointCell\fP (\fBPolygonGridManager\fP &)"
.br
.ti -1c
.RI "\fBCornerPointCell\fP (const \fBCornerPointCell\fP &poly)"
.br
.ti -1c
.RI "\fBCornerPointCell\fP & \fBoperator=\fP (const \fBCornerPointCell\fP &poly)"
.br
.ti -1c
.RI "void \fBAssignNode\fP (size_t local_nid, const \fBcsmp::Point\fP< 3U > &pt)"
.br
.RI "initialization of cell ( assign nodes, define topology ) "
.ti -1c
.RI "void \fBInitializeCornerPointCell\fP ()"
.br
.ti -1c
.RI "void \fBAddCornerPointWellCell\fP (size_t face_id_org, size_t face_id_dst)"
.br
.RI "define cell which contains well "
.ti -1c
.RI "void \fBResolveCornerPointCellConflicts\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges)"
.br
.RI "resolve mesh conflicts for cells "
.ti -1c
.RI "void \fBProcessCornerPointCell\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element=false, bool tetra_mesh=false)"
.br
.RI "process cells "
.ti -1c
.RI "void \fBProcessCornerPointRegularCell\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element=false, bool tetra_mesh=false)"
.br
.ti -1c
.RI "void \fBProcessCornerPointDegenerateCell\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element=false, bool tetra_mesh=false)"
.br
.ti -1c
.RI "void \fBProcessCornerPointDegenerateVolumetricCell\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element=false, bool tetra_mesh=false)"
.br
.ti -1c
.RI "void \fBProcessCornerPointDegenerateVolumetricNonOverlappingCell\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element=false, bool tetra_mesh=false)"
.br
.ti -1c
.RI "void \fBProcessCornerPointDegenerateVolumetricOverlappingCell\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element=false, bool tetra_mesh=false)"
.br
.ti -1c
.RI "void \fBProcessCornerPointDegenerateLowDimensionalCell\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element=false, bool tetra_mesh=false)"
.br
.ti -1c
.RI "size_t \fBGetNumFaces\fP (size_t fid) const"
.br
.RI "returns the number of faces that make up the corner-point cell (only in degenerate cells can this be less than 6!) "
.ti -1c
.RI "bool \fBIsVolume\fP () const"
.br
.RI "type of element ( dimension ) "
.ti -1c
.RI "bool \fBIsSurface\fP () const"
.br
.ti -1c
.RI "bool \fBIsLine\fP () const"
.br
.ti -1c
.RI "bool \fBIsPointElement\fP () const"
.br
.ti -1c
.RI "bool \fBIsVolumetricNonOverlapingElement\fP () const"
.br
.RI "type of element ( topology ) "
.ti -1c
.RI "bool \fBIsVolumetricOverlapingElement\fP () const"
.br
.ti -1c
.RI "bool \fBIsLowDimensionalElement\fP () const"
.br
.ti -1c
.RI "size_t \fBGetNumWellSections\fP () const"
.br
.RI "wells info "
.ti -1c
.RI "size_t \fBGetNumWellSectionNodes\fP (size_t eid) const"
.br
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetWellSectionNode\fP (size_t eid, size_t nid) const"
.br
.ti -1c
.RI "size_t \fBGetWellSectionNodeGlobalId\fP (size_t eid, size_t nid) const"
.br
.ti -1c
.RI "size_t \fBGetPillarNodeGlobalIdOriginalOrder\fP (size_t nid) const"
.br
.RI "pillar nodes "
.ti -1c
.RI "size_t \fBGetPillarNodeGlobalIdCustomOrder\fP (size_t nid) const"
.br
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetPillarPointOriginalOrder\fP (size_t nid) const"
.br
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetPillarPointCustomOrder\fP (size_t nid) const"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetPillarNodeOriginalOrder\fP (size_t nid)"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetPillarNodeCustomOrder\fP (size_t nid)"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "prints object state to screen "
.in -1c

Public Member Functions inherited from \fBcsmp::PolygonCell\fP
.in +1c
.ti -1c
.RI "\fBPolygonCell\fP (\fBPolygonGridManager\fP &pgm)"
.br
.RI "custom constructor "
.ti -1c
.RI "\fBPolygonCell\fP (const \fBPolygonCell\fP &cell)"
.br
.ti -1c
.RI "\fBPolygonCell\fP & \fBoperator=\fP (const \fBPolygonCell\fP &cell)"
.br
.ti -1c
.RI "size_t \fBGetElementDim\fP () const"
.br
.RI "cell dim "
.ti -1c
.RI "size_t \fBGetNumElements\fP () const"
.br
.RI "elements info "
.ti -1c
.RI "size_t \fBGetNumElementNodes\fP (size_t eid) const"
.br
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetElementPoint\fP (size_t eid, size_t nid) const"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetElementNode\fP (size_t eid, size_t nid)"
.br
.ti -1c
.RI "size_t \fBGetElementNodeGlobalId\fP (size_t eid, size_t nid) const"
.br
.ti -1c
.RI "const \fBcsmp::CSMP_FEM_TYPE\fP & \fBGetElementType\fP (size_t eid) const"
.br
.ti -1c
.RI "size_t \fBGetElementDim\fP (size_t eid) const"
.br
.ti -1c
.RI "size_t \fBGetNumFaces\fP () const"
.br
.RI "faces info "
.ti -1c
.RI "size_t \fBGetNumSubFaces\fP (size_t fid) const"
.br
.RI "returns into how many faces a particular face is split? "
.ti -1c
.RI "size_t \fBGetNumFaceNodes\fP (size_t fid, size_t sfid) const"
.br
.RI "should this be GetNumSubFaceNodes() where subfaces only exist when a quadrilateral faces is split into triangles? "
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetFacePoint\fP (size_t fid, size_t sfid, size_t nid) const"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetFaceNode\fP (size_t fid, size_t sfid, size_t nid)"
.br
.ti -1c
.RI "size_t \fBGetFaceNodeGlobalId\fP (size_t fid, size_t sfid, size_t nid) const"
.br
.ti -1c
.RI "const \fBcsmp::CSMP_FEM_TYPE\fP & \fBGetFaceType\fP (size_t fid, size_t sfid) const"
.br
.ti -1c
.RI "size_t \fBGetFaceDim\fP (size_t fid, size_t sfid) const"
.br
.ti -1c
.RI "size_t \fBGetNumNodes\fP () const"
.br
.RI "nodes info "
.ti -1c
.RI "size_t \fBGetNodeGlobalIdOriginalOrder\fP (size_t nid) const"
.br
.ti -1c
.RI "size_t \fBGetNodeGlobalIdCustomOrder\fP (size_t nid) const"
.br
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetPointOriginalOrder\fP (size_t nid) const"
.br
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetPointCustomOrder\fP (size_t nid) const"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetNodeOriginalOrder\fP (size_t nid)"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetNodeCustomOrder\fP (size_t nid)"
.br
.ti -1c
.RI "size_t \fBGetNumExtraNodes\fP () const"
.br
.RI "extra nodes info "
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetExtraPoint\fP (size_t nid) const"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetExtraNode\fP (size_t nid)"
.br
.ti -1c
.RI "void \fBAddExtraNode\fP (const \fBcsmp::Point\fP< 3U > &pt)"
.br
.ti -1c
.RI "size_t \fBGetCellCentroidGlobalId\fP () const"
.br
.RI "cell centroid ( if exist: by convention it's a first node of extra nodes arrays ) "
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetCellCentroidPoint\fP () const"
.br
.ti -1c
.RI "\fBGridNode\fP * \fBGetCellCentroidNode\fP ()"
.br
.ti -1c
.RI "size_t \fBGetOriginalNodeId\fP (size_t custom_nid) const"
.br
.RI "face and node id's "
.ti -1c
.RI "size_t \fBGetCustomNodeId\fP (size_t custom_nid) const"
.br
.ti -1c
.RI "size_t \fBGetOriginalFaceId\fP (size_t custom_fid) const"
.br
.ti -1c
.RI "size_t \fBGetCustomFaceId\fP (size_t custom_fid) const"
.br
.ti -1c
.RI "size_t \fBGetNumPolygonFaceNodes\fP (size_t fid) const"
.br
.RI "polygon faces info "
.ti -1c
.RI "size_t \fBGetPolygonFaceNodeLocalId\fP (size_t fid, size_t nid) const"
.br
.ti -1c
.RI "size_t \fBGetPolygonFaceNodeGlobalId\fP (size_t fid, size_t nid) const"
.br
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetPolygonFacePoint\fP (size_t fid, size_t nid) const"
.br
.ti -1c
.RI "\fBGridNode\fP *const \fBGetPolygonFaceNode\fP (size_t fid, size_t nid) const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "print object state to screen "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddWell\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points)"
.br
.RI "add new well "
.ti -1c
.RI "void \fBAddWell\fP (\fBGridNode\fP *n0, \fBGridNode\fP *n1)"
.br
.ti -1c
.RI "void \fBAssignPillarNodesOrder\fP ()"
.br
.RI "initialize elements ( renumber node and eliminate duplicates ) "
.ti -1c
.RI "void \fBInitializeNodes\fP (std::map< \fBcsmp::Point\fP< 3U >, size_t > &cell_nodes)"
.br
.ti -1c
.RI "void \fBCheckNodeOrder\fP ()"
.br
.ti -1c
.RI "void \fBInitializeFaces\fP ()"
.br
.ti -1c
.RI "void \fBCheckFaceOrder\fP ()"
.br
.ti -1c
.RI "void \fBInitializePoly8Element\fP ()"
.br
.ti -1c
.RI "void \fBInitializePoly7Element\fP (const std::map< \fBcsmp::Point\fP< 3U >, size_t > &cell_nodes, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > &face_ordered_points, const std::vector< size_t > &tri_faces, const std::vector< size_t > &quad_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_tri_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_quad_faces, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > &edge_ordered_points, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_edges)"
.br
.ti -1c
.RI "void \fBInitializePoly6Element\fP (const std::map< \fBcsmp::Point\fP< 3U >, size_t > &cell_nodes, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > &face_ordered_points, const std::vector< size_t > &tri_faces, const std::vector< size_t > &quad_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_tri_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_quad_faces, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > &edge_ordered_points, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_edges)"
.br
.ti -1c
.RI "void \fBInitializePoly5Element\fP (const std::map< \fBcsmp::Point\fP< 3U >, size_t > &cell_nodes, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > &face_ordered_points, const std::vector< size_t > &tri_faces, const std::vector< size_t > &quad_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_tri_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_quad_faces, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > &edge_ordered_points, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_edges)"
.br
.ti -1c
.RI "void \fBInitializePoly4Element\fP (const std::vector< size_t > &tri_faces, const std::vector< size_t > &quad_faces)"
.br
.ti -1c
.RI "void \fBInitializePoly3Element\fP ()"
.br
.ti -1c
.RI "void \fBInitializePoly2Element\fP ()"
.br
.ti -1c
.RI "void \fBInitializePoly1Element\fP ()"
.br
.ti -1c
.RI "void \fBGetTopologycalInfo\fP (std::map< \fBcsmp::Point\fP< 3U >, size_t > &cell_nodes, std::set< std::set< \fBcsmp::Point\fP< 3U > > > &unique_faces, std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > &face_ordered_points, std::vector< std::set< \fBcsmp::Point\fP< 3U > > > &face_unique_points, std::vector< size_t > &tri_faces, std::vector< size_t > &quad_faces, std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_tri_faces, std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_quad_faces, std::set< std::set< \fBcsmp::Point\fP< 3U > > > &unique_edges, std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > &edge_ordered_points, std::vector< std::set< \fBcsmp::Point\fP< 3U > > > &edge_unique_points, std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > &point_edges)"
.br
.ti -1c
.RI "void \fBAddQuadFaceCentroids\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges)"
.br
.RI "process cells "
.ti -1c
.RI "void \fBProcessPolyElement\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element)"
.br
.ti -1c
.RI "void \fBProcessPolyNonWellElement\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool add_edge_centroids, bool add_face_centroids, bool add_cell_centroids)"
.br
.ti -1c
.RI "void \fBProcessPolyWellElement\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges)"
.br
.ti -1c
.RI "void \fBProcessPoly8Element\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element, bool tetra_mesh)"
.br
.ti -1c
.RI "void \fBProcessPoly7Element\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element, bool tetra_mesh)"
.br
.ti -1c
.RI "void \fBProcessPoly6Element\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element, bool tetra_mesh)"
.br
.ti -1c
.RI "void \fBProcessPoly5Element\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element, bool tetra_mesh)"
.br
.ti -1c
.RI "void \fBProcessPoly4Element\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element, bool tetra_mesh)"
.br
.ti -1c
.RI "void \fBProcessPoly3Element\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element, bool tetra_mesh)"
.br
.ti -1c
.RI "void \fBProcessPoly2Element\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element, bool tetra_mesh)"
.br
.ti -1c
.RI "void \fBProcessPoly1Element\fP (std::map< std::set< size_t >, \fBGridNode\fP * > &additional_points, std::set< std::set< size_t > > &additional_edges, bool well_element, bool tetra_mesh)"
.br
.ti -1c
.RI "void \fBFinishMeshing\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBcsmp::PolygonCell\fP
.in +1c
.ti -1c
.RI "void \fBAssignPolygonFaceNode\fP (size_t fid, size_t lnid, size_t cell_nid)"
.br
.RI "polygon faces info "
.ti -1c
.RI "void \fBAddPolygonFaceNode\fP (size_t fid, size_t cell_nid)"
.br
.ti -1c
.RI "void \fBClearPolygonFaceNodes\fP (size_t fid)"
.br
.ti -1c
.RI "void \fBResizePolygonFaceNodes\fP (size_t fid, size_t size)"
.br
.ti -1c
.RI "void \fBInitializeNodeOrder\fP (size_t num_nodes)"
.br
.RI "nodes "
.ti -1c
.RI "void \fBAssignNodeOrder\fP (size_t cnid, size_t onid)"
.br
.ti -1c
.RI "void \fBAddCell\fP (const std::pair< \fBcsmp::CSMP_FEM_TYPE\fP, std::vector< \fBGridNode\fP * > > &cell)"
.br
.RI "elements "
.ti -1c
.RI "void \fBEraseCell\fP (size_t position)"
.br
.ti -1c
.RI "void \fBClearCells\fP ()"
.br
.ti -1c
.RI "void \fBInitializeFaceOrder\fP (size_t num_faces)"
.br
.RI "faces "
.ti -1c
.RI "void \fBAssignFaceOrder\fP (size_t cfid, size_t ofid)"
.br
.ti -1c
.RI "void \fBAddFace\fP (size_t fid, const std::pair< \fBcsmp::CSMP_FEM_TYPE\fP, std::vector< \fBGridNode\fP * > > &face)"
.br
.ti -1c
.RI "void \fBEraseFace\fP (size_t fid)"
.br
.ti -1c
.RI "void \fBEraseFace\fP (size_t fid, size_t position)"
.br
.ti -1c
.RI "void \fBClearFaces\fP (size_t fid)"
.br
.ti -1c
.RI "void \fBClearFaces\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::PolygonCell\fP
.in +1c
.ti -1c
.RI "\fBPolygonGridManager\fP * \fBgrid_\fP"
.br
.RI "grid manager TODO: this class is only used by AddExtraNode(), not clear why a pointer to it is needed "
.ti -1c
.RI "size_t \fBnum_nodes_\fP"
.br
.RI "cell nodes data "
.ti -1c
.RI "std::vector< \fBGridNode\fP * > \fBextra_nodes_\fP"
.br
.ti -1c
.RI "std::vector< \fBGridNode\fP * > \fBnodes_\fP"
.br
.ti -1c
.RI "std::vector< \fBGridNode\fP * > \fBnodes_in_custom_order_\fP"
.br
.ti -1c
.RI "std::vector< size_t > \fBcustom_node_order_\fP"
.br
.ti -1c
.RI "std::vector< std::pair< \fBcsmp::CSMP_FEM_TYPE\fP, std::vector< \fBGridNode\fP * > > > \fBelements_\fP"
.br
.RI "cells TODO: what is the physical meaning of this data structure? "
.ti -1c
.RI "size_t \fBnum_faces_\fP"
.br
.RI "faces "
.ti -1c
.RI "std::vector< std::vector< size_t > > \fBface_nodes_\fP"
.br
.ti -1c
.RI "std::vector< std::vector< size_t > > \fBface_nodes_in_custom_order_\fP"
.br
.ti -1c
.RI "std::vector< size_t > \fBcustom_face_order_\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::pair< \fBcsmp::CSMP_FEM_TYPE\fP, std::vector< \fBGridNode\fP * > > > > \fBfaces_\fP"
.br
.RI "faces[i][j] is a 6 x 5 matrix of faces defined by face-type and corresponding node pointers as entries (type-value pairs) "
.in -1c
.SH "Detailed Description"
.PP 
\fBCornerPointCell\fP provides the necessary functionality to construct valid Finite Elements out of distorted hexahedrons\&. 


.PP
\fBAttention\fP
.RS 4
the CornerPoint cell is inherited from the \fBPolygonCell\fP !
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. Manasipov 
.RE
.PP
\fBDate\fP
.RS 4
2015 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void csmp::CornerPointCell::AssignPillarNodesOrder ()\fR [protected]\fP"

.PP
initialize elements ( renumber node and eliminate duplicates ) reorder nodes
.SS "size_t csmp::CornerPointCell::GetNumFaces (size_t fid) const"

.PP
returns the number of faces that make up the corner-point cell (only in degenerate cells can this be less than 6!) function replaces method in base class

.PP
\fBTodo\fP
.RS 4
remove argument because it has no impact on number of faces returned\&. 
.RE
.PP

.SS "void csmp::CornerPointCell::GetTopologycalInfo (std::map< \fBcsmp::Point\fP< 3U >, size_t > & cell_nodes, std::set< std::set< \fBcsmp::Point\fP< 3U > > > & unique_faces, std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > & face_ordered_points, std::vector< std::set< \fBcsmp::Point\fP< 3U > > > & face_unique_points, std::vector< size_t > & tri_faces, std::vector< size_t > & quad_faces, std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_tri_faces, std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_quad_faces, std::set< std::set< \fBcsmp::Point\fP< 3U > > > & unique_edges, std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > & edge_ordered_points, std::vector< std::set< \fBcsmp::Point\fP< 3U > > > & edge_unique_points, std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_edges)\fR [protected]\fP"
hexa cell info

.PP
topological info faces

.PP
edges

.PP
unique edges and faces

.PP
point sets

.PP
initialize faces

.PP
bottom face

.PP
lateral faces

.PP
top face (4,5,6,7)

.PP
edges

.PP
bottom edge

.PP
top edge

.PP
lateral edge

.PP
assign number of unique faces
.SS "void csmp::CornerPointCell::InitializeCornerPointCell ()"
treat degenerate cells

.PP
faces

.PP
edges

.PP
unique edges and faces
.SS "void csmp::CornerPointCell::InitializeFaces ()\fR [protected]\fP"
reorder nodes

.PP
check correspondance of corner point cell enums to original face order
.SS "void csmp::CornerPointCell::InitializeNodes (std::map< \fBcsmp::Point\fP< 3U >, size_t > & cell_nodes)\fR [protected]\fP"
general hexa fem info

.PP
assign pillar nodes order

.PP
initial numbering of nodes

.PP
reorder nodes
.SS "void csmp::CornerPointCell::InitializePoly1Element ()\fR [protected]\fP"
\fBInitializePoly1Element()\fP: Poly1: sketch

.PP
point ( shouldn't be observed ): 
.PP
.nf
pillars(0,1,2,3)

 \\\\  //
  \\\\//
    x
  / | \\
 / / \\ \\
/  / \\  \\

.fi
.PP
 points ( shouldn't be observed)

.PP
SHOULDN'T BE OBSERVED ( only if pillars intersect )
.SS "void csmp::CornerPointCell::InitializePoly2Element ()\fR [protected]\fP"
\fBInitializePoly2Element()\fP: Poly2: sketch

.PP
bar ( shouldn't be observed ): 
.PP
.nf
 \\   /        \\   /
  \\ /          \\ /
0  x____________x 1
  / \\          / \\
 /   \\        /   \\

.fi
.PP
 pillars(0,2) pillars(1,3) bar ( shouldn't be observed)

.PP
SHOULDN'T BE OBSERVED ( only if pillars intersect )
.SS "void csmp::CornerPointCell::InitializePoly3Element ()\fR [protected]\fP"
\fBInitializePoly3Element()\fP: Poly3: sketch

.PP
triangle ( shouldn't be observed ): 
.PP
.nf
   |            |
   |            |
   |            |
0  x____________x 1
   |\\          /|
   | \\        / |
   |  \\      /  |
   |   \\    /   |
   |    \\  /    |

.fi
.PP
 pillar(0) \\/ pillar(1) x2 / \\ / \\ pillars(2,3) triangle ( shouldn't be observed)

.PP
SHOULDN'T BE OBSERVED ( only if pillars intersect )
.SS "void csmp::CornerPointCell::InitializePoly4Element (const std::vector< size_t > & tri_faces, const std::vector< size_t > & quad_faces)\fR [protected]\fP"
\fBInitializePoly4Element()\fP: Poly4: sketch

.PP
quadrilateral: 
.PP
.nf
  |            |
  |            |
  |            |
  |            |
2 x____________x 3
  |\\            \\
  | \\   |        \\   |
  |  \\  |         \\  |
      \\ |          \\ |
       \\|           \\|
      1 x____________x 0
        |            |
        |            |
        |            |

.fi
.PP

.PP
tetrahedron: ( shouldn't be observed ) 
.PP
.nf
      \\\\ pillars (1,4)
       \\\\
        \\\\3
          x
          |\\
          |\\ \\
          | \\  \\

.fi
.PP
 pillar(0) | \\ \\ \\ | \\ \\ | \\ \\ pillar(2)__1_x__________x_2___pillars (2,4) \\ \\ /\\ \\ \\ / \\ \\ \\ / \\ \\ \\ / \\ \\/ 0 \\x \\ \\ pillars (0,1) (1) quadrilateral ( 2 triangles ) (2) tetrahedron ( shouldn't be observed )

.PP
1st case: quadrilateral

.PP
observed and tested

.PP
2nd case: tetrahedron

.PP
SHOULDN'T BE OBSERVED ( only if pillars intersect )
.SS "void csmp::CornerPointCell::InitializePoly5Element (const std::map< \fBcsmp::Point\fP< 3U >, size_t > & cell_nodes, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > & face_ordered_points, const std::vector< size_t > & tri_faces, const std::vector< size_t > & quad_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_tri_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_quad_faces, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > & edge_ordered_points, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_edges)\fR [protected]\fP"
\fBInitializePoly5Element()\fP: Poly5: sketch

.PP
augmented tetrahedron:

.PP
.PP
.nf
  |              |
  |              |
4 x              |
  |              |
  |    |         |    |
  |    |         |    |
  x____|_________x    |
2 |\\   |        1|\\   |
  | \\  |         | \\  |
  |  \\ |         |  \\ |
  |   \\x_________|___\\x
  |  3 |         |    | 0
       |              |
       |              |
       |              |
.fi
.PP

.PP
pyramid: ( shouldn't be observed ) 
.PP
.nf
             pillars(0,1,2,3)

              \\\\  //
               \\\\//
                 x
               / | \\
              / / \\ \\
             /  / \\  \\
            /  /   \\  \\
           /   /    \\  \\
          /   /     \\  \\
         /   /       \\  \\
        /    /       \\   \\
       /    /         \\  \\
      x____ /_________x   \\
   2 / \\   /        1 \\\\   \\
    /   \\  /          \\ \\  \\

.fi
.PP
 pillar(2) \\ / pillar(1) \\ \\ \\x______________\\x 3 / \\ 0 / \\ pillar(3) / \\ pillar(0) point sets

.PP
node id

.PP
hexa cell info

.PP
(1) 2 tetrahedrons or tetrahedron + triangle (2) pyramid ( 2 tetrahedrons ) ( shouldn't be observed )

.PP
1st case: tetrahedron + triangle

.PP
observed and tested

.PP
renumbering nodes 0 - side node

.PP
1,2,3 - bottom quad nodes

.PP
4 - top quad node

.PP
reorder faces

.PP
bottom quad face ( 0321 )

.PP
top quad face ( 0143 )

.PP
tri face ( 124 )

.PP
tri face ( 234 )

.PP
edge faces( 01 and 03 )

.PP
2nd case: pyramid

.PP
SHOULDN'T BE OBSERVED ( only if pillars intersect )

.PP
renumbering nodes 0,1,2,3 - quad face

.PP
4 - apex

.PP
reorder faces

.PP
bottom quad face ( 0321 )

.PP
tri face ( 014 )

.PP
tri face ( 124 )

.PP
tri face ( 234 )

.PP
tri face ( 304 )

.PP
point faces ( 4 )
.SS "void csmp::CornerPointCell::InitializePoly6Element (const std::map< \fBcsmp::Point\fP< 3U >, size_t > & cell_nodes, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > & face_ordered_points, const std::vector< size_t > & tri_faces, const std::vector< size_t > & quad_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_tri_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_quad_faces, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > & edge_ordered_points, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_edges)\fR [protected]\fP"
\fBInitializePoly6Element()\fP: Poly6: sketch

.PP
______ X |\\ | \\ Y | Z

.PP
wedge:

.PP
| | | | | | 5 | x | | /|\\ | | | / | \\ | | | / | \\ | | | / | \\x 2 | | / | / | | |/ | / | | | |/ | | /| / | | / | /| | |/ | / | | 3 x___|___/__x 4 | |\\ | / \\ | | \\ | / \\ | | |/ \\ | | x__________x| 0 | | 1 | | | |

.PP
octahedron:

.PP
| | 5 x | | | x 4  x____|_________x | 3 |\\ | 2|\\ | | \\ | | \\ | | \\ | | \\ | | \\x_________|___\\x | 0 | | | 1 point sets

.PP
node id

.PP
hexa cell info

.PP
(1) wedge ( 3 tetrahedrons ) (2) octahedron ( 2 tetrahedrons )

.PP
1st case: wedge

.PP
observed and tested

.PP
renumbering nodes 0,1,2 - front triangle

.PP
3,4,5 - back triangle

.PP
reorder faces

.PP
bottom quad face ( 0253 )

.PP
front quad face ( 0143 )

.PP
back quad face ( 1452 )

.PP
left tri face ( 012 )

.PP
right tri face ( 354 )

.PP
edge face ( 03 )

.PP
2nd case: octahedron( 4 or 2 tetrahedrons )

.PP
observed and tested

.PP
renumbering nodes 0 - node where quad's collapse

.PP
1,2,3 - bottom quad

.PP
4,5 - top quad nodes

.PP
reorder faces bottom quad face ( 0321 )

.PP
top quad face ( 0425 )

.PP
tri face ( 014 )

.PP
tri face ( 124 )

.PP
tri face ( 235 )

.PP
tri face ( 305 )
.SS "void csmp::CornerPointCell::InitializePoly7Element (const std::map< \fBcsmp::Point\fP< 3U >, size_t > & cell_nodes, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > & face_ordered_points, const std::vector< size_t > & tri_faces, const std::vector< size_t > & quad_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_tri_faces, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_quad_faces, const std::vector< std::vector< \fBcsmp::Point\fP< 3U > > > & edge_ordered_points, const std::map< \fBcsmp::Point\fP< 3U >, std::vector< size_t > > & point_edges)\fR [protected]\fP"
\fBInitializePoly7Element()\fP: Poly7: sketch

.PP
______ X |\\ | \\ Y | Z

.PP
augmented prism:

.PP
5 x____|_________x 4 | |\\ | | | | \\ | | | | \\ | | | | 6 x | | | | | | x____|_________x | 2 |\\ | 1|\\ | | \\ | | \\ | | \\ | | \\ | | \\x_________|___\\x | 3 | | | 0 point sets

.PP
node id

.PP
hexa cell info

.PP
(1) 4 or 5 tetrahedrons

.PP
observed and tested

.PP
renumbering nodes 0 - point where 2 triangles meet

.PP
1,2,3 - bottom quad

.PP
4,5,6 - top quad

.PP
reorder faces bottom quad face ( 0123 )

.PP
left quad face ( 1452 )

.PP
right quad face ( 2563 )

.PP
top quud face ( 0654 )

.PP
left tri face ( 014 )

.PP
right tri face ( 036 )
.SS "void csmp::CornerPointCell::InitializePoly8Element ()\fR [protected]\fP"
\fBInitializePoly8Element()\fP: Poly8: sketch

.PP
______ X |\\ | \\ Y | Z

.PP
hexahedron:

.PP
7 x____|_________x 6 | |\\ | |\\ | | \\ | | \\ | | \\ | | \\ | | 4x_________|___\\x 5 | | | | x____|_________x | 3 |\\ | 2|\\ | | \\ | | \\ | | \\ | | \\ | | \\x_________|___\\x | 0 | | | 1 hexa cell info

.PP
(1) 5 or 6 tetrahedrons observed and tested

.PP
initialize faces

.PP
bottom face0 ( 0321 )

.PP
left face1 ( 3047 )

.PP
front face2 ( 0154 )

.PP
right face3 ( 1265 )

.PP
back face4 ( 2376 )

.PP
top face5 ( 4567 )

.PP
add faces

.PP
node order

.PP
face order
.SS "void csmp::CornerPointCell::Out () const"

.PP
prints object state to screen Prints object state to screen\&. 
.SS "void csmp::CornerPointCell::ProcessPoly1Element (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element, bool tetra_mesh)\fR [protected]\fP"
SHOULDN'T BE OBSERVED ( only if pillars intersect )
.SS "void csmp::CornerPointCell::ProcessPoly2Element (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element, bool tetra_mesh)\fR [protected]\fP"
SHOULDN'T BE OBSERVED ( only if pillars intersect )

.PP
edges and faces are not meshed
.SS "void csmp::CornerPointCell::ProcessPoly3Element (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element, bool tetra_mesh)\fR [protected]\fP"
SHOULDN'T BE OBSERVED ( only if pillars intersect )

.PP
edges and faces are not meshed
.SS "void csmp::CornerPointCell::ProcessPoly4Element (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element, bool tetra_mesh)\fR [protected]\fP"
(1) quadrilateral ( 2 triangles ) (2) tetrahedron ( shouldn't be observed )

.PP
edges and faces are not meshed

.PP
SHOULDN'T BE OBSERVED ( only if pillars intersect multiple times )

.PP
edges and faces are not meshed
.SS "void csmp::CornerPointCell::ProcessPoly5Element (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element, bool tetra_mesh)\fR [protected]\fP"
diagonal nodes

.PP
(1) 2 tetrahedrons or tetrahedron + triangle (2) pyramid ( 2 tetrahedrons ) ( shouldn't be observed )

.PP
edges and faces are not meshed

.PP
SHOULDN'T BE OBSERVED ( only if pillars intersect )

.PP
edges and faces are not meshed
.SS "void csmp::CornerPointCell::ProcessPoly6Element (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element, bool tetra_mesh)\fR [protected]\fP"
(1) wedge ( 3 tetrahedrons ) (2) octahedron ( 2 tetrahedrons )

.PP
edges and faces are not meshed
.SS "void csmp::CornerPointCell::ProcessPoly7Element (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element, bool tetra_mesh)\fR [protected]\fP"
(1) 4 or 5 tetrahedrons

.PP
edges and faces are not meshed
.SS "void csmp::CornerPointCell::ProcessPoly8Element (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element, bool tetra_mesh)\fR [protected]\fP"
(1) 5 or 6 tetrahedrons

.PP
edges and faces are not meshed
.SS "void csmp::CornerPointCell::ProcessPolyElement (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges, bool well_element)\fR [protected]\fP"
cell with well

.PP
cell with meshed edges

.PP
cell with meshed faces

.PP
edges and faces are not meshed
.SS "void csmp::CornerPointCell::ProcessPolyWellElement (std::map< std::set< size_t >, \fBGridNode\fP * > & additional_points, std::set< std::set< size_t > > & additional_edges)\fR [protected]\fP"
add well elements

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
