.TH "csmp::SplitBoundaryElementSets< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SplitBoundaryElementSets< dim > \- container of juxtaposed element pairs for \fBSplitBoundary\fP creation:  

.SH SYNOPSIS
.br
.PP
.PP
Inherits map< pair< string, string >, set< pair< pair< Element< dim > *, size_t >, pair< Element< dim > *, size_t > > > >\&.
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
struct csmp::SplitBoundaryElementSets< dim >"container of juxtaposed element pairs for \fBSplitBoundary\fP creation: 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
