.TH "csmp::CFL_TestData" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CFL_TestData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtime\fP"
.br
.ti -1c
.RI "double \fBCFLmultiplier\fP"
.br
.ti -1c
.RI "double \fBmobilityRatio\fP"
.br
.ti -1c
.RI "double \fBphi\fP"
.br
.ti -1c
.RI "double \fBvelX\fP"
.br
.ti -1c
.RI "double \fBfrontSat\fP"
.br
.ti -1c
.RI "double \fBfrontX\fP"
.br
.ti -1c
.RI "double \fBlenghtInFlowDir\fP"
.br
.ti -1c
.RI "double \fBfrontSat_fw_Derivative\fP"
.br
.ti -1c
.RI "double \fBtestCFL\fP"
.br
.ti -1c
.RI "double \fBanisotropicCFL\fP"
.br
.ti -1c
.RI "double \fBdifference\fP"
.br
.ti -1c
.RI "string \fBtestName\fP"
.br
.ti -1c
.RI "string \fBtestVersion\fP"
.br
.ti -1c
.RI "string \fBinflowBoundary\fP"
.br
.ti -1c
.RI "bool \fBpassed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
