.TH "csmp::LinearElasticityD_VVCase" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::LinearElasticityD_VVCase
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <LinearElasticityD_VVCase\&.h>\fP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Linear Elasticity Test Case D"
.PP
Mesh: Linear Triangles \fBModel\fP: Beam 40x2 m 2D \fBTest\fP: Tensile stress BC: const displ / const disp 
.SH "Criterion: analytical solution: strain, stress, poisson deformation"
.PP

.SH "Member Function Documentation"
.PP 
.SS "void csmp::LinearElasticityD_VVCase::run ()\fR [virtual]\fP"

.PP
Implements \fBcsmp::Test\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
