.TH "csmp::IndexTrackerTestStruct" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::IndexTrackerTestStruct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcsmp::Index\fP \fBkey1_\fP"
.br
.ti -1c
.RI "\fBcsmp::Index\fP \fBkey2_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
