.TH "csmp::IsoparametricLinearLineElement" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::IsoparametricLinearLineElement \- line element with linear interpolation functions for 1D, 2D and 3D models and variable number of integration points  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IsoparametricLinearLineElement\&.h>\fP
.PP
Inherits \fBcsmp::FiniteElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsoparametricLinearLineElement\fP (uint32_t dimensions=2, uint32_t ips=2)"
.br
.ti -1c
.RI "virtual double \fBVolume\fP ()"
.br
.ti -1c
.RI "virtual double \fBInnerRadius\fP ()"
.br
.RI "returns the radius of the largest sphere that could be inscribed in the element "
.ti -1c
.RI "virtual double \fBAspectRatio\fP ()"
.br
.RI "assuming an unscaled unit thickness, the aspect ratio of this element is equivalent to its length "
.ti -1c
.RI "virtual void \fBCornerNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "reports only the corner nodes (0\&.\&.nodes-1) of the element "
.ti -1c
.RI "virtual void \fBMidSideNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "reports only the mid-edge nodes (0\&.\&.nodes-1) of the element "
.ti -1c
.RI "virtual void \fBNodesOfSegment\fP (uint32_t segm_id, std::vector< uint32_t > &snids) const"
.br
.RI "reports the egde nodes (0\&.\&.nodes-1) which can be more than 2 in higher-order elements "
.ti -1c
.RI "virtual uint32_t \fBCornerNodes\fP () const"
.br
.ti -1c
.RI "virtual uint32_t \fBMidSideNodes\fP () const"
.br
.ti -1c
.RI "virtual std::vector< uint32_t > \fBNodesOfFace\fP (uint32_t face_id) const"
.br
.ti -1c
.RI "virtual std::vector< uint32_t > \fBCornerNodesOfFace\fP (uint32_t face_id) const"
.br
.RI "returns the local numbers of the corner nodes of the face "
.ti -1c
.RI "virtual std::vector< uint32_t > \fBNodesConnectedTo\fP (uint32_t node_id) const"
.br
.RI "returns the local numbers of the nodes at the other end of the sgment that the argument node is on "
.ti -1c
.RI "virtual void \fBCounterClockwiseNodes\fP (std::vector< uint32_t > &ids) const"
.br
.ti -1c
.RI "virtual void \fBEdgeLengths\fP (std::vector< double > &vec)"
.br
.RI "reports the lengths of all edges (connections between nodes) in the currrent element "
.ti -1c
.RI "virtual \fBCSMP_FEM_TYPE\fP \fBElementTypeOfFace\fP (uint32_t face) const"
.br
.RI "reports the element type that would match that of its corresponding face "
.ti -1c
.RI "virtual void \fBN\fP (std::vector< double > &FN, const std::vector< double > &xy)"
.br
.ti -1c
.RI "virtual void \fBIntegrationPoint\fP (uint32_t i, std::vector< double > &xyz) const"
.br
.RI "returns the global coordinates of the element integration point "
.ti -1c
.RI "virtual double \fBWeightAtIntegrationPoint\fP (uint32_t i) const"
.br
.RI "returns the integration weight of the desired quadrature point "
.ti -1c
.RI "virtual void \fBN_AtIntegrationPoint\fP (uint32_t IP, std::vector< double > &\fBN\fP)"
.br
.RI "reports the values of the interpolation functions at the given quadrature point "
.ti -1c
.RI "virtual void \fBN_AtBaryCenter\fP (std::vector< double > &\fBN\fP)"
.br
.RI "reports the values of the interpolation functions at the center of gravity of the element "
.ti -1c
.RI "virtual void \fBJacobianAtIntegrationPoint\fP (uint32_t IP)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point "
.ti -1c
.RI "virtual void \fBJacobianAt\fP (const std::vector< double > &rst)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point defined in parametric space (r,s,t) "
.ti -1c
.RI "virtual double \fBJacobianInverse\fP ()"
.br
.RI "inverts current JAC matrix and returns the determinant of J "
.ti -1c
.RI "virtual double \fBJacobianDeterminant\fP ()"
.br
.RI "returns the determinant of the member Jacobian matrix JAC that must have been initialised before "
.ti -1c
.RI "virtual void \fBNr\fP (double r, std::vector< double > &nr) const"
.br
.RI "constant partial derivatives of interpolation functions on the element "
.ti -1c
.RI "virtual void \fBNr\fP (double r, double *nr) const"
.br
.ti -1c
.RI "virtual void \fBdNr\fP (double r, std::vector< double > &dnr) const"
.br
.RI "1D element interpolation functions derivatives N(r)/dr "
.ti -1c
.RI "virtual void \fBdN\fP (\fBDenseMatrix\fP< DM_MIN > &\fBM\fP)"
.br
.ti -1c
.RI "virtual double \fBdN_AtNode\fP (\fBDenseMatrix\fP< DM_MIN > &\fBM\fP, uint32_t node)"
.br
.ti -1c
.RI "virtual double \fBdN_AtIntegrationPoint\fP (\fBDenseMatrix\fP< DM_MIN > &\fBM\fP, uint32_t IP)"
.br
.RI "returns first derivative of interpolaton functions at quadrature point; determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual double \fBdN_AtBarycenter\fP (\fBDenseMatrix\fP< DM_MIN > &\fBM\fP)"
.br
.RI "returns first derivative of interpolaton functions at center of gravity; determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual void \fBIntegralN\fP (\fBDenseMatrix\fP< DM_MIN > &\fBM\fP)"
.br
.ti -1c
.RI "virtual std::vector< double > \fBUnitNormal\fP () const"
.br
.ti -1c
.RI "virtual void \fBUnitNormalToFace\fP (uint32_t face, std::vector< double > &unrml) const"
.br
.RI "2 normals located on the nodes and aligned with the elements "
.ti -1c
.RI "virtual void \fBExtrapolateIntegrationPointVariableToNodes\fP (uint32_t nvars, const std::vector< double > &IVAR, std::vector< double > &NVAR) const"
.br
.RI "using the interpolation functions, the supplied suite of scalar variable values is extrapolated from the Gauss points to the nodes "
.ti -1c
.RI "virtual void \fBOutputNodeDataToVTK\fP (const char *file_name, const char *var_name, \fBDenseMatrix\fP< DM_MIN > &DATA) const"
.br
.RI "prints the current finite element into a visualisation toolkit (VTK) textfile for visual examination "
.ti -1c
.RI "virtual void \fBReferenceCoordinates\fP (\fBDenseMatrix\fP< DM_MIN > &matCoords) const"
.br
.RI "for element types defined using a local coordinate system, returns the node coordinates into the argument matrix "
.in -1c

Public Member Functions inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "\fBFiniteElement\fP (\fBCSMP_FEM_TYPE\fP csp_fem_type, bool isoparametric, bool uses_local_coordinates, uint32_t order_of_shape_functions)"
.br
.ti -1c
.RI "void \fBCurrentID\fP (size_t id)"
.br
.RI "assigns integer value used to avoid repeating the same operation "
.ti -1c
.RI "size_t \fBCurrentID\fP () const"
.br
.RI "returns integer value for comparison to avoid repeating the same operation "
.ti -1c
.RI "uint32_t \fBDim\fP () const"
.br
.RI "return minimum spatial dimension in which this element can exist "
.ti -1c
.RI "uint32_t \fBNodes\fP () const"
.br
.ti -1c
.RI "uint32_t \fBSegments\fP () const"
.br
.RI "returns the number of edges of the FE, i\&.e\&. the number of connections between nodes "
.ti -1c
.RI "uint32_t \fBFaces\fP () const"
.br
.RI "returns the number of sides the finite element has "
.ti -1c
.RI "uint32_t \fBNeighbors\fP () const"
.br
.RI "neighbor elements that may be connected to this FE in its characteristic space "
.ti -1c
.RI "virtual uint32_t \fBNodesPerFace\fP (uint32_t face) const"
.br
.RI "returns how many nodes make up a particular face; some elements have different numbers "
.ti -1c
.RI "uint32_t \fBIntegrationPoints\fP () const"
.br
.RI "returns number of quadrature points used by current integration scheme "
.ti -1c
.RI "uint32_t \fBInterpolation\fP () const"
.br
.RI "returns order of interpolation scheme: linear=1, quadratic=2, cubic=3 "
.ti -1c
.RI "bool \fBIsoparametric\fP () const"
.br
.RI "for numerically integrated elements, reports whether the order of the interpolation functions is the same as that of the shape functions "
.ti -1c
.RI "bool \fBUsesLocalCoordinates\fP () const"
.br
.RI "reports whether element is defined in a local (r,s,t) coordinate system; analytically integrated elements are not "
.ti -1c
.RI "uint32_t \fBOrderOfShapeFunctions\fP () const"
.br
.RI "returns the interpolation order of the shape functions as opposed to the interpolation (basis) functions "
.ti -1c
.RI "bool \fBIsLine\fP () const"
.br
.ti -1c
.RI "bool \fBIsSurface\fP () const"
.br
.ti -1c
.RI "bool \fBIsVolume\fP () const"
.br
.ti -1c
.RI "bool \fBIsSimplex\fP () const"
.br
.RI "true for linear line-, triangle- or tetrahedral elements for which the Jacobian matrix is constant throughout "
.ti -1c
.RI "\fBCSMP_FEM_TYPE\fP \fBElementType\fP () const"
.br
.ti -1c
.RI "virtual void \fBInteriorNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "reports the nodes (0\&.\&.nodes-1) of the element which are not shared with any other element "
.ti -1c
.RI "virtual uint32_t \fBInteriorNodes\fP () const"
.br
.ti -1c
.RI "virtual \fBCSMP_FEM_TYPE\fP \fBElementTypeOfSegment\fP (uint32_t segment) const"
.br
.RI "reports the element type that would match that of its corresponding segment "
.ti -1c
.RI "virtual void \fBUnitNormalAtFaceBarycenter\fP (uint32_t face, std::vector< double > &nrml)"
.br
.RI "computes unit normal to face using a parametric to physical space transformation available in elements with a local coordinate framework "
.ti -1c
.RI "double \fBXYZ\fP (uint32_t i, uint32_t j) const"
.br
.RI "accessor for coordinate matrix which is associated with the element "
.ti -1c
.RI "void \fBXYZ\fP (uint32_t i, uint32_t j, double val)"
.br
.RI "mutator for coordinate matrix which is associated with the element "
.ti -1c
.RI "virtual double \fBdN_At\fP (\fBDenseMatrix\fP< DM_MIN > &, const std::vector< double > &xyz)"
.br
.RI "returns first derivative of interpolaton functions at global point; in isoparametric elements, the determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 1D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr, const std::vector< double > &dns)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 2D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr, const std::vector< double > &dns, const std::vector< double > &dnt)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 3D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual void \fBIntegralNN\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "initialises interpolation function product matrix N^T x N for analytically integrated elements "
.ti -1c
.RI "virtual void \fBIntegraldNdN\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "initialises interpolation function derivatives product matrix DN^T x DN for element where derivatives are constant "
.ti -1c
.RI "virtual void \fBIntegral_dNT_K_dN\fP (\fBDenseMatrix\fP< DM_MIN > &\fBM\fP, \fBDenseMatrix\fP< DM_MIN > &K)"
.br
.ti -1c
.RI "virtual void \fBNrs\fP (double r, double s, std::vector< double > &\fBNRST\fP) const"
.br
.RI "2D element interpolation functions N(r,s) "
.ti -1c
.RI "virtual void \fBdNr\fP (double r, double s, std::vector< double > &\fBDNR\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s)/dr "
.ti -1c
.RI "virtual void \fBdNs\fP (double r, double s, std::vector< double > &\fBDNS\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s)/ds "
.ti -1c
.RI "virtual void \fBNrst\fP (double r, double s, double t, std::vector< double > &\fBNRST\fP) const"
.br
.RI "3D element interpolation functions N(r,s,t) "
.ti -1c
.RI "virtual void \fBdNr\fP (double r, double s, double t, std::vector< double > &\fBDNR\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/dr "
.ti -1c
.RI "virtual void \fBdNs\fP (double r, double s, double t, std::vector< double > &\fBDNS\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/ds "
.ti -1c
.RI "virtual void \fBdNt\fP (double r, double s, double t, std::vector< double > &\fBDNT\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/dt "
.ti -1c
.RI "virtual void \fBOut\fP () const"
.br
.RI "prints finite element properties to screen "
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "static size_t \fBInitialID\fP ()"
.br
.RI "returns ID value set to FEM during construction "
.in -1c

Public Attributes inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBXY\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBJAC\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBJINV\fP"
.br
.ti -1c
.RI "std::vector< double > \fBNRST\fP"
.br
.RI "convenience storage for interpolation function values "
.ti -1c
.RI "std::vector< double > \fBDNR\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< double > \fBDNS\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< double > \fBDNT\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< uint32_t > \fBIDX\fP"
.br
.RI "convenience storage for integer vectors "
.in -1c

Protected Member Functions inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "\fBFiniteElement\fP (const \fBFiniteElement\fP &)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP (\fBFiniteElement\fP &&)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP & \fBoperator=\fP (const \fBFiniteElement\fP &)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP & \fBoperator=\fP (\fBFiniteElement\fP &&)=default"
.br
.ti -1c
.RI "void \fBIsoparametric\fP (bool isoparam)"
.br
.ti -1c
.RI "void \fBUsesLocalCoordinates\fP (bool uses)"
.br
.ti -1c
.RI "void \fBLineElement\fP ()"
.br
.ti -1c
.RI "void \fBSurfaceElement\fP ()"
.br
.ti -1c
.RI "void \fBVolumeElement\fP ()"
.br
.ti -1c
.RI "void \fBElementType\fP (\fBCSMP_FEM_TYPE\fP etype)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "uint32_t \fBdim\fP"
.br
.ti -1c
.RI "uint32_t \fBitp\fP"
.br
.ti -1c
.RI "uint32_t \fBnpf\fP"
.br
.ti -1c
.RI "uint32_t \fBnpe\fP"
.br
.ti -1c
.RI "uint32_t \fBspe\fP"
.br
.ti -1c
.RI "uint32_t \fBfpe\fP"
.br
.ti -1c
.RI "uint32_t \fBepe\fP"
.br
.ti -1c
.RI "uint32_t \fBnne\fP"
.br
.ti -1c
.RI "uint32_t \fBcne\fP"
.br
.ti -1c
.RI "uint32_t \fBgpe\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
line element with linear interpolation functions for 1D, 2D and 3D models and variable number of integration points 


.PP
\fBDate\fP
.RS 4
2001 
.RE
.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double csmp::IsoparametricLinearLineElement::AspectRatio ()\fR [virtual]\fP"

.PP
assuming an unscaled unit thickness, the aspect ratio of this element is equivalent to its length 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "uint32_t csmp::IsoparametricLinearLineElement::CornerNodes () const\fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::CornerNodes (std::vector< uint32_t > & ids) const\fR [virtual]\fP"

.PP
reports only the corner nodes (0\&.\&.nodes-1) of the element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "\fBvector\fP< uint32_t > csmp::IsoparametricLinearLineElement::CornerNodesOfFace (uint32_t face_id) const\fR [virtual]\fP"

.PP
returns the local numbers of the corner nodes of the face 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::dN (\fBDenseMatrix\fP< DM_MIN > & DN)\fR [virtual]\fP"
void \fBIsoparametricLinearLineElement::dN( DenseMatrix<DM_MIN>& M )\fP

.PP
Description:

.PP
Compute derivatives of interpolation functions at corresponding nodes with respect to the global coordinate system\&.

.PP
It is assumed that the element is a straight line in space\&.
.SH "Input Arguments"
.PP
The element is used to obtain the global interpolation of the bar and the interpolation function derivatives at each node are returned into the matrix M of dimensions rows = spatial dimensions x columns = nodes\&.

.PP
The interpolation-function derivative matrix is returned into the second method argument\&.

.PP
\fBTest\fP
.RS 4
: OK 
.RE
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::IsoparametricLinearLineElement::dN_AtBarycenter (\fBDenseMatrix\fP< DM_MIN > & DM)\fR [virtual]\fP"

.PP
returns first derivative of interpolaton functions at center of gravity; determinant of the Jacobian is returned as well 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::IsoparametricLinearLineElement::dN_AtIntegrationPoint (\fBDenseMatrix\fP< DM_MIN > & DM, uint32_t gauss_point)\fR [virtual]\fP"

.PP
returns first derivative of interpolaton functions at quadrature point; determinant of the Jacobian is returned as well 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::IsoparametricLinearLineElement::dN_AtNode (\fBDenseMatrix\fP< DM_MIN > & DN, uint32_t nd)\fR [virtual]\fP"
double \fBIsoparametricLinearLineElement::dN_AtNode( DenseMatrix<DM_MIN>& B, uint32_t nd )\fP; int dof )

.PP
Description:

.PP
.IP "1." 4
Pre-multiplies local interpolation function derivative matrix, B, with node coordinates to obtain the Jacobian matrix, J at the desired node point\&.
.IP "2." 4
The Jacobian matrix J is inverted and multiplied with B to obtain the global interpolation function derivative matrix at the point i (i=0\&.\&.\&.i=gauss points-1)\&.
.PP
.SH "Input Arguments"
.PP
The first argument is a reference to the parent \fBElement\fP object, the second argument is the result matrix, the third argument indicates the gauss point at which the derivative matrix is computed and the fourth argument specifies the degrees of freedom per node, for which the B matrix shall be transformed\&.

.PP
The global interpolation function derivative matrix is returned into the second method argument\&. The method also returns the determinant of the Jacobian matrix since it is often needed in integration procedures\&.

.PP
\fBTest\fP
.RS 4
ok
.RE
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::dNr (double r, std::vector< double > & DNR) const\fR [virtual]\fP"

.PP
1D element interpolation functions derivatives N(r)/dr 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::EdgeLengths (std::vector< double > & vec)\fR [virtual]\fP"

.PP
reports the lengths of all edges (connections between nodes) in the currrent element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "\fBCSMP_FEM_TYPE\fP csmp::IsoparametricLinearLineElement::ElementTypeOfFace (uint32_t face) const\fR [virtual]\fP"

.PP
reports the element type that would match that of its corresponding face 
.PP
\fBTodo\fP
.RS 4
(2-P) Remove typid by name fct 
.RE
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::ExtrapolateIntegrationPointVariableToNodes (uint32_t nvars, const std::vector< double > & IVAR, std::vector< double > & NVAR) const\fR [virtual]\fP"

.PP
using the interpolation functions, the supplied suite of scalar variable values is extrapolated from the Gauss points to the nodes Extrapolation member( gauss points to nodes )

.PP
Expects input vector to be of size nvars * gauss points and in format [ var1 @ gp1, var2 @ gp1, var3 @ gp1, var1 @ gp2, var2 @ gp2, var3 @ gp2 for all gauss points, with nvar == 3 ] 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::IsoparametricLinearLineElement::InnerRadius ()\fR [virtual]\fP"

.PP
returns the radius of the largest sphere that could be inscribed in the element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::IntegralN (\fBDenseMatrix\fP< DM_MIN > & EPROP)\fR [virtual]\fP"
This assumes that the interpolated data are supplied as a symmetric material element property matrix (this analytic expression exists only if the values do not vary over the nodes) EPROP can also contain normal and tangential forces such that 
.PP
.nf
     ft fn

.fi
.PP
 EPROP = -fn ft

.PP
analytic solution, eqn 2\&.9, Cheung et al\&. p\&. 26

.PP
\fBTest\fP
.RS 4
OK1 
.RE
.PP

.SS "void csmp::IsoparametricLinearLineElement::IntegrationPoint (uint32_t i, std::vector< double > & xyz) const\fR [virtual]\fP"

.PP
returns the global coordinates of the element integration point 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::JacobianAt (const std::vector< double > & rst)\fR [virtual]\fP"

.PP
initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point defined in parametric space (r,s,t) 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::JacobianAtIntegrationPoint (uint32_t ip)\fR [virtual]\fP"

.PP
initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::IsoparametricLinearLineElement::JacobianDeterminant ()\fR [virtual]\fP"

.PP
returns the determinant of the member Jacobian matrix JAC that must have been initialised before 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::IsoparametricLinearLineElement::JacobianInverse ()\fR [virtual]\fP"

.PP
inverts current JAC matrix and returns the determinant of J 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "uint32_t csmp::IsoparametricLinearLineElement::MidSideNodes () const\fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::MidSideNodes (std::vector< uint32_t > & ids) const\fR [virtual]\fP"

.PP
reports only the mid-edge nodes (0\&.\&.nodes-1) of the element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::N (std::vector< double > & FN, const std::vector< double > & xy)\fR [virtual]\fP"
void LinearLineElement::N( const Element& e, vector<double>& FN, const vector<double>& xy )

.PP
Description:

.PP
Computes the values of the interpolation functions at the global coordinate 'xyz'\&. Since a Jacobian matrix can only be obtained for points which lie inside the local tetrahedron, such a transformation cannot be performed here\&. Because of this reason global area-coordinate functions are employed to obtain the interpolation function values at the global point\&.

.PP
Note, that the use of global interpolation functions implies that the method only gives highly accurate results if the element boundaries are not curved\&.
.SH "Input Arguments"
.PP
The parent \fBElement\fP, the vector which will hold the interpolation function values, and the coordinate vector 'xyz' in the global coordinate system\&. Note that if the global coordinates given by 'xyz' do not lie within the global extent of the quadratic triangular element, the interpolation function values will no longer add to one and the interpolation will then be erroneous\&.

.PP
The second method argument, the vector FN, will be filled with the interpolation function values as computed at the point 'xyz'\&.
.SH "Implementation"
.PP
The inverse of the Jacobian matrix is found for the global point 'xyz'\&. Then 'xyz' transposed is pre-multiplied with the Jacobian to find the local coordinate pair 'rs' corresponding to 'xyz'\&. Using these local coordinates the interpolation function values are found\&.
.SH "Application Examples"
.PP
To interpolate a property value withing the quadratic triangular element\&.

.PP
tested: 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::N_AtBaryCenter (std::vector< double > & N)\fR [virtual]\fP"

.PP
reports the values of the interpolation functions at the center of gravity of the element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::N_AtIntegrationPoint (uint32_t ip, std::vector< double > & N)\fR [virtual]\fP"

.PP
reports the values of the interpolation functions at the given quadrature point 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "\fBvector\fP< uint32_t > csmp::IsoparametricLinearLineElement::NodesConnectedTo (uint32_t node) const\fR [virtual]\fP"

.PP
returns the local numbers of the nodes at the other end of the sgment that the argument node is on 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "\fBvector\fP< uint32_t > csmp::IsoparametricLinearLineElement::NodesOfFace (uint32_t face_id) const\fR [virtual]\fP"
Method returns into its argument vector the local node number of either of its 2 faces located at its nodes\&. Conventions:
.IP "\(bu" 2
the faces have only a single node
.IP "\(bu" 2
node 0 corresponds to first face 0 opposite to it
.IP "\(bu" 2
node 1 corresponds to second face 1 opposite to node 1 
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::NodesOfSegment (uint32_t segm_id, std::vector< uint32_t > & snids) const\fR [virtual]\fP"

.PP
reports the egde nodes (0\&.\&.nodes-1) which can be more than 2 in higher-order elements 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::Nr (double r, std::vector< double > & nr) const\fR [virtual]\fP"

.PP
constant partial derivatives of interpolation functions on the element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::OutputNodeDataToVTK (const char * file_name, const char * var_name, \fBDenseMatrix\fP< DM_MIN > & DATA) const\fR [virtual]\fP"

.PP
prints the current finite element into a visualisation toolkit (VTK) textfile for visual examination 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::ReferenceCoordinates (\fBDenseMatrix\fP< DM_MIN > & matCoords) const\fR [virtual]\fP"

.PP
for element types defined using a local coordinate system, returns the node coordinates into the argument matrix Returns the reference coordinates of the element\&.

.PP
\fBDenseMatrix<DM_MIN>\fP & matCoords; -> Holds the reference coordinates of the finite element\&. 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "\fBvector\fP< double > csmp::IsoparametricLinearLineElement::UnitNormal () const\fR [virtual]\fP"
here the normal is calculated using the derivative of the shape function at the middle node the normal is the 90o counter-clockwise rotated origin to destination vector\&. 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::IsoparametricLinearLineElement::UnitNormalToFace (uint32_t face, std::vector< double > & unrml) const\fR [virtual]\fP"

.PP
2 normals located on the nodes and aligned with the elements Line element has 2 faces located at the nodes\&. The normals point outward in the direction of the element\&.

.PP
\fBNote\fP
.RS 4
convention: face 1 is located at the first node\&. 
.RE
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::IsoparametricLinearLineElement::Volume ()\fR [virtual]\fP"
double \fBIsoparametricLinearLineElement::Volume()\fP

.PP
Description:
.SH "Input Arguments"
.PP
The finite element which supplies the nodal coordinates from which the area is computed\&.

.PP
\fBReturns\fP
.RS 4
The volume (m3) of the finite element\&.
.RE
.PP
\fBTest\fP
.RS 4
OK 
.RE
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::IsoparametricLinearLineElement::WeightAtIntegrationPoint (uint32_t i) const\fR [virtual]\fP"

.PP
returns the integration weight of the desired quadrature point 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
