.TH "csmp::IntegralEquation< dim, VARIABLE_SET >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::IntegralEquation< dim, VARIABLE_SET >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IntegralEquation\&.h>\fP
.PP
Inherits VARIABLE_SET\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::map< \fBOperation\fP, \fBMatrixOperator\fP< dim > * >::const_iterator \fBMatrixOperatorConstIterator\fP"
.br
.ti -1c
.RI "typedef std::map< \fBOperation\fP, \fBVectorOperator\fP< dim > * >::const_iterator \fBVectorOperatorConstIterator\fP"
.br
.ti -1c
.RI "typedef std::map< std::string, \fBMatrixOperator\fP< dim > * >::const_iterator \fBPostProcessingOperatorConstIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntegralEquation\fP (const \fBPropertyDatabase\fP< dim > &)"
.br
.RI "advection with sources and sinks "
.ti -1c
.RI "\fBIntegralEquation\fP (const \fBPropertyDatabase\fP< dim > &, const std::set< csmp::ADE_TERM > &ADE_components)"
.br
.RI "builds equation for one of the available options and using the variables supplied in the set "
.ti -1c
.RI "\fB~IntegralEquation\fP ()"
.br
.RI "deletes all copies of MathOperators "
.ti -1c
.RI "void \fBAdd\fP (const \fBOperation\fP &, \fBMatrixOperator\fP< dim > *)"
.br
.RI "operators are added in the user-specified sequence (add, subtract, multiply, specified in operators "
.ti -1c
.RI "void \fBAdd\fP (const \fBOperation\fP &, \fBVectorOperator\fP< dim > *)"
.br
.ti -1c
.RI "void \fBAddPostProcess\fP (\fBMatrixOperator\fP< dim > *)"
.br
.RI "post-processing operations involving the solution variable (these will never have to be modified) "
.ti -1c
.RI "MatrixOperatorConstIterator \fBLHS_OperatorsBegin\fP () const"
.br
.ti -1c
.RI "MatrixOperatorConstIterator \fBLHS_OperatorsEnd\fP () const"
.br
.ti -1c
.RI "VectorOperatorConstIterator \fBRHS_OperatorsBegin\fP () const"
.br
.ti -1c
.RI "VectorOperatorConstIterator \fBRHS_OperatorsEnd\fP () const"
.br
.ti -1c
.RI "PostProcessingOperatorConstIterator \fBPostProcessingOperatorsBegin\fP () const"
.br
.ti -1c
.RI "PostProcessingOperatorConstIterator \fBPostProcessingOperatorsEnd\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const VARIABLE_SET & \fBNotation\fP"
.br
.RI "access to the \fBINDEX\fP keys for the variables used in this equation "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, class VARIABLE_SET>
.br
class csmp::IntegralEquation< dim, VARIABLE_SET >"To build an equation add terms in the desired sequence into the LHS and RHS\&.

.PP
This class depends on the supply of \fBINDEX\fP keys for the transport problem, from the USER template parameter\&.

.PP
\fBIntegralEquation\fP (policy) Operations
.IP "\(bu" 2
Add( operator& )
.IP "\(bu" 2
Subtract( operator& )
.IP "\(bu" 2
MultiplyWith( operator& )
.IP "\(bu" 2
AddPostProcess( domain ); Attributes
.IP "\(bu" 2
map<pair<OperatorLHS,enum:Operation> >;
.IP "\(bu" 2
map<pair<OperatorRHS,enum:Operation> >;
.IP "\(bu" 2
enum OPERATION {}; 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim, class VARIABLE_SET> \fBcsmp::IntegralEquation\fP< dim, VARIABLE_SET >::IntegralEquation (const \fBPropertyDatabase\fP< dim > & pref)\fR [explicit]\fP"

.PP
advection with sources and sinks 
.PP
.nf
Default constructor - advection with sources and sinks\&.

.fi
.PP

.PP
upstream weighted first-order space-time fluxes 
.SS "template<uint32_t dim, class VARIABLE_SET> \fBcsmp::IntegralEquation\fP< dim, VARIABLE_SET >::~\fBIntegralEquation\fP ()"

.PP
deletes all copies of MathOperators delete all dynamic copies of MathOperators from the heap 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, class VARIABLE_SET> void \fBcsmp::IntegralEquation\fP< dim, VARIABLE_SET >::Add (const \fBOperation\fP & operation, \fBMatrixOperator\fP< dim > * mop)"

.PP
operators are added in the user-specified sequence (add, subtract, multiply, specified in operators operators are added in the user-specified sequence (add, subtract, multiply, specified in operators

.PP
\begin{ \mathbf{u}_{\alpha} = -\frac{k_{r\alpha}}{\mu_\alpha} \mathbb{K}\left( \nabla p_\alpha - \rho_\alpha \mathbf{g}\right)\end{ \mathbf{u} 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
