.TH "csmp::EclipseModelSettings" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::EclipseModelSettings \- PROPS and several other specifications from the RUNSPECS file record\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <EclipseInterface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEclipseModelSettings\fP (const std::string &mesh_file_prefix)"
.br
.ti -1c
.RI "void \fBMeshSetup\fP (bool exclude_inactive_cells, bool tetra_mesh, bool create_boundaries=true)"
.br
.ti -1c
.RI "void \fBMeshSetup\fP (const std::string &regions_file_prefix, bool exclude_inactive_cells, bool tetra_mesh, bool create_boundaries=true)"
.br
.ti -1c
.RI "void \fBMeshSetup\fP (const std::set< std::string > &regions, bool exclude_inactive_cells, bool tetra_mesh, bool create_boundaries=true)"
.br
.ti -1c
.RI "void \fBSatNumPropertySetup\fP (const std::string &prop_name='satnum', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::ELEMENT)"
.br
.RI "properties setup "
.ti -1c
.RI "void \fBPvtNumPropertySetup\fP (const std::string &prop_name='ptvnum', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::ELEMENT)"
.br
.ti -1c
.RI "void \fBRockNumPropertySetup\fP (const std::string &prop_name='rocktype', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::ELEMENT)"
.br
.RI "usually this is called "rocknum" "
.ti -1c
.RI "void \fBEqlNumPropertySetup\fP (const std::string &prop_name='eqlnum', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::ELEMENT)"
.br
.ti -1c
.RI "void \fBFipNumPropertySetup\fP (const std::string &prop_name='fipnum', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::ELEMENT)"
.br
.ti -1c
.RI "void \fBNtgPropertySetup\fP (const std::string &prop_name='ntg', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::ELEMENT)"
.br
.ti -1c
.RI "void \fBPoroPropertySetup\fP (const std::string &prop_name='porosity', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::ELEMENT)"
.br
.ti -1c
.RI "void \fBPermPropertySetup\fP (const std::string &prop_name='permeability', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::ELEMENT, const std::string &prop_unit='m2')"
.br
.ti -1c
.RI "void \fBPressurePropertySetup\fP (const std::string &prop_name='pressure', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::NODE, const std::string &prop_unit='Pa')"
.br
.ti -1c
.RI "void \fBSwatPropertySetup\fP (const std::string &prop_name='saturation water', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::NODE)"
.br
.ti -1c
.RI "void \fBSoilPropertySetup\fP (const std::string &prop_name='saturation oil', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::NODE)"
.br
.ti -1c
.RI "void \fBSgasPropertySetup\fP (const std::string &prop_name='saturation gas', const \fB::csmp::VARIABLE_TYPE\fP &prop_type=::csmp::SCALAR, const \fB::csmp::PLACEMENT\fP &prop_place=::csmp::NODE)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmesh_file_prefix_\fP"
.br
.RI "mesh setting "
.ti -1c
.RI "std::string \fBregions_file_prefix_\fP"
.br
.RI "regions file prefix "
.ti -1c
.RI "bool \fBcreate_boundaries_\fP"
.br
.RI "true = create boundaries around model, false = do not create boundaries "
.ti -1c
.RI "std::set< std::string > \fBregions_\fP"
.br
.RI "name of regions to be used "
.ti -1c
.RI "bool \fBtetra_mesh_\fP"
.br
.RI "tetrahedral mesh "
.ti -1c
.RI "bool \fBexclude_inactive_cells_\fP"
.br
.RI "do not consider inactive cells "
.ti -1c
.RI "std::map< int, \fBcsmp::Parameter\fP > \fBproperties_\fP"
.br
.RI "property settings "
.in -1c
.SH "Detailed Description"
.PP 
PROPS and several other specifications from the RUNSPECS file record\&. 


.PP
\fBAuthor\fP
.RS 4
R\&. Manasipov 
.RE
.PP
\fBDate\fP
.RS 4
2014-2015
.RE
.PP
ASCII file interface to read corner point grid from ( *\&.GRDECL, *\&.grdecl ) file\&. In order to build a native CSMP \fBModel\fP the provided grid information is assigned to \fBVSet\fP and \fBModelTopology\fP objects\&. The regions that are constructed by default are: % regions which include all the cells MATRIX MATRIX_ACTIVE MATRIX_INACTIVE % and specific fault regions

.PP
In addition to grid information the properties such as: 'permeability', 'porosity', 'pressure', 'saturation' can be readed as well\&. User is able to control property type and placement\&. For example one can create tensor or scalar permeability variables or to place 'pressure' at the nodes or elements\&.

.PP
.PP
.nf
KEYWORDS that can be currently handled:

\-\-\- Grid
DIMENS
DX
DY
DZ
SPECGRID
TOPS
COORD
ZCORN
FAULTS

\-\-\- Regions
ACTNUM
SATNUM
PVTNUM
ROCKNUM
EQLNUM

\-\-\- Props
NTG
PORO
PERMX            
well\&.well_data_\&.push_back( wellcomp );
PERMY
PERMZ
PRESSURE
SWAT
SOIL
SGAS

\-\-\- Runspec
WELSPECS
COMPDAT (relies on WELLSPECS and can therefore not be defined in isolation)
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "std::string csmp::EclipseModelSettings::mesh_file_prefix_"

.PP
mesh setting name of model or main mesh file 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
