.TH "csmp::ErfDensity" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ErfDensity \- error function based mesh size variation  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <LineElementMesher\&.h>\fP
.PP
Inherits \fBcsmp::MeshDensity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErfDensity\fP (double a=3\&.0, double b=1\&.0)"
.br
.ti -1c
.RI "virtual double \fBoperator()\fP (double x)"
.br
.ti -1c
.RI "void \fBSetA\fP (double)"
.br
.ti -1c
.RI "void \fBSetB\fP (double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
error function based mesh size variation 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::ErfDensity::operator() (double x)\fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::MeshDensity\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
