.TH "csmp::LinearTriangle" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::LinearTriangle \- Straight-sided, analytically integrated triangular element for 2D calculations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <LinearTriangle\&.h>\fP
.PP
Inherits \fBcsmp::FiniteElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBVolume\fP ()"
.br
.RI "computes and returns the volume of the element which is an area for a surface- and a length for a line element "
.ti -1c
.RI "virtual double \fBAspectRatio\fP ()"
.br
.RI "returns the ratio between the maximum and minimum spatial extent of the element "
.ti -1c
.RI "virtual double \fBInnerRadius\fP ()"
.br
.RI "returns the radius of the largest sphere that could be inscribed in the element "
.ti -1c
.RI "virtual void \fBEdgeLengths\fP (std::vector< double > &vec)"
.br
.RI "reports the lengths of all edges (connections between nodes) in the currrent element "
.ti -1c
.RI "virtual void \fBNodesOfSegment\fP (uint32_t segm_id, std::vector< uint32_t > &snids) const"
.br
.RI "segments are numbered like faces "
.ti -1c
.RI "virtual std::vector< uint32_t > \fBNodesOfFace\fP (uint32_t face_id) const"
.br
.ti -1c
.RI "virtual std::vector< uint32_t > \fBCornerNodesOfFace\fP (uint32_t face_id) const"
.br
.RI "returns the local numbers of the corner nodes of the face "
.ti -1c
.RI "virtual std::vector< uint32_t > \fBNodesConnectedTo\fP (uint32_t node_id) const"
.br
.RI "returns the local numbers of the nodes at the other end of the sgment that the argument node is on "
.ti -1c
.RI "virtual uint32_t \fBCornerNodes\fP () const"
.br
.ti -1c
.RI "virtual void \fBCornerNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "The linear triangle is numbered counter-clockwise by default\&. "
.ti -1c
.RI "virtual \fBCSMP_FEM_TYPE\fP \fBElementTypeOfFace\fP (uint32_t face) const"
.br
.RI "reports the element type that would match that of its corresponding face "
.ti -1c
.RI "virtual \fBCSMP_FEM_TYPE\fP \fBElementTypeOfSegment\fP (uint32_t) const"
.br
.RI "reports the element type that would match that of its corresponding segment "
.ti -1c
.RI "virtual void \fBUnitNormalToFace\fP (uint32_t face, std::vector< double > &unrml) const"
.br
.RI "outward-pointing normals "
.ti -1c
.RI "virtual void \fBN\fP (std::vector< double > &N, const std::vector< double > &xyz)"
.br
.RI "element interpolation functions at point in global coordinates "
.ti -1c
.RI "virtual void \fBN_AtBaryCenter\fP (std::vector< double > &\fBN\fP)"
.br
.RI "reports the values of the interpolation functions at the center of gravity of the element "
.ti -1c
.RI "virtual void \fBdN\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "first derivatives of element interpolation functions "
.ti -1c
.RI "virtual double \fBdN_At\fP (\fBDenseMatrix\fP< DM_MIN > &, const std::vector< double > &xyz)"
.br
.ti -1c
.RI "virtual double \fBdN_AtBarycenter\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.ti -1c
.RI "virtual void \fBIntegralNN\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "integrals over interpolation functions products returned into \fBDenseMatrix\fP "
.ti -1c
.RI "virtual void \fBOutputNodeDataToVTK\fP (const char *file_name, const char *var_name, \fBDenseMatrix\fP< DM_MIN > &DATA) const"
.br
.RI "prints the current finite element into a visualisation toolkit (VTK) textfile for visual examination "
.in -1c

Public Member Functions inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "\fBFiniteElement\fP (\fBCSMP_FEM_TYPE\fP csp_fem_type, bool isoparametric, bool uses_local_coordinates, uint32_t order_of_shape_functions)"
.br
.ti -1c
.RI "void \fBCurrentID\fP (size_t id)"
.br
.RI "assigns integer value used to avoid repeating the same operation "
.ti -1c
.RI "size_t \fBCurrentID\fP () const"
.br
.RI "returns integer value for comparison to avoid repeating the same operation "
.ti -1c
.RI "uint32_t \fBDim\fP () const"
.br
.RI "return minimum spatial dimension in which this element can exist "
.ti -1c
.RI "uint32_t \fBNodes\fP () const"
.br
.ti -1c
.RI "uint32_t \fBSegments\fP () const"
.br
.RI "returns the number of edges of the FE, i\&.e\&. the number of connections between nodes "
.ti -1c
.RI "uint32_t \fBFaces\fP () const"
.br
.RI "returns the number of sides the finite element has "
.ti -1c
.RI "uint32_t \fBNeighbors\fP () const"
.br
.RI "neighbor elements that may be connected to this FE in its characteristic space "
.ti -1c
.RI "virtual uint32_t \fBNodesPerFace\fP (uint32_t face) const"
.br
.RI "returns how many nodes make up a particular face; some elements have different numbers "
.ti -1c
.RI "uint32_t \fBIntegrationPoints\fP () const"
.br
.RI "returns number of quadrature points used by current integration scheme "
.ti -1c
.RI "uint32_t \fBInterpolation\fP () const"
.br
.RI "returns order of interpolation scheme: linear=1, quadratic=2, cubic=3 "
.ti -1c
.RI "bool \fBIsoparametric\fP () const"
.br
.RI "for numerically integrated elements, reports whether the order of the interpolation functions is the same as that of the shape functions "
.ti -1c
.RI "bool \fBUsesLocalCoordinates\fP () const"
.br
.RI "reports whether element is defined in a local (r,s,t) coordinate system; analytically integrated elements are not "
.ti -1c
.RI "uint32_t \fBOrderOfShapeFunctions\fP () const"
.br
.RI "returns the interpolation order of the shape functions as opposed to the interpolation (basis) functions "
.ti -1c
.RI "bool \fBIsLine\fP () const"
.br
.ti -1c
.RI "bool \fBIsSurface\fP () const"
.br
.ti -1c
.RI "bool \fBIsVolume\fP () const"
.br
.ti -1c
.RI "bool \fBIsSimplex\fP () const"
.br
.RI "true for linear line-, triangle- or tetrahedral elements for which the Jacobian matrix is constant throughout "
.ti -1c
.RI "\fBCSMP_FEM_TYPE\fP \fBElementType\fP () const"
.br
.ti -1c
.RI "virtual void \fBMidSideNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "reports only the mid-edge nodes (0\&.\&.nodes-1) of the element "
.ti -1c
.RI "virtual void \fBInteriorNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "reports the nodes (0\&.\&.nodes-1) of the element which are not shared with any other element "
.ti -1c
.RI "virtual uint32_t \fBMidSideNodes\fP () const"
.br
.ti -1c
.RI "virtual uint32_t \fBInteriorNodes\fP () const"
.br
.ti -1c
.RI "virtual std::vector< double > \fBUnitNormal\fP () const"
.br
.RI "returns unit normal to element where it makes sense (line and surface elements); expects XY matrix to be initialised with node coordinates "
.ti -1c
.RI "virtual void \fBUnitNormalAtFaceBarycenter\fP (uint32_t face, std::vector< double > &nrml)"
.br
.RI "computes unit normal to face using a parametric to physical space transformation available in elements with a local coordinate framework "
.ti -1c
.RI "double \fBXYZ\fP (uint32_t i, uint32_t j) const"
.br
.RI "accessor for coordinate matrix which is associated with the element "
.ti -1c
.RI "void \fBXYZ\fP (uint32_t i, uint32_t j, double val)"
.br
.RI "mutator for coordinate matrix which is associated with the element "
.ti -1c
.RI "virtual void \fBReferenceCoordinates\fP (\fBDenseMatrix\fP< DM_MIN > &matCoords) const"
.br
.RI "for element types defined using a local coordinate system, returns the node coordinates into the argument matrix "
.ti -1c
.RI "virtual void \fBExtrapolateIntegrationPointVariableToNodes\fP (uint32_t nvars, const std::vector< double > &IVAR, std::vector< double > &NVAR) const"
.br
.RI "using the interpolation functions, the supplied suite of scalar variable values is extrapolated from the Gauss points to the nodes "
.ti -1c
.RI "virtual void \fBIntegrationPoint\fP (uint32_t i, std::vector< double > &xyz) const"
.br
.RI "returns the global coordinates of the element integration point "
.ti -1c
.RI "virtual double \fBWeightAtIntegrationPoint\fP (uint32_t i) const"
.br
.RI "returns the integration weight of the desired quadrature point "
.ti -1c
.RI "virtual void \fBN_AtIntegrationPoint\fP (uint32_t ip, std::vector< double > &\fBN\fP)"
.br
.RI "reports the values of the interpolation functions at the given quadrature point "
.ti -1c
.RI "virtual double \fBdN_AtIntegrationPoint\fP (\fBDenseMatrix\fP< DM_MIN > &, uint32_t gauss_point)"
.br
.RI "returns first derivative of interpolaton functions at quadrature point; determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual double \fBdN_AtNode\fP (\fBDenseMatrix\fP< DM_MIN > &, uint32_t node)"
.br
.RI "returns first derivative of interpolaton functions at node; determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual void \fBJacobianAtIntegrationPoint\fP (uint32_t ip)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point "
.ti -1c
.RI "virtual void \fBJacobianAt\fP (const std::vector< double > &rst)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point defined in parametric space (r,s,t) "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 1D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr, const std::vector< double > &dns)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 2D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr, const std::vector< double > &dns, const std::vector< double > &dnt)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 3D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual double \fBJacobianInverse\fP ()"
.br
.RI "initializes the member matrix JINV "
.ti -1c
.RI "virtual double \fBJacobianDeterminant\fP ()"
.br
.RI "returns the determinant of the member Jacobian matrix JAC that must have been initialised before "
.ti -1c
.RI "virtual void \fBIntegraldNdN\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "initialises interpolation function derivatives product matrix DN^T x DN for element where derivatives are constant "
.ti -1c
.RI "virtual void \fBIntegral_dNT_K_dN\fP (\fBDenseMatrix\fP< DM_MIN > &\fBM\fP, \fBDenseMatrix\fP< DM_MIN > &K)"
.br
.ti -1c
.RI "virtual void \fBNr\fP (double r, std::vector< double > &\fBNRST\fP) const"
.br
.RI "1D element interpolation functions N(r) "
.ti -1c
.RI "virtual void \fBdNr\fP (double r, std::vector< double > &\fBDNR\fP) const"
.br
.RI "1D element interpolation functions derivatives N(r)/dr "
.ti -1c
.RI "virtual void \fBNrs\fP (double r, double s, std::vector< double > &\fBNRST\fP) const"
.br
.RI "2D element interpolation functions N(r,s) "
.ti -1c
.RI "virtual void \fBdNr\fP (double r, double s, std::vector< double > &\fBDNR\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s)/dr "
.ti -1c
.RI "virtual void \fBdNs\fP (double r, double s, std::vector< double > &\fBDNS\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s)/ds "
.ti -1c
.RI "virtual void \fBNrst\fP (double r, double s, double t, std::vector< double > &\fBNRST\fP) const"
.br
.RI "3D element interpolation functions N(r,s,t) "
.ti -1c
.RI "virtual void \fBdNr\fP (double r, double s, double t, std::vector< double > &\fBDNR\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/dr "
.ti -1c
.RI "virtual void \fBdNs\fP (double r, double s, double t, std::vector< double > &\fBDNS\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/ds "
.ti -1c
.RI "virtual void \fBdNt\fP (double r, double s, double t, std::vector< double > &\fBDNT\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/dt "
.ti -1c
.RI "virtual void \fBOut\fP () const"
.br
.RI "prints finite element properties to screen "
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "static size_t \fBInitialID\fP ()"
.br
.RI "returns ID value set to FEM during construction "
.in -1c

Public Attributes inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBXY\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBJAC\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBJINV\fP"
.br
.ti -1c
.RI "std::vector< double > \fBNRST\fP"
.br
.RI "convenience storage for interpolation function values "
.ti -1c
.RI "std::vector< double > \fBDNR\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< double > \fBDNS\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< double > \fBDNT\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< uint32_t > \fBIDX\fP"
.br
.RI "convenience storage for integer vectors "
.in -1c

Protected Member Functions inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "\fBFiniteElement\fP (const \fBFiniteElement\fP &)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP (\fBFiniteElement\fP &&)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP & \fBoperator=\fP (const \fBFiniteElement\fP &)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP & \fBoperator=\fP (\fBFiniteElement\fP &&)=default"
.br
.ti -1c
.RI "void \fBIsoparametric\fP (bool isoparam)"
.br
.ti -1c
.RI "void \fBUsesLocalCoordinates\fP (bool uses)"
.br
.ti -1c
.RI "void \fBLineElement\fP ()"
.br
.ti -1c
.RI "void \fBSurfaceElement\fP ()"
.br
.ti -1c
.RI "void \fBVolumeElement\fP ()"
.br
.ti -1c
.RI "void \fBElementType\fP (\fBCSMP_FEM_TYPE\fP etype)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::FiniteElement\fP
.in +1c
.ti -1c
.RI "uint32_t \fBdim\fP"
.br
.ti -1c
.RI "uint32_t \fBitp\fP"
.br
.ti -1c
.RI "uint32_t \fBnpf\fP"
.br
.ti -1c
.RI "uint32_t \fBnpe\fP"
.br
.ti -1c
.RI "uint32_t \fBspe\fP"
.br
.ti -1c
.RI "uint32_t \fBfpe\fP"
.br
.ti -1c
.RI "uint32_t \fBepe\fP"
.br
.ti -1c
.RI "uint32_t \fBnne\fP"
.br
.ti -1c
.RI "uint32_t \fBcne\fP"
.br
.ti -1c
.RI "uint32_t \fBgpe\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Straight-sided, analytically integrated triangular element for 2D calculations\&. 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::LinearTriangle::AspectRatio ()\fR [virtual]\fP"

.PP
returns the ratio between the maximum and minimum spatial extent of the element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "virtual uint32_t csmp::LinearTriangle::CornerNodes () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::CornerNodes (std::vector< uint32_t > & ids) const\fR [virtual]\fP"

.PP
The linear triangle is numbered counter-clockwise by default\&. clearly all nodes are corner nodes 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "\fBvector\fP< uint32_t > csmp::LinearTriangle::CornerNodesOfFace (uint32_t face_id) const\fR [virtual]\fP"

.PP
returns the local numbers of the corner nodes of the face 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::dN (\fBDenseMatrix\fP< DM_MIN > & B)\fR [virtual]\fP"

.PP
first derivatives of element interpolation functions 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::LinearTriangle::dN_At (\fBDenseMatrix\fP< DM_MIN > & B, const std::vector< double > & xyz)\fR [virtual]\fP"
The interpolation function derivates are constant inside of this linear element\&. Thus, the location of the point itself does not have to be considered\&. The method returns the element area\&. 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::LinearTriangle::dN_AtBarycenter (\fBDenseMatrix\fP< DM_MIN > & B)\fR [virtual]\fP"
The interpolation function derivates are constant inside of this linear element\&. The method returns the element area\&. 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::EdgeLengths (std::vector< double > & vec)\fR [virtual]\fP"

.PP
reports the lengths of all edges (connections between nodes) in the currrent element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "\fBCSMP_FEM_TYPE\fP csmp::LinearTriangle::ElementTypeOfFace (uint32_t face) const\fR [virtual]\fP"

.PP
reports the element type that would match that of its corresponding face 
.PP
\fBTodo\fP
.RS 4
(2-P) Remove typid by name fct 
.RE
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "virtual \fBCSMP_FEM_TYPE\fP csmp::LinearTriangle::ElementTypeOfSegment (uint32_t segment) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
reports the element type that would match that of its corresponding segment 
.PP
\fBTodo\fP
.RS 4
(2-P) Remove typid by name fct 
.RE
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::LinearTriangle::InnerRadius ()\fR [virtual]\fP"

.PP
returns the radius of the largest sphere that could be inscribed in the element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::IntegralNN (\fBDenseMatrix\fP< DM_MIN > & CE)\fR [virtual]\fP"

.PP
integrals over interpolation functions products returned into \fBDenseMatrix\fP 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::N (std::vector< double > & N, const std::vector< double > & xyz)\fR [virtual]\fP"

.PP
element interpolation functions at point in global coordinates 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::N_AtBaryCenter (std::vector< double > & N)\fR [virtual]\fP"

.PP
reports the values of the interpolation functions at the center of gravity of the element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "std::vector< uint32_t > csmp::LinearTriangle::NodesConnectedTo (uint32_t node_id) const\fR [virtual]\fP"

.PP
returns the local numbers of the nodes at the other end of the sgment that the argument node is on 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "\fBvector\fP< uint32_t > csmp::LinearTriangle::NodesOfFace (uint32_t face_id) const\fR [virtual]\fP"
For this element, the faces are numbered such that face 0 lies opposite of node 0, face 1 node 1 etc\&. 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::NodesOfSegment (uint32_t segm_id, std::vector< uint32_t > & snids) const\fR [virtual]\fP"

.PP
segments are numbered like faces 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::OutputNodeDataToVTK (const char * file_name, const char * var_name, \fBDenseMatrix\fP< DM_MIN > & DATA) const\fR [virtual]\fP"

.PP
prints the current finite element into a visualisation toolkit (VTK) textfile for visual examination 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "void csmp::LinearTriangle::UnitNormalToFace (uint32_t face, std::vector< double > & unrml) const\fR [virtual]\fP"

.PP
outward-pointing normals 
.PP
\fBAuthor\fP
.RS 4
SKM 18/2/2016 
.RE
.PP

.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.
.SS "double csmp::LinearTriangle::Volume ()\fR [virtual]\fP"

.PP
computes and returns the volume of the element which is an area for a surface- and a length for a line element 
.PP
Reimplemented from \fBcsmp::FiniteElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
