.TH "csmp::GridNode" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::GridNode
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PolygonGrid\&.h>\fP
.PP
Inherits \fBcsmp::Point< 3U >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridNode\fP (size_t index, const \fBPoint\fP< 3U > &)"
.br
.ti -1c
.RI "\fBGridNode\fP (const \fBGridNode\fP &)"
.br
.ti -1c
.RI "\fBGridNode\fP & \fBoperator=\fP (const \fBGridNode\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBGridNode\fP &)"
.br
.ti -1c
.RI "size_t \fBGetIdx\fP () const"
.br
.ti -1c
.RI "bool \fBIsNullIdx\fP () const"
.br
.ti -1c
.RI "const \fBcsmp::Point\fP< 3U > & \fBGetPoint\fP () const"
.br
.ti -1c
.RI "\fBcsmp::Point\fP< 3U > & \fBGetPoint\fP ()"
.br
.ti -1c
.RI "void \fBAssignNullIdx\fP ()"
.br
.ti -1c
.RI "void \fBAssignIdx\fP (size_t)"
.br
.ti -1c
.RI "void \fBAssignPoint\fP (const \fBcsmp::Point\fP< 3U > &)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Point< 3U >\fP
.in +1c
.ti -1c
.RI "\fBPoint\fP (double=0\&.)"
.br
.ti -1c
.RI "\fBPoint\fP (double, double, double)"
.br
.ti -1c
.RI "\fBPoint\fP (const std::array< double, 3U > &)"
.br
.ti -1c
.RI "\fBPoint\fP (const std::vector< double > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator=\fP (double)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator+\fP (const \fBPoint\fP< 3U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator\-\fP (const \fBPoint\fP< 3U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator*\fP (const \fBPoint\fP< 3U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator/\fP (const \fBPoint\fP< 3U > &) const"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator+\fP (double) const"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator\-\fP (double) const"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator*\fP (double) const"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator/\fP (double) const"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator+=\fP (const \fBPoint\fP< 3U > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator\-=\fP (const \fBPoint\fP< 3U > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator*=\fP (const \fBPoint\fP< 3U > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator/=\fP (const \fBPoint\fP< 3U > &)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator+=\fP (double)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator\-=\fP (double)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator*=\fP (double)"
.br
.ti -1c
.RI "\fBPoint\fP< 3U > & \fBoperator/=\fP (double)"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (uint32_t)"
.br
.ti -1c
.RI "const double & \fBoperator[]\fP (uint32_t) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPoint\fP< 3U > &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPoint\fP< 3U > &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPoint\fP< 3U > &) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBPoint\fP< 3U > &) const"
.br
.ti -1c
.RI "void \fBSet\fP (const std::array< double, 3U > &)"
.br
.ti -1c
.RI "void \fBSet\fP (const std::vector< double > &)"
.br
.ti -1c
.RI "void \fBSet\fP (double, double, double)"
.br
.ti -1c
.RI "double \fBLength\fP () const"
.br
.ti -1c
.RI "double \fBSquaredLength\fP () const"
.br
.ti -1c
.RI "void \fBNormalizeLengthTo\fP (double len=1\&.)"
.br
.ti -1c
.RI "double \fBDistanceTo\fP (const \fBPoint\fP &) const"
.br
.ti -1c
.RI "bool \fBCoincidesWithWithinTolerance\fP (const \fBPoint\fP &, double tolerance=1\&.0e\-5) const"
.br
.ti -1c
.RI "bool \fBIsBetween\fP (const \fBPoint\fP &pt1, const \fBPoint\fP &pt2)"
.br
.ti -1c
.RI "std::vector< double > \fBCoordinates\fP () const"
.br
.ti -1c
.RI "std::array< double, 3U > \fBCoordinateArray\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Point< 3U >\fP
.in +1c
.ti -1c
.RI "double \fBx_\fP"
.br
.ti -1c
.RI "double \fBy_\fP"
.br
.ti -1c
.RI "double \fBz_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
refactored - strictly 3D

.PP
\fBTodo\fP
.RS 4
check whether this class is needed at all, if so, remove all un-used interfaces\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
