.TH "csmp::AndersonianBoundaryStressVisitor" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::AndersonianBoundaryStressVisitor \- Apply stresses to the boundaries of a three-dimensional geomechanic model\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <AndersonianBoundaryStressVisitor\&.h>\fP
.PP
Inherits \fBcsmp::Visitor< 3U >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndersonianBoundaryStressVisitor\fP (const \fBModel\fP< 3U > &, const \fBStressRegime\fP &, const char *SV_variable='overburden pressure', bool overwrite_force_vector=false)"
.br
.RI "by default, any entries into the RHS force vectors will get overwritten "
.ti -1c
.RI "virtual void \fBVisit\fP (\fBBoundary\fP< 3U > *)"
.br
.RI "to zero out force vector if overwrite_force_vector=true, prior to accumulation of forces "
.ti -1c
.RI "virtual void \fBVisit\fP (\fBFace\fP< 3U > *)"
.br
.RI "computes nodal forces ensuing from stress and weighted by number of nodes of the boundary face "
.in -1c

Public Member Functions inherited from \fBcsmp::Visitor< 3U >\fP
.in +1c
.ti -1c
.RI "\fBVisitor\fP (\fBPLACEMENT\fP level=MODEL, \fBPLACEMENT\fP target=ELEMENT)"
.br
.ti -1c
.RI "void \fBApplicationLevel\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "void \fBApplicationTarget\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "virtual void \fBSetInitialProperties\fP (\fBModel\fP< dim > *model)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBModel\fP< dim > *)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Visitor< 3U >\fP
.in +1c
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_target_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Apply stresses to the boundaries of a three-dimensional geomechanic model\&. 


.PP
\fBAuthor\fP
.RS 4
SKM 29/9/2014
.RE
.PP
The stresses are entered via a \fBStressRegime\fP object, but the variable 'overburden pressure' storing the vertical stress Sv must be defined and initialised\&.

.PP
The \fBAndersonianBoundaryStressVisitor\fP accesses all \fBBoundary\fP objects, and resolves the boundary normal stress and shear stresses using the normals of the boundary \fBFace\fP objects which must be outward pointing\&.

.PP
In the corresponding calculations body forces must be enabled\&.

.PP
\fBNote\fP
.RS 4
If a boundary is inclined or vertical, this is fine\&. In this case, the visitor takes the vertical variation in the boundary normal stress into account\&.
.RE
.PP
Input variables are the stress state supplied by the \fBStressRegime\fP object\&.

.PP
The visitor also computes the \fBFace\fP variables 'normal stress' and 'shear stress' on the visited boundaries\&. The nodal forces that it will apply are computed from these\&.

.PP
\fBAttention\fP
.RS 4
by default all forces that were previously assigned are zeroed first\&.

.PP
Confining stresses are always compressive and result inward pointing forces\&.

.PP
this visitor assumes that the far-field stress regime is Andersonian, i\&.e\&. one of the principal stresses is oriented perpendicular to the earth surface, i\&.e\&. that one of the principal stress axes is aligned with the vertical (Y)-axis of the CSMP model\&.
.RE
.PP
\fBNote\fP
.RS 4
This visitor allows for a workaround for applying stress boundary conditions if one does not want to use the Neumann condition functionality of the \fBPDE_Integrator\fP\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::AndersonianBoundaryStressVisitor::AndersonianBoundaryStressVisitor (const \fBModel\fP< 3U > & model, const \fBStressRegime\fP & stress_regime, const char * SV_variable = \fR'overburden pressure'\fP, bool overwrite_force_vector = \fRfalse\fP)"

.PP
by default, any entries into the RHS force vectors will get overwritten For the computation of the nodal 'gravity force'

.PP
Application level is model so that all boundaries are visited followed by a visitation of their faces\&.

.PP
\fBParameters\fP
.RS 4
\fImodel\fP computation domain\&.
.br
\fISV_variable\fP denotes overburden = vertical stress calculated by integration of the sediment column dry density up to the earth' surface\&.
.RE
.PP
TODO: the assumption is that the vertical stress is the largest principal stress, relax this 
.PP
\fBParameters\fP
.RS 4
\fISV_variable\fP should vary with depth 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void csmp::AndersonianBoundaryStressVisitor::Visit (\fBBoundary\fP< 3U > * b)\fR [virtual]\fP"

.PP
to zero out force vector if overwrite_force_vector=true, prior to accumulation of forces Collects the stress value placed on the boudary and (optionally) zeros out the initial force values assigned to this boundary\&. 
.SS "void csmp::AndersonianBoundaryStressVisitor::Visit (\fBFace\fP< 3U > * f)\fR [virtual]\fP"

.PP
computes nodal forces ensuing from stress and weighted by number of nodes of the boundary face Interpolates the applied element-centric forces to the nodes\&.

.PP
An approach is used where the nodal contribution is weighted on the basis of the distance of the barycenter to the node\&.

.PP
\fBAttention\fP
.RS 4
this is an integration (for uniform nodal forces, see option, we get non-uniform stresses) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
