.TH "csmp::IAPWS_H2O_Density" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::IAPWS_H2O_Density
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBDensity\fP (double T, double P)"
.br
.RI "outputs density (kg m-3) for temperature (oC) and pressure (Pa) "
.ti -1c
.RI "double \fBViscosity\fP (double T, double P)"
.br
.ti -1c
.RI "double \fBDensity_P_MPa\fP (double T, double P)"
.br
.RI "outputs density (kg m-3) for temperature (oC) and pressure (MPa) "
.ti -1c
.RI "double \fBVapourDensity\fP (double T, double P)"
.br
.ti -1c
.RI "double \fBLiquidDensity\fP (double T, double P)"
.br
.ti -1c
.RI "double \fBPressure\fP (double T, double rho)"
.br
.RI "outputs pressure (Pa) for temperature (oC) and density (kg m-3) "
.ti -1c
.RI "double \fBHeatCapacity\fP (double T, double P)"
.br
.RI "outputs heat capacity (J K-1 kg-1) for temperature (oC) and pressure (Pa) "
.ti -1c
.RI "double \fBHeatCapacityDensTemp\fP (double rho, double T)"
.br
.RI "outputs heat capacity (J K-1 kg-1) from density (oC) and temperature (oC) "
.ti -1c
.RI "double \fBEnthalpyDensTemp\fP (double rho, double T)"
.br
.RI "outputs enthalpy=heat content (J K-1 kg-1) from density (oC) and temperature (oC) "
.ti -1c
.RI "double \fBEnthalpy\fP (double P, double T)"
.br
.ti -1c
.RI "double \fBLiquidSaturation\fP (double T, double P)"
.br
.RI "outputs vapour density (kg m-3) for temperature (oC) and pressure (Pa) "
.ti -1c
.RI "double \fBSaturationTemperature\fP (double P)"
.br
.ti -1c
.RI "double \fBSaturationPressure\fP (double T)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
