.TH "CSMP_global_enumerations" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSMP_global_enumerations \- CSMP_global_enumerations
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBcsmp::ONE_BYTE_NUMBER\fP : std::int8_t { \fBZERO\fP, \fBONE\fP, \fBTWO\fP, \fBTHREE\fP, \fBFOUR\fP, \fBFIVE\fP, \fBSIX\fP, \fBSEVEN\fP, \fBEIGHT\fP, \fBNINE\fP, \fBTEN\fP, \fBELEVEN\fP, \fBTWELVE\fP, \fBTHIRTEEN\fP, \fBFOURTEEN\fP, \fBFIVETEEN\fP, \fBSIXTEEN\fP, \fBSEVENTEEN\fP, \fBEIGHTEEN\fP, \fBNINETEEN\fP, \fBTWENTY\fP, \fBTWENTY_ONE\fP, \fBTWENTY_TWO\fP, \fBTWENTY_THREE\fP, \fBTWENTY_FOUR\fP, \fBTWENTY_FIVE\fP, \fBTWENTY_SIX\fP, \fBTWENTY_SEVEN\fP, \fBTWENTY_EIGHT\fP, \fBTWENTY_NINE\fP, \fBTHIRTY\fP, \fBTHIRTY_ONE\fP, \fBTHIRTY_TWO\fP, \fBTHIRTY_THREE\fP, \fBTHIRTY_FOUR\fP, \fBTHIRTY_FIVE\fP, \fBTHIRTY_SIX\fP, \fBTHIRTY_SEVEN\fP, \fBTHIRTY_EIGHT\fP, \fBTHIRTY_NINE\fP, \fBFOURTY\fP, \fBFOURTY_ONE\fP, \fBFOURTY_TWO\fP, \fBFOURTY_THREE\fP, \fBFOURTY_FOUR\fP, \fBFOURTY_FIVE\fP, \fBFOURTY_SIX\fP, \fBFOURTY_SEVEN\fP, \fBFOURTY_EIGHT\fP, \fBFOURTY_NINE\fP, \fBFIFTY\fP, \fBNOT_INITIALIZED\fP =-1 }"
.br
.RI "for templates and specific initialisations (set compiler to treat enums as single byte types!) "
.ti -1c
.RI "enum \fBcsmp::VARIABLE_TYPE\fP : std::int8_t { \fBSCALAR\fP =1, \fBVECTOR\fP =2, \fBTENSOR\fP =3, \fBARRAY\fP =4, \fBFLAGGEDARRAY\fP =5 }"
.br
.RI "Discretized csmp variables\&. "
.ti -1c
.RI "enum \fBcsmp::VARIABLE_FLAG\fP : std::int8_t { \fBcsmp::PLAIN\fP, \fBcsmp::ANY\fP, \fBcsmp::INIT_GUESS\fP, \fBcsmp::INIT_COND\fP, \fBcsmp::FIELD_DATA\fP, \fBcsmp::PERIODIC\fP, \fBcsmp::DIRICH\fP, \fBcsmp::NEUMANN\fP, \fBcsmp::ROBIN\fP, \fBcsmp::CONSTANT_FLUX\fP }"
.br
.RI "variable flag indicating treatment in computations (forced to be one-byte size because it is stored everywhere) "
.ti -1c
.RI "enum \fBcsmp::PLACEMENT\fP : std::int8_t { \fBUNDEFINED\fP, \fBMODEL\fP, \fBREGION\fP, \fBBOUNDARY\fP, \fBSPLIT_BOUNDARY\fP, \fBELEMENT\fP, \fBELEMENT_INTEGRATION_POINT\fP, \fBSECTOR_INTEGRATION_POINT\fP, \fBFACET_INTEGRATION_POINT\fP, \fBFACE\fP, \fBFACE_INTEGRATION_POINT\fP, \fBFACE_SECTOR_INTEGRATION_POINT\fP, \fBFACE_FACET_INTEGRATION_POINT\fP, \fBcsmp::EDGE\fP, \fBINTER_FACE\fP, \fBINTER_FACE_INTEGRATION_POINT\fP, \fBINTER_FACE_SECTOR_INTEGRATION_POINT\fP, \fBINTER_FACE_FACET_INTEGRATION_POINT\fP, \fBNODE\fP }"
.br
.RI "Top down hierarchy of variable placements on mesh tree; finite volume quadrature pointe embedded\&. "
.ti -1c
.RI "enum \fBcsmp::CELL_SHAPE\fP : std::int8_t { \fBPOINT\fP =0, \fBLINE\fP =1, \fBSURFACE\fP =2, \fBVOLUME\fP =3, \fBHYPER_DIMENSIONAL\fP =4 }"
.br
.RI "to classify "
.ti -1c
.RI "enum \fBcsmp::INTERFACE_SIDE\fP : std::int32_t { \fBINSIDE\fP = -1, \fBOUTSIDE\fP = 1, \fBMIDDLE\fP = 0 }"
.br
.RI "Side of lower-dimensional face or interface between two higher-dimensional elements ( INSIDE or OUTSIDE ) and a potential lower-dimensional parent element ( MIDDLE ) "
.ti -1c
.RI "enum class \fBcsmp::ManifoldType\fP : int8_t { \fBcsmp::ManifoldType::STAND_ALONE\fP, \fBcsmp::ManifoldType::SPLIT_BOUNDARY\fP, \fBSPLIT_BOUNDARY_WITH_INTERNAL_MESH\fP, \fBcsmp::ManifoldType::SPLIT_BOUNDARY_CROSSING\fP, \fBcsmp::ManifoldType::MULTI_SB_CROSSING\fP, \fBcsmp::ManifoldType::SPLIT_BOUNDARY_TERMINATION\fP, \fBcsmp::ManifoldType::SPLIT_BOUNDARY_END\fP }"
.br
.ti -1c
.RI "enum \fBcsmp::TOPOTYPE\fP : std::int8_t { \fBcsmp::MESH_VERTEX\fP, \fBcsmp::INTERSECTION_POINT\fP, \fBcsmp::PERIMETER_POINT\fP, \fBcsmp::EXTERIOR_POINT\fP, \fBcsmp::INTERIOR_LINE\fP, \fBcsmp::PERIMETER_LINE\fP, \fBcsmp::EXTERIOR_LINE\fP, \fBcsmp::INTERSECTION_LINE\fP, \fBcsmp::INTERIOR_SURFACE\fP, \fBcsmp::PERIMETER_SURFACE\fP, \fBcsmp::EXTERIOR_SURFACE\fP }"
.br
.ti -1c
.RI "enum \fBcsmp::NORM_INDEX\fP : std::int8_t { \fBPOINT_DIFFERENCE\fP = -1, \fBABSOLUTE_POINT_DIFFERENCE\fP = 0, \fBL1_NORM\fP = 1, \fBMANHATTAN_NORM\fP = L1_NORM, \fBTAXICAB_NORM\fP = L1_NORM, \fBL2_NORM\fP = 2, \fBEUCLIDIAN_NORM\fP = L2_NORM, \fBLP_NORM\fP = 3, \fBMAX_NORM\fP = 4, \fBINF_NORM\fP = MAX_NORM, \fBLINF_NORM\fP = MAX_NORM, \fBL21_NORM\fP = 5, \fBL22_NORM\fP = 6, \fBFROBENIUS_NORM\fP = L22_NORM, \fBHILBERT_SCHMIDT_NORM\fP = L22_NORM, \fBLPQ_NORM\fP = 7, \fBINDUCED_L1_NORM\fP = 8, \fBINDUCED_L2_NORM\fP = 9, \fBINDUCED_MAX_NORM\fP = 11, \fBINDUCED_LINF_NORM\fP = INDUCED_MAX_NORM }"
.br
.RI "variable flag indicating treatment in computations "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr int \fBcsmp::NAME_STRING\fP (256)"
.br
.RI "some fixed string sizes (max filename length on NTFS partition / arbitrary #<32k) "
.ti -1c
.RI "constexpr int \fBcsmp::INFO_STRING\fP (1024)"
.br
.ti -1c
.RI "std::string \fBcsmp::parse\fP (\fBManifoldType\fP)"
.br
.RI "converts classifiers to strings so that they can be printed "
.ti -1c
.RI "std::string \fBcsmp::parseTopology\fP (\fBTOPOTYPE\fP)"
.br
.RI "converts classifiers to strings so that they can be printed "
.ti -1c
.RI "void \fBcsmp::variablePlacementSet\fP (std::set< \fBPLACEMENT\fP > &plSet)"
.br
.RI "Fills set with all current \fBPLACEMENT\fP choices\&. "
.ti -1c
.RI "void \fBcsmp::fvVariablePlacementSet\fP (std::set< \fBPLACEMENT\fP > &plSet)"
.br
.RI "Fills set with all finite-volume associated \fBPLACEMENT\fP choices\&. "
.ti -1c
.RI "void \fBcsmp::variableTypeSet\fP (std::set< \fBVARIABLE_TYPE\fP > &)"
.br
.RI "Fills set with all \fBVARIABLE_TYPE\fP choices in current model\&. "
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBcsmp::parseType\fP (int type)"
.br
.RI "variable type "
.ti -1c
.RI "std::string \fBcsmp::parseType\fP (\fBVARIABLE_TYPE\fP)"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBcsmp::parseType\fP (const char *type)"
.br
.ti -1c
.RI "template<typename csmp_type> \fBVARIABLE_TYPE\fP \fBcsmp::variableType\fP ()"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBcsmp::intToPLACEMENT\fP (int i)"
.br
.RI "variable placement "
.ti -1c
.RI "\fBPLACEMENT\fP \fBcsmp::parsePlacement\fP (const char *placement)"
.br
.ti -1c
.RI "std::string \fBcsmp::parsePlacement\fP (\fBPLACEMENT\fP)"
.br
.ti -1c
.RI "bool \fBcsmp::faceVariable\fP (\fBPLACEMENT\fP)"
.br
.ti -1c
.RI "bool \fBcsmp::interFaceVariable\fP (\fBPLACEMENT\fP)"
.br
.ti -1c
.RI "template<uint32_t dim, template< uint32_t > class PLACE> \fBPLACEMENT\fP \fBcsmp::parsePlacement\fP ()"
.br
.RI "determine from the element type whether the placement of the variable is \fBRegion\fP, \fBBoundary\fP or \fBSplitBoundary\fP "
.ti -1c
.RI "bool \fBcsmp::isPlacedOnIntegrationPoint\fP (\fBPLACEMENT\fP)"
.br
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBcsmp::intToVARIABLE_FLAG\fP (int i)"
.br
.RI "variable flag "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBcsmp::parseCondition\fP (std::string &s)"
.br
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBcsmp::parseStatus\fP (const char *status)"
.br
.ti -1c
.RI "std::string \fBcsmp::parseStatus\fP (\fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "std::string \fBcsmp::parseSide\fP (\fBINTERFACE_SIDE\fP)"
.br
.RI "returns the side of the \fBFace\fP or \fBInterFace\fP element "
.in -1c
.SH "Detailed Description"
.PP 
Enums available globally in the csmp Namespace
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBcsmp::ManifoldType\fP : int8_t\fR [strong]\fP"

.PP
\fBNote\fP
.RS 4
This classification is for NodeManifolds (topologically collocated Nodes) only)! 

.PP
Not all of these classifiers apply to manifolds, like endpoint 

.PP
NodeManifolds exist only at \fBSplitBoundary\fP objects 

.PP
\fBSplitBoundary\fP objects exist only inside of models 

.PP
since SplitBoundaries are surfaces, this is the highest dimension 

.PP
Classification applies to all nodes within Manifold simultaneously (including intervening ones) 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BISTAND_ALONE \fP
multiplicated point 
.TP
\f(BISPLIT_BOUNDARY \fP
2-node manifold along a \fBSplitBoundary\fP (most common) 
.TP
\f(BISPLIT_BOUNDARY_CROSSING \fP
4-node manifold intersection of split boundaries 
.TP
\f(BIMULTI_SB_CROSSING \fP
6-node cross of 3 SBs in 
.TP
\f(BISPLIT_BOUNDARY_TERMINATION \fP
T-intersection of SBs or termination of SB against \fBBoundary\fP\&. 
.TP
\f(BISPLIT_BOUNDARY_END \fP
termination against model boundary 
.SS "enum \fBcsmp::PLACEMENT\fP : std::int8_t"

.PP
Top down hierarchy of variable placements on mesh tree; finite volume quadrature pointe embedded\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIEDGE \fP
only in 3D 
.SS "enum \fBcsmp::TOPOTYPE\fP : std::int8_t"
Geometric classification of nodes / points, BREP stands for boundary representation\&. 
.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
9/07/2022
.RE
.PP
\fBAttention\fP
.RS 4
Help! - current scheme still contains apparent ambiguities of features difficult to resolve: What is an interior surface in 3D (is it the inside of a lower-dim fracture?)? PERIMETER_SURFACE in 3D refers to the perimeter of a volumetric region\&.\&.\&.
.RE
.PP
\fBTodo\fP
.RS 4
some flags do not exist in certain dimensions: in 1D PERIMETER_POINT is the same as INTERSECTION_POINT 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIMESH_VERTEX \fP
a point within the model volume 
.TP
\f(BIINTERSECTION_POINT \fP
a point where lines cross or multiple surfaces intersect 
.TP
\f(BIPERIMETER_POINT \fP
point at the end of a line inside a 2D model 
.TP
\f(BIEXTERIOR_POINT \fP
on an outside surface of the model 
.TP
\f(BIINTERIOR_LINE \fP
a line on the interior of the model 
.TP
\f(BIPERIMETER_LINE \fP
a surface edge inside of the model 
.TP
\f(BIEXTERIOR_LINE \fP
an edge of the model 
.TP
\f(BIINTERSECTION_LINE \fP
belonging to multiple surfaces in a 3D model 
.TP
\f(BIINTERIOR_SURFACE \fP
a surface within a 3D model 
.TP
\f(BIPERIMETER_SURFACE \fP
a surface forming the hull of an object inside of a 3D model 
.TP
\f(BIEXTERIOR_SURFACE \fP
a surface delimiting a 3D model 
.SS "enum \fBcsmp::VARIABLE_FLAG\fP : std::int8_t"

.PP
variable flag indicating treatment in computations (forced to be one-byte size because it is stored everywhere) 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIPLAIN \fP
modifyable, dependent or indep\&. var\&. 
.TP
\f(BIANY \fP
unspecified discriminator\&. This is also used to identify if a variable has been assigned a value or not 
.TP
\f(BIINIT_GUESS \fP
convergence oriented not phys\&. meaningful, not checked 
.TP
\f(BIINIT_COND \fP
physically meaningful initial condition, checked 
.TP
\f(BIFIELD_DATA \fP
(Geological) field data for comparison 
.TP
\f(BIPERIODIC \fP
linked via ID to opposite side of model 
.TP
\f(BIDIRICH \fP
Dirichlet boundary condition 
.TP
\f(BINEUMANN \fP
Neumann boundary condition 
.TP
\f(BIROBIN \fP
linear combination function and derivative values on the boundary of the domain 
.TP
\f(BICONSTANT_FLUX \fP
Neumann is prescribed gradient, this one is for prescribed flux 
.SH "Function Documentation"
.PP 
.SS "\fBVARIABLE_FLAG\fP csmp::intToVARIABLE_FLAG (int i)"

.PP
variable flag Options numbered in this sequence, starting with zero are: PLAIN, ANY, INIT_GUESS, INIT_COND, FIELD_DATA, PERIODIC, DIRICH, NEUMANN, ROBIN, CONSTANT_FLUX 
.SS "string csmp::parse (\fBManifoldType\fP topology)"

.PP
converts classifiers to strings so that they can be printed STAND_ALONE, ///< multiplicated point SPLIT_BOUNDARY, ///< 2-node manifold along a \fBSplitBoundary\fP (most common) SPLIT_BOUNDARY_CROSSING, ///< 4-node manifold intersection of split boundaries MULTI_SB_CROSSING, ///< 6-node cross of 3 SBs in SPLIT_BOUNDARY_TERMINATION, ///< T-intersection of SBs are termination of SB against \fBBoundary\fP SPLIT_BOUNDARY_END, ///< termination against model boundary

.PP
\fBNote\fP
.RS 4
if the split boundary cannot be determined, method returns SPLIT_BOUNDARY 
.RE
.PP

.SS "\fBVARIABLE_FLAG\fP csmp::parseCondition (std::string & s)"
Interprets the supplied string as an essential (boundary) condition\&. Possible values are given in '\fBCSMP_definitions\&.h\fP' and MULTIPLE\&. The last type can be used to specify Cauchy or Robbin conditions\&.
.SH "Input Arguments"
.PP
The string that shall be interpreted as boundary condition\&. 
.SS "string csmp::parseSide (\fBINTERFACE_SIDE\fP side)"

.PP
returns the side of the \fBFace\fP or \fBInterFace\fP element To print enum \fBINTERFACE_SIDE\fP\&. 
.SS "\fBVARIABLE_FLAG\fP csmp::parseStatus (const char * status)"
Converts the text string into any of the possible \fBcsmp::VARIABLE_FLAG\fP values\&.

.PP
\fBReturns\fP
.RS 4
if the flag cannot be parsed, the value ANY is returned\&. 
.RE
.PP

.SS "std::string csmp::parseStatus (\fBVARIABLE_FLAG\fP status)"
Convert \fBVARIABLE_FLAG\fP from an enumeration to a string so that it can be printed to stdout\&. 
.SS "std::string csmp::parseTopology (\fBTOPOTYPE\fP topology)"

.PP
converts classifiers to strings so that they can be printed Topologic qualifiers include:

.PP
MESH_VERTEX, - a point within the model volume INTERSECTION_POINT - a point where lines cross or multiple surfaces intersect PERIMETER_POINT, - point at the end of a line inside a 2D model EXTERIOR_POINT, - on an outside surface of the model INTERIOR_LINE, - a line on the interior of the model PERIMETER_LINE, - a surface edge inside of the model EXTERIOR_LINE, - an edge of the model INTERSECTION_LINE, - belonging to multiple surfaces INTERIOR_SURFACE, - a surface withing the model PERIMETER_SURFACE, - a surface forming the hull of an object inside of the model EXTERIOR_SURFACE - a surface delimiting the model 
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
