.TH "csmp::FaceData" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FaceData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFaceData\fP (const \fBFaceData\fP &)"
.br
.ti -1c
.RI "\fBFaceData\fP & \fBoperator=\fP (const \fBFaceData\fP &)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBFaceData\fP &) const"
.br
.ti -1c
.RI "size_t \fBoperator[]\fP (size_t) const"
.br
.ti -1c
.RI "void \fBAssignKey\fP (const std::vector< uint32_t > &)"
.br
.ti -1c
.RI "void \fBAssignNodeIDs\fP (const std::vector< uint32_t > &)"
.br
.ti -1c
.RI "void \fBAssignFirstNeighbor\fP (int32_t)"
.br
.ti -1c
.RI "void \fBAssignSecondNeighbor\fP (int32_t)"
.br
.ti -1c
.RI "void \fBAssignFirstNeighborFaceNumber\fP (size_t)"
.br
.ti -1c
.RI "void \fBAssignSecondNeighborFaceNumber\fP (size_t)"
.br
.ti -1c
.RI "int32_t \fBFirstNeighbor\fP () const"
.br
.ti -1c
.RI "int32_t \fBSecondNeighbor\fP () const"
.br
.ti -1c
.RI "size_t \fBFirstNeighborFaceNumber\fP () const"
.br
.ti -1c
.RI "size_t \fBSecondNeighborFaceNumber\fP () const"
.br
.ti -1c
.RI "void \fBSetFiniteElementType\fP (const \fBCSMP_FEM_TYPE\fP &fetype)"
.br
.ti -1c
.RI "\fBCSMP_FEM_TYPE\fP \fBFiniteElementType\fP () const"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
