.TH "csmp::LHS_FixedValueMatrix< dim, CELL >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::LHS_FixedValueMatrix< dim, CELL >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PDE_Integrator_Test\&.h>\fP
.PP
Inherits \fBcsmp::MathOperatorLHS< dim, CELL >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLHS_FixedValueMatrix\fP (const \fBPropertyDatabase\fP< dim > &p, const char *oper, const char *basic, const char *test, double value)"
.br
.ti -1c
.RI "virtual void \fBComputeContribution\fP (const CELL &)"
.br
.ti -1c
.RI "virtual \fBLHS_FixedValueMatrix\fP< dim, CELL > * \fBclone\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::MathOperatorLHS< dim, CELL >\fP
.in +1c
.ti -1c
.RI "\fBMathOperatorLHS\fP (const \fBPropertyDatabase\fP< dim > &, const char *basic, const char *test)"
.br
.ti -1c
.RI "\fBMathOperatorLHS\fP (const \fBPropertyDatabase\fP< dim > &, const char *oper, const char *basic, const char *test)"
.br
.ti -1c
.RI "\fBMathOperatorLHS\fP (const \fBMathOperatorLHS\fP &mo)"
.br
.ti -1c
.RI "\fBMathOperatorLHS\fP & \fBoperator=\fP (const \fBMathOperatorLHS\fP &)"
.br
.ti -1c
.RI "std::string \fBName\fP () const"
.br
.RI "\fBOperand\fP Functions\&. "
.ti -1c
.RI "void \fBName\fP (const char *mathoperator_name, const char *bopname, const char *topname)"
.br
.RI "=================================== \fBOperand\fP Functions ======================================================================== "
.ti -1c
.RI "void \fBName\fP (const char *mathoperator_name, const char *opname, const char *bopname, const char *topname)"
.br
.ti -1c
.RI "virtual void \fBOut\fP () const"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBMaterialOperand\fP () const"
.br
.ti -1c
.RI "const \fBIndex\fP & \fBMaterialOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBMaterialOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBMaterialOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBMaterialOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBMaterialOperandDataDepth\fP () const"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBBasicOperand\fP () const"
.br
.ti -1c
.RI "const \fBIndex\fP & \fBBasicOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBBasicOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBBasicOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBBasicOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBBasicOperandDataDepth\fP () const"
.br
.ti -1c
.RI "size_t \fBBasicOperandOffset\fP () const"
.br
.ti -1c
.RI "void \fBBasicOperandOffset\fP (size_t)"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBTestOperand\fP () const"
.br
.ti -1c
.RI "const \fBIndex\fP & \fBTestOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBTestOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBTestOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBTestOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBTestOperandDataDepth\fP () const"
.br
.ti -1c
.RI "size_t \fBTestOperandOffset\fP () const"
.br
.ti -1c
.RI "void \fBTestOperandOffset\fP (size_t)"
.br
.ti -1c
.RI "bool \fBAdd\fP () const"
.br
.RI "Accumulation Process Settings\&. "
.ti -1c
.RI "bool \fBSubtract\fP () const"
.br
.ti -1c
.RI "bool \fBAddLater\fP () const"
.br
.ti -1c
.RI "bool \fBSubtractLater\fP () const"
.br
.ti -1c
.RI "bool \fBMultiply\fP () const"
.br
.ti -1c
.RI "bool \fBLumpedFormulation\fP () const"
.br
.ti -1c
.RI "uint32_t \fBApplicationCycle\fP () const"
.br
.ti -1c
.RI "uint32_t \fBApplicationCycles\fP () const"
.br
.ti -1c
.RI "double \fBMultiplyBy\fP () const"
.br
.ti -1c
.RI "bool \fBMultiplyWithTimeIncrement\fP () const"
.br
.ti -1c
.RI "bool \fBDivideByTimeIncrement\fP () const"
.br
.ti -1c
.RI "void \fBAddAccumulate\fP ()"
.br
.RI "Set flags and properties\&. "
.ti -1c
.RI "void \fBSubtractAccumulate\fP ()"
.br
.ti -1c
.RI "void \fBAddAccumulateLater\fP ()"
.br
.ti -1c
.RI "void \fBSubtractAccumulateLater\fP ()"
.br
.ti -1c
.RI "void \fBMultiplyAccumulate\fP ()"
.br
.ti -1c
.RI "void \fBLumpedFormulation\fP (bool)"
.br
.ti -1c
.RI "void \fBApplicationCycle\fP (uint32_t)"
.br
.ti -1c
.RI "void \fBApplicationCycles\fP (uint32_t)"
.br
.ti -1c
.RI "void \fBMultiplyBy\fP (double factor)"
.br
.ti -1c
.RI "void \fBMultiplyWithTimeIncrement\fP (bool multiply)"
.br
.ti -1c
.RI "void \fBDivideByTimeIncrement\fP (bool divide)"
.br
.ti -1c
.RI "void \fBPropertyAtIntegrationPoint\fP (const CELL< dim > &, const \fBcsmp::Index\fP &, uint32_t ip, \fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "interpolation of property if isoparametric elements are used "
.ti -1c
.RI "virtual void \fBGetOperands\fP (const CELL< dim > &)"
.br
.RI "getting data from the \fBElement\fP, \fBFace\fP, \fBInterFace\fP "
.ti -1c
.RI "virtual void \fBComputeContribution\fP (const CELL< dim > &)"
.br
.RI "integration performed on \fBElement\fP, \fBFace\fP, \fBInterFace\fP "
.ti -1c
.RI "virtual void \fBWriteOperands\fP (CELL< dim > &)"
.br
.RI "writing data to the \fBElement\fP, \fBFace\fP, \fBInterFace\fP "
.ti -1c
.RI "virtual void \fBMultiplyWithTimeFactor\fP (double dt)"
.br
.RI "multiply with time increment if this is desired "
.ti -1c
.RI "virtual void \fBAssignToGlobal\fP (const CELL< dim > &, \fBSparseMatrix\fP &)"
.br
.RI "assigment to the left hand side global matrix (after everything was calculated ) "
.ti -1c
.RI "virtual void \fBAssignToGlobal\fP (const CELL< dim > &, \fBSparseMatrix\fP &, std::vector< double > &, const std::vector< size_t > &)"
.br
.RI "used by PDE_IntegratorUoM for assembly of a pre-eliminated solution matrix and RH vector "
.ti -1c
.RI "virtual void \fBAssignToGlobal\fP (const CELL< dim > &, \fBCompressedRowMatrix\fP &, std::vector< double > &, const std::vector< size_t > &)"
.br
.RI "used by \fBPDE_Integrator_CRM\fP for assembly of a pre-eliminated solution matrix and RH vector (scalar versions) "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::MathOperatorLHS< dim, CELL >\fP
.in +1c
.ti -1c
.RI "\fBMathOperatorLHS\fP ()"
.br
.RI "prevent default construction "
.in -1c

Protected Attributes inherited from \fBcsmp::MathOperatorLHS< dim, CELL >\fP
.in +1c
.ti -1c
.RI "std::string \fBname_\fP"
.br
.RI "name of operator "
.ti -1c
.RI "\fBParameter\fP \fBop\fP"
.br
.RI "material property operand "
.ti -1c
.RI "std::pair< \fBParameter\fP, size_t > \fBbop\fP"
.br
.RI "basic function operand and calculation offset "
.ti -1c
.RI "std::pair< \fBParameter\fP, size_t > \fBtop\fP"
.br
.RI "test function operand and calculation offset "
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBLHS\fP"
.br
.RI "solution matrix to be accumulated "
.ti -1c
.RI "std::vector< \fBDenseMatrix\fP< DM_MIN > > \fBMTRL\fP"
.br
.RI "material property matrix(es) needed for PDE operand "
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBDERIV\fP"
.br
.RI "shape function derivative matrix "
.ti -1c
.RI "std::vector< double > \fBIPOL\fP"
.br
.RI "shape function vector "
.ti -1c
.RI "double \fBfactor_\fP"
.br
.RI "constant scaling factor "
.ti -1c
.RI "bool \fBadd_accumulate_\fP"
.br
.ti -1c
.RI "bool \fBsubtract_accumulate_\fP"
.br
.ti -1c
.RI "bool \fBadd_accumulate_later_\fP"
.br
.ti -1c
.RI "bool \fBsubtract_accumulate_later_\fP"
.br
.ti -1c
.RI "bool \fBmultiply_accumulate_\fP"
.br
.ti -1c
.RI "bool \fBlump_matrices_\fP"
.br
.ti -1c
.RI "uint32_t \fBapplication_cycles_\fP"
.br
.ti -1c
.RI "uint32_t \fBapplication_cycle_\fP"
.br
.ti -1c
.RI "bool \fBtime_multiply_\fP"
.br
.ti -1c
.RI "bool \fBtime_divide_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, class CELL = Element<dim>>
.br
class csmp::LHS_FixedValueMatrix< dim, CELL >"LHS operator that puts fixed values in the matrix 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, class CELL = Element<dim>> virtual \fBLHS_FixedValueMatrix\fP< dim, CELL > * \fBcsmp::LHS_FixedValueMatrix\fP< dim, CELL >::clone () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBcsmp::MathOperatorLHS< dim, CELL >\fP\&.
.SS "template<uint32_t dim, class CELL> void \fBcsmp::LHS_FixedValueMatrix\fP< dim, CELL >::ComputeContribution (const CELL & e)\fR [virtual]\fP"
Initialises \fBElement\fP integral contribution to global solution matrix with a fixed value as input in constructor\&.

.PP
This method sets \fIvalue_for_matrix_\fP on the diagonal and -\fIvalue_for_matrix_\fP off the diagonal\&. If the TestOperand is a vector or array then off-diagonal terms are set separately for each component of the vector (no coupling)\&.

.PP
\fBNote\fP
.RS 4
transformNodeIndexVector( uint32_t dim, const csmp::Index&, vector<size_t>& ); in \fBMathOperatorRHS\fP changes matrices according to the degrees of freedom of the solution variables 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
