.TH "csmp::CVFEM_Visitor< dim, CELL >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CVFEM_Visitor< dim, CELL >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CVFEM_Visitor\&.h>\fP
.PP
Inherits \fBcsmp::Visitor< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCVFEM_Visitor\fP (\fBModel\fP< dim > &model, const char *\fBvariable\fP)"
.br
.ti -1c
.RI "\fBCVFEM_Visitor\fP (\fBModel\fP< dim > &model, const char *operand, const char *\fBvariable\fP)"
.br
.ti -1c
.RI "virtual \fB~CVFEM_Visitor\fP ()"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBElement\fP< dim > *)"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBPropertyDatabase\fP< dim > &, \fBCVFEM_MathOperatorLHS\fP< dim, CELL > *lhs_op)"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBCVFEM_MathOperatorRHS\fP< dim, CELL > *rhs_op)"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBPropertyDatabase\fP< dim > &, \fBCVFEM_MathOperatorLHS\fP< dim, CELL > *lhs_op, const char *upwind_variable)"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBPropertyDatabase\fP< dim > &, \fBCVFEM_MathOperatorRHS\fP< dim, CELL > *rhs_op, const char *upwind_variable)"
.br
.ti -1c
.RI "void \fBSetTimeIncrement\fP (double time_increment)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBVisitor\fP (\fBPLACEMENT\fP level=MODEL, \fBPLACEMENT\fP target=ELEMENT)"
.br
.ti -1c
.RI "void \fBApplicationLevel\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApplicationTarget\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationTarget\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetInitialProperties\fP (\fBModel\fP< dim > *model)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBModel\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBRegion\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBSplitBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBInterFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBEdge\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBNode\fP< dim > *)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_target_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class CELL = Element>
.br
class csmp::CVFEM_Visitor< dim, CELL >"
.PP
\fBAuthor\fP
.RS 4
Philipp Weis, ETH Zuerich 
.RE
.PP
.SH "Contact"
.PP
philipp.weis@erdw.ethz.ch

.PP
@changes changes Latest Changes
.SH "Motivation"
.PP
Specialized visitor that allows the use of CVFEM_MathOperators\&. Initially used for consistency checks for development of CVFEM scheme\&. Currently not in use\&. Could be used in future as replacement for FV calculations
.SH "Usage"
.PP
To be used within the CVFEM scheme (Weis et al\&., Geofluids, 2014)\&.

.PP
.PP
.nf
Can assemble PDE_operators in the same way as the PDE_integrator\&.
.fi
.PP
.SH "Dependencies"
.PP
\fBCVFEM_MathOperatorLHS\fP \fBCVFEM_MathOperatorRHS\fP
.SH "Known issues"
.PP
.SH "Testing"
.PP
testing was done in the period before publication in 2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class CELL> \fBcsmp::CVFEM_Visitor\fP< dim, CELL >::CVFEM_Visitor (\fBModel\fP< dim > & model, const char * variable)"
custom constructor 
.SS "template<uint32_t dim, template< uint32_t > class CELL> \fBcsmp::CVFEM_Visitor\fP< dim, CELL >::CVFEM_Visitor (\fBModel\fP< dim > & model, const char * operand, const char * variable)"
custom constructor 
.SS "template<uint32_t dim, template< uint32_t > class CELL> \fBcsmp::CVFEM_Visitor\fP< dim, CELL >::~\fBCVFEM_Visitor\fP ()\fR [virtual]\fP"
default destructor 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class CELL> void \fBcsmp::CVFEM_Visitor\fP< dim, CELL >::Visit (\fBElement\fP< dim > * n)\fR [virtual]\fP"
visit function for elem 
.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
