.TH "csmp::ExplicitNodeCenteredFiniteVolumeTransport< dim, STP >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ExplicitNodeCenteredFiniteVolumeTransport< dim, STP >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP\&.
.PP
Inherited by \fBcsmp::ExplicitMassBasedTransport< dim, STP >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExplicitNodeCenteredFiniteVolumeTransport\fP (const char *region, \fBModel\fP< dim > &, const char *porosity, const char *advected_prop, const char *transp_velocity, const char *nodal_source, bool second_order_accuracy)"
.br
.RI "single phase solute advection-only constructor for a subregion identified as a group "
.ti -1c
.RI "\fBExplicitNodeCenteredFiniteVolumeTransport\fP (const char *region, \fBModel\fP< dim > &, const char *porosity, const char *diffusivity, const char *advected_prop, const char *transp_velocity, const char *nodal_source, bool second_order_accuracy)"
.br
.RI "single phase solute advection-dispersion constructor for a subregion identified as a group "
.ti -1c
.RI "\fBExplicitNodeCenteredFiniteVolumeTransport\fP (const char *region, \fBModel\fP< dim > &, const char *porosity, const char *advected_prop_lhs, const char *advected_prop_rhs, const char *transp_velocity, const char *nodal_source, bool second_order_accurate, bool second_order_in_time, const char *elmt_thickness_attribute=NULL)"
.br
.RI "single-phase passive advection (group-restricted) "
.ti -1c
.RI "virtual \fB~ExplicitNodeCenteredFiniteVolumeTransport\fP ()"
.br
.ti -1c
.RI "virtual double \fBAdvectVariable\fP (double time_interval, double cfl_multiplication_factor, bool apply_flux_balance_correction, bool update_pore_volumes)"
.br
.RI "single-phase transport ( "
.ti -1c
.RI "virtual void \fBAdvectVariableSingleStep\fP (double time_increment, bool apply_flux_balance_correction, bool update_pore_volumes)"
.br
.ti -1c
.RI "double \fBOutputResults\fP (const \fBPropertyDatabase\fP< dim > &, const \fBcsmp::Index\fP &adv_key, bool show_range, uint32_t var_comp_nr=0u) const"
.br
.RI "results are stored back wherever flags are not DIRICH "
.in -1c

Public Member Functions inherited from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP
.in +1c
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeTransport\fP (const char *group_name, \fBModel\fP< dim > &, const char *porosity, const char *advected_prop, const char *transp_velocity, const char *nodal_source, bool second_order_in_space, bool second_order_in_time, const char *elmt_thickness_attribute=NULL, const char *velocity_multiplier=NULL)"
.br
.RI "single-phase solute advection-ONLY constructor, 1st-order method "
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeTransport\fP (const char *group_name, \fBModel\fP< dim > &, const char *porosity, const char *diffusivity, const char *advected_prop, const char *transp_velocity, const char *nodal_source, bool second_order_in_space, bool second_order_in_time, const char *elmt_thickness_attribute=NULL, const char *velocity_multiplier=NULL)"
.br
.RI "single-phase solute advection-diffusion constructor, 1st-order method "
.ti -1c
.RI "virtual double \fBTransportPhase\fP (\fBTwoPhaseModel\fP< dim > &, double time_interval)"
.br
.RI "advection of one of two phases in two-phase flow handled by subclasses "
.ti -1c
.RI "virtual double \fBAnisotropicCourantIncrement\fP ()"
.br
.RI "evaluation of Courant-Friedrich-Levy condition, i\&.e\&., grid Courant number "
.ti -1c
.RI "virtual double \fBAnisotropicCourantIncrement\fP (\fBTwoPhaseModel\fP< dim > &, double max_time_increment=3153600000\&.)"
.br
.RI "advection, capillary diffusion and gravitational flow "
.ti -1c
.RI "void \fBCFL_Multiplier\fP (double desired_value)"
.br
.RI "to set scaling (default=1) "
.ti -1c
.RI "double \fBCFL_Multiplier\fP () const"
.br
.ti -1c
.RI "void \fBWithLsmGradientLimiter\fP (\fBModel\fP< dim > &)"
.br
.RI "to apply the gradient limiter "
.ti -1c
.RI "void \fBMaxNonlinear2ndOrderIterations\fP (size_t max_nonlinear_iterations)"
.br
.ti -1c
.RI "void \fBTargetNonlinear2ndOrderResidual\fP (double target_residual)"
.br
.ti -1c
.RI "double \fBModelInflow\fP () const"
.br
.ti -1c
.RI "double \fBModelOutflow\fP () const"
.br
.ti -1c
.RI "double \fBBoundaryFluxes\fP (double &inflow, double &out_flow, bool box_shaped_model=true, bool use_advected_variable=false, const char *advected_variable='no advected variable', const char *variable_to_determine_no_flow='fluid pressure', \fBVARIABLE_FLAG\fP exclude_flag=\fBANY\fP) const"
.br
.RI "returns inflow, outflow, and mismatch between these; calculation can FVs where variable is flagged with exclude_flag "
.ti -1c
.RI "void \fBFluxBalance\fP (double &fmin, double &fmax) const"
.br
.RI "for each finite volume it sums up incoming and outgoing fluxes reporting the extrema "
.ti -1c
.RI "void \fBDivergence\fP (const char *div_property, const char *result_prop) const"
.br
.RI "as previous method, but assigns surface integrals to the result property "
.ti -1c
.RI "void \fBMultiplyScalarNodePropertyByFiniteVolume\fP (const char *property)"
.br
.RI "integrates nodal scalar properties finite volume by finite volume "
.ti -1c
.RI "double \fBVolumeIntegrateScalarFiniteVolumeVariable\fP (const char *property, bool consider_porosity) const"
.br
.RI "integrates scalar node and element variables "
.ti -1c
.RI "double \fBVolumeIntegrateScalarFiniteElementVariable\fP (const char *property, bool take_porosity_into_account=false, const char *region=NULL) const"
.br
.ti -1c
.RI "double \fBVolumeIntegrateScalarFiniteVolumeVariable\fP (const char *group, const \fBModel\fP< dim > &, const char *property, bool consider_porosity) const"
.br
.RI "integrates target property over a region of interest, result can be scaled by porosity "
.ti -1c
.RI "void \fBVolumeIntegrate\fP (const char *integrand_property, const char *result_prop) const"
.br
.RI "integrals for finite-element computations "
.ti -1c
.RI "void \fBVolumeIntegrate\fP (const char *integrand_property, const char *integrand_multiplier, const char *result_prop) const"
.br
.ti -1c
.RI "void \fBMultiplyScalarBoundaryValuesByFiniteVolumeCrossSectionalArea\fP (\fBModel\fP< dim > &, \fBBOX_BOUNDARY\fP, const char *property)"
.br
.RI "conversion of values already assigned to the nodes (only possible if nodes comprise model boundary) "
.ti -1c
.RI "void \fBTransformScalarBoundaryValuesIntoNeumannConditions\fP (\fBBOX_BOUNDARY\fP boundary, const char *node_property, const char *propertionality_constant, bool distribute_total_amount)"
.br
.RI "computation and assignment of Neumann boundary gradients to target boundary "
.ti -1c
.RI "void \fBAssignScalarBoundaryValues\fP (\fBBOX_BOUNDARY\fP, const char *property, \fBVARIABLE_FLAG\fP bcond, double val, bool distribute_total_amount)"
.br
.RI "assignment of a single specific value that is projected on outward point normal "
.ti -1c
.RI "double \fBFiniteVolume\fP (const char *volume_property) const"
.br
.RI "returns the actual volume of the finite volume i "
.ti -1c
.RI "double \fBPoreVolume\fP (size_t iFv_cell) const"
.br
.ti -1c
.RI "virtual void \fBAdjustSolverSettings\fP ()"
.br
.RI "Adjust flexible samg solver settings\&. "
.ti -1c
.RI "virtual CSMP_DEFAULT_LINEAR_SOLVER_SETTINGS & \fBGetSolverSettings\fP ()"
.br
.RI "Access to advector's solver settings\&. "
.ti -1c
.RI "virtual CSMP_DEFAULT_LINEAR_SOLVER * \fBGetSolver\fP ()"
.br
.ti -1c
.RI "virtual void \fBOut\fP () const"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAccumulateFluxUpwindProducts\fP ()"
.br
.ti -1c
.RI "virtual void \fBAssignFluxBoundaryConditions\fP (uint32_t var_comp_nr=0)"
.br
.RI "as in base class but for a result vector "
.ti -1c
.RI "virtual void \fBComposeSolution\fP (double time_interval, uint32_t var_comp_nr=0u)"
.br
.RI "passive advection: gives transported variable at end of time_interval "
.ti -1c
.RI "void \fBAdvectVariable1stOrder\fP (double time_interval, bool output_result_range)"
.br
.RI "explicit conservative "
.in -1c

Protected Member Functions inherited from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP
.in +1c
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeTransport\fP (const \fBNodeCenteredFiniteVolumeTransport\fP< dim > &)"
.br
.ti -1c
.RI "void \fBInitializeFiniteVolumeData\fP (bool multiply_pore_volumes_with_thickness_attribute=false)"
.br
.ti -1c
.RI "void \fBInitializeFiniteVolumeDataParametricToPhysical\fP (bool store_normals)"
.br
.ti -1c
.RI "void \fBInitializeSectorPoreVolumeData\fP (bool multiply_pore_volumes_with_thickness_attribute)"
.br
.ti -1c
.RI "bool \fBInitializeArraysForFirstOrderMethod\fP ()"
.br
.ti -1c
.RI "bool \fBInitializeArraysForSecondOrderMethod\fP (bool second_order_in_space, bool second_order_in_time)"
.br
.ti -1c
.RI "virtual void \fBCheckTransportVariables\fP () const"
.br
.ti -1c
.RI "virtual size_t \fBMeasureAllocatedMemory\fP () const"
.br
.ti -1c
.RI "bool \fBSecondOrderInTime\fP () const"
.br
.ti -1c
.RI "bool \fBSecondOrderInSpace\fP () const"
.br
.ti -1c
.RI "void \fBInitialAdvectedPropertyValues\fP (const \fBcsmp::Index\fP &adv_key)"
.br
.ti -1c
.RI "void \fBInitialAdvectedPropertyValues\fP (const \fBcsmp::Index\fP &adv_key, double &smin, double &smax)"
.br
.ti -1c
.RI "void \fBMinMaxAdvectedProperty\fP ()"
.br
.ti -1c
.RI "void \fBBackupFacetFluxes\fP ()"
.br
.ti -1c
.RI "void \fBUpdateProjectedVelocitiesAndFluxBalances\fP ()"
.br
.ti -1c
.RI "bool \fBFluxThroughBoundaryFiniteVolume\fP (const \fBNode\fP< dim > *fv_ptr, double &inflow, double &flux_balance) const"
.br
.ti -1c
.RI "void \fBAssignFluxBoundaryConditions\fP (\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > &advection_algorithm, bool use_t0_saturation) const"
.br
.ti -1c
.RI "void \fBRecordFluxBalances\fP (const char *balance_var, double &total_surplus, double &total_deficit) const"
.br
.ti -1c
.RI "void \fBAdvectVariable1stOrder\fP (\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > &, double time_interval, bool with_flux_balance_correction)"
.br
.ti -1c
.RI "void \fBAdvectVariable2ndOrder\fP (\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > &, double time_increment, bool with_flux_balance_correction)"
.br
.ti -1c
.RI "void \fBAdvectVariable2ndOrderInSpaceAndTime\fP (\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > &, double time_increment, bool with_flux_balance_correction)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "STP< dim > \fBstencil_\fP"
.br
.ti -1c
.RI "std::vector< double > \fBRESULT\fP"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP
.in +1c
.ti -1c
.RI "const \fBPropertyDatabase\fP< dim > & \fBpref_\fP"
.br
.ti -1c
.RI "\fBRegion\fP< dim > & \fBgref_\fP"
.br
.ti -1c
.RI "\fBModel\fP< dim > & \fBmref_\fP"
.br
.ti -1c
.RI "bool \fBverbose_\fP"
.br
.ti -1c
.RI "std::vector< \fBFV_Parameter\fP > \fBSTENCIL_DATA\fP"
.br
.RI "finite-volume data for fast calculations "
.ti -1c
.RI "std::vector< double > \fBFVPOREVOL\fP"
.br
.RI "pore volumes of finite-volume cells for theta calculation etc\&. "
.ti -1c
.RI "std::vector< double > \fBSAT0\fP"
.br
.RI "advected variable at t0 "
.ti -1c
.RI "std::vector< double > \fBFLUX_BALANCE\fP"
.br
.RI "for each FV, but excluding truncated FV at global model boundaries "
.ti -1c
.RI "std::vector< std::pair< double, double > > \fBSMINMAX\fP"
.br
.RI "min, max values of advected property at neighbor FV's of current FV "
.ti -1c
.RI "std::vector< std::vector< double > > \fBFACETFLUXES0\fP"
.br
.RI "at time, t (at last time step) "
.ti -1c
.RI "std::vector< std::vector< double > > \fBLTDSATS0\fP"
.br
.RI "ltd values of advected property "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBphi_key_\fP"
.br
.RI "porosity "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBdiff_key_\fP"
.br
.RI "diffusivity of advected variable (only in 2nd-order method) "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBadv1_key_\fP"
.br
.RI "transported variable "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBvel_key_\fP"
.br
.RI "transport velocity "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBsrc_key_\fP"
.br
.RI "nodal fluid volume source "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBthi_key_\fP"
.br
.RI "thickness multiplier for lower dimensional elements "
.ti -1c
.RI "const \fBcsmp::Index\fP \fBvelo_mult_key_\fP"
.br
.RI "velocity multiplier key "
.ti -1c
.RI "\fBcsmp::Index\fP \fBmass_center_key_\fP"
.br
.RI "center of mass for each CV "
.ti -1c
.RI "\fBcsmp::Index\fP \fBgrad_advprop_key_\fP"
.br
.RI "gradient of the advacted property "
.ti -1c
.RI "\fBcsmp::Index\fP \fBgrad_advprop_limiter_key_\fP"
.br
.RI "limiter for the gradient of the advected property "
.ti -1c
.RI "std::string \fBadvected_variable_\fP"
.br
.ti -1c
.RI "double \fBcfl_multiplier_\fP"
.br
.ti -1c
.RI "size_t \fBvar_ncomponents_\fP"
.br
.ti -1c
.RI "\fBStencilProcessor\fP< dim > \fBstencil_\fP"
.br
.RI "default size is 1 if only a scalar is being advected\&. (Julian) "
.ti -1c
.RI "bool \fBfirstCall_\fP"
.br
.ti -1c
.RI "bool \fBwith_lsmgrad_limiter_\fP"
.br
.ti -1c
.RI "double \fBtarget_nonlinear_limiting_case_residual_\fP"
.br
.RI "targed residual in order to get correct 2nd order approximations "
.ti -1c
.RI "size_t \fBmax_nonlinear_limiting_case_iterations_\fP"
.br
.RI "maximum number of nonlinear iterations in 2nd order scheme "
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeAlgorithm\fP< dim > * \fBbaseAdvector_\fP = nullptr"
.br
.ti -1c
.RI "\fBGenericNodePropertyGradientLimiter\fP< dim > * \fBgrad_advprop_limiter_\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class STP>
.br
class csmp::ExplicitNodeCenteredFiniteVolumeTransport< dim, STP >""generic_node_centered_finite_volumes\\ExplicitNodeCenteredFiniteVolumeTransport\&.h" 
.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei 
.RE
.PP
\fBDate\fP
.RS 4
2002
.RE
.PP
.SH "Motivation"
.PP
The \fBExplicitNodeCenteredFiniteVolumeTransport\fP module is provided to allow users to perform passive advection and advection of a single non-wetting phase in two-phase flow simulations\&. It represents the fastest but CFL dependent transport scheme for arbitrary FE meshes including different FE types and mixes of volume and surface elements\&. 
.br

.PP
The scheme is also very tolerant in that no specific boundary conditions need to be applied\&. The value of the advected variable at inflow boundaries is not modified and governs what gets transported into the model domain\&. 
.br
.SH "Design Intent"
.PP
The scheme has been designed to capitalize on the new generic polytype CVFE technology that is part of CSMP\&. 
.br
.SH "Applicability"
.PP
Use the scheme if the transport velocity field is rapidly changing or invalidated by the transport itself\&. In this case the scheme is faster that the implicit scheme embodied in the FiniteVolumeTransport module which starts to pay off at about CFL=20 or greater\&. 
.br

.PP
Do not use this scheme when the CFL condition based transport increment leads global advection steps that are smaller than about 1/1,000 of the model length in the direction of the flow\&. In this case the computations would be prohibitively slow\&.
.SH "Structure"
.PP
The explicit advection scheme consists out of the three modules: 
.br

.PP
\fBExplicitNodeCenteredFiniteVolumeTransport\fP ExplicitFiniteVolumeAlgorithm ExplicitFiniteVolumeProcessor

.PP
The user will only interact with the \fBExplicitNodeCenteredFiniteVolumeTransport\fP module, but the ExplicitFiniteVolumeAlgorithm is used to manage the accumulation and output of the solution in each transport step, and the ExplicitFiniteVolumeProcessor class facilitates the generation of the finite-volume stencils from each finite element, so that the accumulation can proceed on an element by element basis and no FV mesh needs to be stored\&.
.SH "Collaboration"
.PP
The scheme collaborates with the finite elements of the current model\&.
.SH "Consequences"
.PP
This implementation of the scheme cannot be restricted to Regions, but always needs to be applied to the entire model, i\&.e\&. \fBModel\fP\&. 
.br

.PP
Currently it also only works for 3D models\&. Surface computations can still be done if the mesh consists entirely of surface elements in 3D space\&.
.SH "Implementation"
.PP
The flux-balances are computed for all finite volumes including those which are located on the boundaries of the \fBRegion\fP or \fBModel\fP to which the transport scheme is applied\&. They are compensated for also on all domain boundaries\&. 
.br
.SH "Application Examples"
.PP
This is an example of how the second order accurate scheme is applied:

.PP
.PP
.nf
ExplicitNodeCenteredFiniteVolumeTransport  explicit_advector( model, "porosity", "diffusivity", 
                                                 "concentration", "velocity", second_order );

cout <<"\\n\\nadvectVariableExplicit: Configuring TRANSPORT simulation: ";
if ( second_order ) cout <<" IMPES: SECOND ORDER SCHEME\&."<< endl;
else                cout <<" IMPES: FIRST ORDER SCHEME\&."<< endl;
cout <<"\\nThe grid Courant number is "<< explicit_advector\&.CourantIncrement( sg ) << endl;
cout <<"\\nEnter advection time: ";
double time_interval;
cin >> time_interval;

cout <<"\\n\\tMeasuring the time required to solve the advection problem\&."<< endl;
clock_t ticks = clock();
explicit_advector\&.AdvectVariable( model, time_interval );
ticks = clock() \- ticks;
cout <<"\\n\\n\\tCPU clock ticks used for advection step: "<< ticks << endl;
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class STP> \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::ExplicitNodeCenteredFiniteVolumeTransport (const char * region, \fBModel\fP< dim > & sg, const char * porosity, const char * advected_prop, const char * transp_velocity, const char * nodal_source, bool second_order_accuracy)"

.PP
single phase solute advection-only constructor for a subregion identified as a group single-phase passive advection (group-restricted) 
.SS "template<uint32_t dim, template< uint32_t > class STP> \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::ExplicitNodeCenteredFiniteVolumeTransport (const char * group, \fBModel\fP< dim > & sg, const char * porosity, const char * diffusivity, const char * advected_prop_t1, const char * transp_velocity, const char * nodal_source, bool second_order_accurate)"

.PP
single phase solute advection-dispersion constructor for a subregion identified as a group Constructor for the single-phase passive advection scheme for slightly compressible flow without fluid density and viscosity variations\&. The \fBExplicitNodeCenteredFiniteVolumeTransport\fP can be constructed for first- and second order calculations\&. 
.br

.PP
Diffusion is only taken into account if second-order is chosen, because the first-order scheme already is so diffusive that adding an extra diffusion term makes little sense\&. 
.br
.SH "Input Arguments"
.PP
The \fBExplicitNodeCenteredFiniteVolumeTransport\fP gains access via reference to the model to which it is applied to\&. The user needs to specify the piecewise constant element variables porosity, diffusivity and transport velocity as must be defined in the CSP_variables\&.txt file\&. The transported variable must be nodal since this explicit transport scheme is based on node-centered finite volumes\&. 
.br
.SH "Implementation"
.PP
The constructor creates minor storage array for repetitively used variables like the finite (pore) volumes, the flux balance for each FV cell and a \fBvector<double>\fP of FV_parameters called FV_stencil_data that holds the FV sector volumes, facet areas and facet normal fluxes which are always updated before the first advection step, when the CFL criterion is computed\&. This \fBvector<double>\fP will become redundant when the generic FV scheme has been optimized for speed\&. 
.br
.SH "Application Examples"
.PP
Use \fBExplicitNodeCenteredFiniteVolumeTransport\fP as constructed with this particular constructor for the passive advection of tracers in a rapidly evolving flow field that necessitates frequent updates of the velocity fields\&. 
.br
.SH "Messages"
.PP
The memory that is consumed during the construction process is reported\&. 
.SS "template<uint32_t dim, template< uint32_t > class STP> \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::~\fBExplicitNodeCenteredFiniteVolumeTransport\fP ()\fR [virtual]\fP"
Frees all the allocated memory\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class STP> void \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::AccumulateFluxUpwindProducts ()\fR [protected]\fP, \fR [virtual]\fP"
Accumulates facet fluxes (volume * saturation) coming into the control volumes into the result vector\&. 
.PP
Reimplemented in \fBcsmp::ExplicitMassBasedTransport< dim, STP >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class STP> double \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::AdvectVariable (double time_interval, double cfl_multiplication_factor, bool apply_flux_balance_correction, bool update_pore_volumes)\fR [virtual]\fP"

.PP
single-phase transport ( 
.PP
\fBTodo\fP
.RS 4
NEEDS TO BECOME A VIRTUAL FUNCTION TEMPLATE) 
.RE
.PP
normally not needed

.PP
Single-phase transport in a non-divergent flow\&. The method is either first- or second-order accurate depending on the boolean flag that was set when the '\fBExplicitNodeCenteredFiniteVolumeTransport\fP' object was constructed\&.
.SH "Input Arguments"
.PP
The method acts on the supplied \fBModel\fP object and advects the transport variable in the current velocity field for the time interval that the user specifies as second method argument\&. 
.br

.PP
\fBReturns\fP
.RS 4
The advected transport variable is written back to the \fBModel\fP object\&. 
.br
.RE
.PP
.SH "Implementation"
.PP
The CFL_FACTOR is a multiplier that represents the maximum factor by which the diameter of the idealized spherical FV can be multiplied while the transport scheme is stable\&. 
.br
.SH "Messages"
.PP
For each completed advection increment the method writes a dot on the screen as a progress monitor\&.

.PP
\fBTodo\fP
.RS 4
(3) Needs timestep reduction and DIRICHLET inflow condition 
.RE
.PP

.PP
\fBParameters\fP
.RS 4
\fIcfl_multiplication_factor\fP ideally 0\&.1  
.br
\fIapply_flux_balance_correction\fP usually desirable 
.RE
.PP

.PP
Reimplemented from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class STP> void \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::AdvectVariable1stOrder (double time_increment, bool output_result_range)\fR [protected]\fP"

.PP
explicit conservative Explicit first-order advection algorithm of a passive conservative tracer\&. AdvectVariableFirstOrder() uses the upstream values of the advected variable to compose the solution in the result \fBvector<double>\fP managed by the ExplicitFiniteVolumeAlgorithm which performs a range check and writes the RESULT back to the \fBModel\fP\&. 
.br
.SH "Input Arguments"
.PP
Reference to the current model and the ExplicitFiniteVolumeAlgorithm as well as the time_increment for the transport step\&. This increment must fulfill the CFL criterion\&. 
.br
.SH "Implementation"
.PP
The method uses the ExplicitFiniteVolumeProcessor object in the accumulation of the finite-volume stencils, when it loops over the elements\&. 
.br
.SH "Application Examples"
.PP
Since it costs almost the same to compute the second-order accurate explicit solution, there is not much rational to use this method\&. 
.SS "template<uint32_t dim, template< uint32_t > class STP> void \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::AdvectVariableSingleStep (double time_increment, bool apply_flux_balance_correction, bool update_pore_volumes)\fR [virtual]\fP"
single-phase passive advection, does NOT return courant increment, single timestep calculation no checks are made for courant condition\&. Assumes external checks\&.

.PP
\fBAuthor\fP
.RS 4
: Julian E\&. Mindel (23-09-2013)
.RE
.PP
This method calculates a single timestep of transport, assumming nothing about the time interval it is "fed"\&. It will advect using that time interval, assuming the user has externally determined that this is the correct time interval length\&. In contrast with AdvectVariable(, this method does not break the time interval into sub-parts and guarantee stability\&. This also means that the courant increment is not checked for in this method (and should be, externally, of course)\&. 
.PP
Reimplemented from \fBcsmp::NodeCenteredFiniteVolumeTransport< dim >\fP\&.
.PP
Reimplemented in \fBcsmp::ExplicitMassBasedTransport< dim, STP >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class STP> void \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::AssignFluxBoundaryConditions (uint32_t var_comp_nr = \fR0\fP)\fR [protected]\fP, \fR [virtual]\fP"

.PP
as in base class but for a result vector Luat's fix 4/6/2020 
.PP
Reimplemented in \fBcsmp::ExplicitMassBasedTransport< dim, STP >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class STP> void \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::ComposeSolution (double time_interval, uint32_t var_comp_nr = \fR0u\fP)\fR [protected]\fP, \fR [virtual]\fP"

.PP
passive advection: gives transported variable at end of time_interval Computes the values of the transported variable at the new time-level (passive advection case)\&. \fBFluid\fP sources or sinks as well as in or out- fluxes at \fBModel\fP or region boundaries as well as poroelastic sources are also taken care off by consideration of FLUX_BALANCE vector\&. 
.br
.SH "Input Arguments"
.PP
The method needs access to the current transport model and two vectors which store the pore volume of each finite volume cell and the flux balance of that cell, respectively\&. The method further requires a \fBcsmp::Index\fP accessor to the transport variable in order to read current nodal values\&. Also, the current time-increment for the advection step needs to be specified in order to compose the solution\&. This time increment must satisfy the CFL condition, because this is an explicit transport scheme\&. 
.br
.SH "Implementation"
.PP
.SH "Application Examples"
.PP
For the passive advection of tracers\&. 
.PP
Reimplemented in \fBcsmp::ExplicitMassBasedTransport< dim, STP >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class STP> double \fBcsmp::ExplicitNodeCenteredFiniteVolumeTransport\fP< dim, STP >::OutputResults (const \fBPropertyDatabase\fP< dim > & p, const \fBcsmp::Index\fP & adv_key, bool show_range, uint32_t var_comp_nr = \fR0u\fP) const"

.PP
results are stored back wherever flags are not DIRICH Where the condition flag is not DIRICH, results are mapped from solution \fBvector<double>\fP back to finite volume cells after performing a range cheque\&.
.SH "Messages"
.PP
If the result is out of range at more than 10 nodes, an error message is returned\&. If errors occur at more than 2 per cent of the nodes, an 'out_of_range' exception is thrown\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
