.TH "csmp::SimulatorSetupParameter" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SimulatorSetupParameter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SimulatorSetupParameter\&.h>\fP
.PP
Inherits \fBcsmp::Parameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimulatorSetupParameter\fP (const \fBSimulatorSetupParameter\fP &p)"
.br
.ti -1c
.RI "\fBSimulatorSetupParameter\fP & \fBoperator=\fP (const \fBSimulatorSetupParameter\fP &p)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSimulatorSetupParameter\fP &p) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSimulatorSetupParameter\fP &p) const"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Parameter\fP
.in +1c
.ti -1c
.RI "\fBParameter\fP ()"
.br
.ti -1c
.RI "\fBParameter\fP (const \fBParameter\fP &)"
.br
.ti -1c
.RI "\fBParameter\fP & \fBoperator=\fP (const \fBParameter\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBcsmp::Parameter\fP &) const"
.br
.RI "comparitor (to verify uniqueness of a new parameter definition "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBcsmp::Parameter\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBcsmp::Parameter\fP &) const"
.br
.RI "less-than operator so that Parameters can be stored in STL associative containers "
.ti -1c
.RI "void \fBDefineFromStdin\fP ()"
.br
.RI "define a physical variable at runtime, using console input (stdin) "
.ti -1c
.RI "bool \fBIsWithinRange\fP (double) const"
.br
.RI "checks whether the supplied value lies within min/max defined for this parameter "
.ti -1c
.RI "void \fBRange\fP (double &vmin, double &vmax) const"
.br
.RI "expected range of this parameter in the specific simulation "
.ti -1c
.RI "double \fBMinValue\fP () const"
.br
.ti -1c
.RI "double \fBMaxValue\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "prints parameter record to screen "
.ti -1c
.RI "bool \fBOut\fP (std::fstream &fp) const"
.br
.RI "writes parameter record to a binary file "
.ti -1c
.RI "bool \fBIn\fP (std::fstream &fp)"
.br
.RI "reads parameter record from a binary file "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBvsize\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBplacement\fP"
.br
.in -1c

Public Attributes inherited from \fBcsmp::Parameter\fP
.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.RI "typically a human-readable name like 'fluid pressure' that can contain blanks (no tabs or line breaks) "
.ti -1c
.RI "std::string \fBnotation\fP"
.br
.RI "e\&.g\&., k for permeability, v for velocity etc\&. "
.ti -1c
.RI "std::string \fBunit\fP"
.br
.RI "normally SI unit like kg/m2 "
.ti -1c
.RI "double \fBmin\fP"
.br
.ti -1c
.RI "double \fBmax\fP"
.br
.RI "physically meaningful value range, specific to simulation problem "
.ti -1c
.RI "std::string \fBusage\fP"
.br
.RI "with regard to computation: INPUT, COMPUTED etc\&. "
.ti -1c
.RI "std::string \fBexplanation\fP"
.br
.RI "how property is used, e\&.g\&., stress calculation etc\&. "
.ti -1c
.RI "std::string \fBreference\fP"
.br
.RI "to a paper that describes a related calculation "
.ti -1c
.RI "\fBcsmp::Index\fP \fBkey\fP"
.br
.RI "variable accessor for this parameter as calculated and assigned by \fBPropertyDatabase\fP "
.in -1c
.SH "Detailed Description"
.PP 
Relates to the geothermal simulator application

.PP
\fBTodo\fP
.RS 4
documentation is needed (probably Julian Mindel)
.RE
.PP

.PP
\fBTodo\fP
.RS 4
SKM move to applications, geothermal energy storage simulator 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
