.TH "csmp::CRC3_RockType4" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CRC3_RockType4
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsComposite\fP () const"
.br
.ti -1c
.RI "double \fBKrw_ParallelDrainage\fP (double Sw, double ux) const"
.br
.ti -1c
.RI "double \fBKrn_ParallelDrainage\fP (double Sw, double ux) const"
.br
.ti -1c
.RI "double \fBKrw_CrossDrainage\fP (double Sw, double ux) const"
.br
.ti -1c
.RI "double \fBKrn_CrossDrainage\fP (double Sw, double ux) const"
.br
.ti -1c
.RI "double \fBPd\fP (double ux) const"
.br
.ti -1c
.RI "bool \fBIsComposite\fP () const"
.br
.ti -1c
.RI "double \fBKrw_ParallelDrainage\fP (double Sw, double ux) const"
.br
.ti -1c
.RI "double \fBKrn_ParallelDrainage\fP (double Sw, double ux) const"
.br
.ti -1c
.RI "double \fBKrw_CrossDrainage\fP (double Sw, double ux) const"
.br
.ti -1c
.RI "double \fBKrn_CrossDrainage\fP (double Sw, double ux) const"
.br
.ti -1c
.RI "double \fBPd\fP (double ux) const"
.br
.ti -1c
.RI "bool \fBIsComposite\fP () const"
.br
.ti -1c
.RI "double \fBKrw_ParallelDrainage\fP (double Sw, double ux) const"
.br
.RI "\fBWater\fP relative permeability\&. "
.ti -1c
.RI "double \fBKrn_ParallelDrainage\fP (double Sw, double ux) const"
.br
.RI "CO2 relative permeability: "
.ti -1c
.RI "double \fBKrw_CrossDrainage\fP (double Sw, double ux) const"
.br
.RI "\fBWater\fP relative permeability\&. "
.ti -1c
.RI "double \fBKrn_CrossDrainage\fP (double Sw, double ux) const"
.br
.RI "CO2 relative permeability: "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::string \fBname\fP = 'P\-Mst\-Slt'"
.br
.ti -1c
.RI "const int \fBrocktype_\fP = 4"
.br
.ti -1c
.RI "const int \fBsubtypes_\fP = 2"
.br
.ti -1c
.RI "const double \fBk_low_\fP = 1\&.73e\-15"
.br
.ti -1c
.RI "const double \fBk_high_\fP = 3\&.48e\-14"
.br
.ti -1c
.RI "const double \fBphi_\fP = 0\&.183"
.br
.ti -1c
.RI "const double \fBLY_low_\fP = 0\&.25"
.br
.ti -1c
.RI "const double \fBLY_high_\fP = 0\&.25"
.br
.ti -1c
.RI "const double \fBSwi_low_\fP = 0\&.39"
.br
.ti -1c
.RI "const double \fBSwi_high_\fP = 0\&.18"
.br
.ti -1c
.RI "const double \fBSwi_pc_\fP = 0\&.285"
.br
.ti -1c
.RI "const double \fBSgr_\fP = 0\&.41"
.br
.ti -1c
.RI "const double \fBm_low_\fP = 0\&.4"
.br
.ti -1c
.RI "const double \fBm_high_\fP = 0\&.5"
.br
.ti -1c
.RI "const double \fBm_\fP = 0\&.445"
.br
.ti -1c
.RI "const double \fBapd_\fP = 550\&."
.br
.ti -1c
.RI "const double \fBbpd_\fP = 0\&.001903616"
.br
.ti -1c
.RI "const double \fBcpd_\fP = \-0\&.58"
.br
.ti -1c
.RI "const double \fBdpd_\fP = 3300\&."
.br
.ti -1c
.RI "const double \fBpd_low_\fP = 5000\&."
.br
.ti -1c
.RI "const double \fBpd_high_\fP = 3000\&."
.br
.ti -1c
.RI "const double \fBpd_\fP = 3000\&."
.br
.ti -1c
.RI "const double \fBdPc_\fP = 2000\&."
.br
.ti -1c
.RI "const double \fBux_VL_\fP = 9\&.00e\-03"
.br
.ti -1c
.RI "const double \fBux_CL_\fP = 2\&.20e\-06"
.br
.ti -1c
.RI "const double \fBux_cross_VL_\fP = 3\&.00e\-03"
.br
.ti -1c
.RI "const double \fBux_cross_CL_\fP = 1\&.00e\-07"
.br
.ti -1c
.RI "const double \fBaw1_\fP = 0\&.39"
.br
.ti -1c
.RI "const double \fBbw1_\fP = 12088\&.38073"
.br
.ti -1c
.RI "const double \fBcw1_\fP = 1\&."
.br
.ti -1c
.RI "const double \fBdw1_\fP = 4\&.29"
.br
.ti -1c
.RI "const double \fBanw1_\fP = 0\&.31"
.br
.ti -1c
.RI "const double \fBbnw1_\fP = 0\&.009279014"
.br
.ti -1c
.RI "const double \fBcnw1_\fP = \-0\&.65"
.br
.ti -1c
.RI "const double \fBdnw1_\fP = 1\&.58"
.br
.ti -1c
.RI "const double \fBaw1_cross\fP = 4\&.2525"
.br
.ti -1c
.RI "const double \fBbw1_cross\fP = 3\&.6414e\-06"
.br
.ti -1c
.RI "const double \fBcw1_cross\fP = \-1\&."
.br
.ti -1c
.RI "const double \fBdw1_cross\fP = 3\&.45"
.br
.ti -1c
.RI "const double \fBanw1_cross\fP = 0\&.86"
.br
.ti -1c
.RI "const double \fBbnw1_cross\fP = 11489\&.62807"
.br
.ti -1c
.RI "const double \fBcnw1_cross\fP = 1\&."
.br
.ti -1c
.RI "const double \fBdnw1_cross\fP = 2\&.07"
.br
.ti -1c
.RI "const double \fBSwi_\fP = 0\&.38"
.br
.ti -1c
.RI "const double \fBSwi_cross\fP = 0\&.3458"
.br
.ti -1c
.RI "const double \fBux_VL_cross_\fP = 1\&.0e\-4"
.br
.ti -1c
.RI "const double \fBux_CL_cross_\fP = 1\&.0e\-7"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
