.TH "csmp::ExponentialFractureMatrixTransfer" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ExponentialFractureMatrixTransfer \- documentation in 'SKM_linear_diffusion_based_transfer_function\&.mw'  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ExponentialFractureMatrixTransfer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExponentialFractureMatrixTransfer\fP (double swi=0\&.05, double swc=0\&.05, double snr=0\&.14, double lambda=2\&.5, double pd=3000\&., double km=1\&.E\-15, double phi=0\&.25, double muw=1\&.E\-3, double mun=5\&.E\-3)"
.br
.ti -1c
.RI "double \fBCurrentTransferRate\fP (double t, double sw_matrix_avg, double sw_frac) const"
.br
.RI "T(t,sw_avg) "
.ti -1c
.RI "void \fBUpdateMatrixParameters\fP (double swi=0\&.05, double swc=0\&.05, double snr=0\&.14, double lambda=2\&.5, double pd=3000\&., double km=1\&.E\-15, double phi=0\&.25, double muw=1\&.E\-3, double mun=5\&.E\-3)"
.br
.in -1c
.SH "Detailed Description"
.PP 
documentation in 'SKM_linear_diffusion_based_transfer_function\&.mw' 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
