.TH "csmp::EclipseWellPathEntry" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::EclipseWellPathEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEclipseWellPathEntry\fP (const \fBijk\fP &cell, \fB::csmp::CORNER_POINT_CELL_FACE_INDEX\fP from, \fB::csmp::CORNER_POINT_CELL_FACE_INDEX\fP to)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBijk\fP \fBcell\fP"
.br
.ti -1c
.RI "\fB::csmp::CORNER_POINT_CELL_FACE_INDEX\fP \fBfrom\fP"
.br
.ti -1c
.RI "\fB::csmp::CORNER_POINT_CELL_FACE_INDEX\fP \fBto\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
