.TH "csmp::LineElementMesher< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::LineElementMesher< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <LineElementMesher\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBuildUniformMesh\fP (\fBVSet\fP< dim > &vset, double length, size_t n_elements, const std::vector< double > &splitnode_coordinates=std::vector< double >(), const \fBPoint\fP< dim > &origin=\fBPoint\fP< dim >(), const \fBPoint\fP< dim > &destination=\fBPoint\fP< dim >())"
.br
.RI "creates an uniform mesh; org & dest mark the desired end point coordinates of the mesh "
.ti -1c
.RI "void \fBBuildRefinedMesh\fP (\fBVSet\fP< dim > &vset, double length, double dx_min, double dx_max, double width_of_transition_zone, \fBMeshDensity\fP *density, const std::vector< double > &splitnode_coordinates=std::vector< double >(), const \fBPoint\fP< dim > &origin=\fBPoint\fP< dim >(), const \fBPoint\fP< dim > &destination=\fBPoint\fP< dim >())"
.br
.RI "creates a refined mesh "
.ti -1c
.RI "void \fBBuildCustomMesh\fP (\fBVSet\fP< dim > &vset, const std::vector< double > &node_coordinates, const std::vector< double > &splitnode_coordinates=std::vector< double >(), const \fBPoint\fP< dim > &origin=\fBPoint\fP< dim >(), const \fBPoint\fP< dim > &destination=\fBPoint\fP< dim >())"
.br
.RI "creates a custom mesh with \fBvector( 1D node coordinates )\fP "
.ti -1c
.RI "void \fBBuildCustomMesh\fP (\fBVSet\fP< dim > &vset, const std::vector< \fBPoint\fP< dim > > &node_coordinates, const std::vector< \fBPoint\fP< dim > > &splitnode_coordinates=std::vector< \fBPoint\fP< dim > >(), const \fBPoint\fP< dim > &origin=\fBPoint\fP< dim >(), const \fBPoint\fP< dim > &destination=\fBPoint\fP< dim >())"
.br
.RI "creates a custom mesh with \fBvector( 1D, 2D or 3D node coordinates )\fP "
.ti -1c
.RI "void \fBAssignCornerPoints\fP (\fBVSet\fP< dim > &vset, const \fBPoint\fP< dim > &origin, const \fBPoint\fP< dim > &destination)"
.br
.RI "Method which modifies already existing mesh\&. "
.ti -1c
.RI "void \fBInsertSplitNodes\fP (\fBVSet\fP< dim > &vset, const std::vector< double > &splitnodes)"
.br
.ti -1c
.RI "void \fBInsertSplitNodes\fP (\fBVSet\fP< dim > &vset, std::set< \fBPoint\fP< dim > > &splitnodes)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::LineElementMesher< dim >"Line element mesher: collection of functions\&.

.PP
Creates polyline meshes that of an arbitrary dimension (like a spiral in 3D space)\&. The meshes can contain duplicated nodes and INTERNAL boundaries\&.

.PP
\fBAttention\fP
.RS 4
Mesher does not assign \fBBOX_BOUNDARY\fP flags nor neighbor connectivity
.RE
.PP
\fBAuthor\fP
.RS 4
Stephan Matthai 

.PP
extended to work with mulit-dimensional models by Roman Manasipov 
.RE
.PP
\fBDate\fP
.RS 4
2002, 2012
.RE
.PP
\fBTodo\fP
.RS 4
ADD BOUNDARY FLAGS, \fBTOPOTYPE\fP, AND MATERIAL IDENTIFIERS TO VSET! 

.PP
create \fBNodeManifold\fP objects in case of a split boundary 

.PP
create \fBBOX_BOUNDARY\fP flags 

.PP
create neighbor connectivity 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::LineElementMesher\fP< dim >::AssignCornerPoints (\fBVSet\fP< dim > & vset, const \fBPoint\fP< dim > & origin, const \fBPoint\fP< dim > & destination)"

.PP
Method which modifies already existing mesh\&. Modifies the mesh based on the new coordinates of corner points without changing the connectivity of previously created mesh

.PP
\fBAuthor\fP
.RS 4
R\&. Manasipov 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::LineElementMesher\fP< dim >::BuildRefinedMesh (\fBVSet\fP< dim > & vset, double length, double dx_min, double dx_max, double width_of_transition_zone, \fBMeshDensity\fP * density, const std::vector< double > & splitnode_coordinates = \fRstd::vector<double>()\fP, const \fBPoint\fP< dim > & origin = \fR\fBPoint\fP<dim>()\fP, const \fBPoint\fP< dim > & destination = \fR\fBPoint\fP<dim>()\fP)"

.PP
creates a refined mesh create a mesh size gradient 
.SS "template<uint32_t dim> void \fBcsmp::LineElementMesher\fP< dim >::BuildUniformMesh (\fBVSet\fP< dim > & vset, double length, size_t n_elements, const std::vector< double > & splitnode_coordinates = \fRstd::vector<double>()\fP, const \fBPoint\fP< dim > & origin = \fR\fBPoint\fP<dim>()\fP, const \fBPoint\fP< dim > & destination = \fR\fBPoint\fP<dim>()\fP)"

.PP
creates an uniform mesh; org & dest mark the desired end point coordinates of the mesh creates a mesh in which all elements have the same length

.PP
\fBParameters\fP
.RS 4
\fIsplitnode_coordinates\fP location of splitboundaries, if any 
.br
\fIorigin\fP desired first corner point of the mesh 
.br
\fIdestination\fP desired end-point of the mesh 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
