.TH "csmp::BinaryFileSectionWrite" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::BinaryFileSectionWrite \- Helper class to write sections to a binary file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <binaryReadWrite\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryFileSectionWrite\fP (std::fstream &fp, const char *header)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper class to write sections to a binary file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
