.TH "csmp::GenericTransferFunction" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::GenericTransferFunction \- GTF, see doi 0\&.2118/121244-MS\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <GenericTransferFunction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericTransferFunction\fP (double phim, double pd, double BC_param, double muw, double mun)"
.br
.ti -1c
.RI "double \fBTransfer\fP (double sw_block, double sw_initial, double sw_farfield, double km, double block_radius) const"
.br
.ti -1c
.RI "double \fBkrw_BC\fP (double sw_eff) const"
.br
.ti -1c
.RI "double \fBkrn_BC\fP (double sw_eff) const"
.br
.ti -1c
.RI "double \fBLambda_w_BC\fP (double sw_eff) const"
.br
.ti -1c
.RI "double \fBLambda_n_BC\fP (double sw_eff) const"
.br
.ti -1c
.RI "double \fBLambdaTotal\fP (double sw_eff) const"
.br
.ti -1c
.RI "double \fBLambdaOverbar\fP (double sw_eff) const"
.br
.ti -1c
.RI "double \fBPc\fP (double sw) const"
.br
.ti -1c
.RI "double \fBdPcds\fP (double sw) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
GTF, see doi 0\&.2118/121244-MS\&. 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::GenericTransferFunction::Transfer (double sw_block, double sw_initial, double sw_farfield, double km, double block_radius) const"
Computes transfer rate assuming that fracture saturation of the invading phase is fixed=1\&. This approximation has to be seen in the context of the Af(sw) scaling which is subsequently applied to the transfer rate in the block\&.

.PP
\fBReturns\fP
.RS 4
flux (volume * saturation per second) of the defending phase 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
