.TH "csmp::PlacementAccessTraits< ELEMENT_INTEGRATION_POINT >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::PlacementAccessTraits< ELEMENT_INTEGRATION_POINT > \- ELEMENT_INTEGRATION_POINT uses CellVector() with ip access\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FieldVariable\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr bool \fBis_node\fP = false"
.br
.ti -1c
.RI "static constexpr bool \fBis_element\fP = true"
.br
.ti -1c
.RI "static constexpr bool \fBis_integration_point\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
ELEMENT_INTEGRATION_POINT uses CellVector() with ip access\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
