.TH "csmp::Index" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Index \- Accessor for discretized physical variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Index\&.h>\fP
.PP
Inherited by \fBcsmp::INDEX< SCALAR, NODE >\fP, \fBcsmp::INDEX< TENSOR, ELEMENT >\fP, \fBcsmp::INDEX< SCALAR, ELEMENT >\fP, \fBcsmp::INDEX< SCALAR, MODEL >\fP, \fBcsmp::INDEX< VECTOR, ELEMENT >\fP, \fBcsmp::INDEX< VECTOR, NODE >\fP, \fBcsmp::INDEX< SCALAR, FACET_INTEGRATION_POINT >\fP, \fBcsmp::INDEX< VECTOR, FACET_INTEGRATION_POINT >\fP, \fBcsmp::INDEX< SCALAR, SECTOR_INTEGRATION_POINT >\fP, \fBcsmp::INDEX< ARRAY, NODE >\fP, \fBcsmp::INDEX< SCALAR, INTER_FACE >\fP, \fBcsmp::INDEX< SCALAR, FACE >\fP, \fBcsmp::INDEX< VECTOR, FACE >\fP, \fBcsmp::INDEX< ARRAY, MODEL >\fP, \fBcsmp::INDEX< SCALAR, REGION >\fP, and \fBcsmp::INDEX< ty, pl >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBint_type\fP = \fBLocalVariables::int_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndex\fP ()"
.br
.ti -1c
.RI "\fBIndex\fP (\fBVARIABLE_TYPE\fP, \fBPLACEMENT\fP, int_type idx)"
.br
.ti -1c
.RI "\fBIndex\fP (\fBVARIABLE_TYPE\fP, \fBPLACEMENT\fP, int_type idx, int_type \fBdataDepth\fP, int_type \fBflagDepth\fP, int_type \fBdataOffset\fP, int_type \fBflagOffset\fP, const \fBLocalVariables\fP &, const \fBIntegrationPointVariables\fP &=\fBIntegrationPointVariables\fP(), int_type offsetFactorObject=0, int_type \fBoffsetFactorSector\fP=0, int_type ipFactorObject=0, int_type \fBipFactorSector\fP=0, int_type \fBipFactorFacet\fP=0)"
.br
.ti -1c
.RI "\fBIndex\fP (const \fBcsmp::Index\fP &)"
.br
.ti -1c
.RI "\fBIndex\fP (\fBcsmp::Index\fP &&)"
.br
.RI "move constructor that takes care of index tracker "
.ti -1c
.RI "\fB~Index\fP ()"
.br
.RI "DTor: Detaches intself from \fBIndexTracker\fP\&. "
.ti -1c
.RI "\fBIndex\fP & \fBoperator=\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Assignment operator\&. "
.ti -1c
.RI "\fBIndex\fP & \fBoperator=\fP (\fBcsmp::Index\fP &&)"
.br
.RI "move assignment operator "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBcsmp::Index\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBcsmp::Index\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBcsmp::Index\fP &) const"
.br
.ti -1c
.RI "bool \fBIsDefined\fP () const"
.br
.ti -1c
.RI "void \fBAttach\fP (\fBIndexTracker\fP *\fBindexTracker\fP)"
.br
.RI "Registers an \fBIndexTracker\fP (does not detach from current!) "
.ti -1c
.RI "void \fBDetach\fP ()"
.br
.RI "Detaches itself from \fBIndexTracker\fP (i\&.e\&. called upon destruction) "
.ti -1c
.RI "void \fBUpdateData\fP (const \fBcsmp::Index\fP &idx)"
.br
.RI "Updates to the data described by idx without updating indexTracker\&. "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.ti -1c
.RI "bool \fBOut\fP (std::fstream &fp) const"
.br
.ti -1c
.RI "bool \fBIn\fP (std::fstream &fp)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBplace\fP"
.br
.ti -1c
.RI "int_type \fBindex\fP = UNSPECIFIED"
.br
.RI "For Scalars, Vectors, Tensors, Arrays, FlaggedArrays: the how many'th variable of its kind at specified placement\&. "
.ti -1c
.RI "int_type \fBdataDepth\fP"
.br
.RI "Scalar:1 , Vector: dim, Tensor: dim*dim, Array:Size, FlaggedArray:Size\&. "
.ti -1c
.RI "int_type \fBflagDepth\fP"
.br
.RI "Scalar:1 , Vector: dim, Tensor: dim, Array:1, FlaggedArray:Size\&. "
.ti -1c
.RI "int_type \fBdataOffset\fP"
.br
.RI "\fBIndex\fP in data container where data start\&. "
.ti -1c
.RI "int_type \fBflagOffset\fP"
.br
.RI "\fBIndex\fP in flag container where data start\&. "
.ti -1c
.RI "int_type \fBoffsetFactorCell\fP"
.br
.RI "Factors used in integration point variable index arithmetic\&. "
.ti -1c
.RI "int_type \fBoffsetFactorSector\fP"
.br
.RI "Factors used in integration point variable index arithmetic\&. "
.ti -1c
.RI "int_type \fBipFactorCell\fP"
.br
.RI "Factors used in integration point variable index arithmetic\&. "
.ti -1c
.RI "int_type \fBipFactorSector\fP"
.br
.RI "Factors used in integration point variable index arithmetic\&. "
.ti -1c
.RI "int_type \fBipFactorFacet\fP"
.br
.RI "Factors used in integration point variable index arithmetic\&. "
.ti -1c
.RI "\fBLocalVariables\fP \fBlocalVariables\fP"
.br
.RI "Description of state of physical variables at given placement (variables count etc\&.\&.) "
.ti -1c
.RI "\fBIntegrationPointVariables\fP \fBintegrationPointVariables\fP"
.br
.RI "Description of state of physical variables at given placement (variables count etc\&.\&.) "
.ti -1c
.RI "\fBIndexTracker\fP * \fBindexTracker\fP"
.br
.RI "\fBIndexTracker\fP used for runtime updates of offsets (addition/removal of variables) "
.in -1c
.SH "Detailed Description"
.PP 
Accessor for discretized physical variables\&. 

Link between \fBPropertyDatabase\fP and \fBLocalVariableStorage\fP\&.

.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei 

.PP
P\&. Lang 

.PP
S\&. Geiger 

.PP
Stephen G\&. Roberts
.RE
.PP
.SH "Motivation"
.PP
Class encapsulates the three values that are required to retrieve a CSP variable from a model based on an unstructured mesh: The Type() distinguishes scalars, vectors and tensors from one-another since these have different storage requirements\&.

.PP
The Place() specifies whether a variable is discretized on the nodes, elements, faces or on constraint points\&. This has implications as to how the variable is interpolated over the model domain\&.

.PP
The \fBIndex()\fP is used internally by CSMP for housekeeping\&. It corresponds to the number that the variable has in an alphabetically ordered map of variables of the same type and placement, in the same model\&.
.SH "Design Intent"
.PP
Create a universal accessor for discretized physical variables in a model\&.
.SH "Applicability"
.PP
Typically, a \fBcsmp::Index\fP or \fBIndex\fP object is initialized only once before it is used as an accessor to variables in a model\&. The initialization is done by the \fBPropertyDatabase\fP if so requested\&.

.PP
\fBIndex\fP is applicable whereever the parallel structure \fBcsmp::Index\fP is applicable\&. The reason, why a class is present in addition to the structure is that this allows to assign default values when indices are constructed\&.
.SH "Collaborations"
.PP
\fBIndex\fP is known to the \fBPropertyDatabase\fP and all variable accessor and mutator functions\&. It is used by \fBPropertyHandle\fP and \fBOperand\fP objects, as well as Interrelations, Visitors and Algorithms to housekeep currently used variables\&.
.SH "Implementation"
.PP
Both as struct \fBcsmp::Index\fP and this class\&.
.SH "Application Examples"
.PP
To get an \fBIndex\fP for a variable of interest in order to perform a computation, do the following:

.PP
.PP
.nf
Index variable_key = prop_database\&.StorageKey("variable");
.fi
.PP

.PP
\fBTodo\fP
.RS 4
SKM: (3-F) complete scheme for compile-time variables
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::Index::Index ()"
Default constructor

.PP
Assigns an \fBIndex\fP of scalar type on the model\&. The index number itself will be set to the maximum and hence interpreted as not defined\&. Inline implementation\&. 
.SS "csmp::Index::Index (\fBVARIABLE_TYPE\fP ty, \fBPLACEMENT\fP pl, int_type idx)"
Custom constructor

.PP
Neither sets local nor integration point variables and has no option for offsets/depth ( i\&.e\&. = 0 )

.PP
Assigns an \fBIndex\fP with defined type and placement\&. Inline implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fIty\fP the variable type 
.br
\fIpl\fP the placement 
.br
\fIidx\fP the index 
.RE
.PP

.SS "csmp::Index::Index (\fBVARIABLE_TYPE\fP ty, \fBPLACEMENT\fP pl, int_type idx, int_type datadepth, int_type flagdepth, int_type dataoffset, int_type flagoffset, const \fBLocalVariables\fP & lvs, const \fBIntegrationPointVariables\fP & ivs = \fR\fBIntegrationPointVariables\fP()\fP, int_type offsetfactorsimplex = \fR0\fP, int_type offsetfactorsector = \fR0\fP, int_type ipfactorsimplex = \fR0\fP, int_type ipfactorsector = \fR0\fP, int_type ipfactorfacet = \fR0\fP)"
Custom constructor

.PP
This should be goto ctor, even though members may be initialized individually through struct Assigns an \fBIndex\fP with defined type and placement\&. Inline implementation\&.

.PP
\fBParameters\fP
.RS 4
\fIty\fP the variable type 
.br
\fIpl\fP the placement 
.br
\fIidx\fP the index 
.br
\fIdatadepth\fP component count, size of variable (scalar 1, vector 2, tensor 3, array #components) 
.br
\fIdataoffset\fP Offset in of data in variable storage container (implicit dependence on \fBLocalVariableStorage\fP) 
.br
\fIflagoffset\fP Offset in of flag data in variable storage container (implicit dependence on \fBLocalVariableStorage\fP) 
.br
\fIlvs\fP \fBLocalVariables\fP of placement pl 
.br
\fIivs\fP \fBIntegrationPointVariables\fP of elements 
.RE
.PP

.SS "csmp::Index::Index (const \fBcsmp::Index\fP & idx)"
Copy constructor

.PP
Creates an index based on the provided parameter 
.PP
\fBParameters\fP
.RS 4
\fIidx\fP an existing \fBcsmp::Index\fP object 
.RE
.PP
\fBAttention\fP
.RS 4
asserting specific offsets cannot be done here where the Indices are constructed because they are calculated and assigned later after they keys have been registered with the database\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool csmp::Index::In (std::fstream & fp)"

.PP
\fBTodo\fP
.RS 4
(1-C) Meaningless return statement 
.RE
.PP

.SS "bool csmp::Index::IsDefined () const"
Boolean Function that checks if object has been defined

.PP
\fBReturns\fP
.RS 4
true if an index has been assigned 
.RE
.PP

.SS "bool csmp::Index::operator!= (const \fBcsmp::Index\fP & i) const"
Boolean equals not operator

.PP
\fBReturns\fP
.RS 4
boolean result of the comparison 

.PP
true if not equal 
.RE
.PP

.SS "bool csmp::Index::operator< (const \fBcsmp::Index\fP & i) const"
comparator less

.PP
Provides required functionality for use in an STL container\&.

.PP
\fBAttention\fP
.RS 4
Do not use this as an example for how to code since it deduces information at runtime which should already be known at compile time\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIi\fP a \fBcsmp::Index\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true if smaller than argument 
.RE
.PP

.SS "\fBIndex\fP & csmp::Index::operator= (const \fBcsmp::Index\fP & idx)"

.PP
Assignment operator\&. attach itself to \fBIndexTracker\fP and vice versa\&.
.SS "\fBIndex\fP & csmp::Index::operator= (\fBcsmp::Index\fP && idx)"

.PP
move assignment operator attach itself to \fBIndexTracker\fP and vice versa\&.
.SS "bool csmp::Index::operator== (const \fBcsmp::Index\fP & i) const"
Boolean equals operator

.PP
\fBParameters\fP
.RS 4
\fIi\fP an \fBcsmp::Index\fP object 
.RE
.PP
\fBReturns\fP
.RS 4
boolean result of the comparison 

.PP
true if equal 
.RE
.PP

.SS "void csmp::Index::Out () const"
CSMP output feature

.PP
\fBOut()\fP returns all the internal data that \fBIndex\fP needs to access variables\&. These include the type and placement of a variable in the finite element mesh and the associated data storage index for the CSMP 'MemoryManager'\&. 
.SS "bool csmp::Index::Out (std::fstream & fp) const"

.PP
\fBTodo\fP
.RS 4
(1-C) Meaningless return statement 
.RE
.PP

.SS "void csmp::Index::UpdateData (const \fBcsmp::Index\fP & idx)"

.PP
Updates to the data described by idx without updating indexTracker\&. 
.PP
\fBAuthor\fP
.RS 4
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
9/26/2012
.RE
.PP
\fBParameters\fP
.RS 4
\fIidx\fP The index to be updated from 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
