.TH "csmp::TriplePointNaCl" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TriplePointNaCl \- Temperature-Pressure-Composition coordinates of NaCl Triple \fBPoint\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TriplePointNaCl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBTemperature\fP () const"
.br
.ti -1c
.RI "double \fBPressure\fP () const"
.br
.ti -1c
.RI "double \fBCompositionVapor\fP () const"
.br
.ti -1c
.RI "double \fBCompositionLiquid\fP () const"
.br
.ti -1c
.RI "double \fBCompositionHalite\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Temperature-Pressure-Composition coordinates of NaCl Triple \fBPoint\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
