.TH "csmp::ThreephaseHLV" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ThreephaseHLV
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreephaseHLV\fP (const double &externaltemperature)"
.br
.RI "Pressure-temperature coordinates of threephase Halite+Liquid+Vapor coexistence\&. "
.ti -1c
.RI "double \fBTemperature\fP () const"
.br
.ti -1c
.RI "double \fBPressure\fP ()"
.br
.ti -1c
.RI "double \fBDPressureDT\fP ()"
.br
.ti -1c
.RI "double \fBTmax\fP ()"
.br
.ti -1c
.RI "double \fBPmax\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
