.TH "csmp::TestSingleton" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TestSingleton
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::GenericSingleton< TestSingleton >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBGenericSingleton< TestSingleton >\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBcsmp::GenericSingleton< TestSingleton >\fP
.in +1c
.ti -1c
.RI "static \fBSingletonType\fP & \fBInstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
