.TH "csmp::Rock" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Rock
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRock\fP (double heatcapacity)"
.br
.ti -1c
.RI "double \fBHeatCapacity\fP (double t)"
.br
.ti -1c
.RI "double \fBMinimumHeatCapacity\fP ()"
.br
.ti -1c
.RI "double \fBEnthalpy\fP (double t)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
