.TH "csmp::Mute" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Mute \- Allows redirection of the output streams cout and cerr from the screen to null (output goes nowhere) and file (ascii file)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Mute\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Mute\fP ()"
.br
.RI "Dtor does not reinstate ostream\&. "
.ti -1c
.RI "bool \fBNull\fP (std::ostream &)"
.br
.RI "inactivates output to given stream "
.ti -1c
.RI "bool \fBFile\fP (std::ostream &, const char *text_file)"
.br
.RI "redirects output to text file "
.ti -1c
.RI "bool \fBReinstate\fP (std::ostream &)"
.br
.RI "brings back original settings "
.ti -1c
.RI "bool \fBRedirected\fP () const"
.br
.RI "releases redirection to file "
.in -1c
.SH "Detailed Description"
.PP 
Allows redirection of the output streams cout and cerr from the screen to null (output goes nowhere) and file (ascii file) 

Class is used to suppress output on systems where the user has no access to the console and/or where sceen output would dramatically slow the computations\&.

.PP
Only a single stream can be handled by an instance, so return values will reflect that\&.

.PP
Application example: 
.PP
.nf
Mute mute;
cout << "\\nMute mode\&.\&.\&.\\n";
mute\&.Null(cout); // or i\&.e\&. mute\&.File( cout, "Output\&.txt");

// \&.\&.\&. here goes the main code with supressed output

mute\&.Reinstate(cout);

.fi
.PP

.PP
a note 'just in case': if you want to supress samg output too, call following for \fBSAMG_Settings\fP instance (here 'settings') 
.PP
.nf
settings\&.Set_idmp(\-1);
settings\&.Set_iout1(\-1);
settings\&.Set_iout2(\-1);

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "bool csmp::Mute::File (std::ostream & os, const char * text_file)"

.PP
redirects output to text file Redirects to file, returns false if stream already redirected, true if redirection successful\&. 
.SS "bool csmp::Mute::Null (std::ostream & os)"

.PP
inactivates output to given stream Redirects to null stream, returns false if stream already redirected, true if redirection successful\&. 
.SS "bool csmp::Mute::Reinstate (std::ostream & os)"

.PP
brings back original settings Reinstates screen output, returns false if no redirection current, true if reinstation successful\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
