.TH "csmp::ExplicitTransport< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ExplicitTransport< dim > \- For implicit transport calculations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ExplicitTransport\&.h>\fP
.PP
Inherits \fBcsmp::variables::VariableSet_TracerTransfer\fP, \fBcsmp::FluxEvaluator< dim, ExplicitTransport >\fP, and \fBcsmp::TimeStepEvaluator< dim, ExplicitTransport >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExplicitTransport\fP (\fBModel\fP< dim > &, const std::string &target_region)"
.br
.RI "constructor for target region; by default all driving forces are considered; "
.ti -1c
.RI "void \fBUpdateFluxesAndFluxBalances\fP ()"
.br
.RI "initialises transport class for current pressure/velocity/transport variable field "
.ti -1c
.RI "double \fBTimeIncrement\fP () const"
.br
.RI "computes the time constraint "
.ti -1c
.RI "void \fBAdvectVariable\fP (double time_interval)"
.br
.RI "executes incremental time-stepping (a suitable time increment is computed by scheme) "
.ti -1c
.RI "double \fBIncomingVolumetricFlow\fP () const"
.br
.ti -1c
.RI "double \fBOutgoingVolumetricFlow\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::variables::VariableSet_TracerTransfer\fP
.in +1c
.ti -1c
.RI "template<uint32_t dim> \fBVariableSet_TracerTransfer\fP (const \fBPropertyDatabase\fP< dim > &db)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::FluxEvaluator< dim, ExplicitTransport >\fP
.in +1c
.ti -1c
.RI "void \fBAdvective_O1_FluxesAndBalances\fP (\fBElement\fP< dim > *const) const"
.br
.RI "computes F = (A_i vD \&. n_i) and its products with the upstream C0 on all facets, also computes FV flux balances "
.ti -1c
.RI "void \fBVolumetricFlowAndTransportVariableFluxBalances\fP (\fBModelSubDomain\fP< dim, CELL > &, std::vector< CELL< dim > * > &halo_stencils)"
.br
.RI "computes volumetric flows and (chemical) fluxes across facets using FacetFlux (facet flux) and stores them in target region "
.ti -1c
.RI "void \fBFluxBalancesAtBoundary\fP (\fBNode\fP< dim > *const) const"
.br
.RI "computes flux balances on boundary FVs, using precomputed facet fluxes; volumetric balances are set to zero "
.ti -1c
.RI "void \fBTransportVariableFluxes\fP (\fBElement\fP< dim > *const) const"
.br
.RI "computes first-order facet fluxes, F = ff * C0; ff=(pre-computed) volumetric flow, C0=transport variable "
.ti -1c
.RI "void \fBTransportVariableFluxesAndBalances\fP (\fBElement\fP< dim > *const) const"
.br
.RI "like \fBTransportVariableFluxes()\fP, but computes FV balances of F as well, storing them in 'accumulation'\&. "
.ti -1c
.RI "void \fBFluxBalancesFromFacetFluxes\fP (\fBNode\fP< dim > *const) const"
.br
.RI "computes balance of transport variable fluxes from precomputed facet fluxes and transport variable "
.ti -1c
.RI "double \fBFluxBalanceAndOutFlow\fP (\fBNode\fP< dim > *const) const"
.br
.RI "stores FV flux balances computed from current facet fluxes and C0 concentrations; returns outflow from cell "
.ti -1c
.RI "double \fBInFlow\fP (const \fBNode\fP< dim > *const) const"
.br
.RI "computes the volumetric flow into the current cell; "
.ti -1c
.RI "double \fBOutFlow\fP (const \fBNode\fP< dim > *const) const"
.br
.RI "computes the volumetric flow outside of the current cell; "
.ti -1c
.RI "double \fBVolumetricFlowBalance\fP (const \fBNode\fP< dim > *const) const"
.br
.RI "computes the volumetric flow outside of the current cell; "
.in -1c

Public Member Functions inherited from \fBcsmp::TimeStepEvaluator< dim, ExplicitTransport >\fP
.in +1c
.ti -1c
.RI "\fBTimeStepEvaluator\fP (double step_size_reduction_factor=0\&.5, double max_time_increment=86400\&. *365\&.)"
.br
.ti -1c
.RI "double \fBOutFlowLessThanContentIncrement\fP (\fBNode\fP< dim > *const, double outflow) const"
.br
.RI "returns robust delta_t criterion in the presence of fluid sources and sinks; also computes and stores flux balance "
.ti -1c
.RI "double \fBOutFlowLessThanContentIncrementBoundary\fP (const \fBNode\fP< dim > *const, double outflow) const"
.br
.RI "returns robust delta_t criterion in the presence of fluid sources and sinks at model boundary (no variables are touched) "
.ti -1c
.RI "double \fBStreamlineCFL\fP (const \fBElement\fP< dim > *const) const"
.br
.RI "anisotropic CFL for the strictly hyperbolic case; also computes and stores flux balance "
.ti -1c
.RI "void \fBStepSizeReductionFactor\fP (double=0\&.5)"
.br
.RI "adjust setting for the solve (default=0\&.5) "
.ti -1c
.RI "double \fBMaxTimeIncrement\fP () const"
.br
.RI "return maximum time-increment that is applied if there is ~no flow "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const VariableSet_TracerTransfer & \fBNotation\fP"
.br
.RI "shorthand to get to variable names "
.in -1c

Public Attributes inherited from \fBcsmp::variables::VariableSet_TracerTransfer\fP
.in +1c
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_out_\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_acc_\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_CT\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_PF0\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_FVPV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_FB\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, SECTOR_INTEGRATION_POINT > \fBkey_SPV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, SECTOR_INTEGRATION_POINT > \fBkey_SV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_NQV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_QV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_PF\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_k\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_kk\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, FACET_INTEGRATION_POINT > \fBkey_fAk\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, FACET_INTEGRATION_POINT > \fBkey_fn\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_THI\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_V\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_MU\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_RHO\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_C\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_C0\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_C1\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_K\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_KK\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_D\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_ffC\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_ff\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_fA\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_PHI\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBExplicitTransport_Test\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::ExplicitTransport< dim >"For implicit transport calculations\&. 

Single-phase flow tracer, heat or other transport, taking into account the thickness attribute of lower-dimensional elements in the flux calculations\&.

.PP
\fBAttention\fP
.RS 4
terminology is super important:
.IP "\(bu" 2
flux refers to the total quantity that passes through the surface, i\&.e\&. (v \&. n_i) * A_i, where subscript i refers to the finite volume facet
.IP "\(bu" 2
volume flux - refers to volumetric flow
.IP "\(bu" 2
flux - refers to products of the advected quantity and the volumetric flow
.PP
.RE
.PP
flux balance - sum over all finite-volume facet fluxes

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
25/6/2015
.RE
.PP
\fBCopyright\fP
.RS 4
Stephan K\&. Matthai
.RE
.PP
TODO: account for the effects of potential element based 'fluid volume source' terms\&. TODO: return rates of solute influx/outflux into/from the model double InFlux() const; double OutFlux() const; TODO: add choice of transport scheme: 1st versus 2nd order in space TODO: Generalise scheme so that it can handle \fBFace\fP and \fBInterFace\fP objects

.PP
Part of the Colleoli transport scheme\&. 
.PP
\fBAuthor\fP
.RS 4
Stephan K\&. Matthai 
.RE
.PP
\fBVersion\fP
.RS 4
1a 
.RE
.PP
\fBDate\fP
.RS 4
21/2/2013 
.RE
.PP
\fBPrecondition\fP
.RS 4
high-level class depending on CSMP++ API 
.RE
.PP
\fBWarning\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
Stephan K\&. Matthai 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::ExplicitTransport\fP< dim >::ExplicitTransport (\fBModel\fP< dim > & m, const std::string & target_region)"

.PP
constructor for target region; by default all driving forces are considered; 
.PP
\fBAttention\fP
.RS 4
if there is a velocity field, it is used to initialise facet fluxes
.RE
.PP
Custom constructor using an existing model and the default values of the policy classes\&. Halo stencils are created when the computaitonal region is smaller than the model\&. Finite volume and sector volumes are initialised\&. Facet fluxes and flux balances are initialised if the 'velocity' is initialised\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::ExplicitTransport\fP< dim >::AdvectVariable (double time_interval)"

.PP
executes incremental time-stepping (a suitable time increment is computed by scheme) 
.IP "1." 4
\fBElement\fP by element computation of (velocity), facet fluxes, flux balances and tracer balances
.IP "2." 4
Evaluation of time increment
.IP "3." 4
Assembly of solution
.IP "4." 4
Assignment of boundary conditions (treatment of truncated FVs at the boundary)
.IP "5." 4
tranfer of results into 'concentration', vacating 'new concentration' for next assembly\&. 
.PP

.SS "template<uint32_t dim> double \fBcsmp::ExplicitTransport\fP< dim >::IncomingVolumetricFlow () const"
Reports the volumetric flow into the computational region\&. 
.SS "template<uint32_t dim> double \fBcsmp::ExplicitTransport\fP< dim >::OutgoingVolumetricFlow () const"
Reports the volumetric flow outside of the computational region\&.

.PP
\fBTodo\fP
.RS 4
SKM check whether the variable 'outflow' can be used for this, saving some computations\&. 
.RE
.PP

.SS "template<uint32_t dim> double \fBcsmp::ExplicitTransport\fP< dim >::TimeIncrement () const"

.PP
computes the time constraint Computation of time increment (default limited to 1 year)\&.

.PP
\fBAttention\fP
.RS 4
Assumes that the facet flows and tracer fluxes are initialised\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::ExplicitTransport\fP< dim >::UpdateFluxesAndFluxBalances ()"

.PP
initialises transport class for current pressure/velocity/transport variable field initialises transport class for current pressure/velocity/transport variable field\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
