.TH "csmp::IntegrationPointCount" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::IntegrationPointCount \- Data class that tracks number of element/facet/sector integration points in Element/Face/InterFace\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IntegrationPointCount\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntegrationPointCount\fP (uint32_t siIntegrationPoints, uint32_t seIntegrationPoints, uint32_t faIntegrationPoints)"
.br
.ti -1c
.RI "\fBIntegrationPointCount\fP & \fBoperator=\fP (const \fBIntegrationPointCount\fP &ipc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsimplexIntegrationPoints\fP"
.br
.ti -1c
.RI "uint32_t \fBsectorIntegrationPoints\fP"
.br
.ti -1c
.RI "uint32_t \fBfacetIntegrationPoints\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data class that tracks number of element/facet/sector integration points in Element/Face/InterFace\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
