.TH "csmp::SparseMatrix" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SparseMatrix \- For the accumulation of element matrices in finite element calculations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SparseMatrix\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< std::map< size_t, double > >::const_iterator \fBrowsConstIterator\fP"
.br
.ti -1c
.RI "typedef std::map< size_t, double >::const_iterator \fBcolsConstIterator\fP"
.br
.ti -1c
.RI "typedef std::vector< std::map< size_t, double > >::iterator \fBrowsIterator\fP"
.br
.ti -1c
.RI "typedef std::map< size_t, double >::iterator \fBcolsIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSparseMatrix\fP (size_t m_x_n)"
.br
.ti -1c
.RI "\fBSparseMatrix\fP (const \fBSparseMatrix\fP &)"
.br
.ti -1c
.RI "\fBSparseMatrix\fP (\fBSparseMatrix\fP &&)"
.br
.ti -1c
.RI "\fBSparseMatrix\fP & \fBoperator=\fP (const \fBSparseMatrix\fP &)"
.br
.ti -1c
.RI "\fBSparseMatrix\fP & \fBoperator=\fP (\fBSparseMatrix\fP &&)"
.br
.ti -1c
.RI "\fBSparseMatrix\fP & \fBoperator+=\fP (const \fBSparseMatrix\fP &)"
.br
.ti -1c
.RI "double \fBoperator()\fP (size_t, size_t) const"
.br
.RI "operator accumulates sparse matrices\&. Initially created for OpenMP features\&. "
.ti -1c
.RI "double \fBAt\fP (size_t, size_t) const"
.br
.RI "range-checked accessor for matrix elements "
.ti -1c
.RI "void \fBResize\fP (size_t n_x_m, bool preserve_allocated_memory=true)"
.br
.RI "resets the rows=columns of the square matrix, retaining potential extra capacity of the vector used "
.ti -1c
.RI "size_t \fBEntries\fP () const"
.br
.RI "reports the non-zero elements currently stored in the sparse matrix "
.ti -1c
.RI "size_t \fBRows\fP () const"
.br
.ti -1c
.RI "size_t \fBCols\fP () const"
.br
.ti -1c
.RI "rowsConstIterator \fBBegin\fP () const"
.br
.RI "iterator over the matrix rows "
.ti -1c
.RI "rowsConstIterator \fBEnd\fP () const"
.br
.RI "iterator over the rows of the matrix "
.ti -1c
.RI "colsConstIterator \fBRowBegin\fP (size_t i) const"
.br
.ti -1c
.RI "colsConstIterator \fBRowEnd\fP (size_t i) const"
.br
.ti -1c
.RI "void \fBRemoveHalo\fP (int32_t nrhalo)"
.br
.RI "zeroing out rows in the context of parallel computations "
.ti -1c
.RI "bool \fBHasEntry\fP (size_t i, size_t j) const"
.br
.ti -1c
.RI "void \fBRemoveEntry\fP (size_t, size_t)"
.br
.RI "remove a single element from the matrix "
.ti -1c
.RI "void \fBErase\fP ()"
.br
.ti -1c
.RI "void \fBZero\fP ()"
.br
.ti -1c
.RI "void \fBZeroRow\fP (size_t row)"
.br
.ti -1c
.RI "void \fBZeroColumn\fP (size_t col)"
.br
.RI "beware! - this is not an efficient operation "
.ti -1c
.RI "void \fBAdd\fP (size_t, size_t, double val)"
.br
.RI "more efficient additions to matrix than attainable with operator() "
.ti -1c
.RI "void \fBAssign\fP (size_t, size_t, double val)"
.br
.ti -1c
.RI "void \fBMultiplyEntryWith\fP (size_t i, size_t j, double val)"
.br
.RI "multiply an element of the matrix with val; if result is zero, the element is eliminated "
.ti -1c
.RI "void \fBMultiplyWith\fP (const std::vector< double > &vec, std::vector< double > &res)"
.br
.ti -1c
.RI "void \fBColumnIndices\fP (size_t row, std::vector< size_t > &indices) const"
.br
.RI "returns j's of non-zero column entries in row "
.ti -1c
.RI "size_t \fBRecountEntries\fP () const"
.br
.RI "if suspected that a recent operation modified number of entries "
.ti -1c
.RI "double \fBInfinityNorm\fP () const"
.br
.ti -1c
.RI "bool \fBSymmetric\fP () const"
.br
.ti -1c
.RI "bool \fBZeroesInDiagonal\fP () const"
.br
.ti -1c
.RI "bool \fBDiagonallyPositive\fP () const"
.br
.RI "if there are negative elements in the diagonal of the matrix "
.ti -1c
.RI "void \fBSparsityPattern\fP (const char *txtfile) const"
.br
.RI "writes text matrix of zero's and one's to visualise sparsity pattern "
.ti -1c
.RI "template<class cspMat1, class cspMat2> void \fBAssign\fP (const cspMat1 &idx, const cspMat2 &data)"
.br
.RI "inserts (\fBDenseMatrix\fP) 'data' in sparse matrix at location identified by position matrix 'idx' "
.ti -1c
.RI "void \fBOutCompressedRowFormat\fP (int32_t *ia, int32_t *ja, double *a, bool reallocate=true) const"
.br
.RI "output in the form of C-style arrays indexed 0\&.\&.\&.n-1 "
.ti -1c
.RI "void \fBOutCompressedRowFormat\fP (long *ia, long *ja, double *a, bool reallocate=true) const"
.br
.RI "This is the version which is used for the old AMG solver\&. "
.ti -1c
.RI "void \fBOutCompressedRowFormat1_n\fP (int32_t *ia, int32_t *ja, double *a, bool reallocate=true) const"
.br
.RI "output to Fortran arrays indexed 1\&.\&.\&.n "
.ti -1c
.RI "void \fBOutCompressedRowFormatParallel\fP (std::vector< int32_t > &, std::vector< int32_t > &, std::vector< double >, int32_t, bool) const"
.br
.ti -1c
.RI "void \fBIn\fP (const char *file_name_without_extension)"
.br
.RI "read (square) matrix from text file with zeros "
.ti -1c
.RI "void \fBOut\fP (long precis=5L) const"
.br
.ti -1c
.RI "void \fBOut\fP (const char *file) const"
.br
.ti -1c
.RI "void \fBOutForMatlab\fP (const char *file) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
For the accumulation of element matrices in finite element calculations\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 
.RE
.PP
\fBDate\fP
.RS 4
2001 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void csmp::SparseMatrix::Assign (size_t i, size_t j, double val)"
Assigns value to the i,j'th element in the matrix, overwriting any value that might have resided there before\&. 
.SS "void csmp::SparseMatrix::ColumnIndices (size_t row, std::vector< size_t > & indices) const"

.PP
returns j's of non-zero column entries in row Returns the indices j of non-zero column elements in the row of interest\&.

.PP
\fBParameters\fP
.RS 4
\fIrow\fP of interest 
.br
\fIindices\fP is the vector into which the columns where the non-zero elements reside are returned 
.RE
.PP

.SS "double csmp::SparseMatrix::operator() (size_t i, size_t j) const"

.PP
operator accumulates sparse matrices\&. Initially created for OpenMP features\&. standard accessor of matrix elements (asserts i,j in debug mode) 
.SS "\fBSparseMatrix\fP & csmp::SparseMatrix::operator+= (const \fBSparseMatrix\fP & mat)"
Operator accumulates sparse matrices\&. Initially created for OpenMP features\&. All need to have the same number of row entries\&. \fBColumn\fP entries may be differenct 
.PP
\fBAuthor\fP
.RS 4
Julian E\&. Mindel 
.RE
.PP

.SS "void csmp::SparseMatrix::Out (long digits = \fR5L\fP) const"
Prints matrix dimensions, # of non-zero elements and (non-zero) entries row by row\&. Each entry is prefaced by its column index\&. 
.SS "void csmp::SparseMatrix::OutCompressedRowFormat1_n (int32_t * ia, int32_t * ja, double * a, bool reallocate = \fRtrue\fP) const"

.PP
output to Fortran arrays indexed 1\&.\&.\&.n IN ORDER TO IDENTIFY EACH ELEMENT IN A, THE USER HAS TO PROVIDE TWO integer ARRAYS IA AND JA\&. IF NNU DENOTES THE TOTAL NUMBER OF UNKNOWNS, THE NON-ZERO ENTRIES OF ANY ROW I OF L (1<=I<=NNU) ARE STORED IN A(J) WHERE THE RANGE OF J IS GIVEN BY 
.PP
.nf
         IA(I) <= J <= IA(I+1)-1\&.

.fi
.PP

.PP
THUS, IA(I) POINTS TO THE POSITION OF THE DIAGONAL ENTRY OF ROW I WITHIN THE VECTOR A\&. IN PARTICULAR, 
.PP
.nf
         IA(1) = 1 ,  IA(NNU+1) = 1 + NNA

.fi
.PP

.PP
WHERE NNA DENOTES THE TOTAL NUMBER OF MATRIX ENTRIES STORED\&. THE POINTER VECTOR JA HAS TO BE DEFINED SUCH THAT ANY ENTRY A(J) CORRESPONDS TO THE UNKNOWN U(JA(J)), I\&.E\&., JA(J) identifies THE COLUMN \fBINDEX\fP OF A(J)\&. IN PARTICULAR, A(IA(I)) IS THE DIAGONAL ENTRY OF ROW I AND CORRESPONDS TO THE UNKNOWN U(I): JA(IA(I))=I\&.

.PP
IN THIS TERMINOLOGY, THE I-TH EQUATION READS AS FOLLOWS (FOR ANY I WITH 1\&.LE\&.I\&.LE\&.NNU): 
.PP
.nf
      F(I) =        SUM      A(J) * U(JA(J))

               J1 <= J <= J2

.fi
.PP

.PP
WHERE F(I) DENOTES THE I-TH COMPONENT OF THE RIGHT HAND SIDE AND 
.PP
.nf
          J1 = IA(I) ,  J2 = IA(I+1)-1\&. 

.fi
.PP

.PP
NOTES: THE ENTRY IA(NNU+1) HAS TO POINT TO THE FIRST FREE ENTRY IN VECTORS A AND JA, RESPECTIVELY\&. OTHERWISE, AMG CANNOT KNOW THE LENGTH OF THE LAST MATRIX ROW\&.

.PP
THE INPUT VECTORS A, IA AND JA ARE CHANGED BY AMG1R5 SO, AFTER RETURN FROM AMG1R5, THE PACKAGE MUST NOT BE CALLED A SECOND TIME WITHOUT HAVING NEWLY DEFINED THE INPUT VECTORS AND USING ISWTCH=4\&. OTHERWISE, THE SETUP PHASE WILL FAIL\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
