.TH "csmp::ModelSubDomain_Test" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ModelSubDomain_Test
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ModelSubDomain_Test\&.h>\fP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.ti -1c
.RI "bool \fBTest_EstablishNeighborConnectivity\fP ()"
.br
.RI "tests method that creates neighbor connectivity inside of CSMP "
.ti -1c
.RI "void \fBTest_RebuildCellAndNodeVectors\fP ()"
.br
.ti -1c
.RI "template<uint32_t dim, template< uint32_t > class simplicial_complex> bool \fBCompareModelSubdomains\fP (const \fBModelSubDomain\fP< dim, simplicial_complex > &, const \fBModelSubDomain\fP< dim, simplicial_complex > &, bool verbose)"
.br
.RI "compares node locations and connectivity "
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests the functionality of the base class of \fBRegion\fP, \fBBoundary\fP and \fBSplitBoundary\fP Only tests selected less frequently used, less obvious functionality that requires testing\&. Functions involving variables require testing in 2 and 3D\&.

.PP
/ deletes nullptr cells, rebuilds node vector, sorts everything and re-establishes the perimeter face vectors after modifications of cells 
.PP
\fBTodo\fP
.RS 4
void RebuildSubDomainAfterChangeOfCellVector();
.RE
.PP

.PP
/ rebuilds subdomain on the basis of the cells that will be selected according to the supplied property constraints void UpdateCellMembershipApplyingConstraints( typename std::vector<CELL<dim>\fI>\fBconst_iterator\fP master_domain_start, typename std::vector<CELL<dim>\fP>\fBconst_iterator\fP master_domain_end, const \fBPropertyConstraints\fP& );

.PP
/ removes any cells or node pointers that were set to zero elsewhere; returns number of cells removed size_t RemoveNullPointerCells();

.PP
/ reference counting-based unique domain identifier (0\&.\&.n-1) size_t DomainIndex() const;

.PP
bool IsContiguous() const;

.PP
std::pair<CELL_SHAPE,bool> SingleCellShapeDomain() const;

.PP
/ output coordinates to user-defined vector variable [x1,y1,z1,\&.\&.\&.xn,yn,zn] void AssignNodeCoordinatesTo( const char* vector_prop );

.PP
/ assigment of coordinate component 'x','y','z' to scalar variable of choice void AssignNodeCoordinatesTo( const char* scalar_prop, char coord );

.PP
/ characteristics like 'length', 'area', 'volume' , 'aspect ratio', 'inner radius' are assigned to user-defined variable void AssignCellCharacteristicsTo( const char* characteristic, const char* var );

.PP
template<typename Var> void InputPropertyValue( const char* input_prop, const Var& new_value, \fBSUBDOMAIN_PART\fP sd=COMPLETE );

.PP
/ as InputPropertyValue, but with overwrite protection for variable components that have the flag 'do_not_overwrite' template<typename Var> void InputPropertyValue( const char* input_prop, const Var& new_value, \fBVARIABLE_FLAG\fP do_not_overwrite, \fBSUBDOMAIN_PART\fP sd=COMPLETE );

.PP
/ changes the flag of the scalar variable 'property' to new value; applied either in the entire subdomain or its interior or perimeter void ChangePropertyStatus( const char* property, \fBVARIABLE_FLAG\fP new_status_of_scalar, \fBSUBDOMAIN_PART\fP=COMPLETE );

.PP
/ changes the flag of the scalar variable 'property' to new value if the scalar variable is withing the specified range void ChangePropertyStatusWhere( const char* property,
                                    VARIABLE_FLAG new_status_of_scalar,
                                    double min_value_to_change,
                                    double max_value_to_change );

.PP
/ changes the flags of the vector variable 'property' to new value; applied either in the entire subdomain or its interior or perimeter void ChangePropertyStatus( const char* property, const std::vector<VARIABLE_FLAG>& new_status, \fBSUBDOMAIN_PART\fP=COMPLETE );

.PP
/ changes the flag of the vector variable 'property' to new value if the scalar variable is withing the specified range void ChangePropertyStatusWhere( const char* property,
                                    const std::vector<VARIABLE_FLAG>& new_status,
                                    double min_value_to_change,
                                    double max_value_to_change );

.PP
/ changes the flag of a particular variable component to new value; applied either in the entire subdomain or its interior or perimeter void ChangePropertyStatus( const char* property, uint32_t component, \fBVARIABLE_FLAG\fP new_status, \fBSUBDOMAIN_PART\fP=COMPLETE );

.PP
/ changes the flag of a particular variable component to new value if the scalar variable is withing the specified range void ChangePropertyStatusWhere( const char* property,
                                    uint32_t component,
                                    VARIABLE_FLAG new_status,
                                    double min_value_to_change,
                                    double max_value_to_change );

.PP
/ by default (i=0) returns status of scalar variable or first component of a vector or tensor variable; if i>0 flag of corresponding component is returned \fBVARIABLE_FLAG\fP PropertyStatus( const char* variable, \fBSUBDOMAIN_PART\fP flag=COMPLETE , uint32_t i=0 ) const;

.PP
void InterpolateNodeToCellProperty( const char* nprop, const char* eprop ); void InterpolateNodeToIntegrationPointProperty( const char* nprop, const char* eprop ); void InterpolateIntegrationPointToCellProperty( const char* cprop, const char* eprop ); void ExtrapolateCellToIntegrationPointProperty( const char* eprop, const char* cprop ); void ExtrapolateCellToFacetIntegrationPointProperty( const char* eprop, const char* fipprop ); void ExtrapolateCellToNodeProperty( const char* eprop, const char* nprop, bool by_distance=true ); void ExtrapolateIntegrationPointToNodeProperty( const char* cprop, const char* nprop );

.PP
/ arithmetic (number as opposed to volume weighted) average double Average( const char* property ) const; bool CopyGradientOfProperty_A_To_B( const char* node_prop, const char* cell_prop ); void CopyReplace( const char* from, const char* to ); 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class simplicial_complex> template bool csmp::ModelSubDomain_Test::CompareModelSubdomains (const \fBModelSubDomain\fP< dim, simplicial_complex > & , const \fBModelSubDomain\fP< dim, simplicial_complex > & , bool verbose)"

.PP
compares node locations and connectivity compares node locations and connectivity
.IP "\(bu" 2
uses point locations for node comparison 
.PP

.SS "void csmp::ModelSubDomain_Test::run ()\fR [virtual]\fP"
Observations
.IP "\(bu" 2
AllElements in single domain model is non-unique, but should be unique
.PP

.PP
add tests for the other important parts of the functionality\&. 
.PP
Implements \fBcsmp::Test\fP\&.
.SS "bool csmp::ModelSubDomain_Test::Test_EstablishNeighborConnectivity ()"

.PP
tests method that creates neighbor connectivity inside of CSMP Using vsets from 'vset_makers' as input data, this tests weither ModelSubDoman::EstablishNeighborConnectivity() recreates the correct neighbor connectivity 
.PP
.nf
@author SKM 5/12/20

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
