.TH "csmp::GocadPropertyClassHeader" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::GocadPropertyClassHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGocadPropertyClassHeader\fP (const char *name, double lclip, double hclip, long pclip=99, size_t comp=1)"
.br
.ti -1c
.RI "\fBGocadPropertyClassHeader\fP (const \fBGocadPropertyClassHeader\fP &p)"
.br
.ti -1c
.RI "\fBGocadPropertyClassHeader\fP & \fBoperator=\fP (const \fBGocadPropertyClassHeader\fP &p)"
.br
.ti -1c
.RI "std::string \fBProperty\fP () const"
.br
.ti -1c
.RI "void \fBProperty\fP (const std::string &s)"
.br
.ti -1c
.RI "void \fBProperty\fP (const char *s)"
.br
.ti -1c
.RI "std::string \fBPropertyClass\fP () const"
.br
.ti -1c
.RI "void \fBPropertyClass\fP (const std::string &s)"
.br
.ti -1c
.RI "void \fBPropertyClass\fP (const char *s)"
.br
.ti -1c
.RI "double \fBLowClip\fP () const"
.br
.ti -1c
.RI "void \fBLowClip\fP (double lc)"
.br
.ti -1c
.RI "double \fBHighClip\fP () const"
.br
.ti -1c
.RI "void \fBHighClip\fP (double hc)"
.br
.ti -1c
.RI "long \fBPClip\fP () const"
.br
.ti -1c
.RI "void \fBPClip\fP (long pc)"
.br
.ti -1c
.RI "double \fBColorContrast\fP () const"
.br
.ti -1c
.RI "void \fBColorContrat\fP (double ct)"
.br
.ti -1c
.RI "std::string \fBColorMap\fP () const"
.br
.ti -1c
.RI "void \fBColorMap\fP (const std::string &s)"
.br
.ti -1c
.RI "void \fBColorMap\fP (char *s)"
.br
.ti -1c
.RI "size_t \fBComponents\fP () const"
.br
.ti -1c
.RI "size_t \fBESize\fP () const"
.br
.ti -1c
.RI "void \fBESize\fP (size_t esize)"
.br
.ti -1c
.RI "double \fBNoDataValue\fP () const"
.br
.ti -1c
.RI "void \fBNoDataValue\fP (double val)"
.br
.ti -1c
.RI "bool \fBInitializeFrom\fP (std::ifstream &ifn)"
.br
.ti -1c
.RI "void \fBWriteToText\fP (std::ofstream &ofs) const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
