.TH "csmp::UpwindControlVisitor< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::UpwindControlVisitor< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <UpwindControlVisitor\&.h>\fP
.PP
Inherits \fBcsmp::Visitor< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUpwindControlVisitor\fP (\fBModel\fP< dim > &model, \fBExplicitFiniteVolumeTransportPHX\fP< dim > &fv_vapor, \fBExplicitFiniteVolumeTransportPHX\fP< dim > &fv_liquid, const char *permeability, const char *porosity, std::vector< std::string > &densities, std::vector< std::string > &relperm_vis, std::vector< std::string > &saturations, std::vector< std::string > &cfl_variables, std::vector< std::string > &velocities, std::vector< std::string > &pore_velocities)"
.br
.ti -1c
.RI "virtual \fB~UpwindControlVisitor\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP ()"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBElement\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBRegion\fP< dim > *)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "bool \fBRecalculate\fP ()"
.br
.ti -1c
.RI "void \fBFlipping\fP (bool flip)"
.br
.ti -1c
.RI "void \fBRecalculate\fP (bool recalc)"
.br
.ti -1c
.RI "void \fBGravity\fP (bool with_gravity)"
.br
.ti -1c
.RI "void \fBWithVelocity\fP (bool with_velocity)"
.br
.ti -1c
.RI "void \fBSetLargestTimeStep\fP (double timestep)"
.br
.ti -1c
.RI "void \fBAdjust_CFL_Criterion\fP (double scale_factor, bool take_pore_velocity)"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBUpwindMatrix\fP (\fBcsmp::Index\fP rho_index, size_t eidx)"
.br
.ti -1c
.RI "std::vector< \fBDenseMatrix\fP< DM_MIN > > & \fBUpwindMatrices\fP (\fBcsmp::Index\fP rho_index)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBVisitor\fP (\fBPLACEMENT\fP level=MODEL, \fBPLACEMENT\fP target=ELEMENT)"
.br
.ti -1c
.RI "void \fBApplicationLevel\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApplicationTarget\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationTarget\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetInitialProperties\fP (\fBModel\fP< dim > *model)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBModel\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBSplitBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBInterFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBEdge\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBNode\fP< dim > *)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_target_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::UpwindControlVisitor< dim >"
.PP
\fBAuthor\fP
.RS 4
Philipp Weis, ETH Zuerich 
.RE
.PP
.SH "Contact"
.PP
philipp.weis@erdw.ethz.ch

.PP
@changes changes Latest Changes 
.br
.SH "Motivation"
.PP
Specialized visitor to define upwind nodes for CVFEM scheme\&.
.SH "Usage"
.PP
To be used within the CVFEM scheme (Weis et al\&., Geofluids, 2014)\&.

.PP
.PP
.nf
Calculates upwind nodes and store information in a matrix\&.
Calculates velocity and pore velocity vectors for graphical representations only!
.fi
.PP
.SH "Dependencies"
.PP
The functions are tailored for use in \fBExplicitFiniteVolumeTransportPHX\fP\&. This visitor is needed in \fBTwoPhaseTransportPHX\fP and Upwind-PDE-operators\&.
.SH "Known issues"
.PP
.SH "Testing"
.PP
testing was done in the period before publication in 2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::UpwindControlVisitor\fP< dim >::UpwindControlVisitor (\fBModel\fP< dim > & model, \fBExplicitFiniteVolumeTransportPHX\fP< dim > & fv_liquid, \fBExplicitFiniteVolumeTransportPHX\fP< dim > & fv_vapor, const char * permeability, const char * porosity, std::vector< std::string > & densities, std::vector< std::string > & relperm_vis, std::vector< std::string > & saturations, std::vector< std::string > & cfl_variables, std::vector< std::string > & velocities, std::vector< std::string > & pore_velocities)"
custom constructor 
.SS "template<uint32_t dim> \fBcsmp::UpwindControlVisitor\fP< dim >::~\fBUpwindControlVisitor\fP ()\fR [virtual]\fP"
default destructor 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::Adjust_CFL_Criterion (double scale_factor, bool take_pore_velocity)"
modify calculation of cfl criterion 
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::Flipping (bool flip)"
set boolean flip 
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::Gravity (bool with_gravity)"
activate or deactivate gravity component 
.SS "template<uint32_t dim> bool \fBcsmp::UpwindControlVisitor\fP< dim >::Recalculate ()"
set boolean recalculate 
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::Recalculate (bool recalc)"
set recalculate boolean 
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::Reset ()"
reset booleans 
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::SetLargestTimeStep (double timestep)"
set maximum size of time step 
.SS "template<uint32_t dim> \fBDenseMatrix\fP< DM_MIN > \fBcsmp::UpwindControlVisitor\fP< dim >::UpwindMatrix (\fBcsmp::Index\fP rho_index, size_t eidx)"
access to upwind matrix of specified phase (density) and element 
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::Visit (\fBElement\fP< dim > * n)\fR [virtual]\fP"
visit function for elements 
.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::Visit (\fBRegion\fP< dim > * n)\fR [virtual]\fP"
visit function for region 
.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::UpwindControlVisitor\fP< dim >::WithVelocity (bool velo)"
set boolean for velocity calculations 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
