.TH "csmp::CubicSpline" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CubicSpline
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CubicSpline\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCubicSpline\fP (const \fBCubicSpline\fP &)"
.br
.ti -1c
.RI "\fBCubicSpline\fP (const char *datafile)"
.br
.ti -1c
.RI "\fBCubicSpline\fP & \fBoperator=\fP (const \fBCubicSpline\fP &)"
.br
.ti -1c
.RI "void \fBInitialize\fP (const char *datafile)"
.br
.ti -1c
.RI "void \fBInitialize\fP (const std::vector< double > &, const std::vector< double > &, const double, const double)"
.br
.ti -1c
.RI "double \fBValue\fP (const double x) const"
.br
.ti -1c
.RI "double \fBDerivative\fP (const double x) const"
.br
.RI "computes derivative using a forward finite difference approach "
.ti -1c
.RI "double \fBMaxDerivative\fP () const"
.br
.RI "computes the maximum value of the second derivative of the spline function; use for checking whether there are enough data points to get satisfactory curve "
.ti -1c
.RI "double \fBRange_x\fP () const"
.br
.ti -1c
.RI "double \fBRange_fx\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "write internal data to screen "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a cubic spline using at least 3 constraint points / data values and 2 derivatives at the curve ends\&.

.PP
\fBNote\fP
.RS 4
A sufficiently large number of the datapoints need to be supplied to get a satisfactory spline, dependent on the curve represented by the data\&. Graph the spline curve first before using the results in other computations\&. The data for graphing can be obtained using the \fBOut()\fP function\&.
.RE
.PP
CubicSpine is used inside the experimental data-based saturation functions in the CSMP library found in the thmc directory\&. 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::CubicSpline::Derivative (const double x) const"

.PP
computes derivative using a forward finite difference approach two point derivative about x(x-1% of range,x+1% of range

.PP
\fBTodo\fP
.RS 4
improve by using analytic derivative 
.RE
.PP

.SS "void csmp::CubicSpline::Initialize (const char * datafile)"
Reads two-column datafile with the format:

.PP
header line - just filename and explanation what's tabulated blank line number of x,y value pairs (the tabulated function) derivate1 and derivative_n at the function origin and endpoint x-y value pairs (one per line) 1\&.\&.n 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
