.TH "csmp::TPINCFVT3D_VVCase" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TPINCFVT3D_VVCase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTPINCFVT3D_VVCase\fP (const char *prefix)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBSetModel\fP (\fBModel\fP< 3 > &model, double mobilityRatio, double velX, double porosity)"
.br
.RI "Set model\&. "
.ti -1c
.RI "void \fBOutputVTU\fP (\fBModel\fP< 3 > &model, const char *fileName, long time)"
.br
.ti -1c
.RI "double \fBTestFront\fP (\fBModel\fP< 3 > &model, double tolSat, double satOil, double tolFront, double analyticFront)"
.br
.ti -1c
.RI "void \fBTest\fP (\fBTPINCFVT3D_TestData\fP &data, double tolSat, double satOil, double tolFront)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void csmp::TPINCFVT3D_VVCase::run ()\fR [virtual]\fP"
TestCase for Brooks-Corey two-phase flow running a 1\&.0 x 1\&.0 x 1\&.0 m cube model at different transport velocities

.PP
TestCase for Brooks-Corey two-phase flow running a 40\&.0 x 10\&.0 m rectangular slab model with different viscosity ratios and at different transport velocities

.PP
TestCase for Brooks-Corey two-phase flow running a 40\&.0 x 10\&.0 m rectangular slab model of gradually changing cell sizes at different transport velocities

.PP
TestCase for Brooks-Corey two-phase flow running a 10\&.0 x 1\&.0 m rectangular slab model of quadrilateral elements

.PP
TestCase for Linear Two-Phase model (Warning: viscosities are hard-coded in the two-phase contructor) running a 10\&.0 x 1\&.0 x 0\&.25 m rectangular slab model

.PP
TestCase for Brooks-Corey two-phase flow running a 10\&.0 x 1\&.0 m rectangular slab (fracture) model accounting for realistic fracture aperture conditions

.PP
TestCase for Brooks-Corey two-phase flow running a 10\&.0 x 1\&.0 m rectangular slab (fracture) model accounting for realistic fracture aperture conditions Discontinous transport using time multiplier 0\&.1

.PP
TestCase for Brooks-Corey two-phase flow running a 10\&.0 x 1\&.0 m rectangular slab (fracture) model accounting for realistic fracture aperture conditions Discontinous transport using time multiplier 0\&.01

.PP
TestCase for Brooks-Corey two-phase flow running a 10\&.0 x 1\&.0 m rectangular slab model

.PP
TestCase for Brooks-Corey two-phase flow running a 10\&.0 x 1\&.0 m rectangular slab model Discontinous transport using time multiplier 0\&.1

.PP
TestCase for Brooks-Corey two-phase flow running a 10\&.0 x 1\&.0 m rectangular slab model Discontinous transport using time multiplier 0\&.01

.PP
TestCase for Linear Two-Phase model (Warning: viscosities are hard-coded in the two-phase contructor) running a 40\&.0 x 10\&.0 m rectangular slab (fracture) model accounting for realistic fracture aperture conditions

.PP
TestCase for Linear Two-Phase model (Warning: viscosities are hard-coded in the two-phase contructor) running a 40\&.0 x 10\&.0 m rectangular slab (fracture) model accounting for realistic fracture aperture conditions Discontinous transport using time multiplier 0\&.1

.PP
TestCase for Linear Two-Phase model (Warning: viscosities are hard-coded in the two-phase contructor) running a 40\&.0 x 10\&.0 m rectangular slab (fracture) model accounting for realistic fracture aperture conditions Discontinous transport using time multiplier 0\&.01

.PP
TestCase for Linear Two-Phase model (Warning: viscosities are hard-coded in the two-phase contructor) running a 40\&.0 x 10\&.0 m rectangular slab model

.PP
TestCase for Linear Two-Phase model (Warning: viscosities are hard-coded in the two-phase contructor) running a 40\&.0 x 10\&.0 m rectangular slab model Discontinous transport using time multiplier 0\&.1

.PP
TestCase for Linear Two-Phase model (Warning: viscosities are hard-coded in the two-phase contructor) running a 40\&.0 x 10\&.0 m rectangular slab model Discontinous transport using time multiplier 0\&.01

.PP
Report

.PP
Spreadsheet
.PP
Implements \fBcsmp::Test\fP\&.
.SS "void csmp::TPINCFVT3D_VVCase::Test (\fBTPINCFVT3D_TestData\fP & data, double tolSat, double satOil, double tolFront)"
Checking numerical dispersivity

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
