.TH "csmp::variables::VariableSet_TracerTransfer" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::variables::VariableSet_TracerTransfer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcsmp::IntegralEquation< dim, variables::VariableSet_TracerTransfer >\fP, and \fBcsmp::ExplicitTransport< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<uint32_t dim> \fBVariableSet_TracerTransfer\fP (const \fBPropertyDatabase\fP< dim > &db)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_out_\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_acc_\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_CT\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_PF0\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_FVPV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_FB\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, SECTOR_INTEGRATION_POINT > \fBkey_SPV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, SECTOR_INTEGRATION_POINT > \fBkey_SV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_NQV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_QV\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_PF\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_k\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_kk\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, FACET_INTEGRATION_POINT > \fBkey_fAk\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, FACET_INTEGRATION_POINT > \fBkey_fn\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_THI\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< VECTOR, ELEMENT > \fBkey_V\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_MU\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, MODEL > \fBkey_RHO\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_C\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_C0\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, NODE > \fBkey_C1\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_K\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< TENSOR, ELEMENT > \fBkey_KK\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_D\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_ffC\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_ff\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, FACET_INTEGRATION_POINT > \fBkey_fA\fP"
.br
.ti -1c
.RI "\fBcsmp::INDEX\fP< SCALAR, ELEMENT > \fBkey_PHI\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
