.TH "CSMPglobalOperators" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSMPglobalOperators \- Global CSMP Operators
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBcsmp::operator<<\fP (ostream &stream, const \fBcsmp::Index\fP &o)"
.br
.ti -1c
.RI "istream & \fBcsmp::operator>>\fP (istream &stream, \fBcsmp::Index\fP &o)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Operators available globally in the csmp Namespace
.SH "Function Documentation"
.PP 
.SS "ostream & csmp::operator<< (ostream & stream, const \fBcsmp::Index\fP & o)"
Custom global ostream operator

.PP
\fBAttention\fP
.RS 4
Does not output \fBIntegrationPointVariables\fP / \fBLocalVariables\fP
.RE
.PP
Writes human-readable variable characteristics to given output stream (use Out() to get all)

.PP
\fBParameters\fP
.RS 4
\fIstream\fP The output stream 
.br
\fIo\fP The \fBcsmp::Index\fP object to output 
.RE
.PP
\fBReturns\fP
.RS 4
Formatted output 
.RE
.PP

.SS "istream & csmp::operator>> (istream & stream, \fBcsmp::Index\fP & o)"
Custom global istream operator

.PP
\fBAttention\fP
.RS 4
Does not instantiate \fBIntegrationPointVariables\fP / \fBLocalVariables\fP
.RE
.PP
Provides formatted input to a given stream 
.PP
\fBParameters\fP
.RS 4
\fIstream\fP The input stream 
.br
\fIo\fP The \fBcsmp::Index\fP object to intput 
.RE
.PP
\fBReturns\fP
.RS 4
Formatted intput 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
