.TH "csmp::Expiration" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Expiration
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpiration\fP (LICENSE_PERIOD p, int startYear, int startMonth, int startDay)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LICENSE_PERIOD \fBduration\fP"
.br
.ti -1c
.RI "std::tm \fBstart_time\fP"
.br
.ti -1c
.RI "std::time_t \fBsecs_remaining\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
