.TH "csmp::SimulatorControl< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SimulatorControl< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SimulatorControl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimulatorControl\fP (\fBSimulatorSetup\fP< dim > *ss)"
.br
.ti -1c
.RI "void \fBCatchSignals\fP ()"
.br
.ti -1c
.RI "\fBSimulationSignalHandler\fP & \fBGetSignalHandler\fP ()"
.br
.ti -1c
.RI "void \fBOutputRestartFile\fP (bool manually_triggered=false)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "std::string \fBGetName\fP ()"
.br
.ti -1c
.RI "\fBSimulatorSetup\fP< dim > * \fBGetSS\fP ()"
.br
.ti -1c
.RI "\fBComputationalSettings\fP & \fBRunSettings\fP ()"
.br
.ti -1c
.RI "void \fBManageWellRates\fP ()"
.br
.ti -1c
.RI "virtual void \fBRun\fP ()"
.br
.ti -1c
.RI "bool \fBCheckForDirichletEssentialCondition\fP (\fBcsmp::Index\fP key)"
.br
.ti -1c
.RI "void \fBPrintRangeOfVariablesToScreen\fP ()"
.br
.ti -1c
.RI "bool \fBReadControlOptions\fP ()"
.br
.ti -1c
.RI "virtual bool \fBReadSimulatorSpecificControlOptions\fP ()=0"
.br
.ti -1c
.RI "\fBIndex\fP & \fBGetThicknessKey\fP ()"
.br
.ti -1c
.RI "\fBIndex\fP & \fBGetWellRadiusKey\fP ()"
.br
.ti -1c
.RI "virtual void \fBLoadKeysAndNames\fP ()=0"
.br
.ti -1c
.RI "double \fBMaxDifferenceScalarNodalProperty\fP (\fBIndex\fP &snp1Key, \fBIndex\fP &snp2Key)"
.br
.ti -1c
.RI "void \fBSetBoundaryFlag\fP (const char *prop_name, std::string boundary, \fBVARIABLE_FLAG\fP flag)"
.br
.ti -1c
.RI "void \fBSetBoundaryValue\fP (const char *prop_name, std::string boundary, double value, \fBVARIABLE_FLAG\fP flag)"
.br
.ti -1c
.RI "void \fBSetRegionFlag\fP (const char *prop_name, std::string region, \fBVARIABLE_FLAG\fP flag)"
.br
.ti -1c
.RI "void \fBSetRegionValue\fP (std::string prop_name, std::string region, double value, \fBVARIABLE_FLAG\fP flag)"
.br
.ti -1c
.RI "void \fBSetFlagNearestToPoint\fP (\fBIndex\fP key, double x, double y, double z, \fBVARIABLE_FLAG\fP flag)"
.br
.ti -1c
.RI "void \fBSetValueNearestToPoint\fP (\fBIndex\fP key, double x, double y, double z, double value, \fBVARIABLE_FLAG\fP flag, \fBSUBDOMAIN_PART\fP sub=COMPLETE)"
.br
.ti -1c
.RI "void \fBSetPropertyFlagToTopBoundaries\fP (const char *property_name, \fBVARIABLE_FLAG\fP flag)"
.br
.ti -1c
.RI "double \fBGetSimulationEndTime\fP ()"
.br
.ti -1c
.RI "double \fBGetSimulationStartTime\fP ()"
.br
.ti -1c
.RI "std::vector< std::pair< double, std::string > > & \fBGetIntervals\fP ()"
.br
.ti -1c
.RI "double \fBGetIntervalEndTime\fP ()"
.br
.ti -1c
.RI "double \fBGetIntervalStartTime\fP ()"
.br
.ti -1c
.RI "size_t \fBGetIntervalNumber\fP (double current_time)"
.br
.ti -1c
.RI "std::string \fBGetIntervalName\fP (double current_time)"
.br
.ti -1c
.RI "void \fBInsertNewTimeInterval\fP (std::string interval_name, double starttime)"
.br
.ti -1c
.RI "double \fBGetSimulationTime\fP ()"
.br
.ti -1c
.RI "void \fBSetThicknessFactorFromWellRadii\fP ()"
.br
.ti -1c
.RI "void \fBSetSimulationEndTime\fP (double t)"
.br
.ti -1c
.RI "void \fBSetSimulationStartTime\fP (double t)"
.br
.ti -1c
.RI "void \fBSetIntervalEndTime\fP (double t)"
.br
.ti -1c
.RI "void \fBSetIntervalStartTime\fP (double t)"
.br
.ti -1c
.RI "void \fBSetSimulationTime\fP (double t)"
.br
.ti -1c
.RI "void \fBSetGlobalTimestep\fP (double t)"
.br
.ti -1c
.RI "double \fBGetCurrentIntervalEndTime\fP (double current_simulation_time)"
.br
.ti -1c
.RI "double \fBGetCurrentIntervalStartTime\fP (double current_simulation_time)"
.br
.ti -1c
.RI "double \fBCalculateCurrentRunTime\fP ()"
.br
.ti -1c
.RI "void \fBSetOutputTimes\fP (size_t n, double starttime=0\&.0)"
.br
.ti -1c
.RI "void \fBSetMonitorTimes\fP (size_t n, double starttime=0\&.0)"
.br
.ti -1c
.RI "void \fBLoadMonitoringTimesFromRestartedModel\fP ()"
.br
.ti -1c
.RI "virtual void \fBComputeTimeIncrement\fP ()=0"
.br
.ti -1c
.RI "void \fBTrimTimeIncrementWithMonitorTime\fP ()"
.br
.ti -1c
.RI "void \fBTrimTimeIncrementWithOutputTime\fP ()"
.br
.ti -1c
.RI "void \fBTrimTimeIncrementWithEndOfInterval\fP ()"
.br
.ti -1c
.RI "double \fBTimeIncrement\fP ()"
.br
.ti -1c
.RI "void \fBTimeIncrement\fP (double time_increment)"
.br
.ti -1c
.RI "double \fBGetInitialSimulatorStartTimeFromIntervals\fP ()"
.br
.ti -1c
.RI "void \fBOutputSimulationTimeToScreen\fP (double time)"
.br
.ti -1c
.RI "void \fBSyncOutputAntMonitoringTimesToModel\fP ()"
.br
.ti -1c
.RI "bool \fBMonitorAllTimesteps\fP ()"
.br
.ti -1c
.RI "void \fBMonitorAllTimesteps\fP (bool mon_all_timesteps)"
.br
.ti -1c
.RI "void \fBSetReferencePointValuesModelInterior\fP ()"
.br
.ti -1c
.RI "void \fBSetReferencePointValuesModelPerimeter\fP ()"
.br
.ti -1c
.RI "void \fBBeginInterval\fP ()"
.br
.ti -1c
.RI "bool \fBInteractiveInputNodeValue\fP (\fBcsmp::Index\fP key, \fBSUBDOMAIN_PART\fP sub=INTERIOR)"
.br
.ti -1c
.RI "bool \fBAskUserToContinue\fP ()"
.br
.ti -1c
.RI "bool \fBYesOrNo\fP ()"
.br
.ti -1c
.RI "bool \fBCheckTimeIntervals\fP ()"
.br
.ti -1c
.RI "void \fBInteractivelyManageEssentialConditions\fP ()"
.br
.ti -1c
.RI "double \fBGetRealInput\fP (bool success=true)"
.br
.ti -1c
.RI "int32_t \fBGetIntegerInput\fP ()"
.br
.ti -1c
.RI "std::string \fBGetStringInput\fP ()"
.br
.ti -1c
.RI "std::string \fBParseTrueOrFalse\fP (bool trueorfalse)"
.br
.ti -1c
.RI "std::string \fBParseWellMode\fP (WELL_MODE mode)"
.br
.ti -1c
.RI "WELL_MODE \fBParseIntegerToWellMode\fP (int32_t i)"
.br
.ti -1c
.RI "std::multimap< std::string, std::pair< std::string, WELL_MODE > > & \fBGetWellModesPerInterval\fP ()"
.br
.ti -1c
.RI "std::multimap< std::string, std::pair< std::vector< double >, double > > & \fBGetReferencePointsAndValues\fP ()"
.br
.ti -1c
.RI "\fBVTU_Interface\fP< dim > * \fBGetVTU_Interface\fP ()"
.br
.ti -1c
.RI "void \fBOutputVariableToRegionVTUFiles\fP ()"
.br
.ti -1c
.RI "virtual void \fBOutputSimulatorSpecificControlFileSection\fP ()=0"
.br
.ti -1c
.RI "void \fBOutputSampleControlFile\fP ()"
.br
.ti -1c
.RI "void \fBUpdateCurrentRunTime\fP ()"
.br
.ti -1c
.RI "void \fBOutput\fP ()"
.br
.ti -1c
.RI "void \fBQuietSolvers\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBTriggerSAMGSetup\fP (bool trigger)"
.br
.ti -1c
.RI "bool \fBTriggerSAMGSetup\fP ()"
.br
.ti -1c
.RI "bool & \fBRestart\fP ()"
.br
.ti -1c
.RI "void \fBRestart\fP (bool restart)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "clock_t \fBrunTimeStart_\fP"
.br
.ti -1c
.RI "\fBPropertyDatabase\fP< dim > & \fBpdb_\fP"
.br
.ti -1c
.RI "\fBErrorHandler\fP & \fBerror_handler_\fP"
.br
.ti -1c
.RI "double \fBinitial_omp_wtime_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::SimulatorControl< dim >"
.PP
\fBAuthor\fP
.RS 4
Julian E\&. Mindel (ETHZ)
.RE
.PP
\fBTodo\fP
.RS 4
document this code\&.
.RE
.PP

.PP
\fBTodo\fP
.RS 4
SKM move to applications, geothermal energy storage simulator
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> double \fBcsmp::SimulatorControl\fP< dim >::CalculateCurrentRunTime ()"
returns run-time, in seconds, since an initial reference point normally set by the BeginInterval() method\&. 
.SS "template<uint32_t dim> double \fBcsmp::SimulatorControl\fP< dim >::GetCurrentIntervalEndTime (double current_simulation_time)"
Here we look in the stored time interval start times to see which is the the closest to the current simulation time\&. If none is found then GetSimulationEndTime() is returned\&.

.PP
check all simulation start times, and choose the closest one\&.
.SS "template<uint32_t dim> double \fBcsmp::SimulatorControl\fP< dim >::GetCurrentIntervalStartTime (double current_simulation_time)"
Here we look in the stored time interval start times to see which is the the closest previous to the current simulation time\&. If none is found then GetSimulationStartTime() is returned\&.
.SS "template<uint32_t dim> void \fBcsmp::SimulatorControl\fP< dim >::OutputRestartFile (bool manually_triggered = \fRfalse\fP)"

.PP
\fBTodo\fP
.RS 4
make an option here, that if the connectivity hasn't changed we do not need to output the connectivity, saving time\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::SimulatorControl\fP< dim >::OutputSimulationTimeToScreen (double time)"

.PP
\fBTodo\fP
.RS 4
Hualp! -> use standard library
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::SimulatorControl\fP< dim >::OutputVariableToRegionVTUFiles ()"

.PP
\fBTodo\fP
.RS 4
put conditional output options here (i\&.e\&. OutputTimes) 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::SimulatorControl\fP< dim >::QuietSolvers ()"
add extra functionality for alternative solver if needed
.SS "template<uint32_t dim> bool \fBcsmp::SimulatorControl\fP< dim >::ReadControlOptions ()"
Note: These times will output monitoring as well!
.SS "template<uint32_t dim> void \fBcsmp::SimulatorControl\fP< dim >::SetOutputTimes (size_t n, double starttime = \fR0\&.0\fP)"

.PP
\fBTodo\fP
.RS 4
double check if it isn't convenient to set the output intervals related to start time (i\&.e\&. (duration-starttime)/n)\&. At the moment, this does not seem so\&. --Julian 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::SimulatorControl\fP< dim >::SetReferencePointValuesModelInterior ()"
This function sets Dirichlet values on points closest to the supplied coordinates\&. Note that This will only address those nodes in the interior of the model\&. 
.SS "template<uint32_t dim> void \fBcsmp::SimulatorControl\fP< dim >::SetReferencePointValuesModelPerimeter ()"
This function sets Dirichlet values on points closest to the supplied coordinates\&. Note that This will only address those nodes in the perimeter of the model\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
