.TH "csmp::QuadraturePointOutputToVTK" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::QuadraturePointOutputToVTK
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuadraturePointOutputToVTK\fP ()"
.br
.ti -1c
.RI "void \fBOutputQuadraturePointPropertiesAsDiscontinuousNodeVariablesToVTK\fP (const \fBModel\fP< 3U > &, const char *, const char *)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::QuadraturePointOutputToVTK::QuadraturePointOutputToVTK ()"
Extrapolates scalar integration point properties to unique (new) nodes of quadratic tetrahedra and triangles\&.

.PP
The legacy VTK ASCII text file format is used\&.

.PP
Quadratic triangular elements only\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
