.TH "csmp::NumIntegral_DNT_rhsop_DN_dV< dim, CELL >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::NumIntegral_DNT_rhsop_DN_dV< dim, CELL > \- RHS = div^2 \&. operand - interpolation function derivative matrix collapsed into righthand side vector\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <NumIntegral_DNT_rhsop_DN_dV\&.h>\fP
.PP
Inherits \fBcsmp::MathOperatorRHS< dim, Element >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNumIntegral_DNT_rhsop_DN_dV\fP (const \fBPropertyDatabase\fP< dim > &p, const char *oper, const char *test)"
.br
.ti -1c
.RI "\fBNumIntegral_DNT_rhsop_DN_dV\fP (const \fBPropertyDatabase\fP< dim > &p, const char *integral_multiplier, const char *oper, const char *test)"
.br
.ti -1c
.RI "void \fBGetOperands\fP (const CELL< dim > &) override final"
.br
.RI "getting data from the \fBElement\fP, \fBFace\fP, \fBInterFace\fP "
.ti -1c
.RI "void \fBComputeContribution\fP (const CELL< dim > &) override final"
.br
.ti -1c
.RI "void \fBIgnoreOperand\fP (bool ignore)"
.br
.ti -1c
.RI "\fBNumIntegral_DNT_rhsop_DN_dV\fP< dim, CELL > * \fBclone\fP () const override final"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::MathOperatorRHS< dim, Element >\fP
.in +1c
.ti -1c
.RI "\fBMathOperatorRHS\fP & \fBoperator=\fP (const \fBMathOperatorRHS\fP &)"
.br
.ti -1c
.RI "std::string \fBName\fP () const"
.br
.RI "\fBOperand\fP Functions\&. "
.ti -1c
.RI "virtual void \fBOut\fP () const"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBMaterialOperand\fP () const"
.br
.RI "op "
.ti -1c
.RI "const \fBIndex\fP & \fBMaterialOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBMaterialOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBMaterialOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBMaterialOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBMaterialOperandDataDepth\fP () const"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBBasicOperand\fP () const"
.br
.RI "bop "
.ti -1c
.RI "const \fBIndex\fP & \fBBasicOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBBasicOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBBasicOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBBasicOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBBasicOperandDataDepth\fP () const"
.br
.ti -1c
.RI "size_t \fBBasicOperandOffset\fP () const"
.br
.ti -1c
.RI "const \fBParameter\fP & \fBTestOperand\fP () const"
.br
.RI "top "
.ti -1c
.RI "const \fBIndex\fP & \fBTestOperandKey\fP () const"
.br
.ti -1c
.RI "std::string \fBTestOperandName\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_TYPE\fP \fBTestOperandType\fP () const"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBTestOperandPlacement\fP () const"
.br
.ti -1c
.RI "uint32_t \fBTestOperandDataDepth\fP () const"
.br
.ti -1c
.RI "size_t \fBTestOperandOffset\fP () const"
.br
.ti -1c
.RI "bool \fBAdd\fP () const"
.br
.RI "Accumulation Process Settings\&. "
.ti -1c
.RI "bool \fBSubtract\fP () const"
.br
.ti -1c
.RI "bool \fBAddLater\fP () const"
.br
.ti -1c
.RI "bool \fBSubtractLater\fP () const"
.br
.ti -1c
.RI "bool \fBMultiply\fP () const"
.br
.ti -1c
.RI "bool \fBLumpedFormulation\fP () const"
.br
.ti -1c
.RI "uint32_t \fBApplicationCycle\fP () const"
.br
.ti -1c
.RI "uint32_t \fBApplicationCycles\fP () const"
.br
.ti -1c
.RI "double \fBMultiplyBy\fP () const"
.br
.ti -1c
.RI "bool \fBMultiplyWithTimeIncrement\fP () const"
.br
.ti -1c
.RI "bool \fBDivideByTimeIncrement\fP () const"
.br
.ti -1c
.RI "void \fBAddAccumulate\fP ()"
.br
.RI "Set Flags and Properties\&. "
.ti -1c
.RI "void \fBSubtractAccumulate\fP ()"
.br
.ti -1c
.RI "void \fBAddAccumulateLater\fP ()"
.br
.ti -1c
.RI "void \fBSubtractAccumulateLater\fP ()"
.br
.ti -1c
.RI "void \fBMultiplyAccumulate\fP ()"
.br
.ti -1c
.RI "void \fBPropertyAtIntegrationPoint\fP (const \fBElement\fP< dim > &, const \fBcsmp::Index\fP &, uint32_t ip, \fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "interpolation of property if isoparametric elements are used "
.ti -1c
.RI "virtual void \fBWriteOperands\fP (\fBElement\fP< dim > &)"
.br
.RI "writing data to the \fBElement\fP, \fBFace\fP, \fBInterFace\fP "
.ti -1c
.RI "virtual void \fBMultiplyWithTimeFactor\fP (double dt)"
.br
.RI "if so specified multiply with time increment "
.ti -1c
.RI "virtual void \fBAssignToGlobal\fP (const \fBElement\fP< dim > &, std::vector< double > &rhs)"
.br
.RI "assigment to the right hand side global vector (after everything was calculated ) "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::MathOperatorRHS< dim, Element >\fP
.in +1c
.ti -1c
.RI "std::string \fBname_\fP"
.br
.RI "name of operator "
.ti -1c
.RI "\fBParameter\fP \fBop\fP"
.br
.RI "material property operand "
.ti -1c
.RI "std::pair< \fBParameter\fP, size_t > \fBtop\fP"
.br
.RI "test function operand "
.ti -1c
.RI "std::vector< double > \fBRHS\fP"
.br
.RI "solution \fBvector<double>\fP to be accumulated "
.ti -1c
.RI "std::vector< \fBDenseMatrix\fP< DM_MIN > > \fBMTRL\fP"
.br
.RI "material property matrix(es) needed for PDE operand "
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBDERIV\fP"
.br
.RI "shape function derivative matrix "
.ti -1c
.RI "std::vector< double > \fBIPOL\fP"
.br
.RI "shape function vector "
.ti -1c
.RI "double \fBfactor_\fP"
.br
.RI "constant factor "
.ti -1c
.RI "bool \fBadd_accumulate_\fP"
.br
.RI "specifies accumulation procedure "
.ti -1c
.RI "bool \fBsubtract_accumulate_\fP"
.br
.ti -1c
.RI "bool \fBadd_accumulate_later_\fP"
.br
.ti -1c
.RI "bool \fBsubtract_accumulate_later_\fP"
.br
.ti -1c
.RI "bool \fBmultiply_accumulate_\fP"
.br
.ti -1c
.RI "bool \fBlump_matrices_\fP"
.br
.ti -1c
.RI "uint32_t \fBapplication_cycles_\fP"
.br
.ti -1c
.RI "uint32_t \fBapplication_cycle_\fP"
.br
.ti -1c
.RI "bool \fBtime_multiply_\fP"
.br
.RI "time-dependent multipliers "
.ti -1c
.RI "bool \fBtime_divide_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class CELL = Element>
.br
class csmp::NumIntegral_DNT_rhsop_DN_dV< dim, CELL >"RHS = div^2 \&. operand - interpolation function derivative matrix collapsed into righthand side vector\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
S\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1999
.RE
.PP
\fBCopyright\fP
.RS 4
1999 by Dr\&. Stephan K\&. Matthaei & Stephen G\&. Roberts 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class CELL = Element> \fBNumIntegral_DNT_rhsop_DN_dV\fP< dim, CELL > * \fBcsmp::NumIntegral_DNT_rhsop_DN_dV\fP< dim, CELL >::clone () const\fR [inline]\fP, \fR [final]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBcsmp::MathOperatorRHS< dim, Element >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class CELL> void \fBcsmp::NumIntegral_DNT_rhsop_DN_dV\fP< dim, CELL >::ComputeContribution (const CELL< dim > & e)\fR [final]\fP, \fR [override]\fP, \fR [virtual]\fP"

.SH "Input Arguments"
.PP
A reference to the finite-element from which the contribution is computed\&. 
.PP
Reimplemented from \fBcsmp::MathOperatorRHS< dim, Element >\fP\&.
.SS "template<uint32_t dim, template< uint32_t > class CELL> void \fBcsmp::NumIntegral_DNT_rhsop_DN_dV\fP< dim, CELL >::GetOperands (const CELL< dim > & e_ref)\fR [final]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
getting data from the \fBElement\fP, \fBFace\fP, \fBInterFace\fP GetOperands fills a vector of material property matrices with the required values for later computation\&. These matrices always have the dimensions spatial-dimension^2 and they will hold either scalar, vector or tensor properties, depending on what kind of property the \fBOperand\fP is\&.

.PP
When the property is an element property, it will be put into the first vector entry MTRL[0]\&. 
.PP
Reimplemented from \fBcsmp::MathOperatorRHS< dim, Element >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
