.TH "csmp::FiniteElement" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FiniteElement \- CSMP's base class of all finite elements whose functionality is provided through polymorphism\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FiniteElement\&.h>\fP
.PP
Inherited by \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle\fP, and \fBcsmp::LinearTriangle3D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFiniteElement\fP (\fBCSMP_FEM_TYPE\fP csp_fem_type, bool isoparametric, bool uses_local_coordinates, uint32_t order_of_shape_functions)"
.br
.ti -1c
.RI "void \fBCurrentID\fP (size_t id)"
.br
.RI "assigns integer value used to avoid repeating the same operation "
.ti -1c
.RI "size_t \fBCurrentID\fP () const"
.br
.RI "returns integer value for comparison to avoid repeating the same operation "
.ti -1c
.RI "uint32_t \fBDim\fP () const"
.br
.RI "return minimum spatial dimension in which this element can exist "
.ti -1c
.RI "uint32_t \fBNodes\fP () const"
.br
.ti -1c
.RI "uint32_t \fBSegments\fP () const"
.br
.RI "returns the number of edges of the FE, i\&.e\&. the number of connections between nodes "
.ti -1c
.RI "uint32_t \fBFaces\fP () const"
.br
.RI "returns the number of sides the finite element has "
.ti -1c
.RI "uint32_t \fBNeighbors\fP () const"
.br
.RI "neighbor elements that may be connected to this FE in its characteristic space "
.ti -1c
.RI "virtual uint32_t \fBNodesPerFace\fP (uint32_t face) const"
.br
.RI "returns how many nodes make up a particular face; some elements have different numbers "
.ti -1c
.RI "uint32_t \fBIntegrationPoints\fP () const"
.br
.RI "returns number of quadrature points used by current integration scheme "
.ti -1c
.RI "uint32_t \fBInterpolation\fP () const"
.br
.RI "returns order of interpolation scheme: linear=1, quadratic=2, cubic=3 "
.ti -1c
.RI "bool \fBIsoparametric\fP () const"
.br
.RI "for numerically integrated elements, reports whether the order of the interpolation functions is the same as that of the shape functions "
.ti -1c
.RI "bool \fBUsesLocalCoordinates\fP () const"
.br
.RI "reports whether element is defined in a local (r,s,t) coordinate system; analytically integrated elements are not "
.ti -1c
.RI "uint32_t \fBOrderOfShapeFunctions\fP () const"
.br
.RI "returns the interpolation order of the shape functions as opposed to the interpolation (basis) functions "
.ti -1c
.RI "bool \fBIsLine\fP () const"
.br
.ti -1c
.RI "bool \fBIsSurface\fP () const"
.br
.ti -1c
.RI "bool \fBIsVolume\fP () const"
.br
.ti -1c
.RI "bool \fBIsSimplex\fP () const"
.br
.RI "true for linear line-, triangle- or tetrahedral elements for which the Jacobian matrix is constant throughout "
.ti -1c
.RI "\fBCSMP_FEM_TYPE\fP \fBElementType\fP () const"
.br
.ti -1c
.RI "virtual double \fBVolume\fP ()"
.br
.RI "computes and returns the volume of the element which is an area for a surface- and a length for a line element "
.ti -1c
.RI "virtual double \fBAspectRatio\fP ()"
.br
.RI "returns the ratio between the maximum and minimum spatial extent of the element "
.ti -1c
.RI "virtual double \fBInnerRadius\fP ()"
.br
.RI "returns the radius of the largest sphere that could be inscribed in the element "
.ti -1c
.RI "virtual void \fBEdgeLengths\fP (std::vector< double > &vec)"
.br
.RI "reports the lengths of all edges (connections between nodes) in the currrent element "
.ti -1c
.RI "virtual void \fBNodesOfSegment\fP (uint32_t segm_id, std::vector< uint32_t > &snids) const"
.br
.RI "reports the egde nodes (0\&.\&.nodes-1) which can be more than 2 in higher-order elements "
.ti -1c
.RI "virtual void \fBCornerNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "reports only the corner nodes (0\&.\&.nodes-1) of the element "
.ti -1c
.RI "virtual void \fBMidSideNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "reports only the mid-edge nodes (0\&.\&.nodes-1) of the element "
.ti -1c
.RI "virtual void \fBInteriorNodes\fP (std::vector< uint32_t > &ids) const"
.br
.RI "reports the nodes (0\&.\&.nodes-1) of the element which are not shared with any other element "
.ti -1c
.RI "virtual std::vector< uint32_t > \fBNodesOfFace\fP (uint32_t face_id) const"
.br
.RI "reports the face nodes (0\&.\&.nodes-1) of the given face "
.ti -1c
.RI "virtual std::vector< uint32_t > \fBCornerNodesOfFace\fP (uint32_t face_id) const"
.br
.RI "returns the local numbers of the corner nodes of the face "
.ti -1c
.RI "virtual std::vector< uint32_t > \fBNodesConnectedTo\fP (uint32_t node) const"
.br
.RI "returns the local numbers of the nodes at the other end of the sgment that the argument node is on "
.ti -1c
.RI "virtual uint32_t \fBCornerNodes\fP () const"
.br
.ti -1c
.RI "virtual uint32_t \fBMidSideNodes\fP () const"
.br
.ti -1c
.RI "virtual uint32_t \fBInteriorNodes\fP () const"
.br
.ti -1c
.RI "virtual \fBCSMP_FEM_TYPE\fP \fBElementTypeOfFace\fP (uint32_t face) const"
.br
.RI "reports the element type that would match that of its corresponding face "
.ti -1c
.RI "virtual \fBCSMP_FEM_TYPE\fP \fBElementTypeOfSegment\fP (uint32_t segment) const"
.br
.RI "reports the element type that would match that of its corresponding segment "
.ti -1c
.RI "virtual std::vector< double > \fBUnitNormal\fP () const"
.br
.RI "returns unit normal to element where it makes sense (line and surface elements); expects XY matrix to be initialised with node coordinates "
.ti -1c
.RI "virtual void \fBUnitNormalToFace\fP (uint32_t face, std::vector< double > &unrml) const"
.br
.RI "returns the unit normal to element face (for planar elements, normal lies in that plane; expects XY matrix to be initialised with node coordinates "
.ti -1c
.RI "virtual void \fBUnitNormalAtFaceBarycenter\fP (uint32_t face, std::vector< double > &nrml)"
.br
.RI "computes unit normal to face using a parametric to physical space transformation available in elements with a local coordinate framework "
.ti -1c
.RI "double \fBXYZ\fP (uint32_t i, uint32_t j) const"
.br
.RI "accessor for coordinate matrix which is associated with the element "
.ti -1c
.RI "void \fBXYZ\fP (uint32_t i, uint32_t j, double val)"
.br
.RI "mutator for coordinate matrix which is associated with the element "
.ti -1c
.RI "virtual void \fBReferenceCoordinates\fP (\fBDenseMatrix\fP< DM_MIN > &matCoords) const"
.br
.RI "for element types defined using a local coordinate system, returns the node coordinates into the argument matrix "
.ti -1c
.RI "virtual void \fBExtrapolateIntegrationPointVariableToNodes\fP (uint32_t nvars, const std::vector< double > &IVAR, std::vector< double > &NVAR) const"
.br
.RI "using the interpolation functions, the supplied suite of scalar variable values is extrapolated from the Gauss points to the nodes "
.ti -1c
.RI "virtual void \fBIntegrationPoint\fP (uint32_t i, std::vector< double > &xyz) const"
.br
.RI "returns the global coordinates of the element integration point "
.ti -1c
.RI "virtual double \fBWeightAtIntegrationPoint\fP (uint32_t i) const"
.br
.RI "returns the integration weight of the desired quadrature point "
.ti -1c
.RI "virtual void \fBN\fP (std::vector< double > &N, const std::vector< double > &xyz)"
.br
.RI "reports the values of the interpolation functions at the point given in global coordinates; "
.ti -1c
.RI "virtual void \fBN_AtIntegrationPoint\fP (uint32_t ip, std::vector< double > &\fBN\fP)"
.br
.RI "reports the values of the interpolation functions at the given quadrature point "
.ti -1c
.RI "virtual void \fBN_AtBaryCenter\fP (std::vector< double > &\fBN\fP)"
.br
.RI "reports the values of the interpolation functions at the center of gravity of the element "
.ti -1c
.RI "virtual void \fBdN\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "first derivatives of interpolation functions for elements where this is a single constant value "
.ti -1c
.RI "virtual double \fBdN_At\fP (\fBDenseMatrix\fP< DM_MIN > &, const std::vector< double > &xyz)"
.br
.RI "returns first derivative of interpolaton functions at global point; in isoparametric elements, the determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual double \fBdN_AtIntegrationPoint\fP (\fBDenseMatrix\fP< DM_MIN > &, uint32_t gauss_point)"
.br
.RI "returns first derivative of interpolaton functions at quadrature point; determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual double \fBdN_AtNode\fP (\fBDenseMatrix\fP< DM_MIN > &, uint32_t node)"
.br
.RI "returns first derivative of interpolaton functions at node; determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual double \fBdN_AtBarycenter\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "returns first derivative of interpolaton functions at center of gravity; determinant of the Jacobian is returned as well "
.ti -1c
.RI "virtual void \fBJacobianAtIntegrationPoint\fP (uint32_t ip)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point "
.ti -1c
.RI "virtual void \fBJacobianAt\fP (const std::vector< double > &rst)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point defined in parametric space (r,s,t) "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 1D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr, const std::vector< double > &dns)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 2D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual void \fBJacobian\fP (const std::vector< double > &dnr, const std::vector< double > &dns, const std::vector< double > &dnt)"
.br
.RI "initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 3D element using the supplied intpol\&.f\&.derivatives "
.ti -1c
.RI "virtual double \fBJacobianInverse\fP ()"
.br
.RI "initializes the member matrix JINV "
.ti -1c
.RI "virtual double \fBJacobianDeterminant\fP ()"
.br
.RI "returns the determinant of the member Jacobian matrix JAC that must have been initialised before "
.ti -1c
.RI "virtual void \fBIntegralNN\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "initialises interpolation function product matrix N^T x N for analytically integrated elements "
.ti -1c
.RI "virtual void \fBIntegraldNdN\fP (\fBDenseMatrix\fP< DM_MIN > &)"
.br
.RI "initialises interpolation function derivatives product matrix DN^T x DN for element where derivatives are constant "
.ti -1c
.RI "virtual void \fBIntegral_dNT_K_dN\fP (\fBDenseMatrix\fP< DM_MIN > &\fBM\fP, \fBDenseMatrix\fP< DM_MIN > &K)"
.br
.ti -1c
.RI "virtual void \fBNr\fP (double r, std::vector< double > &\fBNRST\fP) const"
.br
.RI "1D element interpolation functions N(r) "
.ti -1c
.RI "virtual void \fBdNr\fP (double r, std::vector< double > &\fBDNR\fP) const"
.br
.RI "1D element interpolation functions derivatives N(r)/dr "
.ti -1c
.RI "virtual void \fBNrs\fP (double r, double s, std::vector< double > &\fBNRST\fP) const"
.br
.RI "2D element interpolation functions N(r,s) "
.ti -1c
.RI "virtual void \fBdNr\fP (double r, double s, std::vector< double > &\fBDNR\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s)/dr "
.ti -1c
.RI "virtual void \fBdNs\fP (double r, double s, std::vector< double > &\fBDNS\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s)/ds "
.ti -1c
.RI "virtual void \fBNrst\fP (double r, double s, double t, std::vector< double > &\fBNRST\fP) const"
.br
.RI "3D element interpolation functions N(r,s,t) "
.ti -1c
.RI "virtual void \fBdNr\fP (double r, double s, double t, std::vector< double > &\fBDNR\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/dr "
.ti -1c
.RI "virtual void \fBdNs\fP (double r, double s, double t, std::vector< double > &\fBDNS\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/ds "
.ti -1c
.RI "virtual void \fBdNt\fP (double r, double s, double t, std::vector< double > &\fBDNT\fP) const"
.br
.RI "2D element interpolation functions derivatives N(r,s,t)/dt "
.ti -1c
.RI "virtual void \fBOut\fP () const"
.br
.RI "prints finite element properties to screen "
.ti -1c
.RI "virtual void \fBOutputNodeDataToVTK\fP (const char *file_name, const char *var_name, \fBDenseMatrix\fP< DM_MIN > &DATA) const"
.br
.RI "prints the current finite element into a visualisation toolkit (VTK) textfile for visual examination "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static size_t \fBInitialID\fP ()"
.br
.RI "returns ID value set to FEM during construction "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBXY\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBJAC\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBJINV\fP"
.br
.ti -1c
.RI "std::vector< double > \fBNRST\fP"
.br
.RI "convenience storage for interpolation function values "
.ti -1c
.RI "std::vector< double > \fBDNR\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< double > \fBDNS\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< double > \fBDNT\fP"
.br
.RI "convenience storage for interpolation function derivatives "
.ti -1c
.RI "std::vector< uint32_t > \fBIDX\fP"
.br
.RI "convenience storage for integer vectors "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBFiniteElement\fP (const \fBFiniteElement\fP &)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP (\fBFiniteElement\fP &&)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP & \fBoperator=\fP (const \fBFiniteElement\fP &)=default"
.br
.ti -1c
.RI "\fBFiniteElement\fP & \fBoperator=\fP (\fBFiniteElement\fP &&)=default"
.br
.ti -1c
.RI "void \fBIsoparametric\fP (bool isoparam)"
.br
.ti -1c
.RI "void \fBUsesLocalCoordinates\fP (bool uses)"
.br
.ti -1c
.RI "void \fBLineElement\fP ()"
.br
.ti -1c
.RI "void \fBSurfaceElement\fP ()"
.br
.ti -1c
.RI "void \fBVolumeElement\fP ()"
.br
.ti -1c
.RI "void \fBElementType\fP (\fBCSMP_FEM_TYPE\fP etype)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBdim\fP"
.br
.ti -1c
.RI "uint32_t \fBitp\fP"
.br
.ti -1c
.RI "uint32_t \fBnpf\fP"
.br
.ti -1c
.RI "uint32_t \fBnpe\fP"
.br
.ti -1c
.RI "uint32_t \fBspe\fP"
.br
.ti -1c
.RI "uint32_t \fBfpe\fP"
.br
.ti -1c
.RI "uint32_t \fBepe\fP"
.br
.ti -1c
.RI "uint32_t \fBnne\fP"
.br
.ti -1c
.RI "uint32_t \fBcne\fP"
.br
.ti -1c
.RI "uint32_t \fBgpe\fP"
.br
.ti -1c
.RI "\fBDenseMatrix\fP< DM_MIN > \fBM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CSMP's base class of all finite elements whose functionality is provided through polymorphism\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1996
.RE
.PP
.SH "Motivation"
.PP
\fBBase\fP class for CSMP's finite element library\&. 
.br
.SH "Design Intent"
.PP
Provide a unified interface for all finite element calculations carried out by CSMP\&. 
.br

.PP
Store the matrices necessary for finite element computations so that these do not have to be constructed/destructed by every method that uses them\&. 
.br
.SH "Collaborations"
.PP
Forms a bridge pattern with the \fBElement\fP class which provides an interface to it\&. Used by any FEM calculations facilitated by the Algorithm class\&.

.PP
\fBTodo\fP
.RS 4
make this class a Singleton and avoid pointer connections with elements
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double csmp::FiniteElement::AspectRatio ()\fR [virtual]\fP"

.PP
returns the ratio between the maximum and minimum spatial extent of the element 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::CornerNodes (std::vector< uint32_t > & ids) const\fR [virtual]\fP"

.PP
reports only the corner nodes (0\&.\&.nodes-1) of the element 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "std::vector< uint32_t > csmp::FiniteElement::CornerNodesOfFace (uint32_t face_id) const\fR [virtual]\fP"

.PP
returns the local numbers of the corner nodes of the face 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::dN (\fBDenseMatrix\fP< DM_MIN > & DM)\fR [virtual]\fP"

.PP
first derivatives of interpolation functions for elements where this is a single constant value 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "double csmp::FiniteElement::dN_At (\fBDenseMatrix\fP< DM_MIN > & DM, const std::vector< double > & xyz)\fR [virtual]\fP"

.PP
returns first derivative of interpolaton functions at global point; in isoparametric elements, the determinant of the Jacobian is returned as well 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "double csmp::FiniteElement::dN_AtBarycenter (\fBDenseMatrix\fP< DM_MIN > & DM)\fR [virtual]\fP"

.PP
returns first derivative of interpolaton functions at center of gravity; determinant of the Jacobian is returned as well 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "double csmp::FiniteElement::dN_AtIntegrationPoint (\fBDenseMatrix\fP< DM_MIN > & DM, uint32_t gauss_point)\fR [virtual]\fP"

.PP
returns first derivative of interpolaton functions at quadrature point; determinant of the Jacobian is returned as well 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "double csmp::FiniteElement::dN_AtNode (\fBDenseMatrix\fP< DM_MIN > & DM, uint32_t node)\fR [virtual]\fP"

.PP
returns first derivative of interpolaton functions at node; determinant of the Jacobian is returned as well 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, and \fBcsmp::LinearLineElement\fP\&.
.SS "void csmp::FiniteElement::dNr (double r, double s, double t, std::vector< double > & DNR) const\fR [virtual]\fP"

.PP
2D element interpolation functions derivatives N(r,s,t)/dr 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, and \fBcsmp::IsoparametricQuadraticTetrahedron\fP\&.
.SS "void csmp::FiniteElement::dNr (double r, double s, std::vector< double > & DNR) const\fR [virtual]\fP"

.PP
2D element interpolation functions derivatives N(r,s)/dr 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "void csmp::FiniteElement::dNr (double r, std::vector< double > & DNR) const\fR [virtual]\fP"

.PP
1D element interpolation functions derivatives N(r)/dr 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearLineElement\fP, and \fBcsmp::IsoparametricQuadraticLineElement\fP\&.
.SS "void csmp::FiniteElement::dNs (double r, double s, double t, std::vector< double > & DNS) const\fR [virtual]\fP"

.PP
2D element interpolation functions derivatives N(r,s,t)/ds 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, and \fBcsmp::IsoparametricQuadraticTetrahedron\fP\&.
.SS "void csmp::FiniteElement::dNs (double r, double s, std::vector< double > & DNS) const\fR [virtual]\fP"

.PP
2D element interpolation functions derivatives N(r,s)/ds 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "void csmp::FiniteElement::dNt (double r, double s, double t, std::vector< double > & DNT) const\fR [virtual]\fP"

.PP
2D element interpolation functions derivatives N(r,s,t)/dt 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, and \fBcsmp::IsoparametricQuadraticTetrahedron\fP\&.
.SS "void csmp::FiniteElement::EdgeLengths (std::vector< double > & vec)\fR [virtual]\fP"

.PP
reports the lengths of all edges (connections between nodes) in the currrent element 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "\fBCSMP_FEM_TYPE\fP csmp::FiniteElement::ElementTypeOfFace (uint32_t face) const\fR [virtual]\fP"

.PP
reports the element type that would match that of its corresponding face 
.PP
\fBTodo\fP
.RS 4
(2-P) Remove typid by name fct 
.RE
.PP

.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "\fBCSMP_FEM_TYPE\fP csmp::FiniteElement::ElementTypeOfSegment (uint32_t segment) const\fR [virtual]\fP"

.PP
reports the element type that would match that of its corresponding segment 
.PP
\fBTodo\fP
.RS 4
(2-P) Remove typid by name fct 
.RE
.PP

.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::ExtrapolateIntegrationPointVariableToNodes (uint32_t nvars, const std::vector< double > & IVAR, std::vector< double > & NVAR) const\fR [virtual]\fP"

.PP
using the interpolation functions, the supplied suite of scalar variable values is extrapolated from the Gauss points to the nodes Extrapolation member( gauss points to nodes )

.PP
Expects input vector to be of size nvars * gauss points and in format [ var1 @ gp1, var2 @ gp1, var3 @ gp1, var1 @ gp2, var2 @ gp2, var3 @ gp2 for all gauss points, with nvar == 3 ] 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "size_t csmp::FiniteElement::InitialID ()\fR [static]\fP"

.PP
returns ID value set to FEM during construction initalizing to a value that makes sure that ID does not equal initial element idx 
.SS "double csmp::FiniteElement::InnerRadius ()\fR [virtual]\fP"

.PP
returns the radius of the largest sphere that could be inscribed in the element 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::IntegraldNdN (\fBDenseMatrix\fP< DM_MIN > & DM)\fR [virtual]\fP"

.PP
initialises interpolation function derivatives product matrix DN^T x DN for element where derivatives are constant 
.PP
Reimplemented in \fBcsmp::LinearCuboid\fP\&.
.SS "void csmp::FiniteElement::IntegralNN (\fBDenseMatrix\fP< DM_MIN > & DM)\fR [virtual]\fP"

.PP
initialises interpolation function product matrix N^T x N for analytically integrated elements 
.PP
Reimplemented in \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::IntegrationPoint (uint32_t i, std::vector< double > & xyz) const\fR [virtual]\fP"

.PP
returns the global coordinates of the element integration point 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "void csmp::FiniteElement::Jacobian (const std::vector< double > & dnr)\fR [virtual]\fP"

.PP
initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for 1D element using the supplied intpol\&.f\&.derivatives Compute the Jacobian matrix for the local coordinate point 'rst' in the finite element\&.

.PP
\fBParameters\fP
.RS 4
\fIdnr\fP The local shape function derivatives at the point of interest\&. These are provided as pointers to inbuilt arrays of type 'double'\&. Whether a third argument is supplied or not determines whether a 2D or a 3D Jacobian is output\&. 
.br
.RE
.PP
The Jacobian matrix is returned into the protected matrix JAC\&. 
.SS "void csmp::FiniteElement::JacobianAt (const std::vector< double > & rst)\fR [virtual]\fP"

.PP
initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point defined in parametric space (r,s,t) 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, and \fBcsmp::IsoparametricQuadraticTetrahedron\fP\&.
.SS "void csmp::FiniteElement::JacobianAtIntegrationPoint (uint32_t ip)\fR [virtual]\fP"

.PP
initialises JAC = DN*XY (intpl\&. derivative * coordinate matrix) parametric-to-physical space transformation matrix for given quadrature point 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "double csmp::FiniteElement::JacobianDeterminant ()\fR [virtual]\fP"

.PP
returns the determinant of the member Jacobian matrix JAC that must have been initialised before 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTriangle\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "double csmp::FiniteElement::JacobianInverse ()\fR [virtual]\fP"

.PP
initializes the member matrix JINV Computes the determinant J of the Jacobian matrix computed for this element/integration point

.PP
\fBAttention\fP
.RS 4
if the calculation fails, an ERROR is reported and some details about the Jacobian are printed to screen\&. 
.RE
.PP

.PP
Reimplemented in \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "void csmp::FiniteElement::MidSideNodes (std::vector< uint32_t > & ids) const\fR [virtual]\fP"

.PP
reports only the mid-edge nodes (0\&.\&.nodes-1) of the element 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "void csmp::FiniteElement::N (std::vector< double > & N, const std::vector< double > & xyz)\fR [virtual]\fP"

.PP
reports the values of the interpolation functions at the point given in global coordinates; 
.PP
\fBAttention\fP
.RS 4
due to iteration method is slow for numerically integrated elements 
.RE
.PP

.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::N_AtBaryCenter (std::vector< double > & N)\fR [virtual]\fP"

.PP
reports the values of the interpolation functions at the center of gravity of the element 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::N_AtIntegrationPoint (uint32_t ip, std::vector< double > & N)\fR [virtual]\fP"

.PP
reports the values of the interpolation functions at the given quadrature point 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "\fBvector\fP< uint32_t > csmp::FiniteElement::NodesConnectedTo (uint32_t node) const\fR [virtual]\fP"

.PP
returns the local numbers of the nodes at the other end of the sgment that the argument node is on 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "\fBvector\fP< uint32_t > csmp::FiniteElement::NodesOfFace (uint32_t face_id) const\fR [virtual]\fP"

.PP
reports the face nodes (0\&.\&.nodes-1) of the given face 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::NodesOfSegment (uint32_t segm_id, std::vector< uint32_t > & snids) const\fR [virtual]\fP"

.PP
reports the egde nodes (0\&.\&.nodes-1) which can be more than 2 in higher-order elements 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "uint32_t csmp::FiniteElement::NodesPerFace (uint32_t face) const\fR [virtual]\fP"

.PP
returns how many nodes make up a particular face; some elements have different numbers 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, and \fBcsmp::IsoparametricQuadraticPyramid\fP\&.
.SS "void csmp::FiniteElement::Nr (double r, std::vector< double > & NRST) const\fR [virtual]\fP"

.PP
1D element interpolation functions N(r) 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearLineElement\fP, and \fBcsmp::IsoparametricQuadraticLineElement\fP\&.
.SS "void csmp::FiniteElement::Nrs (double r, double s, std::vector< double > & NRST) const\fR [virtual]\fP"

.PP
2D element interpolation functions N(r,s) 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "void csmp::FiniteElement::Nrst (double r, double s, double t, std::vector< double > & NRST) const\fR [virtual]\fP"

.PP
3D element interpolation functions N(r,s,t) 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, and \fBcsmp::IsoparametricQuadraticTetrahedron\fP\&.
.SS "void csmp::FiniteElement::OutputNodeDataToVTK (const char * file_name, const char * var_name, \fBDenseMatrix\fP< DM_MIN > & DATA) const\fR [virtual]\fP"

.PP
prints the current finite element into a visualisation toolkit (VTK) textfile for visual examination 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "void csmp::FiniteElement::ReferenceCoordinates (\fBDenseMatrix\fP< DM_MIN > & matCoords) const\fR [virtual]\fP"

.PP
for element types defined using a local coordinate system, returns the node coordinates into the argument matrix Returns the reference coordinates of the element\&.

.PP
\fBDenseMatrix<DM_MIN>\fP & matCoords; -> Holds the reference coordinates of the finite element\&. 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "\fBvector\fP< double > csmp::FiniteElement::UnitNormal () const\fR [virtual]\fP"

.PP
returns unit normal to element where it makes sense (line and surface elements); expects XY matrix to be initialised with node coordinates 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SS "void csmp::FiniteElement::UnitNormalAtFaceBarycenter (uint32_t face, std::vector< double > & nrml)\fR [virtual]\fP"

.PP
computes unit normal to face using a parametric to physical space transformation available in elements with a local coordinate framework This method is intended for numerically integrated element types with higher order shape functions\&. As these elements can get deformed in physical space, it is important to specify the precise location of the unit normal\&.

.PP
\fBNote\fP
.RS 4
this method cannot be constant because it modifies matrices that are data members of the \fBFiniteElement\fP class\&. 
.RE
.PP

.PP
Reimplemented in \fBcsmp::IsoparametricQuadraticTetrahedron\fP\&.
.SS "void csmp::FiniteElement::UnitNormalToFace (uint32_t face, std::vector< double > & unrml) const\fR [virtual]\fP"

.PP
returns the unit normal to element face (for planar elements, normal lies in that plane; expects XY matrix to be initialised with node coordinates Virtual function stub, overload method in desired subclass of \fBFiniteElement\fP

.PP
method should return the unit normal to element face (for planar elements, this normal will lie in that plane

.PP
method expects that the XY matrix is initialised with node coordinates 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "double csmp::FiniteElement::Volume ()\fR [virtual]\fP"

.PP
computes and returns the volume of the element which is an area for a surface- and a length for a line element 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, \fBcsmp::IsoparametricQuadraticTriangle\fP, \fBcsmp::LinearCuboid\fP, \fBcsmp::LinearLineElement\fP, \fBcsmp::LinearRectangle\fP, \fBcsmp::LinearTetrahedron\fP, \fBcsmp::LinearTriangle3D\fP, and \fBcsmp::LinearTriangle\fP\&.
.SS "double csmp::FiniteElement::WeightAtIntegrationPoint (uint32_t i) const\fR [virtual]\fP"

.PP
returns the integration weight of the desired quadrature point 
.PP
Reimplemented in \fBcsmp::IsoparametricLinearHexahedron\fP, \fBcsmp::IsoparametricLinearLineElement\fP, \fBcsmp::IsoparametricLinearPrism\fP, \fBcsmp::IsoparametricLinearPyramid\fP, \fBcsmp::IsoparametricLinearQuadrilateral\fP, \fBcsmp::IsoparametricLinearTetrahedron\fP, \fBcsmp::IsoparametricLinearTriangle\fP, \fBcsmp::IsoparametricQuadraticHexahedron\fP, \fBcsmp::IsoparametricQuadraticLineElement\fP, \fBcsmp::IsoparametricQuadraticPrism\fP, \fBcsmp::IsoparametricQuadraticPyramid\fP, \fBcsmp::IsoparametricQuadraticQuadrilateral\fP, \fBcsmp::IsoparametricQuadraticTetrahedron\fP, and \fBcsmp::IsoparametricQuadraticTriangle\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t csmp::FiniteElement::cne\fR [protected]\fP"
typical number of elements that share each integration point 
.SS "uint32_t csmp::FiniteElement::dim\fR [protected]\fP"
spatial dimension of element 
.SS "uint32_t csmp::FiniteElement::epe\fR [protected]\fP"
neighbors of element 
.SS "uint32_t csmp::FiniteElement::fpe\fR [protected]\fP"
faces per element 
.SS "uint32_t csmp::FiniteElement::gpe\fR [protected]\fP"
Gauss points per element for numerical integration 
.SS "uint32_t csmp::FiniteElement::itp\fR [protected]\fP"
degree of interpolation 
.SS "\fBDenseMatrix\fP<DM_MIN> csmp::FiniteElement::JAC"
Jacobian matrix 
.SS "\fBDenseMatrix\fP<DM_MIN> csmp::FiniteElement::JINV"
the Jacobians inverse 
.SS "\fBDenseMatrix\fP<DM_MIN> csmp::FiniteElement::M\fR [protected]\fP"
test-function coefficients 
.SS "uint32_t csmp::FiniteElement::nne\fR [protected]\fP"
typical number of elements that share each node 
.SS "uint32_t csmp::FiniteElement::npe\fR [protected]\fP"
nodes per element 
.SS "uint32_t csmp::FiniteElement::npf\fR [protected]\fP"
nodes per face 
.SS "uint32_t csmp::FiniteElement::spe\fR [protected]\fP"
segments per element 
.SS "\fBDenseMatrix\fP<DM_MIN> csmp::FiniteElement::XY"
node coordinates 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
