.TH "csmp::Solver" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Solver \- Inverts global solution matrices matrices of the finite-element computations using a variety of solution procedures sparse matrices (class \fBSparseMatrix\fP)\&. \fBSolver\fP base class in strategy pattern\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Solver\&.h>\fP
.PP
Inherited by \fBcsmp::EigenSolver\fP, \fBcsmp::GaussJordan_Solver\fP, \fBcsmp::LUdcmp_Solver\fP, \fBcsmp::PARDISO_Solver\fP, and \fBcsmp::SAMG_Solver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSolver\fP ()"
.br
.ti -1c
.RI "\fBSolver\fP (\fBSolverSettings\fP *settings)"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verb)"
.br
.ti -1c
.RI "bool \fBVerbose\fP () const"
.br
.ti -1c
.RI "void \fBSolve\fP (\fBSparseMatrix\fP &G, std::vector< double > &rh, std::vector< double > &x, size_t no_unknowns=1U)"
.br
.ti -1c
.RI "void \fBSolve\fP (\fBCompressedRowMatrix\fP &G, std::vector< double > &rh, std::vector< double > &x, size_t no_unknowns=1U)"
.br
.ti -1c
.RI "void \fBOut\fP (const \fBSparseMatrix\fP &mat, const char *fname='SparseMatrix') const"
.br
.ti -1c
.RI "void \fBOut\fP (const std::vector< double > &vec, const char *fname='CSP_Vec') const"
.br
.ti -1c
.RI "double \fBCalculateResidual\fP (const \fBSparseMatrix\fP &A, const std::vector< double > &b, const std::vector< double > &x) const"
.br
.ti -1c
.RI "virtual void \fBInputSolverSettings\fP (\fBSolverSettings\fP &settings)"
.br
.ti -1c
.RI "virtual \fBSolverSettings\fP * \fBGetSolverSettings\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSolveMatrixEquation\fP (\fBSparseMatrix\fP &A, std::vector< double > &b, std::vector< double > &x, size_t no_unknowns)=0"
.br
.ti -1c
.RI "virtual void \fBSolveMatrixEquation\fP (\fBCompressedRowMatrix\fP &A, std::vector< double > &b, std::vector< double > &x, size_t no_unknowns)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSolverSettings\fP * \fBsolver_settings_\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inverts global solution matrices matrices of the finite-element computations using a variety of solution procedures sparse matrices (class \fBSparseMatrix\fP)\&. \fBSolver\fP base class in strategy pattern\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1999
.RE
.PP
.SH "Design Intent"
.PP
To encapsulate numerical algebraic methods in an object which services the \fBPDE_Integrator\fP and other class objects\&.
.SH "Applicability"
.PP
Currently the solver offers an algebraic multigrid method (AMG), a conjugate gradient method (CG), and a Gaussian elimination method (GE) as solution schemes\&. Gaussian elimination can be applied to non-symmetric matrices as they arise if advection-dispersion matrices are accumulated into the global solution matrix\&. The algebraic multigrid and conjugate gradient methods require symmetric positive-definite (no negative elements in the diagonal) solution matrices in order to be applicable\&.

.PP
Dependent on the size of the computation different solution methods are appropriate: If you have a very small test problem, like a 30 x 30 matrix, CG ist as fast or faster than AMG and it will require less storage\&. Above a size of 50 x 50, AMG becomes much faster than the other methods\&.
.SH "Participants"
.PP
Each inversion involves a sparse global solution matrix of type SpMat, a righthand, and a solution vector of type \fBvector<double>\fP\&.
.SH "Implementation"
.PP
The \fBSolver\fP uses the Meschach++ and the AMG libraries to carry out the matrix operations\&. The user sets the private variable solution method, whose default is algebraic multigrid\&.
.SH "Application Examples"
.PP
The \fBSolver\fP is called by the Algorithm and Algorithm objects, when they are submitted to the \fBModel\fP through its Apply() interfaces\&. In this process the Algorithm hands the solver the global solution matrix 'G', the solution vector 'x' and the righthand vector 'rh'\&.:

.PP
.PP
.nf
SolveMatrixEquation( G, rh, x );
.fi
.PP

.PP
The \fBSolver\fP then returns the solution into 'x' and it is tested further by the Algorithm before it is mapped back to the \fBModel\fP variable storage\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::Solver::Solver ()"
Default constructor chooses the algebraic multigrid method as solution method, sets the pivot factor to 0\&.5, and the residual multiplication factor to 1\&.0e-15\&. Verbose is disabled and therefore no solution matrices or vectors will be printed\&. 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::Solver::CalculateResidual (const \fBSparseMatrix\fP & A, const std::vector< double > & b, const std::vector< double > & x) const"
Calculates the size of the residual error by comparing the product A*x with the righthand vector b\&. 
.br
.SH "Input Arguments"
.PP
The global solution matrix, the righthand vector, and the solution vector\&.
.SH "Application Examples"
.PP
To calculate the residual of a solution to see whether the solver reached some convergence and how good the solution actually is\&. 
.SS "void csmp::Solver::InputSolverSettings (\fBSolverSettings\fP & settings)\fR [virtual]\fP"

.PP
Reimplemented in \fBcsmp::SAMG_Solver\fP\&.
.SS "void csmp::Solver::Out (const \fBSparseMatrix\fP & mat, const char * fname = \fR'SparseMatrix'\fP) const"
Outputs the solution matrix to a textfile in \fBSparseMatrix\fP output format\&.
.SH "Input Arguments"
.PP
The first argument is a constant reference to the solution matrix and the second argument is the name of the file which the matrix will be output to\&. To this file name, the global runtime of the model and the extension '\&.text' will be appended\&. 
.br
.SH "Implementation"
.PP
\fBOut()\fP calls the Meschach function sp_foutput()\&.
.SH "Application Examples"
.PP
To independently test the solution matrix or to transfer it to another solver\&.
.SH "Messages"
.PP
A successful write will be reported\&. 
.SS "void csmp::Solver::Out (const std::vector< double > & vec, const char * fname = \fR'CSP_Vec'\fP) const"
Outputs the Meschach++ vector 'vec' to a textfile in Meschach++ output format\&.
.SH "Input Arguments"
.PP
The first argument is a constant reference to the Meschach vector and the second argument is the name of the file which the vector will be output to\&. To this file name, the global runtime of the model and the extension '\&.text' will be appended\&. 
.br
.SH "Implementation"
.PP
\fBOut()\fP calls the Meschach function v_foutput() on a standard C filestream\&.
.SH "Application Examples"
.PP
To independently examine a solution or righthand vector or to transfer it to another solver\&.
.SH "Messages"
.PP
A failure to open the output file or a successful write will be reported\&. 
.SS "void csmp::Solver::Solve (\fBSparseMatrix\fP & A, std::vector< double > & b, std::vector< double > & x, size_t no_unknowns = \fR1U\fP)"
Calls solution methods from the Meschach++ and algebraic multigrid libraries to invert the global solution matrix\&. If the solution process fails, the solution matrix and the righthand vector are output to textfiles whose name contains the runtime in seconds and which have the extension '\&.text'\&.

.PP
\fBParameters\fP
.RS 4
\fIA\fP The sparse solution matrix A, 
.br
\fIb\fP the righthand vector 'b' with boundary conditions, 
.br
\fIx\fP the solution vector\&.
.RE
.PP
After successful matrix inversion, the solution vector is returned into 'x'\&.
.SH "Implementation"
.PP
SolveMatrixEquation() first tries to calculate a "typical" size of the residual (the difference between the exact and the numerical solution)\&. Secondly, based on this residual it sets the 'tolerance' for the matrix inversion\&. This involves an initial guess with correct boundary conditions and assumes that the righthand vector b has been setup with Dirichlet boundary conditions and the solution matrix with corresponding 1's on its diagonal\&.

.PP
If the matrix inversion fails, SolveMatrixEquation() calls the method \fBOut()\fP on the solution matrix and the righthand vector\&.
.SH "Application Examples"
.PP
Everytime an Algorithm is passed to the \fBModel\fP, its computation involves the solution of a matrix equation\&.
.SH "Messages"
.PP
If verbose is enabled the method will print out the solution matrix, the solution vector, and the righthand vector\&. Also it will report a gues of the initial residual and the actual residual of the obtained solution:

.PP
.PP
.nf
Typical initial Residue   = 5\&.21798
Residual after solution   = 3\&.58661e\-16
.fi
.PP

.PP
Important is that this output gives the ratio between the typical initial residue and the residual after the solution (here 1\&.0e+16)\&. This ratio is essentially the signal-to-noise ratio and must (as a minimum for the solution to be meaningful), be greater than the ratio between the largest and the smallest dependent-variable value which was specified as initial or as boundary condition\&. 
.br

.PP
When the AMG solver is used, the residual relative to the initial residual is given inside of the AMG output (see above)\&. It is found as the L2 vector norm\&. 
.SS "virtual void csmp::Solver::SolveMatrixEquation (\fBCompressedRowMatrix\fP & A, std::vector< double > & b, std::vector< double > & x, size_t no_unknowns)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Implemented in \fBcsmp::SAMG_Solver\fP\&.
.SS "virtual void csmp::Solver::SolveMatrixEquation (\fBSparseMatrix\fP & A, std::vector< double > & b, std::vector< double > & x, size_t no_unknowns)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Implemented in \fBcsmp::EigenSolver\fP, \fBcsmp::GaussJordan_Solver\fP, \fBcsmp::LUdcmp_Solver\fP, and \fBcsmp::SAMG_Solver\fP\&.
.SS "void csmp::Solver::Verbose (bool verb)"
When verbose is switched on, the \fBSolver\fP will print the global solution matrix, the solution vector, and the righthand side to stdout\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
