.TH "csmp::EclipseWellCompletion" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::EclipseWellCompletion
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBic_\fP"
.br
.ti -1c
.RI "size_t \fBjc_\fP"
.br
.ti -1c
.RI "size_t \fBk_top_\fP"
.br
.ti -1c
.RI "size_t \fBk_bot_\fP"
.br
.ti -1c
.RI "size_t \fBw_start_\fP"
.br
.ti -1c
.RI "size_t \fBw_end_\fP"
.br
.ti -1c
.RI "bool \fBis_open_\fP"
.br
.RI "connected with the reservoir or not "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
