.TH "csmp::GravityProjectionVisitor< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::GravityProjectionVisitor< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <GravityProjectionVisitor\&.h>\fP
.PP
Inherits \fBcsmp::Visitor< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGravityProjectionVisitor\fP (\fBModel\fP< dim > &, const \fBIndex\fP &prop_idx, const \fBIndex\fP &result_idx, \fBVectorVariable\fP< dim > &)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBElement\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBModel\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBRegion\fP< dim > *)"
.br
.ti -1c
.RI "\fBIndex\fP \fBGet_PropertyIndex\fP ()"
.br
.RI "Get Result\&. "
.ti -1c
.RI "\fBIndex\fP \fBGet_ResultIndex\fP ()"
.br
.ti -1c
.RI "void \fBGet_Result\fP (\fBElement\fP< dim > *, \fBVectorVariable\fP< dim > &result)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBVisitor\fP (\fBPLACEMENT\fP level=MODEL, \fBPLACEMENT\fP target=ELEMENT)"
.br
.ti -1c
.RI "void \fBApplicationLevel\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApplicationTarget\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationTarget\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetInitialProperties\fP (\fBModel\fP< dim > *model)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBSplitBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBInterFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBEdge\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBNode\fP< dim > *)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_target_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::GravityProjectionVisitor< dim >"TODO: Who? - What for? 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::GravityProjectionVisitor\fP< dim >::Visit (\fBElement\fP< dim > * eptr)\fR [virtual]\fP"
projection of a vector field in 1D is simply the original fields

.PP
projection of a vector field onto a unit norm vector r(r[0],r[1]),|r|=1 VecProj = ( vec, r ) r

.PP
( VecProj, vec ) > 0 Note that the direction of the result vector should be align with the original one

.PP
projection of a vector field onto a unit norm vector r(r[0],r[1],r[2]),|r|=1 VecProj = ( vec, r ) r

.PP
(n,vec) >0 Note that the direction of the result vector should be align with the original one

.PP
projection of a vector field onto a surface with a unit normal vector n(n[0], n[1], n[2]), |n|=1 VecProj = n x ( n x vec ) = ( vec, n ) n - vec

.PP
( VecProj, vec ) > 0 Note that the direction of the result vector should be align with the original one
.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::GravityProjectionVisitor\fP< dim >::Visit (\fBModel\fP< dim > * m)\fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::GravityProjectionVisitor\fP< dim >::Visit (\fBRegion\fP< dim > * region)\fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
