.TH "csmp::FiniteVolumePolicy< 3U, CELL >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FiniteVolumePolicy< 3U, CELL > \- Policy of the \fBElement\fP class which provides it with the functionality needed for finite-volume stencil formation, i\&.e\&. node-centered finite-volume computations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FiniteVolumePolicy\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFiniteVolumePolicy\fP (const \fBcsmp::FiniteVolumeStencil\fP< 3U > *=nullptr)"
.br
.ti -1c
.RI "\fBFiniteVolumePolicy\fP (const \fBFiniteVolumePolicy\fP &p)"
.br
.ti -1c
.RI "\fBFiniteVolumePolicy\fP & \fBoperator=\fP (const \fBFiniteVolumePolicy\fP &p)"
.br
.ti -1c
.RI "\fBFiniteVolumePolicy\fP (\fBFiniteVolumePolicy\fP &&p) noexcept"
.br
.RI "move semantics "
.ti -1c
.RI "\fBFiniteVolumePolicy\fP & \fBoperator=\fP (\fBFiniteVolumePolicy\fP &&p) noexcept"
.br
.ti -1c
.RI "void \fBAssignFiniteVolume\fP (const \fBcsmp::FiniteVolumeStencil\fP< 3U > *)"
.br
.RI "connect policy to a finite-volume stencil that must match the parent element "
.ti -1c
.RI "void \fBAssignFiniteVolumeNullPtr\fP ()"
.br
.ti -1c
.RI "const \fBFiniteVolumeStencil\fP< 3U > *const \fBFV\fP () const"
.br
.RI "access the stencil functionality directly "
.ti -1c
.RI "uint32_t \fBFacets\fP () const"
.br
.RI "the surface patches that constitute the outside walls of the finite volume "
.ti -1c
.RI "uint32_t \fBSectors\fP () const"
.br
.RI "the volumetric partitions of the finite elements that belong to the different node-centered finite volumes "
.ti -1c
.RI "uint32_t \fBIntegrationPointsPerSector\fP () const"
.br
.RI "volume quadrature points: usually one, but there may be multiple "
.ti -1c
.RI "uint32_t \fBIntegrationPointsPerFacet\fP () const"
.br
.RI "surface quadrature points: usually one, but there may be multiple "
.ti -1c
.RI "void \fBN_AtFacetIntegrationPoint\fP (uint32_t iFacet, uint32_t ip) const"
.br
.RI "finite-element interpolation function values Ni output to NRST vector (stored by the current finite element) at the numbered facet integration point "
.ti -1c
.RI "void \fBN_AtFacetIntegrationPoint\fP (uint32_t iFacet, uint32_t ip, std::vector< double > &NRST) const"
.br
.ti -1c
.RI "void \fBN_AtSectorIntegrationPoint\fP (uint32_t iSector, uint32_t ip) const"
.br
.RI "SKM add-on\&. "
.ti -1c
.RI "void \fBLocal_dN_At\fP (const \fBPoint\fP< 3U > &rst) const"
.br
.RI "interpolation function derivatives at point specified in local coordinates; result is returned into NRST vector of current finite element "
.ti -1c
.RI "double \fBdN_At\fP (const \fBPoint\fP< 3U > &rst, \fBDenseMatrix\fP< DM_MIN > &DN) const"
.br
.RI "interpolation function derivatives at point specified in local coordinates returned into NRST vector of current finite element + detJ for integration "
.ti -1c
.RI "double \fBPropertyValueAtFacetIntegrationPoint\fP (uint32_t iFacet, uint32_t ip, const \fBcsmp::Index\fP &) const"
.br
.RI "interpolates value of scalar node variable to facet integration point (XYZ) "
.ti -1c
.RI "double \fBPropertyValueAtSectorIntegrationPoint\fP (uint32_t iSector, uint32_t ip, const \fBcsmp::Index\fP &) const"
.br
.RI "interpolates value of scalar node variable to sector integration point (XYZ) "
.ti -1c
.RI "template<class Var> void \fBPropertyValueAtFacetIntegrationPoint\fP (const \fBcsmp::Index\fP &, uint32_t iFacet, uint32_t ip, Var &) const"
.br
.RI "interpolate values of any node variable to facet integration point (XYZ) "
.ti -1c
.RI "template<class Var> void \fBPropertyValueAtSectorIntegrationPoint\fP (const \fBcsmp::Index\fP &, uint32_t iSector, uint32_t ip, Var &) const"
.br
.RI "interpolate values of any node variable to sector integration point (XYZ) "
.ti -1c
.RI "double \fBFacetIntegral\fP (uint32_t iFacet, const \fBcsmp::Index\fP &) const"
.br
.RI "integrates value of property over the area of the facet "
.ti -1c
.RI "double \fBSectorIntegral\fP (uint32_t iSector, const \fBcsmp::Index\fP &) const"
.br
.RI "integrates value of property over the sector "
.ti -1c
.RI "double \fBProjectionOnFacetNormal\fP (uint32_t iFacet, const \fBcsmp::Index\fP &) const"
.br
.RI "reads value of vector property and projects it onto facet normal in physical space; returns projected value "
.ti -1c
.RI "double \fBProjectionOnFacetNormal\fP (uint32_t iFacet, const \fBVectorVariable\fP< 3U > &) const"
.br
.RI "projects value of vector property onto facet normal in physical space; returns projection "
.ti -1c
.RI "double \fBSectorVolume\fP (uint32_t iSector) const"
.br
.RI "returns subvolume of finite element that corresponds to the requested finite volume sector "
.ti -1c
.RI "double \fBFacetArea\fP (uint32_t iFacet) const"
.br
.RI "returns the area of the finite-volume facet in physical space as obtained by construction of facet in physical space "
.ti -1c
.RI "double \fBFacetAreaMapped\fP (uint32_t iFacet) const"
.br
.RI "returns the area of the finite volume facet in physical space as obtained by Jacobian transformation of area in parametric space "
.ti -1c
.RI "\fBPoint\fP< 3U > \fBFacetNormal\fP (uint32_t iFacet) const"
.br
.RI "returns the unit normal to the finite-volume facet "
.ti -1c
.RI "\fBPoint\fP< 3U > \fBFacetNormalMapped\fP (uint32_t iFacet) const"
.br
.RI "transforms the facet normal from parametric to physical space and optionally normalises it to obtain a unit length "
.ti -1c
.RI "double \fBParametricFacetArea\fP (uint32_t iFacet) const"
.br
.RI "returns the facet area in parametric space "
.ti -1c
.RI "\fBPoint\fP< 3U > \fBParametricFacetNormal\fP (uint32_t iFacet) const"
.br
.RI "returns the normal to the facet in parametric space "
.ti -1c
.RI "\fBPoint\fP< 3U > \fBFacetPoint\fP (uint32_t iFacet, uint32_t iPoint) const"
.br
.RI "returns facet corner point in physical coordinates using RST_to_XYX "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBElement< 3U >\fP"
.br
.ti -1c
.RI "class \fBFace< 3U >\fP"
.br
.ti -1c
.RI "class \fBInterFace< 3U >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<template< uint32_t > class CELL>
.br
class csmp::FiniteVolumePolicy< 3U, CELL >"Policy of the \fBElement\fP class which provides it with the functionality needed for finite-volume stencil formation, i\&.e\&. node-centered finite-volume computations\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 
.RE
.PP
\fBDate\fP
.RS 4
2003
.RE
.PP
Class is the implementation of the TRAITS design pattern\&. The traits template technique, pioneered by Nathan Myers,is a means of bundling type-dependent declarations together\&.In essence, using traits allows you to mix and match certain types and and values with contexts that use them in a flexible manner, while keeping your code readable and maintainable\&. 
.br

.PP
In our case for example, such code design permits to maintain efficient access to the \fBElement\fP class, thus giving the possibility to tie up Finite Volume and Finite \fBElement\fP parts of the stencil implementation\&. 
.br
.SH "Functionality"
.PP
Provides a set of functionality to perform operations, used in the CVCELL transport method, implemented in CSMP\&. This includes calculation of volumes of sectors and surfaces of internal division walls - facets - inside the element, definition of projections of the velocity at the facet integration point on the normal to the facet, required for flux calculation, etc\&.
.SH "Motivation"
.PP
Part of a consistent framework for generation of the Finite Element/Finite Volume method in CSP\&. Uses the concept of the TRAITS design pattern for efficient access to the the \fBElement\fP class of CSP\&. Give the possibility for elegant coupling and access to Finite \fBElement\fP and Finite Volume frameworks inside CSMP\&.
.SH "Implementation"
.PP
Uses the traints desigh pattern\&. Currently the class is supporting linear iso-parametric family of Finite Elements with reduced polynomial interpolation basis\&. Distinctive feature of the \fBFiniteVolumePolicy\fP class is the possibility to access
.SH "Application Examples"
.PP
No specific application examples are required, as the method is multiply 
.br
 called the great code CSP, within the implementation of the classes ExplicitFiniteVolumeProcessor and others\&. 
.br

.PP
TODO: 
.PP
\fBTodo\fP
.RS 4
(3) Put finiteVolumeAuxiliaryFunctions into \fBFiniteVolumePolicy\fP class (A) TODO: 

.PP
SKM try to do computations in parametric space
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<template< uint32_t > class CELL> \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::FiniteVolumePolicy (const \fBcsmp::FiniteVolumeStencil\fP< 3U > * fvptr = \fRnullptr\fP)"
Default constructor of the traits class\&.
.SH "Application Examples"
.PP
The Traits constructor is called numerous times, it must not allocate memory or do expensive things\&. It initialises the private variable of the class, associated with the element and MemoryManager and updates Coordinate \fBMatrix\fP of the element\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<template< uint32_t > class CELL> void \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::AssignFiniteVolume (const \fBcsmp::FiniteVolumeStencil\fP< 3U > * fvptr)"

.PP
connect policy to a finite-volume stencil that must match the parent element Connects policy to a finite-volume stencil that must match the parent element\&. Check is performed in DEBUG mode that the stencil matches parent element\&. 
.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::dN_At (const \fBPoint\fP< 3U > & rst, \fBDenseMatrix\fP< DM_MIN > & DN) const"

.PP
interpolation function derivatives at point specified in local coordinates returned into NRST vector of current finite element + detJ for integration 
.PP
\fBAttention\fP
.RS 4
SKM: Caution! - not clear what FEM matrices have to do with FV traits 
.RE
.PP

.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::FacetArea (uint32_t iFacet) const"

.PP
returns the area of the finite-volume facet in physical space as obtained by construction of facet in physical space Method calculates the surface area for the given facet\&.

.PP
\fBParameters\fP
.RS 4
\fIiFacet\fP index (No) of the internal facet inside the FE;
.RE
.PP
.SH "Application Examples"
.PP
This method takes the tabulated facet points, converts them to physical space, and then calculates the area of the given facet\&. If the element is a surface element, then only two points describe the facet, therefore, only the distance between these two points will be calculated\&. 
.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::FacetIntegral (uint32_t iSector, const \fBcsmp::Index\fP & prop_key) const"

.PP
integrates value of property over the area of the facet Method calculates the surface integral for given scalar property and finite volume sector\&.

.PP
\fBParameters\fP
.RS 4
\fIiSector\fP index (No) of the target sector of the FE; 
.br
\fIprop_key\fP key of the integrated property name;
.RE
.PP
.SH "Application Examples"
.PP
As the method calculates the value of the surface integral for given property and facet, the value is returned by the method\&. 
.SS "template<template< uint32_t > class CELL> \fBPoint\fP< 3U > \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::FacetNormal (uint32_t iFacet) const"

.PP
returns the unit normal to the finite-volume facet Normal is generated in physical space, using quadrilateral patch, fitted to the facet\&. Method returns the determinant of the Jacobian for the surface at integration point (=facet area)\&.

.PP
\fBParameters\fP
.RS 4
\fIiFacet\fP index (No) of the internal facet is inside the FE;
.RE
.PP
\fBReturns\fP
.RS 4
\fBPoint\fP containing physical normal coordinates\&.
.RE
.PP
.SH "Application Examples"
.PP
This method defines the normal to the facet in physical space, using standard FE methodology of normal definition, fitting the quadrilateral patch to the corner points of the facet in physical space-> This method could be rather computationally expensive, therefore parametric definition of the surface normal is more efficient\&.

.PP
For current implementation index ip is constrained to 0 only, i\&.e-> the FVPEM method is working with 1 facet integration point only\&. 
.SS "template<template< uint32_t > class CELL> \fBPoint\fP< 3U > \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::FacetNormalMapped (uint32_t iFacet) const"

.PP
transforms the facet normal from parametric to physical space and optionally normalises it to obtain a unit length Maps the normal from parametric space to physical space using a 1D to 3D Jacobian in a volumetric element 
.SS "template<template< uint32_t > class CELL> uint32_t \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::Facets () const"

.PP
the surface patches that constitute the outside walls of the finite volume Returns number of facets, 0 if no \fBFiniteVolumeStencil\fP assigned\&. 
.SS "template<template< uint32_t > class CELL> uint32_t \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::IntegrationPointsPerFacet () const"

.PP
surface quadrature points: usually one, but there may be multiple Returns number of integration points per facet, 0 if no \fBFiniteVolumeStencil\fP assigned\&. 
.SS "template<template< uint32_t > class CELL> uint32_t \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::IntegrationPointsPerSector () const"

.PP
volume quadrature points: usually one, but there may be multiple Returns number of integration points per sector, 0 if no \fBFiniteVolumeStencil\fP assigned\&. 
.SS "template<template< uint32_t > class CELL> void \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::Local_dN_At (const \fBPoint\fP< 3U > & rst) const"

.PP
interpolation function derivatives at point specified in local coordinates; result is returned into NRST vector of current finite element The method gets parametric derivatives of interpolation functions at given parametric coordinates\&.
.SH "Application Examples"
.PP
Normally the method is called in connection with all the operations, using the transformation from parametric to physical space and back\&. For that purpose, the user can use public variable of the \fBElement\fP class, containing derivateves: stl vectors DNR,DNS,DNT\&. For example, before constructing the Jacobian matrix of the transformation rst->xyz the user should always call this method\&. 
.SS "template<template< uint32_t > class CELL> void \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::N_AtFacetIntegrationPoint (uint32_t iFacet, uint32_t ip) const"

.PP
finite-element interpolation function values Ni output to NRST vector (stored by the current finite element) at the numbered facet integration point SKM add-on (no rst vector needed !) 
.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::ParametricFacetArea (uint32_t iFacet) const"

.PP
returns the facet area in parametric space Method calculates the value of the facet area in the parametric space of the given finite element\&.

.PP
\fBParameters\fP
.RS 4
\fIiFacet\fP index (No) of the internal facet isnside the FE;
.RE
.PP
.SH "Application Examples"
.PP
The method is applicable to the algorithm of the parametric calculation of fluxes\&. It should be used together with the method ParametricProjectionOnFacetNormal()\&. 
.SS "template<template< uint32_t > class CELL> \fBPoint\fP< 3U > \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::ParametricFacetNormal (uint32_t iFacet) const"

.PP
returns the normal to the facet in parametric space 
.PP
\fBReturns\fP
.RS 4
Reference normal is returned\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIiFacet\fP index (No) of the internal facet isnside the FE;
.RE
.PP
\fBReturns\fP
.RS 4
reference to STL vector of the reference normal coordinates\&.
.RE
.PP
.SH "Application Examples"
.PP
Application of the method gives the reference normal\&. This reference normal is used to find outwards pointing normal to the facet, not taking care of the orientation of the boundary loop of the facet\&. Dot product of the reference normal and any normal in physical or parametric realisation can be used to define outward pointing normal\&. 
.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::ProjectionOnFacetNormal (uint32_t iFacet, const \fBcsmp::Index\fP & prop_key) const"

.PP
reads value of vector property and projects it onto facet normal in physical space; returns projected value Method carries out projection of the given by name vector property on the normal of the internal facet\&. In this implementation of the method, projection is done in physical space-> The surface parameter corresponds to local number of surfaces per node, 3 or 4 for vertice 5 of the pyramid\&.

.PP
\fBParameters\fP
.RS 4
\fIiFacet\fP index (No) of the internal facet inside the FE; 
.br
\fIprop_key\fP key of the property name;
.RE
.PP
\fBReturns\fP
.RS 4
returned value of the determinant of the transformation of the topologically quadrilateral facet from parametric space of that surface to physical space;
.RE
.PP
.SH "Application Examples"
.PP
The method defines the normal to the facet in physical space, using standard FE methodology of normal definition, fitting the quadrilateral patch to the corner points of the facet in physical space-> This method could be rather computationally expensive, therefore parametric projection on surface normal is more efficient\&.

.PP
For current implementation index ip is constrained to 0 only, i\&.e-> the FVPEM method is working with 1 facet integration point only\&. 
.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::ProjectionOnFacetNormal (uint32_t iFacet, const \fBVectorVariable\fP< 3U > & vc) const"

.PP
projects value of vector property onto facet normal in physical space; returns projection Overloaded method carries out projection of the given vector property on the normal of the internal facet\&. In this implementation of the method, projection is done in physical space-> The surface parameter corresponds to local number of surfaces per node, 3 or 4 for vertice 5 of the pyramid\&.

.PP
\fBParameters\fP
.RS 4
\fIiFacet\fP index (No) of the internal facet isnside the FE; 
.br
\fIvc\fP vector variable (not by database name) for projection;
.RE
.PP
\fBReturns\fP
.RS 4
returned value of the determinant of the transformation of the topologically quadrilateral facet from parametric space of that surface to physical space;
.RE
.PP
.SH "Application Examples"
.PP
This overloaded method defines the normal to the facet in physical space, using standard FE methodology of normal definition, fitting the quadrilateral patch to the corner points of the facet in physical space-> This method could be rather computationally expensive, therefore parametric projection on surface normal is more efficient\&.

.PP
For current implementation index ip is constrained to 0 only, i\&.e-> the FVPEM method is working with 1 facet integration point only\&. 
.SS "template<template< uint32_t > class CELL> template<class Var> void \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::PropertyValueAtFacetIntegrationPoint (const \fBcsmp::Index\fP & prop_key, uint32_t iFacet, uint32_t ip, Var & var) const"

.PP
interpolate values of any node variable to facet integration point (XYZ) 
.PP
\fBAttention\fP
.RS 4
Does not work for array variables at the moment\&. 
.RE
.PP

.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::PropertyValueAtFacetIntegrationPoint (uint32_t iFacet, uint32_t ip, const \fBcsmp::Index\fP & prop_key) const"

.PP
interpolates value of scalar node variable to facet integration point (XYZ) Returns double value of property at given internal facet integration point\&.

.PP
\fBParameters\fP
.RS 4
\fIiFacet\fP index (No) of the internal facet isnside the FE 
.br
\fIip\fP index (No) of the integration point on the facet 
.br
\fIprop_key\fP key of the property name
.RE
.PP
.SH "Application Examples"
.PP
For current implementation index ip is constrained to 0 only, i\&.e-> the FVPEM method is working with 1 facet integration point only\&. 
.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::PropertyValueAtSectorIntegrationPoint (uint32_t iSector, uint32_t ip, const \fBcsmp::Index\fP & prop_key) const"

.PP
interpolates value of scalar node variable to sector integration point (XYZ) Returns double value of property at given volume integration point, inside the volumetric sector of FE, composing FV\&.

.PP
\fBParameters\fP
.RS 4
\fIip\fP index (No) of the integration point on the facet; 
.br
\fIprop_key\fP key of the property name;
.RE
.PP
.SH "Application Examples"
.PP
For current implementation index ip is constrained to 0 only, i\&.e-> the FVPEM method is working with 1 volume sector integration point only\&. 
.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::SectorIntegral (uint32_t iSector, const \fBcsmp::Index\fP & prop_key) const"

.PP
integrates value of property over the sector Method calculates the value of the volume integral for given scalar property and volume sector of finite element\&.

.PP
\fBParameters\fP
.RS 4
\fIiSector\fP index (No) of the internal sector inside the FE; 
.br
\fIprop_key\fP key of the integrated property name;
.RE
.PP
.SH "Application Examples"
.PP
As the method calculates the value of the volume integral for the given property and volume sector, the value is returned by the method\&. 
.SS "template<template< uint32_t > class CELL> uint32_t \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::Sectors () const"

.PP
the volumetric partitions of the finite elements that belong to the different node-centered finite volumes Returns number of sectors, 0 if no \fBFiniteVolumeStencil\fP assigned\&. 
.SS "template<template< uint32_t > class CELL> double \fBcsmp::FiniteVolumePolicy\fP< 3U, CELL >::SectorVolume (uint32_t iSector) const"

.PP
returns subvolume of finite element that corresponds to the requested finite volume sector Method calculates the volume for the given volumetric sector\&.

.PP
\fBParameters\fP
.RS 4
\fIiSector\fP index (No) of the internal facet isnside the FE;
.RE
.PP
.SH "Application Examples"
.PP
Method automatically takes into account composite nature of the sector at the apex of the pyramid\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
