.TH "csmp::SubDomainInfo" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SubDomainInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ModelSubDomain\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.RI "unique name "
.ti -1c
.RI "std::vector< size_t > \fBinterior_elmts\fP"
.br
.RI "cells that have no face on the perimeter "
.ti -1c
.RI "std::vector< size_t > \fBperimeter_elmts\fP"
.br
.RI "cells that have at least one face on perimeter "
.ti -1c
.RI "std::vector< std::vector< uint32_t > > \fBperimeter_faces\fP"
.br
.RI "local 0\&.\&.faces-1 identifiers of the faces of the simplices that lie on domain boundary "
.ti -1c
.RI "std::vector< size_t > \fBinterior_nodes\fP"
.br
.RI "nodes within the subdomain "
.ti -1c
.RI "std::vector< size_t > \fBperimeter_nodes\fP"
.br
.RI "nodes on the perimeter of the subdomain "
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Complete index specifications of a ModelSubDomain
used in the reconstruction of subdomains from binary files\&.

.fi
.PP

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
14/3/2016 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
