.TH "csmp::FiniteVolumePolicy< 2U, CELL >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FiniteVolumePolicy< 2U, CELL > \- full specialization ( 2D )  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FiniteVolumePolicy\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFiniteVolumePolicy\fP (const \fBcsmp::FiniteVolumeStencil\fP< 2U > *=nullptr)"
.br
.ti -1c
.RI "\fBFiniteVolumePolicy\fP (const \fBFiniteVolumePolicy\fP &p)"
.br
.ti -1c
.RI "void \fBAssignFiniteVolume\fP (const \fBcsmp::FiniteVolumeStencil\fP< 2U > *)"
.br
.ti -1c
.RI "void \fBAssignFiniteVolumeNullPtr\fP ()"
.br
.ti -1c
.RI "const \fBFiniteVolumeStencil\fP< 2U > *const \fBFV\fP () const"
.br
.ti -1c
.RI "uint32_t \fBFacets\fP () const"
.br
.RI "Returns number of facets, 0 if no \fBFiniteVolumeStencil\fP assigned\&. "
.ti -1c
.RI "uint32_t \fBSectors\fP () const"
.br
.RI "Returns number of sectors, 0 if no \fBFiniteVolumeStencil\fP assigned\&. "
.ti -1c
.RI "uint32_t \fBIntegrationPointsPerSector\fP () const"
.br
.RI "Returns number of integration points per sector, 0 if no \fBFiniteVolumeStencil\fP assigned\&. "
.ti -1c
.RI "uint32_t \fBIntegrationPointsPerFacet\fP () const"
.br
.RI "Returns number of integration points per facet, 0 if no \fBFiniteVolumeStencil\fP assigned\&. "
.ti -1c
.RI "void \fBN_AtFacetIntegrationPoint\fP (uint32_t iFacet, uint32_t ip) const"
.br
.ti -1c
.RI "void \fBN_AtFacetIntegrationPoint\fP (uint32_t iFacet, uint32_t ip, std::vector< double > &NRST) const"
.br
.ti -1c
.RI "void \fBN_AtSectorIntegrationPoint\fP (uint32_t iSector, uint32_t ip) const"
.br
.ti -1c
.RI "void \fBLocal_dN_At\fP (const \fBPoint\fP< 2U > &rst) const"
.br
.ti -1c
.RI "double \fBdN_At\fP (const \fBPoint\fP< 2U > &rst, \fBDenseMatrix\fP< DM_MIN > &DN) const"
.br
.ti -1c
.RI "double \fBPropertyValueAtFacetIntegrationPoint\fP (uint32_t iFacet, uint32_t ip, const \fBcsmp::Index\fP &prop_key) const"
.br
.ti -1c
.RI "double \fBPropertyValueAtSectorIntegrationPoint\fP (uint32_t iSector, uint32_t ip, const \fBcsmp::Index\fP &prop_key) const"
.br
.ti -1c
.RI "template<class Var> void \fBPropertyValueAtFacetIntegrationPoint\fP (const \fBcsmp::Index\fP &, uint32_t iFacet, uint32_t ip, Var &) const"
.br
.ti -1c
.RI "template<class Var> void \fBPropertyValueAtSectorIntegrationPoint\fP (const \fBcsmp::Index\fP &, uint32_t iSector, uint32_t ip, Var &) const"
.br
.ti -1c
.RI "double \fBFacetIntegral\fP (uint32_t iFacet, const \fBcsmp::Index\fP &prop_key) const"
.br
.ti -1c
.RI "double \fBSectorIntegral\fP (uint32_t iSector, const \fBcsmp::Index\fP &prop_key) const"
.br
.ti -1c
.RI "double \fBProjectionOnFacetNormal\fP (uint32_t iFacet, const \fBcsmp::Index\fP &prop_key) const"
.br
.ti -1c
.RI "double \fBProjectionOnFacetNormal\fP (uint32_t iFacet, const \fBVectorVariable\fP< 2U > &vc) const"
.br
.ti -1c
.RI "double \fBSectorVolume\fP (uint32_t iSector) const"
.br
.ti -1c
.RI "double \fBFacetArea\fP (uint32_t iFacet) const"
.br
.ti -1c
.RI "double \fBFacetAreaMapped\fP (uint32_t iFacet) const"
.br
.ti -1c
.RI "\fBPoint\fP< 2U > \fBFacetNormal\fP (uint32_t iFacet) const"
.br
.ti -1c
.RI "\fBPoint\fP< 2U > \fBFacetNormalMapped\fP (uint32_t iFacet) const"
.br
.ti -1c
.RI "double \fBParametricFacetArea\fP (uint32_t iFacet) const"
.br
.ti -1c
.RI "\fBPoint\fP< 2U > \fBParametricFacetNormal\fP (uint32_t iFacet) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBElement< 2U >\fP"
.br
.ti -1c
.RI "class \fBFace< 2U >\fP"
.br
.ti -1c
.RI "class \fBInterFace< 2U >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<template< uint32_t > class CELL>
.br
class csmp::FiniteVolumePolicy< 2U, CELL >"full specialization ( 2D ) 
.SH "Member Function Documentation"
.PP 
.SS "template<template< uint32_t > class CELL> template<class Var> void \fBcsmp::FiniteVolumePolicy\fP< 2U, CELL >::PropertyValueAtFacetIntegrationPoint (const \fBcsmp::Index\fP & prop_key, uint32_t iFacet, uint32_t ip, Var & var) const"
TODO: test for all relevant cases 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
