.TH "csmp::FRED_Interface" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FRED_Interface \- FRED was a DFN-modelling consortium run by Golder Associates <2004\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FRED_Interface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeFrom_FRED_File\fP (const char *ffb_file)"
.br
.ti -1c
.RI "double \fBBoundingBox\fP (\fBmjl::Point3D\fP &pmin, \fBmjl::Point3D\fP &pmax) const"
.br
.RI "returns volume of box "
.ti -1c
.RI "void \fBMoveGeometryToOrigin\fP ()"
.br
.ti -1c
.RI "void \fBScaleGeometry\fP (double xfac, double yfac, double zfac)"
.br
.RI "scales geometry by supplied factors "
.ti -1c
.RI "void \fBOutputToDXF\fP (const char *dxf_file) const"
.br
.RI "writes entities only DXF file compatible with DXF 12 or earlier "
.ti -1c
.RI "void \fBOutputToTETIN\fP (const char *tetin_file) const"
.br
.ti -1c
.RI "void \fBOutputSelectedRegions\fP (const char *sregions) const"
.br
.ti -1c
.RI "void \fBOutputSelectedFractureDiameters\fP (const char *sregions) const"
.br
.RI "outputs fracture numbers and diameters to text "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
FRED was a DFN-modelling consortium run by Golder Associates <2004\&. 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::FRED_Interface::MoveGeometryToOrigin ()"
places minimum xyz coordinate of all fractures into the origin of the coordinate system 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
