.TH "csmp::FluidPropertyVisitorConfiguration" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FluidPropertyVisitorConfiguration
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBpres_w\fP"
.br
.ti -1c
.RI "const char * \fBpres_o\fP"
.br
.ti -1c
.RI "const char * \fBtemp\fP"
.br
.ti -1c
.RI "const char * \fBdens_w\fP"
.br
.ti -1c
.RI "const char * \fBdens_o\fP"
.br
.ti -1c
.RI "const char * \fBcomp_w\fP"
.br
.ti -1c
.RI "const char * \fBcomp_o\fP"
.br
.ti -1c
.RI "const char * \fBvisc_w\fP"
.br
.ti -1c
.RI "const char * \fBvisc_o\fP"
.br
.ti -1c
.RI "double \fBAPI\fP"
.br
.ti -1c
.RI "double \fBspGr_sp\fP"
.br
.ti -1c
.RI "double \fBPb\fP"
.br
.ti -1c
.RI "double \fBRsb\fP"
.br
.ti -1c
.RI "double \fBmy_o_b\fP"
.br
.ti -1c
.RI "double \fBrho_o_b\fP"
.br
.ti -1c
.RI "double \fBsalinity\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
