.TH "csmp::RandomFieldGenerator< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::RandomFieldGenerator< dim >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRandomElementField2D\fP (\fBModel\fP< dim > &sg, const char *\fBvariable\fP, double mean, double sigma, double xlength, double ylength, bool logarithmic, const char *region='Model', size_t iterations=50)"
.br
.ti -1c
.RI "void \fBRandomNodeField2D\fP (\fBModel\fP< dim > &sg, const char *\fBvariable\fP, double mean, double sigma, double xlength, double ylength, bool logarithmic, const char *region='Model', size_t iterations=50)"
.br
.ti -1c
.RI "void \fBOutputRandomNodeField\fP (\fBModel\fP< dim > &sg)"
.br
.ti -1c
.RI "void \fBOutputRandomElementField\fP (\fBModel\fP< dim > &sg)"
.br
.ti -1c
.RI "void \fBInputRandomNodeField\fP (\fBModel\fP< dim > &sg, const char *\fBvariable\fP)"
.br
.ti -1c
.RI "void \fBInputRandomElementField\fP (\fBModel\fP< dim > &sg, const char *\fBvariable\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
