.TH "csmp::SinglePhaseVelocityVisitor< dim, CELL >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SinglePhaseVelocityVisitor< dim, CELL >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SinglePhaseVelocityVisitor\&.h>\fP
.PP
Inherits \fBcsmp::Visitor< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSinglePhaseVelocityVisitor\fP (\fBModel\fP< dim > &, const char *porosity, const char *conductivity, const char *fluid_density, const char *fluid_pressure, const char *velocity, const char *model_gravity_vector=NULL, const char *pore_velocity=NULL, const char *volume_flux=NULL, const char *nodal_velocity=NULL, const char *nodal_pore_velocity=NULL, const char *nodal_volume_flux=NULL)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (CELL< dim > *)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBVisitor\fP (\fBPLACEMENT\fP level=MODEL, \fBPLACEMENT\fP target=ELEMENT)"
.br
.ti -1c
.RI "void \fBApplicationLevel\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApplicationTarget\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationTarget\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetInitialProperties\fP (\fBModel\fP< dim > *model)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBModel\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBRegion\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBSplitBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBElement\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBInterFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBEdge\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBNode\fP< dim > *)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_target_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class CELL>
.br
class csmp::SinglePhaseVelocityVisitor< dim, CELL >"IMPORTANT: for legacy purposes, the transport class assumes that the supplied velocity has already been scaled to adjust for facet areas coming from the thickness attribute (LDE's)\&. This is perhaps a little unintuitive, since any new user needs to know beforehand that this has to happen\&. The user should always provide the "real" velocity (not scaled) and the transport class should deal with thickness through internal scaling of its facet areas\&. This class calculates single phase velocity in its "de-scaled" form\&. No thickness factor is used\&. Thus, using this calculation with a problem containing LDE's and using legacy transport classes (e\&.g\&. NCFVT) requires an extra step of multiplication by a "thickness" attribute\&.

.PP
The class supports and will take advantage of Open MP by dividing the evaluation of the contributions equally among available threads\&.

.PP
-- Julian M\&. 26-09-2015 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
