.TH "csmp::H2OPropertiesLookUpTable< fT >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::H2OPropertiesLookUpTable< fT >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBH2OPropertiesLookUpTable\fP (bool use_lookup_tables=true)"
.br
.ti -1c
.RI "\fBH2OPropertiesLookUpTable\fP (const \fBH2OPropertiesLookUpTable\fP< fT > &lookup)"
.br
.ti -1c
.RI "\fBH2OPropertiesLookUpTable\fP< fT > & \fBoperator=\fP (const \fBH2OPropertiesLookUpTable\fP< fT > &lookup)"
.br
.ti -1c
.RI "fT \fBLiquidSaturation\fP (fT p, fT t)"
.br
.ti -1c
.RI "fT \fBVaporSaturation\fP (fT p, fT t)"
.br
.ti -1c
.RI "fT \fBSaturationTemperatureFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBLiquidDensityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBVaporDensityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBLiquidEnthalpyFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBVaporEnthalpyFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBLiquidHeatCapacityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBVaporHeatCapacityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBLiquidViscosityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBVaporViscosityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBLiquidCompressibilityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBVaporCompressibilityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBLiquidThermalExpansivityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBVaporThermalExpansivityFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBLiquidPressureDensityDerivativeFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBVaporPressureDensityDerivativeFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBLiquidPressureTemperatureDerivativeFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBVaporPressureTemperatureDerivativeFromP\fP (fT p)"
.br
.ti -1c
.RI "fT \fBSaturationPressureFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBLiquidDensityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBVaporDensityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBLiquidEnthalpyFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBVaporEnthalpyFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBLiquidHeatCapacityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBVaporHeatCapacityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBLiquidViscosityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBVaporViscosityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBLiquidCompressibilityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBVaporCompressibilityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBLiquidThermalExpansivityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBVaporThermalExpansivityFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBLiquidPressureDensityDerivativeFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBVaporPressureDensityDerivativeFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBLiquidPressureTemperatureDerivativeFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBVaporPressureTemperatureDerivativeFromT\fP (fT t)"
.br
.ti -1c
.RI "fT \fBDensity\fP (fT t, fT p)"
.br
.ti -1c
.RI "fT \fBHeatCapacity\fP (fT t, fT p)"
.br
.ti -1c
.RI "fT \fBEnthalpy\fP (fT t, fT p)"
.br
.ti -1c
.RI "fT \fBViscosity\fP (fT t, fT p)"
.br
.ti -1c
.RI "fT \fBThermalExpansivity\fP (fT t, fT p)"
.br
.ti -1c
.RI "fT \fBCompressibility\fP (fT t, fT p)"
.br
.ti -1c
.RI "fT \fBPressureDensityDerivative\fP (fT t, fT p)"
.br
.ti -1c
.RI "fT \fBPressureTemperatureDerivative\fP (fT t, fT p)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
