.TH "source/includes/math/CSMP_mathUtilities.h" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/includes/math/CSMP_mathUtilities.h
.SH SYNOPSIS
.br
.PP
\fR#include 'CSMP_definitions\&.h'\fP
.br
\fR#include 'DenseMatrix\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcsmp::vectorDotProduct< dim, T >\fP"
.br
.RI "scalar product of any two STL vectors (loop is unrolled) "
.ti -1c
.RI "class \fBcsmp::vectorDotProduct< 1U, T >\fP"
.br
.RI "partial specialization of previous template needed to stop recursion "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsmp\fP"
.br
.RI "Complex System Modeling Platform\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBcsmp::degreesToRadians\fP (double deg)"
.br
.RI "all trigonomic functions in C++ take arguments in radians "
.ti -1c
.RI "double \fBcsmp::radiansToDegrees\fP (double rad)"
.br
.ti -1c
.RI "double \fBcsmp::quantiseToScale\fP (double x, double scale)"
.br
.ti -1c
.RI "template<typename T> T \fBcsmp::sign\fP (T val)"
.br
.RI "sign function to determine a positive or negative multiplier= -1 0 1 extracting the sign of a number "
.ti -1c
.RI "template<typename T> T \fBcsmp::square\fP (T val)"
.br
.RI "Square function\&. "
.ti -1c
.RI "double \fBcsmp::rsqrt\fP (double val)"
.br
.RI "Reciprocal square root function\&. "
.ti -1c
.RI "double \fBcsmp::erf_Chebyshev\fP (double)"
.br
.RI "for conversion of numbers to strings use to_string() function "
.ti -1c
.RI "double \fBcsmp::erfc_Chebyshev\fP (double x)"
.br
.RI "approximation of the complementary error function using a Chebyshev polynomial "
.ti -1c
.RI "double \fBcsmp::vector_norm1\fP (std::vector< double > &x, std::vector< double > &scale)"
.br
.RI "L1 norm\&. "
.ti -1c
.RI "double \fBcsmp::vector_norm2\fP (std::vector< double > &x, std::vector< double > &scale)"
.br
.RI "L2 norm\&. "
.ti -1c
.RI "double \fBcsmp::vector_norm_inf\fP (std::vector< double > &x, std::vector< double > &scale)"
.br
.RI "L-infinity norm\&. "
.ti -1c
.RI "void \fBcsmp::vector_randomize\fP (std::vector< double > &x, double scale_fac=1\&.)"
.br
.RI "randomly perturbs the values stored in the supplied floating-point vector "
.ti -1c
.RI "template<typename Var> void \fBcsmp::average\fP (const std::vector< Var > &, Var &)"
.br
.RI "averaging the floating-point values of scalar, vector and tensor variables in CSMP "
.ti -1c
.RI "void \fBcsmp::dN_To2DOF\fP (uint32_t nodes, \fBDenseMatrix\fP< DM_MIN > &DN)"
.br
.RI "FEM matrix transformations, for the case where the solution variable is a vector in 2D, Zienkewicz, volume 1, p\&. 22\&. "
.ti -1c
.RI "void \fBcsmp::dN_To3DOF\fP (uint32_t nodes, \fBDenseMatrix\fP< DM_MIN > &DN)"
.br
.RI "FEM matrix transformations, for the case where the solution variable is a vector in 3D, Zienkewicz, volume 1, p\&. 133\&. "
.ti -1c
.RI "double \fBcsmp::splineValue\fP (double x, double x1, double x2, double y1, double y2, double k1, double k2)"
.br
.RI "auxiliary functions for spline interpolation "
.ti -1c
.RI "double \fBcsmp::splineDerivative\fP (double x, double x1, double x2, double y1, double y2, double k1, double k2)"
.br
.ti -1c
.RI "double \fBcsmp::splineSecondDerivative\fP (double x, double x1, double x2, double y1, double y2, double k1, double k2)"
.br
.ti -1c
.RI "double \fBcsmp::secant_method\fP (double xmin, double xmax, double(*function)(double), double tolerance)"
.br
.RI "finding root of function f(x) by Secant method within the x range [xmin,xmax] "
.ti -1c
.RI "double \fBcsmp::secant_line\fP (double x_intercept, double xmin, double xmax, double(*flinear)(double), double(*fnonlinear)(double), double tolerance)"
.br
.RI "in the range [xmin,xmax], finds the intersection of the nonlinear function (flinear) with a linear function (fnonlinear) with the given x-axis intercept "
.ti -1c
.RI "double \fBcsmp::maximum_of_function\fP (double xmin, double xmax, double(*function)(double), double tolerance)"
.br
.RI "finding the x value, in the range [xmin,xmax], where function f(x) is maximum by using golden-section search "
.ti -1c
.RI "double \fBcsmp::minimum_of_function\fP (double xmin, double xmax, double(*function)(double), double tolerance)"
.br
.RI "finding the x value, in the range [xmin,xmax], where function f(x) is minimum by using golden-section search "
.ti -1c
.RI "double \fBcsmp::g\fP (double x, double x1, double(*function)(double), double(*dfunction)(double))"
.br
.RI "finding the x value, in the range [xmin,xmax], where function the "df(x)/dx=(f(x)-f(x1))/(x-x1)"\&.\&. this line is the secant and tangent to f(x) at that point "
.ti -1c
.RI "template<typename Var> void \fBcsmp::out\fP (const Var &obj)"
.br
.RI "console output of arguments like STL vectors etc\&. "
.ti -1c
.RI "template<unsigned int dim, typename T> T \fBcsmp::vector_product\fP (const std::vector< T > &a, const std::vector< T > &b)"
.br
.RI "inlined convenience function to facilitate multiplication of STL vectors "
.ti -1c
.RI "template<typename T> T \fBcsmp::lerp\fP (const double t, T x0, T x1)"
.br
.RI "linearly interpolate between two values "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr double \fBcsmp::PI\fP = 3\&.14159265358979323846"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
