.TH "csmp::ErrorHandler" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ErrorHandler \- The singleton \fBErrorHandler\fP implements an issue reporting scheme to support platform-specific message capabilities like error windows or specific options that can be specified for core-dumps etc\&. The error handler further documents the progression of issues that occur during a run so that warnings etc\&. leading up to an error can be examined in the runtime\&.log file\&. Thus, the aim is to provide diagnostics of when and under what conditions an error arose\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ErrorHandler\&.h>\fP
.PP
Inherits \fBcsmp::GenericSingleton< ErrorHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~ErrorHandler\fP ()"
.br
.RI "writes a file called 'Runtime\&.log' with all the current messages when the program terminates "
.ti -1c
.RI "void \fBVerbose\fP (bool VERBOSE)"
.br
.RI "sets output reporting level to verbose (reporting of all events to cout and cerr) "
.ti -1c
.RI "bool \fBVerbose\fP () const"
.br
.RI "reports whether the reporting level is set to VERBOSE "
.ti -1c
.RI "void \fBReportingLevel\fP (\fBCSMP_OUTPUT_LEVEL\fP verb)"
.br
.RI "sets output to corresponding \fBCSMP_OUTPUT_LEVEL\fP "
.ti -1c
.RI "\fBCSMP_OUTPUT_LEVEL\fP \fBReportingLevel\fP () const"
.br
.RI "returns the current setting of the \fBCSMP_OUTPUT_LEVEL\fP "
.ti -1c
.RI "void \fBNote\fP (\fBCSMP_MESSAGE\fP err_type, const std::string &source, const std::string &message)"
.br
.RI "use as "
.ti -1c
.RI "void \fBNote\fP (\fBCSMP_MESSAGE\fP err_type, const std::string &source, const std::string &message1, const std::string &message2)"
.br
.RI "4 argument version of notice "
.ti -1c
.RI "void \fBPrintInfos\fP () const"
.br
.ti -1c
.RI "void \fBPrintWarnings\fP () const"
.br
.ti -1c
.RI "void \fBPrintErrors\fP () const"
.br
.ti -1c
.RI "size_t \fBMaximumNumberOfErrors\fP () const"
.br
.RI "returns how many errors are allowed before program termination is triggered "
.ti -1c
.RI "void \fBWriteErrorsToFile\fP (const char *err_file='ErrorHandler\&.log')"
.br
.RI "writes the content of message containers stored by the handler to file "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "writes contents of contained maps to file "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBGenericSingleton< ErrorHandler >\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBcsmp::GenericSingleton< ErrorHandler >\fP
.in +1c
.ti -1c
.RI "static \fBSingletonType\fP & \fBInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The singleton \fBErrorHandler\fP implements an issue reporting scheme to support platform-specific message capabilities like error windows or specific options that can be specified for core-dumps etc\&. The error handler further documents the progression of issues that occur during a run so that warnings etc\&. leading up to an error can be examined in the runtime\&.log file\&. Thus, the aim is to provide diagnostics of when and under what conditions an error arose\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1999
.RE
.PP
.SH "Messages"
.PP
The \fBErrorHandler\fP classifies (by enumeration), the different messages that are sent to it as INFOs, WARNINGs, ERRORs, and FATAL_ERRORs:

.PP
.PP
.nf
enum csmp_error{ INFO, EXCEPTION, WARNING, ERROR, FATAL_ERROR };
.fi
.PP

.PP
If a FATAL_ERROR is reported, the \fBErrorHandler\fP will terminate the run\&. This role is given to the error handler with its future role as exception handler in mind\&. Present FATAL_ERRORs will become recoverable once exception handling is consistently implemented throughout CSMP\&.
.SH "Design Intent"
.PP
The \fBErrorHandler\fP logs information strings to 'cout' / 'cerr' and to the log file 'ErrorHandler\&.log'\&. To be able to trace a message to its source, a string that consists of the class and method name from which the message originated must be supplied as first message argument\&. In case of an overloaded method additional information is included in braces which identifies the called method uniquely, for example:

.PP
.PP
.nf
ErrorHandler::Notice(char*, char*):
.fi
.PP

.PP
Messages which are written to file, are automatically preceded by a time string which tells the user when the message originated\&. Since messages may also contain numerical data in the description of the error message the \fBErrorHandler\fP interface is overloaded to accept std::string arguments (std::string has overloaded operators that allow the method writer to convert numbers to strings)\&. The functionality of the \fBErrorHandler\fP is planned to be extended to handle top level (C++) exceptions\&. For this purpose the standard exception base classes exception, logic_error, and runtime_error will be subclassed for CSMP-specific error types\&.

.PP
A goal of the exception handling is to store the transient state of a run before it gets aborted such that it can be carried on from this state at a later time, when the error condition has been properly diagnosed\&.
.SH "Applicability"
.PP
The \fBErrorHandler\fP is used inside high-level CSMP objects like the \fBModel\fP etc\&.\&. Only those which carry enough information so that it makes sense to collect user-readable diagnostics from a CSMP run are logged\&. Atomic generic classes report errors directly to the 'cerr' stream\&.
.SH "Structure"
.PP
\fBErrorHandler\fP is a base-level class using STL maps to store the different types of error messages\&.
.SH "Participants"
.PP
A singleton instance(static) is created upon loading the csmp core library\&.
.SH "Collaborations"
.PP
\fBErrorHandler\fP uses the functionality of STL maps and the std::string class\&. The \fBStandard_IO_Handler\fP is used in dialogs with a console user\&. The object \fBBE_Time\fP is contained to log the time at which errors occur\&.
.SH "Consequences"
.PP
The consequent usage of the \fBErrorHandler\fP turns it into an 'Observer' object the functionality of which may be widely extended in future implementations\&. For the time being, the user can use the '*\&.log' file and the screen output to obtain a detailed progress report for his/her CSMP run\&. Interaction with the run, however, is still very limited\&.
.SH "Implementation"
.PP
The \fBErrorHandler\fP stores the message strings in 3 maps corresponding to the message types: INFO, WARNING, ERROR\&. Since only a single FATAL_ERROR can occur before the run is terminated, it is lumped into the ERROR map\&. In the log file, all messages are logged sequentially\&.

.PP
The error log file is written by the destructor of the error handler\&. Because the destructor of a global object is called last, this assures that all messages that arise in the destruction process are logged as well\&.
.SH "Application Examples"
.PP
The \fBErrorHandler\fP is implemented as a Singleton pattern (GoF)\&.

.PP
A reference to the ErrorHanlder instance is acquired as such

.PP
.PP
.nf
#include "ErrorHandler\&.h"
\&.\&.\&.
ErrorHandler& csmp_error( ErrorHandler::Instance() );
\&.\&.\&.
csmp_error\&.Note( ERROR, "MyClass::ProblematicMethod()", "what actually went wrong" );
.fi
.PP

.PP
after which one can call the handler

.PP
.PP
.nf
csmp_error\&.Note( ERROR, "IterativeAlgorithm<dim>::Iterations", "Solution did not converge! " );
.fi
.PP

.PP
alternatively, if i\&.e\&. just a single call is to be made

.PP
.PP
.nf
ErrorHandler::Instance()\&.Note( ERROR, "IterativeAlgorithm<dim>::Iterations", "Solution did not converge! " );
.fi
.PP

.PP
\fBTodo\fP
.RS 4
SKM - resolve how \fBErrorHandler\fP should interact with exception handling
.RE
.PP

.PP
\fBTodo\fP
.RS 4
SKM - use typename capability to find out from which inherited object the message came
.RE
.PP

.PP
\fBTodo\fP
.RS 4
SKM - allow user to intervene and fix some problems
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::ErrorHandler::~ErrorHandler ()"

.PP
writes a file called 'Runtime\&.log' with all the current messages when the program terminates The destructor of the \fBErrorHandler\fP has a special role in that it dumps all the recorded messages in sequential order into the text file 'ErrorHandler\&.log' for examination of the conditions which caused a fatal error or which occurred until the normal termination of the run\&.
.SH "Application Examples"
.PP
Destructors are called automatically when a C++ program exits normally\&. If the Terminate() method ends the run it prompts the generation of the same logfile\&. 
.SH "Member Function Documentation"
.PP 
.SS "size_t csmp::ErrorHandler::MaximumNumberOfErrors () const"

.PP
returns how many errors are allowed before program termination is triggered Returns the maximum number of errors that the \fBErrorHandler\fP permits before issueing a fatal (program terminating) error\&. 
.SS "void csmp::ErrorHandler::Note (\fBCSMP_MESSAGE\fP err_type, const std::string & source, const std::string & message)"

.PP
use as 
.PP
.nf
ErrorHandler& csmp_error( ErrorHandler::Instance() ); csmp_error\&.Note( WARNING, "class::method where this comes from", messsage ); 

.fi
.PP
 
.SS "void csmp::ErrorHandler::Out () const"

.PP
writes contents of contained maps to file The standard CSmP interface used to list the state of the object\&. Here, all recorded messages are printed on 'stdout' in chronological sequence\&. 
.SS "void csmp::ErrorHandler::PrintInfos () const"
To print messages of a specific type, such as INFO, as a list ordered by the object and method names from which the messages originated\&. This is useful, for instance, to test whether a new object performed in the expected way during a complex simulation\&.

.PP
Apart from \fBPrintInfos()\fP there are methods which print warnings (PrintWarnings()), and for errors\&. 
.SS "\fBCSMP_OUTPUT_LEVEL\fP csmp::ErrorHandler::ReportingLevel () const"

.PP
returns the current setting of the \fBCSMP_OUTPUT_LEVEL\fP Returns the current level of error reporting 
.SS "void csmp::ErrorHandler::ReportingLevel (\fBCSMP_OUTPUT_LEVEL\fP verb)"

.PP
sets output to corresponding \fBCSMP_OUTPUT_LEVEL\fP Sets the level of error reporting 
.SS "void csmp::ErrorHandler::Verbose (bool verb)"

.PP
sets output reporting level to verbose (reporting of all events to cout and cerr) Method to suppress runtime error messages\&. The latter can still be output selectively by listing the message maps using the Print\&.\&.\&.() methods\&. 
.SS "void csmp::ErrorHandler::WriteErrorsToFile (const char * err_file = \fR'ErrorHandler\&.log'\fP)"

.PP
writes the content of message containers stored by the handler to file OS-specific program termination prompted by an error classification as FATAL_ERROR\&. Before program terminates, this method writes all the messages which occurred until then to the text file 'ErrorHandler\&.log'\&. This is similar to calling the destructor of the error handler\&. 
.br
.SH "Messages"
.PP
Terminate() will report if it cannot open the output file and prompt the user for a new file name such that the event sequence until the error occurred can still be recorded\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
