.TH "csmp::Brine" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Brine \- Thermodynamic properties of H2O-NaCl solutions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'eos/h2o_nacl/Brine\&.h'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBrine\fP (const double &externaltemperature, const double &externalpressure, const double &externalcomposition)"
.br
.ti -1c
.RI "\fB~Brine\fP ()"
.br
.ti -1c
.RI "double \fBMolarVolume\fP ()"
.br
.ti -1c
.RI "double \fBDMolarVolumeDT\fP ()"
.br
.ti -1c
.RI "double \fBDensity\fP ()"
.br
.ti -1c
.RI "double \fBCompressibilityBar\fP ()"
.br
.ti -1c
.RI "double \fBCompressibility\fP ()"
.br
.ti -1c
.RI "double \fBExpansivity\fP ()"
.br
.ti -1c
.RI "double \fBIsochoreSlope\fP ()"
.br
.ti -1c
.RI "double \fBEnthalpy\fP ()"
.br
.ti -1c
.RI "double \fBHeatCapacity\fP ()"
.br
.ti -1c
.RI "double \fBViscosity\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Thermodynamic properties of H2O-NaCl solutions\&. 


.PP
\fBAuthor\fP
.RS 4
Thomas Driesner, ETH Zuerich 
.RE
.PP
.SH "Contact"
.PP
thomas.driesner@erdw.ethz.ch

.PP
@changes changes Latest Changes 
.br
.SH "Motivation"
.PP
\fBBrine\fP is legacy code from Thomas Driesner's developments for the H2O-NaCl system, but it is REQUIRED in the CSMP context\&. There, it is essential to build accurate lookup tables for the H2O-NaCl system, which are then actually used by CSMP\&. As long as we don't distribute the lookup tables per se for the various platforms, the \fBBrine\fP legacy will remain in CSMP\&.

.PP
\fBBrine\fP computes the properties of H\*<2\*> O-NaCl fluids as a function of temperature-pressure-composition [Celsius, bar, mole fraction NaCl] , according to the paper

.PP
Driesner T\&. (2007): The system H2O-NaCl\&. Part II: Correlations for molar volume, enthalpy, and isobaric heat capacity from 0 to 1000oC, 1 to 5000 bar, and 0 to 1 XNaCl\&. Geochimica et Cosmochimica Acta 71, 4902-4919\&.
.SH "Usage"
.PP
Construct an instance of "Brine" with the temperature (in C), Pressure (Pa) and NaCl Concentration (mass fraction) that live in your code part as constructor arguments\&. "Brine" has an internal mechanism (via const&) to make sure that it always uses the current values of temperature, pressure, and composition that you have calculated externally\&. Public member names should be self-explanatory\&. Don't experiment with making private memebrs public as that will almost inevitably lead to wrong results!

.PP
.PP
.nf
double temperature(100\&.0);       // temperature in your code
double fluid_pressure(10\&.0e6);   // fluid pressure in your code
double massfraction_nacl(0\&.1);   // mass fraction NaCl in fluid, in your code

Brine    brine(temperature, fluid_pressure, massfraction_nacl); // instantiate a Brine object

\&.\&.\&. // simulation goes on

// new values for temperature, fluid pressure, and composition have been computed:
temperature      = newtemperature;
fluid_pressure   = new_fluid_pressure;
massfractionnacl = new_massfraction_nacl;

// retrieve and assign new fluid properties, no need to new communicate he new temperature, fluid pressure, and composition, they are "known" automatically by Brine
rho = brine\&.Density();
mu  = brine\&.Viscosity();
cp  = brine\&.HeatCapacity();

\&.\&.\&. // move on
.fi
.PP
.SH "Dependencies"
.PP
.SH "Known issues"
.PP
Performance is not optimized\&. Whenever one of the public members is invoked ALL properties are being computed\&. There is currently no intention to improve this as \fBBrine\fP should only be used to compute the lookup tables\&. Pressure() still returns values in bars, a legacy from the SoWat development\&. Composition() is in mole fraction NaCl, to convert to other units, the functions in "ConvertConcentrationUnitsNaCl\&.h" may be useful
.SH "Testing"
.PP
testing was done in the period before publication in 2007, prior to writing this documentation, no details are available anymore 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "csmp::Brine::Brine (const double & externaltemperature, const double & externalpressure, const double & externalcomposition)"
custom constructor

.PP
\fBAttention\fP
.RS 4
Use only this conctructor\&. \fBBrine\fP computes thermodynamic properties of H2O-NaCl solutions as a function of temperature, pressure, and composition\&. These governing parameters are typically computed somewhere outside this class\&. By using const refs to those external variables as constructor argument, \fBBrine\fP is able to decipher their current values when being queried for fluid properties\&. Only this constructor is allowed to ensure that functionality, default constructor has been made private\&. 
.RE
.PP

.SS "csmp::Brine::~Brine ()"
destructor 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::Brine::Compressibility ()"
Isothermal compressibility of H2O-NaCl solution in [Pa-1] 
.SS "double csmp::Brine::CompressibilityBar ()"
Isothermal compressibility of H2O-NaCl solution in [bar-1] 
.SS "double csmp::Brine::Density ()"
Density of H2O-NaCl solution in [kg m-3] 
.SS "double csmp::Brine::DMolarVolumeDT ()"
Temperature derivative of molar volume of H2O-NaCl solution in [cm3 mol-1 C-1] 
.SS "double csmp::Brine::Enthalpy ()"
Specific enthalpy of H2O-NaCl solution in [J kg-1] 
.SS "double csmp::Brine::Expansivity ()"
Thermal expansivity of H2O-NaCl solution in [C-1] 
.SS "double csmp::Brine::HeatCapacity ()"
Specific heat capacity of H2O-NaCl solution in [J kg-1 C-1] 
.SS "double csmp::Brine::IsochoreSlope ()"
Isochore slope (dP/dT)_V of H2O-NaCl solution in [Pa C-1] 
.SS "double csmp::Brine::MolarVolume ()"
Molar volume of H2O-NaCl solution in [cm3 mol-1] 
.SS "double csmp::Brine::Viscosity ()"
Dynamic viscosity of H2O-NaCl solution in [Pa s] 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
