.TH "csmp::TensorVariable< 3U >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TensorVariable< 3U > \- full 3D specialisation of the \fBTensorVariable\fP class template  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TensorVariable\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTensorVariable\fP (\fBVARIABLE_FLAG\fP flag, double val)"
.br
.RI "creates isotropic diagonal tensor with diagonal elements equal to supplied value "
.ti -1c
.RI "\fBTensorVariable\fP (\fBVARIABLE_FLAG\fP f, double v11, double v12, double v13, double v21, double v22, double v23, double v31, double v32, double v33)"
.br
.RI "full initialisation where all diagonal elements have the same flag "
.ti -1c
.RI "\fBTensorVariable\fP (const \fBVARIABLE_FLAG\fP f11, const \fBVARIABLE_FLAG\fP f22, const \fBVARIABLE_FLAG\fP f33, const double v11, const double v12, const double v13, const double v21, const double v22, const double v23, const double v31, const double v32, const double v33)"
.br
.RI "full initialisation "
.ti -1c
.RI "double & \fBoperator()\fP (uint32_t i, uint32_t j)"
.br
.RI "read/write access to the elements of the tensor "
.ti -1c
.RI "const double & \fBoperator()\fP (uint32_t i, uint32_t j) const"
.br
.RI "read-only access to the elements of the tensor "
.ti -1c
.RI "void \fBComponent\fP (uint32_t, double)"
.br
.RI "alternative mutator of tensor elements 0\&.\&.8 accessing them sequentially row by row "
.ti -1c
.RI "double \fBComponent\fP (uint32_t i) const"
.br
.RI "alternative accessor of tensor elements 0\&.\&.8 accessing them sequentially row by row "
.ti -1c
.RI "uint32_t \fBSize\fP () const"
.br
.RI "number of entries in tensor (dim x dim = 9 in this 3D case) "
.ti -1c
.RI "void \fBResize\fP (uint32_t, double newValue=std::numeric_limits< double >::quiet_NaN())"
.br
.RI "assigns second argument to all elements of the tensor, first argument is not used; "
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator+\fP (double val) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator\-\fP (double val) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator*\fP (double val) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator/\fP (double val) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator+=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator\-=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator*=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator/=\fP (double val)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator+=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator\-=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator*=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator/=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator+\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator\-\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator*\fP (const \fBTensorVariable\fP &) const"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 3U > \fBoperator*\fP (const \fBVectorVariable\fP< 3U > &) const"
.br
.RI "(A x) matrix-vector multiplication -> vector (v treated as column vector) "
.ti -1c
.RI "\fBPoint\fP< 3U > \fBoperator*\fP (const \fBPoint\fP< 3U > &) const"
.br
.RI "(A x) matrix-vector multiplication -> vector (v treated as column vector) "
.ti -1c
.RI "\fBTensorVariable\fP \fBoperator/\fP (const \fBTensorVariable\fP &) const"
.br
.RI "value by value division of the elements of the tensor with another one "
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator+=\fP (const \fBTensorVariable\fP &)"
.br
.RI "value by value addition of the elements of the tensors "
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator\-=\fP (const \fBTensorVariable\fP &)"
.br
.RI "value by value subtraction from the lh-tensor by the rh tensor "
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator/=\fP (const \fBTensorVariable\fP &)"
.br
.RI "value by value division of the elements of the lh-tensor by those of the righthand tensor "
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator*=\fP (const \fBTensorVariable\fP &)"
.br
.RI "matrix multiplication -> matrix (A\&.rows, B\&.cols); creates temporary tensor, avoid this using 'operator*()' "
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator=\fP (double val)"
.br
.RI "sets all ij values to val or sc "
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator=\fP (const \fBScalarVariable\fP &)"
.br
.RI "sets all ii values to sc (value and flags of diagonal elements) "
.ti -1c
.RI "\fBTensorVariable\fP & \fBoperator=\fP (const \fBVectorVariable\fP< 3U > &)"
.br
.RI "assigns vector to diagonal elements of tensor, off-diagonal elements are set to zero "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTensorVariable\fP &) const"
.br
.RI "element-by-element comparison of ij values "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBTensorVariable\fP &) const"
.br
.RI "element-by-element comparison of ij values "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBTensorVariable\fP &) const"
.br
.RI "comparison of the determinants of the tensors "
.ti -1c
.RI "bool \fBIsWithinRange\fP (double vmin, double vmax) const"
.br
.RI "compares the individual elements of the tensor with the ranges specified in \fBPropertyDatabase\fP file "
.ti -1c
.RI "bool \fBHas_NaN_Values\fP () const"
.br
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBFlag\fP (uint32_t i=0) const"
.br
.RI "returns the flag of the diagonal tensor element of choice "
.ti -1c
.RI "double \fBMinElement\fP () const"
.br
.RI "returns smallest element in tensor (this is zero if the tensor is diagonal) "
.ti -1c
.RI "double \fBMaxElement\fP () const"
.br
.RI "returns largest element in tensor "
.ti -1c
.RI "double \fBDeterminant\fP () const"
.br
.ti -1c
.RI "double \fBTrace\fP () const"
.br
.RI "returns the sum of the diagonal values of the tensor "
.ti -1c
.RI "\fBTensorVariable\fP \fBAdjoint\fP () const"
.br
.RI "returns the conjugate transpose of the tensor (commonly denoted M^(H)) "
.ti -1c
.RI "\fBTensorVariable\fP \fBInverse\fP () const"
.br
.RI "returns a tensor the product of which with the original tensor gives the identity matrix "
.ti -1c
.RI "\fBTensorVariable\fP \fBTransposed\fP () const"
.br
.RI "returns the transposed of the tensor into a new tensor variable "
.ti -1c
.RI "bool \fBEigenValuesPositiveDefiniteSymmetricMatrix\fP (double &eigenValue0, double &eigenValue1, double &eigenValue2) const"
.br
.RI "assuming that the tensor is symmetric and positive definite, method returns its sorted Eigen values (largest to smallest) "
.ti -1c
.RI "bool \fBEigenNonSymmetric\fP (\fBVectorVariable\fP< 3U > &eigenVals, \fBTensorVariable\fP< 3U > &eigenVecs) const"
.br
.RI "alternative Eigen decomposition that should also work for non-symmetric matrices "
.ti -1c
.RI "bool \fBEigenValues\fP (\fBVectorVariable\fP< 3U > &vecEigenvalues) const"
.br
.RI "assuming that the tensor is symmetric and positive definite, its Eigenvalues are returned into the supplied \fBVectorVariable\fP "
.ti -1c
.RI "bool \fBEigenValues\fP (std::vector< double > &vecEigenvalues) const"
.br
.RI "assuming that the tensor is symmetric and positive definite, its Eigenvalues are returned into the supplied STL vector "
.ti -1c
.RI "bool \fBEigen\fP (\fBVectorVariable\fP< 3U > &vvEigenvalues, \fBTensorVariable\fP< 3U > &tvEigenvectors, bool bNormalize) const"
.br
.RI "assuming that the tensor is symmetric and positive definite, method returns Eigenvalues and vectors that can be normalised to 1 "
.ti -1c
.RI "void \fBDiagonalValues\fP (double f_00, double f_11, double f_22)"
.br
.RI "assigns diagonal values to tensor (off-diagonal elements are not touched) "
.ti -1c
.RI "void \fBDiagonalValues\fP (const std::vector< double > &)"
.br
.RI "assigns diagonal values to tensor from STL vector "
.ti -1c
.RI "void \fBDiagonalValues\fP (const \fBVectorVariable\fP< 3U > &)"
.br
.RI "assigns diagonal values to tensor "
.ti -1c
.RI "void \fBAssignToRow\fP (uint32_t i, \fBVectorVariable\fP< 3U > &)"
.br
.RI "assigns vector variable to row i of the tensor "
.ti -1c
.RI "void \fBAssignToColumn\fP (uint32_t j, \fBVectorVariable\fP< 3U > &)"
.br
.RI "assigns vector variable to column j of the tensor "
.ti -1c
.RI "\fBVectorVariable\fP< 3U > \fBRow\fP (uint32_t iRow) const"
.br
.RI "returns row iRow into the argument \fBVectorVariable\fP "
.ti -1c
.RI "\fBVectorVariable\fP< 3U > \fBColumn\fP (uint32_t iCol) const"
.br
.RI "returns column iCol into the argument \fBVectorVariable\fP "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP & \fBFlag\fP (uint32_t i=0)"
.br
.RI "accessor/mutator of the flags of the diagonal elements of the tensor "
.ti -1c
.RI "void \fBIdentity\fP ()"
.br
.RI "converts tensor into identity matrix "
.ti -1c
.RI "void \fBIn\fP ()"
.br
.RI "prompts user to initialise the tensor from the command line "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "prints the tensor to the command line "
.ti -1c
.RI "bool \fBIn\fP (std::fstream &fp)"
.br
.RI "reads the tensor from the supplied input file "
.ti -1c
.RI "bool \fBOut\fP (std::fstream &fp) const"
.br
.RI "writes the tensor to the supplied output file "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr \fBVARIABLE_TYPE\fP \fBVariableType\fP = TENSOR"
.br
.in -1c
.SH "Detailed Description"
.PP 
full 3D specialisation of the \fBTensorVariable\fP class template 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
2001
.RE
.PP
.SH "Motivation"
.PP
Template specialization implementing optimized tensors in CSP\&. Depending on the spatial dimension of the model, tensor variables are either 2 x 2 or 3 x 3 matrices\&. Each value is associated with a flag which can be set to indicate to finite-element computations that the corresponding degree of freedom is enabled or restricted\&.
.SH "Functionality"
.PP
Apart from the standard constructors with a default where all elements are initialized to NaN (not-a-number) and the flags are set to plain, assignment is defined to allow the storage of tensors in STL containers\&. Ordering using STL's less() is facilitated through an \fBoperator<()\fP that compares the determinants of matrices\&. All costly operations like this are unrolled\&.

.PP
\fBTensorVariable\fP implements typical accessors, mutators for tensor elements and operations on entire tensors\&. To get at element 1,2 of 3D tensor, ts, use ts(1,2), for instance\&.

.PP
Value-by-value operations such as matrix addition, subtraction, division are implemented by the operators +, -, /\&. operator*() assumes different meanings dependent on the type of its arguments\&. Thus, tensors can be multiplied with scalars, vectors, and tensors to produce the standard results expected for matrix algebra\&. Other matrix algebraic operations include finding the \fBTransposed()\fP, \fBDeterminant()\fP, \fBInverse()\fP, \fBIdentity()\fP, and \fBAdjoint()\fP matrices\&.

.PP
The *= operator will always produce a temporary matrix\&. Therefore, should be preferred if the result is to be assigned to a new variable\&.

.PP
Assignent of a vector to a tensor is done by placing the vector in the tensors diagonal and zeroing its off-diagonal elements\&.

.PP
Matrices can be input and output via the console, using the \fBIn()\fP and \fBOut()\fP member functions\&.
.SH "Motivation"
.PP
Part of a consistent framework for physical variables for which there exist overloaded operators so that vector-matrix multiplications and other operations can be written in a straight forward way\&.
.SH "Implementation"
.PP
Using the template specialization mechanism of C++\&. Specializations exist only for the 2 and 3D cases\&. These are declared in this (3D) and the header file '\fBTensorVariable2\&.h\fP' (2D), respectively\&.
.SH "Application Examples"
.PP
To diagonalize a tensor variable, one could write:

.PP
.PP
.nf
VectorVariable<double,2> vc(PLAIN,PLAIN,1,1);
TensorVariable<double,2> ts;

ts\&.Identity();
vc = ts * vc;

vc\&.Out();
.fi
.PP

.PP
\fBTodo\fP
.RS 4
(2-D) Const/Non const access operator convention not consistent with VectorVariable/ArrayVariable 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcsmp::TensorVariable\fP< 3U >::TensorVariable (\fBVARIABLE_FLAG\fP f, double val)"

.PP
creates isotropic diagonal tensor with diagonal elements equal to supplied value initialises variable as diagonal isotropic tensor with flag and value SKM 17/6/2015 
.SH "Member Function Documentation"
.PP 
.SS "double \fBcsmp::TensorVariable\fP< 3U >::Determinant () const"

.PP
\fBTest\fP
.RS 4
tested: O\&.K\&. 
.RE
.PP

.SS "bool \fBcsmp::TensorVariable\fP< 3U >::Eigen (\fBVectorVariable\fP< 3U > & evals, \fBTensorVariable\fP< 3U > & evecs, bool bNormalize) const"

.PP
assuming that the tensor is symmetric and positive definite, method returns Eigenvalues and vectors that can be normalised to 1 Computes eigenvalues and eigenvectors assuming that the tensor variable is symmetric\&. If not symmetric, off-diagonal elements are averaged\&. No check of symmetry is performed\&.

.PP
\fBAttention\fP
.RS 4
the Eigenvectors are returned row by row into the evecs tensor\&.
.RE
.PP
By default the length of the eigenvectors is equivalent to the eigenvalues but it can be normalized to one\&.
.SH "Input Arguments"
.PP
Flag to normalize length of eigenvectors to 1\&.

.PP
\fBReturns\fP
.RS 4
Eigenvalues and vectors are returned into the supplied Vector and TensorVariables, respectively\&. Method returns false if the rank of the matrix is zero\&.
.RE
.PP
.SH "Implementation"
.PP
Cubic root finding algorithm using Cardano's formula and the eigenvectors are calculated via LU-backsubstitution\&.

.PP
\fBTest\fP
.RS 4
SKM - observed, by comparison with Maple, that all the values are the same, but that the first element of the second Eigenvector always has the opposite sign (does this matter?)
.RE
.PP

.SS "bool \fBcsmp::TensorVariable\fP< 3U >::EigenNonSymmetric (\fBVectorVariable\fP< 3U > & eigenVals, \fBTensorVariable\fP< 3U > & eigenVecs) const"

.PP
alternative Eigen decomposition that should also work for non-symmetric matrices Computes eigenvalues and eigenvectors for 3d \fBTensorVariable\fP (doesn't have to be symmetric)
.SH "Input Arguments"
.PP
eigenVectors, eigenValues

.PP
\fBReturns\fP
.RS 4
Eigenvalues and vectors are returned into the supplied Vector and TensorVariables, respectively\&.
.RE
.PP
.SH "Implementation"
.PP
Uses: 1) Symmetric Householder reduction to tridiagonal form, derived from the Algol procedures tred2 by Bowdler, Martin, Reinsch, and Wilkinson, Handbook for Auto\&. Comp\&., Vol\&.ii-Linear Algebra, and the corresponding Fortran subroutine in EISPACK\&. 2) Symmetric tridiagonal QL algorithm, derived from the Algol procedures tql2, by Bowdler, Martin, Reinsch, and Wilkinson, Handbook for Auto\&. Comp\&., Vol\&.ii-Linear Algebra, and the corresponding Fortran subroutine in EISPACK\&.

.PP
\fBAuthor\fP
.RS 4
Lukas Mosser? 
.RE
.PP

.SS "bool \fBcsmp::TensorVariable\fP< 3U >::EigenValuesPositiveDefiniteSymmetricMatrix (double & eigenValue0, double & eigenValue1, double & eigenValue2) const"

.PP
assuming that the tensor is symmetric and positive definite, method returns its sorted Eigen values (largest to smallest) Code revision by Hossein Ageshlui (Nov\&. 2015), fixing several errors:

.PP
Previous code included two functions for eigenvalue calculation, using basically the same code, one outputing eigenvalues as a vector and the other one as an object of the class \fBVectorVariable<3U>\fP&\&.

.PP
To shorten the code and to not to cause any issues with previously written code, this new function has been added which calculates eigenvalues as scalar variables\&.

.PP
The old functions now only call this new function and output the eigenvalues as a vector or as an object of a \fBVectorVariable\fP\&. The new code also sorts the eigenvalues in descending order\&.

.PP
Also all the pow (1\&./3\&.) calls are replaced with cbrt()\&. The pow (1\&./\&.3) does not produce a result when used with negative values and it is slow\&. The source for solving the cubic equation is: http://mathworld.wolfram.com/CubicFormula.html 
.SS "bool \fBcsmp::TensorVariable\fP< 3U >::Has_NaN_Values () const"
Checks only the diagonal\&. 
.SS "void \fBcsmp::TensorVariable\fP< 3U >::Identity ()"

.PP
converts tensor into identity matrix 
.PP
\fBTest\fP
.RS 4
tested: O\&.K\&. 
.RE
.PP

.SS "\fBTensorVariable\fP< 3U > \fBcsmp::TensorVariable\fP< 3U >::Inverse () const"

.PP
returns a tensor the product of which with the original tensor gives the identity matrix 
.PP
\fBTest\fP
.RS 4
tested: O\&.K\&. 
.RE
.PP

.SS "bool \fBcsmp::TensorVariable\fP< 3U >::IsWithinRange (double vmin, double vmax) const"

.PP
compares the individual elements of the tensor with the ranges specified in \fBPropertyDatabase\fP file Assumes that tensor is diagonal, checking its Eigen values\&.

.PP
\fBTest\fP
.RS 4
re-tested: SKM 29-9-2001 
.RE
.PP

.SS "double \fBcsmp::TensorVariable\fP< 3U >::MaxElement () const"

.PP
returns largest element in tensor 
.PP
\fBTest\fP
.RS 4
re-tested: SKM 29-9-2001 
.RE
.PP

.SS "double \fBcsmp::TensorVariable\fP< 3U >::MinElement () const"

.PP
returns smallest element in tensor (this is zero if the tensor is diagonal) 
.PP
\fBTest\fP
.RS 4
re-tested: SKM 29-9-2001 
.RE
.PP

.SS "\fBVectorVariable\fP< 3U > \fBcsmp::TensorVariable\fP< 3U >::operator* (const \fBVectorVariable\fP< 3U > & vc) const"

.PP
(A x) matrix-vector multiplication -> vector (v treated as column vector) 
.PP
\fBTest\fP
.RS 4
tested: O\&.K\&. SKM 29-9-2001 
.RE
.PP

.SS "bool \fBcsmp::TensorVariable\fP< 3U >::operator< (const \fBTensorVariable\fP< 3U > & ) const"

.PP
comparison of the determinants of the tensors to achieve reasonable ordering in associative STL containers 
.SS "\fBTensorVariable\fP< 3U > & \fBcsmp::TensorVariable\fP< 3U >::operator= (const \fBVectorVariable\fP< 3U > & vc)"

.PP
assigns vector to diagonal elements of tensor, off-diagonal elements are set to zero writes vector into the diagonal of the zero'd tensor 
.SS "void \fBcsmp::TensorVariable\fP< 3U >::Out () const"

.PP
prints the tensor to the command line 
.PP
\fBTest\fP
.RS 4
tested: O\&.K\&. 
.RE
.PP

.SS "void \fBcsmp::TensorVariable\fP< 3U >::Resize (uint32_t , double newValue = \fRstd::numeric_limits< double >::quiet_NaN()\fP)"

.PP
assigns second argument to all elements of the tensor, first argument is not used; 
.PP
\fBTodo\fP
.RS 4
remove 
.RE
.PP

.SS "\fBTensorVariable\fP< 3U > \fBcsmp::TensorVariable\fP< 3U >::Transposed () const"

.PP
returns the transposed of the tensor into a new tensor variable 
.PP
\fBTest\fP
.RS 4
tested: O\&.K\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
