.TH "csmp::TriplePointH2O" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TriplePointH2O \- Temperature and pressure at the triple point of pure H2O\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TriplePointH2O\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBTemperature\fP () const"
.br
.ti -1c
.RI "double \fBPressure\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Temperature and pressure at the triple point of pure H2O\&. 
.SH "Member Function Documentation"
.PP 
.SS "double csmp::TriplePointH2O::Pressure () const"
Output H2O triple point pressure in [Pa] 
.SS "double csmp::TriplePointH2O::Temperature () const"
Output H2O triple point temperature in [C] 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
