.TH "csmp::InputDataManager< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::InputDataManager< dim > \- input of parameter values from block-structured text file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <InputDataManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHelp\fP () const"
.br
.RI "writes configuration options to screen "
.ti -1c
.RI "bool \fBConfigureFromFile\fP (\fBModel\fP< dim > &, const char *fname)"
.br
.RI "reads data for blocks 1-5, assigning them to box-shaped models "
.ti -1c
.RI "bool \fBConfigureFromFile\fP (\fBModel\fP< dim > &, const char *fname, bool block1, bool block2, bool block3, bool block4, bool block5, bool block6, \fBComputationalSettings\fP &settings)"
.br
.RI "key generic configuration method for time-dependent models that can contain \fBBoundary\fP objects "
.ti -1c
.RI "bool \fBConfigureFromSpecificFile\fP (\fBModel\fP< dim > &, const char *configuration_fname, bool block1, bool block2, bool block3, bool block4, bool block5, bool block6, \fBComputationalSettings\fP &settings)"
.br
.RI "customized configuration of CSMP models including a particular configuration file "
.ti -1c
.RI "bool \fBConfigureFromFile\fP (\fBModel\fP< dim > &, const char *fname, bool block1, bool block2, bool block3, bool block4, bool block5, bool block6=false)"
.br
.RI "as above but without runtime information "
.ti -1c
.RI "bool \fBConfigureRegionsFromFile\fP (\fBModel\fP< dim > &, const char *fname, std::set< std::string > &regions)"
.br
.RI "configuration restricted to unique regions in the input model "
.ti -1c
.RI "bool \fBConfigureFRED_ModelFromFile\fP (\fBModel\fP< dim > &, const char *fname, std::map< std::string, std::vector< double > > &well_data, \fBComputationalSettings\fP &settings)"
.br
.RI "FRED was a FRACMAN consortium of Golder Associates, this interface is used in the Fracman GUI\&. "
.ti -1c
.RI "bool \fBConfigure_ANSYS_ModelFromFile\fP (\fBModel\fP< dim > &, const char *fname)"
.br
.RI "configures box-shaped ANSYS models output using ANSYS' csmp input interface "
.ti -1c
.RI "bool \fBConfigureIrregular_ANSYS_ModelFromFile\fP (\fBModel\fP< dim > &, const char *fname)"
.br
.RI "configures arbitrarily shaped ANSYS models output to CSMP, recognising boundaries if their name contains BOUNDARY "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::InputDataManager< dim >"input of parameter values from block-structured text file\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
S\&. Geiger 

.PP
S\&.G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
2001
.RE
.PP
.SH "Motivation"
.PP
To have an ASCII-file based interface to CSMP which allows to assign material properties and initial conditions to models and their subregions as identified by unique names (of groups)\&. 
.br

.PP
\fBBoundary\fP and essential conditions should also be assignable via condition flags and this approach needs to work in 1-3D and both for box- and for freeform models\&. 
.br

.PP
Since many meshing tools do not allow to assign names to subregions of models / meshes, but subregions and model internal and external boundaries are identified by integer or floating point (material property) values, this interface should also provide the possibility to create named model subregions from property values and ranges\&. The only possible properties for this purpose inside of CSMP are element properties\&. This is because each subregion must at least consist of one finite element\&.
.SH "Design Intent"
.PP
A simple design is achieved by dividing the input data into five different data blocks\&. The user decides which blocks to read, by setting boolean flag arguments to \fBConfigureFromFile()\fP:

.PP
Block 1 - to define named regions of elements with characteristic values of element properties\&. 
.br

.PP
Block 2 - to set default property values for the entire model\&. These can get overwritten in individual subregions by the values and flags supplied in the data blocks 3-5\&.

.PP
Block 3 - property values for model subregions\&. The user can determine whether these values are applied to the entire subregion (option=COMPLETE), its boundary (option=PERIMETER), or only the interior of the region (option=INTERIOR)\&. The CSMP user's guide explains how these parts of a region are defined and how \fBRegion\fP objects work in general\&. The perimeter elements of regions are only those which have at least one of their faces on the region boundary\&.

.PP
\fBAttention\fP
.RS 4
Since perimeter nodes are shared between adjacent regions the last value assignment instruction will determine the values that the target variables at these boundary nodes will have after initialisation is complete\&. This is not the case for other property placements\&.
.RE
.PP
Block 4 - (box-shaped models only): assigns boundary conditions using the boundary identifiers defined by the enumeration \fBBOX_BOUNDARY\fP in '\fBBox\&.h\fP'\&. Box-shaped models offer a few extra configuration possibilities\&. For instance, linear boundary property variations can be assigned, which is not possible for free-form models for which only uniform boundary values can be assigned\&. For the latter, computations performed on the boundaries can achieve this goal\&.

.PP
Block 5 - Essential conditions that are assigned by setting property condition flags for specifc regions\&. Again the discriminators 'complete, interior, perimeter' can be used\&. To assign boundary condition values to irregular models, one first sets the desired property value in the target region and then assigns the intended condition flag to it, i\&.e\&. DIRICH or NEUMANN etc\&. in Block 5\&.

.PP
Any of the data blocks are started and terminated by an empty line\&. 
.br

.PP
Apart from the block-structured approach to the configuration file the \fBInputDataManager\fP provides several methods to initialize models created with specific meshing tools, such as Shewchuk's triangle mesher and ICEM's suite of meshing tools\&.

.PP
Computational Settings - is an additional block that can be appended, allowing the user to define the time stepping strategy, duration and times when simulation results shall be output to file\&.

.PP
Again, a blank line indicates the end of this block and users can write any comments, references, and observations made on models as kind of a documentation, following the configuration\&.
.SH "Applicability"
.PP
The \fBInputDataManager\fP can be used to configure any CSMP model, but its functionality is restricted to that of public interfaces of the \fBModel\fP\&.
.SH "Participants"
.PP
The data input manager requires a \fBModel\fP to act on- and interacts with the \fBComputationalSettings\fP object that is used to store runtime information\&.
.SH "Consequences"
.PP
The decision that CSMP variable names may contain white space forced us to restrict the use of token (string item) separators to the tab keys\&. Thus every item in any configuration line must be separated by a tab key and any other white space must be avoided (also at the end of lines)\&. Comments can be inserted anywhere into configuration files\&. To write a comment, start the line with a # sign\&.

.PP
The data input manager allows the user to configure CSMP models without the need for compilation of a program\&.
.SH "Application Examples"
.PP
An example configuration file as would be used to configure a model created with the Triangle mesher and including comments is shown in the following (the CSMP \fBExample\fP suite contains many others):

.PP
.PP
.nf
'mymodel\-configuration\&.txt' file created X/X/X \- this is its title
.fi
.PP

.PP
blank line (thereafter region identifications in terms of their permeability and in alphabetical order)

.PP
.PP
.nf
# Block 1: creating a region called joint containing all finite elements whose
# permeability ranges between 1\&.0e\-8 and 1\&.0e\-8 m2\&.
joint               tab     permeability    tab     1\&.0e\-8 1\&.0e\-8
left fault zone     tab     permeability    tab     1\&.0e\-12 1\&.0e\-11
.fi
.PP

.PP
blank line (thereafter default properties and initial conditions assigned to whole model)

.PP
.PP
.nf
# Block 2: default properties for the entire model
permeability    tab   1\&.0e\-13
storativity     tab   1\&.0e\-9
.fi
.PP

.PP
blank line (thereafter region descriptions and assigned properties) discriminators here are: 'complete', 'interior', or 'boundary'

.PP
.PP
.nf
# Block 3: specific properties of certain model subregions
left fault zone     tab     interior        tab     porosity    tab   0\&.25
left fault zone     tab     boundary        tab     porosity    tab   0\&.25
.fi
.PP

.PP
blank line (thereafter essential conditions, 'TOP' or 'top' will both work, so will 'Dirichlet' or 'DIRICH', or 'DIRICHLET')\&. Conditions only apply to boundaries flagged using the mechanism for box-shaped models

.PP
.PP
.nf
# Block 4: Dirichlet boundary conditions assigned to box\-shaped models via BOX_BOUNDARY flags
top     tab     Dirichlet   tab     fluid pressure      tab     1\&.0 1\&.0 4\&.3 4\&.7
bottom  tab     Dirichlet   tab     fluid pressure      tab     1\&.0 1\&.0 1\&.0 1\&.0
bottom  tab     Dirichlet   tab     displacement        tab     1\&.0 1\&.0 1\&.0 1\&.0 1\&.0 1\&.0 1\&.0 1\&.0 DIRICH PLAIN
# (here the model will know whether to read either 2(2D) or 4(3D) values
.fi
.PP

.PP
blank line (thereafter regional condition flags: 'Dirichlet' or 'Neumann')

.PP
.PP
.nf
# Block 5: essential conditions assigned to regions
well    tab     interior    tab     fluid pressure  tab     Dirichlet
.fi
.PP

.PP
blank line (thereafter boundary condition flags for free-form boundaries)

.PP
.PP
.nf
# Block 6: boundary conditions applied to CSMP Boundary objects (that can have arbitrary shape)
# Boundary name       part of       flag           variable name      uniform value on boundary
BOUNDARY_TOP     tab  complete tab  Dirichlet  tab fluid pressure tab 16495146\&.
.fi
.PP

.PP
The configuration file could be read configuring a \fBModel\fP object either with the specific method: 
.br

.PP
.PP
.nf
bool ConfigureFromFile( Model<dim>& sg, const char* fname );
.fi
.PP

.PP
Or with the generic method, but the specific settings:

.PP
.PP
.nf
bool ConfigureFromFile( Model<dim>& sg, const char* fname,
                        bool block1, 
                        bool block2,
                        bool block3,
                        bool block4,
                        bool block5,
                        bool block6 );
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> bool \fBcsmp::InputDataManager\fP< dim >::Configure_ANSYS_ModelFromFile (\fBModel\fP< dim > & model, const char * fname)"

.PP
configures box-shaped ANSYS models output using ANSYS' csmp input interface The method is similar to \fBConfigureFromFile()\fP, version 1, but should be applied only to box-shaped models which already contain the target regions\&.

.PP
These are the characteristics of models generated through the \fBANSYS_Interface\fP object\&.

.PP
Reading is restricted to blocks 2 to 4\&.
.SH "Input Arguments"
.PP
The method takes a reference to the model which shall be initialized with the input data and the name of the file from which the data shall be read\&. The file name has to be specified without extension\&. The model will automatically append '-configuration\&.txt' to it\&.

.PP
\fBReturns\fP
.RS 4
The data will be assigned to the input \fBModel\fP object\&.
.RE
.PP
.SH "Implementation"
.PP
\fBBoundary\fP conditions can only be assigned to scalar and vector variables, see the documentation of ReadPropertyValue() to learn how CSMP variable values are specified in the input\&.

.PP
\fBAttention\fP
.RS 4
The internal settings that determine which input file blocks are read are as follows:
.RE
.PP
.PP
.nf
bool region_specifications      ( false );  // regionname from parameter range
bool default_property_values    ( true  );  // default property values
bool region_property_values     ( true  );  // regional property values
bool box_boundary_conditions    ( true  );  // boundary conditions for box\-shaped model
bool region_property_conditions ( true  );  // essential conditions for regions
bool boundary_conditions        ( false );  // boundary conditions for arbitrary\-shaped model
bool well_settings              ( false );  // well names, locations, rates, ratios
bool computational_settings     ( false );  // computational settings
.fi
.PP
.SH "Application Examples"
.PP
Use this method to configure models for which the meshes were created with the ANSYS suite of simulation tools\&.
.SH "Messages"
.PP
The reading process is verbose\&. The method keeps the user informed about the progress and assigned property values are echoed to screen\&. 
.SS "template<uint32_t dim> bool \fBcsmp::InputDataManager\fP< dim >::ConfigureFRED_ModelFromFile (\fBModel\fP< dim > & , const char * fname, std::map< std::string, std::vector< double > > & well_data, \fBComputationalSettings\fP & settings)"

.PP
FRED was a FRACMAN consortium of Golder Associates, this interface is used in the Fracman GUI\&. The agreed file structure for FRED-based CSMP models combines the assigment of material properties with that of boundary conditions and computational settings such as the run duration, time-stepping strategy, and output times\&.
.SH "Input Arguments"
.PP
The method takes a reference to the model that will be configured and the name of the input file to which the extension '-FRED-input\&.txt' will be appended\&.

.PP
\fBReturns\fP
.RS 4
The method returns node point locations which represent the intersection of lines representing wells with fracture surfaces\&. The last method argument is the object into which the computational settings will be stored\&.
.RE
.PP
.SH "Application Examples"
.PP
A typical FRED input file may look as follows:

.PP
.PP
.nf
'eight_binary\-FRED\-input\&.txt' simple model generated by SKM 10/7/2003

# (1) global material properties
porosity                                1\&.0
nodal fluid volume source               0\&.0
fluid volume source                     0\&.0
density oil                             1000\&.0
density water                           1000\&.0
viscosity oil                           1\&.0e\-3
viscosity water                         1\&.0e\-3
saturation oil                          0\&.95
saturation water                        0\&.05
residual saturation wetting phase       0\&.03
residual saturation non\-wetting phase   0\&.14
# relative permeability model options: 1\&.=linear, 2\&.=Brooks\-Corey, 3\&.=van\-Genuchten
relative permeability model             2\&.0
# relative\-permeability model parameters
brooks corey parameter                  2\&.0
van genuchten parameter                 4\&.37
entry pressure                          1\&.0e+1

# (2) local material properties (of the fractures)
FRACTURE    complete    aperture        3\&.0e\-3
FRACTURE    complete    compressibility 1\&.0e\-7

# (3) well intersections (well name, intersection point (x,y,z),
#    injection rate (m^3 s\-1), saturation oil)
WELL1   20\&.0508 0\&.  21\&.3699     1\&.1574e\-4   0\&.
WELL2   87\&.8615 0\&.  23\&.359      \-1\&.1574e\-4  0\&.

# (4) computational settings
time stepping   pedantic
duration        86400\&.
output time     10000\&.
output time     43200\&.
.fi
.PP
.SH "Messages"
.PP
The assignment process is verbose\&. The progress of the reading process is echoed to screen so that the last line which appears before a problem is reported contains the offending characters\&. 
.SS "template<uint32_t dim> bool \fBcsmp::InputDataManager\fP< dim >::ConfigureFromFile (\fBModel\fP< dim > & model, const char * fname)"

.PP
reads data for blocks 1-5, assigning them to box-shaped models Reads the input data blocks 1-5 (see class documentation) from the user specified '*-configuaration\&.txt' input file\&. The method gives the user the possibility to generate regions of elements with certain variable data range and to assign values and essential conditions to them\&.
.SH "Input Arguments"
.PP
The method takes a reference to the model which shall be initialized with the input data and the name of the file from which the data shall be read\&. The file name has to be specified without extension\&. The model will automatically append '-configuration\&.txt' to it\&.

.PP
\fBReturns\fP
.RS 4
The data will be assigned to the input \fBModel\fP object\&.
.RE
.PP
.SH "Implementation"
.PP
\fBBoundary\fP conditions can only be assigned to scalar and vector variables, see the documentation of ReadPropertyValue() to learn how CSP variable values are specified in the input\&.
.SH "Application Examples"
.PP
Because the method attempts to assign essential conditions to model boundaries identified by the enumeration \fBBOX_BOUNDARY\fP, it should only be for rectangular or box-shaped models which may however contain boundaries that are flagged as IRREGULAR as well\&. This is the case for box-shaped models with a top surface that represents a topography\&.
.SH "Messages"
.PP
The reading process is verbose\&. The title of the input file and potential parsing errors are reported\&. 
.SS "template<uint32_t dim> bool \fBcsmp::InputDataManager\fP< dim >::ConfigureFromFile (\fBModel\fP< dim > & model, const char * fname, bool region_specifications, bool default_property_values, bool region_property_values, bool box_boundary_conditions, bool region_property_conditions, bool boundary_conditions, \fBComputationalSettings\fP & settings)"

.PP
key generic configuration method for time-dependent models that can contain \fBBoundary\fP objects Allows for the costumized configuration of CSMP models including \fBcsmp::Boundary\fP
.SH "Input Arguments"
.PP
The method takes a reference to model which shall be initialized with the property values from the input file and the name of the file without the extension '-configuration\&.txt' which will be appended to the file name automatically\&.

.PP
The boolean variables block1 to block5 enable the user to costumize the reading process\&. Thus, the desired data blocks can be switched on with their boolean variable values set to true\&. The role of the different input blocks is to read and create:

.PP
.PP
.nf
block1 \- regionname from parameter range\&.
block2 \- assign default property values\&.
block3 \- assign regional property values (i\&.e\&. values to existing regions),
block4 \- assign standard boundary conditions to box\-shaped model\&.
block5 \- assign essential conditions via VARIABLE_FLAG flags to regions\&.
block6 \- assign properties incl flag to csmp::Boundary objects
.fi
.PP

.PP
\fBReturns\fP
.RS 4
The property values and flags are assigned to the model specified by the first method argument\&.
.RE
.PP
The methood also initializes a \fBComputationalSettings\fP object which allows the user to specify the duration of the run, the time stepping strategy, and the output times\&.
.SH "Messages"
.PP
The method is verbose\&. Errors and monitors on the reading process are reported to stdout\&.

.PP
\fBParameters\fP
.RS 4
\fImodel\fP The \fBcsmp::Model\fP to set up 
.br
\fIfname\fP The file name (extension '-configuration\&.txt' appended automatically) 
.br
\fIregion_specifications\fP block1 \fBRegion\fP from parameter range 
.br
\fIdefault_property_values\fP block2 Default property values 
.br
\fIregion_property_values\fP block3 \fBRegion\fP property values 
.br
\fIbox_boundary_conditions\fP block4 \fBBoundary\fP conditions for box-shaped model 
.br
\fIregion_property_conditions\fP block5 Essential conditions for Regions 
.br
\fIboundary_conditions\fP block6 Properties & Essential conditions for \fBBoundary\fP 
.br
\fIsettings\fP Computational settings 
.RE
.PP

.PP
\fBParameters\fP
.RS 4
\fIregion_specifications\fP region name from parameter range  
.br
\fIdefault_property_values\fP default property values  
.br
\fIregion_property_values\fP regional property values  
.br
\fIbox_boundary_conditions\fP boundary conditions for box-shaped model  
.br
\fIregion_property_conditions\fP essential conditions for regions  
.br
\fIboundary_conditions\fP boundary conditions for arbitrary-shaped model 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::InputDataManager\fP< dim >::ConfigureFromFile (\fBModel\fP< dim > & model, const char * fname, bool region_specifications, bool default_property_values, bool region_property_values, bool box_boundary_conditions, bool region_property_conditions, bool boundary_conditions = \fRfalse\fP)"

.PP
as above but without runtime information boundary conditions for arbitrary-shaped model

.PP
Allows for configuration of CSMP models\&.
.SH "Input Arguments"
.PP
The method takes a reference to model which shall be initialized with the property values from the input file and the name of the file without the extension '-configuration\&.txt' which will be appended to the file name automatically\&.

.PP
The boolean variables block1 to block5 enable the user to costumize the reading process\&. Thus, the desired data blocks can be switched on with their boolean variable values set to true\&. The role of the different input blocks is to read and create:

.PP
.PP
.nf
block1 \- regionname from parameter range\&.
block2 \- assign default property values\&.
block3 \- assign regional property values (i\&.e\&. values to existing regions),
block4 \- ONLY for box\-shaped models: assign boundary conditions to LEFT, RIGHT etc\&.
block5 \- assign essential conditions via VARIABLE_FLAG flags to regions\&.
block6 \- properties / conditions assigned to CSMP Boundary objects
.fi
.PP

.PP
\fBReturns\fP
.RS 4
The property values and flags are assigned to the model specified by the first method argument\&.
.RE
.PP
.SH "Messages"
.PP
The method is verbose\&. Errors and monitors on the reading process are reported to stdout\&. 
.PP
\fBParameters\fP
.RS 4
\fIregion_specifications\fP region name from parameter range  
.br
\fIdefault_property_values\fP default property values  
.br
\fIregion_property_values\fP regional property values  
.br
\fIbox_boundary_conditions\fP boundary conditions for box-shaped model  
.br
\fIregion_property_conditions\fP essential conditions for regions 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::InputDataManager\fP< dim >::ConfigureFromSpecificFile (\fBModel\fP< dim > & model, const char * configuration_fname, bool region_specifications, bool default_property_values, bool region_property_values, bool box_boundary_conditions, bool region_property_conditions, bool boundary_conditions, \fBComputationalSettings\fP & settings)"

.PP
customized configuration of CSMP models including a particular configuration file Allows for the costumized configuration of CSMP models including a particualr configuration file Here we do not use the extension '-configuration\&.txt' which will be appended to the model name automatically\&. 
.PP
\fBParameters\fP
.RS 4
\fIregion_specifications\fP region name from parameter range  
.br
\fIdefault_property_values\fP default property values  
.br
\fIregion_property_values\fP regional property values  
.br
\fIbox_boundary_conditions\fP boundary conditions for box-shaped model  
.br
\fIregion_property_conditions\fP essential conditions for regions  
.br
\fIboundary_conditions\fP boundary conditions for arbitrary-shaped model 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::InputDataManager\fP< dim >::ConfigureIrregular_ANSYS_ModelFromFile (\fBModel\fP< dim > & model, const char * fname)"

.PP
configures arbitrarily shaped ANSYS models output to CSMP, recognising boundaries if their name contains BOUNDARY The method is similar to \fBConfigureFromFile()\fP, version 1, but should be applied only to freeform models which already contain the target regions\&.

.PP
These are the characteristics of models generated through the \fBANSYS_Interface\fP object\&.

.PP
Reading is restricted to blocks 2 to 4\&.
.SH "Input Arguments"
.PP
The method takes a reference to the model which shall be initialized with the input data and the name of the file from which the data shall be read\&. The file name has to be specified without extension\&. The model will automatically append '-configuration\&.txt' to it\&.

.PP
\fBReturns\fP
.RS 4
The data will be assigned to the input \fBModel\fP object\&.
.RE
.PP
.SH "Implementation"
.PP
The method is essentially the same as the previous one but for freeform ANSYS models for which boundary conditions can be assigned only to regions\&.

.PP
\fBBoundary\fP conditions can only be assigned to scalar and vector variables, see the documentation of ReadPropertyValue() to learn how CSMP variable values are specified in the input\&.
.SH "Application Examples"
.PP
Use this method to configure models for which the meshes were created with the ANSYS suite of simulation tools\&.
.SH "Messages"
.PP
The reading process is verbose\&. The method keeps the user informed about the progress and assigned property values are echoed to screen\&. 
.SS "template<uint32_t dim> bool \fBcsmp::InputDataManager\fP< dim >::ConfigureRegionsFromFile (\fBModel\fP< dim > & , const char * fname, std::set< std::string > & regions)"

.PP
configuration restricted to unique regions in the input model The method reads the data block3 (see description of the class below), assigning material property values and initial conditions to the set of regions specified in the file\&. The names of these are inserted into a supplied set container class\&.
.SH "Input Arguments"
.PP
The method takes a reference to the model to which the region properties shall be applied, an empty set that will contain the region names and the file name to which the extension '-configuration\&.txt' is appended automatically before the file is opened\&.

.PP
\fBReturns\fP
.RS 4
The method returns true if the assigment process was successful\&.
.RE
.PP
.SH "Messages"
.PP
The reading process is verbose, potential errors are reported to screen\&. 
.SS "template<uint32_t dim> void \fBcsmp::InputDataManager\fP< dim >::Help () const"

.PP
writes configuration options to screen Constructs the data input manager\&.
.SH "Messages"
.PP
The method reports on the requirements that the input must meet to be parsed correctly\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
