.TH "csmp::Boundary< dim >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Boundary< dim > \- A \fBBoundary\fP is lower-dimensional \fBModelSubDomain\fP, consisting of \fBFace\fP objects\&. Consisting of Faces endows the boundary with special functionality such as access to higer-dimensional elements on either side and a distinct treatment in the accumulation of PDE operators such as surface integrals for a domain\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Boundary\&.h>\fP
.PP
Inherits \fBcsmp::ModelSubDomain< dim, Face >\fP, and \fBcsmp::LocalVariableStorage< dim, Boundary >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoundary\fP ()=delete"
.br
.RI "there is no sensible default contruction "
.ti -1c
.RI "\fBBoundary\fP (const std::string &boundary_name, const \fBPropertyDatabase\fP< dim > &, typename std::vector< \fBFace\fP< dim > * >::iterator facesBegin, typename std::vector< \fBFace\fP< dim > * >::iterator facesEnd, \fBBOX_BOUNDARY\fP)"
.br
.RI "constructor: creating boundary from supplied vector of faces "
.ti -1c
.RI "\fBBoundary\fP (std::string boundaryname, const \fBPropertyDatabase\fP< dim > &, \fBBOX_BOUNDARY\fP flag)"
.br
.RI "create empty boundary with appropriately resized property storage "
.ti -1c
.RI "\fBBoundary\fP (const \fBBoundary\fP &)"
.br
.RI "copy constructor "
.ti -1c
.RI "\fBBoundary\fP (\fBBoundary\fP &&)"
.br
.RI "move constructor "
.ti -1c
.RI "virtual \fB~Boundary\fP ()"
.br
.RI "gets \fBMeshManager\fP to delete the boundary including Faces "
.ti -1c
.RI "\fBBoundary\fP< dim > & \fBoperator=\fP (const \fBBoundary\fP &)"
.br
.ti -1c
.RI "virtual \fBPLACEMENT\fP \fBPlacement\fP () const override"
.br
.RI "methods required for the \fBLocalVariableStorage\fP "
.ti -1c
.RI "virtual bool \fBValidVariable\fP (const char *variableName) const override"
.br
.ti -1c
.RI "\fBBoundary\fP (const \fBPropertyDatabase\fP< dim > &, \fBMeshManager\fP< dim > &, const \fBSubDomainInfo\fP &, \fBBOX_BOUNDARY\fP=\fBIRREGULAR\fP)"
.br
.RI "RECONSTRUCTOR of boundary from index data stored in \fBSubDomainInfo\fP (call only prior to deleting anythin from colonies) "
.ti -1c
.RI "virtual void \fBAccept\fP (\fBVisitor\fP< dim > &) override"
.br
.RI "Visitors\&. "
.ti -1c
.RI "template<typename Var> void \fBInputPropertyValue\fP (const char *input_prop, const Var &new_value, \fBSUBDOMAIN_PART\fP sd=COMPLETE)"
.br
.RI "for the assignment of properties that are unique to the instance of this subclass "
.ti -1c
.RI "template<typename Var> void \fBInputPropertyValue\fP (const char *input_prop, const Var &new_value, \fBVARIABLE_FLAG\fP do_not_overwrite, \fBSUBDOMAIN_PART\fP sd=COMPLETE)"
.br
.RI "as InputPropertyValue, but with overwrite protection for variable components that have the flag 'do_not_overwrite' "
.ti -1c
.RI "template<class Var> void \fBInputVariableFrom\fP (const char *property, const \fBFEM_Data\fP< Var > &)"
.br
.RI "assigning the variable values from the FEM_DATA container to the corresponding property of the \fBBoundary\fP "
.ti -1c
.RI "template<class Var> void \fBOutputVariableTo\fP (const char *property, \fBFEM_Data\fP< Var > &) const"
.br
.ti -1c
.RI "size_t \fBAccumulateByNumber\fP (\fBMeshManager\fP< dim > &, std::vector< size_t > &cell_ids)"
.br
.RI "creates pointers to existing \fBFace\fP objects assuming that these have consecutive ID numbers starting with that of the last \fBElement\fP object "
.ti -1c
.RI "bool \fBCreateFrom\fP (const typename std::vector< \fBFace\fP< dim > * >::const_iterator facesBegin, const typename std::vector< \fBFace\fP< dim > * >::const_iterator facesEnd)"
.br
.RI "creating from supplied vector of faces "
.ti -1c
.RI "bool \fBCreateFrom\fP (\fBRegion\fP< dim > &lower_dimensional_region, \fBMeshManager\fP< dim > &meshManager, \fBBOX_BOUNDARY\fP boxBoundary)"
.br
.RI "create faces from lower dimensional region, deleting these and assigning nullptr values "
.ti -1c
.RI "double \fBLength\fP () const"
.br
.RI "in case the boundary consists of line segments "
.ti -1c
.RI "double \fBArea\fP () const"
.br
.RI "surface area of the boundary "
.ti -1c
.RI "double \fBPerimeter\fP () const"
.br
.RI "length of the boundary perimeter in 3D, else NaN "
.ti -1c
.RI "double \fBSurfaceIntegral\fP (const \fBPropertyDatabase\fP< dim > &, const char *property) const"
.br
.RI "surface integral over the variable of interest "
.ti -1c
.RI "bool \fBIsExternal\fP () const"
.br
.RI "reports whether the boundary lies on the outside of the whole model "
.ti -1c
.RI "void \fBAtBoundary\fP (\fBBOX_BOUNDARY\fP boxBoundary)"
.br
.RI "application of single-value \fBBox\fP boundary flagging "
.ti -1c
.RI "\fBBOX_BOUNDARY\fP \fBAtBoundary\fP () const"
.br
.RI "reports the flagging of the boundary with respect to \fBcsmp::Box\fP boundary convention "
.ti -1c
.RI "std::pair< int32_t, int32_t > \fBFaceSpatialDimensions\fP () const"
.br
.RI "returns 1) elements of how many different spatial dimensions are contained, and 2) the highest element spatial dimension in boundary "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.ti -1c
.RI "template<class Var> bool \fBOut\fP (fstream &fp, \fBPLACEMENT\fP place, \fBVARIABLE_TYPE\fP vtype) const"
.br
.ti -1c
.RI "template<class Var> bool \fBIn\fP (fstream &fp, \fBPLACEMENT\fP, \fBVARIABLE_TYPE\fP)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::ModelSubDomain< dim, Face >\fP
.in +1c
.ti -1c
.RI "\fBModelSubDomain\fP (const std::string &subdomain_name, const \fBPropertyDatabase\fP< dim > &)"
.br
.RI "constructs incomplete subdomain for later initialisation with suitable methods in subclasses "
.ti -1c
.RI "\fBModelSubDomain\fP< dim, \fBFace\fP > & \fBoperator=\fP (const \fBModelSubDomain\fP &)"
.br
.ti -1c
.RI "std::string \fBName\fP () const"
.br
.ti -1c
.RI "void \fBApply\fP (\fBInterrelation\fP< dim > &)"
.br
.RI "modification via Operand-based relations between discretised properties that only modify a single result variable "
.ti -1c
.RI "void \fBRebuildSubDomainAfterChangeOfCellVector\fP ()"
.br
.RI "deletes nullptr cells, rebuilds node vector, sorts everything and re-establishes the perimeter face vectors after modifications of cells "
.ti -1c
.RI "void \fBRebuildSubDomainAfterChangeOfNodeVector\fP ()"
.br
.RI "rebuilds node vector, sorts everything and re-establishes interior and perimeter "
.ti -1c
.RI "void \fBUpdateCellMembershipApplyingConstraints\fP (typename std::vector< \fBFace\fP< dim > * >::const_iterator master_domain_start, typename std::vector< \fBFace\fP< dim > * >::const_iterator master_domain_end, const \fBPropertyConstraints\fP &)"
.br
.RI "rebuilds subdomain on the basis of the cells that will be selected according to the supplied property constraints "
.ti -1c
.RI "void \fBIdentifyPerimeter\fP ()"
.br
.RI "distinguishes PERIMETER simplices that have at least one face on domain boundary from INTERIOR ones; calls PartitionElementVector() "
.ti -1c
.RI "void \fBCreateNodePointerVector\fP ()"
.br
.RI "creates node pointer vector from cell vector, using a vector to achieve uniqueness via sort, unique, erase algorithms "
.ti -1c
.RI "void \fBSortVectors\fP (size_t interior_cells, size_t interior_nodes)"
.br
.RI "sorts the node and CELL vectors split into the interior and perimeter ranges (4 sorting operations) "
.ti -1c
.RI "void \fBBuildPerimeterFaceVector\fP (int64_t interior_cells)"
.br
.RI "assuming that a partitioned (and sorted) cell vector is in place, constructs the bd_face_vec_ by checking whether neighbor cells belong to the domain or not "
.ti -1c
.RI "void \fBScheduleForRebuild\fP ()"
.br
.RI "for rebuilding subdomains when nodes or cells changed: flag up for a rebuild using RebuildSubDomainAfterChangeOfCellVector "
.ti -1c
.RI "bool \fBNeedsRebuild\fP () const"
.br
.ti -1c
.RI "size_t \fBRebuildCellAndPerimeterFaceVector\fP ()"
.br
.RI "deletes 'nullptr' cells from cell vector, retaining the sorting into interior and perimeter elements, and rebuilding perimeter faces as necessary "
.ti -1c
.RI "size_t \fBRebuildNodeVector\fP ()"
.br
.RI "deletes 'nullptr' nodes from \fBNode\fP vector, retaining the sorting into interior and perimeter nodes "
.ti -1c
.RI "int32_t \fBDomainIndex\fP () const"
.br
.RI "reference counting-based unique domain identifier (0\&.\&.n-1) "
.ti -1c
.RI "size_t \fBRenumberNodes\fP () const"
.br
.RI "renumbers nodes in domain 0\&.\&.n-1 "
.ti -1c
.RI "size_t \fBRenumberCells\fP () const"
.br
.RI "renumbers cells in domain 0\&.\&.n-1 "
.ti -1c
.RI "void \fBUpdateMemberIndexes\fP () const"
.br
.RI "renumber cells and nodes consecutively from 0\&.\&.n-1 "
.ti -1c
.RI "std::vector< size_t > \fBMemberCellIndexes\fP () const"
.br
.RI "output current indices to vector "
.ti -1c
.RI "const std::vector< \fBFace\fP< dim > * > & \fBCellVector\fP () const"
.br
.RI "reference to container of finite cell pointers to either \fBElement\fP, \fBFace\fP or \fBInterFace\fP objects; "
.ti -1c
.RI "const std::vector< \fBNode\fP< dim > * > & \fBNodeVector\fP () const"
.br
.RI "reference to const \fBNode\fP pointer vector "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBNodesBegin\fP () const"
.br
.RI "const iterators (cell and node pointers cannot be modified but the nodes and cells can!) "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBPerimeterNodesBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBNodesEnd\fP () const"
.br
.ti -1c
.RI "std::vector< \fBFace\fP< dim > * >::const_iterator \fBCellsBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBFace\fP< dim > * >::const_iterator \fBPerimeterCellsBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBFace\fP< dim > * >::const_iterator \fBCellsEnd\fP () const"
.br
.ti -1c
.RI "size_t \fBSharedPerimeterNodes\fP (typename std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator start, typename std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator end) const"
.br
.RI "returns how many of the nodes in the supplied iterator range also form part of the current subdomain's perimeter "
.ti -1c
.RI "bool \fBEmpty\fP () const"
.br
.RI "check whether subdomain conatains any cells "
.ti -1c
.RI "size_t \fBNodes\fP () const"
.br
.ti -1c
.RI "size_t \fBInteriorNodes\fP () const"
.br
.ti -1c
.RI "size_t \fBPerimeterNodes\fP () const"
.br
.ti -1c
.RI "size_t \fBIntegrationPoints\fP () const"
.br
.ti -1c
.RI "size_t \fBSectorIntegrationPoints\fP () const"
.br
.ti -1c
.RI "size_t \fBFacetIntegrationPoints\fP () const"
.br
.ti -1c
.RI "size_t \fBCells\fP () const"
.br
.ti -1c
.RI "size_t \fBInteriorCells\fP () const"
.br
.ti -1c
.RI "size_t \fBPerimeterCells\fP () const"
.br
.ti -1c
.RI "bool \fBContains\fP (const \fBFace\fP< dim > *const) const"
.br
.ti -1c
.RI "bool \fBIsPerimeterNode\fP (const \fBcsmp::Node\fP< dim > *const) const"
.br
.ti -1c
.RI "bool \fBIsPerimeterCell\fP (const \fBFace\fP< dim > *const) const"
.br
.ti -1c
.RI "uint32_t \fBPerimeterFaces\fP (size_t eid) const"
.br
.RI "for looping over the perimeter faces of perimeter cell with #eid, method is used to travel across subdomain surface / outline "
.ti -1c
.RI "uint32_t \fBPerimeterFace\fP (size_t eid, uint32_t face) const"
.br
.RI "returns local face id of face #face that lies on perimeter of model subdomain "
.ti -1c
.RI "\fBcsmp::Node\fP< dim > * \fBN\fP (size_t n) const"
.br
.RI "pointer to node #n in subdomain; "
.ti -1c
.RI "\fBFace\fP< dim > * \fBE\fP (size_t n) const"
.br
.RI "pointer to cell #n of model subdomain "
.ti -1c
.RI "bool \fBIsContiguous\fP () const"
.br
.RI "checks whether all cells within the subdomain are interconnected (if the domain has multi-dimensional cells this is never the case) "
.ti -1c
.RI "std::pair< \fBCELL_SHAPE\fP, bool > \fBSingleCellShapeDomain\fP () const"
.br
.RI "if the model subdomain consists of a single cell shape (line, surface, volume) this method returns true revealing the type "
.ti -1c
.RI "std::pair< int32_t, int32_t > \fBSpatialDimensions\fP () const"
.br
.RI "returns 1) cells of how many different spatial dimensions are contained, and 2) the highest cell spatial dimension in subdomain "
.ti -1c
.RI "void \fBMinMaxCoordinates\fP (\fBPoint\fP< dim > &xyz_min, \fBPoint\fP< dim > &xyz_max) const"
.br
.RI "returns diagonally opposite points of bounding box "
.ti -1c
.RI "void \fBAssignNodeCoordinatesTo\fP (const char *vector_prop)"
.br
.RI "output coordinates to user-defined vector variable [x1,y1,z1,\&.\&.\&.xn,yn,zn] "
.ti -1c
.RI "void \fBAssignCellCharacteristicsTo\fP (const char *characteristic, const char *var)"
.br
.RI "characteristics like 'length', 'area', 'volume' , 'aspect ratio', 'inner radius' are assigned to user-defined variable "
.ti -1c
.RI "void \fBNodeAttributesToCSV\fP ()"
.br
.RI "writes a CSV (comma delimited ascii text) file with point coordinates, node-idx, \fBBOX_BOUNDARY\fP flags, and interior vs perimeter information "
.ti -1c
.RI "void \fBInputPropertyValue\fP (const char *input_prop, const Var &new_value, \fBSUBDOMAIN_PART\fP sd=COMPLETE)"
.br
.RI "assigns uniform (single) variable value to either the entire subdomain or its interior or perimeter "
.ti -1c
.RI "void \fBChangePropertyStatus\fP (const char *property, \fBVARIABLE_FLAG\fP new_status_of_scalar, \fBSUBDOMAIN_PART\fP=COMPLETE)"
.br
.RI "changes the flag of the scalar variable 'property' to new value; applied either in the entire subdomain or its interior or perimeter "
.ti -1c
.RI "void \fBChangePropertyStatusWhere\fP (const char *property, \fBVARIABLE_FLAG\fP new_status_of_scalar, double min_value_to_change, double max_value_to_change)"
.br
.RI "changes the flag of the scalar variable 'property' to new value if the scalar variable is withing the specified range "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBPropertyStatus\fP (const char *\fBvariable\fP, \fBSUBDOMAIN_PART\fP flag=COMPLETE, uint32_t i=0) const"
.br
.RI "by default (i=0) returns status of scalar variable or first component of a vector or tensor variable; if i>0 flag of corresponding component is returned "
.ti -1c
.RI "void \fBMinMaxOf\fP (const char *property, double &gmin, double &gmax) const"
.br
.RI "min/max property values (length of vectors and eigenvalues of tensors) "
.ti -1c
.RI "void \fBInterpolateNodeToCellProperty\fP (const char *nprop, const char *eprop)"
.br
.ti -1c
.RI "void \fBInterpolateNodeToIntegrationPointProperty\fP (const char *nprop, const char *eprop)"
.br
.ti -1c
.RI "void \fBInterpolateIntegrationPointToCellProperty\fP (const char *cprop, const char *eprop)"
.br
.ti -1c
.RI "void \fBExtrapolateCellToIntegrationPointProperty\fP (const char *eprop, const char *cprop)"
.br
.ti -1c
.RI "void \fBExtrapolateCellToFacetIntegrationPointProperty\fP (const char *eprop, const char *fipprop)"
.br
.ti -1c
.RI "void \fBExtrapolateCellToNodeProperty\fP (const char *eprop, const char *nprop, bool by_distance=true)"
.br
.ti -1c
.RI "void \fBExtrapolateIntegrationPointToNodeProperty\fP (const char *cprop, const char *nprop)"
.br
.ti -1c
.RI "double \fBAverage\fP (const char *property) const"
.br
.RI "arithmetic (number as opposed to volume weighted) average "
.ti -1c
.RI "bool \fBCopyGradientOfProperty_A_To_B\fP (const char *node_prop, const char *cell_prop)"
.br
.ti -1c
.RI "void \fBCopyReplace\fP (const char *from, const char *to)"
.br
.ti -1c
.RI "void \fBWriteDomainIndexesToBinaryFile\fP (std::fstream &) const"
.br
.RI "writes complete \fBModelSubDomain\fP specifications in terms of unique indices as block to binary file "
.ti -1c
.RI "void \fBOutputVariableToScreen\fP (const char *prop) const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::LocalVariableStorage< dim, Boundary >\fP
.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLocalVariableStorage\fP< dim, \fBBoundary\fP > &) const"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBResizePropertyStorage\fP (const \fBLocalVariables\fP &)"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBAddProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Creates an empty space in the storage preserving the original variable values\&. \fBLocalVariables\fP in \fBIndex\fP have to reflect NEW state (incl added) "
.ti -1c
.RI "void \fBDeleteProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Deletes data and flags of property \fBLocalVariables\fP in \fBIndex\fP have to reflect CURRENT state (incl property to be removed) "
.ti -1c
.RI "bool \fBIsWithinRange\fP (const \fBcsmp::Index\fP &, double, double) const"
.br
.ti -1c
.RI "double \fBRead\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar variable value\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar & Array variable flag\&. "
.ti -1c
.RI "void \fBStoreArrayEntry\fP (const \fBcsmp::Index\fP &, double array_elmt_value, int_type)"
.br
.ti -1c
.RI "double \fBReadArrayEntry\fP (const \fBcsmp::Index\fP &, int_type array_elmt) const"
.br
.RI "reads single double element inside of the target array "
.ti -1c
.RI "bool \fBEmptyLVS\fP () const"
.br
.ti -1c
.RI "void \fBOutLVS\fP () const"
.br
.ti -1c
.RI "void \fBAssertPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertFiniteVolumeIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBStoreLocalState\fP (const \fBLocalVariables\fP &lv)"
.br
.RI "We store in debug only\&. "
.ti -1c
.RI "void \fBLVS\fP (const Data &data)"
.br
.RI "copy or move supplied data into storage "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeBoundaryFlags\fP (\fBBOX_BOUNDARY\fP boxBoundary)"
.br
.RI "assigns box boundary flags to nodes unless they do not have a NOT value "
.ti -1c
.RI "\fBIntegrationPointVariables\fP \fBFaceIntegrationPointVariables\fP () const"
.br
.RI "returns local variables stored at face integration points "
.ti -1c
.RI "\fBLocalVariables\fP \fBFaceVariables\fP () const"
.br
.RI "returns local variables stored at on the boundary faces "
.ti -1c
.RI "template<class Var> bool \fBOut\fP (std::fstream &fp, \fBPLACEMENT\fP place, \fBVARIABLE_TYPE\fP vtype) const"
.br
.ti -1c
.RI "template<class Var> bool \fBIn\fP (std::fstream &fp, \fBPLACEMENT\fP place, \fBVARIABLE_TYPE\fP vtype)"
.br
.in -1c

Protected Member Functions inherited from \fBcsmp::ModelSubDomain< dim, Face >\fP
.in +1c
.ti -1c
.RI "size_t \fBPartitionCellVector\fP ()"
.br
.RI "establishes interior vs\&. exterior simplices and nodes; returns index of first boundary cell "
.ti -1c
.RI "size_t \fBPartitionCellVectorForBoundary\fP ()"
.br
.ti -1c
.RI "size_t \fBPartitionCellVectorForSplitBoundary\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBBOX_BOUNDARY\fP \fBboundaryFlag_\fP"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::ModelSubDomain< dim, Face >\fP
.in +1c
.ti -1c
.RI "const \fBPropertyDatabase\fP< dim > & \fBpref_\fP"
.br
.ti -1c
.RI "std::string \fBsubdomain_name_\fP"
.br
.RI "passed down when domain is created so that it can be referred to "
.ti -1c
.RI "std::vector< \fBFace\fP< dim > * > \fBcell_vec_\fP"
.br
.RI "doubly sorted, interior cells first "
.ti -1c
.RI "std::vector< std::vector< uint32_t > > \fBbd_face_vec_\fP"
.br
.RI "matching second sorted range of cell_vec_ "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * > \fBnode_vec_\fP"
.br
.RI "doubly sorted, interior nodes first "
.ti -1c
.RI "size_t \fBfirst_bd_node_\fP"
.br
.RI "begin of the perimeter nodes "
.ti -1c
.RI "int32_t \fBdomain_idx_\fP"
.br
.RI "created during construction from domain_count_ "
.ti -1c
.RI "bool \fBrebuilt_needed_\fP"
.br
.RI "parameter set when mesh gets modified by \fBMeshManager\fP so that update can be prompted "
.in -1c
.SS "Additional Inherited Members"


Static Protected Attributes inherited from \fBcsmp::ModelSubDomain< dim, Face >\fP
.in +1c
.ti -1c
.RI "static int32_t \fBdomain_count_\fP"
.br
.RI "reference-counting to get unique identifier for subdomains "
.ti -1c
.RI "static constexpr bool \fBverbose_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::Boundary< dim >"A \fBBoundary\fP is lower-dimensional \fBModelSubDomain\fP, consisting of \fBFace\fP objects\&. Consisting of Faces endows the boundary with special functionality such as access to higer-dimensional elements on either side and a distinct treatment in the accumulation of PDE operators such as surface integrals for a domain\&. 

Like for the \fBModel\fP or \fBRegion\fP, properties can be placed directly on them saving storage and supporting subdomain specific treatment of processes\&.

.PP
Boundaries have \fBBOX_BOUNDARY\fP flags, telling whether they are internal or external (box flags including IRREGULAR) boundaries\&. Their nodes are flagged correspondingly, which is important because it helps in the progressive construction of Boundaries to avoid accidential duplication\&.

.PP
The nodes of a boundary have the same flag as the box boundary\&. Nodes within a model are thus flagged INTERNAL unless they already have a !NOT box-boundary flag\&.

.PP
Boundaries creation and removal are managed via the \fBBoundaryInterface\fP of the \fBModel\fP class\&.

.PP
\fBNote\fP
.RS 4
Since \fBFace\fP is a separate variable placement variables placed on the element are accessible via Read, Store or Status operations\&. In practice, however, one always has access to the adjacent higher-dimensional \fBElement\fP from which element properties can be obtained, for instance, to compute 2D solutions of the governing equations on the \fBBoundary\fP\&.
.RE
.PP
.SH "Motivation"
.PP
To apply areal boundary conditions, carry out computations or monitor processes at material interfaces or model side boundaries\&.

.PP
To distinguish surface elements by turning them into \fBFace\fP objects for specific processing, and treating boundary-specific calculations separately\&.

.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
2010 

.PP
2022 major revision 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::Boundary\fP< dim >::Boundary (std::string boundaryname, const \fBPropertyDatabase\fP< dim > & pref, \fBBOX_BOUNDARY\fP flag)"

.PP
create empty boundary with appropriately resized property storage Constructor for an empty boundary (no faces yet)\&. 
.SS "template<uint32_t dim> \fBcsmp::Boundary\fP< dim >::~\fBBoundary\fP ()\fR [virtual]\fP"

.PP
gets \fBMeshManager\fP to delete the boundary including Faces Default dtor does not delete faces, even though constructed by \fBBoundary\fP\&. Need to call DeleteFaces explicitly! 
.PP
\fBTodo\fP
.RS 4
FIX THIS CONCEPTUAL MISUNDERSTANDING ALL THE WAY THROUGH: the faces are managed by the \fBMeshManager\fP 
.RE
.PP

.SS "template<uint32_t dim> \fBcsmp::Boundary\fP< dim >::Boundary (const \fBPropertyDatabase\fP< dim > & pref, \fBMeshManager\fP< dim > & mesh, const \fBSubDomainInfo\fP & info, \fBBOX_BOUNDARY\fP bflag = \fR\fBIRREGULAR\fP\fP)"

.PP
RECONSTRUCTOR of boundary from index data stored in \fBSubDomainInfo\fP (call only prior to deleting anythin from colonies) RECONSTRUCTOR of boundary from the mesh manager in the model

.PP
\fBAttention\fP
.RS 4
expects that the face numbering is unique and that all faces are numbered consecutivly\&.
.RE
.PP
\fBAuthor\fP
.RS 4
SKM 4/5/2016
.RE
.PP
\fBAttention\fP
.RS 4
assumes that the index for the first \fBFace\fP is equivalent to the number of elements in the model\&.
.RE
.PP
\fBTest\fP
.RS 4
nodes are assigned correctly, \fBFace\fP objects are not 
.RE
.PP

.PP
\fBParameters\fP
.RS 4
\fIinfo\fP contains correctly partitioned vectors and boundary faces 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::Boundary\fP< dim >::Accept (\fBVisitor\fP< dim > & v)\fR [override]\fP, \fR [virtual]\fP"

.PP
Visitors\&. Visitation of boundary, like for any visitation, the application level determines where the visitation starts and where it ends\&. 
.PP
Reimplemented from \fBcsmp::ModelSubDomain< dim, Face >\fP\&.
.SS "template<uint32_t dim> size_t \fBcsmp::Boundary\fP< dim >::AccumulateByNumber (\fBMeshManager\fP< dim > & mesh, std::vector< size_t > & cell_ids)"

.PP
creates pointers to existing \fBFace\fP objects assuming that these have consecutive ID numbers starting with that of the last \fBElement\fP object Accumulates existing \fBFace\fP objects, identified by their ID number into a new \fBBoundary\fP object\&. The \fBFace\fP ids are expected to be in the the range between n_elements and n_interfaces-1\&.

.PP
Method assumes that face numbers follow consecutively on the element numbers and before the interface numbers in the mesh\&. Thus, the first \fBFace\fP is expected to have the index 'n_elements' 
.SS "template<uint32_t dim> double \fBcsmp::Boundary\fP< dim >::Area () const"

.PP
surface area of the boundary Sums the area of surface elements in the boundary, if any\&. 
.SS "template<uint32_t dim> void \fBcsmp::Boundary\fP< dim >::AtBoundary (\fBBOX_BOUNDARY\fP boxBoundary)"

.PP
application of single-value \fBBox\fP boundary flagging adds boundary flags to boundary nodes and elements if not already flagged as box boundary entity

.PP
\fBNote\fP
.RS 4
changes BOX boundary flags for INTERIOR nodes along the boundary 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::Boundary\fP< dim >::CreateFrom (const typename std::vector< \fBFace\fP< dim > * >::const_iterator facesBegin, const typename std::vector< \fBFace\fP< dim > * >::const_iterator facesEnd)"

.PP
creating from supplied vector of faces To create \fBBoundary\fP from an existing range of \fBFace\fP objecgts\&.

.PP
\fBAttention\fP
.RS 4
the method assumes that the faces are already interconnected\&. 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::Boundary\fP< dim >::CreateFrom (\fBRegion\fP< dim > & region, \fBMeshManager\fP< dim > & meshManager, \fBBOX_BOUNDARY\fP boxBoundary)"

.PP
create faces from lower dimensional region, deleting these and assigning nullptr values Creates faces matching the elements of the supplied (lower dimensional) region\&.

.PP
\fBAuthor\fP
.RS 4
P\&. Lang - SKM refactored 2016, 2021 
.RE
.PP
\fBDate\fP
.RS 4
30/8/2011
.RE
.PP
This method requires the supplied region to be of lower dimensional representation, throws otherwise\&. Storage for both, the faces and boundary, is established\&. If a box boundary is supplied, the flag of the \fBBoundary\fP will be set accordingly; whether it actually represents a valid box boundary is not checked for\&.

.PP
When establishing face connectivity(parent elements) the convention is as outlined:

.PP
\fBAttention\fP
.RS 4
If the element is on the model boundary(attached to a single higher dimensional parent element only), the unit normal of the created face will point outward\&.

.PP
the elements of the input region are removed and this region must therefore be deleted 
.RE
.PP

.SS "template<uint32_t dim> pair< int32_t, int32_t > \fBcsmp::Boundary\fP< dim >::FaceSpatialDimensions () const"

.PP
returns 1) elements of how many different spatial dimensions are contained, and 2) the highest element spatial dimension in boundary Detects of how many spatial dimensions element types are contained in model\&. It returns a pair: first value gives number of different spatial dimensions contained, second value returns the highest spatial dimension contained\&.

.PP
\fBAuthor\fP
.RS 4
SKM 1/11/2013 
.RE
.PP

.SS "template<uint32_t dim> template<class Var> bool \fBcsmp::Boundary\fP< dim >::In (fstream & fp, \fBPLACEMENT\fP , \fBVARIABLE_TYPE\fP )"
Ins \fBFEM_Data\fP of provided variable type and placement from binary

.PP
Complimentary to Out(\&.\&.\&.) function\&.

.PP
\fBAuthor\fP
.RS 4
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
9/30/2012
.RE
.PP
\fBParameters\fP
.RS 4
\fIfp\fP If non-null, the binary file pointer
.RE
.PP
\fBReturns\fP
.RS 4
true if it succeeds, false if it fails\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::Boundary\fP< dim >::InitializeBoundaryFlags (\fBBOX_BOUNDARY\fP boxBoundary)\fR [protected]\fP"

.PP
assigns box boundary flags to nodes unless they do not have a NOT value Dispatched initialize method to establish node vector, perimeter entities, bflags and entity sorting\&.

.PP
\fBAttention\fP
.RS 4
Only assigns boundary flags if they have not already been set\&. 
.RE
.PP

.SS "template<uint32_t dim> template<typename Var> void \fBcsmp::Boundary\fP< dim >::InputPropertyValue (const char * input_prop, const Var & new_value, \fBSUBDOMAIN_PART\fP sd = \fRCOMPLETE\fP)"

.PP
for the assignment of properties that are unique to the instance of this subclass for the assignment of properties that are unique to the instance of this subclass

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
7/6/2020 
.RE
.PP

.SS "template<uint32_t dim> template<class Var> template void \fBcsmp::Boundary\fP< dim >::InputVariableFrom< \fBTensorVariable\fP< 3U > > (const char * property, const \fBFEM_Data\fP< Var > & )"

.PP
assigning the variable values from the FEM_DATA container to the corresponding property of the \fBBoundary\fP Inputs geometry and property data from an \fBFEM_Data\fP object into this group\&.

.PP
The expectation is that nodes and element numbers in the \fBVData\fP set correspond to these in the current \fBRegion\fP and that elements / nodes in the model have the same ordering as in the input dataset!
.SH "Input Arguments"
.PP
The name of the property which shall be input to \fBVSet\fP\&.
.SH "Implementation"
.PP
The current element and node indices are used to retrieve the data from from the data container\&.
.SH "Application Examples"
.PP
Enable to store data to disk to faciliate persistance\&. 
.SS "template<uint32_t dim> bool \fBcsmp::Boundary\fP< dim >::IsExternal () const"

.PP
reports whether the boundary lies on the outside of the whole model If one of the \fBFace\fP objects in the boundary has no outer higher-dim neighbor, the boundary is located on the model boundary\&.

.PP
\fBReturns\fP
.RS 4
returns true when part or all of the boundary is located on the model boundary\&. 
.RE
.PP

.SS "template<uint32_t dim> double \fBcsmp::Boundary\fP< dim >::Length () const"

.PP
in case the boundary consists of line segments Sums the length of line elements in the boundary, if any\&. 
.SS "template<uint32_t dim> template<class Var> bool \fBcsmp::Boundary\fP< dim >::Out (fstream & fp, \fBPLACEMENT\fP place, \fBVARIABLE_TYPE\fP vtype) const"
Outs \fBFEM_Data\fP of provided variable type and placement to binary

.PP
\fBAuthor\fP
.RS 4
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
9/30/2012
.RE
.PP
\fBParameters\fP
.RS 4
\fIfp\fP If non-null, the binary file pointer 
.br
\fIplace\fP The placement of variables 
.br
\fIvtype\fP The vtype of variables
.RE
.PP
\fBReturns\fP
.RS 4
true if it succeeds, false if it fails\&. 
.RE
.PP

.SS "template<uint32_t dim> template<class Var> template void \fBcsmp::Boundary\fP< dim >::OutputVariableTo< \fBTensorVariable\fP< 3U > > (const char * property, \fBFEM_Data\fP< Var > & ) const"
Outputs specific property data to a \fBFEM_Data\fP container\&. This function is a nested template: the outer template provides double = data type and dim = dimension, and Var the data type of the property (\fBScalarVariable\fP, \fBVectorVariable\fP, or \fBTensorVariable\fP)\&.

.PP
\fBParameters\fP
.RS 4
\fIproperty\fP the name of the variable from \fBPropertyDatabase\fP 
.br
\fIdata\fP The \fBFEM_Data\fP container with the data that corresponds to the given property is returned into the second method argument\&.
.RE
.PP
.SH "Implementation"
.PP
Only data pertinent to this local group is output\&. A new data container containing only group relevant data is returned\&.

.PP
Thus, the data extracted only corresponds to -this- group and is organized by local id numbers\&.
.SH "Application Examples"
.PP
The idea is to extract the property data that corresponds to this group only\&. 
.SS "template<uint32_t dim> double \fBcsmp::Boundary\fP< dim >::Perimeter () const"

.PP
length of the boundary perimeter in 3D, else NaN Returns the length of the perimeter line of the boundary\&.

.PP
\fBReturns\fP
.RS 4
returns either the length of the perimeter of the boundary or NaN if the boundary is an edge\&.
.RE
.PP
\fBAttention\fP
.RS 4
method can only be applied in 3D and only on boundaries which are not lines themselves else the perimeter is not defined\&. 
.RE
.PP

.SS "template<uint32_t dim> virtual \fBPLACEMENT\fP \fBcsmp::Boundary\fP< dim >::Placement () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
methods required for the \fBLocalVariableStorage\fP 
.PP
Implements \fBcsmp::ModelSubDomain< dim, Face >\fP\&.
.SS "template<uint32_t dim> bool \fBcsmp::Boundary\fP< dim >::ValidVariable (const char * variableName) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::ModelSubDomain< dim, Face >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
