.TH "csmp::OpeningModeFracture" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::OpeningModeFracture
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpeningModeFracture\fP (const \fBOpeningModeFracture\fP &)"
.br
.RI "copy-constructor "
.ti -1c
.RI "\fBOpeningModeFracture\fP (double length, double Poissons_ratio, double Youngs_modulus)"
.br
.ti -1c
.RI "void \fBLength\fP (double length)"
.br
.ti -1c
.RI "double \fBLength\fP () const"
.br
.ti -1c
.RI "double \fBCenterAperture\fP (double pf, double syy) const"
.br
.RI "convention syy, the fracture normal stress, is positive if compressive "
.ti -1c
.RI "double \fBAperture\fP (double pf, double syy, double cx) const"
.br
.RI "calculates fracture aperture at some distance cx (0\&.\&.length/2) from the fracture center "
.ti -1c
.RI "double \fBTransmissivity\fP (double pf, double syy, double visc) const"
.br
.RI "returns (permeability/viscosity) * aperture product "
.ti -1c
.RI "double \fBMode_I_Volume\fP (double pf, double syy) const"
.br
.RI "joint volume (assuming unit thickness) "
.ti -1c
.RI "double \fBMode_II_Volume\fP (double sxy) const"
.br
.RI "volume of a joint in shear (assuming unit thickness) "
.ti -1c
.RI "double \fBMaximumVolume\fP (double pf, double syy, double sxy) const"
.br
.RI "maximum volume in response to tensile and shear stresses "
.ti -1c
.RI "double \fBDilatation\fP (double frac_intensity, double pf, double syy, double sxy) const"
.br
.RI "dilatation of a square block of rock with fracture intensity (f/m), and dimensions = frac length^2 "
.ti -1c
.RI "void \fBSixteenPointConvexHull\fP (double pf, double syy, const \fBmjl::Point\fP &a, const \fBmjl::Point\fP &b, std::list< \fBmjl::Point\fP > &chain)"
.br
.RI "2D construction routines for fracture polygons "
.ti -1c
.RI "void \fBBluntTenPointHull\fP (double pf, double syy, const \fBmjl::Point\fP &b, const \fBmjl::Point\fP &c, std::list< \fBmjl::Point\fP > &chain)"
.br
.ti -1c
.RI "void \fBRectangleHull\fP (double pf, double syy, \fBmjl::Point\fP &b, \fBmjl::Point\fP &c, std::list< \fBmjl::Point\fP > &chain)"
.br
.ti -1c
.RI "void \fBRectangleHull\fP (double fixed_aperture, \fBmjl::Point\fP &b, \fBmjl::Point\fP &c, std::list< \fBmjl::Point\fP > &chain)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "double csmp::OpeningModeFracture::CenterAperture (double pf, double syy) const"

.PP
convention syy, the fracture normal stress, is positive if compressive normal stress is negative if tensile 
.SS "double csmp::OpeningModeFracture::Dilatation (double frac_intensity, double pf, double syy, double sxy) const"

.PP
dilatation of a square block of rock with fracture intensity (f/m), and dimensions = frac length^2 dilatation of a square block of rock with fracture intensity (f/m), and dimensions = frac length^2 
.SS "void csmp::OpeningModeFracture::Length (double len)"
NB: also setting fracture half-length a ! 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
