.TH "csmp::Node< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Node< dim > \- \fBNode\fP = lowest class of the model hierarchy\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Node\&.h>\fP
.PP
Inherits \fBcsmp::LocalVariableStorage< dim, Node >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.ti -1c
.RI "\fBNode\fP (size_t idx, const \fBPoint\fP< dim > &, const \fBLocalVariables\fP &, \fBBOX_BOUNDARY\fP=\fBNOT\fP, \fBTOPOTYPE\fP=\fBMESH_VERTEX\fP)"
.br
.RI "custom constructor used when model is reconstructed from binary file "
.ti -1c
.RI "\fBNode\fP (const \fBNode\fP< dim > &)"
.br
.ti -1c
.RI "\fBNode\fP< dim > & \fBoperator=\fP (const \fBNode\fP< dim > &)"
.br
.ti -1c
.RI "\fBNode\fP (\fBNode\fP< dim > &&)"
.br
.ti -1c
.RI "\fBNode\fP< dim > & \fBoperator=\fP (\fBNode\fP< dim > &&)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBNode\fP< dim > &)"
.br
.RI "compares memory location, idx_, BREP classifier and boundary flag "
.ti -1c
.RI "\fBPLACEMENT\fP \fBPlacement\fP () const"
.br
.RI "Local variable storage interface\&. "
.ti -1c
.RI "bool \fBUnitNormal\fP (\fBPoint\fP< dim > &unrml) const"
.br
.RI "for node forming part of line elements (2D) or surface elements (3D), method returns a unit normal that represents the average of the normals of the connected elements "
.ti -1c
.RI "\fBPoint\fP< dim > \fBVertexNormal\fP (typename std::vector< \fBNode\fP< dim > * >::const_iterator first, typename std::vector< \fBNode\fP< dim > * >::const_iterator last) const"
.br
.RI "normal to surface mesh at the \fBNode\fP as based on its connectivity with the surrounding nodes on the surface (cf\&., computer graphics) TODO: fails for quadrilateral meshes "
.ti -1c
.RI "\fBTOPOTYPE\fP \fBAttribute\fP () const"
.br
.RI "which geometric part of the discretisation of the initial boundary representation (BREP) of the model geometry the node belongs to "
.ti -1c
.RI "void \fBAttribute\fP (\fBTOPOTYPE\fP geom_feature)"
.br
.ti -1c
.RI "void \fBReserveParentStorage\fP (size_t capacity)"
.br
.RI "if it is known how many parent elements will have to be assigned this can be done more efficiently with the optional help of this "
.ti -1c
.RI "void \fBAssign\fP (uint32_t parent_elmt_node_number, \fBElement\fP< dim > *const parent_elmt)"
.br
.RI "assign new parent element where there is a NOT_INITIALISED slot in the parent element storage, else adds new one "
.ti -1c
.RI "void \fBUnassign\fP (const \fBElement\fP< dim > *const parent_elmt)"
.br
.RI "if found, sets matching parent element pointer to nullptr and the corresponding node number to NOT_INITIALIZED "
.ti -1c
.RI "void \fBEraseParents\fP ()"
.br
.RI "remove all current parent elements "
.ti -1c
.RI "uint32_t \fBParents\fP () const"
.br
.RI "returns how many elements share this node "
.ti -1c
.RI "\fBElement\fP< dim > * \fBParent\fP (uint32_t)"
.br
.RI "access to the (0\&.\&.n-1) parent element "
.ti -1c
.RI "const \fBElement\fP< dim > *const \fBParent\fP (uint32_t) const"
.br
.ti -1c
.RI "uint32_t \fBParentNodeNumber\fP (uint32_t parent_element) const"
.br
.RI "the local number of this node within the node-numbering scheme of parent element (and equal to sector number) "
.ti -1c
.RI "bool \fBIsParent\fP (const \fBElement\fP< dim > *const) const"
.br
.RI "checks whether \fBElement\fP is a parent of the node; call SortParents() first !!! "
.ti -1c
.RI "std::vector< std::pair< \fBElement\fP< dim > *, short > >::const_iterator \fBParentElementsBegin\fP () const"
.br
.ti -1c
.RI "std::vector< std::pair< \fBElement\fP< dim > *, short > >::const_iterator \fBParentElementsEnd\fP () const"
.br
.ti -1c
.RI "void \fBAssign\fP (std::set< \fBNode\fP< dim > * > &neighbor_nodes)"
.br
.RI "initialises the corner-node to neighbor corner node pointer vector "
.ti -1c
.RI "void \fBAssign\fP (std::vector< \fBNode\fP< dim > * > &neighbor_nodes, bool sort_neighbors=false)"
.br
.RI "expects a sorted vector without duplicates "
.ti -1c
.RI "void \fBCopyPropertyValuesFrom\fP (\fBNode\fP< dim > &)"
.br
.RI "copies property values from the argument node to the current node "
.ti -1c
.RI "uint32_t \fBAssignNodeNeighbors\fP ()"
.br
.RI "builds the neighbor connectivity working through higher-dimensional parent element edges that the node is part of; returns new number of neighbors "
.ti -1c
.RI "uint32_t \fBUpdateNeighbors\fP ()"
.br
.RI "removes null pointers and potential duplicates returning the resulting number of neighbors "
.ti -1c
.RI "bool \fBIsNeighbor\fP (const \fBNode\fP< dim > *const) const"
.br
.ti -1c
.RI "void \fBAddNeighbor\fP (\fBNode\fP< dim > *neighbor_node)"
.br
.ti -1c
.RI "void \fBRemoveNeighbor\fP (const \fBNode\fP< dim > *const neighbor_node)"
.br
.ti -1c
.RI "void \fBEraseNeighbors\fP ()"
.br
.RI "releases all the memory used "
.ti -1c
.RI "uint32_t \fBNeighbors\fP () const"
.br
.RI "the number of corner nodes that this node is directly connected with via segments "
.ti -1c
.RI "\fBNode\fP< dim > * \fBNeighbor\fP (uint32_t) const"
.br
.RI "access to any of the neighbor nodes "
.ti -1c
.RI "std::vector< \fBNode\fP< dim > * >::const_iterator \fBNeighborsBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBNode\fP< dim > * >::const_iterator \fBNeighborsEnd\fP () const"
.br
.ti -1c
.RI "bool \fBLinearSearch\fP (\fBNode\fP< dim > *const nptr) const"
.br
.RI "check whether a node is neighbor of this node via linear search algorithm "
.ti -1c
.RI "bool \fBBinarySearch\fP (\fBNode\fP< dim > *const nptr) const"
.br
.RI "checks whether a node is neighbor of this node ( since a sorted vector is required call \fBSortNeighbors()\fP first) "
.ti -1c
.RI "void \fBSortNeighbors\fP ()"
.br
.RI "to prepare neighbor vector for binary search "
.ti -1c
.RI "void \fBAssign\fP (\fBNodeManifold\fP< dim > &)"
.br
.RI "connects the node to other topologically collocated nodes if any "
.ti -1c
.RI "bool \fBIsManifold\fP () const"
.br
.RI "access to manifold if any; returns nullptr if the node is not a manifold "
.ti -1c
.RI "\fBNodeManifold\fP< dim > *const \fBManifold\fP () const"
.br
.RI "access to other topologically collocarted \fBNode\fP objects through manifold if any; returns nullptr if the node is not a manifold "
.ti -1c
.RI "void \fBAccept\fP (\fBcsmp::Visitor\fP< dim > &)"
.br
.RI "support of the vistor design pattern "
.ti -1c
.RI "void \fBIdx\fP (size_t id_0_to_n_minus_1) const"
.br
.RI "on-the-fly 0\&.\&.n-1 numbering stored in a mutable local variable (therefore const) "
.ti -1c
.RI "size_t \fBIdx\fP () const"
.br
.ti -1c
.RI "void \fBCoordinate\fP (const \fBPoint\fP< dim > &)"
.br
.ti -1c
.RI "\fBPoint\fP< dim > \fBCoordinate\fP () const"
.br
.ti -1c
.RI "void \fBAtBoundary\fP (\fBBOX_BOUNDARY\fP)"
.br
.RI "flagging for box-shaped models: NOT, LEFT, BOTTOM, RIGHT, TOP, BACK, FRONT etc\&. "
.ti -1c
.RI "\fBBOX_BOUNDARY\fP \fBAtBoundary\fP () const"
.br
.ti -1c
.RI "double \fBoperator[]\fP (uint32_t i) const"
.br
.RI "accessors/mutators for specific node coordinates x=0, y=1, z=2 (z exists only in 3D) "
.ti -1c
.RI "double & \fBoperator[]\fP (uint32_t i)"
.br
.ti -1c
.RI "double & \fBoperator()\fP (uint32_t i)"
.br
.ti -1c
.RI "void \fBx\fP (double)"
.br
.RI "Set or return the coordinates of the current node\&. "
.ti -1c
.RI "void \fBy\fP (double)"
.br
.ti -1c
.RI "void \fBz\fP (double)"
.br
.ti -1c
.RI "double \fBx\fP () const"
.br
.ti -1c
.RI "double \fBy\fP () const"
.br
.ti -1c
.RI "double \fBz\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "output current state of class \fBNode\fP "
.in -1c

Public Member Functions inherited from \fBcsmp::LocalVariableStorage< dim, Node >\fP
.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLocalVariableStorage\fP< dim, \fBNode\fP > &) const"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBResizePropertyStorage\fP (const \fBLocalVariables\fP &)"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBAddProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Creates an empty space in the storage preserving the original variable values\&. \fBLocalVariables\fP in \fBIndex\fP have to reflect NEW state (incl added) "
.ti -1c
.RI "void \fBDeleteProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Deletes data and flags of property \fBLocalVariables\fP in \fBIndex\fP have to reflect CURRENT state (incl property to be removed) "
.ti -1c
.RI "bool \fBIsWithinRange\fP (const \fBcsmp::Index\fP &, double, double) const"
.br
.ti -1c
.RI "double \fBRead\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar variable value\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar & Array variable flag\&. "
.ti -1c
.RI "void \fBStoreArrayEntry\fP (const \fBcsmp::Index\fP &, double array_elmt_value, int_type)"
.br
.ti -1c
.RI "double \fBReadArrayEntry\fP (const \fBcsmp::Index\fP &, int_type array_elmt) const"
.br
.RI "reads single double element inside of the target array "
.ti -1c
.RI "bool \fBEmptyLVS\fP () const"
.br
.ti -1c
.RI "void \fBOutLVS\fP () const"
.br
.ti -1c
.RI "void \fBAssertPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertFiniteVolumeIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBStoreLocalState\fP (const \fBLocalVariables\fP &lv)"
.br
.RI "We store in debug only\&. "
.ti -1c
.RI "void \fBLVS\fP (const Data &data)"
.br
.RI "copy or move supplied data into storage "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<uint32_t> class \fBMeshManager\fP"
.br
.RI "private because these operators are owned by the \fBMeshManager\fP "
.ti -1c
.RI "class \fBFiniteElement_TestData\fP"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &iStream, \fBFiniteElement_TestData\fP &femTestData)"
.br
.RI "PL 2010: overloaded istream operator for the \fBFiniteElement_TestData\fP class\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::Node< dim >"\fBNode\fP = lowest class of the model hierarchy\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1999
.RE
.PP
.SH "Motivation"
.PP
\fBNode\fP class in the finite element mesh hierarchy stores the coordinate of the node point and the variables associated with the node\&.
.SH "Design Intent"
.PP
Mesh vertex with coordinates and associated flags\&. 
.br
.SH "Participants"
.PP
Uses \fBPoint<>\fP template to represent the coordinate\&. 
.br
.SH "Collaborations"
.PP
Elements are registered as parents, Faces and InterFaces are not\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::Node\fP< dim >::Node ()"
default constructor

.PP
\fBNode\fP coordinate is initialised to origin (0,0,0) 
.SS "template<uint32_t dim> \fBcsmp::Node\fP< dim >::Node (size_t idx, const \fBPoint\fP< dim > & pt, const \fBLocalVariables\fP & lvs, \fBBOX_BOUNDARY\fP boundary_flag = \fR\fBNOT\fP\fP, \fBTOPOTYPE\fP topotype = \fR\fBMESH_VERTEX\fP\fP)"

.PP
custom constructor used when model is reconstructed from binary file Initialises everything except for parent element related vectors\&. 
.SS "template<uint32_t dim> \fBcsmp::Node\fP< dim >::Node (const \fBNode\fP< dim > & nd)"
Copy constructor also copies the pointer assignments (!)\&.

.PP
\fBAttention\fP
.RS 4
when copy constructing manifold nodes, make sure to add this new \fBNode\fP to it 
.RE
.PP

.SS "template<uint32_t dim> \fBcsmp::Node\fP< dim >::Node (\fBNode\fP< dim > && nd)"
Move constructor also copies the pointer assignments (!)\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::Node\fP< dim >::Assign (uint32_t pnode, \fBElement\fP< dim > *const parent_elmt)"

.PP
assign new parent element where there is a NOT_INITIALISED slot in the parent element storage, else adds new one Assigns parent element pointer and remembers which node (local idx) of the parent element this node is\&.

.PP
\fBParameters\fP
.RS 4
\fIpnode\fP is the node number in the parent element of the assigned node\&. 
.br
\fIelement\fP is pointer to the parent element that gets assigned\&.
.RE
.PP
.SH "Input Arguments"
.PP
The local number of the parent element which is going to be assigned\&. 
.br
 The local node number of this node in the parent element\&. 
.br
 A pointer to the parent \fBElement\fP which shall be added\&. 
.SS "template<uint32_t dim> uint32_t \fBcsmp::Node\fP< dim >::AssignNodeNeighbors ()"

.PP
builds the neighbor connectivity working through higher-dimensional parent element edges that the node is part of; returns new number of neighbors Re-establishes the node neighbors of the node using the parent element connectivity\&. Since lower-dimensional elements share the nodes with the higher dimensional ones, they are ignored\&. Only corner nodes are considered in the first pass\&. Subsequently midside nodes which exist in higher-order elements are detected and their neighbors are assigned\&. 
.SS "template<uint32_t dim> void \fBcsmp::Node\fP< dim >::AtBoundary (\fBBOX_BOUNDARY\fP b)"

.PP
flagging for box-shaped models: NOT, LEFT, BOTTOM, RIGHT, TOP, BACK, FRONT etc\&. Set or return the global boundary flag of the \fBNode\fP\&. 
.SS "template<uint32_t dim> bool \fBcsmp::Node\fP< dim >::IsParent (const \fBElement\fP< dim > * const eptr) const"

.PP
checks whether \fBElement\fP is a parent of the node; call SortParents() first !!! checks whether \fBElement\fP is a parent of the node 
.SS "template<uint32_t dim> \fBNode\fP< dim > * \fBcsmp::Node\fP< dim >::Neighbor (uint32_t neighbor_node) const"

.PP
access to any of the neighbor nodes Implements node connectivity graph, giving access to all the \fBNode\fP objects that the \fBNode\fP is connected to via \fBElement\fP, \fBFace\fP or \fBInterFace\fP edges\&. \fBNode\fP neighbors are enlisted in an order that is determined by sorting the points to them (this makes the neighbor vector searchable)\&.

.PP
\fBParameters\fP
.RS 4
\fIneighbor_node\fP the nth \fBNode\fP in the sortes vector of pointers to nodes stored in the node\&.
.RE
.PP
\fBAttention\fP
.RS 4
If the node is a manifold (topologically co-located with other nodes that can be accessed looping over the branches of the manifold, then only those Nodes are neighbors who are on the same contiguous mesh patch as the \fBNode\fP, i\&.e\&., not shared with the other nodes in the manifold\&.
.RE
.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
8/10/2021 
.RE
.PP

.SS "template<uint32_t dim> uint32_t \fBcsmp::Node\fP< dim >::Neighbors () const"

.PP
the number of corner nodes that this node is directly connected with via segments If the parent elements are of the same dimension as the node, then there are exactly as many elements as are nodes\&.

.PP
\fBAttention\fP
.RS 4
calculation is costly, compute only once per node loop!
.RE
.PP
\fBTest\fP
.RS 4
correct SKM (unit test exists) 
.RE
.PP

.SS "template<uint32_t dim> \fBNode\fP< dim > & \fBcsmp::Node\fP< dim >::operator= (\fBNode\fP< dim > && nd)"
Move assignment, relying on that similar operators exist for the nodes components\&.

.PP
\fBNote\fP
.RS 4
this assumes that the supplied node is a temporary\&. 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::Node\fP< dim >::operator== (const \fBNode\fP< dim > & nd)"

.PP
compares memory location, idx_, BREP classifier and boundary flag Tries to distinguish 2 nodes from one another\&.

.PP
This comparison operator was designed specifically for the creation of particular \fBRegion\fP, \fBBoundary\fP and \fBSplitBoundary\fP objects\&. Hence, only information important for this process is taken into account, distinguishing 2 Nodes from each other\&. That must be coordinate and parent elements 
.SS "template<uint32_t dim> void \fBcsmp::Node\fP< dim >::Out () const"

.PP
output current state of class \fBNode\fP Outputs internal data of the node\&. 
.SS "template<uint32_t dim> void \fBcsmp::Node\fP< dim >::RemoveNeighbor (const \fBNode\fP< dim > *const neighbor_node)"
Moves unwanted \fBNode\fP to the end of the vector before erasing it\&. 
.PP
\fBAttention\fP
.RS 4
Use UpdateNeighbors to shrink vector to new size\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::Node\fP< dim >::Unassign (const \fBElement\fP< dim > *const element)"

.PP
if found, sets matching parent element pointer to nullptr and the corresponding node number to NOT_INITIALIZED Sets the pointer to the argument element to zero, and the corresponding node number to NOT_INITIALIZED\&.

.PP
\fBNote\fP
.RS 4
the argument element is not deleted\&. To do this use EraseNullPointerParents()\&. 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::Node\fP< dim >::UnitNormal (\fBPoint\fP< dim > & avg_nrml) const"

.PP
for node forming part of line elements (2D) or surface elements (3D), method returns a unit normal that represents the average of the normals of the connected elements If node is part of line elements (2D) or surface elements (3D), method returns a unit normal that represents the average of the normals of the connected elements\&.

.PP
\fBReturns\fP
.RS 4
false if 1) the node is not located on the inside of a patch of lower dimensional elements, 2) not properly initialised or 3) adjacent element normals are pointing in opposite directions 
.RE
.PP

.SS "template<uint32_t dim> uint32_t \fBcsmp::Node\fP< dim >::UpdateNeighbors ()"

.PP
removes null pointers and potential duplicates returning the resulting number of neighbors Sorts vector and removes duplicates and nullptrs\&. The vector is trimmed so that size matches capacity\&. 
.SS "template<uint32_t dim> \fBPoint\fP< dim > \fBcsmp::Node\fP< dim >::VertexNormal (typename std::vector< \fBNode\fP< dim > * >::const_iterator first, typename std::vector< \fBNode\fP< dim > * >::const_iterator last) const"

.PP
normal to surface mesh at the \fBNode\fP as based on its connectivity with the surrounding nodes on the surface (cf\&., computer graphics) TODO: fails for quadrilateral meshes Computes normal to \fBNode\fP from its neighbor nodes, but ignoring neighbors that are not contained with the supplied \fBNode\fP vector (as in computer graphics) Supplying this vector allows to narrow the calculation to nodes that lie on a line or surface\&.

.PP
\fBNote\fP
.RS 4
The method was created to help check the consistency of the node numbering of lower-dimensional elements representing surfaces prior to converting them into boundaries\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIfirst\fP iterator to first node in the restricted node range that shall be considered (so that a geometric element can be captured) 
.br
\fIlast\fP iterator to last node in the restricted node range that shall be considered (so that a geometric element can be captured) 
.RE
.PP
\fBReturns\fP
.RS 4
either the vertex normal or a \fBPoint\fP object initialised with signalling NaN
.RE
.PP
\fBAttention\fP
.RS 4
std::find() is used so that the supplied \fBNode\fP range does not have to be sorted (or may consist of 2 sorted ranges, like in a model subdomain)
.RE
.PP
Explanation of algorithm: for each vertex, calculate the normal of the plane formed by the two edges entering and leaving that vertex\&. More formally, given vertices 𝐯1,𝐯2,…𝐯𝑛 with counterclockwise winding, define the normal at the 𝑖th vertex as: 
.PP
.nf
 𝐧𝑖=(𝐯𝑖−𝐯𝑖−1)×(𝐯𝑖+1−𝐯𝑖)

.fi
.PP

.PP
(where the indices wrap around)\&. The algorithm is implemented using the MJL library in the discretisation/ directory

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
12/10/24 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
