.TH "csmp::EclipseFault" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::EclipseFault
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReserve\fP (size_t count)"
.br
.ti -1c
.RI "void \fBAdd\fP (uint32_t i, uint32_t j, uint32_t, \fB::csmp::CORNER_POINT_CELL_FACE_INDEX\fP face)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::pair< \fBijk\fP, \fB::csmp::CORNER_POINT_CELL_FACE_INDEX\fP > > \fBfault\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
