.TH "csmp::SourceTermRHS< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SourceTermRHS< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SourceTermRHS\&.h>\fP
.PP
Inherits \fBcsmp::VectorOperator< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourceTermRHS\fP (const \fBcsmp::INDEX\fP< SCALAR, ELEMENT > &source_variable_key, const \fBcsmp::INDEX\fP< SCALAR, NODE > &nodal_source_variable_key, const \fBcsmp::INDEX\fP< SCALAR, NODE > &transported_variable_key)"
.br
.RI "note that this source variable may be an element or a nodal one "
.ti -1c
.RI "virtual void \fBAccumulateFiniteVolume\fP (const \fBNode\fP< dim > &, std::vector< double > &rhs) const"
.br
.RI "accumulates integrated (single) values of source term onto the finite volume centered on the \fBNode\fP "
.ti -1c
.RI "virtual void \fBAccumulateStencil\fP (const \fBElement\fP< dim > &, std::vector< double > &rhs) const"
.br
.RI "accumulates distributed values of the source term on the finite volume "
.in -1c

Public Member Functions inherited from \fBcsmp::VectorOperator< dim >\fP
.in +1c
.ti -1c
.RI "void \fBMultiplyWithTimeIncrement\fP (double dt)"
.br
.RI "includes the time increment in the multiplication factor for this operator "
.ti -1c
.RI "void \fBFactor\fP (double value)"
.br
.RI "set factor to achieve multiplication with time increment (fac=dt), subtraction (fac=-1), multiplication or division (fac=1/value) "
.ti -1c
.RI "double \fBFactor\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::SourceTermRHS< dim >"Either an areal/volumetric source specified on the \fBElement\fP or \fBFace\fP or a nodal (point) source term to be accumulated into the righthand vector\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::SourceTermRHS\fP< dim >::AccumulateFiniteVolume (const \fBNode\fP< dim > & n, std::vector< double > & rhs) const\fR [virtual]\fP"

.PP
accumulates integrated (single) values of source term onto the finite volume centered on the \fBNode\fP 
.PP
Implements \fBcsmp::VectorOperator< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::SourceTermRHS\fP< dim >::AccumulateStencil (const \fBElement\fP< dim > & e, std::vector< double > & rhs) const\fR [virtual]\fP"

.PP
accumulates distributed values of the source term on the finite volume 
.PP
Implements \fBcsmp::VectorOperator< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
