.TH "csmp::FiniteElementPolicy_Test" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FiniteElementPolicy_Test \- Tests the finite element functionality made available via \fBFiniteElementPolicy\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FiniteElementPolicy_Test\&.h>\fP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.RI "using 'create_Prism_Hexa_VSet' dataset, tests fem operations against provided data in text file "
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests the finite element functionality made available via \fBFiniteElementPolicy\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::FiniteElementPolicy_Test::run ()\fR [virtual]\fP"

.PP
using 'create_Prism_Hexa_VSet' dataset, tests fem operations against provided data in text file integrates a scalar property over the element and returns this value

.PP
interpolates node property values to the point of interest (in global coordinates); 
.PP
\fBAttention\fP
.RS 4
costly for isoparametric elements
.RE
.PP
returns the value of any property interpolated to the element's center of gravity

.PP
returns the value of any property interpolated to the integration point of interest

.PP
returns property values at the integration points

.PP
uses linear extrapolation of property values from the integration points to the nodes

.PP
retrieve barycenter of element face
.PP
Implements \fBcsmp::Test\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
