.TH "csmp::VLH_HaliteLookup" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::VLH_HaliteLookup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVLH_HaliteLookup\fP (const double &externaltemperature)"
.br
.ti -1c
.RI "double \fBTemperature\fP ()"
.br
.ti -1c
.RI "double \fBPressure\fP ()"
.br
.ti -1c
.RI "double \fBMassFractionNaCl\fP ()"
.br
.ti -1c
.RI "double \fBDensity\fP ()"
.br
.ti -1c
.RI "double \fBEnthalpy\fP ()"
.br
.ti -1c
.RI "double \fBHeatCapacity\fP ()"
.br
.ti -1c
.RI "double \fBCompressibility\fP ()"
.br
.ti -1c
.RI "double \fBViscosity\fP ()"
.br
.ti -1c
.RI "double \fBPmax\fP ()"
.br
.ti -1c
.RI "double \fBTmax\fP ()"
.br
.ti -1c
.RI "double \fBDEnthalpyDT\fP ()"
.br
.ti -1c
.RI "double \fBTfromP\fP (const double &press, const double &t_estimate)"
.br
.ti -1c
.RI "double \fBValueOf\fP (const int &property_index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< double > \fBproperties_at_tmax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
