.TH "csmp::IntegrationPointVariables" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::IntegrationPointVariables
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IntegrationPointVariables\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBint_type\fP = \fBLocalVariables::int_type\fP"
.br
.RI "unsigned integer type that is big enough to hold 'totalDataDepth' "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntegrationPointVariables\fP (const \fBIntegrationPointVariables\fP &ivs)"
.br
.ti -1c
.RI "\fBIntegrationPointVariables\fP (\fBint_type\fP scalarsSimplex, \fBint_type\fP vectorsSimplex, \fBint_type\fP tensorsSimplex, \fBint_type\fP arrayCountSimplex, \fBint_type\fP arrayLengthSimplex, \fBint_type\fP flaggedArrayCountSimplex, \fBint_type\fP flaggedArrayLengthSimplex, \fBint_type\fP totalDataDepthSimplex, \fBint_type\fP totalFlagDepthSimplex, \fBint_type\fP scalarsSector, \fBint_type\fP vectorsSector, \fBint_type\fP tensorsSector, \fBint_type\fP arrayCountSector, \fBint_type\fP arrayLengthSector, \fBint_type\fP flaggedArrayCountSector, \fBint_type\fP flaggedArrayLengthSector, \fBint_type\fP totalDataDepthSector, \fBint_type\fP totalFlagDepthSector, \fBint_type\fP scalarsFacet, \fBint_type\fP vectorsFacet, \fBint_type\fP tensorsFacet, \fBint_type\fP arrayCountFacet, \fBint_type\fP arrayLengthFacet, \fBint_type\fP flaggedArrayCountFacet, \fBint_type\fP flaggedArrayLengthFacet, \fBint_type\fP totalDataDepthFacet, \fBint_type\fP totalFlagDepthFacet)"
.br
.ti -1c
.RI "\fBIntegrationPointVariables\fP & \fBoperator=\fP (const \fBIntegrationPointVariables\fP &ivs)"
.br
.ti -1c
.RI "bool \fBEmpty\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLocalVariables\fP \fBipvCell\fP"
.br
.ti -1c
.RI "\fBLocalVariables\fP \fBipvSector\fP"
.br
.ti -1c
.RI "\fBLocalVariables\fP \fBipvFacet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data container storing physical variable counts at given integration points see Paluszny et al\&. (2007, Geofluids) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
