.TH "csmp::CellGenerator::vec3" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CellGenerator::vec3
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvec3\fP (double x0, double y0, double z0)"
.br
.ti -1c
.RI "\fBvec3\fP \fBoperator\-\fP (\fBvec3\fP p) const"
.br
.ti -1c
.RI "\fBvec3\fP \fBcross\fP (\fBvec3\fP p) const"
.br
.ti -1c
.RI "double \fBdot\fP (\fBvec3\fP p) const"
.br
.ti -1c
.RI "double \fBnorm\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
