.TH "csmp::MatrixOperator< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::MatrixOperator< dim > \- \fBMatrix\fP operator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MatrixOperator\&.h>\fP
.PP
Inherited by \fBcsmp::DiffusionLHS< dim >\fP, \fBcsmp::FluidCompressibilitySourceLHS< dim >\fP, \fBcsmp::PoreVolumeLHS< dim >\fP, and \fBcsmp::UpwindFluxLHS< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAccumulateFiniteVolume\fP (const \fBNode\fP< dim > &fv, \fBSparseMatrix\fP &lhs) const =0"
.br
.ti -1c
.RI "virtual void \fBAccumulateStencil\fP (const \fBElement\fP< dim > &fe, \fBSparseMatrix\fP &lhs) const =0"
.br
.ti -1c
.RI "void \fBMultiplyWithTimeIncrement\fP (double dt)"
.br
.RI "includes the time increment in the multiplication factor for this operator "
.ti -1c
.RI "void \fBFactor\fP (double value)"
.br
.RI "set factor to achieve multiplication with time increment (fac=dt), subtraction (fac=-1), multiplication or division (fac=1/value) "
.ti -1c
.RI "double \fBFactor\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::MatrixOperator< dim >"\fBMatrix\fP operator\&. 

Part of the Colleoli transport scheme\&. 
.PP
\fBVersion\fP
.RS 4
0a 
.RE
.PP
\fBDate\fP
.RS 4
6/12/2017 
.RE
.PP
\fBPrecondition\fP
.RS 4
base class for matrix operators
.RE
.PP
\fBCopyright\fP
.RS 4
The University of Melbourne
.RE
.PP
TODO: move MultiplyWithDt etc to operation TODO: find way of treating terms in equation as groups in a specific way TODO: perhaps chain operations like mathematic expressions TODO: perhaps perform multiple sequential operations in an element by element fashion 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> virtual void \fBcsmp::MatrixOperator\fP< dim >::AccumulateFiniteVolume (const \fBNode\fP< dim > & fv, \fBSparseMatrix\fP & lhs) const\fR [pure virtual]\fP"

.PP
Implemented in \fBcsmp::DiffusionLHS< dim >\fP, and \fBcsmp::FluidCompressibilitySourceLHS< dim >\fP\&.
.SS "template<uint32_t dim> virtual void \fBcsmp::MatrixOperator\fP< dim >::AccumulateStencil (const \fBElement\fP< dim > & fe, \fBSparseMatrix\fP & lhs) const\fR [pure virtual]\fP"

.PP
Implemented in \fBcsmp::DiffusionLHS< dim >\fP, \fBcsmp::FluidCompressibilitySourceLHS< dim >\fP, and \fBcsmp::UpwindFluxLHS< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
