.TH "csmp::VTU_Interface< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::VTU_Interface< dim > \- Interface for the creation of XML files for the visualisation toolkit (VTK)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VTU_Interface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVTU_Interface\fP (const \fBModel\fP< dim > &, const std::string &problemTitle='CSMP_Simulation', bool use_problem_title_as_output_folder_name=false)"
.br
.ti -1c
.RI "\fBVTU_Interface\fP (const \fBModel\fP< dim > &, const std::string &problemTitle, const std::string &subFolderTitle, bool use_problem_title_as_output_folder_name=false)"
.br
.ti -1c
.RI "\fB~VTU_Interface\fP ()"
.br
.RI "destructor removing connectivity files from the heap "
.ti -1c
.RI "template<class T> bool \fBOutputDataToVTU\fP (const std::string &fileName, const std::string &propertyName, const std::string &regionName='Model', T timestep=static_cast< T >(0))"
.br
.RI "output a single property to VTU for given region "
.ti -1c
.RI "template<class T> bool \fBOutputDataToVTU\fP (const std::string &fileName, const std::list< std::string > &propertyNames, const std::string &regionName='Model', T timestep=static_cast< T >(0))"
.br
.RI "output a list of properties to VTU for given region "
.ti -1c
.RI "template<class T> bool \fBOutputDataToVTU\fP (const std::string &fileName, const std::vector< std::string > &propertyNames, const std::string &regionName='Model', T timestep=static_cast< T >(0))"
.br
.RI "output a vector of properties to VTU for given region "
.ti -1c
.RI "template<class T> bool \fBOutputDataToVTU\fP (const std::string &fileName, const std::set< std::string > &propertyNames, const std::string &regionName='Model', T timestep=static_cast< T >(0))"
.br
.RI "output a set of properties to VTU for given region "
.ti -1c
.RI "template<template< uint32_t > class CELL, class T> bool \fBOutputDataToVTU\fP (const std::string &fileName, const std::string &propertyName, const \fBModelSubDomain\fP< dim, CELL > &subDomain, T timestep=static_cast< T >(0))"
.br
.RI "output a single property to VTU for given model sub domain (\fBRegion\fP, \fBBoundary\fP or \fBSplitBoundary\fP) "
.ti -1c
.RI "template<template< uint32_t > class CELL, class T> bool \fBOutputDataToVTU\fP (const std::string &fileName, const std::list< std::string > &propertyNames, const \fBModelSubDomain\fP< dim, CELL > &subDomain, T timestep=static_cast< T >(0))"
.br
.RI "output a list of properties to VTU for given model sub domain (\fBRegion\fP, \fBBoundary\fP or \fBSplitBoundary\fP) "
.ti -1c
.RI "template<template< uint32_t > class CELL, class T> bool \fBOutputDataToVTU\fP (const std::string &fileName, const std::vector< std::string > &propertyNames, const \fBModelSubDomain\fP< dim, CELL > &subDomain, T timestep=static_cast< T >(0))"
.br
.RI "output a vector of properties to VTU for given model sub domain (\fBRegion\fP, \fBBoundary\fP or \fBSplitBoundary\fP) "
.ti -1c
.RI "template<template< uint32_t > class CELL, class T> bool \fBOutputDataToVTU\fP (const std::string &fileName, const std::set< std::string > &propertyNames, const \fBModelSubDomain\fP< dim, CELL > &subDomain, T timestep=static_cast< T >(0))"
.br
.RI "output a set of properties to VTU for given model sub domain (\fBRegion\fP, \fBBoundary\fP or \fBSplitBoundary\fP) "
.ti -1c
.RI "bool \fBVariableNameAliases\fP (const std::map< std::string, std::string > &variableNameAliases)"
.br
.RI "provide aliases for csmp variables that will be shown in vtu instead "
.ti -1c
.RI "void \fBCreateArrayComponentPrefixNames\fP (std::string array_var_name, std::vector< std::string > &index_to_name)"
.br
.ti -1c
.RI "void \fBSetSuffixText\fP (std::string text)"
.br
.RI "Allows adding text after the timestep number to the vtu filename\&. By default, this string is empty\&. "
.ti -1c
.RI "const std::string & \fBGetProblemTitle\fP () const"
.br
.ti -1c
.RI "void \fBOmitZeroInFileName\fP (bool omitZeroInFileName)"
.br
.RI "control whether '0' is appended "
.ti -1c
.RI "bool \fBOmitZeroInFileName\fP () const"
.br
.ti -1c
.RI "void \fBOutputElementVectorAndTensorDataAtCellCenters\fP (bool element_data_at_cell_centers)"
.br
.RI "setup "
.ti -1c
.RI "void \fBOutputRegionVectorAndTensorDataAtRegionCenters\fP (bool region_data_at_cell_centers)"
.br
.ti -1c
.RI "void \fBDeleteConnectivity\fP ()"
.br
.RI "allows to force recreation of connectivity map (FOR THE UPCOMING OUTPUT ONLY!!!) "
.ti -1c
.RI "template<class T> string \fBFullOutputFileName\fP (const string &fileName, T timestep)"
.br
.ti -1c
.RI "template<class T> bool \fBOutputDataToVTU\fP (const string &fileName, const string &propertyName, const string &regionName, T timestep)"
.br
.RI "user interface to output single property to vtu for a \fBcsmp::Region\fP "
.ti -1c
.RI "template<class T> bool \fBOutputDataToVTU\fP (const string &fileName, const list< string > &propertyNames, const string &regionName, T timestep)"
.br
.RI "user interface to output list of properties to vtu for a \fBcsmp::Region\fP "
.ti -1c
.RI "template<class T> bool \fBOutputDataToVTU\fP (const string &fileName, const \fBvector\fP< string > &propertyNames, const string &regionName, T timestep)"
.br
.RI "user interface to output vector of properties to vtu for a \fBcsmp::Region\fP "
.ti -1c
.RI "template<class T> bool \fBOutputDataToVTU\fP (const string &fileName, const set< string > &propertyNames, const string &regionName, T timestep)"
.br
.RI "user interface to output set of properties to vtu for a \fBcsmp::Region\fP "
.ti -1c
.RI "template<template< uint32_t > class CELL, class T> bool \fBOutputDataToVTU\fP (const string &fileName, const string &propertyName, const \fBModelSubDomain\fP< dim, CELL > &subDomain, T timestep)"
.br
.RI "user interface to output property to vtu for a \fBcsmp::ModelSubDomain\fP "
.ti -1c
.RI "template<template< uint32_t > class CELL, class T> bool \fBOutputDataToVTU\fP (const string &initial_file_name, const list< string > &propertyNamesList, const \fBModelSubDomain\fP< dim, CELL > &subDomain, T timestep)"
.br
.RI "user interface to output list of properties to vtu for a \fBcsmp::ModelSubDomain\fP "
.ti -1c
.RI "template<template< uint32_t > class CELL, class T> bool \fBOutputDataToVTU\fP (const string &initial_file_name, const \fBvector\fP< string > &propertyNamesList, const \fBModelSubDomain\fP< dim, CELL > &subDomain, T timestep)"
.br
.RI "user interface to output vector of properties to vtu for a \fBcsmp::ModelSubDomain\fP "
.ti -1c
.RI "template<template< uint32_t > class CELL, class T> bool \fBOutputDataToVTU\fP (const string &initial_file_name, const set< string > &propertyNames, const \fBModelSubDomain\fP< dim, CELL > &subDomain, T timestep)"
.br
.RI "user interface to output set of properties to vtu for a \fBcsmp::ModelSubDomain\fP "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBOutputMultiBlockVTU\fP (const string &fileName, const \fBvector\fP< string > &fileNames, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.RI "write multiblock file "
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputFieldNodesAndElementDataToVTU\fP (const string &fileName, const list< \fBIndex\fP > &fieldDataIndices, const list< \fBIndex\fP > &nodeIndices, const list< \fBIndex\fP > &elementIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.RI "we dispatch the output to node and element scalar/vector/tensor/array/flagged array "
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputElementBarycentricDataToVTU\fP (const string &fileName, const list< \fBIndex\fP > &elementMatrixIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputRegionDataToVTU\fP (const string &fileName, const list< \fBIndex\fP > &regionIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputFiniteElementIntegrationPointsDataToVTU\fP (const string &fileName, const list< \fBIndex\fP > &feipIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputFiniteVolumeSectorIntegrationPointsDataToVTU\fP (const string &fileName, const list< \fBIndex\fP > &fvsipIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputFiniteVolumeFacetIntegrationPointsDataToVTU\fP (const string &fileName, const list< \fBIndex\fP > &fvfipIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBOutputFieldDataToVTU\fP (\fBXML_Document\fP &outputFile, const \fBModelSubDomain\fP< dim, CELL > &subDomain, const list< \fBIndex\fP > &indices)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBOutputPointDataToVTU\fP (\fBXML_Document\fP &outputFile, const \fBModelSubDomain\fP< dim, CELL > &subDomain, const list< \fBIndex\fP > &indices)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBOutputCellDataToVTU\fP (\fBXML_Document\fP &outputFile, const \fBModelSubDomain\fP< dim, CELL > &subDomain, const list< \fBIndex\fP > &indices)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> \fBXML_Document\fP * \fBfindConnectivityFile\fP (map< const \fBModelSubDomain\fP< dim, CELL > *, \fBXML_Document\fP * > &connectivityMap, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBinsertConnectivityFile\fP (map< const \fBModelSubDomain\fP< dim, CELL > *, \fBXML_Document\fP * > &connectivityMap, \fBXML_Document\fP *newConnectivityFile, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> \fBXML_Document\fP * \fBConnectivityFile\fP (map< const \fBModelSubDomain\fP< dim, CELL > *, \fBXML_Document\fP * > &connectivityMap, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.RI "returns a pointer to the regions connectivity file\&. creates one if not existing yet "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBOutputVectorsToVTU\fP (const std::string &fileName, const std::string &propertyCaption, const std::vector< std::vector< double > > &vectors)"
.br
.RI "output vectors in origin of coordinate system to VTU file "
.ti -1c
.RI "static bool \fBOutputPrincipalVectorsToVTU\fP (const std::string &fileName, const std::string &propertyCaption, const std::vector< double > &xyzLengths)"
.br
.RI "output principle axes with given length in origin of coordinate system to VTU file "
.ti -1c
.RI "static bool \fBOutputTensorToVTU\fP (const std::string &fileName, const std::string &propertyCaption, const std::vector< std::vector< double > > &tensor)"
.br
.RI "output tensor placed in origin of coordinate system to VTU file "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBFindVariableOutputAlias\fP (const std::string &csmpVariableName) const"
.br
.RI "for a given csmp variable, returns output alias if existing\&. returns variable name otherwise "
.ti -1c
.RI "std::string \fBOutputFileNamePrefix\fP (const std::string &)"
.br
.ti -1c
.RI "std::string \fBDomainSpecificOutputFileNamePrefix\fP (const std::string &fileName, const std::string &domainName)"
.br
.ti -1c
.RI "template<class T> std::string \fBFullOutputFileName\fP (const std::string &fileName, T timestep)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBOutputMultiBlockVTU\fP (const std::string &fileName, const std::vector< std::string > &fileNames, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputFieldNodesAndElementDataToVTU\fP (const std::string &fileName, const std::list< \fBcsmp::Index\fP > &fieldDataIndices, const std::list< \fBcsmp::Index\fP > &nodeIndices, const std::list< \fBcsmp::Index\fP > &elementIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputElementBarycentricDataToVTU\fP (const std::string &fileName, const std::list< \fBcsmp::Index\fP > &elementMatrixIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputRegionDataToVTU\fP (const std::string &fileName, const std::list< \fBcsmp::Index\fP > &regionIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputFiniteElementIntegrationPointsDataToVTU\fP (const std::string &fileName, const std::list< \fBcsmp::Index\fP > &feipIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputFiniteVolumeSectorIntegrationPointsDataToVTU\fP (const std::string &fileName, const std::list< \fBcsmp::Index\fP > &fvsipIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBOutputFiniteVolumeFacetIntegrationPointsDataToVTU\fP (const std::string &fileName, const std::list< \fBcsmp::Index\fP > &fvfipIndices, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBOutputFieldDataToVTU\fP (\fBXML_Document\fP &outputFile, const \fBModelSubDomain\fP< dim, CELL > &subDomain, const std::list< \fBIndex\fP > &indices)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBOutputPointDataToVTU\fP (\fBXML_Document\fP &outputFile, const \fBModelSubDomain\fP< dim, CELL > &subDomain, const std::list< \fBIndex\fP > &indices)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBOutputCellDataToVTU\fP (\fBXML_Document\fP &outputFile, const \fBModelSubDomain\fP< dim, CELL > &subDomain, const std::list< \fBIndex\fP > &indices)"
.br
.ti -1c
.RI "void \fBWriteScalar\fP (\fBXML_Document\fP &vtu, const size_t &MAX_ENTRIES_PER_LINE, double \fBvariable\fP, size_t &entriesOfLine, bool &newLine) const"
.br
.RI "write variables "
.ti -1c
.RI "void \fBWriteVector\fP (\fBXML_Document\fP &vtu, const size_t &MAX_ENTRIES_PER_LINE, const \fBVectorVariable\fP< dim > &\fBvariable\fP, size_t &entriesOfLine, bool &newLine) const"
.br
.ti -1c
.RI "void \fBWriteTensor\fP (\fBXML_Document\fP &vtu, const size_t &MAX_ENTRIES_PER_LINE, const \fBTensorVariable\fP< dim > &\fBvariable\fP, size_t &entriesOfLine, bool &newLine) const"
.br
.ti -1c
.RI "template<class Var> void \fBWriteFieldDataArray\fP (const \fBIndex\fP &key, \fBXML_Document\fP &vtu) const"
.br
.RI "write field data "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWritePointDataArrayScalar\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "write point data "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWritePointDataArrayVector\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "writes vector point data array to xml document "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWritePointDataArrayTensor\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "writes tensor point data array to xml document "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWritePointDataArrayScalarArray\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "writes point data array ( array of scalars ) to xml document "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWritePointDataArrayScalarFlaggedArray\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "writes point data array ( flagged array of scalars ) to xml document "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWriteElementDataArrayScalar\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "write element data "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWriteElementDataArrayVector\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "writes vector cell data array to xml document "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWriteElementDataArrayTensor\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "writes tensor cell data array to xml document "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWriteElementDataArrayScalarArray\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "writes cell data array ( array of scalars ) to xml document "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBWriteElementDataArrayScalarFlaggedArray\fP (const \fBIndex\fP &, \fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "writes cell data array ( array of scalars ) to xml document "
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBElement\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMap\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &subDomain)"
.br
.RI "Connnectivity File's\&. "
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBElement\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapBCS\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBElement\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapRCS\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBElement\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFEIPS\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBElement\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFVSIPS\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBElement\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFVFIPS\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBElement\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapMultiBlock\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMap\fP (const \fBModelSubDomain\fP< dim, \fBFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapBCS\fP (const \fBModelSubDomain\fP< dim, \fBFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapRCS\fP (const \fBModelSubDomain\fP< dim, \fBFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFEIPS\fP (const \fBModelSubDomain\fP< dim, \fBFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFVSIPS\fP (const \fBModelSubDomain\fP< dim, \fBFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFVFIPS\fP (const \fBModelSubDomain\fP< dim, \fBFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapMultiBlock\fP (const \fBModelSubDomain\fP< dim, \fBFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBInterFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMap\fP (const \fBModelSubDomain\fP< dim, \fBInterFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBInterFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapBCS\fP (const \fBModelSubDomain\fP< dim, \fBInterFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBInterFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapRCS\fP (const \fBModelSubDomain\fP< dim, \fBInterFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBInterFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFEIPS\fP (const \fBModelSubDomain\fP< dim, \fBInterFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBInterFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFVSIPS\fP (const \fBModelSubDomain\fP< dim, \fBInterFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBInterFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapFVFIPS\fP (const \fBModelSubDomain\fP< dim, \fBInterFace\fP > &subDomain)"
.br
.ti -1c
.RI "std::map< const \fBModelSubDomain\fP< dim, \fBInterFace\fP > *, \fBXML_Document\fP * > & \fBGetConnectivityMapMultiBlock\fP (const \fBModelSubDomain\fP< dim, \fBInterFace\fP > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> \fBXML_Document\fP * \fBfindConnectivityFile\fP (std::map< const \fBModelSubDomain\fP< dim, CELL > *, \fBXML_Document\fP * > &connectivityMap, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> bool \fBinsertConnectivityFile\fP (std::map< const \fBModelSubDomain\fP< dim, CELL > *, \fBXML_Document\fP * > &connectivityMap, \fBXML_Document\fP *newConnectivityFile, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> \fBXML_Document\fP * \fBConnectivityFile\fP (std::map< const \fBModelSubDomain\fP< dim, CELL > *, \fBXML_Document\fP * > &connectivityMap, const \fBModelSubDomain\fP< dim, CELL > &subDomain)"
.br
.ti -1c
.RI "bool \fBCloseFile\fP (const std::string &fileName, const std::string &extension, \fBXML_Document\fP &)"
.br
.ti -1c
.RI "void \fBEstablishConnectivityFileHeader\fP (\fBXML_Document\fP &) const"
.br
.RI "writes common header unstructured grids "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBEstablishConnectivityFile\fP (\fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "Elements and Nodes\&. "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBEstablishConnectivityFileBCPC\fP (\fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "\fBCell\fP centers\&. "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBEstablishConnectivityFileRPC\fP (\fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "\fBRegion\fP's \fBPoint\fP Clouds\&. "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBEstablishConnectivityFileFEIP\fP (\fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "Finite \fBElement\fP Integration Points\&. "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBEstablishConnectivityFileFVSIP\fP (\fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "Finite Volume Sector Integration Points\&. "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBEstablishConnectivityFileFVFIP\fP (\fBXML_Document\fP &, const \fBModelSubDomain\fP< dim, CELL > &subDomain) const"
.br
.RI "Finite Volume Facet Integration Points\&. "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBQuadraticWedgeConnectivity\fP (const CELL< dim > *const, std::vector< long > &data) const"
.br
.RI "Quadratic Elements connectivity\&. "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBQuadraticHexahedronConnectivity\fP (const CELL< dim > *const, std::vector< long > &data) const"
.br
.RI "converts csmp to vtk node numbering "
.ti -1c
.RI "template<template< uint32_t > class CELL> \fBVTK_TYPE\fP \fBElementType\fP (const CELL< dim > *const elmt) const"
.br
.RI "finds the corresponding VTK \fBElement\fP type for given \fBcsmp::Element\fP "
.ti -1c
.RI "std::string \fBDomainName\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &subDomain) const"
.br
.ti -1c
.RI "std::string \fBDomainName\fP (const \fBModelSubDomain\fP< dim, \fBFace\fP > &subDomain) const"
.br
.ti -1c
.RI "std::string \fBDomainName\fP (const \fBModelSubDomain\fP< dim, \fBInterFace\fP > &subDomain) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::VTU_Interface< dim >"Interface for the creation of XML files for the visualisation toolkit (VTK)\&. 


.PP
\fBAuthor\fP
.RS 4
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
2010
.RE
.PP
\fBAttention\fP
.RS 4
still issues with nan values(when attempting to visualized uninitialized vars in paraview)
.RE
.PP
Interface for serial unstructured VTK XML files (\&.vtu)\&. The VTU file format is considered to be of greater flexibility and to offer more options than the legacy format(VTK)\&. The main advantage of this interface lies in the fact that the connectivity part is only build once for each region, and is reused in consecutive outputs\&. This results in major speed increase during repetitive outputs\&.

.PP
It is possible to output multiple variables to one file, the interface automatically separates element placed vectors and tensors to another file, since a different connectivity is required (point cloud output)\&.
.SH "Features"
.PP
The key features of this interface are: -Direct mapping from CSMP to VTK elements / nodes -Linear and Quadratic elements -\fBNode\fP and \fBElement\fP properties -Caching of connectivity data for speed up in consecutive outputs -Writing several property data into one file -Output of 2D and 3D models
.SH "Application Examples"
.PP
The methods of this interface resemble those of the \fBVTK_Interface\fP\&. To instantiata a \fBVTU_Interface\fP, dimension and a reference to the model has to be provided

.PP
In the simplest case, all you need is 
.PP
.nf
VTU_Interface<SPACE> vtu( model );
vtu\&.OutputDataToVTU( "BOX", "fluid pressure" );
vtu\&.OutputDataToVTU( "BOX", "fluid pressure", "FRACTURES" );
vtu\&.OutputDataToVTU( "BOX", "fluid pressure", "FRACTURES", model_time );

.fi
.PP

.PP
For further details:

.PP
.PP
.nf
// dimension, csmp::Model and an optional session/simulation title
VTU_Interface<3U> vtu( model, "Debug Session" );
.fi
.PP

.PP
If you elect to output one variable only:

.PP
.PP
.nf
// 'permeability' of entire model at time 0
// file will be named 'ModelPermeability0\&.vtu'
vtu\&.OutputDataToVTU( "ModelPermeability", "permeability" );

// as above, but for region 'FRACTURES'
// file will be named 'FRACTURES_Permeability1333\&.vtu' for model_time = 1333
vtu\&.OutputDataToVTU( "Permeability", "permeability", "FRACTURES",  model_time );
.fi
.PP

.PP
If you wish to output multiple properties:

.PP
.PP
.nf
// create a list of the variables at the beginning
list<string> vtuVariables;
props\&.push_back( "fluid pressure" );
props\&.push_back( "total mobility" );
props\&.push_back( "saturation oil" );

//\&.\&.\&.

// to output all properties to single VTU file for entire model
// file will be named 'Simulation0\&.vtu'
vtu\&.OutputDataToVTU( "Simulation", vtuVariables );

// as above but for specific region
// file will be named 'FRACTURES_Simulation0\&.vtu' etc
vtu\&.OutputDataToVTU( "Simulation", vtuVariables, "FRACTURES" );

// as above but for specific region and model time
// file will be named 'FRACTURES_Simulation1333\&.vtu' etc
vtu\&.OutputDataToVTU( "Simulation", vtuVariables, "FRACTURES",  model_time );
.fi
.PP
.SH "Featured CSMP Elements"
.PP
csmp Elements are directly mapped to their vtk counterpart(no simplification of geometry/transformation of nodes/element types)

.PP
.PP
.nf
ISOPARAMETRIC_LINEAR_BAR
LINEAR_BAR
LINEAR_TRIANGLE3D
ISOPARAMETRIC_LINEAR_TRIANGLE
LINEAR_TRIANGLE
ISOPARAMETRIC_LINEAR_TETRAHEDRON
LINEAR_TETRAHEDRON
ISOPARAMETRIC_LINEAR_PYRAMID
ISOPARAMETRIC_LINEAR_PRISM
ISOPARAMETRIC_LINEAR_QUADRILATERAL
ISOPARAMETRIC_LINEAR_HEXAHEDRON
ISOPARAMETRIC_QUADRATIC_BAR
QUADRATIC_BAR
ISOPARAMETRIC_QUADRATIC_TRIANGLE
QUADRATIC_TRIANGLE
ISOPARAMETRIC_QUADRATIC_QUADRILATERAL
ISOPARAMETRIC_QUADRATIC_TETRAHEDRON
QUADRATIC_TETRAHEDRON
ISOPARAMETRIC_QUADRATIC_HEXAHEDRON20
ISOPARAMETRIC_QUADRATIC_PRISM15
ISOPARAMETRIC_QUADRATIC_PYRAMID13
.fi
.PP
.SH "Implementation"
.PP
Requires '\fBVTK_Interface\&.h\fP' for VTK element enumeration\&.

.PP
For the sake of user readability, binary output was postponed to a later point in development, as was offset/appended data arrays\&.

.PP
Furthermore, \fBPoint\fP locations are described by a single data array, holding their x, y and z position(in this order)\&. This approach also should increase readability compared to the alternative of having 3 seperate DataArrays, each holding the x, y and z coordinates for all points\&.

.PP
Instantiating creates the connectivity file that may be reused consequently\&. Calling OutputToVTU opens a new file, writes Headers, Mesh and Data and closes the file, leaving vtuFile_ == 0\&.

.PP
The node numbering convention of VTK is consistent with CSMP's for linear FEs, but not so for quadratic ones\&.

.PP
Uses member function pointers for visitor like node/element loops when writing data arrays\&.

.PP
Convention is that all outputs end with a new line each\&.

.PP
\fBTodo\fP
.RS 4
(3) Fix tensor output( if dim == 2 ) 

.PP
(3) Exceptions 

.PP
(3) Implement true/false checks in bool members 

.PP
(3) In insertConnectivityFile<dim> check whether insertion sucessfull 

.PP
(3) Update doc 

.PP
(3) think about bringing in mem alloc class to manage vtu files 

.PP
(3) Additional info in xml header(see legacy vtu interface) 

.PP
(3) Replace list by set as property container 
.RE
.PP

.PP
\fBNote\fP
.RS 4
minor refactoring by SKM\&.
.RE
.PP
\fBTodo\fP
.RS 4
break class into smaller functional units and remove code bloat by duplication\&. 

.PP
simplify interfaces\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> bool \fBcsmp::VTU_Interface\fP< dim >::CloseFile (const std::string & fileName, const std::string & extension, \fBXML_Document\fP & )\fR [protected]\fP"

.PP
\fBTodo\fP
.RS 4
(2-F) This should return filename up to user call 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::VTU_Interface\fP< dim >::CreateArrayComponentPrefixNames (std::string array_var_name, std::vector< std::string > & index_to_name)"
allows the creation of an index-to-name correspondance\&. If the resulting container is empty or the array variable name does not exist upon the output call, the behaviour is the default one (output of [#] suffix)\&. If the component name exists,it gets prefixed to the variable name for the vtu file\&. Works for flagged arrays, too\&. Julian, July 2014

.PP
allows the creation of an index-to-name correspondance\&. If the resulting container is empty or the array variable name does not exist upon the output call, the behaviour is the detault one (output of [#] suffix)\&. If the component name exists,it gets prefixed to the variable name for the vtu file\&. Works for flagged arrays, too\&. Julian, July 2014 
.SS "template<uint32_t dim> void \fBcsmp::VTU_Interface\fP< dim >::DeleteConnectivity ()"

.PP
allows to force recreation of connectivity map (FOR THE UPCOMING OUTPUT ONLY!!!) 
.PP
\fBTodo\fP
.RS 4
SKM verify this deletion process; looks like that there may be a memory leak\&. 
.RE
.PP
delete connectivity files for Field, \fBNode\fP and \fBElement\fP data

.PP
delete connectivity files for \fBElement\fP BaryCenters data

.PP
delete connectivity files for Regions data

.PP
delete connectivity files for Finite \fBElement\fP Integration Points data

.PP
delete connectivity files for Finite Volume Sector Integration Points data

.PP
delete connectivity files for Finite Volume Facet Integration Points data

.PP
delete connectivity files of multiblock dataset
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::EstablishConnectivityFile (\fBXML_Document\fP & , const \fBModelSubDomain\fP< dim, CELL > & subDomain) const\fR [protected]\fP"

.PP
Elements and Nodes\&. establishes the connectivity file for given region 
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::EstablishConnectivityFileBCPC (\fBXML_Document\fP & , const \fBModelSubDomain\fP< dim, CELL > & subDomain) const\fR [protected]\fP"

.PP
\fBCell\fP centers\&. establishes the connectivity file for given region using a finite element barycenter point cloud 
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::EstablishConnectivityFileFEIP (\fBXML_Document\fP & , const \fBModelSubDomain\fP< dim, CELL > & subDomain) const\fR [protected]\fP"

.PP
Finite \fBElement\fP Integration Points\&. establishes the connectivity file for given region using a finite element integration points 
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::EstablishConnectivityFileFVFIP (\fBXML_Document\fP & , const \fBModelSubDomain\fP< dim, CELL > & subDomain) const\fR [protected]\fP"

.PP
Finite Volume Facet Integration Points\&. establishes the connectivity file for given region using a finite volume integration points 
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::EstablishConnectivityFileFVSIP (\fBXML_Document\fP & , const \fBModelSubDomain\fP< dim, CELL > & subDomain) const\fR [protected]\fP"

.PP
Finite Volume Sector Integration Points\&. establishes the connectivity file for given region using a finite volume integration points 
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::EstablishConnectivityFileRPC (\fBXML_Document\fP & , const \fBModelSubDomain\fP< dim, CELL > & subDomain) const\fR [protected]\fP"

.PP
\fBRegion\fP's \fBPoint\fP Clouds\&. establishes the connectivity file for given region using a region barycenter point cloud 
.SS "template<uint32_t dim> map< const \fBModelSubDomain\fP< dim, \fBElement\fP > *, \fBXML_Document\fP * > & \fBcsmp::VTU_Interface\fP< dim >::GetConnectivityMap (const \fBModelSubDomain\fP< dim, \fBElement\fP > & subDomain)\fR [protected]\fP"

.PP
Connnectivity File's\&. 
.PP
\fBTodo\fP
.RS 4
how about some typedefs? 
.RE
.PP

.SS "template<uint32_t dim> template<template< uint32_t > class CELL, class T> bool \fBcsmp::VTU_Interface\fP< dim >::OutputDataToVTU (const string & initial_file_name, const set< string > & propertyNames, const \fBModelSubDomain\fP< dim, CELL > & subDomain, T timestep)"

.PP
user interface to output set of properties to vtu for a \fBcsmp::ModelSubDomain\fP scalars,arrays,vectors,tensors on model, elements and nodes

.PP
scalars,arrays,vectors,tensors on element barycenters

.PP
scalars,arrays,vectors,tensors on regions

.PP
scalars,arrays,vectors,tensors on finite element integration points

.PP
scalars,arrays,vectors,tensors on finite volume sector integration points

.PP
scalars,arrays,vectors,tensors on finite volume facet integration points

.PP
write multiblock file *\&.vtm
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> bool \fBcsmp::VTU_Interface\fP< dim >::OutputElementBarycentricDataToVTU (const string & fileName, const list< \fBIndex\fP > & elementMatrixIndices, const \fBModelSubDomain\fP< dim, CELL > & subDomain)"
initialize file

.PP
Open VTKFile section

.PP
Open UnstructuredGrid section

.PP
.IP "1." 4
\fBCell\fP centers data
.PP

.PP
1\&.1 create connectivity, open Piece section

.PP
1\&.2 point data arrays

.PP
1\&.3 close Piece section

.PP
Close UnstructuredGrid section

.PP
Close file
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> bool \fBcsmp::VTU_Interface\fP< dim >::OutputFieldNodesAndElementDataToVTU (const string & fileName, const list< \fBIndex\fP > & fieldDataIndices, const list< \fBIndex\fP > & nodeIndices, const list< \fBIndex\fP > & elementIndices, const \fBModelSubDomain\fP< dim, CELL > & subDomain)"

.PP
we dispatch the output to node and element scalar/vector/tensor/array/flagged array initialize file

.PP
Open VTKFile section

.PP
Open UnstructuredGrid section

.PP
.IP "1." 4
Regions data
.PP

.PP
.IP "2." 4
Nodes and \fBElement\fP's data
.PP

.PP
2\&.1 create connectivity, open Piece section

.PP
2\&.2 point data arrays

.PP
2\&.3 cell data arrays

.PP
2\&.4 close Piece section

.PP
Close UnstructuredGrid section

.PP
Close file
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> bool \fBcsmp::VTU_Interface\fP< dim >::OutputFiniteElementIntegrationPointsDataToVTU (const string & fileName, const list< \fBIndex\fP > & feipIndices, const \fBModelSubDomain\fP< dim, CELL > & subDomain)"
initialize file

.PP
Open VTKFile section

.PP
Open UnstructuredGrid section

.PP
.IP "1." 4
Finite \fBElement\fP Integration Points
.PP

.PP
1\&.1 create connectivity, open Piece section

.PP
1\&.2 point data arrays

.PP
1\&.3 close Piece section

.PP
Close UnstructuredGrid section

.PP
Close file
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> bool \fBcsmp::VTU_Interface\fP< dim >::OutputFiniteVolumeFacetIntegrationPointsDataToVTU (const string & fileName, const list< \fBIndex\fP > & fvfipIndices, const \fBModelSubDomain\fP< dim, CELL > & subDomain)"
initialize file

.PP
Open VTKFile section

.PP
Open UnstructuredGrid section

.PP
.IP "1." 4
Finite Volume Facet Integration Points
.PP

.PP
1\&.1 create connectivity, open Piece section

.PP
1\&.2 point data arrays

.PP
1\&.3 close Piece section

.PP
Close UnstructuredGrid section

.PP
Close file
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> bool \fBcsmp::VTU_Interface\fP< dim >::OutputFiniteVolumeSectorIntegrationPointsDataToVTU (const string & fileName, const list< \fBIndex\fP > & fvsipIndices, const \fBModelSubDomain\fP< dim, CELL > & subDomain)"
initialize file

.PP
Open VTKFile section

.PP
Open UnstructuredGrid section

.PP
.IP "1." 4
Finite Volume Sector Integration Points
.PP

.PP
1\&.1 create connectivity, open Piece section

.PP
1\&.2 point data arrays

.PP
1\&.3 close Piece section

.PP
Close UnstructuredGrid section

.PP
Close file
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> void \fBcsmp::VTU_Interface\fP< dim >::OutputMultiBlockVTU (const string & fileName, const \fBvector\fP< string > & fileNames, const \fBModelSubDomain\fP< dim, CELL > & subDomain)"

.PP
write multiblock file initialize file

.PP
Open multiblock section

.PP
Close multiblock section

.PP
Close file
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> bool \fBcsmp::VTU_Interface\fP< dim >::OutputRegionDataToVTU (const string & fileName, const list< \fBIndex\fP > & regionIndices, const \fBModelSubDomain\fP< dim, CELL > & subDomain)"
initialize file

.PP
Open VTKFile section

.PP
Open UnstructuredGrid section

.PP
.IP "1." 4
\fBRegion\fP's data
.PP

.PP
1\&.1 create connectivity, open Piece section

.PP
1\&.2 point data arrays

.PP
1\&.1\&. close Piece section

.PP
Close UnstructuredGrid section

.PP
Close file
.SS "template<uint32_t dim> bool \fBcsmp::VTU_Interface\fP< dim >::OutputTensorToVTU (const std::string & fileName, const std::string & propertyCaption, const std::vector< std::vector< double > > & tensor)\fR [static]\fP"

.PP
output tensor placed in origin of coordinate system to VTU file user interface to output a tensor

.PP
\fBTodo\fP
.RS 4
(3) Check inner vector sizes 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::VTU_Interface\fP< dim >::OutputVectorsToVTU (const std::string & fileName, const std::string & propertyCaption, const std::vector< std::vector< double > > & vectors)\fR [static]\fP"

.PP
output vectors in origin of coordinate system to VTU file user interface to output vectors 
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::QuadraticWedgeConnectivity (const CELL< dim > * const , std::vector< long > & data) const\fR [protected]\fP"

.PP
Quadratic Elements connectivity\&. converts csmp to vtk node numbering 
.SS "template<uint32_t dim> bool \fBcsmp::VTU_Interface\fP< dim >::VariableNameAliases (const std::map< std::string, std::string > & variableNameAliases)"

.PP
provide aliases for csmp variables that will be shown in vtu instead provide aliases for csmp variables that will be shown in vtu instead 
.PP
\fBReturns\fP
.RS 4
returns if existing was empty 
.RE
.PP

.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::WriteElementDataArrayScalar (const \fBIndex\fP & , \fBXML_Document\fP & , const \fBModelSubDomain\fP< dim, CELL > & subDomain) const\fR [protected]\fP"

.PP
write element data writes cell data array to xml document 
.SS "template<uint32_t dim> template<class Var> template void \fBcsmp::VTU_Interface\fP< dim >::WriteFieldDataArray< \fBFlaggedArrayVariable\fP > (const \fBIndex\fP & key, \fBXML_Document\fP & vtu) const\fR [protected]\fP"

.PP
write field data writes scalar field data to xml document 
.SS "template<uint32_t dim> template<template< uint32_t > class CELL> template void \fBcsmp::VTU_Interface\fP< dim >::WritePointDataArrayScalar (const \fBIndex\fP & , \fBXML_Document\fP & , const \fBModelSubDomain\fP< dim, CELL > & subDomain) const\fR [protected]\fP"

.PP
write point data writes scalar point data array to xml document 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
