.TH "csmp::SparseMatrix_Test" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SparseMatrix_Test
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBTest_PDE_IntegratorUseCases\fP ()"
.br
.RI "retests those specific methods that are used by \fBPDE_Integrator\fP "
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSparseMatrix\fP \fBA\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBResA\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBB\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBBB\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBBBB\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBResAB\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBC\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBResC\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBD\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBResD\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBE\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBF\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBResF\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBG\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBResG\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBH\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBSparseMatrix2x2\fP"
.br
.ti -1c
.RI "\fBSparseMatrix\fP \fBSparseMatrix3x3\fP"
.br
.ti -1c
.RI "\fBTensorVariable\fP< 1 > \fBTensorVariable1U\fP"
.br
.ti -1c
.RI "\fBTensorVariable\fP< 2 > \fBTensorVariable2U\fP"
.br
.ti -1c
.RI "\fBTensorVariable\fP< 3 > \fBTensorVariable3U\fP"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 1 > \fBVectorVariable1U\fP"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 2 > \fBVectorVariable2U\fP"
.br
.ti -1c
.RI "\fBVectorVariable\fP< 3 > \fBVectorVariable3U\fP"
.br
.ti -1c
.RI "\fBPoint\fP< 1 > \fBPoint1U\fP"
.br
.ti -1c
.RI "\fBPoint\fP< 2 > \fBPoint2U\fP"
.br
.ti -1c
.RI "\fBPoint\fP< 3 > \fBPoint3U\fP"
.br
.ti -1c
.RI "std::vector< double > \fBx\fP"
.br
.ti -1c
.RI "std::vector< double > \fBy\fP"
.br
.ti -1c
.RI "std::vector< double > \fBsol_y\fP"
.br
.ti -1c
.RI "std::vector< double > \fBsolB\fP"
.br
.ti -1c
.RI "std::vector< double > \fBsolD\fP"
.br
.ti -1c
.RI "std::vector< size_t > \fBsizetVector\fP"
.br
.ti -1c
.RI "double \fBfTolerance\fP = 1\&.0e\-6"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBverbose_\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void csmp::SparseMatrix_Test::run ()\fR [virtual]\fP"

.PP
Implements \fBcsmp::Test\fP\&.
.SS "void csmp::SparseMatrix_Test::Test_PDE_IntegratorUseCases ()"

.PP
retests those specific methods that are used by \fBPDE_Integrator\fP Tests specifically those methods that are used by \fBPDE_Integrator\fP:
.IP "\(bu" 2
Rows(), Cols()
.IP "\(bu" 2
Out()
.IP "\(bu" 2
Erase()
.IP "\(bu" 2
Resize()
.IP "\(bu" 2
Add( i, j, val ) - also checking whether nulled elements are eliminated
.IP "\(bu" 2
At( i, j ) vs\&. operator()(i,j)
.IP "\(bu" 2
Assign( i, j, val )
.PP

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
8/5/22 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
