.TH "csmp::vsetMakers_Test" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::vsetMakers_Test
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vsetMakers_Test\&.h>\fP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.ti -1c
.RI "template<uint32_t dim> bool \fBTestConsistencyWithCSMP_Conventions\fP (const \fBVSet\fP< dim > &)"
.br
.RI "test numbering/faces/neighbors/segments compliance of single element meshes with element numbering etc\&. for CSMP_FEM_conventions\&.pdf "
.ti -1c
.RI "template<uint32_t dim> \fBvector\fP< \fBvector\fP< uint32_t > > \fBNodesOfElementFaces\fP (const \fBVSet\fP< dim > &vset, size_t elmt)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBverbose_\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests the suite of meshes/boundary flags, data etc\&. that serve as the input for many of the unit tests created for the CSMP library\&.

.PP
TODO: test prism_test for 'invalid' elements using geometric calculations TODO: test whether the faces are in the expected place 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::vsetMakers_Test::run ()\fR [virtual]\fP"
Rectangle-shaped MODEL_TINY, consisting of 1 line element two triangles, 1 quadrilateral and 6 face object marking the box boundary\&.

.PP
Rectangle shaped mixed model with 2 intersecting line element regions (USED IN UNIT TESTS)

.PP
model SPLIT22_BASIC with box boundaries (Faces) and one through-going and one internal crossing split boundary (USED IN UNIT TESTS)
.PP
Implements \fBcsmp::Test\fP\&.
.SS "template<uint32_t dim> template bool csmp::vsetMakers_Test::TestConsistencyWithCSMP_Conventions (const \fBVSet\fP< dim > & )"

.PP
test numbering/faces/neighbors/segments compliance of single element meshes with element numbering etc\&. for CSMP_FEM_conventions\&.pdf For single element meshes only\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
