.TH "csmp::NodeCenteredFiniteVolumeAlgorithm< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::NodeCenteredFiniteVolumeAlgorithm< dim >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeCenteredFiniteVolumeAlgorithm\fP (\fBRegion\fP< dim > &)"
.br
.ti -1c
.RI "void \fBResetLHS\fP (size_t finite_volumes)"
.br
.ti -1c
.RI "void \fBResetRHS\fP (size_t finite_volumes)"
.br
.ti -1c
.RI "void \fBResetRow\fP (size_t nid)"
.br
.ti -1c
.RI "void \fBZeroRHS\fP (size_t nid)"
.br
.ti -1c
.RI "void \fBAddToLHS\fP (size_t i, size_t j, double addition)"
.br
.ti -1c
.RI "void \fBAddToRHS\fP (size_t i, double addition)"
.br
.ti -1c
.RI "void \fBAddToRESULT\fP (size_t i, double addition)"
.br
.ti -1c
.RI "void \fBAssignRESULT\fP (size_t i, double result)"
.br
.ti -1c
.RI "double \fBResult\fP (size_t i) const"
.br
.ti -1c
.RI "std::vector< double > & \fBResultVector\fP ()"
.br
.ti -1c
.RI "std::vector< double > & \fBRHSVector\fP ()"
.br
.ti -1c
.RI "double \fBLHS_Value\fP (size_t i, size_t j) const"
.br
.ti -1c
.RI "std::vector< double >::iterator \fBResultsBegin\fP ()"
.br
.ti -1c
.RI "std::vector< double >::iterator \fBResultsEnd\fP ()"
.br
.ti -1c
.RI "void \fBAccumulateLHS\fP (const \fBStencilProcessor\fP< dim > &es, double time_multiplier)"
.br
.RI "FV volume terms in diagonal & first-order terms=inter-FV fluxes in off-diagonal\&. "
.ti -1c
.RI "void \fBAccumulateMatrix_NonlinearNewtonRaphson\fP (const \fBStencilProcessor\fP< dim > &, std::vector< double > &SAT0, double time_multiplier)"
.br
.RI "Accumulation Process for Nonlinear Systems\&. "
.ti -1c
.RI "void \fBAccumulateResidual_NonlinearNewtonRaphson\fP (const \fBStencilProcessor\fP< dim > &, std::vector< double > &SAT0, double time_multiplier)"
.br
.ti -1c
.RI "void \fBAccumulateMatrixAtBoundary_NonlinearNewtonRaphson\fP (const \fBStencilProcessor\fP< dim > &, std::vector< double > &SAT0, size_t nid, uint32_t pnid, double time_multiplier, const \fBcsmp::Index\fP &adv1_key)"
.br
.ti -1c
.RI "void \fBAccumulateResidualAtBoundary_NonlinearNewtonRaphson\fP (const \fBStencilProcessor\fP< dim > &, std::vector< double > &SAT0, size_t nid, uint32_t pnid, double time_multiplier, const \fBcsmp::Index\fP &adv1_key)"
.br
.ti -1c
.RI "void \fBCompensateInflowOutFlowBoundaries\fP (size_t nid, const double &inflow, const double &flux_balance)"
.br
.ti -1c
.RI "void \fBAccumulateRHS\fP (const \fBStencilProcessor\fP< dim > &es, double time_multiplier)"
.br
.RI "Backward-Euler righthandside (psi at t0 * pore-volume) / dt for non-iterative computations\&. "
.ti -1c
.RI "void \fBAccumulateRHS\fP (const \fBStencilProcessor\fP< dim > &es, std::vector< double > &SAT0, double time_multiplier)"
.br
.RI "for iterative computations "
.ti -1c
.RI "void \fBAccumulateHigherOrderRHS\fP (const \fBStencilProcessor\fP< dim > &)"
.br
.RI "higher-order solution is added from RHS (first order in time) "
.ti -1c
.RI "void \fBAccumulateHigherOrderRHS\fP (const \fBStencilProcessor\fP< dim > &, const std::vector< std::vector< double > > &FACETFLUXES0, const std::vector< std::vector< double > > &LTDSATS0)"
.br
.RI "higher-order solution is subtracted from RHS (second order in time) "
.ti -1c
.RI "void \fBAddToRHS\fP (const \fBStencilProcessor\fP< dim > &)"
.br
.RI "first-order Backward Euler solution is added to RHS "
.ti -1c
.RI "void \fBAddToRHS\fP (const \fBStencilProcessor\fP< dim > &, std::vector< double > &SAT0)"
.br
.ti -1c
.RI "void \fBSubtractNonConservativeOutFluxesFromRHS\fP (\fBTwoPhaseModel\fP< dim > &, const std::vector< double > &FLUX_BALANCE, const \fBcsmp::Index\fP &ad_key)"
.br
.ti -1c
.RI "void \fBAccumulateIntegral_DNT_op_DN_dV_LHS\fP (const \fBStencilProcessor\fP< dim > &es)"
.br
.RI "diffusion and other divergent fluxes "
.ti -1c
.RI "void \fBAccumulateIntegral_DN_op_dS_LHS\fP (const \fBStencilProcessor\fP< dim > &es)"
.br
.ti -1c
.RI "void \fBAccumulateSectorSourceTermsInLHS\fP (const \fBStencilProcessor\fP< dim > &)"
.br
.ti -1c
.RI "void \fBAccumulateFluxUpwindSaturationProducts\fP (const \fBStencilProcessor\fP< dim > &es)"
.br
.RI "accumulates FV volume terms and first-order terms=inter-FV fluxes "
.ti -1c
.RI "void \fBAccumulateHigherOrderFluxSaturationProducts\fP (const \fBStencilProcessor\fP< dim > &es)"
.br
.RI "higher-order version for the case when fractional flows are considered "
.ti -1c
.RI "void \fBSolveMatrixEquation\fP ()"
.br
.ti -1c
.RI "double \fBOutputResults\fP (const \fBPropertyDatabase\fP< dim > &, const \fBcsmp::Index\fP &adv_key, bool show_range, uint32_t var_comp_nr=0) const"
.br
.RI "results are stored back in the \fBRegion\fP where condition flag is PLAIN "
.ti -1c
.RI "double \fBOutputResults\fP (const \fBPropertyDatabase\fP< dim > &, size_t result_phase, const \fBcsmp::Index\fP &adv1_key, const \fBcsmp::Index\fP &adv2_key, bool show_range) const"
.br
.RI "multiphase version for range 0\&.\&.1 (adv1=wetting phase=1) "
.ti -1c
.RI "double \fBOutputResultsWithL2NormRes\fP (const \fBPropertyDatabase\fP< dim > &, const \fBcsmp::Index\fP &adv_key, bool show_range) const"
.br
.RI "testing only: results are stored back in the \fBRegion\fP where condition flag is PLAIN "
.ti -1c
.RI "double \fBOutputResults_NonlinearNewtonRaphson\fP (const \fBPropertyDatabase\fP< dim > &, size_t result_phase, const \fBcsmp::Index\fP &adv1_key, const \fBcsmp::Index\fP &adv2_key, bool show_range)"
.br
.RI "multiphase version for range 0\&.\&.1 (adv1=wetting phase=1) "
.ti -1c
.RI "int32_t \fBOutputResults_NonlinearNewtonRaphson\fP (const \fBPropertyDatabase\fP< dim > &, size_t result_phase, const \fBcsmp::Index\fP &adv1_key, const \fBcsmp::Index\fP &adv2_key, bool show_range, std::vector< double > &, std::vector< double > &)"
.br
.RI "multiphase version for range 0\&.\&.1 (adv1=wetting phase=1) "
.ti -1c
.RI "CSMP_DEFAULT_LINEAR_SOLVER_SETTINGS & \fBGetSolverSettings\fP ()"
.br
.RI "interface to solver settings and instance "
.ti -1c
.RI "CSMP_DEFAULT_LINEAR_SOLVER * \fBGetSolver\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "bool \fBVerbose\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::NodeCenteredFiniteVolumeAlgorithm (\fBRegion\fP< dim > & sg)\fR [explicit]\fP"
Initializes LHS, XVEC, and RHS arrays\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::AccumulateFluxUpwindSaturationProducts (const \fBStencilProcessor\fP< dim > & es)"

.PP
accumulates FV volume terms and first-order terms=inter-FV fluxes The transport velocity values projected onto the facet normals and multiplied with the facet areas are multiplied with the upstream values of the transported variable at each facet integration point and accumulated into the solution \fBvector<double>\fP as the upstream weighted first-order fluxes\&. 
.br
.SH "Input Arguments"
.PP
To assign the higher order fluxes, the method needs access to the current finite element and the associated FV stencil processor\&. 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::AccumulateHigherOrderFluxSaturationProducts (const \fBStencilProcessor\fP< dim > & es)"

.PP
higher-order version for the case when fractional flows are considered The transport velocity values projected onto the facet normals and multiplied with the facet areas are multiplied with the (limited) 'isat' variable values at each facet integration point to define the higher order fluxes\&. 
.br
.SH "Input Arguments"
.PP
To assign the higher order fluxes, the method needs access to the current finite element and the associated FV stencil processor\&. 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::AccumulateHigherOrderRHS (const \fBStencilProcessor\fP< dim > & es)"

.PP
higher-order solution is added from RHS (first order in time) Higher-order fluxes are calculated from the slope-limited saturations at the current and previous time levels and the corresponding volume fluxes integrated over the facets dividing the finite-volume sectors\&. 
.br

.PP
The contributions from the two time levels are weighted using the theta limiter value computed for each facet\&. When theta=1 the scheme is fully implicit, i\&.e\&. only the contributions for the new time level are considered\&. Theta limiting attempts however the equally weight the contributions on the basis of their magnitude\&. If this is achieved, the scheme is second-order accurate in time and numerical diffusion is minimized\&. 
.br

.PP
The computed higher-order fluxes are subtracted from the righthand vector\&.
.SH "Input Arguments"
.PP
To compute the higher-order fluxes, the method requires access to the current \fBElement\fP and up-to-date finite volume processor object\&. 
.br

.PP
The method requires the facet-fluxes and the slope-limited interpolated values of the transported variable at the facet integration points\&. The temporal limiter value, theta, is supplied as a 7th method argument\&. 
.br
.SH "Implementation"
.PP
.SH "Application Examples"
.PP
In higher-order theta-limited transport scheme\&. 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::AccumulateIntegral_DNT_op_DN_dV_LHS (const \fBStencilProcessor\fP< dim > & es)"

.PP
diffusion and other divergent fluxes Uses the finite element method to add diffusion to the FV scheme\&.

.PP
\fBAttention\fP
.RS 4
this method relies on uptodate \fBNode\fP indices\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::AccumulateLHS (const \fBStencilProcessor\fP< dim > & es, double time_multiplier)"

.PP
FV volume terms in diagonal & first-order terms=inter-FV fluxes in off-diagonal\&. Accumulates the volume over the time-increment and the outgoing facet- integrated fluxes into the diagonal of the solution matrix\&. 
.br

.PP
An upstream coupling is created by accumulating the fluxes that come into the finite-volumes sectors as off-diagonal elements\&. For each finite-volume facet, there are the nodes i (inside) and j(outside)\&. 
.br
.SH "Input Arguments"
.PP
The current \fBElement\fP and uptodate FiniteVolumeProcessor are used to retrieve the variables of interest\&. 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::AccumulateRHS (const \fBStencilProcessor\fP< dim > & es, std::vector< double > & SAT0, double time_multiplier)"

.PP
for iterative computations Righthand side for Backward-Euler FD time stepping 
.br
 
.PP
.nf
RHS = (FV-volume * sat_t0) / time-increment

.fi
.PP
.SH "Input Arguments"
.PP
The current \fBElement\fP and up-to-date FiniteVolumeProcessor are used to retrieve the variables of interest\&. The saturations from the current timelevel are supplied by the \fBvector<double>\fP SAT0\&. The time-multiplier is needed to divide the finite-volume sector volume by\&. 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::AccumulateSectorSourceTermsInLHS (const \fBStencilProcessor\fP< dim > & es)"
Source term per finite volume sector is added to the diagonal of the matrix\&. 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::AddToRHS (const \fBStencilProcessor\fP< dim > & es)"

.PP
first-order Backward Euler solution is added to RHS Add first-order Backward Euler solution to RHS (using upstream saturations)\&. This integrates upstream sats over the segments by summing (flux * saturation) products over faces\&. 
.br
.SH "Input Arguments"
.PP
References to the current element, finite-volume stencil processor, and the fluxes integrated over the facets inside the current element\&. 
.SS "template<uint32_t dim> CSMP_DEFAULT_LINEAR_SOLVER * \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::GetSolver ()"
returns the solver object if SAMG is used to solve the matrix equations It is important to note that this, just like the old method above (GetSolverSettings), asks for an instance of \fBSAMG_Solver\fP that may not exist, given that if the problem is smaller than 50 nodes, a Gauss_Jordan solver is created by default\&. I believe this needs re-consideration\&. Rather , I would utilize \fBSAMG_Solver\fP even for small problems, with special settings\&. -- Julian 24-09\&.2013 
.SS "template<uint32_t dim> CSMP_DEFAULT_LINEAR_SOLVER_SETTINGS & \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::GetSolverSettings ()"

.PP
interface to solver settings and instance returns the settings object if SAMG is used to solve the matrix equations 
.SS "template<uint32_t dim> double \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::OutputResults (const \fBPropertyDatabase\fP< dim > & p, const \fBcsmp::Index\fP & adv_key, bool show_range, uint32_t var_comp_nr = \fR0\fP) const"

.PP
results are stored back in the \fBRegion\fP where condition flag is PLAIN Where the condition flag is not DIRICH, results are mapped from solution \fBvector<double>\fP back to finite volume cells after performing a range cheque\&. 
.br
.SH "Messages"
.PP
If the result is out of range at more than 10 nodes, an error message is returned\&. If errors occur at more than 2 per cent of the nodes, an 'out_of_range' exception is thrown\&. 
.SS "template<uint32_t dim> double \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::OutputResults (const \fBPropertyDatabase\fP< dim > & p, size_t result_phase, const \fBcsmp::Index\fP & adv1_key, const \fBcsmp::Index\fP & adv2_key, bool show_range) const"

.PP
multiphase version for range 0\&.\&.1 (adv1=wetting phase=1) Updates saturation water as well! - by default phase1 = wetting phase multiphase version - assumes range to be between 0 and 1 
.SS "template<uint32_t dim> double \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::OutputResults_NonlinearNewtonRaphson (const \fBPropertyDatabase\fP< dim > & p, size_t result_phase, const \fBcsmp::Index\fP & adv1_key, const \fBcsmp::Index\fP & adv2_key, bool show_range)"

.PP
multiphase version for range 0\&.\&.1 (adv1=wetting phase=1) 
.PP
\fBTodo\fP
.RS 4
JM move these kinds of testing methods into the subclasses that are used for the testing:
.RE
.PP

.PP
i\&.e\&., class NodeCenteredFiniteVolumeAlgorithm_Test : public \fBNodeCenteredFiniteVolumeAlgorithm\fP { \&.\&.\&.

.PP
and do not just sloppily copy everything without cleaning up the parts that are no longer used or have changed\&.

.PP
\fBTodo\fP
.RS 4
SMK: Dear SKM (from JM): This method is needed by the Newton Raphson procedure\&. Please contact me directly if these things are important\&. It is NOT a testing method\&. I do my best to not perform any "sloppy" copying\&. 
.RE
.PP

.SS "template<uint32_t dim> int32_t \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::OutputResults_NonlinearNewtonRaphson (const \fBPropertyDatabase\fP< dim > & p, size_t result_phase, const \fBcsmp::Index\fP & adv1_key, const \fBcsmp::Index\fP & adv2_key, bool show_range, std::vector< double > & DS, std::vector< double > & SN)"

.PP
multiphase version for range 0\&.\&.1 (adv1=wetting phase=1) Save results for saturation in order to use it on the next nonlinear iteration step\&. Updates saturation water as well! - by default phase1 = wetting phase multiphase version - assumes range to be between 0 and 1 
.SS "template<uint32_t dim> double \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::OutputResultsWithL2NormRes (const \fBPropertyDatabase\fP< dim > & p, const \fBcsmp::Index\fP & adv_key, bool show_range) const"

.PP
testing only: results are stored back in the \fBRegion\fP where condition flag is PLAIN 
.PP
\fBTodo\fP
.RS 4
JM move these kinds of testing methods into the subclasses that are used for the testing: JM addition 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::ResetLHS (size_t nodes)"
Removes potential leftover entries from previous solution matrix or re-initializes the righthand \fBvector<double>\fP to zero\&. 
.br
.SH "Input Arguments"
.PP
The size of the computational problem = number of FVs\&. 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::SolveMatrixEquation ()"
The matrices and vectors are copied to condensed row storage and are then used by the AMG to find a solution\&. 
.SS "template<uint32_t dim> void \fBcsmp::NodeCenteredFiniteVolumeAlgorithm\fP< dim >::SubtractNonConservativeOutFluxesFromRHS (\fBTwoPhaseModel\fP< dim > & relperm, const std::vector< double > & FLUX_BALANCE, const \fBcsmp::Index\fP & ad_key)"
including potential point sources or sinks in the model\&.

.PP
If the fluxbalance is negative, this means that there is outflow from a truncated boundary cell that only has inward pointing normals\&.

.PP
This function compensates this negative balance\&.

.PP
\fBWarning\fP
.RS 4
THIS FUNCTION ACTUALLY ADDS CONTRIBUTIONS DUE TO NON_CONSERVATIVE OUTFLUXES To RHS 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
