.TH "csmp::ModelPreProcessor3D" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ModelPreProcessor3D
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ModelPreProcessor3D\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelPreProcessor3D\fP (const std::string &csmp_model)"
.br
.RI "reads CSMP native model from file to perform the preprocessing on "
.ti -1c
.RI "void \fBCheckIntegrity\fP (const std::string &report_file) const"
.br
.RI "tests: "
.in -1c
.SH "Detailed Description"
.PP 
Preparation of input models so that they have all the facilities (boundaries, splitboundaries, neighbor information etc\&. to perform standard CSMP computations\&.

.PP
Output of CSMP native models into different formats for comparison runs with other software\&.

.PP
TODO: use VTK mesh and contouring of variables to perform a flux-adapted gridding\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
