.TH "csmp::MohrCoulombFailure_Visitor< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::MohrCoulombFailure_Visitor< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MohrCoulombFailure_Visitor\&.h>\fP
.PP
Inherits \fBcsmp::Visitor< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMohrCoulombFailure_Visitor\fP (\fBModel\fP< dim > &, bool positive_compressive_stress_convention=true, bool verbose=false)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBElement\fP< dim > *)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBVisitor\fP (\fBPLACEMENT\fP level=MODEL, \fBPLACEMENT\fP target=ELEMENT)"
.br
.ti -1c
.RI "void \fBApplicationLevel\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApplicationTarget\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationTarget\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetInitialProperties\fP (\fBModel\fP< dim > *model)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBModel\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBRegion\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBSplitBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBInterFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBEdge\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBNode\fP< dim > *)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_target_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::MohrCoulombFailure_Visitor< dim >"Evaluates Mohr-Coulomb shear and tensile failure criteria that are output to the element integration points\&.

.PP
Input variables:
.IP "\(bu" 2
friction angle
.IP "\(bu" 2
cohesion (scalar)
.IP "\(bu" 2
stress (tensor) = Cartesian stress
.IP "\(bu" 2
fluid pressure (if this variable is not specified its value is assumed to be zero)

.PP
\fBTodo\fP
.RS 4
SKM: this visitor should include the influence of pore pressure\&.
.RE
.PP

.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::MohrCoulombFailure_Visitor\fP< dim >::MohrCoulombFailure_Visitor (\fBModel\fP< dim > & model, bool positive_compressive_stress_convention = \fRtrue\fP, bool verbose = \fRfalse\fP)\fR [explicit]\fP"

.PP
\fBAttention\fP
.RS 4
SKM 28/9/2014 - added documentation, fixed wrong output and formatted code 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::MohrCoulombFailure_Visitor\fP< dim >::Visit (\fBElement\fP< dim > * e)\fR [virtual]\fP"
Loops over the element integration points and evaluates shear and tensile failure potential\&. Where failure occurred the variable 'failure' is set to 1\&. A distinction is made between tensile 'tensile failure' and shear failure 'failure' variables\&.

.PP
\fBAttention\fP
.RS 4
it is assumed that the tensile strength is about 1/10 of the cohesive strength of the rock

.PP
SKM 28/9/2014 - added case where stress is placed on the element\&. 
.RE
.PP

.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
