.TH "csmp::TypeMatchesVariableType< T, IT >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TypeMatchesVariableType< T, IT >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <enumTypeCompatibilityChecks\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBvalue\fP = false }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, \fBVARIABLE_TYPE\fP IT>
.br
struct csmp::TypeMatchesVariableType< T, IT >"for compile-time type compatibility checking between csmp enumerations and types 
.PP
.nf
use like:

static_assert( TypeMatchesVariableType<type, placement>::value, "type does not match variable placement");

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
