.TH "csmp::SimulatorMonitor< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SimulatorMonitor< dim >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimulatorMonitor\fP (std::string text_file, \fBModel\fP< dim > &model, bool restart, const std::list< std::string > &variables_to_monitor_integrals, const std::list< std::string > &variables_to_monitor_ranges, const std::list< std::string > &variables_to_monitor_single_values, const std::list< std::string > &subdomains_to_integrate, const std::list< std::string > &subdomains_to_measure_ranges, const std::list< std::string > &subdomains_to_calculate_dimension, const std::list< std::string > &subdomains_to_calculate_perimeter, const std::list< std::string > &to_divide_by_region_porevolume, const std::list< std::string > &to_multiply_integrand_by_porosity, bool verbose=true)"
.br
.ti -1c
.RI "void \fBScalarPropertyIntegrals\fP (std::vector< double > &rowdata)"
.br
.RI "calculates property integrals and stores these for the current time-step and property name "
.ti -1c
.RI "void \fBScalarPropertyRanges\fP (std::vector< double > &rowdata)"
.br
.ti -1c
.RI "void \fBScalarPropertyValues\fP (std::vector< double > &rowdata)"
.br
.ti -1c
.RI "void \fBCalculateDimensionsAndPerimeters\fP (std::vector< double > &rowdata)"
.br
.ti -1c
.RI "void \fBMonitor\fP ()"
.br
.ti -1c
.RI "void \fBInsertValueHeader\fP (std::string property_regionname, std::vector< size_t > &indexes)"
.br
.ti -1c
.RI "void \fBClearAllHeadersAndValues\fP ()"
.br
.ti -1c
.RI "void \fBEraseDataValuesOnly\fP ()"
.br
.ti -1c
.RI "bool \fBDataExists\fP ()"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.ti -1c
.RI "void \fBReadOldMonitoringData\fP (std::string file_name)"
.br
.ti -1c
.RI "void \fBReadModelTime\fP (std::vector< double > &rowdata)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::SimulatorMonitor\fP< dim >::CalculateDimensionsAndPerimeters (std::vector< double > & rowdata)"

.PP
\fBTodo\fP
.RS 4
multiplication with porosity is not supported as with regions\&. To be resolved later on\&. 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
multiplication with porosity is not supported as with regions\&. To be resolved later on\&. 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
multiplication with porosity is not supported as with regions\&. To be resolved later on\&. 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
multiplication with porosity is not supported as with regions\&. To be resolved later on\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::SimulatorMonitor\fP< dim >::InsertValueHeader (std::string property_regionname, std::vector< size_t > & indexes)"
adds in values in a separate container, to be output to a separate file with the same prefix name as the other monitoring file, except with the "_ext" added to its name\&. 
.SS "template<uint32_t dim> void \fBcsmp::SimulatorMonitor\fP< dim >::ReadOldMonitoringData (std::string file_name)"
if the size of the data read on one line does not match the number of headers, skip to the next data line\&.
.SS "template<uint32_t dim> void \fBcsmp::SimulatorMonitor\fP< dim >::ScalarPropertyIntegrals (std::vector< double > & rowdata)"

.PP
calculates property integrals and stores these for the current time-step and property name calculates property integrals and stores these for the current time-step and property name if the variable 'thickness' is defined in the \fBPropertyDatabase\fP, it is used to scale the element by element integrals\&. 
.SS "template<uint32_t dim> void \fBcsmp::SimulatorMonitor\fP< dim >::ScalarPropertyValues (std::vector< double > & rowdata)"
this method reads values directly from the model 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
