.TH "csmp::Fracture< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Fracture< dim > \- The \fBFracture\fP class is a \fBFractureTip\fP Manager\&. It is responsible for the creation of fracture tips relevant to a split boundary, and their updating when a \fBFractureTip\fP propagates\&. The \fBFracture\fP class has 1 Fundamental requirement for creation 1) A split boundary\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Fracture\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFracture\fP (\fBModel\fP< dim > &model, std::string splitboundary, TIP_TYPE=DC_TIP)"
.br
.ti -1c
.RI "\fB~Fracture\fP ()"
.br
.ti -1c
.RI "\fBSplitBoundary\fP< dim > & \fBSplitBoundaryRef\fP ()"
.br
.ti -1c
.RI "std::string \fBMidRegionName\fP ()"
.br
.ti -1c
.RI "std::string \fBSplitBoundaryName\fP ()"
.br
.ti -1c
.RI "void \fBAveragePropertyToMiddle\fP (\fBIndex\fP property, std::vector< \fBInterFace\fP< dim > * > &interfaces)"
.br
.RI "General method to split tip nodes along a predefined path specified by the boundary object\&. "
.ti -1c
.RI "void \fBInputPropertyValue\fP (const char *prop, \fBScalarVariable\fP Sval, \fBBOX_BOUNDARY\fP bound_side)"
.br
.ti -1c
.RI "std::vector< \fBFractureTip\fP< dim > * > \fBFractureTips\fP ()"
.br
.ti -1c
.RI "void \fBSetOldTipCoordinatesAsCurrent\fP ()"
.br
.ti -1c
.RI "std::vector< \fBNode\fP< dim > * > \fBBoxBoundaryNodes\fP ()"
.br
.ti -1c
.RI "std::vector< \fBElement\fP< dim > * > \fBBoxBoundaryElements\fP ()"
.br
.ti -1c
.RI "std::vector< \fBElement\fP< dim > * > \fBBoxBoundaryElements\fP (\fBBOX_BOUNDARY\fP side)"
.br
.ti -1c
.RI "std::map< \fBInterFace\fP< dim > *, size_t > \fBFindInterFaceOfNode\fP (\fBNode\fP< dim > *n_ptr, \fBINTERFACE_SIDE\fP side, \fBSUBDOMAIN_PART\fP part=COMPLETE)"
.br
.ti -1c
.RI "std::map< \fBPoint\fP< dim >, \fBNode\fP< dim > * > \fBNodeMap\fP (\fBINTERFACE_SIDE\fP side)"
.br
.ti -1c
.RI "std::map< double, \fBNode\fP< dim > * > \fBNodeMap\fP (\fBINTERFACE_SIDE\fP side, size_t xyz)"
.br
.ti -1c
.RI "std::map< \fBPoint\fP< dim >, \fBElement\fP< dim > * > \fBElementMap\fP (\fBINTERFACE_SIDE\fP side)"
.br
.ti -1c
.RI "double \fBFractureLength\fP (\fBINTERFACE_SIDE\fP side)"
.br
.RI "Calculates length by calling element area\&. "
.ti -1c
.RI "double \fBDistanceFromTip\fP (std::map< \fBPoint\fP< dim >, \fBNode\fP< dim > * > &, \fBNode\fP< dim > *N, \fBBOX_BOUNDARY\fP side=RIGHT)"
.br
.ti -1c
.RI "double \fBMaxPropertyValue\fP (const char *prop, \fBINTERFACE_SIDE\fP side=MIDDLE)"
.br
.ti -1c
.RI "double \fBVolume\fP (const char *aperture='aperture')"
.br
.ti -1c
.RI "double \fBSurfaceIntegral\fP (const char *oper, \fBINTERFACE_SIDE\fP side)"
.br
.ti -1c
.RI "void \fBConfigureAnalyticalParametersAndSolutions\fP (double constant_flux, double viscosity, double critSIF, double youngs_modulus, double poisson_ratio, bool plane_strain=true)"
.br
.ti -1c
.RI "double \fBAnalyticalAperture\fP (double t, double x=0\&.0)"
.br
.ti -1c
.RI "double \fBAnalyticalPressure\fP (double t, double x=0\&.0)"
.br
.ti -1c
.RI "double \fBAnalyticalLength\fP (double t)"
.br
.ti -1c
.RI "double \fBDimensionlessToughness\fP ()"
.br
.ti -1c
.RI "double \fBDimensionlessViscosity\fP ()"
.br
.ti -1c
.RI "void \fBStoreDisplacementDifferenceAsAperture\fP (const std::string displacement, const std::string aperture, \fBINTERFACE_SIDE\fP side=MIDDLE)"
.br
.ti -1c
.RI "void \fBOut\fP ()"
.br
.ti -1c
.RI "void \fBSolOut\fP (\fBINTERFACE_SIDE\fP side=MIDDLE, const char *aperture='aperture', const char *pressure='fluid pressure')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeQuarterPointElements\fP ()"
.br
.ti -1c
.RI "void \fBRestoreQuarterPointElementsToMidPoint\fP ()"
.br
.ti -1c
.RI "void \fBCreateFractureTips\fP ()"
.br
.ti -1c
.RI "void \fBSetOldFractureLengthToCurrent\fP (double dt=0)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBModel\fP< dim > * \fBmodel_\fP"
.br
.ti -1c
.RI "\fBcsmp::SplitBoundary\fP< dim > & \fBsb_ref_\fP"
.br
.ti -1c
.RI "\fBRegion\fP< dim > * \fBmidregion_\fP"
.br
.ti -1c
.RI "TIP_TYPE \fBtiptype_\fP"
.br
.ti -1c
.RI "std::vector< \fBFractureTip\fP< dim > * > \fBfracturetips_\fP"
.br
.RI "Container for fracture tips\&. "
.ti -1c
.RI "std::vector< \fBNode\fP< dim > * > \fBboxboundaryNodes_\fP"
.br
.RI "vector of pointers of middle regions nodes who are at boundary "
.ti -1c
.RI "\fBIndex\fP \fBdisp_key_\fP"
.br
.ti -1c
.RI "\fBIndex\fP \fBE_key_\fP"
.br
.ti -1c
.RI "\fBIndex\fP \fBnu_key_\fP"
.br
.ti -1c
.RI "bool \fBconfigured_\fP"
.br
.ti -1c
.RI "bool \fBplane_strain_\fP"
.br
.ti -1c
.RI "double \fBQ_\fP"
.br
.ti -1c
.RI "double \fBmu_\fP"
.br
.ti -1c
.RI "double \fBKc_\fP"
.br
.ti -1c
.RI "double \fBym_\fP"
.br
.ti -1c
.RI "double \fBnu_\fP"
.br
.ti -1c
.RI "double \fBK_dominant\fP"
.br
.ti -1c
.RI "double \fBM_dominant\fP"
.br
.ti -1c
.RI "double \fBK_small\fP"
.br
.ti -1c
.RI "double \fBM_small\fP"
.br
.ti -1c
.RI "double \fBold_fracture_length_\fP"
.br
.ti -1c
.RI "double \fBaccumulated_time_\fP"
.br
.ti -1c
.RI "bool \fBtwo_tips_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::Fracture< dim >"The \fBFracture\fP class is a \fBFractureTip\fP Manager\&. It is responsible for the creation of fracture tips relevant to a split boundary, and their updating when a \fBFractureTip\fP propagates\&. The \fBFracture\fP class has 1 Fundamental requirement for creation 1) A split boundary\&. 

This class provides a tool to model fractures and accurately handle fracture mechanics\&.

.PP
\fBAuthor\fP
.RS 4
M\&. Nejati 
.RE
.PP
\fBDate\fP
.RS 4
2016
.RE
.PP
Extended by 
.PP
\fBAuthor\fP
.RS 4
E\&. Pezzulli 
.RE
.PP
\fBDate\fP
.RS 4
2019
.RE
.PP

.PP
The \fBFracture\fP class manages two fundamental data types 1) A collection of TipNodes\&. 2) A collection of FractureTips\&.

.PP
Construction involves: Identifying Tip Nodes of the splitboundary & constructing an associated \fBFractureTip\fP\&.

.PP
Propagation involves: A modification (without deletion/reconstruction) of the fracture tips and their associated tip nodes\&.

.PP
\fBAttention\fP
.RS 4
From a User Perspective! When advancing to a new time step, the user must set run SetOldCoordinatesToCurrentTip() in order to calibrate the old tip coordinate of all \fBFractureTip\fP objects (this ensures propagation velocity is calculated correctly every time step) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::Fracture\fP< dim >::~\fBFracture\fP ()"
Destructor for \fBFracture\fP tips that are dynamically created 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> double \fBcsmp::Fracture\fP< dim >::AnalyticalAperture (double t, double x = \fR0\&.0\fP)"
EP Analytical half length for a plane strain griffith crack propagating in an infinite elastic medium Dahi taleghani thesis pg 130 "Analysis of hydraulic fracture propagation in fractured reservoirs: an improved model for the interaction between induced and natural fractures"

.PP
Toughness Dominated Solution: Garagash 2007 - Plane Strain propagation of \fBFracture\fP Durign injection and shut in: Asymptotics of large toughness\&. Small Viscosity Solution: Garagash 2007 - Plane Strain propagation of \fBFracture\fP Durign injection and shut in: Asymptotics of large toughness\&.

.PP
Viscous-dominated solution: Garagash 2005 - Plane-Strain Propagation of a Fluid-Driven \fBFracture\fP: Small Toughness Solution Analytical solutions based on propagation regime
.SS "template<uint32_t dim> double \fBcsmp::Fracture\fP< dim >::AnalyticalLength (double t)"
Analytical half length for a plane strain griffith crack propagating in an infinite elastic medium Analytical solutions based on propagation regime
.SS "template<uint32_t dim> double \fBcsmp::Fracture\fP< dim >::AnalyticalPressure (double t, double x = \fR0\&.0\fP)"
Analytical fluid pressure are the wellbore for a plane strain griffith crack propagating in an infinite elastic medium Analytical solutions based on propagation regime
.SS "template<uint32_t dim> void \fBcsmp::Fracture\fP< dim >::AveragePropertyToMiddle (\fBIndex\fP property, std::vector< \fBInterFace\fP< dim > * > & interfaces)"

.PP
General method to split tip nodes along a predefined path specified by the boundary object\&. 
.PP
\fBAuthor\fP
.RS 4
E\&.Pezzulli 
.RE
.PP
\fBDate\fP
.RS 4
2020  Takes properties defined on the node or element of the outside and inside of interface, and averages them to the nodes/elements of the middle region, respectively\&.
.RE
.PP
This method preserves the flag of the side elements and requires the flag Outside and Inside to be the same 
.SS "template<uint32_t dim> double \fBcsmp::Fracture\fP< dim >::DimensionlessToughness ()"
Returns the dimensionless toughness using the scaling paramters youngs modulus, poisson ratio, critical stress intensity factor, viscosity and constant flux, for a plane-strain fracture propagating in an infinite medium 
.SS "template<uint32_t dim> std::map< \fBPoint\fP< dim >, \fBNode\fP< dim > * > \fBcsmp::Fracture\fP< dim >::NodeMap (\fBINTERFACE_SIDE\fP side)"
Initialises fracture tips : 1) Finds tip nods 2) Find boundary nodes 3) Get fracture length 4) Create \fBFractureTip\fP for each tip node 5) Set Current tip coordinate as old tip coord

.PP
Note: FractureTips are created thinking there is not a situation where they are created and have already propagated! Therefore they do not need old tip coord! Method to call when advancing time steps and need to tell \fBFracture\fP tips their current tip is now the tip at old time step 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
