.TH "csmp::FieldVariable< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FieldVariable< dim > \- \fBFieldVariable\fP class for accessing distributed variables in the model\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FieldVariable\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBSubdomainType\fP = \fBModelSubDomain\fP<dim, CELL>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldVariable\fP (\fBModel\fP< dim > &model, const std::string &variable_name)"
.br
.RI "Construct a new \fBFieldVariable\fP object\&. "
.ti -1c
.RI "\fBFieldVariable\fP (const \fBFieldVariable\fP &other)=default"
.br
.ti -1c
.RI "\fBFieldVariable\fP (\fBFieldVariable\fP &&other)=default"
.br
.ti -1c
.RI "\fBFieldVariable\fP & \fBoperator=\fP (const \fBFieldVariable\fP &other)=default"
.br
.ti -1c
.RI "\fBFieldVariable\fP & \fBoperator=\fP (\fBFieldVariable\fP &&other)=default"
.br
.ti -1c
.RI "template<typename T> void \fBStore\fP (const T &value)"
.br
.RI "Store a value in the variable\&. "
.ti -1c
.RI "template<typename T> void \fBRead\fP (T &value) const"
.br
.RI "Read a value from the variable\&. "
.ti -1c
.RI "void \fBStatus\fP (bool status)"
.br
.RI "Set the status flag for the variable\&. "
.ti -1c
.RI "template<typename T> \fBFieldVariable\fP & \fBoperator=\fP (const T &value)"
.br
.ti -1c
.RI "template<typename T> \fBFieldVariable\fP & \fBoperator+=\fP (const T &value)"
.br
.ti -1c
.RI "template<typename T> \fBFieldVariable\fP & \fBoperator\-=\fP (const T &value)"
.br
.ti -1c
.RI "template<typename T> \fBFieldVariable\fP & \fBoperator*=\fP (const T &value)"
.br
.ti -1c
.RI "template<typename T> \fBFieldVariable\fP & \fBoperator/=\fP (const T &value)"
.br
.ti -1c
.RI "template<typename T> auto \fBoperator+\fP (const T &other) const"
.br
.ti -1c
.RI "template<typename T> auto \fBoperator\-\fP (const T &other) const"
.br
.ti -1c
.RI "template<typename T> auto \fBoperator*\fP (const T &other) const"
.br
.ti -1c
.RI "template<typename T> auto \fBoperator/\fP (const T &other) const"
.br
.ti -1c
.RI "\fBFieldVariable\fP (\fBModel\fP< dim > &model, const std::string &subdomain_name, const std::string &var_name)"
.br
.RI "Constructor: binds to an existing variable in the model's property database\&. "
.ti -1c
.RI "\fBFieldVariable\fP (const \fBFieldVariable\fP &)=default"
.br
.RI "Defaulted copy constructor and assignment\&. "
.ti -1c
.RI "\fBFieldVariable\fP & \fBoperator=\fP (const \fBFieldVariable\fP &)=default"
.br
.ti -1c
.RI "\fBFieldVariable\fP & \fBoperator=\fP (const \fBScalarVariable\fP &s)"
.br
.RI "Assignment from scalar, vector, or tensor constants\&. "
.ti -1c
.RI "\fBFieldVariable\fP & \fBoperator=\fP (const \fBVectorVariable\fP< dim > &v)"
.br
.ti -1c
.RI "\fBFieldVariable\fP & \fBoperator=\fP (const \fBTensorVariable\fP< dim > &t)"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBFieldVariable\fP &other)"
.br
.ti -1c
.RI "void \fBSubtract\fP (const \fBFieldVariable\fP &other)"
.br
.ti -1c
.RI "void \fBMultiply\fP (const \fBFieldVariable\fP &other)"
.br
.ti -1c
.RI "void \fBDivide\fP (const \fBFieldVariable\fP &other)"
.br
.ti -1c
.RI "template<typename Var> void \fBAdd\fP (const Var &value)"
.br
.ti -1c
.RI "template<typename Var> void \fBSubtract\fP (const Var &value)"
.br
.ti -1c
.RI "template<typename Var> void \fBMultiply\fP (const Var &value)"
.br
.ti -1c
.RI "template<typename Var> void \fBDivide\fP (const Var &value)"
.br
.ti -1c
.RI "const \fBSubdomainType\fP & \fBSubdomain\fP () const"
.br
.RI "Access the associated subdomain\&. "
.ti -1c
.RI "const \fBIndex\fP & \fBVarKey\fP () const"
.br
.RI "Access the variable key (index) "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t dim>
.br
class csmp::FieldVariable< dim >"\fBFieldVariable\fP class for accessing distributed variables in the model\&. 

\fBFieldVariable\fP represents a handle to a distributed variable (scalar, vector, tensor) in the model\&.

.PP
This class provides a clean interface for accessing variables that are distributed across the model hierarchy (\fBModel\fP > \fBRegion\fP > \fBElement\fP > \fBNode\fP)\&. It uses the \fBPropertyDatabase\fP to look up variable indices and \fBLocalVariableStorage\fP for actual variable access\&.

.PP
The class supports expression templates and operator overloading for mathematical operations\&.

.PP
\fBTemplate Parameters\fP
.RS 4
\fIdim\fP The dimension of the model (2 or 3)
.RE
.PP
The \fBFieldVariable\fP provides access to variable values across a subdomain (e\&.g\&., \fBRegion\fP, \fBBoundary\fP) and supports arithmetic operations and expression templates\&.

.PP
\fBTemplate Parameters\fP
.RS 4
\fIdim\fP Spatial dimension 
.br
\fICELL\fP cell type used in the subdomain, i\&.e\&. \fBElement\fP for \fBRegion\fP, \fBFace\fP for \fBBoundary\fP and \fBInterFace\fP for \fBSplitBoundary\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<size_t dim> \fBcsmp::FieldVariable\fP< dim >::FieldVariable (\fBModel\fP< dim > & model, const std::string & variable_name)\fR [inline]\fP"

.PP
Construct a new \fBFieldVariable\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fImodel\fP Reference to the model containing the variable 
.br
\fIvariable_name\fP Name of the variable to access 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIstd::runtime_error\fP if variable doesn't exist in database 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<size_t dim> template<typename T> void \fBcsmp::FieldVariable\fP< dim >::Read (T & value) const\fR [inline]\fP"

.PP
Read a value from the variable\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of variable to read 
.RE
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The value to read into 
.RE
.PP

.SS "template<size_t dim> void \fBcsmp::FieldVariable\fP< dim >::Status (bool status)\fR [inline]\fP"

.PP
Set the status flag for the variable\&. 
.PP
\fBParameters\fP
.RS 4
\fIstatus\fP The status to set 
.RE
.PP

.SS "template<size_t dim> template<typename T> void \fBcsmp::FieldVariable\fP< dim >::Store (const T & value)\fR [inline]\fP"

.PP
Store a value in the variable\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of variable to store 
.RE
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The value to store 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
