.TH "csmp::RectangularGrid" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::RectangularGrid
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RectangleToCrossSectionConverter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRectangularGrid\fP (size_t n_cells_x, size_t n_cells_y)"
.br
.RI "specifies the dimensions of the target grid "
.ti -1c
.RI "void \fBProjectCellCentersToCrossSection\fP (const \fBPoint\fP< 3U > &lower_left, const \fBPoint\fP< 3U > &lower_right, const \fBPoint\fP< 3U > &upper_right, const \fBPoint\fP< 3U > &upper_left, std::vector< \fBPoint\fP< 3U > > &global_coordinates) const"
.br
.RI "transfers regular grid in local coordinates to a potentially distorted grid in physical space coordinates "
.ti -1c
.RI "void \fBWriteGridAsIntegerMatrix\fP (const char *gridfile) const"
.br
.RI "input for quadrilaterator "
.ti -1c
.RI "void \fBOut\fP (const char *file_name, const std::vector< \fBPoint\fP< 3U > > &cell_center_coordinates) const"
.br
.RI "writes the supplied cell center coordinates to a comma-delimited ascii file "
.in -1c
.SH "Detailed Description"
.PP 
Created to create a regular grid of points for the sampling of a geomodel\&. The points are numbered row by row from the top down to decreasing Y coordinates, \fBColumn\fP indices increase in the X direction\&. 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::RectangularGrid::Out (const char * file_name, const std::vector< \fBPoint\fP< 3U > > & cell_center_coordinates) const"

.PP
writes the supplied cell center coordinates to a comma-delimited ascii file Writes file with cell barycentre coordinates, preceded by element-id(number)\&.

.PP
The file format is

.PP
header line axes titles: region-name(string), region-id(number 0\&.\&.n-1), element-id(number 0\&.\&.n-1), x, y, z comma-seperated data\&.\&.\&. EOF

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP

.SS "void csmp::RectangularGrid::ProjectCellCentersToCrossSection (const \fBPoint\fP< 3U > & lower_left, const \fBPoint\fP< 3U > & lower_right, const \fBPoint\fP< 3U > & upper_right, const \fBPoint\fP< 3U > & upper_left, std::vector< \fBPoint\fP< 3U > > & global_coordinates) const"

.PP
transfers regular grid in local coordinates to a potentially distorted grid in physical space coordinates Transfers regular grid in local coordinates to a potentially distorted grid in physical space coordinates 
.SS "void csmp::RectangularGrid::WriteGridAsIntegerMatrix (const char * file_name) const"

.PP
input for quadrilaterator tab-delimited integer (0\&.\&.256) input for quadrilaterator 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
