.TH "csmp::Cell" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Cell \- vector of pairs of FE-type - \fBGridNode\fP pointer vectors  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MeshingTools\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< std::pair< \fBcsmp::CSMP_FEM_TYPE\fP, std::vector< \fBGridNode\fP * > > > \fBVector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
vector of pairs of FE-type - \fBGridNode\fP pointer vectors 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
