.TH "csmp::FiniteDifferenceGrid" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FiniteDifferenceGrid \- Two-dimensional regular grid with interpolation operations and an optional halo across which interpolation still works; can be used for grid-point in finite-element cell transport computations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FiniteDifferenceGrid\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFiniteDifferenceGrid\fP (const \fBFiniteDifferenceGrid\fP &\fBg\fP)"
.br
.ti -1c
.RI "\fBFiniteDifferenceGrid\fP (double x_dim, double y_dim, double xres, double yres, int32_t frame_width=0)"
.br
.ti -1c
.RI "\fBFiniteDifferenceGrid\fP (double x_min, double x_max, double y_min, double y_max, double xres, double yres, int32_t frame_width=0)"
.br
.ti -1c
.RI "void \fBInitialize\fP (double x_dim, double y_dim, double xres, double yres, int32_t frame_width=0)"
.br
.ti -1c
.RI "void \fBInitialize\fP (double x_min, double x_max, double y_min, double y_max, double xres, double yres, int32_t frame_width=0)"
.br
.ti -1c
.RI "\fBFiniteDifferenceGrid\fP & \fBoperator=\fP (const \fBFiniteDifferenceGrid\fP &\fBg\fP)"
.br
.ti -1c
.RI "\fBFiniteDifferenceGrid\fP & \fBoperator=\fP (double val)"
.br
.ti -1c
.RI "void \fBLinearInterpolateOnTo\fP (\fBFiniteDifferenceGrid\fP &grid) const"
.br
.ti -1c
.RI "double \fBInterpolateOutside\fP (double x, double y) const"
.br
.ti -1c
.RI "double \fBInterpolateWithin\fP (double &x, double &y) const"
.br
.ti -1c
.RI "double \fBExtrapolateTo\fP (double x, double y) const"
.br
.ti -1c
.RI "double \fBoperator()\fP (double x, double y, bool rounded=false) const"
.br
.ti -1c
.RI "double & \fBoperator()\fP (int32_t row, int32_t col)"
.br
.ti -1c
.RI "double \fBoperator()\fP (int32_t row, int32_t col) const"
.br
.ti -1c
.RI "double \fBValue\fP (int32_t row, int32_t col) const"
.br
.ti -1c
.RI "double & \fBN\fP (int32_t row, int32_t col)"
.br
.ti -1c
.RI "double & \fBS\fP (int32_t i, int32_t j)"
.br
.ti -1c
.RI "double & \fBE\fP (int32_t i, int32_t j)"
.br
.ti -1c
.RI "double & \fBW\fP (int32_t i, int32_t j)"
.br
.ti -1c
.RI "double & \fBNW\fP (int32_t i, int32_t j)"
.br
.ti -1c
.RI "double & \fBNE\fP (int32_t i, int32_t j)"
.br
.ti -1c
.RI "double & \fBSW\fP (int32_t i, int32_t j)"
.br
.ti -1c
.RI "double & \fBSE\fP (int32_t i, int32_t j)"
.br
.ti -1c
.RI "double \fBResolutionX\fP () const"
.br
.ti -1c
.RI "double \fBResolutionY\fP () const"
.br
.ti -1c
.RI "int32_t \fBRows\fP () const"
.br
.ti -1c
.RI "int32_t \fBColumns\fP () const"
.br
.ti -1c
.RI "bool \fBHasFrame\fP () const"
.br
.ti -1c
.RI "double \fBMinX\fP () const"
.br
.ti -1c
.RI "double \fBMinY\fP () const"
.br
.ti -1c
.RI "double \fBMinZ\fP () const"
.br
.ti -1c
.RI "double \fBMaxX\fP () const"
.br
.ti -1c
.RI "double \fBMaxY\fP () const"
.br
.ti -1c
.RI "double \fBMaxZ\fP () const"
.br
.ti -1c
.RI "void \fBDataMinMax\fP (double &dmin, double &dmax, bool incl_frame=false) const"
.br
.ti -1c
.RI "void \fBDataMinMaxWithoutNAN\fP (double &dmin, double &dmax, bool incl_frame=false) const"
.br
.ti -1c
.RI "double \fBX\fP (int32_t i) const"
.br
.RI "returns x-coordinate for column c-style index 0\&.\&.\&.n "
.ti -1c
.RI "double \fBY\fP (int32_t j) const"
.br
.RI "returns x-coordinate for row c-style index 0\&.\&.\&.n "
.ti -1c
.RI "void \fBClosestGridPointTo\fP (double x, double y, int32_t &index_row, int32_t &index_col) const"
.br
.ti -1c
.RI "double \fBRowAverage\fP (int32_t row) const"
.br
.ti -1c
.RI "double \fBColumnAverage\fP (int32_t col) const"
.br
.ti -1c
.RI "void \fBScaleDataToRange\fP (double dmin, double dmax)"
.br
.RI "scales all grid data to range: dmin to dmax "
.ti -1c
.RI "bool \fBIsInitialized\fP () const"
.br
.ti -1c
.RI "void \fBSetRowTo\fP (int32_t row, double val)"
.br
.ti -1c
.RI "void \fBSetColumnTo\fP (int32_t col, double val)"
.br
.ti -1c
.RI "void \fBSetFirstNRowsTo\fP (int32_t n, double val)"
.br
.ti -1c
.RI "void \fBSetLastNRowsTo\fP (int32_t n, double val)"
.br
.ti -1c
.RI "void \fBSetRegionTo\fP (double xmin, double xmax, double ymin, double ymax, double val)"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP (const char *fname, int32_t tstep=0, bool with_frame=false) const"
.br
.ti -1c
.RI "bool \fBBinaryOut\fP (const char *bin_name, int32_t tstep=0, bool with_frame=false) const"
.br
.ti -1c
.RI "bool \fBIn\fP (const char *fname)"
.br
.ti -1c
.RI "bool \fBBinaryIn\fP (const char *fname)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Two-dimensional regular grid with interpolation operations and an optional halo across which interpolation still works; can be used for grid-point in finite-element cell transport computations\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 
.RE
.PP
\fBDate\fP
.RS 4
28/7/97
.RE
.PP
\fBFiniteDifferenceGrid\fP class implements a regular grid i {0,i_max-1} corresponding to the horizontal coordinate direction and j {0,j_max-1} corresponding to the vertical coordinate direction\&. Thus i=columns, j=rows\&. an operator(x,y) is provided to interpolate values within the grid domain\&. \fBX()\fP, \fBY()\fP give x and y values corresponding to column and row indices of the regular grid, respectively\&. Val(i,j) is used to input and output values at the exact grid locations indicated by i(column=x) and j(row=y)\&. 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::FiniteDifferenceGrid::ClosestGridPointTo (double x, double y, int32_t & row, int32_t & col) const"
Computes the grid indices (i{0,n-1}, j{0\&.\&.m-1}) of the grid point (x,y) that is located the closest to the entered point

.PP
NB: i,j are NOT numbered in the usual matrix sense
.IP "\(bu" 2
i refers to x-coordinate direction
.IP "\(bu" 2
j refers to y-coordinate direction 
.PP

.SS "double csmp::FiniteDifferenceGrid::ExtrapolateTo (double x, double y) const"
given the point x,y outside of the grid use linear interpolation of the values at the grid boundary to find the property value outside the grid\&. The point which is extrapolated must be in the first square outside the grid\&.

.PP
A third order polynomial extrapolation is used which performs well if the grid variable varies smoothly and monotonous\&. 
.SS "double csmp::FiniteDifferenceGrid::InterpolateWithin (double & x, double & y) const"
Interpolates strictly within the confines of the grid: If y is smaller than the minimum of the y-range value is interpolated on the horizontal model boundary x is set to the smallest x value\&. Then the desired value is interpolated along the grid boundary between the marginal 2 points\&. 
.SS "void csmp::FiniteDifferenceGrid::LinearInterpolateOnTo (\fBFiniteDifferenceGrid\fP & grid2) const"
interpolates its values on the target grid where the two grids overlap, elsewhere, the target grid is left untouched\&. Only the area inside the frame is considered\&. 
.SS "double csmp::FiniteDifferenceGrid::operator() (double x, double y, bool rounded = \fRfalse\fP) const"
outputs interpolated value of grid-point at the location x,y in the domain of the regular grid 0\&.0\&.\&.\&.x_max, 0\&.0\&.\&.\&.y_max\&. NB: if the queried x,y coordinates lie outside of the grid, operator(x,y) returns the closest value on the grid\&. It does not give a warning\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
