.TH "csmp::FlaggedArrayVariable" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FlaggedArrayVariable \- Storage for an arbitrary number of variables and flags with a size that is not predefined but can be determined at runtime\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FlaggedArrayVariable\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< double > \fBFlaggedArrayContainer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlaggedArrayVariable\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBFlaggedArrayVariable\fP (const \fBFlaggedArrayVariable\fP &)"
.br
.ti -1c
.RI "template<uint32_t dim> \fBFlaggedArrayVariable\fP (const char *arrayPropertyName, const \fBPropertyDatabase\fP< dim > &pd, double defaultValue=std::numeric_limits< double >::quiet_NaN(), \fBVARIABLE_FLAG\fP flag=\fBANY\fP)"
.br
.RI "Automatically sets size to corresponding index, flag to ANY\&. "
.ti -1c
.RI "\fBFlaggedArrayVariable\fP (uint32_t arraySize, double defaultValue=0\&., \fBVARIABLE_FLAG\fP flag=\fBANY\fP)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP (const \fBIndex\fP &arrayKey, double defaultValue=0\&., \fBVARIABLE_FLAG\fP flag=\fBANY\fP)"
.br
.RI "As \fBPropertyDatabase\fP constructor, but using index right away\&. "
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator=\fP (const \fBFlaggedArrayVariable\fP &)"
.br
.RI "assignments "
.ti -1c
.RI "void \fBCopyValuesOnly\fP (\fBArrayVariable\fP &av)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator=\fP (double)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator+\fP (double) const"
.br
.RI "standard operations "
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator\-\fP (double) const"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator*\fP (double) const"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator/\fP (double) const"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator^\fP (double) const"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator+=\fP (double)"
.br
.RI "Standard Operations with current object\&. "
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator\-=\fP (double)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator*=\fP (double)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator/=\fP (double)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator+=\fP (const \fBScalarVariable\fP &)"
.br
.RI "Standard Operations with current object\&. "
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator\-=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator*=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator/=\fP (const \fBScalarVariable\fP &)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator+=\fP (const \fBFlaggedArrayVariable\fP &)"
.br
.RI "value by value operations "
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator\-=\fP (const \fBFlaggedArrayVariable\fP &)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator*=\fP (const \fBFlaggedArrayVariable\fP &)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP & \fBoperator/=\fP (const \fBFlaggedArrayVariable\fP &)"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator\-\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.RI "element-by-element operations "
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator*\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator+\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.ti -1c
.RI "\fBFlaggedArrayVariable\fP \fBoperator/\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.RI "arithmetical comparison of array values "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBFlaggedArrayVariable\fP &) const"
.br
.ti -1c
.RI "double \fBoperator[]\fP (size_t) const"
.br
.RI "accessors to the data "
.ti -1c
.RI "double & \fBoperator()\fP (size_t)"
.br
.ti -1c
.RI "void \fBComponent\fP (uint32_t, double)"
.br
.ti -1c
.RI "double \fBComponent\fP (uint32_t) const"
.br
.ti -1c
.RI "uint32_t \fBSize\fP () const"
.br
.ti -1c
.RI "void \fBResize\fP (uint32_t newSize, double newValue=std::numeric_limits< double >::quiet_NaN())"
.br
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBFlag\fP (const size_t &) const"
.br
.ti -1c
.RI "\fBVARIABLE_FLAG\fP & \fBFlag\fP (const size_t &)"
.br
.ti -1c
.RI "void \fBFlag\fP (const size_t &, \fBVARIABLE_FLAG\fP)"
.br
.ti -1c
.RI "bool \fBIsWithinRange\fP (double min, double max) const"
.br
.ti -1c
.RI "bool \fBHas_NaN_Values\fP () const"
.br
.ti -1c
.RI "void \fBMinMax\fP (double &min, double &max) const"
.br
.RI "returns the minimum and maximum of the values stored in the array variable "
.ti -1c
.RI "void \fBSort\fP ()"
.br
.ti -1c
.RI "void \fBOut\fP (long digits=3) const"
.br
.RI "printing array values to screen "
.ti -1c
.RI "bool \fBOut\fP (const char *filename, size_t precision=9) const"
.br
.ti -1c
.RI "bool \fBOut\fP (std::fstream &fp) const"
.br
.RI "SKM: DO NOT USE C-STYLE I/O - for internal csmp binary IO\&. "
.ti -1c
.RI "bool \fBIn\fP (std::fstream &fp)"
.br
.RI "Reads the array from given file pointer (binary format) "
.ti -1c
.RI "FlaggedArrayContainer::const_iterator \fBBegin\fP () const"
.br
.ti -1c
.RI "FlaggedArrayContainer::const_iterator \fBEnd\fP () const"
.br
.ti -1c
.RI "double \fBNextLargestEntry\fP (double) const"
.br
.ti -1c
.RI "bool \fBHasLargerEntry\fP (double) const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr \fBVARIABLE_TYPE\fP \fBVariableType\fP = FLAGGEDARRAY"
.br
.in -1c
.SH "Detailed Description"
.PP 
Storage for an arbitrary number of variables and flags with a size that is not predefined but can be determined at runtime\&. 


.PP
\fBAuthor\fP
.RS 4
Roman Manasipov, Philipp Lang 
.RE
.PP
\fBDate\fP
.RS 4
2013
.RE
.PP
In order to support arbitrary sized variables to be discretized in CSMP\&. Based on implementation of \fBArrayVariable\fP by Philipp Lang but has additional container of flags for each data component
.SH "Usage"
.PP
To instantiate an \fBFlaggedArrayVariable\fP of arbitrary size:

.PP
.PP
.nf
FlaggedArrayVariable fav;                  // 0 entries, flag set to Any
FlaggedArrayVariable fav(4, 10\&., DIRICH ); // 4 entries with value 10\&., flag set to Dirichlet
.fi
.PP

.PP
When using \fBFlaggedArrayVariable\fP in Store/Read operations, we need to first create an instance of appropriate size, i\&.e\&. the same size as provided in the \fBPropertyDatabase\fP\&. A constructor which does exactly this:

.PP
.PP
.nf
FlaggedArrayVariable fav( "element array", model\&.Database() ); // size as specified in PropertyDatabase, values = 0\&., flag = any
.fi
.PP

.PP
Again, the alternative would be to manually initiate the correct size\&. With an \fBFlaggedArrayVariable\fP of appropriate size, you may use functions like

.PP
.PP
.nf
model\&.InputPropertyValue( "element flagged array", fav );
.fi
.PP

.PP
Or something low level in the likes of

.PP
.PP
.nf
Index efaKey( model\&.Database()\&.StorageKey("element flagged array") );
for( vector<Element<3>*>::const_iterator it( model\&.Region("Model")\&.CellsBegin() ); it != model\&.Region("Model")\&.CellsEnd(); ++it )
  (*it)\->Read( efaKey, fav );
.fi
.PP

.PP
\fBFlaggedArrayVariable\fP operations are possible as defined through the interface 
.SH "Member Function Documentation"
.PP 
.SS "bool csmp::FlaggedArrayVariable::In (std::fstream & fp)"

.PP
Reads the array from given file pointer (binary format) See bool \fBFlaggedArrayVariable::Out( std::fstream& fp ) const\fP

.PP
\fBParameters\fP
.RS 4
\fIfp\fP If non-null, the fp\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if it succeeds, false if it fails\&. 
.RE
.PP

.SS "\fBFlaggedArrayVariable\fP csmp::FlaggedArrayVariable::operator+ (double val) const"

.PP
standard operations Standard Operations with temporary object\&. 
.SS "\fBFlaggedArrayVariable\fP & csmp::FlaggedArrayVariable::operator+= (const \fBFlaggedArrayVariable\fP & av)"

.PP
value by value operations Operations with FlaggedArrayVariables\&. 
.SS "\fBFlaggedArrayVariable\fP & csmp::FlaggedArrayVariable::operator+= (const \fBScalarVariable\fP & sc)"

.PP
Standard Operations with current object\&. Operations with ScalarVariables 
.SS "void csmp::FlaggedArrayVariable::Out (long digits = \fR3\fP) const"

.PP
printing array values to screen outputs values to screen up to 10 values per row 
.SS "bool csmp::FlaggedArrayVariable::Out (std::fstream & fp) const"

.PP
SKM: DO NOT USE C-STYLE I/O - for internal csmp binary IO\&. Outs the array to given file pointer (binary format)

.PP
Order:
.IP "1." 4
Flag
.IP "2." 4
Size
.IP "3." 4
Data
.PP

.PP
Roman, 2013: Changed order due to multiple flags:
.IP "1." 4
Size
.IP "2." 4
Flags
.IP "3." 4
Data
.PP

.PP
\fBAuthor\fP
.RS 4
P\&. Lang 
.RE
.PP
\fBDate\fP
.RS 4
9/28/2012
.RE
.PP
\fBParameters\fP
.RS 4
\fIfp\fP If non-null, the fp\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if it succeeds, false if it fails\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
