.TH "csmp::VariableTypeTraits< dim, SCALAR >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::VariableTypeTraits< dim, SCALAR >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef double \fBReturnType\fP"
.br
.ti -1c
.RI "typedef \fBScalarVariable\fP \fBVariableType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
