.TH "csmp::Fluid< dim, USER >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Fluid< dim, USER >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Fluid\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFluid\fP ()"
.br
.RI "default constructor that tests the phase-state key "
.ti -1c
.RI "double \fBViscosity\fP (\fBNode\fP< dim > *const, uint32_t phase) const"
.br
.RI "the node property fluid viscosity (Pa\&.s) returned has been interpolated to the user-specified target placement (argument parameter) "
.ti -1c
.RI "double \fBViscosity\fP (\fBElement\fP< dim > *const, uint32_t phase) const"
.br
.RI "the node property fluid viscosity (Pa\&.s) interpolated to element barycentre "
.ti -1c
.RI "double \fBViscosity\fP (\fBElement\fP< dim > *const, uint32_t node, uint32_t phase) const"
.br
.RI "the node property fluid viscosity (Pa\&.s) at the node i of the element "
.ti -1c
.RI "double \fBDensity\fP (\fBNode\fP< dim > *const, uint32_t phase) const"
.br
.RI "the returned node property fluid density (of phase) (kg/m3) interpolated to the user-specified target placement (argument parameter) "
.ti -1c
.RI "double \fBDensity\fP (\fBElement\fP< dim > *const, uint32_t phase) const"
.br
.ti -1c
.RI "double \fBDensity\fP (\fBElement\fP< dim > *const, uint32_t node, uint32_t phase) const"
.br
.ti -1c
.RI "double \fBMixtureDensity\fP (\fBNode\fP< dim > *const) const"
.br
.RI "returns saturation-weighted density average (kg/m3) for the fluid mixture; properties are interpolated to the target placement "
.ti -1c
.RI "double \fBMixtureDensity\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBMixtureDensity\fP (\fBElement\fP< dim > *const, uint32_t node) const"
.br
.ti -1c
.RI "double \fBViscosityRatio\fP (\fBNode\fP< dim > *const) const"
.br
.RI "returns the ratio of the phase viscosities at the target placement "
.ti -1c
.RI "double \fBViscosityRatio\fP (\fBElement\fP< dim > *const) const"
.br
.ti -1c
.RI "double \fBViscosityRatio\fP (\fBElement\fP< dim > *const, uint32_t node) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "USER< dim > * \fBUser\fP ()"
.br
.RI "shorthand for accessing the class that FacetFlux_TracerTransferExplicit is a policy of "
.ti -1c
.RI "USER< dim > const * \fBUser\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class USER>
.br
class csmp::Fluid< dim, USER >"Blueprint for any specific \fBFluid\fP property class to be used in the generic transport scheme\&. This generic one is not associated with any particular equation of state, but derived ones in this implementation of static polymorphism may well be\&.

.PP
When properties are requested for the element, the methods of the class performs a smart interpolation of fluid properties dependent on their existance as indicated by the phase state\&. Else,the method just reads the properties from the model\&.

.PP
\fBAttention\fP
.RS 4
the fluid properties must be initialised elsewhere by an equation of state\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::Fluid\fP< dim, USER >::ViscosityRatio (\fBNode\fP< dim > * const n) const"

.PP
returns the ratio of the phase viscosities at the target placement aqueous phase viscosity / carbonic phase viscosity 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
