.TH "csmp::SteadyStateDiffusionProfile< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SteadyStateDiffusionProfile< dim >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcsmp::SAMG_Profile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteadyStateDiffusionProfile\fP (\fBModel\fP< dim > &model, const char *diffusivity, const char *diffusingVariable, const char *spatialSourceVariable)"
.br
.ti -1c
.RI "\fBSteadyStateDiffusionProfile\fP (\fBModel\fP< dim > &model, const char *diffusivity, const char *diffusingVariable, const char *spatialSourceVariable, const char *gradientVariable, double gradient_multiplier)"
.br
.ti -1c
.RI "virtual bool \fBSolve\fP (double modelTime)"
.br
.RI "Solve for steadystate pressure diffusion\&. "
.ti -1c
.RI "\fBSteadyStateDiffusor\fP< dim, \fBElement\fP > & \fBSolver\fP ()"
.br
.RI "bridging to solver "
.in -1c

Public Member Functions inherited from \fBcsmp::SAMG_Profile\fP
.in +1c
.ti -1c
.RI "std::string \fBFileDumpName\fP () const"
.br
.ti -1c
.RI "void \fBFileDumpName\fP (const std::string &dumpFileName)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::SAMG_Profile\fP
.in +1c
.ti -1c
.RI "std::string \fBdumpFileName_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::SteadyStateDiffusionProfile\fP< dim >::SteadyStateDiffusionProfile (\fBModel\fP< dim > & model, const char * diffusivity, const char * diffusingVariable, const char * spatialSourceVariable)"
Adjust SAMG Settings
.SS "template<uint32_t dim> \fBcsmp::SteadyStateDiffusionProfile\fP< dim >::SteadyStateDiffusionProfile (\fBModel\fP< dim > & model, const char * diffusivity, const char * diffusingVariable, const char * spatialSourceVariable, const char * gradientVariable, double gradient_multiplier)"
Adjust SAMG Settings
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> bool \fBcsmp::SteadyStateDiffusionProfile\fP< dim >::Solve (double modelTime)\fR [virtual]\fP"

.PP
Solve for steadystate pressure diffusion\&. Reconfiguration of SAMG solver settings after completing first solver call
.SH "Input Arguments"
.PP
Under provision of a separate SAMG instance (SAMG_MULTIPLE_INSTANCES) or applicaton of the IMPES solution scheme the below defined SAMG input parameters are re-adjusted to gain additional solver performance\&.

.PP
.IP "\(bu" 2
SAMG input parameters reconfigured after first SAMG solver call:
.PP
.IP "1." 4
Provide solution of the previous time step as initial guess -> Set_itypu
.IP "2." 4
Reuse SAMG solver setup if not initialized in automatic mode Set_iswit(7)
.IP "3." 4
Change absolute convergence criterion -> Set_eps() or
.IP "4." 4
Switch to relative convergence criterion -> Set_eps()
.PP

.PP
The gained functionality concerns SAMG input arguments that are required to be set in a different way at the initial solver call\&. The if-loop "firstCall_" has been implemented to cater for changed SAMG solver settings after the solver routine has been called for the first time\&. Changed settings take effect with the second call of the the SAMG solver instance\&.

.PP
ad 1\&. For faster numeric convergence SAMG settings can be changed in order to provide the result of the previous solver call as initial guess\&. The setting (Set_itypu(0) has to be called succeeding an initial solver call\&.

.PP
ad 2\&. Handling the SAMG solver memory is done in a similar manner: The coarsening setup created at the initial solver call is kept in the memory with any setting other than Set_iswit(5)\&. Subsequent calls shall reuse the setup\&.

.PP
Manual (no primary solver control) setup refresh check, iswit(4) is adjusted immediately after the first SAMG solver call as seen below to iswit(3)\&. In the event of exceeding a defined benchmark of iteration cycles in \fBSAMG_Solver::CheckCycleCriterion\fP a new setup will be forced in the upcoming solver call\&. Since the paramter iswit remains unchanged, the new setup is reused from the following solver calls until the criterion is failed again\&. The benchmark case is set within the firstCall_ sequence as well\&.

.PP
Automatic primary solver control performs setup refresh check (convegence control, \&.\&.\&.) with iswit(7) which corresponds iswit(3) functionality\&. Whenever possible and reasonable, SAMG runs with partial setup\&. Otherwise, SAMG makes a full setup\&. In contrast to this, the automatic control does not assume a full hierarchy to be available from a previous run\&. If no setup is available, SAMG will automatically perform a fresh setup\&.

.PP
ad 3\&. After the first solution has converged with an absolut convergence set to the round-off error, a less strict convergence criterion, either absolute or residual, is subsequently used as stopping criterion\&. Absolute convergence is defined by "res <= eps"\&.

.PP
ad\&.4 Relative convergence is defined by "res <= eps\&.res0" (res0 = starting residual)\&. SAMG output to file

.PP
Solve
.PP
Implements \fBcsmp::SAMG_Profile\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
