.TH "csmp::CRC3_RockType2" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::CRC3_RockType2 \- Planar bedding mudstone - silt\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <OtwayCRC3_RockTypes_Version_2\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsComposite\fP () const"
.br
.ti -1c
.RI "double \fBKrw_ParallelDrainage\fP (double Sw) const"
.br
.RI "\fBWater\fP relative permeability (CL) "
.ti -1c
.RI "double \fBKrn_ParallelDrainage\fP (double Sw) const"
.br
.RI "CO2 relative permeability: "
.ti -1c
.RI "double \fBKrw_CrossDrainage\fP (double Sw) const"
.br
.RI "\fBWater\fP relative permeability (CL) "
.ti -1c
.RI "double \fBKrn_CrossDrainage\fP (double Sw) const"
.br
.RI "CO2 relative permeability: "
.ti -1c
.RI "bool \fBIsComposite\fP () const"
.br
.ti -1c
.RI "double \fBKrw_ParallelDrainage\fP (double Sw) const"
.br
.RI "\fBWater\fP relative permeability (CL) "
.ti -1c
.RI "double \fBKrn_ParallelDrainage\fP (double Sw) const"
.br
.RI "CO2 relative permeability: "
.ti -1c
.RI "double \fBKrw_CrossDrainage\fP (double Sw) const"
.br
.RI "\fBWater\fP relative permeability (CL) "
.ti -1c
.RI "double \fBKrn_CrossDrainage\fP (double Sw) const"
.br
.RI "CO2 relative permeability: "
.ti -1c
.RI "bool \fBIsComposite\fP () const"
.br
.ti -1c
.RI "double \fBKrw_ParallelDrainage\fP (double Sw) const"
.br
.RI "\fBWater\fP relative permeability (CL) "
.ti -1c
.RI "double \fBKrn_ParallelDrainage\fP (double Sw) const"
.br
.RI "CO2 relative permeability: "
.ti -1c
.RI "double \fBKrw_CrossDrainage\fP (double Sw) const"
.br
.RI "\fBWater\fP relative permeability (CL) "
.ti -1c
.RI "double \fBKrn_CrossDrainage\fP (double Sw) const"
.br
.RI "CO2 relative permeability: "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::string \fBname\fP = 'M\-CbSst\-Mst'"
.br
.ti -1c
.RI "const int \fBrocktype_\fP = 2"
.br
.ti -1c
.RI "const int \fBsubtypes_\fP = 1"
.br
.ti -1c
.RI "const double \fBk_low_\fP = 1\&.539564e\-15"
.br
.ti -1c
.RI "const double \fBk_high_\fP = 1\&.727075e\-15"
.br
.ti -1c
.RI "const double \fBk_\fP = k_low_ + k_high_ / 2\&."
.br
.ti -1c
.RI "const double \fBphi_\fP = 0\&.176"
.br
.ti -1c
.RI "const double \fBLY_low_\fP = 0\&.025"
.br
.ti -1c
.RI "const double \fBLY_high_\fP = 0\&.025"
.br
.ti -1c
.RI "const double \fBSwi_low_\fP = 0\&.552"
.br
.ti -1c
.RI "const double \fBSwi_high_\fP = 0\&.39"
.br
.ti -1c
.RI "const double \fBSwi_pc_\fP = 0\&.472"
.br
.ti -1c
.RI "const double \fBSgr_\fP = 0\&.288"
.br
.ti -1c
.RI "const double \fBm_low_\fP = 0\&.4"
.br
.ti -1c
.RI "const double \fBm_high_\fP = 0\&.4"
.br
.ti -1c
.RI "const double \fBm_\fP = 0\&.4"
.br
.ti -1c
.RI "const double \fBpd_low_\fP = 10000\&."
.br
.ti -1c
.RI "const double \fBpd_high_\fP = 5000\&."
.br
.ti -1c
.RI "const double \fBpd_\fP = 5000\&."
.br
.ti -1c
.RI "const double \fBdPc_\fP = 5000\&."
.br
.ti -1c
.RI "const double \fBSwi_\fP = 0\&.472"
.br
.ti -1c
.RI "const double \fBm_ave_\fP = 0\&.427"
.br
.in -1c
.SH "Detailed Description"
.PP 
Planar bedding mudstone - silt\&. 

Massive bedding: Carbonate-cemented Sandstone - Mudstone

.PP
\fBAttention\fP
.RS 4
SKM: difference of relperms for vertical flow is ignored here because it is so small\&. 
.PP
.nf
  @TODO this should be made a composite to honour different end-point krn for horizontal and vertical

.fi
.PP
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
