.TH "csmp::TypeMatchesFEM_IP_Placement< T, IT >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TypeMatchesFEM_IP_Placement< T, IT > \- For variables placed on the integration points (Gauss quadrature points) of \fBElement\fP, \fBFace\fP or \fBInterFace\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <enumTypeCompatibilityChecks\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBvalue\fP = false }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<template< uint32_t > class T, \fBPLACEMENT\fP IT>
.br
struct csmp::TypeMatchesFEM_IP_Placement< T, IT >"For variables placed on the integration points (Gauss quadrature points) of \fBElement\fP, \fBFace\fP or \fBInterFace\fP objects\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
