.TH "csmp::SplitBoundaryPressureDiffusion_Test" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SplitBoundaryPressureDiffusion_Test
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SplitBoundaryPressureDiffusion_Test\&.h>\fP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplitBoundaryPressureDiffusion_Test\fP (const char *test_model='box_with_wavy_fracture', const char *test_variables='SplitBoundaryPressureDiffusion_Test\-variables\&.txt')"
.br
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests diffusive pressure transfer between a wavy fracture and the rock matrix employing Robin boundary conditions and a coupling coefficient that is based on the 1D analytic solution to the transient diffusion problem\&. 
.SH "Member Function Documentation"
.PP 
.SS "void csmp::SplitBoundaryPressureDiffusion_Test::run ()\fR [virtual]\fP"

.PP
\fBTodo\fP
.RS 4
influx surface integral: \fBNumIntegral_NT_op_N_dS<2U>\fP influx( model\&.Database(), "influx", "fluid pressure" ); 
.RE
.PP

.PP
Implements \fBcsmp::Test\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
