.TH "csmp::ModelTopology" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ModelTopology
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ModelTopology\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelTopology\fP (bool isoparametric_element_mesh=false)"
.br
.ti -1c
.RI "\fBModelTopology\fP (const char *model_name, bool isoparametric_element_mesh)"
.br
.ti -1c
.RI "\fBModelTopology\fP (const \fBModelTopology\fP &mt)"
.br
.ti -1c
.RI "\fBModelTopology\fP & \fBoperator=\fP (const \fBModelTopology\fP &mt)"
.br
.ti -1c
.RI "void \fBModelName\fP (const char *name)"
.br
.RI "general model info "
.ti -1c
.RI "std::string \fBModelName\fP () const"
.br
.ti -1c
.RI "size_t \fBModelDomains\fP () const"
.br
.ti -1c
.RI "bool \fBLineModel\fP () const"
.br
.RI "model shape and spatial dimension "
.ti -1c
.RI "bool \fBSurfaceModel\fP () const"
.br
.ti -1c
.RI "bool \fBSolidModel\fP () const"
.br
.ti -1c
.RI "size_t \fBMinimumSpatialDimensionOfDomain\fP (const char *region) const"
.br
.ti -1c
.RI "bool \fBIsoparametricFiniteElements\fP () const"
.br
.RI "type of elements "
.ti -1c
.RI "void \fBUseIsoparametricFiniteElementTypes\fP ()"
.br
.ti -1c
.RI "size_t \fBInterpolationOrder\fP () const"
.br
.RI "FEM interpolation function properties\&. "
.ti -1c
.RI "bool \fBLinearElementMesh\fP () const"
.br
.ti -1c
.RI "bool \fBQuadraticElementMesh\fP () const"
.br
.ti -1c
.RI "size_t \fBFiniteElementTypes\fP (std::set< std::string > &etypes) const"
.br
.RI "return total number and CSMP names of FE-types in the model "
.ti -1c
.RI "size_t \fBFiniteElementTypes\fP (std::set< int32_t > &etypes) const"
.br
.ti -1c
.RI "void \fBChangeCellType\fP (const std::string &old_cell_type, std::string new_cell_type_same_as_enum_names)"
.br
.RI "changes the finite - element type associated with a particular region; see \fBFiniteElement\&.h\fP for available types "
.ti -1c
.RI "void \fBEliminateCellType\fP (const char *etype)"
.br
.ti -1c
.RI "void \fBEliminateCellTypes\fP (const std::list< std::string > &etypes)"
.br
.ti -1c
.RI "void \fBEliminateLineCells\fP ()"
.br
.RI "remove all curves "
.ti -1c
.RI "void \fBEliminateSurfaceCells\fP ()"
.br
.RI "remove all surfaces "
.ti -1c
.RI "void \fBEliminateVolumeCells\fP ()"
.br
.RI "remove all volumetric elements from a model "
.ti -1c
.RI "size_t \fBCells\fP () const"
.br
.RI "manipulation with elements within region "
.ti -1c
.RI "void \fBCells\fP (std::set< size_t > &elmt_ids) const"
.br
.ti -1c
.RI "size_t \fBCellsWithinDomain\fP (const char *region) const"
.br
.ti -1c
.RI "std::vector< size_t >::const_iterator \fBCellsOfDomainBegin\fP (const char *region) const"
.br
.ti -1c
.RI "std::vector< size_t >::const_iterator \fBCellsOfDomainEnd\fP (const char *region) const"
.br
.ti -1c
.RI "void \fBCellTypesOfDomain\fP (const char *region, std::set< std::string > &etypes) const"
.br
.ti -1c
.RI "bool \fBIsWithinDomain\fP (const char *region, size_t elmt_id) const"
.br
.ti -1c
.RI "void \fBExportSelectionTo\fP (const std::list< std::string > &regions, \fBModelTopology\fP &mt) const"
.br
.ti -1c
.RI "void \fBOutputAll\fP (std::list< std::string > &regions) const"
.br
.RI "lists all the contained subdomains (regions, boundaries and splitboundaries "
.ti -1c
.RI "void \fBOutputRegions\fP (std::list< std::string > &regions) const"
.br
.ti -1c
.RI "void \fBOutputBoundaries\fP (std::list< std::string > &regions) const"
.br
.ti -1c
.RI "void \fBOutputSplitBoundaries\fP (std::list< std::string > &regions) const"
.br
.ti -1c
.RI "bool \fBContains\fP (const char *region) const"
.br
.RI "check whether region is alreday included "
.ti -1c
.RI "void \fBErase\fP ()"
.br
.RI "remove certain regions "
.ti -1c
.RI "void \fBRemoveDomains\fP (const std::set< std::string > &regions)"
.br
.ti -1c
.RI "void \fBRemoveDomain\fP (const char *name)"
.br
.ti -1c
.RI "void \fBRemoveEmptyDomains\fP ()"
.br
.ti -1c
.RI "void \fBReduceToDomains\fP (const char *regions_file)"
.br
.RI "eliminate all model regions other than the ones specified in '*-regions\&.txt' file "
.ti -1c
.RI "void \fBReduceToDomains\fP (const std::set< std::string > &regions)"
.br
.ti -1c
.RI "bool \fBAddDomain\fP (const char *rname, const std::set< std::string > &fem_types, const std::vector< size_t > &elms)"
.br
.RI "add new regions "
.ti -1c
.RI "void \fBAddDomainCellType\fP (const char *rname, const std::string &fem_types)"
.br
.RI "if the region only consists of a single element type, choose this method to add it (enums and strings are defined in \fBFiniteElement\&.h\fP) "
.ti -1c
.RI "void \fBAddDomainCellTypes\fP (const char *rname, const std::set< std::string > &fem_types)"
.br
.RI "add element types for regions that consist of multiple ones (enums and strings are defined in \fBFiniteElement\&.h\fP) "
.ti -1c
.RI "void \fBAddDomainCellId\fP (const char *rname, size_t elm)"
.br
.RI "element IDs range from 0\&.\&.n-1 "
.ti -1c
.RI "void \fBAddDomainCellIds\fP (const char *rname, const std::vector< size_t > &elms)"
.br
.ti -1c
.RI "bool \fBAddDomains\fP (const std::map< std::string, std::pair< std::set< std::string >, std::vector< size_t > > > &unique_regions)"
.br
.RI "adds unique (non-overlapping) regions to topology, using the name, element types and element indices supplied "
.ti -1c
.RI "bool \fBAddDomains\fP (const std::multimap< std::string, std::string > &object_specs, const std::multimap< std::string, std::vector< size_t > > &object_elements)"
.br
.RI "adds unique (non-overlapping) regions to topology, using the region specifications (name and element types) and element index lists supplied "
.ti -1c
.RI "bool \fBAddDomainsWithEquidimensionalCheck\fP (const std::multimap< std::string, std::string > &object_specs, const std::multimap< std::string, std::vector< size_t > > &object_elements)"
.br
.RI "adds regions to topology, eliminating lower-dimensional regions with the same name as the ones with the same dimension as the model "
.ti -1c
.RI "template<uint32_t dim> void \fBRemoveLowDimCellsFromDomains\fP (\fBcsmp::VSet\fP< dim > &vset)"
.br
.ti -1c
.RI "void \fBDomainNames\fP (std::vector< std::string > &) const"
.br
.RI "region, boundary or split boundary names "
.ti -1c
.RI "bool \fBChangeDomainName\fP (const std::string &old_name, const std::string &new_name)"
.br
.RI "changes the name of a domain in the most efficient way; reports whether operation was successful "
.ti -1c
.RI "void \fBPropertiesOfDomains\fP (const char *regions_file, std::list< std::string > &properties, std::map< std::string, std::list< double > > &props) const"
.br
.RI "properties of regions "
.ti -1c
.RI "template<uint32_t dim> bool \fBEstablishTopology\fP (\fBVSet\fP< dim > &vset, const std::multimap< std::string, std::string > &object_specs, const std::multimap< std::string, std::vector< size_t > > &object_elements, bool require_unique_names_for_vol_surf_lines=true, bool interactive_property_assignment=false, bool correct_orientation_of_surface_elements=false, bool reassign_boundary_flags=true)"
.br
.RI "initialises topology object and fixes pontentially wrong surface element orientations, non-consecutive numbering, orphan nodes, neighbor connectivity etc\&. "
.ti -1c
.RI "template<uint32_t dim> bool \fBEstablishTopology\fP (\fBVSet\fP< dim > &vset, bool require_unique_names_for_vol_surf_lines=true, bool correct_orientation_of_surface_elements=false, bool reassign_boundary_flags=true)"
.br
.RI "calls EstablishTopology with a reduced set of options "
.ti -1c
.RI "bool \fBRectangleShapedModel\fP () const"
.br
.RI "checks that 2D model contains the boundaries LEFT, RIGHT, BOTTOM, TOP "
.ti -1c
.RI "bool \fBBoxShapedModel\fP () const"
.br
.RI "checks that 3D model contains the boundaries LEFT, RIGHT, BOTTOM, FRONT, BACK; TOP omitted because it may be IRREGULAR "
.ti -1c
.RI "template<uint32_t dim> bool \fBAssignBoxShapedModelFlags\fP (\fBVSet\fP< dim > &) const"
.br
.RI "recreates the \fBBOX_BOUNDARY\fP node flags if a problem was detected "
.ti -1c
.RI "template<uint32_t dim> void \fBAssignMaterialProperties\fP (\fBVSet\fP< dim > &, const std::multimap< std::string, std::vector< size_t > > &object_elements)"
.br
.ti -1c
.RI "bool \fBCheckCellNumbering\fP () const"
.br
.ti -1c
.RI "void \fBCreateNewCellNumbers\fP (std::map< size_t, size_t > &old_to_new_mapping, bool check_output=true)"
.br
.RI "numbering / repair "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "output info "
.ti -1c
.RI "void \fBOut\fP (const char *output_file, const std::string header=std::string()) const"
.br
.ti -1c
.RI "bool \fBInputFromTextFile\fP (const char *file_dot_asc)"
.br
.RI "initialises \fBModelTopology\fP from text file as written by \fBOut()\fP "
.ti -1c
.RI "template<uint32_t dim> void \fBAssignMaterialProperties\fP (\fBVSet\fP< dim > &vset, const multimap< string, \fBvector\fP< size_t > > &object_elements)"
.br
.ti -1c
.RI "template<uint32_t dim> bool \fBEstablishTopology\fP (\fBVSet\fP< dim > &vset, const multimap< string, string > &object_specs, const multimap< string, \fBvector\fP< size_t > > &object_elements, bool require_unique_names_for_vol_surf_lines, bool interactive_property_assignment, bool correct_orientation_of_surface_elements, bool reassign_boundary_flags)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBModel\fP topology associates elements with regions and boundaries, recording their names, element types, and their dimensionality\&. This is important in model construction process\&. The \fBModelTopology\fP thus stores this "topologic" information, which cannot be stored in the \fBVSet\fP\&.

.PP
In CSMP regions are model subdomains, just as boundaries and split boundaries\&. All of these can be stored in the \fBModelTopology\fP\&. They are distinguished only by their names\&. Thus, a \fBBoundary\fP either contains the string BOUNDARY in its name or has one of the standard names for boundaries and or edges of box-shaped models (BOTTOM, TOP, LEFT, RIGHT, BACK, FRONT, IRREGULAR etc\&., EDGE1\&.\&.EDGE12\&. Likewise, \fBSplitBoundary\fP objects contain the string SPLITBOUNDARY in their name, typically separated by underscores from other more specific parts of the name\&.

.PP
\fBAttention\fP
.RS 4
It follows that the user has to assign appropriate names to the geometrical entities in their model that they want to become boundaries\&.
.RE
.PP
\fBModel\fP topology can also be used to perform a consistency check on the cells stored in the \fBVSet\fP\&. Thus, it can check the cell numbering and the neighbor connectivity\&. To some degree it can also fix such potential problems with the \fBVSet\fP\&.

.PP
When the model is supposed box-shaped, this is tested and potentially missing information is restored in collaboration with the \fBVSet\fP / \fBVData\fP and \fBBox\fP\&. In this case it can deduce the correct \fBBOX_BOUNDARY\fP flags and assign them to the nodes\&.

.PP
When a model is created by ANSYS and output using the CSMP interface of ANSYS the information needed to initialise the ModelToplogy class is contained in the '\&.asc' file\&.
.SH "Motivation"
.PP
\fBModelTopology\fP was created to convey topological information from an ANSYS model to CSMP so that corresponding named groups of elements can be created and assigned specific material properties\&. 
.br

.PP
For this purpose, \fBModelTopology\fP stores named maps of the element IDs and types that make up specific model regions\&. By default, the element names are the ANSYS element names as captured inside the class \fBANSYS_ElementSpecifications\fP\&. Functionality is there in the public interface to convert these into CSMP names\&.

.PP
Since one does not always want to use all topological information and or finite elements in a simulation, \fBModelTopology\fP allows the user to reduce the initial topology as, for instance, obtained from ANSYS's meshing tools, to a few target regions - or element types, such as only the volume elements\&. Several interfaces are provided for this purpose\&. 
.br
.SH "Structure"
.PP
\fBModelTopology\fP assumes a complementary role to the \fBVSet\fP which stores the connectivity between elements and their nodes\&. Thus, there must always be a supporting \fBVSet\fP in order to build a \fBModel\fP\&. When the \fBModelTopology\fP is reduced to a subset of the original model, corresponding operations must be performed on the \fBVSet\fP\&.

.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthaei 
.RE
.PP
\fBDate\fP
.RS 4
2001 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool csmp::ModelTopology::AddDomain (const char * rname, const std::set< std::string > & fem_types, const std::vector< size_t > & elms)"

.PP
add new regions Adds a new region of finite-elements to the current model topology\&.
.SH "Input Arguments"
.PP
The region must be defined by a unique name, a set of unique finite element types that make up the region and the list of elements that actually constitute the region in the greater finite element mesh\&.

.PP
\fBReturns\fP
.RS 4
the method reports 'true' if the region could be added to the model topology, and 'false' if not\&. 
.RE
.PP

.SS "template<uint32_t dim> template bool csmp::ModelTopology::AssignBoxShapedModelFlags (\fBVSet\fP< dim > & ) const"

.PP
recreates the \fBBOX_BOUNDARY\fP node flags if a problem was detected Overwrites all pre-existing boundary flags\&. 
.SS "template<uint32_t dim> void csmp::ModelTopology::AssignMaterialProperties (\fBVSet\fP< dim > & vset, const multimap< string, \fBvector\fP< size_t > > & object_elements)"
AssignMaterialProperties() allows the user to interactively assign properties to ANSYS models via the console\&. This is tedious and we recommend to use a configuration file for this purpose\&.

.PP
The only properties that can be assigned are element properties, ie, piecewise constant material properties\&.

.PP
The method adds the property data to the argument \fBVSet\fP\&.
.SH "Input Arguments"
.PP
The methods takes a const reference to the model topology object\&.
.SH "Messages"
.PP
The user is prompted for region and property names\&. 
.SS "bool csmp::ModelTopology::BoxShapedModel () const"

.PP
checks that 3D model contains the boundaries LEFT, RIGHT, BOTTOM, FRONT, BACK; TOP omitted because it may be IRREGULAR A box-shaped model has walls that lie in the XY, XZ, and YZ planes of the coordinate system\&. These wall must be identified by groups of surface elements with the correct CSP names LEFT, RIGHT, BOTTOM, TOP, FRONT and BACK\&. If these boundary identifying surfaces are present the topology is interpreted as box shaped\&. A model can also be box shaped if the top boundary is not present but a surface exists in its place that is called IRREGULAR\&. 
.br

.PP
\fBReturns\fP
.RS 4
If the model contains the aforementioned boundary surfaces 'true' is returned, else 'false'\&. 
.RE
.PP

.SS "\fBvector\fP< size_t >::const_iterator csmp::ModelTopology::CellsOfDomainBegin (const char * region) const"
The method provides access to the element list of the target region via a constant iterator\&.

.PP
\fBParameters\fP
.RS 4
\fIregion\fP The name of the region the element IDs of which shall be recovered\&.
.RE
.PP
\fBReturns\fP
.RS 4
A constant iterator set to the beginning of the target list, if the latter could be found\&. Otherwise an iterator to the end of the first element list stored by the topology class is returned\&.
.RE
.PP
.SH "Messages"
.PP
An ERROR is raised if the target region cannot be found\&. 
.SS "\fBvector\fP< size_t >::const_iterator csmp::ModelTopology::CellsOfDomainEnd (const char * region) const"
The method provides access to the element list of the target region via a constant iterator\&.

.PP
\fBParameters\fP
.RS 4
\fIregion\fP The name of the region the element IDs of which shall be recovered\&.
.RE
.PP
\fBReturns\fP
.RS 4
A constant iterator set to the end of the target list, if the latter could be found\&. Otherwise an iterator to the end of the first element list stored by the topology class is returned\&.
.RE
.PP
.SH "Messages"
.PP
A ERROR is raised if the target region cannot be found\&. 
.SS "void csmp::ModelTopology::CellTypesOfDomain (const char * region, std::set< std::string > & etypes) const"
Returns the names of the finite element types that constitute the region of interest as strings\&.

.PP
\fBParameters\fP
.RS 4
\fIregion\fP The name of the region that shall be investigated\&.
.RE
.PP
A set of unique finite-element type names of the elements that constitute the regions of interest\&. 
.SS "void csmp::ModelTopology::ChangeCellType (const std::string & old_cell_type, std::string new_cell_type_same_as_enum_names)"

.PP
changes the finite - element type associated with a particular region; see \fBFiniteElement\&.h\fP for available types Cheanges the element type from CSMP_Type as specified in \fBCSMP_ElementSpecifications\fP to user defined type\&.
.SH "Input Arguments"
.PP
Use, for example, to convert linear tetrahedra into quadratic tetrahedra\&. AP\&. 
.SS "bool csmp::ModelTopology::ChangeDomainName (const std::string & old_name, const std::string & new_name)"

.PP
changes the name of a domain in the most efficient way; reports whether operation was successful changes the name of a domain in the most efficient way; reports whether operation was successful 
.SS "bool csmp::ModelTopology::CheckCellNumbering () const"
Tests whether the element numbers stored in \fBModelTopology\fP are in a format suitable for reorganising the \fBVSet\fP\&. The following tests are made:

.PP
.IP "\(bu" 2
does the element numbering start with zero?
.IP "\(bu" 2
is the largest element number equivalent to the number of elements-1?
.IP "\(bu" 2
are the elements numbered consecutively?
.IP "\(bu" 2
are the elemnt ids' within each Domain consecutive\&.
.IP "\(bu" 2
are there any duplicate elements?
.PP

.PP
The method assumes that that each element can only belong to a single region\&.

.PP
\fBReturns\fP
.RS 4
Boolean\&. If any of the tests fails the method returns false\&.
.RE
.PP
.SH "Messages"
.PP
The method complains if the element numbering does not start at 0 or the largest element number is not equal to nn-elements-1\&. 
.SS "bool csmp::ModelTopology::Contains (const char * region) const"

.PP
check whether region is alreday included \fBContains()\fP allows the user to test whether the current model contains a certain region identified by the supplied name\&.

.PP
\fBParameters\fP
.RS 4
\fIregion\fP Enter the name of the region that you are looking for\&.
.RE
.PP
\fBReturns\fP
.RS 4
The methods returns 'true' if the region can-, and 'false' if the region cannot be found in the current model topology\&.
.RE
.PP
.SH "Messages"
.PP
A CSMP error is printed if the region was found but is empty, i\&.e\&. contains no elements\&. 
.SS "void csmp::ModelTopology::CreateNewCellNumbers (std::map< size_t, size_t > & old_to_new_mapping, bool check_output = \fRtrue\fP)"

.PP
numbering / repair Creates a new contiguous element numbering 0\&.\&.n-1 and outputs an old-to-new mapping into its argument map\&.

.PP
\fBParameters\fP
.RS 4
\fIcheck_output\fP - if true a consistency check is performed on the new mapping, using the \fBConsecutiveSequenceChecker\fP\&. 
.RE
.PP

.SS "void csmp::ModelTopology::DomainNames (std::vector< std::string > & ) const"

.PP
region, boundary or split boundary names return names of regions in the model 
.SS "void csmp::ModelTopology::EliminateCellType (const char * etype)"
Gets rid of all the model regions which only contain the target element type\&. For poly-element-type model regions the method cannot determine which of the elements are of the target type\&. Thus, they are left untouched\&.

.PP
\fBParameters\fP
.RS 4
\fIetype\fP A character string that matches the element type that is to be removed\&.
.RE
.PP
.SH "Messages"
.PP
The method reports back which regions are being eliminated\&. 
.SS "void csmp::ModelTopology::EliminateCellTypes (const std::list< std::string > & etypes)"
Removes the enlisted element types from the current model topology, irrespective whether this breaks the model up into spatially non- contiguous domains\&.

.PP
\fBEliminateCellTypes()\fP will leave regions which consist of a range of elements untouched, since it cannot identify which element IDs correspond to the enlisted types\&.

.PP
\fBParameters\fP
.RS 4
\fIetypes\fP The method takes a list of strings as argument which define the ANSYS element types\&.
.RE
.PP
.SH "Application Examples"
.PP
Use with utmost care !

.PP
RenumberCellsConsecutively() should be called after the element elimination to re-establish contiguous element numbering in the model\&. Corresponding operations must also be carried out on the \fBVSet\fP that stores the element connectivity which has to be updated when elements were removed\&. 
.SS "void csmp::ModelTopology::EliminateLineCells ()"

.PP
remove all curves Removes all line elements from the current model\&.
.SH "Application Examples"
.PP
Use carefully ! - while the nodes of line elements are typically shared with surface or volume elements, if single line wells are present in a model, the geometry is disrupted\&.

.PP
RenumberCellsConsecutively() should be called after the element elimination to re-establish contiguous element numbering in the model\&. Corresponding operations must also be carried out on the \fBVSet\fP that stores the element connectivity which has to be updated when elements were removed\&. 
.SS "void csmp::ModelTopology::EliminateSurfaceCells ()"

.PP
remove all surfaces Removes all surface elements from the current topology\&.
.SH "Application Examples"
.PP
It may be desirable to get rid of internal or external surfaces in a model since their accumulation will add extra terms to the solution of PDE integrals\&. If the surface element nodes are shared with volume elements, the model topology will stay intact\&. Else the model will be broken\&.

.PP
RenumberCellsConsecutively() should be called after the element elimination to re-establish contiguous element numbering in the model\&. Corresponding operations must also be carried out on the \fBVSet\fP that stores the element connectivity which has to be updated when elements were removed\&. 
.SS "void csmp::ModelTopology::EliminateVolumeCells ()"

.PP
remove all volumetric elements from a model Method eliminates all volume elements from the current model topology\&.
.SH "Application Examples"
.PP
This operation typically greatly upsets a current model, but it gives the option to do, for instance, a fracture only model of a volumetric mesh of a fractured rock\&. It is recommended, however, to control this inside the meshing tool rather than by post-processing, because a better and smaller mesh can typically be created if it is known that only surfaces are required\&.

.PP
RenumberCellsConsecutively() should be called after the element elimination to re-establish contiguous element numbering in the model\&. Corresponding operations must also be carried out on the \fBVSet\fP that stores the element connectivity which has to be updated when elements were removed\&. 
.SS "void csmp::ModelTopology::Erase ()"

.PP
remove certain regions all regions

.PP
Returns all the dynamically allocated memory to the operating system\&. Consequently all the information about the current model is lost\&.

.PP
The name of the model topology is set to 'erased' to signify that all data are gone\&.
.SH "Application Examples"
.PP
Use \fBErase()\fP to free up memory once the construction of a model has been completed, i\&.e\&. a \fBModel\fP object has been formed\&. 
.SS "template<uint32_t dim> bool csmp::ModelTopology::EstablishTopology (\fBVSet\fP< dim > & vset, const multimap< string, string > & object_specs, const multimap< string, \fBvector\fP< size_t > > & object_elements, bool require_unique_names_for_vol_surf_lines, bool interactive_property_assignment, bool correct_orientation_of_surface_elements, bool reassign_boundary_flags)"
Checks that the new numbers in the \fBVSet\fP form a consecutive range\&.

.PP
test: assert( ConsecutiveSequenceChecker::Test_ConsecutiveSequenceChecker() ); 
.SS "void csmp::ModelTopology::ExportSelectionTo (const std::list< std::string > & regions, \fBModelTopology\fP & mt) const"
operations on regions output subset as another model topology

.PP
Copies the selected regions into the target model topology object\&. The target object is emptied before the new regions are inserted\&.

.PP
The target model topology to which the selected regions shall be added is returned into the second method argument\&.

.PP
\fBParameters\fP
.RS 4
\fIregions\fP The list of the regions that shall be copied\&.
.RE
.PP
.SH "Messages"
.PP
If the target object is not empty, this will be reported\&. A ERROR is raised if one of the selected regions does not exist in the source object\&. 
.SS "bool csmp::ModelTopology::InputFromTextFile (const char * file_dot_asc)"

.PP
initialises \fBModelTopology\fP from text file as written by \fBOut()\fP Reads topological information from a user specified text file\&. Format is as produced by method \fBModelTopology::Out()\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIfile_dot_asc\fP The name of the textfile containing topological information to be read\&. 
.RE
.PP

.SS "size_t csmp::ModelTopology::InterpolationOrder () const"

.PP
FEM interpolation function properties\&. Returns the order of the finite-element interpolation functions of the current finite-element model\&.

.PP
\fBReturns\fP
.RS 4
If all elements have the same interpolation order, it is returned as an unsigned integer (1=linear, 2=quadratic, 3=cubic)\&. If the order varies 0 is returned\&.
.RE
.PP
.SH "Implementation"
.PP
Cubic interpolation is currently not tested for\&.
.SH "Messages"
.PP
The method tests whether elements of different order appear in the mesh (a no-no) and report this as an error\&. 
.SS "bool csmp::ModelTopology::IsoparametricFiniteElements () const"

.PP
type of elements A finite element mesh can either be treated as isoparametric (using a local coordinates system to define the interpolation functions and numeric integration) or as standard\&. straight-sided elements defined in physical space\&. CSMP uses different element type names to differentiate the two families of elements\&. Thus it is important to let it know your the desired approach as this will later affect the FEM formulation and available integrals\&.

.PP
The default is 'isoparametric' elements\&.

.PP
\fBReturns\fP
.RS 4
This method returns whether the current model is treated as isoparametric or not\&. 
.RE
.PP

.SS "bool csmp::ModelTopology::LinearElementMesh () const"
The method checks the order of the finite element interpolation functions of the current model\&. 
.br

.PP
\fBReturns\fP
.RS 4
If all the element types in the current model use linear interpolation the method returns true, else it returns false\&. 
.RE
.PP

.SS "bool csmp::ModelTopology::LineModel () const"

.PP
model shape and spatial dimension Loops over the contained elements testing whether the model consists entirely of line elements, i\&.e\&., linear, quadratic or cubic bars\&. 
.br

.PP
\fBReturns\fP
.RS 4
If the model consists entirely of line elements, \fBLineModel()\fP returns true, else it returns false\&. 
.RE
.PP

.SS "size_t csmp::ModelTopology::MinimumSpatialDimensionOfDomain (const char * region) const"
The minimum spatial dimension of a model region is taken to be one if it consists of line elements, and 2 or 3 if it is made up entirely of surface or volume elements, respectively\&. For regions that contain lines, surfaces and or volumes, the elements of highest spatial dimensionality determine the result\&. Still, this result is only a minimum estimate, because line and surface elements also exist in 3D space\&. 
.br

.PP
\fBParameters\fP
.RS 4
\fIregion\fP The method takes to model region name as input argument\&.
.RE
.PP
\fBReturns\fP
.RS 4
The method returns the minimum spatial dimension of the target region\&. For line elements this is 1, for surfaces 2, and for volumes 3\&. 
.br
.RE
.PP
If the region cannot be found, the spatial dimension of the model will be returned in stead\&. 
.br
.SH "Messages"
.PP
When the region cannot be found, the method will report an error\&. 
.SS "void csmp::ModelTopology::Out () const"

.PP
output info Writes all the currently stored topological information to standard output, i\&.e\&. the screen\&. 
.SS "void csmp::ModelTopology::Out (const char * output_file, const std::string header = \fRstd::string()\fP) const"
Writes all the currently stored topological information to a user specified text file\&. If no information is present when the method is called, a message is printed to screen instead of writing an output file\&.

.PP
\fBParameters\fP
.RS 4
\fIoutput_file\fP The name of the textfile which will either be newly created or overwritten\&. 
.br
\fIheader\fP If not empty, outputs this header before the topological information\&. 
.RE
.PP

.SS "void csmp::ModelTopology::OutputAll (std::list< std::string > & regions) const"

.PP
lists all the contained subdomains (regions, boundaries and splitboundaries \fBOut()\fP returns writes all the current region names in the output list\&.

.PP
The method takes a list as an argument into which the region names are inserted\&. If the list is not empty, its contents will be deleted before the new names are inserted\&.
.SH "Messages"
.PP
If the current model does not contain a topology a message is printed\&. 
.SS "void csmp::ModelTopology::PropertiesOfDomains (const char * regions_file, std::list< std::string > & properties, std::map< std::string, std::list< double > > & props) const"

.PP
properties of regions Read material properties from '*-regions\&.txt' file and associate them with the regions storage\&. The property values are going to be constant throughout the regions to which they are assigned\&.
.SH "Input Arguments"
.PP
The method expects that the file name has the appendage and extension '-regions\&.txt'\&. 
.SS "bool csmp::ModelTopology::QuadraticElementMesh () const"
The method checks the order of the finite element interpolation functions of the current model\&. 
.br

.PP
\fBReturns\fP
.RS 4
If all the element types in the current model use linear interpolation the method returns true, else it returns false\&. 
.RE
.PP

.SS "void csmp::ModelTopology::RemoveDomain (const char * region)"
If the target region exists it is removed from the current model\&.

.PP
\fBParameters\fP
.RS 4
\fIregion\fP The name of the region that shall be removed\&.
.RE
.PP
.SH "Messages"
.PP
If the region could not be found in the current topology a warning message is printed to stdout\&. 
.SS "template<uint32_t dim> template void csmp::ModelTopology::RemoveLowDimCellsFromDomains (\fBcsmp::VSet\fP< dim > & vset)"
Method enforces unique names for regions consisting of volumes, surfaces, and line elements: If volume, surface and or line elements belong to element families with the same name, the elements of lower spatial dimension will be ignored\&. find highest dimension for elements in current region

.PP
remove types of low dim elements

.PP
remove ids of low dim elements
.SS "bool csmp::ModelTopology::SolidModel () const"
The models is considered a solid if it contains volume elements, even if these do not enclose contiguous domains and are mixed with surfaces\&.

.PP
\fBReturns\fP
.RS 4
If the model contains volume elements, i\&.e\&., tetrahedra, hexahedra, pyramids or prisms, the method returns true, else false\&. 
.RE
.PP

.SS "bool csmp::ModelTopology::SurfaceModel () const"
If the model consists entirely of line and surface type elements it is considered as a surface model\&. This is checked by the \fBSurfaceModel()\fP\&. Surface elements are triangles and quadrilaterals\&. 
.br

.PP
\fBReturns\fP
.RS 4
bool reporting whether the model consists entirely of surfaces\&.
.RE
.PP
The method returns true if the model consists entirely of line and surface elements, else false is returned\&. 
.SS "void csmp::ModelTopology::UseIsoparametricFiniteElementTypes ()"
Instructs the \fBModelTopology\fP class to treat the contained finite elements as isoparametric, i\&.e\&. as finite elements with local interpolation functions and using numeric integration\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
