.TH "csmp::Element< dim >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Element< dim > \- Object representation of a finite element Bridge pattern together with \fBFiniteElement\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Element\&.h>\fP
.PP
Inherits \fBcsmp::FiniteElementPolicy< dim, Element >\fP, \fBcsmp::FiniteVolumePolicy< dim, Element >\fP, and \fBcsmp::LocalVariableStorage< dim, Element >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP (\fBFiniteElement\fP *)"
.br
.RI "constructor for testing element in isolation "
.ti -1c
.RI "\fBElement\fP (\fBFiniteElement\fP *, const \fBFiniteVolumeStencil\fP< dim > *)"
.br
.RI "constructor for testing element in isolation "
.ti -1c
.RI "\fBElement\fP (\fBFiniteElement\fP *, const \fBFiniteVolumeStencil\fP< dim > *, const \fBLocalVariables\fP &element_props, const \fBIntegrationPointVariables\fP &integration_point_props)"
.br
.ti -1c
.RI "\fBElement\fP (size_t index, \fBFiniteElement\fP *, const \fBFiniteVolumeStencil\fP< dim > *, const \fBLocalVariables\fP &element_props, const \fBIntegrationPointVariables\fP &integration_point_props, int32_t material)"
.br
.RI "for model reconstruction from CSMP native binary file "
.ti -1c
.RI "\fBElement\fP (const \fBElement\fP< dim > &)"
.br
.ti -1c
.RI "\fBElement\fP< dim > & \fBoperator=\fP (const \fBElement\fP< dim > &)"
.br
.ti -1c
.RI "\fBElement\fP (\fBElement\fP< dim > &&)"
.br
.ti -1c
.RI "\fBElement\fP< dim > & \fBoperator=\fP (\fBElement\fP< dim > &&)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBElement\fP< dim > &) const"
.br
.RI "compares finite element type, material id, nodes, and neighbors; ignoring mutable idx and other attributes "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBElement\fP< dim > &) const"
.br
.RI "less than operator for comparing barycentre locations using operator of the corresponding point object "
.ti -1c
.RI "\fBPLACEMENT\fP \fBPlacement\fP () const"
.br
.RI "Local variable storage interface\&. "
.ti -1c
.RI "void \fBAccept\fP (\fBcsmp::Visitor\fP< dim > &)"
.br
.ti -1c
.RI "void \fBAssign\fP (uint32_t nbor, \fBElement\fP< dim > *const)"
.br
.RI "(re)connect the element to its neighbors (during the model construction process or after remeshing) "
.ti -1c
.RI "bool \fBUnassign\fP (const \fBElement\fP< dim > *const)"
.br
.RI "sets pointer to given neighbor element to zero, reports whether removal was made "
.ti -1c
.RI "void \fBUnassignNeighbor\fP (uint32_t)"
.br
.RI "sets pointer to given neighbor element identifed by its number to zero "
.ti -1c
.RI "void \fBAssign\fP (uint32_t node, \fBNode\fP< dim > *const)"
.br
.RI "(re)connect the element to its nodes (during the model construction process or after remeshing / split boundary creation) "
.ti -1c
.RI "void \fBUnassign\fP (const \fBcsmp::Node\fP< dim > *const)"
.br
.RI "sets pointer to given node to zero "
.ti -1c
.RI "uint32_t \fBNodes\fP () const"
.br
.RI "number of nodes of this element "
.ti -1c
.RI "uint32_t \fBNeighbors\fP () const"
.br
.RI "number of equidimensional neighbor elements of this element (not necessarily connected) "
.ti -1c
.RI "uint32_t \fBConnectedNeighbors\fP () const"
.br
.RI "number of equidimensional neighbor elements of this element (necessarily connected) "
.ti -1c
.RI "uint32_t \fBFaces\fP () const"
.br
.RI "number of faces (side-surfaces) of the current element; for each element face, there can be a neighbor "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBNodesBegin\fP () const"
.br
.RI "only constant iterators are provided because the user is not supposed to change the node pr neighbor connectivity (done by \fBMeshManager\fP); thus, nodes and element neighbors can be manipulated but not the pointers to them "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBNodesEnd\fP () const"
.br
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBCornerNodesBegin\fP () const"
.br
.RI "assuming that the corner nodes are the first, the midside nodes the second, and the \&.\&. in the elements node set according to CSMP_FEM_conventions\&.pdf "
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBCornerNodesEnd\fP () const"
.br
.ti -1c
.RI "std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator \fBNeighborsBegin\fP () const"
.br
.ti -1c
.RI "std::vector< \fBcsmp::Element\fP< dim > * >::const_iterator \fBNeighborsEnd\fP () const"
.br
.ti -1c
.RI "std::vector< \fBcsmp::Node\fP< dim > * > & \fBNodeVector\fP ()"
.br
.ti -1c
.RI "std::vector< \fBcsmp::Element\fP< dim > * > & \fBNeighborElementVector\fP ()"
.br
.ti -1c
.RI "\fBcsmp::Node\fP< dim > *const \fBN\fP (uint32_t n_local) const"
.br
.RI "accessor of the nodes of the current finite element "
.ti -1c
.RI "const \fBcsmp::Element\fP< dim > *const \fBNeighbor\fP (uint32_t) const"
.br
.RI "accessor of the equidimensional neighbor elements of the current element (volume->volume, surface->surfaces element etc\&.) "
.ti -1c
.RI "\fBcsmp::Element\fP< dim > *const \fBNeighbor\fP (uint32_t)"
.br
.ti -1c
.RI "void \fBIdx\fP (size_t) const"
.br
.RI "on-the-fly 0\&.\&.n-1 numbering stored in a mutable local variable (therefore const) "
.ti -1c
.RI "size_t \fBIdx\fP () const"
.br
.ti -1c
.RI "\fBBOX_BOUNDARY\fP \fBAtBoundary\fP (uint32_t boundary_face) const"
.br
.RI "is element located at an outside or internal model boundary; if it shares a face with a boundary, this is true "
.ti -1c
.RI "int32_t \fBMaterial_ID\fP () const"
.br
.RI "unique material identifier used to store 'rocktype' or \fBModelSubDomain::domain_idx_\fP "
.ti -1c
.RI "void \fBMaterial_ID\fP (int32_t id)"
.br
.ti -1c
.RI "int32_t \fBRegion_ID\fP () const"
.br
.RI "unique region identifier to be set to minus \fBModelSubDomain::domain_idx_\fP for non-unique regions "
.ti -1c
.RI "void \fBRegion_ID\fP (int32_t id)"
.br
.ti -1c
.RI "template<class Var> void \fBNodePropertyVector\fP (const \fBcsmp::Index\fP &, std::vector< Var > &) const"
.br
.RI "returns a vector of the property of interest discretized on the node "
.ti -1c
.RI "void \fBNodeCoordinateMatrix\fP (\fBDenseMatrix\fP< DM_MIN > &) const"
.br
.RI "inputs node coordinates into supplied matrix "
.ti -1c
.RI "\fBPoint\fP< dim > \fBBaryCenter\fP () const"
.br
.RI "the centre of gravity of the elemt "
.ti -1c
.RI "double \fBLengthInDirection\fP (const \fBVectorVariable\fP< dim > &vecDirection) const"
.br
.RI "projects node points onto line returning max distance between them; vec direction can have any length "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "prints \fBElement\fP internal data and those of connected objects\&. "
.in -1c

Public Member Functions inherited from \fBcsmp::FiniteElementPolicy< dim, Element >\fP
.in +1c
.ti -1c
.RI "\fBFiniteElementPolicy\fP (const \fBElement\fP< dim > &) noexcept"
.br
.ti -1c
.RI "\fBFiniteElementPolicy\fP & \fBoperator=\fP (const \fBFiniteElementPolicy\fP &p) noexcept"
.br
.ti -1c
.RI "void \fBAssign\fP (\fBFiniteElement\fP *fe_ptr)"
.br
.RI "for deferred assignment or changing the element at runtime "
.ti -1c
.RI "void \fBAssignFiniteElementNullPtr\fP () noexcept"
.br
.ti -1c
.RI "\fBCSMP_FEM_TYPE\fP \fBFE_Type\fP () const noexcept"
.br
.RI "the type is an enumeration that is used in the generation of finite elements "
.ti -1c
.RI "\fBFiniteElement\fP * \fBFE\fP () const noexcept"
.br
.RI "you are allowed to switch the element at runtime and modifies the volatile data it stores "
.ti -1c
.RI "bool \fBIsEquidimensional\fP () const"
.br
.RI "true for volumes in 3D, surfaces in 2D, and line elements in 1D, else this is a lower dimensional element "
.ti -1c
.RI "bool \fBIsLine\fP () const"
.br
.ti -1c
.RI "bool \fBIsSurface\fP () const"
.br
.ti -1c
.RI "bool \fBIsVolume\fP () const"
.br
.ti -1c
.RI "uint32_t \fBInterpolation\fP () const"
.br
.ti -1c
.RI "bool \fBUsesLocalCoordinates\fP () const"
.br
.ti -1c
.RI "uint32_t \fBIntegrationPoints\fP () const"
.br
.RI "number of element integration points for current quadrature scheme "
.ti -1c
.RI "\fBPoint\fP< dim > \fBIntegrationPoint\fP (uint32_t ip) const"
.br
.RI "returns the location of the integration point in global coordinates "
.ti -1c
.RI "double \fBWeightAtIntegrationPoint\fP (uint32_t i) const"
.br
.ti -1c
.RI "\fBPoint\fP< dim > \fBRstToXYZ\fP (\fBPoint\fP< dim > rst) const"
.br
.RI "mapping of local points from local to global coordinates "
.ti -1c
.RI "void \fBN_At\fP (const \fBPoint\fP< dim > &rst) const"
.br
.RI "interpolation function values at local points "
.ti -1c
.RI "void \fBN_AtGlobalPoint\fP (std::vector< double > &N, const std::vector< double > &xyz) const"
.br
.RI "for elements with local coordinates, this method uses an iterative approach to find the correspoding location in parametric space "
.ti -1c
.RI "void \fBN_AtBaryCenter\fP (std::vector< double > &N) const"
.br
.ti -1c
.RI "void \fBN_AtIntegrationPoint\fP (uint32_t ipoint, std::vector< double > &N) const"
.br
.ti -1c
.RI "void \fBIntegral_dNT_K_dN\fP (\fBDenseMatrix\fP< DM_MIN > &M, \fBDenseMatrix\fP< DM_MIN > &K) const"
.br
.RI "first (constant) derivatives of linear interpolation functions of analytically integrated simplex "
.ti -1c
.RI "void \fBdN\fP (\fBDenseMatrix\fP< DM_MIN > &) const"
.br
.ti -1c
.RI "double \fBdN_AtNode\fP (\fBDenseMatrix\fP< DM_MIN > &, uint32_t nd, uint32_t dof=1) const"
.br
.RI "first derivatives of interpolation functions at the given node (returned is determinant of Jacobian matrix at i,j) "
.ti -1c
.RI "double \fBdN_AtBaryCenter\fP (\fBDenseMatrix\fP< DM_MIN > &, uint32_t dof=1) const"
.br
.RI "first derivatives of interpolation functions at the (returned is determinant of Jacobian matrix at i,j) "
.ti -1c
.RI "double \fBdN_AtIntegrationPoint\fP (\fBDenseMatrix\fP< DM_MIN > &, uint32_t gp, uint32_t dof=1) const"
.br
.RI "first derivatives of interpolation functions at Gauss point gp (returned is determinant of Jacobian matrix at i,j) "
.ti -1c
.RI "double \fBdet_JINV_AtIntegrationPoint\fP (uint32_t ipoint) const"
.br
.RI "returned is determinant of Jacobian matrix at given Gauss point "
.ti -1c
.RI "void \fBIntegralNN\fP (\fBDenseMatrix\fP< DM_MIN > &M) const"
.br
.RI "interpolation function products matrix for analytically integrated element "
.ti -1c
.RI "void \fBCoordinateMatrix\fP () const"
.br
.RI "initialises the nodes x dim matrix XY stored in the connected finite element class "
.ti -1c
.RI "double \fBPropertyIntegral\fP (const \fBcsmp::Index\fP &scalar_property) const"
.br
.RI "integrates a scalar property over the element and returns this value "
.ti -1c
.RI "void \fBPropertyValueAt\fP (const \fBcsmp::Index\fP &, const std::vector< double > &xyz, Var &) const"
.br
.RI "interpolates node property values to the point of interest (in global coordinates); "
.ti -1c
.RI "void \fBPropertyValueAtBaryCenter\fP (const \fBcsmp::Index\fP &, Var &) const"
.br
.RI "returns the value of any property interpolated to the element's center of gravity "
.ti -1c
.RI "void \fBPropertyValueAtIntegrationPoint\fP (const \fBcsmp::Index\fP &node_prop, uint32_t integration_point, Var &) const"
.br
.RI "returns the value of any property interpolated to the integration point of interest "
.ti -1c
.RI "void \fBIntegrationPointPropertyVector\fP (const \fBcsmp::Index\fP &, std::vector< Var > &) const"
.br
.RI "returns property values at the integration points "
.ti -1c
.RI "void \fBExtrapolateIntegrationPointVariableToNodes\fP (uint32_t nvars, const std::vector< double > &integration_point_var, std::vector< double > &node_variable) const"
.br
.RI "uses linear extrapolation of property values from the integration points to the nodes "
.ti -1c
.RI "double \fBVolume\fP () const"
.br
.RI "reports volume, area*1, and length*1*1 products for volumetric, surfacic and line elements respectively "
.ti -1c
.RI "double \fBAspectRatio\fP () const"
.br
.RI "ratio of longest to shortest edge=segment "
.ti -1c
.RI "double \fBInnerRadius\fP () const"
.br
.RI "the radius of an inscribed circle / sphere "
.ti -1c
.RI "uint32_t \fBSegments\fP () const"
.br
.RI "number of edges = segments in the finite element of interest "
.ti -1c
.RI "\fBPoint\fP< dim > \fBSegmentMidPoint\fP (uint32_t segm) const"
.br
.RI "retrieve position of the segment (element edge) mid-points "
.ti -1c
.RI "double \fBSegmentLength\fP (uint32_t segm) const"
.br
.RI "returns the length of the nth segment=edge of the finite element "
.ti -1c
.RI "void \fBSegmentLengths\fP (std::vector< double > &) const"
.br
.RI "returns a vector with the lengths of all finite element segments = edges "
.ti -1c
.RI "std::set< \fBNode\fP< dim > * > \fBCornerNodesOfFace\fP (uint32_t face_id) const"
.br
.RI "returns search key to match element faces; pointers in order so that they can be searched "
.ti -1c
.RI "std::set< \fBNode\fP< dim > * > \fBCornerNodesConnectedTo\fP (uint32_t node_id) const"
.br
.RI "returns set of nodes that are neighbors of the target node in this element "
.ti -1c
.RI "\fBPoint\fP< dim > \fBFaceBaryCenter\fP (uint32_t face) const"
.br
.RI "retrieve barycenter of element face "
.ti -1c
.RI "\fBPoint\fP< dim > \fBUnitNormalToFace\fP (uint32_t face) const"
.br
.RI "returns unit normal to face of element i "
.ti -1c
.RI "\fBPoint\fP< dim > \fBUnitNormal\fP () const"
.br
.RI "computes unit normal to element if it is planar (3D) or linear (2D); vector components are returned into point "
.ti -1c
.RI "void \fBOutputPropertyToVTK\fP (const \fBcsmp::Index\fP &, const char *file_name, const char *var_name) const"
.br
.RI "outputs finite element and discretised variable to VTK file "
.in -1c

Public Member Functions inherited from \fBcsmp::LocalVariableStorage< dim, Element >\fP
.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLocalVariableStorage\fP< dim, \fBElement\fP > &) const"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBResizePropertyStorage\fP (const \fBLocalVariables\fP &)"
.br
.RI "Goto overload for storees without \fBIntegrationPointVariables\fP\&. "
.ti -1c
.RI "void \fBAddProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Creates an empty space in the storage preserving the original variable values\&. \fBLocalVariables\fP in \fBIndex\fP have to reflect NEW state (incl added) "
.ti -1c
.RI "void \fBDeleteProperty\fP (const \fBcsmp::Index\fP &)"
.br
.RI "Deletes data and flags of property \fBLocalVariables\fP in \fBIndex\fP have to reflect CURRENT state (incl property to be removed) "
.ti -1c
.RI "bool \fBIsWithinRange\fP (const \fBcsmp::Index\fP &, double, double) const"
.br
.ti -1c
.RI "double \fBRead\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar variable value\&. "
.ti -1c
.RI "void \fBStore\fP (const \fBcsmp::Index\fP &, const \fBScalarVariable\fP &)"
.br
.RI "Scalar variable\&. "
.ti -1c
.RI "\fBVARIABLE_FLAG\fP \fBStatus\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "Scalar & Array variable flag\&. "
.ti -1c
.RI "void \fBStoreArrayEntry\fP (const \fBcsmp::Index\fP &, double array_elmt_value, int_type)"
.br
.ti -1c
.RI "double \fBReadArrayEntry\fP (const \fBcsmp::Index\fP &, int_type array_elmt) const"
.br
.RI "reads single double element inside of the target array "
.ti -1c
.RI "bool \fBEmptyLVS\fP () const"
.br
.ti -1c
.RI "void \fBOutLVS\fP () const"
.br
.ti -1c
.RI "void \fBAssertPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBAssertFiniteVolumeIntegrationPointPlacement\fP (const \fBcsmp::Index\fP &) const"
.br
.RI "We check in debug only\&. "
.ti -1c
.RI "void \fBStoreLocalState\fP (const \fBLocalVariables\fP &lv)"
.br
.RI "We store in debug only\&. "
.ti -1c
.RI "void \fBLVS\fP (const Data &data)"
.br
.RI "copy or move supplied data into storage "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<uint32_t> class \fBMeshManager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::Element< dim >"Object representation of a finite element Bridge pattern together with \fBFiniteElement\fP class\&. 


.PP
\fBAuthor\fP
.RS 4
S\&.K\&. Matthai 

.PP
Stephen G\&. Roberts 
.RE
.PP
\fBDate\fP
.RS 4
1999
.RE
.PP
.SH "Motivation"
.PP
The finite-element method uses areal/volumetric elements as smallest computational units\&. Each element has 2 functions: (1) to store material properties and nodes with associated properties; (2) To generate matrices which contribute to a global system of algebraic equations which is solved to obtain the value of the dependent spatially-distributed variable which typically is stored on the nodes\&.
.SH "Design Intent"
.PP
The \fBElement\fP class is a structural object that forms part of a Bridge design pattern (pattern 151, Gamma et al\&. 1995)\&. The bridge pattern is used to allow that elements can be mass-contructed by a container class (an STL vector in the \fBMeshManager\fP), but that they have polymorphic properties at the same\&. time\&. Also a mesh usually has many elements, but only a few element types\&. This is achieved by "bridging" the \fBElement\fP objects to a few \fBFiniteElement\fP object pointers stored in the global array globalFE_types[]\&.

.PP
A class diagram of the Element-FiniteElement bridge pattern is shown in the CSP3D User Guide in the developers section\&.
.SH "Applicability"
.PP
The \fBElement\fP class should be applicable in any type of finite-element computation\&. Higher-order elements will make use of the ability to store retrieve integration point data\&.
.SH "Structure"
.PP
The structure of the \fBElement\fP - \fBFiniteElement\fP bridge pattern is described in Gamma et al\&. 1995 (p\&. 151)\&. The element interface is broken down into a part that echoes the interfaces of the \fBFiniteElement\fP base class from which the desired element types are inherited thereby giving these inter- faces polymorphic behaviour\&.

.PP
The main operations which the element is used for are the retrieval of property values, node coordinate matrices, and node ID number vectors which are used in the assembly of the element equations\&. The element matrices are square and theur size is equivalent to the product of the degrees of freedom of each node and the number of nodes\&.
.SH "Participants"
.PP
The \fBElement\fP queries Nodes, IntegrationPoints, and the MemoryManager<dim> to obtain the data which it needs in its computations\&. It cannot exist without reference to the \fBFiniteElement\fP which implements half of its interface\&.

.PP
The \fBElement\fP uses \fBDenseMatrix<DM_MIN>\fP, and STL vector objects to receive and tranfer data\&.
.SH "Collaborations"
.PP
Elements can collaborate with \fBVisitor\fP objects through their \fBAccept()\fP interface\&. This combines the methods of the \fBVisitor\fP with the functionality of the \fBElement\fP\&.

.PP
The main collaboration exists between Elements and Algorithms\&. The latter query the \fBElement\fP for coordinate and property matrices and a node number vector\&. The new Algorithm class queries Elements through virtual methods of the MathOperator base classes\&.
.SH "Consequences"
.PP
Elements are "finite-element-independent" mesh-building blocks\&. Because variables are only accessed through the Elements but not stored there, the mesh storage is also independent from the number of properties associated with it, while encapsulation is maintained and the access hierarchy is preserved\&.
.SH "Implementation"
.PP
The bridge between the \fBElement\fP and the \fBFiniteElement\fP is implemented as a reference\&. It is initialized either through the default constructor which accesses the globalFE_types[] array, or, through a constructor which takes a reference to a finite element as argument\&.

.PP
Nodes, IntegrationPoints, and Neighbors of an \fBElement\fP are accessed by pointers which are initialized through the ConnectTo\&.\&.\&.() interfaces\&. Methods with the same name interface the \fBElement\fP with the methods of the \fBFiniteElement\fP\&. The \fBElement\fP methods \fBRead()\fP, \fBStore()\fP and \fBStatus()\fP are used to access element properties\&. Alternatively, to property output into \fBDenseMatrix<DM_MIN>\fP and vector objects you can also get STL vectors of scalar, vector, and tensor properties\&.
.SH "Application Examples"
.PP
The Visit(Element* e) method in "TransportVisitor\&.h" illustrates nicely the functionality of the \fBElement\fP class\&. In this method element and node properties and node property averages are obtained and written back to the mesh\&.
.SH "- FOR DEVELOPERS"
.PP
Consider that users of the policies may also want to work on other incarnations of the \fBElement\fP, in particular ones with less policies\&. This only works when the policies only depend on the functionality of the element, but not on each other!

.PP
As a key difference between policies and traits, the latter have state\&. Thus, the finite-element policy own the fe pointer and the fv policy ons the fv pointer which is key to the design\&.

.PP
For the current design, however, this is only partially true because the \fBFiniteVolumePolicy\fP depends on finite element functionality\&. Thus, one can have an element with FEM but without FVM, but not vice versa\&.

.PP
\fBTodo\fP
.RS 4
(3) Write faster code to determine whether a \fBPoint\fP is contained in a certain element (A)
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::Element\fP< dim >::Element (\fBcsmp::FiniteElement\fP< dim > * f)\fR [explicit]\fP"

.PP
constructor for testing element in isolation Constructor associates \fBElement\fP with instance of specific finite element\&. This initialized the bridge pattern\&. Also, vectors of pointers to nodes, constraint points and neighbor elements are constructed\&.
.SH "Input Arguments"
.PP
Finite element, for example \fBLinearTriangle\fP\&. The element type determines how many nodes and constraint points the \fBElement\fP will have and if affects the element dimensionality which can be queried with Dim()\&.
.SH "Application Examples"
.PP
Elements are constructed inside the \fBMeshManager\fP\&. There are 2 methods for VSets and VSets respectively\&. VSets (a class that will be phased out in 1999) cannot hold different element types in one mesh\&. In this case the \fBElement\fP default constructor will initialize the \fBFiniteElement\fP reference to \fBFiniteElementManager\fP\&. In the case of VSets, specific element types can be stored and this constructor is used to reference them properly\&. 
.SS "template<uint32_t dim> \fBcsmp::Element\fP< dim >::Element (size_t idx, \fBcsmp::FiniteElement\fP< dim > * f, const \fBFiniteVolumeStencil\fP< dim > * s, const \fBLocalVariables\fP & ep, const \fBIntegrationPointVariables\fP & cp, int32_t material)"

.PP
for model reconstruction from CSMP native binary file For model reconstruction from binary file 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::Element\fP< dim >::Accept (\fBcsmp::Visitor\fP< dim > & vis)"
\fBVisitor\fP subclassed objects may be passed to the \fBElement\fP object to gain access to its public interface\&. This then allows the visitor to query the Elements methods for the data it needs for its own computations\&. Apart from just visiting each \fBElement\fP sequentially, a \fBVisitor\fP can target the Elements neigbor elements to which it simultaneously has access\&. This allows to implement a mesh traversal technique like streamline routing\&.
.SH "Implementation"
.PP
The visitor is queried for its application Target\&. Depending on the result it is applied to this \fBElement\fP or passed on to all of its Nodes, IntegrationPoints or Neighbors\&.
.SH "Application Examples"
.PP
The Accept method is used, for instance, by the TranportVisitor class\&.

.PP
\fBParameters\fP
.RS 4
\fIvis\fP A reference to a \fBVisitor\fP subclass\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::Element\fP< dim >::Assign (uint32_t i, \fBElement\fP< dim > * const e_ptr)"

.PP
(re)connect the element to its neighbors (during the model construction process or after remeshing) Assign equidimensional neighbor elements to element\&. 
.SS "template<uint32_t dim> \fBPoint\fP< dim > \fBcsmp::Element\fP< dim >::BaryCenter () const"

.PP
the centre of gravity of the elemt \fBBaryCenter()\fP calculates the node coordinate average for the element\&. This coordinate value is equivalent to the center of gravity of the \fBElement\fP type\&.
.SH "Input Arguments"
.PP
The barycentre is returned into a CSMP vector variable a reference to which is supplied as single argument\&.
.SH "Application Examples"
.PP
The element barycentre could be used for instance to output element material properties from the \fBModel\fP as point data\&. This is done if you use the \fBModel\fP OutputToTextFile() methods\&.

.PP
\fBReturns\fP
.RS 4
The \fBVARIABLE_FLAG\fP of the returned vector variable will not be changed by BaryCentre()\&.
.RE
.PP
\fBNote\fP
.RS 4
could be madfe more
.RE
.PP
\fBTest\fP
.RS 4
O\&.K\&. SKM25/8/14 after refactoring loop
.RE
.PP

.SS "template<uint32_t dim> double \fBcsmp::Element\fP< dim >::LengthInDirection (const \fBVectorVariable\fP< dim > & vecDirection) const"

.PP
projects node points onto line returning max distance between them; vec direction can have any length Measures the length of the element (in physical space) in a certain direction\&.

.PP
\fBParameters\fP
.RS 4
\fIvecDirection\fP direction in which the element is to be measured
.RE
.PP
\fBReturns\fP
.RS 4
Length of the element\&.
.RE
.PP
@sectin implementation Implementation

.PP
The main idea is to measure the height of the oriented bounding box (oriented by the direction of vecDirection) which surrounds the element\&. This is done by projecting each node onto the direction vector and calculating the difference between the largest and smallest magnitude\&. The distance between both projections will be given by the absolute value of this difference\&.
.SH "Application Examples"
.PP
The length of the element in a certain dimension is used to weigh the error of the element, when evaluating the quality of a certain mesh\&.

.PP
\fBTodo\fP
.RS 4
this method could be optimised if only the corner nodes would be used
.RE
.PP

.SS "template<uint32_t dim> int32_t \fBcsmp::Element\fP< dim >::Material_ID () const"

.PP
unique material identifier used to store 'rocktype' or \fBModelSubDomain::domain_idx_\fP unique material identifier that matches number of parent unique region 
.SS "template<uint32_t dim> \fBcsmp::Node\fP< dim > *const \fBcsmp::Element\fP< dim >::N (uint32_t n) const"

.PP
accessor of the nodes of the current finite element The suite of methods Node(), \fBIntegrationPoint()\fP, Face() and \fBNeighbor()\fP, enables access of these connected objects via const references\&. A NULL pointer is returned by \fBNeighbor()\fP if the \fBElement\fP lies at the model boundary and a Neighbor does not exist\&. Also constraint points do not exist unless you defined these for the specific \fBFiniteElement\fP which you are using\&.
.SH "Input Arguments"
.PP
An integer from 0\&.\&.\&.n-1, where n is the number of nodes per \fBElement\fP\&. Nodes are numbered clockwise for regular-gridded meshes (since Y points downward) and counter-clockwise for all other meshes\&.
.SH "Implementation"
.PP
A range check is performed\&.
.SH "Application Examples"
.PP
Use only when the other methods of the \fBElement\fP fail to give you enough information about the target object\&. For instance when you want to retrieve a \fBNode\fP coordinate:

.PP
.PP
.nf
double x = (*element\&.N(2))\->x();
.fi
.PP

.PP
\fBReturns\fP
.RS 4
return A pointer to the Target object, e\&.g\&. a \fBNode\fP\&. 
.RE
.PP

.SS "template<uint32_t dim> const \fBcsmp::Element\fP< dim > *const \fBcsmp::Element\fP< dim >::Neighbor (uint32_t n) const"

.PP
accessor of the equidimensional neighbor elements of the current element (volume->volume, surface->surfaces element etc\&.) Returns a pointer to neighbouring element i (see CSMP's FEM type conventions to understand the neighbor numbering scheme)\&.

.PP
\fBAttention\fP
.RS 4
always check whether the neighbor pointer is valid before you are trying to use it\&. 
.RE
.PP

.SS "template<uint32_t dim> void \fBcsmp::Element\fP< dim >::NodeCoordinateMatrix (\fBDenseMatrix\fP< DM_MIN > & XY) const"

.PP
inputs node coordinates into supplied matrix Returns a matrix with 'nodes'-rows and 'coordinate-directions' columns\&. This Meschach++ matrix defines the positions of the elements nodes for the finite-element matrix assembly\&. Since the number of element nodes may vary among different elements types, the number of rows in XY may also vary from element to element\&.

.PP
\fBParameters\fP
.RS 4
\fIXY\fP A \fBDenseMatrix<DM_MIN>\fP class object (value type fT)\&. This matrix is dynamically resized if necessary but must have been constructed with a finite size before passing it to \fBCoordinateMatrix()\fP\&.
.RE
.PP
\fBNote\fP
.RS 4
\fBElement\fP The node coordinates are returned into the supplied matrix\&.
.RE
.PP
.SH "Application Examples"
.PP
Finite-element forms of differential equations require the global node coordinates of the element to calculate the element constribution to the global solution matrix\&. If the element uses local coordinates, the global node coordinates will still be required to compute Jacobian (coordinate- transformation) matrix\&. 
.SS "template<uint32_t dim> template<class Var> template void \fBcsmp::Element\fP< dim >::NodePropertyVector (const \fBcsmp::Index\fP & , std::vector< Var > & ) const"

.PP
returns a vector of the property of interest discretized on the node returns property values at the nodes 
.SS "template<uint32_t dim> std::vector< \fBcsmp::Node\fP< dim > * >::const_iterator \fBcsmp::Element\fP< dim >::NodesBegin () const"

.PP
only constant iterators are provided because the user is not supposed to change the node pr neighbor connectivity (done by \fBMeshManager\fP); thus, nodes and element neighbors can be manipulated but not the pointers to them iterator to the element nodes 
.SS "template<uint32_t dim> bool \fBcsmp::Element\fP< dim >::operator< (const \fBElement\fP< dim > & el) const"

.PP
less than operator for comparing barycentre locations using operator of the corresponding point object less_than<> predicate for storage of Elements in STL container objects, including equal comparisons\&.

.PP
\fBNote\fP
.RS 4
Uses comparitor on barycentre point object to order the elements\&.
.RE
.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
6/9/2021 
.RE
.PP

.SS "template<uint32_t dim> bool \fBcsmp::Element\fP< dim >::operator== (const \fBElement\fP< dim > & el) const"

.PP
compares finite element type, material id, nodes, and neighbors; ignoring mutable idx and other attributes comparitor 
.SS "template<uint32_t dim> bool \fBcsmp::Element\fP< dim >::Unassign (const \fBElement\fP< dim > * const e_ptr)"

.PP
sets pointer to given neighbor element to zero, reports whether removal was made Unassigns the neighbor element, setting the pointer in the 'elmt_connector' vector to nullptr\&. Neither the argument pointer nor the \fBElement\fP pointed to are modified\&. 
.PP
.nf
@return whether removal was successful

.fi
.PP
 
.SS "template<uint32_t dim> void \fBcsmp::Element\fP< dim >::UnassignNeighbor (uint32_t nbor)"

.PP
sets pointer to given neighbor element identifed by its number to zero Fast version which assumes that the number of the neighbor is known 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
