.TH "csmp::H2ONaClLookup" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::H2ONaClLookup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBH2ONaClLookup\fP (const double &externaltemperature, const double &externalpressure, const double &externalcomposition)"
.br
.ti -1c
.RI "double \fBTemperature\fP ()"
.br
.ti -1c
.RI "double \fBPressure\fP ()"
.br
.ti -1c
.RI "double \fBMassFractionNaCl\fP ()"
.br
.ti -1c
.RI "double \fBDensity\fP ()"
.br
.ti -1c
.RI "double \fBEnthalpy\fP ()"
.br
.ti -1c
.RI "double \fBHeatCapacity\fP ()"
.br
.ti -1c
.RI "double \fBCompressibility\fP ()"
.br
.ti -1c
.RI "double \fBViscosity\fP ()"
.br
.ti -1c
.RI "void \fBPrintAll\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalVaporDensity\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalVaporEnthalpy\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalVaporHeatCapacity\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalVaporCompressibility\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalVaporViscosity\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalLiquidDensity\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalLiquidEnthalpy\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalLiquidHeatCapacity\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalLiquidCompressibility\fP ()"
.br
.ti -1c
.RI "double \fBSubcriticalLiquidViscosity\fP ()"
.br
.ti -1c
.RI "long \fBGetTableID\fP (const double &t)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
