.TH "csmp::MohrCoulombFailure< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::MohrCoulombFailure< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MohrCoulombFailure\&.h>\fP
.PP
Inherits \fBcsmp::Interrelation< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMohrCoulombFailure\fP (const \fBPropertyDatabase\fP< dim > &, double friction_angle)"
.br
.ti -1c
.RI "virtual void \fBCalculate\fP ()"
.br
.RI "computes the local value of result property "failure" which gets written back to the model "
.in -1c

Public Member Functions inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "\fBInterrelation\fP (const \fBPropertyDatabase\fP< dim > &p)"
.br
.ti -1c
.RI "void \fBName\fP (const char *s)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApply\fP (\fBModel\fP< dim > &)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBApply\fP (\fBModelSubDomain\fP< dim, CELL > &)"
.br
.RI "a simplex is any geometrical association of points "
.ti -1c
.RI "bool \fBResultWithinRange\fP ()"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::const_iterator \fBOperandsBegin\fP () const"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::const_iterator \fBOperandsEnd\fP () const"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::iterator \fBResult\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBMeanStress\fP (const \fBTensorVariable\fP< dim > &)"
.br
.RI "average of the magnitude of the principal stress "
.ti -1c
.RI "double \fBDeviatoricStress\fP (const \fBTensorVariable\fP< dim > &, double &t_stress_invariant)"
.br
.RI "computes the shear-stress related stress invariant, returning into second argument; method difference between sigma1 and sigma3 "
.ti -1c
.RI "double \fBTheta\fP (const \fBTensorVariable\fP< dim > &, double t_stress_invariant)"
.br
.RI "computes stress state invariance theta (Smith & Griffith, 2014, p\&. 236 "
.ti -1c
.RI "double \fBG_OfTheta\fP (double theta)"
.br
.RI "computes stress state invariance, see Zienkiewitz II, p\&. 89 "
.in -1c

Protected Member Functions inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "\fBOperand\fP< dim > & \fBGlobalProperty\fP (const char *var)"
.br
.ti -1c
.RI "void \fBResultProperty\fP (const char *var)"
.br
.ti -1c
.RI "void \fBOutputCondition\fP (\fBOperand\fP< dim > &var, \fBVARIABLE_FLAG\fP output)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "const \fBPropertyDatabase\fP< dim > & \fBp_ref\fP"
.br
.ti -1c
.RI "std::string \fBname_\fP"
.br
.ti -1c
.RI "std::string \fBresult_property_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > > \fBoperand_list_\fP"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::iterator \fBresult_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::MohrCoulombFailure< dim >"Using the current local stress state stored on the model in the variable "stress", this \fBInterrelation\fP subclass computes the failure criterion 'failure' performing a Mohr Coulomb analysis, but without consideration of the fluid pressure\&.

.PP
To apply this interrelation the following discretised variables need to be defined:

.PP
"stress", "mean stress", "cohesion", "failure"\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::MohrCoulombFailure\fP< dim >::Calculate ()\fR [virtual]\fP"

.PP
computes the local value of result property "failure" which gets written back to the model Zienkiewicz II, p\&. 89, modified Mohr-Coulomb envelope with smooth boundaries\&.

.PP
Yielding can occur when F >= 0, the material is described only in terms of its friction angle and cohesion\&. 
.PP
Reimplemented from \fBcsmp::Interrelation< dim >\fP\&.
.SS "template<uint32_t dim> double \fBcsmp::MohrCoulombFailure\fP< dim >::DeviatoricStress (const \fBTensorVariable\fP< dim > & ts, double & t_stress_invariant)\fR [protected]\fP"

.PP
computes the shear-stress related stress invariant, returning into second argument; method difference between sigma1 and sigma3 Zienkiewitz II, p\&. 61 bottom, p\&. 62 top, sigma-dash = deviatoric stress\&. 
.SS "template<uint32_t dim> double \fBcsmp::MohrCoulombFailure\fP< dim >::G_OfTheta (double theta)\fR [protected]\fP"

.PP
computes stress state invariance, see Zienkiewitz II, p\&. 89 Zienkiewitz II, p\&. 89\&. 
.SS "template<uint32_t dim> double \fBcsmp::MohrCoulombFailure\fP< dim >::MeanStress (const \fBTensorVariable\fP< dim > & ts)\fR [protected]\fP"

.PP
average of the magnitude of the principal stress Smith & Griffiths, p\&. 233\&. 
.SS "template<uint32_t dim> double \fBcsmp::MohrCoulombFailure\fP< dim >::Theta (const \fBTensorVariable\fP< dim > & ts, double t_stress_invariant)\fR [protected]\fP"

.PP
computes stress state invariance theta (Smith & Griffith, 2014, p\&. 236 calculate lode angle, Smith & Griffiths, p\&. 233, computed in radians 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
