.TH "csmp::ThermalVisitor< dim >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::ThermalVisitor< dim > \- Computes PT-dependent fluid properties for flow simulations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ThermalVisitor\&.h>\fP
.PP
Inherits \fBcsmp::Visitor< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThermalVisitor\fP (\fBModel\fP< dim > &, std::vector< std::string > *to_initialize_keys=nullptr)"
.br
.ti -1c
.RI "\fBThermalVisitor\fP (\fBModel\fP< dim > &model, \fBIndex\fP nCPT_key, \fBIndex\fP cp_fluid_key, \fBIndex\fP cp_rock_key, \fBIndex\fP rho_rock_key, \fBIndex\fP t_key, \fBIndex\fP p_key, \fBIndex\fP hl_key, \fBIndex\fP hCl_key, \fBIndex\fP hClp_key, \fBIndex\fP hVl_key, \fBIndex\fP mt_key, \fBIndex\fP rl_key, \fBIndex\fP mu_key, \fBIndex\fP nphi_key, \fBIndex\fP nQ_key, \fBIndex\fP dRho_key, \fBIndex\fP volume_factor_key, \fBIndex\fP beta_rock_key, \fBIndex\fP beta_tot_key, \fBIndex\fP beta_fluid_key)"
.br
.ti -1c
.RI "void \fBSetInitialProperties\fP (\fBModel\fP< dim > *model)"
.br
.ti -1c
.RI "void \fBApplyTemperatureBoundaryConditionsToTransportedVariables\fP ()"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBNode\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBModel\fP< dim > *)"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBVisitor\fP (\fBPLACEMENT\fP level=MODEL, \fBPLACEMENT\fP target=ELEMENT)"
.br
.ti -1c
.RI "void \fBApplicationLevel\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApplicationTarget\fP (\fBPLACEMENT\fP p)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationTarget\fP () const"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBRegion\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBSplitBoundary\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBElement\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBInterFace\fP< dim > *)"
.br
.ti -1c
.RI "virtual void \fBVisit\fP (\fBEdge\fP< dim > *)"
.br
.ti -1c
.RI "bool \fBVerbose\fP ()"
.br
.ti -1c
.RI "void \fBVerbose\fP (bool verbose)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBcsmp::Visitor< dim >\fP
.in +1c
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_target_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::ThermalVisitor< dim >"Computes PT-dependent fluid properties for flow simulations\&. 


.PP
\fBAuthor\fP
.RS 4
Thomas Driesner, ETH Zuerich 
.RE
.PP
.SH "Contact"
.PP
thomas.driesner@erdw.ethz.ch 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::ThermalVisitor\fP< dim >::SetInitialProperties (\fBModel\fP< dim > * model)\fR [virtual]\fP"
Loops over the nodes writing basis fluid (from H2O-EOS) and rock properties there\&.

.PP
\fBTodo\fP
.RS 4
if this visitor gets applied to another region than the model, all hell will break loose! - fix
.RE
.PP

.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::ThermalVisitor\fP< dim >::Visit (\fBModel\fP< dim > * )\fR [virtual]\fP"

.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.
.SS "template<uint32_t dim> void \fBcsmp::ThermalVisitor\fP< dim >::Visit (\fBNode\fP< dim > * n)\fR [virtual]\fP"
This is the key part of this \fBNode\fP visitor\&. for wells
.PP
Reimplemented from \fBcsmp::Visitor< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
