.TH "csmp::SAMG_Profile" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SAMG_Profile
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcsmp::SteadyStateDiffusionProfile< dim >\fP, and \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransProfile< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBSolve\fP (double modelTime)=0"
.br
.RI "Solve for matrix equation\&. "
.ti -1c
.RI "std::string \fBFileDumpName\fP () const"
.br
.ti -1c
.RI "void \fBFileDumpName\fP (const std::string &dumpFileName)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdumpFileName_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual bool csmp::SAMG_Profile::Solve (double modelTime)\fR [pure virtual]\fP"

.PP
Solve for matrix equation\&. 
.PP
Implemented in \fBcsmp::SteadyStateDiffusionProfile< dim >\fP, and \fBcsmp::TwoPhaseImplicitNodeCenteredFVTransProfile< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
