.TH "csmp::Accumulator< dim, USER >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Accumulator< dim, USER >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Accumulator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.RI "initalises sparse matrix and vector, taking into account how many solution variables there are "
.ti -1c
.RI "void \fBAccumulate\fP (double time_increment=1\&.)"
.br
.RI "accumuates finite volume / hybride FVM _ FEM transport equation into global system "
.ti -1c
.RI "void \fBBalanceFlowsThroughTruncatedBoundaryFiniteVolumes\fP (\fBSparseMatrix\fP &lhs, std::vector< double > &rhs, double time_increment=1\&.)"
.br
.RI "compensate (+) balance at inflow boundaries, (-) balance at outflow boundaries, and any potential divergence of flow at no-flow boundaries "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class USER>
.br
class csmp::Accumulator< dim, USER >"\fBAccumulator\fP Operations
.IP "\(bu" 2
SetupSystem()
.IP "\(bu" 2
AccumulateInteriorByFV( operator, operation )
.IP "\(bu" 2
AccumulateInteriorByFE( range )
.IP "\(bu" 2
LateAccumulateInteriorByFV()
.IP "\(bu" 2
LateAccumulateInteriorByFE()
.IP "\(bu" 2
AccumulatePerimeterByFV( operator, operation )
.IP "\(bu" 2
AccumulatePerimeterByFE( range )
.IP "\(bu" 2
LateAccumulatePerimeterByFV()
.IP "\(bu" 2
LateAccumulatePerimeterByFE()= Attributes
.IP "\(bu" 2
halo elements
.PP

.PP
\fBAttention\fP
.RS 4
the \fBAccumulator\fP uses stencil accumulation for the interior and finite volume accumulation for its perimeter\&. 

.PP
the order in which LHS and RHS are accumulated is defined in \fBOperation\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::Accumulator\fP< dim, USER >::Accumulate (double time_increment = \fR1\&.\fP)"

.PP
accumuates finite volume / hybride FVM _ FEM transport equation into global system Default sequence
.IP "1." 4
pore volume in diagonal of LHS
.IP "2." 4
upwinded flows coupling diagonal with off-diagonal and outgoing flows into diagonal
.IP "3." 4
pore volume times concentration into rhs
.IP "4." 4
sources and sinks into rhs
.PP

.PP
Inside of the domain and for the halo stencils, accumulation by stencil is used, while truncated boundary FVs need to be accumulated finite volume by finite volume (only certain terms) 
.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::Accumulator\fP< dim, USER >::SetUp ()"

.PP
initalises sparse matrix and vector, taking into account how many solution variables there are Should use information from equation to define computational problem (solution variables etc\&.) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
