.TH "csmp::FV_Parameter" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FV_Parameter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FV_Parameter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFV_Parameter\fP (size_t sectors, size_t facets, uint32_t dim, bool with_normals=false)"
.br
.ti -1c
.RI "void \fBResize\fP (size_t sectors, size_t facets, uint32_t dim, bool with_normals=false)"
.br
.ti -1c
.RI "void \fBSectorVolume\fP (size_t sector, double vol)"
.br
.ti -1c
.RI "void \fBFacetArea\fP (size_t facet, double area)"
.br
.ti -1c
.RI "void \fBFacetNormal\fP (size_t facet, const std::vector< double > &fnxyz)"
.br
.ti -1c
.RI "void \fBFacetNormalVelocity\fP (size_t facet, double flux)"
.br
.ti -1c
.RI "void \fBInitialize\fP (size_t facet, double flux, double area)"
.br
.ti -1c
.RI "size_t \fBSectors\fP () const"
.br
.ti -1c
.RI "size_t \fBFacets\fP () const"
.br
.ti -1c
.RI "double \fBSectorVolume\fP (size_t sector) const"
.br
.ti -1c
.RI "double \fBFacetArea\fP (size_t facet) const"
.br
.ti -1c
.RI "double \fBFacetNormalVelocity\fP (size_t facet) const"
.br
.ti -1c
.RI "double \fBFacetNormalComponent\fP (size_t facet, size_t x_or_y_or_z) const"
.br
.ti -1c
.RI "double \fBFacetNormalProjection\fP (size_t facet, const std::vector< double > &cxyz) const"
.br
.RI "dot product fn \&. vc "
.ti -1c
.RI "double \fBFacetNormalProjection\fP (size_t facet, const \fBVectorVariable\fP< 1U > &cxyz) const"
.br
.RI "universal versions of projection functions "
.ti -1c
.RI "double \fBFacetNormalProjection\fP (size_t facet, const \fBVectorVariable\fP< 2U > &cxyz) const"
.br
.ti -1c
.RI "double \fBFacetNormalProjection\fP (size_t facet, const \fBVectorVariable\fP< 3U > &cxyz) const"
.br
.ti -1c
.RI "size_t \fBBytes\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
storage for the sector volumes, facet area and projected velocities so that these do not have to be recompute each timecrement 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
