.TH "csmp::SplitBoundary_Test" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::SplitBoundary_Test
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SplitBoundary_Test\&.h>\fP
.PP
Inherits \fBcsmp::Test\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBTest_InitialiseSKUA_Model\fP ()"
.br
.RI "initialises 2022 SKUA model with properties from binary version of \fBVSet\fP "
.ti -1c
.RI "bool \fBTest_InputNodePropertyValue\fP (const char *mesh_file)"
.br
.RI "tests that all properties are properly added to nodes on split boundary "
.ti -1c
.RI "bool \fBTest_Area_and_SurfaceIntegral\fP (const char *mesh_file)"
.br
.RI "integrates the property over the boundary line or surface "
.ti -1c
.RI "bool \fBTest_FacingDirection\fP ()"
.br
.RI "returns location of split boundary relative to adjacent region "
.ti -1c
.RI "bool \fBTest_PerimeterCalculation\fP ()"
.br
.RI "outputs length of perimeter curve of a 3D split boundary; no meaning in 1 or 2D models "
.ti -1c
.RI "bool \fBTest_SurfaceIntegral\fP ()"
.br
.RI "integrates the property over the boundary line or surface "
.ti -1c
.RI "bool \fBTest_HigherDimensionalNeighbors\fP ()"
.br
.RI "do all interfaces have higher dimensional neighbors "
.ti -1c
.RI "bool \fBTest_Manifolds\fP ()"
.br
.ti -1c
.RI "bool \fBTest_SingleParameterNode\fP ()"
.br
.RI "is there only a single node along the perimeter of a split boundary "
.ti -1c
.RI "bool \fBTest_IntegrityOfSplitBoundaryFromBinaryFile\fP ()"
.br
.RI "are all of the above operations still valid for a \fBSplitBoundary\fP read from binary file? "
.ti -1c
.RI "template<uint32_t dim> void \fBLoadModel\fP (const std::string &model_name)"
.br
.ti -1c
.RI "template<uint32_t dim> void \fBLoadModel\fP (const std::string &model_name, std::vector< std::string > &regions)"
.br
.ti -1c
.RI "template<uint32_t dim> void \fBLoadContiguousModel\fP (const std::string &model_name, std::vector< std::string > &fractures)"
.br
.ti -1c
.RI "void \fBInputFromFile\fP (const char *file_name, std::set< std::string > &fractures_basic_set)"
.br
.RI "reading fault modeling input data "
.ti -1c
.RI "void \fBInputFromFile\fP (const char *file_name, std::vector< std::string > &fractures)"
.br
.ti -1c
.RI "void \fBOutputToFile\fP (const char *file_name, const std::vector< std::string > &fractures)"
.br
.RI "writing fault modeling input data into text file "
.ti -1c
.RI "void \fBOutputToFile\fP (const char *file_name, const std::set< std::string > &fractures)"
.br
.ti -1c
.RI "template<uint32_t dim> void \fBEstablishContiguousRegionsList\fP (\fBModel\fP< dim > &model, const std::set< std::string > &interface_basic_set, std::set< std::string > &interface_sets)"
.br
.ti -1c
.RI "template<uint32_t dim> void \fBEstablishContiguousRegionsList\fP (\fBModel\fP< dim > &model, const std::set< string > &interface_basic_set, std::set< string > &interface_sets)"
.br
.RI "Input name of regions to split\&. "
.in -1c

Public Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (std::ostream *osptr=0)"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const std::ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (std::ostream *osptr)"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string testName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBhasName\fP () const"
.br
.ti -1c
.RI "void \fBdo_succeed\fP ()"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "void \fBdo_equal\fP (double expr, double value, double tol, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_test\fP (bool cond, const std::string &lbl, const char *fname, long lineno)"
.br
.ti -1c
.RI "void \fBdo_fail\fP (const std::string &lbl, const char *fname, long lineno)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Test\fP
.in +1c
.ti -1c
.RI "const char * \fBprefix_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSplitBoundary_Test\fP of the functionality of individual SpitBoundary objects as opposed to their creation (see \fBSplitBoundaryInterface_Test\fP) or that of the \fBInterFace\fP objects that the \fBSplitBoundary\fP objects consist of (see \fBInterFace_Test\fP)\&.

.PP
\fBAttention\fP
.RS 4
this also performs test on \fBSplitBoundary\fP objects created in ANSYS
.RE
.PP
.SH "Performed Here (2D and 3D)"
.PP
.IP "\(bu" 2
do all interfaces have higher dimensional neighbors
.IP "\(bu" 2
do correspoding nodes coincide
.IP "\(bu" 2
is there only a single node along the perimeter of a split boundary
.IP "\(bu" 2
are all of the above operations still valid for a \fBSplitBoundary\fP read from binary file?

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
26/1/2020 
.RE
.PP

.PP

.SH "Member Function Documentation"
.PP 
.SS "void csmp::SplitBoundary_Test::run ()\fR [virtual]\fP"

.PP
Implements \fBcsmp::Test\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
