.TH "csmp::MeshPatch< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::MeshPatch< dim >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MeshPatch\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeshPatch\fP (\fBCELL_SHAPE\fP cs)"
.br
.RI "specify whether this is a volume, surface or line element patch "
.ti -1c
.RI "size_t \fBBuildInterveningPatch\fP (const std::vector< std::pair< std::pair< \fBElement\fP< dim > *, uint32_t >, std::pair< \fBElement\fP< dim > *, uint32_t > > > &, bool copy_nodes, std::vector< \fBNode\fP< dim > * > perimeter_node_ptrs)"
.br
.RI "creates an interconnected element patch from the shared faces of the supplied elements; replicates nodes upon request, and returns perimeter nodes and size of patch "
.ti -1c
.RI "size_t \fBCellTypes\fP () const"
.br
.RI "how many different finite element types the patch contains "
.ti -1c
.RI "\fBCELL_SHAPE\fP \fBCellGeometry\fP () const"
.br
.RI "whether this is a LINE, SURFACE or VOLUME mesh "
.ti -1c
.RI "size_t \fBCells\fP () const"
.br
.ti -1c
.RI "size_t \fBNodes\fP () const"
.br
.ti -1c
.RI "plf::colony< \fBElement\fP< dim > >::iterator \fBElementsBegin\fP ()"
.br
.ti -1c
.RI "plf::colony< \fBElement\fP< dim > >::iterator \fBElementsEnd\fP ()"
.br
.ti -1c
.RI "plf::colony< \fBNode\fP< dim > >::iterator \fBNodesBegin\fP ()"
.br
.ti -1c
.RI "plf::colony< \fBNode\fP< dim > >::iterator \fBNodesEnd\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::MeshPatch< dim >"Contiguous mesh patch that can, but does not have to be integrated into a \fBModel\fP\&. The idea is to temporarily store parts of a mesh during rebuilding operations; Size info is used also to keep number information uptodate\&.

.PP
\fBAuthor\fP
.RS 4
SKM 
.RE
.PP
\fBDate\fP
.RS 4
23/5/21 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> size_t \fBcsmp::MeshPatch\fP< dim >::BuildInterveningPatch (const std::vector< std::pair< std::pair< \fBElement\fP< dim > *, uint32_t >, std::pair< \fBElement\fP< dim > *, uint32_t > > > & , bool copy_nodes, std::vector< \fBNode\fP< dim > * > perimeter_node_ptrs)"

.PP
creates an interconnected element patch from the shared faces of the supplied elements; replicates nodes upon request, and returns perimeter nodes and size of patch < inside element and its outside face number outside element and inside face number

.PP
Creates an interconnected element patch from the shared faces of the supplied elements\&. There is no property storage associated with these elements from the start\&. The elements are rather barebone\&.

.PP
\fBParameters\fP
.RS 4
\fIinput_elmts\fP pairs of highest-dim elements that share a face that will be turned into a new lower-dimensional element 
.br
\fIcopy_nodes\fP the Elements already share nodes, but light copies of these are made when true 
.br
\fIperimeter_node_ptrs\fP whether copies are made or not, the method returns vector of pointers of the perimeter nodes of the new element patch 
.RE
.PP
\fBReturns\fP
.RS 4
the number of new elements in the patch 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
