.TH "csmp::FluxEvaluator< dim, USER >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::FluxEvaluator< dim, USER > \- Policy class that computes fluxes across finite-volume facets\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdvective_O1_FluxesAndBalances\fP (\fBElement\fP< dim > *const) const"
.br
.RI "computes F = (A_i vD \&. n_i) and its products with the upstream C0 on all facets, also computes FV flux balances "
.ti -1c
.RI "void \fBAdvective_O1_FluxesAndBalances\fP (\fBNode\fP< dim > *const) const"
.br
.RI "computes F = (A_i vD \&. n_i) and its products with transported variables, also computes FV flux balances "
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBVolumetricFlowAndTransportVariableFluxBalances\fP (\fBModelSubDomain\fP< dim, CELL > &, std::vector< CELL< dim > * > &halo_stencils)"
.br
.RI "computes volumetric flows and (chemical) fluxes across facets using FacetFlux (facet flux) and stores them in target region "
.ti -1c
.RI "void \fBFluxBalancesAtBoundary\fP (\fBNode\fP< dim > *const) const"
.br
.RI "computes flux balances on boundary FVs, using precomputed facet fluxes; volumetric balances are set to zero "
.ti -1c
.RI "void \fBTransportVariableFluxes\fP (\fBElement\fP< dim > *const) const"
.br
.RI "computes first-order facet fluxes, F = ff * C0; ff=(pre-computed) volumetric flow, C0=transport variable "
.ti -1c
.RI "void \fBTransportVariableFluxesAndBalances\fP (\fBElement\fP< dim > *const) const"
.br
.RI "like \fBTransportVariableFluxes()\fP, but computes FV balances of F as well, storing them in 'accumulation'\&. "
.ti -1c
.RI "void \fBFluxBalancesFromFacetFluxes\fP (\fBNode\fP< dim > *const) const"
.br
.RI "computes balance of transport variable fluxes from precomputed facet fluxes and transport variable "
.ti -1c
.RI "double \fBFluxBalanceAndOutFlow\fP (\fBNode\fP< dim > *const) const"
.br
.RI "stores FV flux balances computed from current facet fluxes and C0 concentrations; returns outflow from cell "
.ti -1c
.RI "double \fBInFlow\fP (const \fBNode\fP< dim > *const) const"
.br
.RI "computes the volumetric flow into the current cell; "
.ti -1c
.RI "double \fBOutFlow\fP (const \fBNode\fP< dim > *const) const"
.br
.RI "computes the volumetric flow outside of the current cell; "
.ti -1c
.RI "double \fBVolumetricFlowBalance\fP (const \fBNode\fP< dim > *const) const"
.br
.RI "computes the volumetric flow outside of the current cell; "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class USER>
.br
class csmp::FluxEvaluator< dim, USER >"Policy class that computes fluxes across finite-volume facets\&. 

Part of trial implementation of Colleoli transport scheme\&. 
.PP
\fBAuthor\fP
.RS 4
Stephan K\&. Matthai 
.RE
.PP
\fBVersion\fP
.RS 4
1a 
.RE
.PP
\fBDate\fP
.RS 4
21/2/2013 
.RE
.PP
\fBPrecondition\fP
.RS 4
high-level class depending on CSMP++ API 
.RE
.PP
\fBCopyright\fP
.RS 4
Stephan K\&. Matthai
.RE
.PP
The transported variable on current and future time level is denoted as C0 and C1, respectively\&.

.PP
All interim results are stored on the model\&.

.PP
\fBTodo\fP
.RS 4
double FluxBalanceFromGradP_K_mu_C0( Node<dim>* const ) const; 

.PP
double FluxBalanceFromGradP_KK_mu_C0( Node<dim>* const ) const; 

.PP
include dispersion and options for diffusive fluxes
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::FluxEvaluator\fP< dim, USER >::Advective_O1_FluxesAndBalances (\fBElement\fP< dim > * const eptr) const"

.PP
computes F = (A_i vD \&. n_i) and its products with the upstream C0 on all facets, also computes FV flux balances Computes A_i vD \&. n_i for all facets and its product with the upstream concentrations\&. Stores 'facet flux' and 'facet flux concentration' product variables\&. Accumulates the flux balance and flux concentration balances in the corresponding node variables\&.

.PP
\fBAttention\fP
.RS 4
vD can be used directly as interstitial velocity since the FV is scaled by porosity

.PP
the thickness of lower-dimensional elements is taken into account

.PP
, assumes that the FV variables 'flux balance' and 'new concentration' were zeroed out before\&.
.RE
.PP
@tested OK SKM 17/8/19 
.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::FluxEvaluator\fP< dim, USER >::Advective_O1_FluxesAndBalances (\fBNode\fP< dim > * const nd_ptr) const"

.PP
computes F = (A_i vD \&. n_i) and its products with transported variables, also computes FV flux balances COMPUTING FLUX BALANCE FROM VELOCITY AND NORMAL AND FACET AREA\&.

.PP
The divergence of the transport velocity on the current FV = node, and its product with the transport variable is stored\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::FluxEvaluator\fP< dim, USER >::FluxBalanceAndOutFlow (\fBNode\fP< dim > * const nptr) const"

.PP
stores FV flux balances computed from current facet fluxes and C0 concentrations; returns outflow from cell Like \fBFluxBalancesFromFacetFluxes()\fP, but returns the current outflow from the cell\&.

.PP
The latter is valid only for intact finite volumes (not at model boundary)\&. Else, a ficticious outflow is detected at inflow boundaries\&.

.PP
\fBAttention\fP
.RS 4
this method relies on precomputed facet fluxes\&. 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::FluxEvaluator\fP< dim, USER >::FluxBalancesAtBoundary (\fBNode\fP< dim > * const nd_ptr) const"

.PP
computes flux balances on boundary FVs, using precomputed facet fluxes; volumetric balances are set to zero From precomputed facet fluxes, \fBFluxBalancesAtBoundary()\fP computes:

.PP
.IP "0." 4
Nothing for FVs on the model boundary with Dirichlet concentration constraints\&.
.IP "1." 4
facet fluxes and flux balances of intact perimeter finite volumes that are not on the model boundary
.IP "2." 4
accumulation of facet flux-concentration products
.IP "3." 4
inflow if the the perimeter finite volume is truncated by the model boundary\&. This is determined from the AtBoundary() flag (flag!=NOT)\&.
.PP

.PP
In summary, this method computes flux balances and concentration-facet flux products where possible, at sliced boundaries inflow (+) concentration products are stored to C1\&. At such boundaries the influx is found from the flux balance and the FV cell's concentration\&.

.PP
\fBAttention\fP
.RS 4
This method is only for perimeter nodes 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::FluxEvaluator\fP< dim, USER >::FluxBalancesFromFacetFluxes (\fBNode\fP< dim > * const nptr) const"

.PP
computes balance of transport variable fluxes from precomputed facet fluxes and transport variable Computes and returns FV flux balance computed from pre-calculated thickness-weighted facet fluxes\&. The divergence of the volumetric flow is stored into the variable 'flux balance'\&. The volumetric flow * upstream concentration product is stored into 'new concentration'\&. Both, the flux balance and its product with concentration are stored on the node\&.

.PP
\fBAttention\fP
.RS 4
this method relies on precomputed facet fluxes\&. 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::FluxEvaluator\fP< dim, USER >::InFlow (const \fBNode\fP< dim > * const nptr) const"

.PP
computes the volumetric flow into the current cell; 
.PP
\fBReturns\fP
.RS 4
inflow which is always positive
.RE
.PP
Like \fBFluxBalanceAndOutFlow()\fP, but computes only the volumetric inflow into the cell\&.

.PP
The latter is valid only for intact finite volumes (not at model boundary)\&. Else, a ficticious inflow is detected at inflow boundaries\&.

.PP
\fBAttention\fP
.RS 4
this method relies on precomputed facet fluxes\&. 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::FluxEvaluator\fP< dim, USER >::OutFlow (const \fBNode\fP< dim > * const nptr) const"

.PP
computes the volumetric flow outside of the current cell; 
.PP
\fBReturns\fP
.RS 4
outflow which is always positive
.RE
.PP
Like \fBFluxBalanceAndOutFlow()\fP, but computes only the volumetric outflow from the cell\&.

.PP
The latter is valid only for intact finite volumes (not at model boundary)\&. Else, not the complete outflow may be detected at out-flow boundaries\&.

.PP
\fBAttention\fP
.RS 4
this method relies on precomputed facet fluxes\&. 
.RE
.PP

.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::FluxEvaluator\fP< dim, USER >::TransportVariableFluxes (\fBElement\fP< dim > * const eptr) const"

.PP
computes first-order facet fluxes, F = ff * C0; ff=(pre-computed) volumetric flow, C0=transport variable Computes first-order facet fluxes, F = ff * C0 = (pre-computed) volumetric flow upstream C0 products on all facets

.PP
@apply this method to the interior and halo stencils\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> void \fBcsmp::FluxEvaluator\fP< dim, USER >::TransportVariableFluxesAndBalances (\fBElement\fP< dim > * const eptr) const"

.PP
like \fBTransportVariableFluxes()\fP, but computes FV balances of F as well, storing them in 'accumulation'\&. Also computes the outflow from each FV cell\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> template<template< uint32_t > class CELL> template void \fBcsmp::FluxEvaluator\fP< dim, USER >::VolumetricFlowAndTransportVariableFluxBalances (\fBModelSubDomain\fP< dim, CELL > & , std::vector< CELL< dim > * > & halo_stencils)"

.PP
computes volumetric flows and (chemical) fluxes across facets using FacetFlux (facet flux) and stores them in target region Computes volumetric flows and (chemical) fluxes across facets using FacetFlux (facet flux) and stores them in target region

.PP
Volumetric facet flow and (chemical) flux calculation (element by element), for all elements in the domain

.PP
Facet fluxes in the FV sectors outside the domain are considered\&. by Advective_O1_FluxesBoundary()\&. This method also writes the correct volumetric flow balances onto the nodes on the perimeter\&. 
.SS "template<uint32_t dim, template< uint32_t > class USER> double \fBcsmp::FluxEvaluator\fP< dim, USER >::VolumetricFlowBalance (const \fBNode\fP< dim > * const nptr) const"

.PP
computes the volumetric flow outside of the current cell; 
.PP
\fBReturns\fP
.RS 4
outflow which is always positive
.RE
.PP
Meters cubed, going in versus out\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
