.TH "csmp::Limiter< dim >" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::Limiter< dim > \- Limiting the value of a variable to a specified range\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Limiter\&.h>\fP
.PP
Inherits \fBcsmp::Interrelation< dim >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLimiter\fP (const \fBPropertyDatabase\fP< dim > &p, const char *prop, double min_value, double max_value)"
.br
.ti -1c
.RI "void \fBCalculate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "\fBInterrelation\fP (const \fBPropertyDatabase\fP< dim > &p)"
.br
.ti -1c
.RI "void \fBName\fP (const char *s)"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBApplicationLevel\fP () const"
.br
.ti -1c
.RI "void \fBApply\fP (\fBModel\fP< dim > &)"
.br
.ti -1c
.RI "template<template< uint32_t > class CELL> void \fBApply\fP (\fBModelSubDomain\fP< dim, CELL > &)"
.br
.RI "a simplex is any geometrical association of points "
.ti -1c
.RI "bool \fBResultWithinRange\fP ()"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::const_iterator \fBOperandsBegin\fP () const"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::const_iterator \fBOperandsEnd\fP () const"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::iterator \fBResult\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "\fBOperand\fP< dim > & \fBGlobalProperty\fP (const char *var)"
.br
.ti -1c
.RI "void \fBResultProperty\fP (const char *var)"
.br
.ti -1c
.RI "void \fBOutputCondition\fP (\fBOperand\fP< dim > &var, \fBVARIABLE_FLAG\fP output)"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::Interrelation< dim >\fP
.in +1c
.ti -1c
.RI "const \fBPropertyDatabase\fP< dim > & \fBp_ref\fP"
.br
.ti -1c
.RI "std::string \fBname_\fP"
.br
.ti -1c
.RI "std::string \fBresult_property_\fP"
.br
.ti -1c
.RI "\fBPLACEMENT\fP \fBapplication_level_\fP"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > > \fBoperand_list_\fP"
.br
.ti -1c
.RI "std::map< std::string, \fBOperand\fP< dim > >::iterator \fBresult_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim>
.br
class csmp::Limiter< dim >"Limiting the value of a variable to a specified range\&. 


.PP
\fBAuthor\fP
.RS 4
Philipp Weis, ETH Zuerich 
.RE
.PP
.SH "Contact"
.PP
philipp.weis@erdw.ethz.ch

.PP
@changes changes Latest Changes 
.br
.SH "Motivation"
.PP
Designed to keep variable within the validity of equation of state\&.
.SH "Usage"
.PP
Used within the CVFEM scheme (Weis et al\&., Geofluids, 2014)\&. Use with care, as the values are changed somewhat arbitrarily, which may lead to unwanted behavior\&.

.PP
.PP
.nf
The interralation reads in a variable and checks whether the value lies within the specified range\&.
If not, the value is corrected to the minimum or maximum value, respectively\&.
.fi
.PP
.SH "Dependencies"
.PP
.SH "Known issues"
.PP
Currently, the user does not receive any information whether the values are changed or not\&.
.SH "Testing"
.PP
testing was done in the period before publication in 2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<uint32_t dim> \fBcsmp::Limiter\fP< dim >::Limiter (const \fBPropertyDatabase\fP< dim > & p, const char * prop, double min_value, double max_value)"
custom constructor 
.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim> void \fBcsmp::Limiter\fP< dim >::Calculate ()\fR [virtual]\fP"
Limit values to specified range between min_value and max_value 
.PP
Reimplemented from \fBcsmp::Interrelation< dim >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
