.TH "csmp::H2OThermalEquilibrator" 3 "Thu May 29 2025 14:52:19" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::H2OThermalEquilibrator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <H2OThermalEquilibrator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBH2OThermalEquilibrator\fP (const double &external_mass_rock, const double &external_cp_rock, const double &external_rho_rock, const double &external_porosity, const double &external_mass_fluid, const double &external_t_previous, const double &external_p_current, const double &external_H_current, const double &external_H_previous, const bool &fixed_external_t, const double &t_fix, const double &external_t_diff)"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBLiquid\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBVapor\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBBulk\fP ()"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBReportLiquidProperties\fP (const double &t, const double &p, const double &\fBh\fP)"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBReportVaporProperties\fP (const double &t, const double &p, const double &\fBh\fP)"
.br
.ti -1c
.RI "\fBFluidproperties\fP \fBReportBulkProperties\fP (const double &t, const double &p, const double &\fBh\fP)"
.br
.ti -1c
.RI "int \fBn_iterations\fP ()"
.br
.ti -1c
.RI "int \fBEqType\fP ()"
.br
.ti -1c
.RI "bool \fBEquilibrated\fP ()"
.br
.ti -1c
.RI "bool \fBFatal\fP ()"
.br
.ti -1c
.RI "void \fBTemperatureDependentHeatCapacityRock\fP (double cpr_min_ext, double t_min_ext, double cpr_max_ext, double t_max_ext)"
.br
.ti -1c
.RI "double \fBTemperatureDependent_cpr\fP (double T)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Thomas Driesner, ETH Zuerich 
.RE
.PP
.SH "Contact"
.PP
thomas.driesner@erdw.ethz.ch
.SH "Motivation"
.PP
\fBH2OThermalEquilibrator\fP finds the temperature at which rock and a pure H2O fluid are in thermal equilibrium at a given pressure\&. This is done by an isobaric bisection iteration through the water phase diagram, which compares the total enthalpy at a test temperature t_eq (H_test = mass_rock*enthalpy_rock(t_eq) + mass_fluid*enthalpy_fluid(t_eq) ) with the enthalpy value H_current_eq that was provided by the transport code (specifically: H2OPropertiesVisitor)\&.

.PP
Currently (as of January 28, 2011) iteration starts from an upper temperature limt tmax at 1000C and a lower one at 5C and follows true bisection\&. The actual computation of fluid properties as well as determination of fluid phase state is done by an \fBH2OFluidProperties\fP object\&.
.SH "Usage"
.PP
Instantiate \fBH2OThermalEquilibrator\fP with references to various properties seen as constructor arguments\&. It is YOUR responsibility to make sure they are properly up to date when \fBH2OThermalEquilibrator\fP ist called\&.

.PP
The main calls are Liquid(), Vapor(), and Bulk()\&. Calling one of them triggers a full equilibration (except if the values of those properties referenced in the constructor havn't changed, then the last equilibration results are assumed to be correct)\&. It returns fluid property values as \fBFluidproperties\fP objects (see documentation there for full property set)\&. These fluidproperties refer to the phase indicate by the name of the function call\&.

.PP
Another set of calls - ReportLiquidProperties(const double& t, const double& p, const double& h), ReportVaporProperties(const double& t, const double& p, const double& h), ReportBulkProperties(const double& t, const double& p, const double& h) - lets you query the properties for a desired combination of temperature, pressure and specific fluid enthalpy\&. Use with care because getting the logic for this right in a simulation context is non-trivial\&. 
.br
 
.SH "Dependencies"
.PP
requires "H2OFluidProperties\&.h", "Fluidproperties\&.h", "States\&.h"
.SH "Known issues"
.PP
Pressure() still returns values in bars, a legacy from the SoWat development\&. Composition() is in mole fraction NaCl, to convert to other units, the functions in "ConvertConcentrationUnitsNaCl\&.h" may be useful
.SH "Testing"
.PP
Testing is in progress\&. Besides general functionality, the following aspects need to be tested:

.PP
.IP "\(bu" 2
Convergence is assumed once the difference (H_test-H_current_eq) divided by the fluid mass is less than 10^-4 of the fluid's specific enthalpy\&. Wether a tighter criterion is necessary (and can successfully be fulfilled by this method) remains subject to further testing\&.
.IP "\(bu" 2
Care has been taken that the \fBH2OFluidProperties\fP object catches problems arising from numerical precision when being close to phase boundaries (e\&.g\&. when t_eq is within numerical precision identical to the boiling temperature and a vapor state is determined although the actual state is liquid)\&. However, this has not been tested in great detail\&. Further details will be added to this section with time\&.
.IP "\(bu" 2
The current bisection scheme is likely to be small\&. If a Newton-like component is added, the treatment of rock heat capacity / enthalpy and the prediction of tmin / tmax from t_eq may become non-trivial 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
