.TH "csmp::EclipseTextFileInterface< STREAM >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::EclipseTextFileInterface< STREAM > \- parses the ECLIPSE text file(s) into streams  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <EclipseTextFileInterface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEclipseTextFileInterface\fP (size_t max_line_length=256)"
.br
.ti -1c
.RI "bool \fBReadFile\fP (std::ifstream &ifs, STREAM *, bool(STREAM::*IsCommentLineFunction)(char *), bool(STREAM::*ReadFunction)(std::ifstream &, char *, size_t, std::set< std::string > &, std::string &, std::vector< std::string > &), bool fail_for_unknown_keyword=true)"
.br
.ti -1c
.RI "bool \fBReadFile\fP (std::ifstream &ifs, STREAM *, bool(*IsCommentLineFunction)(char *), bool(STREAM::*ReadFunction)(std::ifstream &, char *, size_t, std::set< std::string > &, std::string &, std::vector< std::string > &), bool fail_for_unknown_keyword=true)"
.br
.ti -1c
.RI "bool \fBReadFile\fP (std::ifstream &ifs, STREAM *, bool(STREAM::*IsCommentLineFunction)(char *), bool(STREAM::*ReadFunction)(std::ifstream &, char *, size_t))"
.br
.ti -1c
.RI "bool \fBReadFile\fP (std::ifstream &ifs, STREAM *, bool(*IsCommentLineFunction)(char *), bool(STREAM::*ReadFunction)(std::ifstream &, char *, size_t))"
.br
.ti -1c
.RI "bool \fBFindKeyword\fP (const std::string &)"
.br
.ti -1c
.RI "void \fBAddKeyword\fP (const std::string &)"
.br
.ti -1c
.RI "void \fBAddKeywords\fP (const std::set< std::string > &)"
.br
.ti -1c
.RI "void \fBClearKeywords\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::set< std::string > \fBkeywords_\fP"
.br
.ti -1c
.RI "std::string \fBkeyword_\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBkeyword_parameters_\fP"
.br
.ti -1c
.RI "size_t \fBline_length_\fP"
.br
.ti -1c
.RI "char * \fBtext_line_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class STREAM>
.br
class csmp::EclipseTextFileInterface< STREAM >"parses the ECLIPSE text file(s) into streams 


.PP
\fBAuthor\fP
.RS 4
R\&. Manasipov 
.RE
.PP
\fBDate\fP
.RS 4
2014
.RE
.PP
Text file parser that separates out comments and finds data blocks on the basis of keywords\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class STREAM> bool \fBcsmp::EclipseTextFileInterface\fP< STREAM >::ReadFile (std::ifstream & ifs, STREAM * stream, bool(STREAM::* IsCommentLineFunction )(char *), bool(STREAM::* ReadFunction )(std::ifstream &, char *, size_t, std::set< std::string > &, std::string &, std::vector< std::string > &), bool fail_for_unknown_keyword = \fRtrue\fP)"
Reading block data marked by keywords

.PP
\fBAuthor\fP
.RS 4
Roman, 2014 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
