.TH "csmp::TestSuite" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TestSuite
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestSuite\fP (const string &name, ostream *osptr=0)"
.br
.ti -1c
.RI "string \fBgetName\fP () const"
.br
.ti -1c
.RI "long \fBgetNumPassed\fP () const"
.br
.ti -1c
.RI "long \fBgetNumFailed\fP () const"
.br
.ti -1c
.RI "const ostream * \fBgetStream\fP () const"
.br
.ti -1c
.RI "void \fBsetStream\fP (ostream *osptr)"
.br
.ti -1c
.RI "void \fBaddTest\fP (\fBTest\fP *t)"
.br
.ti -1c
.RI "void \fBaddTest\fP (const char *test_name, \fBTest\fP *t)"
.br
.ti -1c
.RI "void \fBaddTestSuite\fP (const \fBTestSuite\fP &)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBRunSpecificTest\fP (const char *)"
.br
.ti -1c
.RI "void \fBFreeAllButSpecificTest\fP (const char *test_name)"
.br
.ti -1c
.RI "bool \fBIsInSuite\fP (const char *test_name)"
.br
.ti -1c
.RI "long \fBreport\fP () const"
.br
.ti -1c
.RI "void \fBfree\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void csmp::TestSuite::run ()"

.PP
\fBTodo\fP
.RS 4
(1-D) Put exception catch around each test and report as failed if throw, instead of throwing all the way out of this member, halting test routine 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
