.TH "csmp::TransientDiffusor< dim, CELLTYPE >" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csmp::TransientDiffusor< dim, CELLTYPE >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TransientDiffusor\&.h>\fP
.PP
Inherits \fBcsmp::PDE_Integrator< dim, Element >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransientDiffusor\fP (\fBModel\fP< dim > &, const char *diffusivity, const char *diffusing_variable, const char *storage_variable, const char *element_source_variable)"
.br
.ti -1c
.RI "\fBTransientDiffusor\fP (\fBModel\fP< dim > &, const char *diffusivity, const char *diffusing_variable, const char *storage_variable, const char *element_source_variable, const char *point_source_variable)"
.br
.ti -1c
.RI "\fBTransientDiffusor\fP (\fBModel\fP< dim > &, const char *lhs_diffusivity, const char *rhs_diffusivity, const char *diffusing_variable, const char *storage_variable, const char *spatial_source_variable, const char *point_source_variable)"
.br
.ti -1c
.RI "\fBTransientDiffusor\fP (\fBModel\fP< dim > &, const char *diffusivity, const char *diffusing_variable, const char *storage_variable, const char *spatial_source_variable, const char *gradient_variable, double gradient_multiplier)"
.br
.ti -1c
.RI "\fBTransientDiffusor\fP (\fBModel\fP< dim > &, const char *lhs_diffusivity, const char *rhs_diffusivity, const char *diffusing_variable, const char *storage_variable, const char *spatial_source_variable, const char *gradient_variable, double gradient_multiplier)"
.br
.ti -1c
.RI "\fBTransientDiffusor\fP (\fBModel\fP< dim > &, const char *lhs_diffusivity, const char *rhs_diffusivity, const char *diffusing_variable, const char *storage_variable, const char *spatial_source_variable, const char *point_source_variable, const char *gradient_variable, double gradient_multiplier)"
.br
.ti -1c
.RI "void \fBComputeTransientStateFullyImplicit\fP (\fBModel\fP< dim > &sg, double time_increment, bool verbose=false)"
.br
.RI "[C/dt + K]{p}_t+dt = [C/dt]{p}_t + q + g [d(var)/dy] "
.ti -1c
.RI "virtual void \fBAdjustSolverSettings\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBcsmp::PDE_Integrator< dim, Element >\fP
.in +1c
.ti -1c
.RI "\fBPDE_Integrator\fP ()"
.br
.ti -1c
.RI "\fBPDE_Integrator\fP & \fBoperator=\fP (const \fBPDE_Integrator\fP &)=delete"
.br
.RI "do not assign "
.ti -1c
.RI "void \fBAdd\fP (\fBMathOperatorLHS\fP< dim, \fBElement\fP > *)"
.br
.RI "add desired integral terms (pde operators) to the left-hand side matrix of the algebraic system of equations "
.ti -1c
.RI "void \fBAddPostProcess\fP (\fBMathOperatorLHS\fP< dim, \fBElement\fP > *)"
.br
.RI "adds math operators that will be applied in a second loop after the matrix has been inverted "
.ti -1c
.RI "void \fBAddBoundaryIntegral\fP (\fBMathOperatorRHS\fP< dim, \fBFace\fP > *)"
.br
.RI "adds integral terms on the boundary of the computational domain if any "
.ti -1c
.RI "void \fBAddSplitBoundaryIntegral\fP (\fBMathOperatorRHS\fP< dim, \fBInterFace\fP > *)"
.br
.RI "for the computation of fluxes across internal split boundaries "
.ti -1c
.RI "void \fBTimeIncrement\fP (double dt)"
.br
.RI "sets the time-increment for- and triggers a transient calculation (use 1/t if problem has been set up that way) "
.ti -1c
.RI "bool \fBTransient\fP () const"
.br
.RI "returns whether a finite-difference time increment has been set "
.ti -1c
.RI "void \fBIntegrateOver\fP (\fBModelSubDomain\fP< dim, \fBElement\fP > &, bool debug=false)"
.br
.RI "accumulates, assembles, and solves PDEs in domain of interest; "
.ti -1c
.RI "void \fBSetSolver\fP (\fBSolver\fP &)"
.br
.RI "switch to another solver deleting any dynamically allocated solver that was associated with integrator "
.ti -1c
.RI "\fBSolver\fP & \fBGetSolver\fP () const"
.br
.RI "returns a reference to the current solver object "
.ti -1c
.RI "virtual void \fBReset\fP (bool delete_math_operators=true)"
.br
.RI "returns PDE integrator into the state created by default constructor ( "
.ti -1c
.RI "void \fBSolutionVector\fP (std::vector< double > &) const"
.br
.RI "outputs solution vector; "
.ti -1c
.RI "void \fBFirstGuess\fP (const std::vector< double > &)"
.br
.RI "optional input of a solution vector with an initial guess of the result; for SAMG set ifirst=0 so that this vector is used "
.ti -1c
.RI "void \fBRetainGlobalSolutionMatrix\fP (bool yes_or_no)"
.br
.RI "if an evolutionary problem where only the right-hand side changes, the matrix needs to be assembled only once "
.ti -1c
.RI "void \fBTrimExcessCapacityOfVectors\fP (bool trim)"
.br
.RI "'swap trick' keeps size and capacity of solution and righthand vectors equal "
.ti -1c
.RI "void \fBWriteGlobalMatrixBitMapToText\fP (const char *file_name)"
.br
.RI "writes out the sparsity pattern of the solution matrix "
.ti -1c
.RI "void \fBListMathOperatorsLHS\fP () const"
.br
.ti -1c
.RI "void \fBListMathOperatorsRHS\fP () const"
.br
.ti -1c
.RI "void \fBOutputGlobals\fP (int precision=1)"
.br
.RI "outputs the system A x = b to the screen "
.ti -1c
.RI "void \fBOut\fP () const"
.br
.RI "prints current parameters settings and pde operators to screen "
.ti -1c
.RI "void \fBVerbose\fP (bool)"
.br
.RI "extra detailed screen output about the assembly solution progress "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNumIntegral_dNT_op_dN_dV\fP< dim, CELLTYPE > \fBconductance_\fP"
.br
.RI "add extra functionality for alternative solver if needed "
.ti -1c
.RI "\fBNumIntegral_NT_op_N_dV\fP< dim, CELLTYPE > * \fBsource_\fP"
.br
.ti -1c
.RI "\fBNumIntegral_NT_lhsop_N_dV\fP< dim, CELLTYPE > \fBcapacitance_lhs_\fP"
.br
.ti -1c
.RI "\fBNumIntegral_NT_op_N_dV\fP< dim, CELLTYPE > \fBcapacitance_rhs_\fP"
.br
.ti -1c
.RI "\fBPointSource_rhsop\fP< dim, CELLTYPE > * \fBnodal_source_\fP"
.br
.ti -1c
.RI "\fBNumIntegral_dNT_op_dV\fP< dim, CELLTYPE > * \fBgravity_\fP"
.br
.ti -1c
.RI "CSMP_DEFAULT_LINEAR_SOLVER \fBsolver_\fP"
.br
.ti -1c
.RI "const double \fBgrad_multiplier_\fP"
.br
.ti -1c
.RI "std::string \fBdep_var_name_\fP"
.br
.in -1c

Protected Attributes inherited from \fBcsmp::PDE_Integrator< dim, Element >\fP
.in +1c
.ti -1c
.RI "std::map< std::string, \fBMathOperatorLHS\fP< dim, \fBElement\fP > * > \fBlhs_operators_\fP"
.br
.RI "stencils for lefthand solution matrix "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorRHS\fP< dim, \fBElement\fP > * > \fBrhs_operators_\fP"
.br
.RI "stencils for righthand vector "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorLHS\fP< dim, \fBElement\fP > * > \fBpostpro_operators_\fP"
.br
.RI "post-processing: Darcy velocities, stresses from strains etc\&. "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorRHS\fP< dim, \fBFace\fP > * > \fBrhs_boundary_operators_\fP"
.br
.RI "surface integrals for accumulation over boundary "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorLHS\fP< dim, \fBInterFace\fP > * > \fBlhs_split_boundary_operators_\fP"
.br
.RI "implicit integral coupling terms for \fBSplitBoundary\fP "
.ti -1c
.RI "std::map< std::string, \fBMathOperatorRHS\fP< dim, \fBInterFace\fP > * > \fBrhs_split_boundary_operators_\fP"
.br
.RI "explicit integral coupling terms for \fBSplitBoundary\fP "
.ti -1c
.RI "std::map< \fBcsmp::Parameter\fP, size_t > \fBbasic_operands_\fP"
.br
.ti -1c
.RI "std::map< \fBcsmp::Parameter\fP, size_t > \fBtest_operands_\fP"
.br
.RI "dependent variables in the solved system of equations "
.ti -1c
.RI "std::vector< const \fBcsmp::Face\fP< dim > * > \fBboundary_faces_\fP"
.br
.RI "empty if computation applies to entire model; else Faces needed for dS integrals "
.ti -1c
.RI "std::vector< const \fBcsmp::InterFace\fP< dim > * > \fBsplitboundary_interfaces_\fP"
.br
.RI "empty if computation applies to entire model; else InterFaces needed for domain coupling "
.ti -1c
.RI "\fBSparseMatrix\fP \fBG_\fP"
.br
.RI "solution matrix "
.ti -1c
.RI "std::vector< double > \fBrh_\fP"
.br
.RI "righthand vector "
.ti -1c
.RI "std::vector< double > \fBx_\fP"
.br
.RI "solution vector "
.ti -1c
.RI "std::vector< size_t > \fBDOF_indexes_\fP"
.br
.RI "indices of DOFs, but only of the non-Dirichlet dofs, size enumerated 0 - DOF-1 (including Dirich DOF) "
.ti -1c
.RI "std::vector< double > \fBpivotVector_\fP"
.br
.RI "mapping from DOFs to actual node numbers "
.ti -1c
.RI "\fBSolver\fP * \fBsolver_\fP"
.br
.ti -1c
.RI "size_t \fBdof_per_node_\fP"
.br
.ti -1c
.RI "bool \fBsetup_established_\fP"
.br
.ti -1c
.RI "bool \fBretain_matrix_\fP"
.br
.ti -1c
.RI "bool \fBtrim_vectors_\fP"
.br
.RI "false, false, false to start with "
.ti -1c
.RI "bool \fBnewed_Solver_object_\fP"
.br
.ti -1c
.RI "double \fBtime_increment_\fP"
.br
.ti -1c
.RI "struct \fBcsmp::PDE_Integrator::SIZES\fP \fBtarget_\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBcsmp::PDE_Integrator< dim, Element >\fP
.in +1c
.ti -1c
.RI "typedef std::map< \fBParameter\fP, size_t >::const_iterator \fBoperandsConstIterator\fP"
.br
.RI "constant iterator over solution variables "
.ti -1c
.RI "typedef std::map< \fBParameter\fP, size_t >::iterator \fBoperandsIterator\fP"
.br
.RI "iterator over solution variables "
.in -1c

Protected Member Functions inherited from \fBcsmp::PDE_Integrator< dim, Element >\fP
.in +1c
.ti -1c
.RI "std::list< std::string > \fBIdentifySharedBoundaries\fP (const \fBModel\fP< dim > &, const \fBModelSubDomain\fP< dim, \fBElement\fP > &) const"
.br
.RI "checks whether any \fBBoundary\fP object in the model is a surface of the computational domain "
.ti -1c
.RI "std::list< std::string > \fBIdentifySharedSplitBoundaries\fP (const \fBModel\fP< dim > &, const \fBModelSubDomain\fP< dim, \fBElement\fP > &) const"
.br
.RI "checks whether any \fBSplitBoundary\fP object in the model is a surface of the computational domain "
.ti -1c
.RI "virtual bool \fBEstablishMatrixSetup\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &)"
.br
.RI "resizes sparse solution matrix and establishes variable offsets if a system of equations will be solved, but without boundary or splitboundary integrals "
.ti -1c
.RI "void \fBReduceSystemSizeEliminatingEssentialConditions\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &, size_t max_offset)"
.br
.RI "for the elimination of Dirichlet constraints from the solution matrix; called after EstablishMatrixSetup but before accumulation "
.ti -1c
.RI "virtual void \fBAssignInitialConditions\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &)"
.br
.RI "in time-dependent calculations this method assigns initial conditions to the RHS; uses node numbering "
.ti -1c
.RI "virtual void \fBAssignEssentialConditions\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &)"
.br
.RI "modifies right-hand vector; adding Dirichlet condition terms that were elimitated before "
.ti -1c
.RI "virtual void \fBAccumulate\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &)"
.br
.RI "accumulates finite element integrals into solution matrix and right-hand side; uses node numbering "
.ti -1c
.RI "virtual void \fBLateAccumulate\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &)"
.br
.RI "accumulates finite-element integrals to matrix and vector after the corresponding entries were already multiplied with the initial conditions; uses node numbering "
.ti -1c
.RI "virtual void \fBAccumulateBoundaryIntegrals\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &, const \fBBoundary\fP< dim > &)"
.br
.RI "accumulates surface integrals from Neumann-flagged \fBFace\fP object variables representing those parts of all boundaries that delimit the computational domain "
.ti -1c
.RI "virtual void \fBAccumulateSplitBoundaryIntegrals\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &, const \fBSplitBoundary\fP< dim > &)"
.br
.RI "accumulation of Robin-type boundary conditions to \fBSplitBoundary\fP interfaces "
.ti -1c
.RI "virtual void \fBLateAccumulateBoundaryIntegrals\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &, const \fBBoundary\fP< dim > &)"
.br
.RI "late accumulates surface integrals from Neumann-flagged \fBFace\fP object variables representing those parts of all boundaries that delimit the computational domain "
.ti -1c
.RI "virtual void \fBLateAccumulateSplitBoundaryIntegrals\fP (const \fBModelSubDomain\fP< dim, \fBElement\fP > &, const \fBSplitBoundary\fP< dim > &)"
.br
.ti -1c
.RI "void \fBCoupleDomainsAcrossSplitBoundary\fP (\fBModelSubDomain\fP< dim, \fBElement\fP > &)"
.br
.RI "couples domains separated by SplitBoundaries using the information from NodeManifolds "
.ti -1c
.RI "virtual void \fBSolve\fP ()"
.br
.RI "calls connected solver object to find x in G x = rh problem "
.ti -1c
.RI "virtual void \fBPostProcess\fP (\fBModelSubDomain\fP< dim, \fBElement\fP > &)"
.br
.RI "allows to apply pde operators to post-process the newly computed solution "
.ti -1c
.RI "virtual void \fBOutputResults\fP (\fBModelSubDomain\fP< dim, \fBElement\fP > &)"
.br
.RI "transfers the results stored in solution vector onto the nodes of the computational domain; uses node numbering "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE = Element>
.br
class csmp::TransientDiffusor< dim, CELLTYPE >"transient diffusion solver with Backward-Euler time-stepping
.SS "[C/dt + K]{p}_t+dt = [C/dt]{p}_t + q"
specific to the CSP reservoir simulator only a single equation is solved for total pressure result variable 'fluid pressure' initialises hydrostatic pressure to zero

.PP
\fBAttention\fP
.RS 4
gradient_multiplier currently is not used\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<uint32_t dim, template< uint32_t > class CELLTYPE> void \fBcsmp::TransientDiffusor\fP< dim, CELLTYPE >::AdjustSolverSettings ()\fR [virtual]\fP"
add extra functionality for alternative solver if needed

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
