.TH "source/includes/math/DenseMatrix.h" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/includes/math/DenseMatrix.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdexcept>\fP
.br
\fR#include <typeinfo>\fP
.br
\fR#include <array>\fP
.br
\fR#include 'Point\&.h'\fP
.br
\fR#include 'ScalarVariable\&.h'\fP
.br
\fR#include 'VectorVariable\&.h'\fP
.br
\fR#include 'TensorVariable\&.h'\fP
.br
\fR#include 'ArrayVariable\&.h'\fP
.br
\fR#include 'FlaggedArrayVariable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcsmp::DenseMatrix< mn_max >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsmp\fP"
.br
.RI "Complex System Modeling Platform\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBcsmp::CSMP_DMAT_SIZE\fP { \fBDM3\fP =3U, \fBDM4\fP =4U, \fBDM6\fP =6U, \fBDM12\fP =12U, \fBDM_MIN\fP =36U, \fBDM_MAX\fP =81U }"
.br
.RI "choice of fixed sizes 'mn_max' "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<uint32_t mn_max> bool \fBcsmp::operator==\fP (const \fBDenseMatrix\fP< mn_max > &, const \fBDenseMatrix\fP< mn_max > &)"
.br
.RI "comparitor of elements using compareFloats "
.ti -1c
.RI "template<uint32_t mn_max> \fBDenseMatrix\fP< mn_max > \fBcsmp::operator+\fP (const \fBDenseMatrix\fP< mn_max > &a, const \fBDenseMatrix\fP< mn_max > &b)"
.br
.RI "operator + "
.ti -1c
.RI "template<uint32_t mn_max> \fBDenseMatrix\fP< mn_max > \fBcsmp::operator\-\fP (const \fBDenseMatrix\fP< mn_max > &a, const \fBDenseMatrix\fP< mn_max > &b)"
.br
.RI "operator - "
.ti -1c
.RI "template<uint32_t mn_max> \fBDenseMatrix\fP< mn_max > \fBcsmp::operator*\fP (const \fBDenseMatrix\fP< mn_max > &a, const \fBDenseMatrix\fP< mn_max > &b)"
.br
.RI "matrix multiplication operator* that returns temporary "
.ti -1c
.RI "template<uint32_t mn_max> std::vector< double > \fBcsmp::operator*\fP (const \fBDenseMatrix\fP< mn_max > &mat, const std::vector< double > &)"
.br
.RI "vector^T = \fBMatrix\fP * vector^T "
.ti -1c
.RI "template<uint32_t mn_max> \fBDenseMatrix\fP< mn_max > \fBcsmp::operator*\fP (const std::vector< double > &v, const \fBDenseMatrix\fP< mn_max > &M)"
.br
.RI "v^T = (v^T M)^T "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
