.TH "DynamicArray2D< T >" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicArray2D< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBdata_type\fP = std::vector<T>"
.br
.ti -1c
.RI "using \fBvalue_type\fP = typename std::vector<T>::value_type"
.br
.ti -1c
.RI "using \fBsize_type\fP = typename std::vector<T>::size_type"
.br
.ti -1c
.RI "using \fBreference\fP = typename std::vector<T>::reference"
.br
.ti -1c
.RI "using \fBconst_reference\fP = typename std::vector<T>::const_reference"
.br
.ti -1c
.RI "using \fBiterator\fP = typename std::vector<T>::iterator"
.br
.ti -1c
.RI "using \fBconst_iterator\fP = typename std::vector<T>::const_iterator"
.br
.ti -1c
.RI "using \fBreverse_iterator\fP = typename std::vector<T>::reverse_iterator"
.br
.ti -1c
.RI "using \fBconst_reverse_iterator\fP = typename std::vector<T>::const_reverse_iterator"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamicArray2D\fP (size_type rows, size_type cols)"
.br
.ti -1c
.RI "\fBDynamicArray2D\fP (size_type rows, size_type cols, const_reference val)"
.br
.ti -1c
.RI "\fBDynamicArray2D\fP (std::initializer_list< data_type > vals)"
.br
.ti -1c
.RI "\fBDynamicArray2D\fP (std::initializer_list< T > vals)"
.br
.RI "construction of square array via vector-style initialiser list "
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "const_iterator \fBend\fP () const"
.br
.ti -1c
.RI "const_iterator \fBcbegin\fP () const"
.br
.ti -1c
.RI "const_iterator \fBcend\fP () const"
.br
.ti -1c
.RI "reverse_iterator \fBrbegin\fP ()"
.br
.ti -1c
.RI "reverse_iterator \fBrend\fP ()"
.br
.ti -1c
.RI "const_reverse_iterator \fBrbegin\fP () const"
.br
.ti -1c
.RI "const_reverse_iterator \fBrend\fP () const"
.br
.ti -1c
.RI "const_reverse_iterator \fBcrbegin\fP () const"
.br
.ti -1c
.RI "const_reverse_iterator \fBcrend\fP () const"
.br
.ti -1c
.RI "reference \fBoperator()\fP (size_type const row, size_type const column)"
.br
.ti -1c
.RI "const_reference \fBoperator()\fP (size_type const row, size_type const column) const"
.br
.ti -1c
.RI "reference \fBat\fP (size_type const row, size_type const column)"
.br
.ti -1c
.RI "const_reference \fBat\fP (size_type const row, size_type const column) const"
.br
.ti -1c
.RI "void \fBresize\fP (size_type new_rows, size_type new_cols)"
.br
.ti -1c
.RI "size_type \fBsize\fP () const"
.br
.ti -1c
.RI "size_type \fBcapacity\fP () const"
.br
.ti -1c
.RI "size_type \fBmax_size\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "size_type \fBrows\fP () const"
.br
.ti -1c
.RI "size_type \fBcols\fP () const"
.br
.ti -1c
.RI "void \fBswap\fP (\fBDynamicArray2D\fP &rhs)"
.br
.ti -1c
.RI "void \fBout\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBDynamicArray2D\fP< T >\fB::DynamicArray2D\fP (std::initializer_list< data_type > vals)\fR [inline]\fP"
matrix constructor taking vector-of-vectors-style initialiser list supporting initialisation by: \fBDynamicArray2D<double>\fP mat4{ {1\&., 0\&.}, {0\&., 2\&.} }; 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
