.TH "source/includes/integration/finite_volumes/finiteVolumeAuxiliaryFunctions.h" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/includes/integration/finite_volumes/finiteVolumeAuxiliaryFunctions.h
.SH SYNOPSIS
.br
.PP
\fR#include 'CSMP_mathUtilities\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsmp\fP"
.br
.RI "Complex System Modeling Platform\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<uint32_t dim> void \fBcsmp::initializeFiniteVolumeProperties\fP (\fBModel\fP< dim > &, \fBRegion\fP< dim > &, bool initialize_flux)"
.br
.RI "identifies "halo" elements/faces/interfaces, i\&.e\&. which contribute to domain FVs, but are outside of domain, returns number "
.ti -1c
.RI "template<uint32_t dim> void \fBcsmp::initializeBasicFiniteVolumeProperties\fP (\fBModel\fP< dim > &, \fBRegion\fP< dim > &)"
.br
.RI "taking into account thickness, initialising FV sector volume, FV pore volume, facet area, facet normal "
.ti -1c
.RI "template<uint32_t dim> double \fBcsmp::sectorFlux\fP (const \fBElement\fP< dim > *const eptr, uint32_t sector, const \fBcsmp::Index\fP &flux_key)"
.br
.RI "sums precomputed fluxes over the facets that surround the FE - FV sector; thickness of dim-1 elements is taken into account "
.ti -1c
.RI "template<uint32_t dim> double \fBcsmp::fluxThroughFiniteVolume\fP (\fBNode\fP< dim > const &node, \fBIndex\fP const &velocityKey)"
.br
.ti -1c
.RI "template<uint32_t dim, typename ForwardIt> double \fBcsmp::fluxThroughFiniteVolumes\fP (ForwardIt nodesBegin, ForwardIt nodesEnd, \fBIndex\fP const &velocityKey)"
.br
.ti -1c
.RI "double \fBcsmp::diffusionVelocity\fP (const \fBRegion\fP< 1 > &model_domain, const \fBNode\fP< 1U > *const nd, const std::set< uint32_t > &ngraph_entry, const \fBcsmp::Index\fP &advected_var_key)"
.br
.ti -1c
.RI "double \fBcsmp::diffusionVelocity\fP (const \fBRegion\fP< 2 > &, const \fBNode\fP< 2U > *const, const std::set< uint32_t > &, const \fBcsmp::Index\fP &)"
.br
.ti -1c
.RI "double \fBcsmp::diffusionVelocity\fP (const \fBRegion\fP< 3 > &, const \fBNode\fP< 3U > *const, const std::set< uint32_t > &, const \fBcsmp::Index\fP &)"
.br
.ti -1c
.RI "double \fBcsmp::delta_X_FromFV_Volume\fP (double FV_volume, uint32_t dim)"
.br
.ti -1c
.RI "double \fBcsmp::omega\fP (double dt, double pore_vol, double src)"
.br
.ti -1c
.RI "double \fBcsmp::NVD_Function\fP (double xi, double U_f, double U_c)"
.br
.ti -1c
.RI "double \fBcsmp::limitProperty\fP (double psi_hat_c, double psi_hat_d, double psi_facet, const std::pair< double, double > &SMINMAX_at_upstream_node, double limiter_value_xi=2\&.)"
.br
.RI "minmod limiter with coefficient xi that controls maximum permissible gradient "
.ti -1c
.RI "double \fBcsmp::limitProperty\fP (double psi_hat_c, double psi_hat_u, double min, double max)"
.br
.ti -1c
.RI "template<uint32_t dim> void \fBcsmp::limitProperty_LSMGRAD\fP (const \fBElement\fP< dim > &e, const \fBcsmp::Index\fP &mass_center_key, const \fBcsmp::Index\fP &grad_sn_key, const \fBcsmp::Index\fP &grad_sn_limiter_key, uint32_t inside_node, uint32_t outside_node, uint32_t iFacet, const double sn_inside_node, const double sn_outside_node, double &limited_sn_inside_node, double &limited_sn_outside_node)"
.br
.RI "limiting with node-based property gradients, see Geiger et al\&. (2004, Geofluids) "
.ti -1c
.RI "template<uint32_t dim> double \fBcsmp::limitProperty_LSMGRAD\fP (const \fBElement\fP< dim > &e, const \fBcsmp::Index\fP &mass_center_key, const \fBcsmp::Index\fP &grad_sn_key, const \fBcsmp::Index\fP &grad_sn_limiter_key, uint32_t ustream_node, uint32_t iFacet, const double sn_upstream_node)"
.br
.RI "limiting with node-based property gradients, see Geiger et al\&. (2004, Geofluids) "
.ti -1c
.RI "double \fBcsmp::thetaLimiter\fP (double hf_t0, double hf_t1, double vol_upstr, double vol_dwstr, double psi_hat_c_t1_minus_psi_hat_c_t0, double psi_hat_d_t1_minus_psi_hat_d_t0, double dt)"
.br
.RI "Matthai et al\&. 2009 (TIPM) explains theta limiting concept\&. "
.ti -1c
.RI "double \fBcsmp::diffusionLimiter\fP (double grad_psi_O1, double grad_psi_O2)"
.br
.RI "gradient limiter for the solution of diffusion equations with the FVM method "
.ti -1c
.RI "template<uint32_t dim> std::pair< double, double > \fBcsmp::diameterAndVerticalExtentOfLowerDimensional_FV\fP (const \fBNode\fP< dim > *const)"
.br
.RI "computes the diameter and vertical of a surface finite volume using midpoints to connected nodes on the same surface "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
