.TH "ijk" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ijk
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CornerPointGrid\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBijk\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBijk\fP &rhs) const"
.br
.ti -1c
.RI "\fBijk\fP (uint32_t i, uint32_t j, uint32_t k)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBi\fP"
.br
.ti -1c
.RI "uint32_t \fBj\fP"
.br
.ti -1c
.RI "uint32_t \fBk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Hash table utility class for storing (i,j,k) coordinates, in this case the i,j,k indices of the CornerPointGrid 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
