.TH "io::error::base" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::error::base
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.PP
Inherited by \fBio::error::can_not_open_file\fP, \fBio::error::duplicated_column_in_header\fP, \fBio::error::escaped_string_not_closed\fP, \fBio::error::extra_column_in_header\fP, \fBio::error::header_missing\fP, \fBio::error::integer_must_be_positive\fP, \fBio::error::integer_overflow\fP, \fBio::error::integer_underflow\fP, \fBio::error::invalid_single_character\fP, \fBio::error::line_length_limit_exceeded\fP, \fBio::error::missing_column_in_header\fP, \fBio::error::no_digit\fP, \fBio::error::too_few_columns\fP, and \fBio::error::too_many_columns\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBformat_error_message\fP () const =0"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const  throw ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBerror_message_buffer\fP [256]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
