.TH "io::error::with_file_name" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::error::with_file_name
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBio::error::can_not_open_file\fP, \fBio::error::duplicated_column_in_header\fP, \fBio::error::escaped_string_not_closed\fP, \fBio::error::extra_column_in_header\fP, \fBio::error::header_missing\fP, \fBio::error::integer_must_be_positive\fP, \fBio::error::integer_overflow\fP, \fBio::error::integer_underflow\fP, \fBio::error::invalid_single_character\fP, \fBio::error::line_length_limit_exceeded\fP, \fBio::error::missing_column_in_header\fP, \fBio::error::no_digit\fP, \fBio::error::too_few_columns\fP, and \fBio::error::too_many_columns\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_file_name\fP (const char *file_name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBfile_name\fP [max_file_name_length+1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
