.TH "io::error::with_column_name" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::error::with_column_name
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBio::error::duplicated_column_in_header\fP, \fBio::error::extra_column_in_header\fP, \fBio::error::integer_must_be_positive\fP, \fBio::error::integer_overflow\fP, \fBio::error::integer_underflow\fP, \fBio::error::invalid_single_character\fP, \fBio::error::missing_column_in_header\fP, and \fBio::error::no_digit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_column_name\fP (const char *column_name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBcolumn_name\fP [max_column_name_length+1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
