.TH "io::error::with_errno" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::error::with_errno
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBio::error::can_not_open_file\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_errno\fP (int errno_value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBerrno_value\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
