.TH "io::set_to_max_on_overflow" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::set_to_max_on_overflow
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T> static void \fBon_overflow\fP (T &x)"
.br
.ti -1c
.RI "template<class T> static void \fBon_underflow\fP (T &x)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
