.TH "Loki" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Loki \- Andrei Alexandrescu\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCompileTimeError\fP"
.br
.ti -1c
.RI "struct \fBCompileTimeError< true >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Andrei Alexandrescu\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
