.TH "source/modules/thmc/mechanics/mechanics.cpp" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/modules/thmc/mechanics/mechanics.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'mechanics\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsmp\fP"
.br
.RI "Complex System Modeling Platform\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcsmp::planeStressMatrix\fP (double E, double nu, \fBDenseMatrix\fP< DM_MIN > &D)"
.br
.ti -1c
.RI "void \fBcsmp::planeStrainMatrix\fP (double E, double nu, \fBDenseMatrix\fP< DM_MIN > &D)"
.br
.ti -1c
.RI "void \fBcsmp::stiffnessMatrix\fP (double E, double nu, \fBDenseMatrix\fP< DM_MIN > &D)"
.br
.ti -1c
.RI "void \fBcsmp::stiffnessMatrix\fP (double E, \fBDenseMatrix\fP< DM_MIN > &D, double length)"
.br
.RI "1D linear bar "
.ti -1c
.RI "void \fBcsmp::planeStressMatrix\fP (const \fBvector\fP< \fBScalarVariable\fP > &E, const \fBvector\fP< \fBScalarVariable\fP > &nu, \fBvector\fP< \fBDenseMatrix\fP< DM_MIN > > &D)"
.br
.ti -1c
.RI "void \fBcsmp::planeStrainMatrix\fP (const \fBvector\fP< \fBScalarVariable\fP > &E, const \fBvector\fP< \fBScalarVariable\fP > &nu, \fBvector\fP< \fBDenseMatrix\fP< DM_MIN > > &D)"
.br
.ti -1c
.RI "void \fBcsmp::stiffnessMatrix\fP (const \fBvector\fP< \fBScalarVariable\fP > &E, const \fBvector\fP< \fBScalarVariable\fP > &nu, \fBvector\fP< \fBDenseMatrix\fP< DM_MIN > > &D)"
.br
.ti -1c
.RI "void \fBcsmp::sortEigenVectorsAndValues\fP (\fBVectorVariable\fP< 2U > &vc, \fBTensorVariable\fP< 2U > &ts)"
.br
.RI "in the order of the biggest positive to the smallest eigenvalue "
.ti -1c
.RI "void \fBcsmp::sortEigenVectorsAndValues\fP (\fBVectorVariable\fP< 3U > &vc, \fBTensorVariable\fP< 3U > &ts)"
.br
.ti -1c
.RI "void \fBcsmp::normalAndShearStressOnPlane\fP (const \fBTensorVariable\fP< 3U > &cartesian_stress, const \fBPoint\fP< 3U > &plane_normal, double &sigma_n, double &sigma_s)"
.br
.RI "uses Cauchy's formula to resolve normal and magnitude of shear stress on a surface defined by its normal "
.ti -1c
.RI "void \fBcsmp::normalAndShearStressOnPlane\fP (const \fBTensorVariable\fP< 3U > &cartesian_stress, const \fBPoint\fP< 3U > &plane_normal, double &sigma_n, \fBVectorVariable\fP< 3U > &sigma_s)"
.br
.RI "uses Cauchy's formula to resolve normal and shear stress on a surface defined by its normal "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
