.TH "mjl::Triangle3D" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mjl::Triangle3D
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriangle3D\fP (const \fBPoint3D\fP &v0, const \fBPoint3D\fP &v1, const \fBPoint3D\fP &v2, long id)"
.br
.ti -1c
.RI "\fBTriangle3D\fP (const \fBTriangle3D\fP &t)"
.br
.ti -1c
.RI "\fBTriangle3D\fP & \fBoperator=\fP (const \fBTriangle3D\fP &t)"
.br
.ti -1c
.RI "\fBPoint3D\fP \fBoperator[]\fP (int i) const"
.br
.ti -1c
.RI "\fBEdge3D\fP \fBboundingBox\fP () const"
.br
.ti -1c
.RI "\fBPoint3D\fP \fBn\fP () const"
.br
.ti -1c
.RI "void \fBUnitNormal\fP (\fBEdge3D\fP &) const"
.br
.ti -1c
.RI "void \fBUnitNormal\fP (std::vector< double > &vec) const"
.br
.ti -1c
.RI "int \fBClassify\fP (const \fBPoint3D\fP &p) const"
.br
.ti -1c
.RI "int \fBFacingDirection\fP () const"
.br
.ti -1c
.RI "void \fBSet\fP (const \fBPoint3D\fP &v0, const \fBPoint3D\fP &v1, const \fBPoint3D\fP &v2, long id)"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBid_\fP"
.br
.ti -1c
.RI "int \fBmark_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int mjl::Triangle3D::FacingDirection () const"
Identifies the facing direction of the father triangle, by comparing the orientation of its normal to the principle coordinate directions\&. In CSP, these directions are defined in a righthand coordinate system: 
.PP
.nf
     TOP

    y |
3D:   | 
      |
      o-------> RIGHT
     /       x
 z  / 

FRONT

.fi
.PP

.PP
\fBReturns\fP
.RS 4
the integer value definition from '\fBMJL_Geometry\&.h\fP' for the result of the comparison\&. If none of the principal axes match, the method will return the value MJL3D_TILTED\&.
.RE
.PP
.SH "Implementation"
.PP
The comparison will evaluate to one of the principal facing directions if the face normal is parallel to-, or inclined by less that 45o to the normal representing that direction\&.
.SH "Application Examples"
.PP
Identify to which model boundary a face of a tetrahedron in an input mesh belongs\&. In CSP, for instance, this comparison will be carried out in MeshInterface::ReadTSolid()\&.
.SH "Messages"
.PP
If the determined facing direction does not match any of the principal axis, a message will report this\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
