.TH "mjl::Edge" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mjl::Edge
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEdge\fP (const \fBmjl::Point\fP &, const \fBmjl::Point\fP &)"
.br
.ti -1c
.RI "\fBEdge\fP (const \fBmjl::Edge\fP &)"
.br
.ti -1c
.RI "\fBEdge\fP & \fBoperator=\fP (const \fBmjl::Edge\fP &m)"
.br
.ti -1c
.RI "void \fBSet\fP (const \fBmjl::Point\fP &, const \fBmjl::Point\fP &)"
.br
.ti -1c
.RI "void \fBSet\fP (double x1, double y1, double x2, double y2)"
.br
.ti -1c
.RI "\fBEdge\fP & \fBRot\fP ()"
.br
.RI "pivots an edge 90o clockwise around it's midpoint "
.ti -1c
.RI "\fBEdge\fP & \fBFlip\fP ()"
.br
.RI "flip the direction of an edge "
.ti -1c
.RI "void \fBMove\fP (double dx, double dy)"
.br
.ti -1c
.RI "void \fBScale\fP (double xfac, double yfac)"
.br
.ti -1c
.RI "void \fBNormalizeTo\fP (double n)"
.br
.ti -1c
.RI "bool \fBIfCloserThanMerge\fP (double tolerance, \fBmjl::Point\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBmjl::Edge\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBmjl::Edge\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBmjl::Edge\fP &) const"
.br
.ti -1c
.RI "\fBmjl::Point\fP \fBPoint\fP (double t) const"
.br
.ti -1c
.RI "double \fBY\fP (double x) const"
.br
.ti -1c
.RI "\fBmjl::Point\fP \fBOrigin\fP () const"
.br
.ti -1c
.RI "\fBmjl::Point\fP \fBDestination\fP () const"
.br
.ti -1c
.RI "void \fBMidPoint\fP (\fBmjl::Point\fP &) const"
.br
.ti -1c
.RI "\fBmjl::Point\fP \fBMidPoint\fP () const"
.br
.ti -1c
.RI "bool \fBIsVertical\fP () const"
.br
.ti -1c
.RI "double \fBSlope\fP () const"
.br
.ti -1c
.RI "double \fBDistanceFrom\fP (const \fBmjl::Point\fP &) const"
.br
.ti -1c
.RI "double \fBLength\fP () const"
.br
.ti -1c
.RI "LOCATION \fBClassify\fP (const \fBmjl::Point\fP &) const"
.br
.ti -1c
.RI "INTERSECTION \fBIntersect\fP (const \fBEdge\fP &, double &) const"
.br
.ti -1c
.RI "INTERSECTION \fBCross\fP (const \fBEdge\fP &, double &) const"
.br
.ti -1c
.RI "INTERSECTION \fBCrossingPoint\fP (double tolerance, const \fBEdge\fP &, \fBmjl::Point\fP &) const"
.br
.ti -1c
.RI "INTERSECTION \fBSKM_CrossingPoint\fP (double tolerance, const \fBEdge\fP &, \fBmjl::Point\fP &) const"
.br
.ti -1c
.RI "EDGE_CLASSIFICATION \fBType\fP (const \fBmjl::Point\fP &) const"
.br
.ti -1c
.RI "double \fBAngleTo\fP (const \fBEdge\fP &) const"
.br
.RI "see "Mathematische Formeln" p\&. 170, Schnittwinkel\&.\&.\&. "
.ti -1c
.RI "double \fBDotProduct\fP (const \fBmjl::Point\fP &, const \fBmjl::Point\fP &) const"
.br
.ti -1c
.RI "void \fBOut\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmjl::Point\fP \fBorg_\fP"
.br
.ti -1c
.RI "\fBmjl::Point\fP \fBdest_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "INTERSECTION mjl::Edge::Cross (const \fBEdge\fP & e, double & t) const\fR [inline]\fP"

.PP
\fBReturns\fP
.RS 4
SKEW_CROSS if the line segments intersect (in constrast with the infinite lines) COLLINEAR, PARALLEL SKEW_NO_CROSS as appropriate t = x value of intersection if intersection occurs 
.RE
.PP

.SS "INTERSECTION mjl::Edge::CrossingPoint (double tolerance, const \fBEdge\fP & f, \fBmjl::Point\fP & p) const"
includes start and end-point into the edge comparison\&. Thus if the intersection is within the tolerance of these nodes, \fBCrossingPoint()\fP will return SKEW_CROSS and it will snap the intersection point to that node\&. 
.SS "INTERSECTION mjl::Edge::Intersect (const \fBEdge\fP & e, double & t) const"

.PP
\fBReturns\fP
.RS 4
SKEW if infinite lines defined by edges crossat a point p COLLINEAR if the lines are the same PARALLEL if the two lines defined by the edges are parallel
.RE
.PP
t is assigned the parametric value (along the line) of where the lines intersect if they do\&. t = x of the intersection 
.SS "INTERSECTION mjl::Edge::SKM_CrossingPoint (double tolerance, const \fBEdge\fP & f, \fBmjl::Point\fP & p) const"
as above but no snapping to points, the intersection point is returned into p\&. 
.SS "EDGE_CLASSIFICATION mjl::Edge::Type (const \fBmjl::Point\fP & p) const"
classifies an edge relative to its location compared with the point p\&. Options are CROSSING, TOUCHING and INESSENTIAL 
.SS "double mjl::Edge::Y (double x) const\fR [inline]\fP"
for a given x value \fBY()\fP returns the corresponding y value on the line defined by the \fBEdge\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
