.TH "mjl::Plane3D" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mjl::Plane3D
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlane3D\fP (const \fBmjl::Point3D\fP &, const \fBmjl::Point3D\fP &)"
.br
.ti -1c
.RI "\fBPlane3D\fP (const \fBmjl::Point3D\fP &, const \fBmjl::Point3D\fP &, const \fBmjl::Point3D\fP &)"
.br
.ti -1c
.RI "\fBPlane3D\fP (const \fBmjl::Plane3D\fP &)"
.br
.ti -1c
.RI "\fBPlane3D\fP & \fBoperator=\fP (const \fBmjl::Plane3D\fP &m)"
.br
.ti -1c
.RI "\fBmjl::Point3D\fP \fBPointP\fP () const"
.br
.ti -1c
.RI "\fBmjl::Point3D\fP \fBNVector\fP () const"
.br
.ti -1c
.RI "void \fBOut\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmjl::Point3D\fP \fBp1_\fP"
.br
.ti -1c
.RI "\fBmjl::Point3D\fP \fBp2_\fP"
.br
.ti -1c
.RI "\fBmjl::Point3D\fP \fBp3_\fP"
.br
.ti -1c
.RI "\fBmjl::Point3D\fP \fBvc_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
