.TH "mjl::Node" 3 "Thu May 29 2025 14:52:20" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mjl::Node
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBmjl::Vertex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fBNext\fP ()"
.br
.ti -1c
.RI "\fBNode\fP * \fBPrev\fP ()"
.br
.ti -1c
.RI "\fBNode\fP * \fBInsert\fP (\fBNode\fP *)"
.br
.ti -1c
.RI "\fBNode\fP * \fBRemove\fP ()"
.br
.ti -1c
.RI "void \fBSplice\fP (\fBNode\fP *)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fBnext_\fP = nullptr"
.br
.ti -1c
.RI "\fBNode\fP * \fBprev_\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
