.TH "source/includes/thmc/single_phase_flow/parallelPlatePermeabilityFromChannelWidth.h" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/includes/thmc/single_phase_flow/parallelPlatePermeabilityFromChannelWidth.h
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcsmp\fP"
.br
.RI "Complex System Modeling Platform\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<uint32_t dim> void \fBcsmp::parallelPlatePermeabilityFromChannelWidth\fP (\fBModel\fP< dim > &, const char *channel_region, const char *channel_width='channel width', double minimum_channel_width=1\&.0e\-9)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
