.TH "SimulationSignalHandler" 3 "Thu May 29 2025 14:52:18" "Version 1.0" "Open-CSMP++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimulationSignalHandler
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SimulationSignalHandler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOutputVTUSignal\fP (bool signal)"
.br
.ti -1c
.RI "bool \fBOutputVTUSignal\fP ()"
.br
.ti -1c
.RI "void \fBOutputMonitorDataSignal\fP (bool signal)"
.br
.ti -1c
.RI "bool \fBOutputMonitorDataSignal\fP ()"
.br
.ti -1c
.RI "void \fBOutputRestartFileSignal\fP (bool signal)"
.br
.ti -1c
.RI "bool \fBOutputRestartFileSignal\fP ()"
.br
.ti -1c
.RI "void \fBQuitSignal\fP (bool signal)"
.br
.ti -1c
.RI "bool \fBQuitSignal\fP ()"
.br
.ti -1c
.RI "void \fBSignalRaised\fP (bool signal)"
.br
.ti -1c
.RI "bool \fBSignalRaised\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows user to interrupt simulation by keystrokes\&.

.PP
Used by FEMCFVM simulator\&.

.PP
\fBAuthor\fP
.RS 4
J\&. Mindel & S\&. Bazrafkan 
.RE
.PP
\fBDate\fP
.RS 4
2012 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Open-CSMP++ from the source code\&.
