#ifndef REGIONS_INTERFACE_H
#define REGIONS_INTERFACE_H

#include "Region.h"
#include "ErrorHandler.h"
#include "ModelTopology.h"
#include "PropertyConstraints.h"
#include "CSMP_highLevelUtilities.h"

#include <map>
#include <set>
#include <utility>
#include <tuple>

namespace csmp {

  /**
  
  @brief Policy of the class model for the management of its labeled subdomains that
  are equivalent to the parts (CAD) or geobodies of the input model.

  @author S.K. Matthai
  @author P. Lang
  @date 2010

  @section motivation Motivation
    
  Break the complex interface of the model down into functional units.
  
  @section design Design Intent and Rules

  Policy of the Model that manages any kind of Region objects, i.e. ModelSubDomain objects
  that consist of Elements.
  
  @attention there can be unique (non-overlapping) and non-unique regions. A region "Model"
  that encompasses all elements that form part of the Model class' computational domain
  is either unique or non-unique, depending on whether there are other unique regions
  (in this latter case it is non-unique).

  @attention there is a second "fixed" master region that is always there. It is always called "Model" and
  its purpose is as the default computational domain, i.e. when you compute something on the mdel
  this region called "Model" will include all parts of the model's computational domain.
  However, the "Model" region does not automatically include the other non-unique regions
  nor Faces or InterFace objects which are managed by the Boundary and SplitBoundary classes.

  @section collaborations Collaborations

  The RegionInterface relies on the functionality of the Region derived from the ModelSubDomain class.

  @section examples Application Examples

  Interface allows to construct a region or reference regions, for example:

  @code
   // for each distinct value of the 'permeability' a region is created
   set<string>  group_names;
   model.FormRegionsFromPropertyValues( "permeability", group_names );
   //    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   cout <<"\n\n\nmain: FormRegionsFromPropertyValues()  creating 'permeability' regions: ";
   for ( set<string>::const_iterator it=group_names.begin(); it!=group_names.end(); it++ ) cout << (*it) <<" ";
   cout << endl;
  @endcode

  TODO: @todo !!! all methods that create regions from regions must also copy potential regional property values to these
  
  @bug the region property values of regions that were generated by boolean operators or merge
  are not defined. A rule is needed to assign them in a consistent fashion

*/
template<size_t dim, template<size_t> class REGION_COMPLEX>
class RegionInterface
  {
  public:
    RegionInterface();
    virtual ~RegionInterface();

    /// checks whether region exists considering both unique and non-unique regions
    bool ContainsRegion( const std::string& regionname ) const;

    /// returns const reference to region
    const csmp::Region<dim>&  Region( const std::string& region_name ) const;

    /// returns reference to region
    csmp::Region<dim>&  Region( const std::string& region_name );
    
    /// checks whether the region is space exclusive, i.e. does not contain any other regions
    bool IsUnique( const std::string& regionname ) const;

    /// checks whether all elements within the region are interconnected (if the region has multi-dimensional elements this is never the case)
    bool IsContiguous( const std::string& regionname ) const;

    // -----------------------------------------------
    // Binary input/output
    // -----------------------------------------------

    // NEW:
    /// writes unique and non-unique regions to binary file, including, interior/perimeter/boundary face information; relies on unique indexes
    void OutputAllRegionsToBinary( const char* file_name ) const;

    // NEW:
    /// Reads unique and non-unique regions from binary file as written by OutputAllRegionsToBinary()
    void InputAllRegionsFromBinary( const char* file_name );

    // TODO: DEPRECATE THESE METHODS AFTER FIRST TWO HAVE BEEN VERIFIED
    /// writes a single region to binary file relying on a prexisting unique element and node numbering
    void OutputRegionToBinary( const char* region_name, const char* file_name ) const;

    /// appends unique and non-unique region information to CSMP native binary file
    void AppendRegionsToBinary( const char* file_name ) const;

    /// reads a single region from binary file relying on a prexisting unique element and node numbering
    void InputRegionFromBinary( const char* region_name, bool is_unique, const char* file_name );

    /// initializes region from CSMP native binary file using a pre-existing master region that contains all elements
    void InputRegionsFromBinary( const char* file_name );

    // -------------------------------------------------------------------------
    // Regions access and manipulations with the list of Regions
    // -------------------------------------------------------------------------

    /// iterators to associative containers of regions
    typedef typename std::map<std::string,csmp::Region<dim> >::iterator        regionIterator;
    typedef typename std::map<std::string,csmp::Region<dim> >::const_iterator  regionConstIterator;

    regionIterator            RegionsBegin();
    regionIterator            RegionsEnd();
    regionConstIterator       RegionsBegin() const;
    regionConstIterator       RegionsEnd() const;

    regionIterator            UniqueRegionsBegin();
    regionIterator            UniqueRegionsEnd();
    regionConstIterator       UniqueRegionsBegin() const;
    regionConstIterator       UniqueRegionsEnd() const;

    /// number of non-unique regions that potentially overlap
    size_t                    Regions() const;
    /// number of regions that are space eclusive like the subvolumes of a water tight CAD model
    size_t                    UniqueRegions() const;

    // -----------------------------------------------
    // Regions creation
    // -----------------------------------------------
    
    /// forms non-unique region by graph traversal of all reachable elements in the mesh without expecting element-to-neighbor connections
    bool CreateRegionFromRootNode( const char* regionname, bool is_unique, bool reestablishNeighborConnectivity=true );

    /// forms unique regions from the lists of element ids (0..n-1) stored in the model topology object
    bool FormRegionsFrom( const ModelTopology& );

    /// treats the values of the property as discrete, forming one region per value and returning their names into the set
    void FormRegionsFromPropertyValues( const char* prop, std::set<std::string>& region_names );

    /// forms a new non-unique region from elements whose property value falls into the user-defined range
    bool FormRegionFrom( const char* regionname, const char* prop, double64 pmin, double64 pmax, bool unique=false );

    /// forms region from complex value constraints as provided via a PropertyContraints object that has to be configured before
    bool FormRegionFrom( const char* regionname, PropertyConstraints&, bool unique=false );

    /// forms region from element id numbers that must be in the range 0..n-1
    bool FormRegionFrom( const char* regionname, std::vector<size_t>& element_numbers );

    /// forms region that represents union of preexisting regions. @todo SKM remove method as it duplicates MergeRegions()
    void FormRegionFrom( const char* regionname, const std::set<std::string>& region_names );

    template<template<size_t> class ElementComp>
    bool FormRegionFrom( const char* regionname, ElementComp<dim> const& elementComp, const char* hostRegion = "Model" );

    /// forms unique or non-unique regions. @todo SKM deprecate this method as it is equivalent to CopyRegion()
    bool FormRegionFrom( const char* regionname, const csmp::Region<dim>& region, bool unique=false );


    // -----------------------------------------------
    // Manipulations with already existed Regions
    // -----------------------------------------------
    
    /// assigns unique region-indicative variable values to the elements of all unique regions and returns name value mapping vector[value]=name
    size_t CountAndLabelRegions( const char* region_identifier, std::vector<std::string>& region_names );

    /// finds disconnected subregions in region, dividing it into these. The new subregion are numbered and their total # is returned
    size_t  PartitionRegionIntoContiguousSubRegions( const char* region );
    
    /// like partitionR.. but using element ids instead of pointers
    size_t  PartitionRegionIntoContiguousSubRegionsByIdx( const char* region );
    
    /// removes all regions with the given name followed by an arbitrary number; returns number of removed regions=partitions
    size_t  RemoveRegionPartitionsFor( const char* name );

    /// forms a non-unique rectangular region of elements whose barycenter falls into the bounding box defined by the points
    bool    FormRectangularRegion( const char* regionname, const csmp::Point<dim>& xyz_min, const csmp::Point<dim>& xyz_max );

    /// replicates region and gives duplicate a new name (@attention now you also have new property storage for regional variables)
    void    CopyRegion( const char* existing_region, const char* copied_region, bool place_copy_in_unique_regions=false );

    /// adds the region specified by first argument to the existing region given by second argument
    void    AssimilateRegion( const char* region_to_add, const char* region_to_be_added_to );

    /// merges multiple regions as identified by their names into a new master region
    void    MergeRegions( const std::set<std::string>& input_regions, const char* ensemble_region );
    size_t  MergeRegions( const char* region_name_tag, const char* ensemble_region );

    /// removes region and associated variable storage, and optionally the underlying elements, nodes etc.
    void    RemoveRegion( const char* regionname, bool delete_elements );

    // NEW!
    /// excludes the intersection of elements of the 2 regions from the non-unique region
    bool    RemoveFromRegion( const char* region, const char* region_to_subtract );
    
    // NEW!
    /// moves region to from the unique- to the non-unique regions map
    bool    MoveToNonUniqueRegions( const char* unique_region );

    /// boolean operation: include
    bool    RegionIncludes( const char* region_a, const char* region_b ) const;

    /// boolean operation: union
    bool    RegionUnion( const char* region_a, const char* region_b, const char* region_union );

    /// boolean operation: intersection
    bool    RegionIntersection( const char* region_a, const char* region_b, const char* region_intersection );

    /// boolean operation: difference (returns the data in region a that is not in region b)
    bool    RegionDifference( const char* region_a, const char* region_b, const char* region_diff );

    /// boolean operation: symmetric difference (the symmetric difference is the union without the intersection)
    bool    RegionSymmetricDifference( const char* region_a, const char* region_b, const char* region_symdiff );

    // TODO: test
    /// creates a lower-dimensiona region along the contact area of 2 higher dimensional ones
    bool    RegionBetween( const char* region_a, const char* region_b, const char* region_between );
    
    /// finds the contact area between regions a and b, logging pairs of element pointers and face numbers; @return number of shared faces
    size_t  SharedPerimeterFaces( const char* region_a, const char* region_b,
                                  std::vector<std::tuple<Element<dim>*,Element<dim>*,size_t,size_t> >& shared ) const;

  protected:
  
    /// creates a region that contains all elements of the model
    void CreateOverallModelRegionFromMeshManager( bool model_is_unique );

    std::map<std::string,csmp::Region<dim> >  uniqueGroupMap_; ///< map of regions that do not overlap
    std::map<std::string,csmp::Region<dim> >  groupMap_;       ///< map of potentially overlapping regions

private:
    RegionInterface( const RegionInterface& );
};

} // csmp

#endif
