#ifndef REGIONS_INTERFACE_H
#define REGIONS_INTERFACE_H

#include "CSMP_definitions.h"

namespace csmp {

class PropertyConstraints;
class ModelTopology;
template<uint32_t> class Region;
template<uint32_t> class Element;
template<uint32_t> class Node;
template<uint32_t> class Point;

/**
@brief Policy of the class model for the management of its labeled subdomains that
are equivalent to the parts (CAD) or geobodies of the input model.

@author S.K. Matthai
@author P. Lang
@date 2010

@section motivation Motivation

Break the complex interface of the model down into functional units.

@section design Design Intent and Rules

Policy of the Model that manages any kind of Region objects, i.e. ModelSubDomain objects
that consist of Elements.

@attention there can be unique (non-overlapping) and non-unique regions. A region "Model"
that encompasses all elements that form part of the Model class' computational domain
is either unique or non-unique, depending on whether there are other unique regions
(in this latter case it is non-unique).

@attention there is a second "fixed" master region that is always there. It is always called "Model" and
its purpose is as the default computational domain, i.e. when you compute something on the mdel
this region called "Model" will include all parts of the model's computational domain.
However, the "Model" region does not automatically include the other non-unique regions
nor Faces or InterFace objects which are managed by the Boundary and SplitBoundary classes.

@section collaborations Collaborations

The RegionInterface relies on the functionality of the Region derived from the ModelSubDomain class.

@section examples Application Examples

Interface allows to construct a region or reference regions, for example:

@code
// for each distinct value of the 'permeability' a region is created
set<string>  group_names;
model.FormRegionsFromPropertyValues( "permeability", group_names );
//    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cout <<"\n\n\nmain: FormRegionsFromPropertyValues()  creating 'permeability' regions: ";
for ( set<string>::const_iterator it=group_names.begin(); it!=group_names.end(); it++ ) cout << (*it) <<" ";
cout << endl;
@endcode

@bug the value of region properties values  that were generated by boolean operators or when merging regions
are not defined. A rule is needed to assign them in a consistent fashion

TODO: @todo !!! all methods that create regions from regions must also copy potential regional property values to these

*/
template<uint32_t dim, template<uint32_t> class REGION_COMPLEX>
class RegionInterface {
  public:
    RegionInterface() {}
    RegionInterface( const RegionInterface& ) = delete;
    ~RegionInterface() {}

    /// checks whether region exists considering both unique and non-unique regions
    bool ContainsRegion( const std::string& regionname ) const;

    /// returns const reference to region
    const csmp::Region<dim>&  Region( const std::string& region_name ) const;

    /// returns reference to region
    csmp::Region<dim>&  Region( const std::string& region_name );

    /// checks whether the region is space exclusive, i.e. does not contain any other regions
    bool IsUnique( const std::string& regionname ) const;

    /// checks whether all elements within the region are interconnected (if the region has multi-dimensional elements this is never the case)
    // see model subdomain: bool IsContiguous( const std::string& regionname ) const;
 
     /// using the unique region ID (=domain idx) assigned to any ModelSubDomain upon creation, this method searches for the corresponding unique region
    csmp::Region<dim>&  RegionByDomainIndex( int32_t domain_index );

    /// checks that there is a model region and that it contains elements
    bool HasValidModelRegion() const;
    

    // -----------------------------------------------
    //  Input/output
    // -----------------------------------------------

    size_t RegionsOut() const;
    
    /// prints ModelSubDomain::domain_idx_ assigned automatically using reference count mechanism
    void PrintDomainIndices() const;

    /// writes unique and non-unique regions to binary file, including, interior/perimeter/boundary face information; relies on unique indexes
    void OutputRegionsToBinary( const char* file_name ) const;

    /// Reads unique and non-unique regions from binary file as written by OutputAllRegionsToBinary(); it can also read only a subset of variables
    void InputRegionsFromBinary( const char* file_name, const std::set<std::string>& subset_variables );


    // -------------------------------------------------------------------------
    //  Regions access and manipulations with the list of Regions
    // -------------------------------------------------------------------------

    /// iterators to associative containers of regions
    typedef typename std::map<std::string, csmp::Region<dim> >::iterator        regionIterator;
    typedef typename std::map<std::string, csmp::Region<dim> >::const_iterator  regionConstIterator;

    // non-unique (potentially overlapping) regions
    regionIterator            RegionsBegin();
    regionIterator            RegionsEnd();
    regionConstIterator       RegionsBegin() const;
    regionConstIterator       RegionsEnd() const;

    // unique (spatially exclusive) regions
    regionIterator            UniqueRegionsBegin();
    regionIterator            UniqueRegionsEnd();
    regionConstIterator       UniqueRegionsBegin() const;
    regionConstIterator       UniqueRegionsEnd() const;

    /// number of non-unique regions that potentially overlap
    size_t                    Regions() const;
    /// number of regions that are space eclusive like the subvolumes of a water tight CAD model
    size_t                    UniqueRegions() const;
    
    /// changes the subdomain name and the search key in the region map with deletion or copying of elements
    bool                      RenameRegion( const std::string& old_name, const std::string& new_name );


    // -----------------------------------------------
    // Region creation
    // -----------------------------------------------

    /// builds master region 'Model' (discontigous or not) including all elements (line, surface, or volume if any); this regions is then used to build others
    size_t FormModelRegion( bool is_unique );
    
    /// forms unique or non-unique region including entire range of elements; returns number of elements created (USED TO CREATE MODEL REGION 22/5/21)
    size_t FormRegionFrom( const char* regionname,
                           typename std::vector<Element<dim>*>::iterator first,
                           typename std::vector<Element<dim>*>::iterator last,
                           bool unique = false );

    /// treats the values of the property as discrete, forming one region per value and returning their names into the set; returns number of regions
    size_t FormRegionsFromPropertyValues( const char* prop, std::set<std::string>& region_names );

    /// forms unique regions from the supplied element ids (0..n-1) stored in ModelTopology; assigns region number to element material IDs if empty; returns # of regions formed
    size_t FormRegionsFrom( const ModelTopology&, bool ignore_domain_type_identifiers=false );

    // FROM THE 'MODEL' REGION THAT NEEDS TO BE CREATED BEFORE

    /// creates unique regions from material IDs which must have been defined earlier; returns number of regions formed; returns number of regions
    size_t FormRegionsFromMaterialIDs();
    
    /// Assuming that elements have been numbered as required by caller, method forms region of elements with this Idx() values; returns # of elements in region; returns number of elements
    size_t FormRegionFrom( const char* regionname, std::vector<size_t>& elmt_ids, bool is_unique=true );

    /// forms a new non-unique region from elements whose property value falls into the user-defined range; returns number of elements
    size_t FormRegionFrom( const char* regionname, const char* prop, double pmin, double pmax, bool unique = false );

    /// forms region from complex value constraints as provided via a PropertyContraints object that has to be configured before; returns number of elements
    size_t FormRegionFrom( const char* regionname, PropertyConstraints&, bool unique = false );

    /// forms region that represents union of preexisting regions. @todo SKM remove method as it duplicates MergeRegions(); returns number of elements
    size_t FormRegionFrom( const char* regionname, const std::set<std::string>& region_names );

    /// ; returns number of elements
    template<template<uint32_t> class ElementComp>
    size_t FormRegionFrom( const char* regionname, ElementComp<dim> const& elementComp, const char* hostRegion = "Model" );

    /// Assuming that the supplied n-nodes are in sequence of a polyline, method forms n-1 line elements putting them into a now limer-dimensional region
    size_t FormRegionFrom( const char* regionname, std::vector<Node<dim>*>& nodes, bool is_unique=true );

    size_t FormRegionInBoundingBox( const char* regionName,
                                    const Point<dim>& cnr_min, const Point<dim>& cnr_max,
                                    bool all_nodes_must_be_within );
                                    

    // -----------------------------------------------
    // Manipulations with already existed Regions
    // -----------------------------------------------

    /// assigns unique region-indicative variable values to the elements of all unique regions and returns name value mapping vector[value]=name
    size_t  CountAndLabelUniqueRegions( const char* region_identifier, std::vector<std::string>& region_names );

    // E.P Compares material identifier with number of unique regions in model (this must match unless regions have been eliminated)
    bool CheckRegionIdentifierIsUpToDate( const char* region_identifier );

    /// finds disconnected subregions in region, dividing it into these. The new subregion are numbered and their total # is returned
    size_t  PartitionRegionIntoContiguousSubRegions( const char* region );
    
    // Andrew Bromage implementation using UnionFind
    size_t  PartitionRegionIntoContiguousSubRegions_Bromage( const char* region );

    /// removes all regions with the given name followed by an arbitrary number; returns number of removed regions=partitions
    size_t  RemoveRegionPartitionsFor( const char* name );

    /// forms a non-unique rectangular region of elements whose barycenter falls into the bounding box defined by the points
    size_t  FormRectangularRegion( const char* regionname, const csmp::Point<dim>& xyz_min, const csmp::Point<dim>& xyz_max );

    /// replicates region and gives duplicate a new name (@attention now you also have new property storage for regional variables)
    void    CopyRegion( const char* existing_region, const char* copied_region, bool place_copy_in_unique_regions = false );

    /// adds the region specified by first argument to the existing region given by second argument
    void    AssimilateRegion( const char* region_to_add, const char* region_to_be_added_to );

    /// merges multiple regions as identified by their names into a new master region
    void    MergeRegions( const std::set<std::string>& input_regions, const char* ensemble_region );
    size_t  MergeRegions( const char* region_name_tag, const char* ensemble_region );

    /// removes region and associated variable storage;  MeshManager removes elements and rebuilds connectivity if requested, but only if  region is unique
    void    RemoveRegion( const char* regionname, bool erase_elements = false );

    /// excludes the intersection of elements of the 2 regions from the non-unique region
    bool    RemoveFromRegion( const char* region, const char* region_to_subtract );

    /// removes the elements shared with the supplied set from the region
    bool    RemoveFromRegion( const char* region, const std::set<Element<dim>*>& elmt_set );

    /// moves region to from the unique- to the non-unique regions map
    bool    MoveToNonUniqueRegions( const char* unique_region );

    /// boolean operation: include
    bool    RegionIncludes( const char* region_a, const char* region_b ) const;

    /// boolean operation: union
    bool    RegionUnion( const char* region_a, const char* region_b, const char* region_union );

    /// boolean operation: intersection
    bool    RegionIntersection( const char* region_a, const char* region_b, const char* region_intersection );

    /// boolean operation: difference (returns the data in region a that is not in region b)
    bool    RegionDifference( const char* region_a, const char* region_b, const char* region_diff );

    /// boolean operation: symmetric difference (the symmetric difference is the union without the intersection)
    bool    RegionSymmetricDifference( const char* region_a, const char* region_b, const char* region_symdiff );

    /// finds the contact area between regions a and b, logging pairs of element pointers and face numbers; @return number of shared faces
    size_t  SharedPerimeterFaces( const char* region_a, const char* region_b,
                                  std::vector<std::tuple<Element<dim>*, Element<dim>*, size_t, size_t> >& shared ) const;

    /// if the mesh changed this safe but model-wide method rebuilds the node and element vectors of all regions
    void UpdateRegions();

  protected:
    /// rebuilds unique regions, but only if they contain some nulled element pointers
    void RebuildUniqueRegions();

    //       region name  region / creation constraints
    std::map<std::string, csmp::Region<dim> >   uniqueRegionMap_;  ///<  map of unique regions that do not overlap
    std::map<std::string, csmp::Region<dim> >   regionMap_;        ///<  map of non-unique (potentially overlapping) regions
    std::map<std::string, PropertyConstraints>  regionTraits_;     ///<  criteria how non-unique regions were created
};


// NOn-MEMBER FUNCTIONS

/// Returns those elements from outside Region 2, which share a face or touch (with a node) the perimeter of the inside Region 1
template<uint32_t dim>
size_t haloElements( const Region<dim>& region1, const Region<dim>& region2, std::unordered_set<Element<dim>*>& halo_elmts );

} // csmp

#endif
