var dir_854e1a20a5c6356ccbf09e31b24de07d =
[
    [ "AP_algebraUtilities.h", "_a_p__algebra_utilities_8h_source.html", null ],
    [ "compareFloats.h", "compare_floats_8h.html", null ],
    [ "CompressedRowMatrix.h", "_compressed_row_matrix_8h_source.html", null ],
    [ "CompressedRowMatrixParallel.h", "_compressed_row_matrix_parallel_8h_source.html", null ],
    [ "ConsecutiveSequenceChecker.h", "_consecutive_sequence_checker_8h_source.html", null ],
    [ "CSMP_mathUtilities.h", "_c_s_m_p__math_utilities_8h.html", "_c_s_m_p__math_utilities_8h" ],
    [ "CSRMatrix.h", "_c_s_r_matrix_8h_source.html", null ],
    [ "CubicSpline.h", "_cubic_spline_8h_source.html", null ],
    [ "DenseMatrix.h", "_dense_matrix_8h.html", "_dense_matrix_8h" ],
    [ "denseMatrixMethods.h", "dense_matrix_methods_8h_source.html", null ],
    [ "DynamicArray2D.h", "_dynamic_array2_d_8h_source.html", null ],
    [ "DynamicArray3D.h", "_dynamic_array3_d_8h_source.html", null ],
    [ "FixedArray.h", "_fixed_array_8h_source.html", null ],
    [ "JaggedArray3D.h", "_jagged_array3_d_8h_source.html", null ],
    [ "KahanSummation.h", "_kahan_summation_8h_source.html", null ],
    [ "NewtonRaphson.h", "_newton_raphson_8h_source.html", null ],
    [ "ODE_StiffSolver.h", "_o_d_e___stiff_solver_8h_source.html", null ],
    [ "RandomFieldGenerator.h", "_random_field_generator_8h_source.html", null ],
    [ "SparseMatrix.h", "_sparse_matrix_8h_source.html", null ],
    [ "SumOfProducts.h", "_sum_of_products_8h_source.html", null ],
    [ "SumOfProductsWithExponents.h", "_sum_of_products_with_exponents_8h_source.html", null ],
    [ "tensorOperations.h", "tensor_operations_8h_source.html", null ],
    [ "vectorOperations.h", "vector_operations_8h_source.html", null ]
];