//
//  SplitBoundaryPressureDiffusion_Test.cpp
//  CSMP_API_examples
//
//  Created by Stephan Matthai on 2/09/2015.
//  Copyright (c) 2015 Stephan Matthai. All rights reserved.
//

#include "SplitBoundaryPressureDiffusion_Test.h"
#include "VSet.h"
#include "ModelTopology.h"
#include "Model.h"
#include "Boundary.h"
#include "PDE_Integrator.h"
#include "NumIntegral_dNT_op_dN_dV.h"
#include "NumIntegral_NT_op_N_dV.h"
#include "VelocityAndVolumeFlux.h"
#include "NumIntegral_NT_lhsop_N_dV.h"
// LHS version
#include "NumIntegral_dudn_op_u_dS_InterFace_w_dimM1_Region.h"
// RHS version
#include "NumIntegral_dudn_rhsop_u_dS.h"

#ifdef CSMP_WITH_SAMG_SOLVER
#include "SAMG_Settings.h"
#include "SAMG_Solver.h"
#else
#include "LinearSolver.h"
#endif

#include "ExplicitTransport.h"
#include "finiteVolumeAuxiliaryFunctions.h"

#include "VTK_Interface.h"

using namespace std;

namespace csmp {

SplitBoundaryPressureDiffusion_Test::SplitBoundaryPressureDiffusion_Test( const char* test_model,
                                                                          const char* test_variables )
 : test_model_(test_model),
   test_variable_file_(test_variables),
   model_ptr_(nullptr)
 {
 }




SplitBoundaryPressureDiffusion_Test::~SplitBoundaryPressureDiffusion_Test()
{
   delete model_ptr_;
}




void SplitBoundaryPressureDiffusion_Test::run()
 {
    // 1. Reading SKUA model from input file set
    // ------------------------------------------------------------------------------------
    // Read VSet binary file generated by SKUA
    VSet<3U> vset;
    double model_time = 0.;
    vset.InputFrom( test_model_.c_str(), model_time );

    // Read ModelTopology file generated by SKUA
    ModelTopology  model_topology(true);
    model_topology.InputFromTextFile( test_model_.c_str() );
    
    // Build Model using variables file generated by SKUA
    model_ptr_ = new Model<3U>( model_topology, vset, test_variable_file_.c_str(), false );
    Region<3U>&  model_domain = model_ptr_->Region("Model");
    printModelDimensions( *model_ptr_, true );
  
    // 2. Assigning property values and initial conditions to model
    // ------------------------------------------------------------------------------------
    ConfigureModel();

    VTK_Interface<3U>  vtk_output;
    vtk_output.OutputDataToVTK( *model_ptr_, "model_perm", "permeability", 0 );
    vtk_output.OutputDataToVTK( *model_ptr_, fracture_name_, string("model_perm"), string("permeability"), 0UL );

    // assigning initial uniform fluid pressure of 10 MPa
    const double initial_fluid_pressure{ 1.0e7 };
    model_ptr_->InputPropertyValue( "fluid pressure", makeScalar(PLAIN,initial_fluid_pressure) ); // always in Pascal
    model_ptr_->InputPropertyValue( "fluid volume source", makeScalar(PLAIN,0.) ); // no sources/sinks (units m3 m-2 s-1)
    model_ptr_->Boundary("TOP").InputPropertyValue( "fluid pressure", makeScalar(DIRICH,initial_fluid_pressure) ); // always in Pascal
    model_ptr_->Boundary("BOTTOM").InputPropertyValue( "fluid pressure", makeScalar(DIRICH,initial_fluid_pressure) ); // always in Pascal


    // setting up transient pressure computation
    //cout << "\nEnter the pressure change on the left side of the model in percent: "<< endl;
    const double pressure_change{ initial_fluid_pressure/3. };
    //cin  >> pressure_change;
    cout << "\nNew pressure on the lefthand fracture boundary is " << initial_fluid_pressure - pressure_change << " Pa " << endl;
    // finding the node manifolds in the lefthand boundary and assigning new pressure to them
    csmp::Index pf_key  = model_ptr_->Database().StorageKey("fluid pressure");
    Region<3U>& fracture = model_ptr_->Region( fracture_name_ );
    for ( auto& nit : fracture.NodeVector() )
      if ( nit->AtBoundary() == LEFT ) {
           assert( nit->IsManifold() );
           assert( nit->Manifold()->Branches() >= 2 );
           nit->Store( pf_key, makeScalar(DIRICH,initial_fluid_pressure - pressure_change) );
        }
        
    vtk_output.OutputDataToVTK( *model_ptr_, "fluid-pressure", "fluid pressure", 999, true );



    // 3.  Build a transient fluid pressure algorithm using Backward-Euler time-stepping
    //     that equates to:
    //                       ([C]/dt + [K]){p}t+dt = [C]/dt {p}t + {Q}t+dt
    //
    //      the latter formulation is preferred because it reduces the error due to
    //      the lumping of the storativity matrices such that their contribution to
    //      the righthandside is equivalent to that in the lefthandside.
    // ------------------------------------------------------------------------------------

#ifdef CSMP_WITH_SAMG_SOLVER
    SAMG_Settings  settings;
    settings.Set_eps(0.);
    SAMG_Solver  samg_solver(&settings);
    PDE_Integrator<3U,Element> fluid_pressure(samg_solver);
#else
    CSMP_DEFAULT_LINEAR_SOLVER linear_solver;
    PDE_Integrator<3U,Element>  fluid_pressure(linear_solver);
#endif
   
    // steady state part of the pressure diffusion PDE
    // -----------------------------------------------
    NumIntegral_dNT_op_dN_dV<3U> conductance( model_ptr_->Database(), "conductivity", "fluid pressure",  "fluid pressure" );
    NumIntegral_NT_op_N_dV<3U>   source( model_ptr_->Database(),  "fluid volume source", "fluid pressure" );
  /// @todo influx surface integral: NumIntegral_NT_op_N_dS<2U>   influx( model.Database(), "influx", "fluid pressure" );
    VelocityAndVolumeFlux<3U>    velocity( *model_ptr_,  "conductivity", "porosity", "fluid pressure", false );

    // add PDE_Operators and post-processor to the FE Algorithm
    fluid_pressure.Add( &conductance );
    fluid_pressure.Add( &source );
  //  fluid_pressure.Add( &influx );
    fluid_pressure.AddPostProcess( &velocity );

    // transient part of the pressure diffusion PDE
    // --------------------------------------------
    // left-hand side capacitance matrix [C] at pressure d+dt
    NumIntegral_NT_lhsop_N_dV<3U> capacitance_lhs( model_ptr_->Database(),
                                                   "storativity",  "fluid pressure", "fluid pressure" );
    capacitance_lhs.LumpedFormulation(true);
    capacitance_lhs.MultiplyWithTimeIncrement(true);

    // right-hand side capacitance matrix [C] at current pressure
    NumIntegral_NT_op_N_dV<3U>    capacitance_rhs( model_ptr_->Database(),
                                                   "storativity",  "fluid pressure" );
    capacitance_rhs.LumpedFormulation(true);
    capacitance_rhs.MultiplyWithTimeIncrement(true);

    // source term {Q} at  dt + delta  needs to be accumulated later
    source.AddAccumulateLater();
    source.LumpedFormulation(true);
        
    // interface transfer modelled with LHS integral
    NumIntegral_dudn_op_u_dS_InterFace_w_dimM1_Region<3U>  iface_transferLHS( *model_ptr_,
                                                                             "conductivity",
                                                                             "fluid pressure", "fluid pressure",
                                                                              60. ); // seconds initial timestep

    // interface transfer modelled with RHS integral
    NumIntegral_dudn_rhsop_u_dS<3U>  iface_transferRHS( *model_ptr_, "fracture conductivity", "conductivity", "fluid pressure" );
    iface_transferRHS.AddAccumulateLater();
    
    

    // coupling across the sides of the splitboundary
    // (via MathOperatorLHS)
    // ----------------------------------------------

    // add PDE_Operators and post-processor to the FE Algorithm
    // and multiply with time-increment
    fluid_pressure.Add( &conductance );
    fluid_pressure.Add( &capacitance_lhs );
    fluid_pressure.Add( &capacitance_rhs );
    fluid_pressure.Add( &source );
    fluid_pressure.AddSplitBoundaryIntegral( &iface_transferRHS );
    fluid_pressure.AddPostProcess( &velocity );



    // 4. Transient loop: Compute fluid pressure during each time-step and output the results for each time step
    // ---------------------------------------------------------------------------------------------------------
    const double maxtime{ 365. * 86400. }; // 1 year
    double       time_increment{ 0.5 }; // seconds
    uint32_t     timestep{ 1U };
    // iout: for the transient loop, the screen output from SAMG solver is reduced
    #ifdef USE_SAMG_SOLVER
    settings.Set_iout1( 0 );
    settings.Set_iout2( 0 );
    settings.Set_idmp( -1 );
    #endif

    while ( model_time <= maxtime )
      {
        cout << "\n\n\nmain: COMPUTING TIMESTEP " << timestep << endl;
        iface_transferLHS.UpdateTimeIncrement( time_increment );
        iface_transferRHS.UpdateTimeIncrement( time_increment );

        // transient pressure
        fluid_pressure.TimeIncrement( 1. / time_increment ); // see equation above
//        fluid_pressure.IntegrateOver( *model_ptr_, fracture ); // model_domain );
        fluid_pressure.IntegrateOver( *model_ptr_, model_domain );
        iface_transferLHS.ResetMinMaxTransferTerms();
        iface_transferRHS.ResetMinMaxTransferTerms();

        // output variables to file and screen
        printRangeOfVariable( *model_ptr_, "fluid pressure" );
        printRangeOfVariable( *model_ptr_, "velocity" );
        printRangeOfVariable( *model_ptr_, "pore velocity" );
        printRangeOfVariable( *model_ptr_, "volume flux" );

        // VTK
        vtk_output.OutputDataToVTK( *model_ptr_, "fluid-pressure", "fluid pressure", timestep );
        vtk_output.OutputDataToVTK( *model_ptr_, fracture_name_, string("fluid-pressure"), string("fluid pressure"), timestep );
        vtk_output.OutputDataToVTK( *model_ptr_, "velocity",       "velocity",       timestep );
        vtk_output.OutputDataToVTK( *model_ptr_, "volume-flux",    "volume flux",    timestep );

        // Preparing next Time Step
        model_time += time_increment;
        // Ramping up the time increment
        time_increment *= 1.2;
        timestep++;

        cout << "\nmain: ELAPSED TIME " << model_time << " seconds." << endl;
     }

    cout <<"\nmain: That's it..."<< endl;
 
 } // end run





/**
    Creates fracture region in Splitboundary and initialises the model parameters thickness, permeability, porosity, total velocity everywhere.
*/
void  SplitBoundaryPressureDiffusion_Test::ConfigureModel()
 {
    assert( model_ptr_ != nullptr );
    
     // property assigment
    model_ptr_->InputPropertyValue( "thickness",     makeScalar(ANY,1.0) );
    model_ptr_->InputPropertyValue( "permeability",  makeScalar(ANY,1.0e-13) );  // 100 mD
    model_ptr_->InputPropertyValue( "conductivity",  makeScalar(ANY,1.0e-10) ); // dyn visc = 1.0e-3
    // to get PDE_Integrator to detect interfaces with a fracture within and Robin boundary conditions applied
    model_ptr_->InputPropertyValue( "fracture conductivity", makeScalar(ROBIN,numeric_limits<double>::quiet_NaN()) );
    model_ptr_->InputPropertyValue( "porosity",      makeScalar(ANY,0.13) );
    model_ptr_->InputPropertyValue( "fluid volume source", makeScalar(ANY,0.) );
    model_ptr_->InputPropertyValue( "storativity", makeScalar(ANY,1.0e-11) );
    
    // SplitBoundary<3U>& fracture_slit = model_ptr_->SplitBoundary("fracture_SPLITBOUNDARY");
    //fracture_slit.InputPropertyValue( "interface thickness", makeScalar(ANY,1.0e-3) ); // 1mm
    
    // creating a splitboundary in the fracture
    const int32_t material_id_for_new_elements{5};
    pair<string,bool> new_region = model_ptr_->InsertRegionIntoSplitBoundary("fracture_SPLITBOUNDARY", material_id_for_new_elements );
    Region<3U>& fracture = model_ptr_->Region( new_region.first );
    fracture_name_ = new_region.first;
    fracture.InputPropertyValue( "thickness",    makeScalar(ANY,1.0e-3) );
    fracture.InputPropertyValue( "porosity",     makeScalar(ANY,1.0) ); // 100%
    fracture.InputPropertyValue( "permeability", makeScalar(ANY, pow(0.001,3)/12. ) ); // 1-mm aperture fracture with 1.0e-9 m2 k
    fracture.InputPropertyValue( "conductivity", makeScalar(ANY, 1e3 * pow(0.001,3)/12. ) );
    fracture.InputPropertyValue( "storativity",  makeScalar(ANY,1.0e-9) ); // Pa-1 (greater than matrix)
    
    // computing the hydraulic diffusivity, kappa_p = k / (phi * storativity * viscosity), storativity is equivalent to total systems compressibility
    const csmp::Index k_key   = model_ptr_->Database().StorageKey("permeability");
    const csmp::Index phi_key = model_ptr_->Database().StorageKey("porosity");
    const csmp::Index Ss_key   = model_ptr_->Database().StorageKey("storativity");
    const csmp::Index hd_key = model_ptr_->Database().StorageKey("hydraulic diffusivity");
    const double viscosity{ 1.0e-3 };
    Region<3U>& model_domain = model_ptr_->Region("Model");
    
    for ( auto& it : model_domain.CellVector() ) {
         double hdiffusivity = it->Read( k_key );
         hdiffusivity /= it->Read(phi_key) * it->Read(Ss_key) * viscosity;
         it->Store( hd_key, makeScalar(PLAIN,hdiffusivity) );
      }
    
    printRangeOfVariable( *model_ptr_, "hydraulic diffusivity" );
    
} // end configure







// TODO: HELPER FUNCTIONS THAT NEED TO BE PUT INTO A LOGICAL PLACE /thermal ?

/** Analytic one-dimensional temperature profile in homogeneous material.
 
    @param T0 temperature of medium before boundary temperature was changed (oC)
    @param kappa thermal diffusivity (m2/s)
    @param x distance from interface (m)
    @param t time (s)
*/
double temperatureDiffusion1D( double T0, double kappa, double x, double t )
 {
    return T0 * erf( x / (2. * sqrt( kappa * t ) ) );
 }



/** Derivative * thermal conductivity product at x0
*/
double heatFlow1DAtX0( double T0, double kappa, double t, double K )
 {
    // derivative pf previous expression
    constexpr double pi = 3.14159265358979323846;
    const double     sqrtPi{ sqrt(pi) }, x{0.};
    const double     x2{ x * x };
    double dTdx  = T0 * exp( -x2 ) / (4. * kappa * t);
    dTdx /= sqrtPi * sqrt( kappa * t );

    // heat flux
    return dTdx * K;
 }



} // end csmp
