#include "Partitioner.h"
#include "partitionVSet.h"
#include "SAMGp_CommunicationData.h"
#include "ParallelIO.h"

using namespace std;

namespace csp
 {
    csp::ErrorHandler skm_err;
    csp_float         global_time;
 }

using namespace csp;

int main()
{
   /*
  Prepartitioner:

  Use this main file to partition a vset file containing a global
  2D triangular mesh into subdomains. 
  vset files, continaining the sub-domains will be stored as well
  as txt files containing the communication data between processors
  These files can be read in using memberfunctions in ParallelIO<fT,dim>
  */

  char fname[200];
  cout<<"\n\nGive vset file to partition"<< endl;
  cin >> fname;

  int n_procs;
  cout<<"\n\nGive number of partitions"<< endl;
  cin >> n_procs;

  char rank[200];
  // meshing
  VSet<csp_float,3> saved_model;
  saved_model.InputFrom( fname, global_time);
  bool isoparametric(false);

  // Partitioning. create pointers
  std::vector<VSet<csp_float,3> >     vsets;
  VSetConnectivity<csp_float,3>       VSetConn;

  // vectors for partition storage
  std::vector<std::vector<stl_index> >               element_vector;
  std::vector<std::set<std::pair<stl_index,int> > >  outerhalo;

  cout <<"\nPrepartitioner 3D: calling the Partitioner"<< endl;

  // partition mesh
  Partitioner<csp_float,3>                           partitioner( saved_model, n_procs );
  partitioner.FastPartition( element_vector, true ); // true = 3D
  partitioner.GetOuterhaloNodes(outerhalo);

  cout <<"\nPrepartitioner 3D: partitioning the VSet"<< endl;

  // create sub-VSets from global VSet and partition storage vectors
  partitionVSet( saved_model, element_vector, outerhalo, vsets, VSetConn, isoparametric );
  SAMGp_CommunicationData<csp_float,3>*            samgp_par;

  // store sub-VSets in vset-files
  int total_overlap(0), overlap(0);
  for(int my_rank=0;my_rank!=n_procs;my_rank++)
   {

     cout <<"\nPrepartitioner 3D: writing communication data to file for rank "<<my_rank<< endl;
     samgp_par = new SAMGp_CommunicationData<csp_float,3>(VSetConn, my_rank);
     ParallelIO<csp_float,3>        VSetIO(n_procs,my_rank);
     VSetIO.WriteToTextFile(*samgp_par, fname);

     // create name local input file
     sprintf(rank, "%ld", static_cast<long>(my_rank));
     string filename(fname);
     filename += "_"; filename += rank;

     cout <<"\nPrepartitioner 3D: writing binary file for rank "<<my_rank<< endl;
     vsets[my_rank].ParallelOutputTo(filename.c_str(), global_time, VSetConn.GetFirstOuterhalo(my_rank));

     // count overlap between this rank and its neighbors
     overlap = 0;
     for(int rank=0;rank!=n_procs;rank++)
       if(rank!=my_rank)
         overlap += VSetConn.CommunicationVolume(rank, my_rank);
     total_overlap += overlap; 
  }
  // overlap counted double:
  total_overlap /= 2;
  csp_float overlap_in_percent = static_cast<csp_float>(total_overlap)/static_cast<csp_float>(saved_model.Vertices())*100.;

  cout <<"\n\nPrepartitioner 3D:\tvset-file '"<<fname<<".vset' was succesfully partitioned into "<<n_procs<<" partitions."<< endl;
  cout <<"\tEach partition was saved in vset-file '"<<fname<<"_rank.vset'"<< endl;
  cout <<"\tCommunication data for each partition was saved in text-file '"<<fname<<"_rank_SAMGp_Comm.txt'"<< endl;
  cout <<"\tTotal overlap nodes generated by partitioning: "<<total_overlap<<" = "<<overlap_in_percent<<"% of total."<< endl;
  cout <<"\tEstimated computational efficiency: "<<(100. - 3.9 * overlap_in_percent)<< endl;
  cout <<"\t(NOTE: efficiency is conservative lower estimate !! )"<< endl;

  cout <<"\n\nmain:\tHave fun in the parallel world..."<< endl;

  return 0;
   
  
} // end main



