#ifndef VTK_TYPE_H
#define VTK_TYPE_H

namespace csmp {

/// polygonal data types supported by the Visual Tool Kit (VTK) from kitware.com
enum VTK_TYPE // keep default int because it is written to file
{ 
  VTK_VERTEX=1,
  VTK_POLY_VERTEX=2,
  VTK_LINE=3,
  VTK_POLYLINE=4,
  VTK_TRIANGLE=5,
  VTK_TRIANGLE_STRIP=6,
  VTK_POLYGON=7,
  VTK_QUAD=9,
  VTK_TETRA=10,
  VTK_HEXAHEDRON=12,
  VTK_WEDGE=13,
  VTK_PYRAMID=14,
  VTK_QUADRATIC_EDGE=21,
  VTK_QUADRATIC_TRIANGLE=22,
  VTK_QUADRATIC_QUAD=23,
  VTK_QUADRATIC_TETRA=24,
  VTK_QUADRATIC_HEXAHEDRON=25,
  VTK_QUADRATIC_WEDGE=26,
  VTK_QUADRATIC_PYRAMID=27,
  VTK_BIQUADRATIC_QUAD=28,
  VTK_BIQUADRATIC_TRIANGLE=34
};

} // csmp

#endif
