var searchData=
[
  ['library_20examples_20and_20tests_20with_20cmake_0',['Building CSMP (Library, Examples and Tests) with CMake',['../md__r_e_a_d_m_e.html#autotoc_md106',1,'']]],
  ['license_1',['License',['../md__r_e_a_d_m_e.html#autotoc_md125',1,'']]],
  ['licensing_2',['Licensing',['..//Users/skmatthai/OpenCSMP/open-csmp-2024/source/includes/eos/Water.h#licensing',1,'']]],
  ['linear_20elastic_3a_20plane_20stress_20strain_20problem_20under_20uniform_20traction_3',['Linear Elastic: Plane stress/Strain problem under uniform traction',['../classcsmp_1_1_linear_elastic_isotropic_deformation2_d___v_v_case.html#autotoc_md44',1,'']]],
  ['linear_20elasticity_20mdash_4',['BEGIN TESTING OF LINEAR ELASTICITY ---------------------------------------------&amp;mdash;',['../classcsmp_1_1_linear_elastic_isotropic_deformation2_d___v_v_case.html#autotoc_md47',1,'']]],
  ['linear_20elasticity_20test_20case_20a_5',['Linear Elasticity Test Case A',['../classcsmp_1_1_linear_elasticity_a___v_v_case.html#autotoc_md48',1,'']]],
  ['linear_20elasticity_20test_20case_20c_6',['Linear Elasticity Test Case C',['../classcsmp_1_1_linear_elasticity_c___v_v_case.html#autotoc_md52',1,'']]],
  ['linear_20elasticity_20test_20case_20d_7',['Linear Elasticity Test Case D',['../classcsmp_1_1_linear_elasticity_d___v_v_case.html#autotoc_md54',1,'']]],
  ['linear_20elasticity_20test_20case_20e_8',['Linear Elasticity Test Case E',['../classcsmp_1_1_linear_elasticity_e___v_v_case.html#autotoc_md56',1,'']]],
  ['linear_20elasticity_3a_20plane_20strain_20problem_20with_20central_20crack_20under_20uniform_20tension_20testing_20the_20aperture_20profile_20of_20the_20crack_20compared_20to_20sneddon_20analytical_20solution_9',['Linear Elasticity: Plane strain problem with central crack under uniform tension; testing the aperture profile of the crack compared to Sneddon Analytical solution',['../classcsmp_1_1_linear_elastic_fracture_aperture2_d___v_v_case.html#autotoc_md37',1,'']]],
  ['linear_20elasticity_3a_20plane_20stress_20strain_20problem_20with_20central_20crack_20under_20uniform_20tension_20testing_20the_20aperture_20profile_20of_20the_20crack_10',['Linear Elasticity: Plane stress strain problem with central crack under uniform tension testing the aperture profile of the crack',['../classcsmp_1_1_sneddon_crack___v_v_case.html#autotoc_md58',1,'Linear Elasticity: Plane stress/strain problem with central crack under uniform tension; testing the aperture profile of the crack'],['../classcsmp_1_1_sneddon_crack_coupled3_d___v_v_case.html#autotoc_md67',1,'Linear Elasticity: Plane stress/strain problem with central crack under uniform tension; testing the aperture profile of the crack'],['../classcsmp_1_1_sneddon_crack_coupled___v_v_case.html#autotoc_md78',1,'Linear Elasticity: Plane stress/strain problem with central crack under uniform tension; testing the aperture profile of the crack']]],
  ['linearelasticity_20test_20case_20b_11',['LinearElasticity Test Case B',['../classcsmp_1_1_linear_elasticity_b___v_v_case.html#autotoc_md50',1,'']]],
  ['linux_20based_20os_12',['linux based os',['../classcsmp_1_1_s_a_m_g___solver.html#segFault',1,'Segmentation Fault on some linux based os'],['../todo.html#_todo000116',1,'Segmentation Fault on some linux based os']]],
  ['list_13',['List',['../test.html',1,'Test List'],['../todo.html',1,'Todo List']]],
  ['list_14',['To do list',['../class_h2_o_na_cl_thermal_equilibrator_1_1h.html#todo',1,'']]],
  ['loop_15',['loop',['../classcsmp_1_1_thermal_convection_e_t_h_z___example.html#autotoc_md7',1,'4. Time evolution loop'],['../classcsmp_1_1_geothermal___example.html#autotoc_md4',1,'5. PT-equlibration loop']]],
  ['lubrication_20equation_16',['Lubrication Equation',['../classcsmp_1_1_sneddon_crack_coupled3_d___v_v_case.html#autotoc_md75',1,'Lubrication Equation'],['../classcsmp_1_1_sneddon_crack_coupled___v_v_case.html#autotoc_md86',1,'Lubrication Equation']]],
  ['lubrication_20parameter_20configuration_17',['Lubrication Parameter Configuration',['../classcsmp_1_1_sneddon_crack___v_v_case.html#autotoc_md62',1,'Elasto-Lubrication Parameter Configuration'],['../classcsmp_1_1_sneddon_crack_coupled3_d___v_v_case.html#autotoc_md71',1,'Elasto-Lubrication Parameter Configuration'],['../classcsmp_1_1_sneddon_crack_coupled___v_v_case.html#autotoc_md82',1,'Elasto-Lubrication Parameter Configuration']]]
];
