#include "InputDataManager.h"
#include "ComputationalSettings.h"
#include "Model.h"
#include "Region.h"
#include "Boundary.h"
#include "SplitBoundary.h"
#include "Node.h"
#include "Element.h"
#include "Face.h"
#include "InterFace.h"

#include "TextFileIO.h"

using namespace std;

namespace csmp {

/** Constructs the data input manager.

@section messages Messages

The method reports on the requirements that the input must meet
to be parsed correctly.
*/
template<uint32_t dim>
void InputDataManager<dim>::Help() const
 {
    cout <<"\nInputDataManager (constructor): "<< endl;
    cout <<"\nYou are configuring your model from an input file in text format.";
    cout <<"\nThis file must have the extension '.configuration'.";
    cout <<"\n\nFILE SPECIFICATIONS"<< endl;
    cout <<"\nFile should contain the following data blocks (separated by blank lines): "<< endl << endl;
    cout <<"\n1. Simulation title (name, date, reference)" << endl;
    cout <<"\n2. Subregions to be identified as regions or 'no regions' text string";
    cout <<"\n(example: fault zone	'tab' permeability	'tab' 1.0e-12 'tab' 1.0e-11)" << endl;
    cout <<"\n3. Initial values and material properties applied to entire model";
    cout <<"\n(example: permeability 'tab' 1.0e-13)"<< endl;
    cout <<"\n4. Initial values and material properties applied to specific regions (see above)";
    cout <<"\n(example: fault zone 'tab' interior 'tab' porosity 'tab' 0.25)"<< endl;
    cout <<"\n5. Essential conditions (if of vector type, set of values must be followed by conditional flags)";
    cout <<"\n(example: top	'tab' Dirichlet 'tab' fluid pressure 'tab' 1.0 'tab' 1.0)"<< endl;
    cout <<"\n6. Condition flags applied to parts of or entire regions";
    cout <<"\n(example: well 'tab' interior 'tab' fluid pressure 'tab' Dirichlet)"<< endl;
    cout <<"\n\nNOTES: "<< endl;
    cout <<"\nTabs delimit input fields; white space cannot be used as delimiter !";
    cout <<"\nComments can be inserted but must be preceded by the pound (#) character.";
    cout << endl << endl;
 }



/**

The agreed file structure for FRED-based CSMP models combines the
assigment of material properties with that of boundary conditions and
computational settings such as the run duration, time-stepping strategy,
and output times.

@section arguments Input Arguments

The method takes a reference to the model that will be configured and
the name of the input file to which the extension '-FRED-input.txt' will
be appended.

@return The method returns node point locations which represent the intersection
of lines representing wells with fracture surfaces. The last method
argument is the object into which the computational settings will be
stored.

@section application Application

A typical FRED input file may look as follows:

@code
'eight_binary-FRED-input.txt' simple model generated by SKM 10/7/2003

# (1) global material properties
porosity								1.0
nodal fluid volume source				0.0
fluid volume source						0.0
density oil								1000.0
density water							1000.0
viscosity oil							1.0e-3
viscosity water							1.0e-3
saturation oil							0.95
saturation water						0.05
residual saturation wetting phase		0.03
residual saturation non-wetting phase	0.14
# relative permeability model options: 1.=linear, 2.=Brooks-Corey, 3.=van-Genuchten
relative permeability model				2.0
# relative-permeability model parameters
brooks corey parameter					2.0
van genuchten parameter					4.37
entry pressure							1.0e+1

# (2) local material properties (of the fractures)
FRACTURE	complete	aperture		3.0e-3
FRACTURE	complete	compressibility	1.0e-7

# (3) well intersections (well name, intersection point (x,y,z),
#    injection rate (m^3 s-1), saturation oil)
WELL1	20.0508	0.	21.3699		1.1574e-4	0.
WELL2	87.8615	0.	23.359		-1.1574e-4	0.

# (4) computational settings
time stepping	pedantic
duration		86400.
output time		10000.
output time		43200.
@endcode

@section messages Messages

The assignment process is verbose. The progress of the reading process
is echoed to screen so that the last line which appears before a problem
is reported contains the offending characters.
*/
template<uint32_t dim>
bool InputDataManager<dim>::ConfigureFRED_ModelFromFile( Model<dim>& model,
                                                         const char* fname,
                                                         map<string,vector<double> >& well_data,
                                                         ComputationalSettings& settings )
{
    ErrorHandler& csmp_error ( ErrorHandler::Instance() );

    cout <<"\n\nInputDataManager<"<<  dim <<">::ConfigureFRED_ModelFromFile: Configuring model from file..."<< endl;

    ifstream  ifs;
    string    file_header;
    const std::string file_extension( "-FRED-input.txt" );

    // 0. Open the file
    openFile( ifs, fname, file_extension );

    // 1. Read the title
    readFileHeader( ifs, file_header, csmp_error.Verbose() );

    // 2. Read data in blocks
    std::set<std::string> groups;
    bool region_specifications      ( false );  // regionname from parameter range
    bool default_property_values    ( true  );  // default property values
    bool region_property_values     ( true  );  // regional property values
    bool box_boundary_conditions    ( false );  // boundary conditions for box-shaped model
    bool region_property_conditions ( false );  // essential conditions for regions
    bool boundary_conditions        ( false );  // boundary conditions for arbitrary-shaped model
    bool well_settings              ( true  );  // well names, locations, rates, ratios
    bool computational_settings     ( true  );  // computational settings
    ReadBlocks( model, ifs,
                groups, well_data, settings,
                region_specifications,
                default_property_values,
                region_property_values,
                region_property_conditions,
                box_boundary_conditions,
                boundary_conditions,
                well_settings,
                computational_settings );

    cout <<"\nInputDataManager<"<< dim <<">::ConfigureFRED_ModelFromFile: Configuration completed."<< endl;
    return true;

} // end ConfigureFRED_ModelFromFile






/**

The method is similar to ConfigureFromFile(), version 1, but should be
applied only to box-shaped models which already contain the target
regions.

These are the characteristics of models generated through the
ANSYS_Interface object.

Reading is restricted to blocks 2 to 4.

@section arguments Input Arguments

The method takes a reference to the model which shall be initialized
with the input data and the name of the file from which the data
shall be read. The file name has to be specified without extension.
The model will automatically append '-configuration.txt' to it.

@return The data will be assigned to the input Model object.

@section implementation Implementation

Boundary conditions can only be assigned to scalar and vector variables,
see the documentation of ReadPropertyValue() to learn how CSMP variable
values are specified in the input. 

@attention The internal settings that determine which input file blocks are 
read are as follows:

@code
    bool region_specifications      ( false );  // regionname from parameter range
    bool default_property_values    ( true  );  // default property values
    bool region_property_values     ( true  );  // regional property values
    bool box_boundary_conditions    ( true  );  // boundary conditions for box-shaped model
    bool region_property_conditions ( true  );  // essential conditions for regions
    bool boundary_conditions        ( false );  // boundary conditions for arbitrary-shaped model
    bool well_settings              ( false );  // well names, locations, rates, ratios
    bool computational_settings     ( false );  // computational settings
@endcode

@section application Application

Use this method to configure models for which the meshes were created
with the ANSYS suite of simulation tools.

@section messages Messages

The reading process is verbose. The method keeps the user informed
about the progress and assigned property values are echoed to screen.
 */
template<uint32_t dim>
bool InputDataManager<dim>::Configure_ANSYS_ModelFromFile( Model<dim>& model, const char* fname )
{
    ErrorHandler& csmp_error ( ErrorHandler::Instance() );

    cout <<"\n\nInputDataManager<"<< dim << ">::Configure_ANSYS_ModelFromFile: Configuring model from file..."<< endl;

    ifstream  ifs;
    string    file_header;
    const std::string file_extension ( "-configuration.txt" );

    // 0. Open the file
    openFile( ifs, fname, file_extension );

    // 1. Read the title
    readFileHeader( ifs, file_header, csmp_error.Verbose() );

    // 2. Read data in blocks
    std::set<std::string> groups;
    std::map<std::string,std::vector<double> > well_data;
    ComputationalSettings settings;
    bool region_specifications      ( false );  // regionname from parameter range
    bool default_property_values    ( true  );  // default property values
    bool region_property_values     ( true  );  // regional property values
    bool box_boundary_conditions    ( true  );  // boundary conditions for box-shaped model
    bool region_property_conditions ( true  );  // essential conditions for regions
    bool boundary_conditions        ( false );  // boundary conditions for arbitrary-shaped model
    bool well_settings              ( false );  // well names, locations, rates, ratios
    bool computational_settings     ( false );  // computational settings
    ReadBlocks( model, ifs,
                groups, well_data, settings,
                region_specifications,
                default_property_values,
                region_property_values,
                region_property_conditions,
                box_boundary_conditions,
                boundary_conditions,
                well_settings,
                computational_settings );

    cout <<"\nInputDataManager<"<< dim << ">::Configure_ANSYS_ModelFromFile: Configuration completed."<< endl;
    return true;

} // end Configure_ANSYS_ModelFromFile


/**

The method is similar to ConfigureFromFile(), version 1, but should be
applied only to freeform models which already contain the target
regions.

These are the characteristics of models generated through the
ANSYS_Interface object.

Reading is restricted to blocks 2 to 4.

@section arguments Input Arguments

The method takes a reference to the model which shall be initialized
with the input data and the name of the file from which the data
shall be read. The file name has to be specified without extension.
The model will automatically append '-configuration.txt' to it.

@return The data will be assigned to the input Model object.

@section implementation Implementation

The method is essentially the same as the previous one but for freeform
ANSYS models for which boundary conditions can be assigned only to regions.


Boundary conditions can only be assigned to scalar and vector variables,
see the documentation of ReadPropertyValue() to learn how CSMP variable
values are specified in the input.

@section application Application

Use this method to configure models for which the meshes were created
with the ANSYS suite of simulation tools.

@section messages Messages

The reading process is verbose. The method keeps the user informed
about the progress and assigned property values are echoed to screen.
*/
template<uint32_t dim>
bool InputDataManager<dim>::ConfigureIrregular_ANSYS_ModelFromFile( Model<dim>& model, const char* fname )
{
    ErrorHandler& csmp_error ( ErrorHandler::Instance() );

    cout <<"\n\nInputDataManager<"<< dim <<">::ConfigureIrregular_ANSYS_ModelFromFile: Configuring model from file..."<< endl;

    ifstream  ifs;
    string    file_header;
    const std::string file_extension ( "-configuration.txt" );

    // 0. Open the file
    openFile( ifs, fname, file_extension );

    // 1. Read the title
    readFileHeader( ifs, file_header, csmp_error.Verbose() );

    // 2. Read data in blocks
    std::set<std::string> groups;
    std::map<std::string,std::vector<double> > well_data;
    ComputationalSettings settings;
    bool region_specifications      ( false );  // regionname from parameter range
    bool default_property_values    ( true  );  // default property values
    bool region_property_values     ( true  );  // regional property values
    bool box_boundary_conditions    ( true  );  // boundary conditions for box-shaped model
    bool region_property_conditions ( false );  // essential conditions for regions
    bool boundary_conditions        ( false );  // boundary conditions for arbitrary-shaped model
    bool well_settings              ( false );  // well names, locations, rates, ratios
    bool computational_settings     ( false );  // computational settings
    ReadBlocks( model, ifs,
                groups, well_data, settings,
                region_specifications,
                default_property_values,
                region_property_values,
                region_property_conditions,
                box_boundary_conditions,
                boundary_conditions,
                well_settings,
                computational_settings );

    cout <<"\nInputDataManager<"<< dim <<">::ConfigureIrregular_ANSYS_ModelFromFile: Configuration completed."<< endl;
    return true;

} // end ConfigureIrregular_ANSYS_ModelFromFile





/**

The method reads the data block3 (see description of the class below),
assigning material property values and initial conditions to the
set of regions specified in the file. The names of these are inserted
into a supplied set container class.

@section arguments Input Arguments

The method takes a reference to the model to which the region properties
shall be applied, an empty set that will contain the region names and
the file name to which the extension '-configuration.txt' is appended
automatically before the file is opened.

@return The method returns true if the assigment process was successful.

@section messages Messages

The reading process is verbose, potential errors are reported to screen.
*/
template<uint32_t dim>
bool InputDataManager<dim>::ConfigureRegionsFromFile( Model<dim>& model, const char* fname,
                                                      set<string>& groups )
{
    ErrorHandler& csmp_error ( ErrorHandler::Instance() );

    cout <<"\n\nInputDataManager<"<<  dim <<">::ConfigureRegionsFromFile: Parsing file..."<< endl;

    ifstream  ifs;
    string    file_header;
    const std::string file_extension ( "-configuration.txt" );

    // 0. Open the file
    openFile( ifs, fname, file_extension );

    // 1. Read the title
    readFileHeader( ifs, file_header, csmp_error.Verbose() );

    // 2. Read data in blocks
    groups.erase( groups.begin(), groups.end() );
    std::map<std::string,std::vector<double> > well_data;
    ComputationalSettings settings;
    bool region_specifications      ( true  );  // regionname from parameter range
    bool default_property_values    ( false );  // default property values
    bool region_property_values     ( true  );  // regional property values
    bool box_boundary_conditions    ( true  );  // boundary conditions for box-shaped model
    bool region_property_conditions ( false );  // essential conditions for regions
    bool boundary_conditions        ( false );  // boundary conditions for arbitrary-shaped model
    bool well_settings              ( false );  // well names, locations, rates, ratios
    bool computational_settings     ( false );  // computational settings
    ReadBlocks( model, ifs,
                groups, well_data, settings,
                region_specifications,
                default_property_values,
                region_property_values,
                region_property_conditions,
                box_boundary_conditions,
                boundary_conditions,
                well_settings,
                computational_settings );

    cout <<"\nInputDataManager<"<< dim <<">::ConfigureRegionsFromFile: Configuration completed."<< endl;
    return true;

} // end ConfigureRegionsFromFile




/**

Reads the input data blocks 1-5 (see class documentation) from the
user specified '*-configuaration.txt' input file. The method gives the
user the possibility to generate regions of elements with certain variable
data range and to assign values and essential conditions to them.

@section arguments Input Arguments

The method takes a reference to the model which shall be initialized
with the input data and the name of the file from which the data
shall be read. The file name has to be specified without extension.
The model will automatically append '-configuration.txt' to it.

@return The data will be assigned to the input Model object.

@section implementation Implementation

Boundary conditions can only be assigned to scalar and vector variables,
see the documentation of ReadPropertyValue() to learn how CSP variable
values are specified in the input.

@section application Application

Because the method attempts to assign essential conditions
to model boundaries identified by the enumeration BOX_BOUNDARY, it
should only be for rectangular or box-shaped models which may however
contain boundaries that are flagged as IRREGULAR as well. This is the
case for box-shaped models with a top surface that represents a
topography.

@section messages Messages

The reading process is verbose. The title of the input file and
potential parsing errors are reported.
*/
template<uint32_t dim>
bool InputDataManager<dim>::ConfigureFromFile( Model<dim>& model, const char* fname )
{
    ErrorHandler& csmp_error ( ErrorHandler::Instance() );

    cout <<"\n\nInputDataManager<"<< dim <<">::ConfigureFromFile: Configuring model from file..."<< endl;

    ifstream  ifs;
    string    file_header;
    const std::string file_extension ( "-configuration.txt" );

    // 0. Open the file
    openFile( ifs, fname, file_extension );

    // 1. Read the title
    readFileHeader( ifs, file_header, csmp_error.Verbose() );

    // 2. Read data in blocks
    std::set<std::string> groups;
    std::map<std::string,std::vector<double> > well_data;
    ComputationalSettings settings;
    bool region_specifications      ( true  );  // regionname from parameter range
    bool default_property_values    ( true  );  // default property values
    bool region_property_values     ( true  );  // regional property values
    bool box_boundary_conditions    ( true  );  // boundary conditions for box-shaped model
    bool region_property_conditions ( true  );  // essential conditions for regions
    bool boundary_conditions        ( false );  // boundary conditions for arbitrary-shaped model
    bool well_settings              ( false );  // well names, locations, rates, ratios
    bool computational_settings     ( false );  // computational settings
    ReadBlocks( model, ifs,
                groups, well_data, settings,
                region_specifications,
                default_property_values,
                region_property_values,
                region_property_conditions,
                box_boundary_conditions,
                boundary_conditions,
                well_settings,
                computational_settings );

    cout <<"\nInputDataManager<"<< dim <<">::ConfigureFromFile: Configuration completed."<< endl;
    return true;

} // end ConfigureFromFile




/** Allows for configuration of CSMP models.

@section arguments Input Arguments

The method takes a reference to model which shall be initialized with
the property values from the input file and the name of the file
without the extension '-configuration.txt' which will be appended
to the file name automatically.

The boolean variables block1 to block5 enable the user to costumize the
reading process. Thus, the desired data blocks can be switched on with
their boolean variable values set to true. The role of the different
input blocks is to read and create:

@code
block1 - regionname from parameter range.
block2 - assign default property values.
block3 - assign regional property values (i.e. values to existing regions),
block4 - ONLY for box-shaped models: assign boundary conditions to LEFT, RIGHT etc.
block5 - assign essential conditions via VARIABLE_FLAG flags to regions.
block6 - properties / conditions assigned to CSMP Boundary objects
@endcode

@return The property values and flags are assigned to the model specified by the
first method argument.

@section messages Messages

The method is verbose. Errors and monitors on the reading process are
reported to stdout.

*/
template<uint32_t dim>
bool InputDataManager<dim>::ConfigureFromFile(
        Model<dim>& model,
        const char* fname,
        bool region_specifications,       // regionname from parameter range
        bool default_property_values,     // default property values
        bool region_property_values,      // regional property values
        bool box_boundary_conditions,     // boundary conditions for box-shaped model
        bool region_property_conditions,  // essential conditions for regions
        bool boundary_conditions)         // boundary conditions for arbitrary-shaped model
{
    ErrorHandler& csmp_error ( ErrorHandler::Instance() );

    cout <<"\n\nInputDataManager<"<< dim <<">::ConfigureFromFile: Configuring model from file..."<< endl;

    ifstream  ifs;
    string    file_header;
    const std::string file_extension ( "-configuration.txt" );

    // 0. Open the file
    openFile( ifs, fname, file_extension );

    // 1. Read the title
    readFileHeader( ifs, file_header, csmp_error.Verbose() );

    // 2. Read data in blocks
    std::set<std::string> groups;
    std::map<std::string,std::vector<double> > well_data;
    ComputationalSettings settings;
    bool well_settings          ( false );  // well names, locations, rates, ratios
    bool computational_settings ( false );  // computational settings
    ReadBlocks( model, ifs,
                groups, well_data, settings,
                region_specifications,
                default_property_values,
                region_property_values,
                region_property_conditions,
                box_boundary_conditions,
                boundary_conditions,
                well_settings,
                computational_settings );


    cout <<"\nInputDataManager<"<< dim <<">::ConfigureFromFile: Configuration completed."<< endl;
    return true;

} // end ConfigureFromFile





/** Allows for the costumized configuration of CSMP models including csmp::Boundary

@section arguments Input Arguments

The method takes a reference to model which shall be initialized with
the property values from the input file and the name of the file
without the extension '-configuration.txt' which will be appended
to the file name automatically.

The boolean variables block1 to block5 enable the user to costumize the
reading process. Thus, the desired data blocks can be switched on with
their boolean variable values set to true. The role of the different
input blocks is to read and create:

@code
block1 - regionname from parameter range.
block2 - assign default property values.
block3 - assign regional property values (i.e. values to existing regions),
block4 - assign standard boundary conditions to box-shaped model.
block5 - assign essential conditions via VARIABLE_FLAG flags to regions.
block6 - assign properties incl flag to csmp::Boundary objects
@endcode

@return The property values and flags are assigned to the model specified by the
first method argument.

The methood also initializes a ComputationalSettings object which allows
the user to specify the duration of the run, the time stepping strategy,
and the output times.

@section messages Messages

The method is verbose. Errors and monitors on the reading process are
reported to stdout.

@param [in] model The csmp::Model to set up
@param [in] fname The file name (extension '-configuration.txt' appended automatically)
@param [in] region_specifications block1 Region from parameter range
@param [in] default_property_values block2 Default property values
@param [in] region_property_values  block3 Region property values
@param [in] box_boundary_conditions block4 Boundary conditions for box-shaped model
@param [in] region_property_conditions block5 Essential conditions for Regions
@param [in] boundary_conditions block6 Properties & Essential conditions for Boundary
@param [in] settings Computational settings

*/
template<uint32_t dim>
bool InputDataManager<dim>
::ConfigureFromFile( Model<dim>& model, const char* fname,
                     bool region_specifications,       // regionname from parameter range
                     bool default_property_values,     // default property values
                     bool region_property_values,      // regional property values
                     bool box_boundary_conditions,     // boundary conditions for box-shaped model
                     bool region_property_conditions,  // regional property conditions
                     bool boundary_conditions,         // boundary conditions for arbitrary-shaped model
                     ComputationalSettings& settings )
{
    ErrorHandler& csmp_error ( ErrorHandler::Instance() );

    cout <<"\n\nInputDataManager<"<< dim <<">::ConfigureFromFile: Configuring model from file..."<< endl;

    ifstream  ifs;
    string    file_header;
    const std::string file_extension ( "-configuration.txt" );

    // 0. Open the file
    openFile( ifs, fname, file_extension );

    // 1. Read the title
    readFileHeader( ifs, file_header, csmp_error.Verbose() );

    // 2. Read data in blocks
    std::set<std::string> groups;
    std::map<std::string,std::vector<double> > well_data;
    bool well_settings          ( false );  // well names, locations, rates, ratios
    bool computational_settings ( true );   // computational settings
    ReadBlocks( model, ifs,
                groups, well_data, settings,
                region_specifications,
                default_property_values,
                region_property_values,
                region_property_conditions,
                box_boundary_conditions,
                boundary_conditions,
                well_settings,
                computational_settings );

    cout <<"\nInputDataManager<"<<  dim <<">::ConfigureFromFile: Configuration completed."<< endl;
    return true;

} // end ConfigureFromFile (computational settings)


/** Allows for the costumized configuration of CSMP models including a particualr configuration file
Here we do not use the extension '-configuration.txt' which will be appended to the model name automatically.
*/
template<uint32_t dim>
bool InputDataManager<dim>
::ConfigureFromSpecificFile( Model<dim>& model, const char* configuration_fname,
                     bool region_specifications,       // regionname from parameter range
                     bool default_property_values,     // default property values
                     bool region_property_values,      // regional property values
                     bool box_boundary_conditions,     // boundary conditions for box-shaped model
                     bool region_property_conditions,  // regional property conditions
                     bool boundary_conditions,         // boundary conditions for arbitrary-shaped model
                     ComputationalSettings& settings )
{
  ErrorHandler& csmp_error( ErrorHandler::Instance() );

  cout << "\n\nInputDataManager<" << dim << ">::ConfigureFromFile: Configuring model from file..." << endl;

  ifstream  ifs;
  string    file_header;
  
  // 0. Open the file
  openFile( ifs, configuration_fname );

  // 1. Read the title
  readFileHeader( ifs, file_header, csmp_error.Verbose() );

  // 2. Read data in blocks
  std::set<std::string> groups;
  std::map<std::string, std::vector<double> > well_data;
  bool well_settings( false );  // well names, locations, rates, ratios
  bool computational_settings( true );   // computational settings
  ReadBlocks( model, ifs,
              groups, well_data, settings,
              region_specifications,
              default_property_values,
              region_property_values,
              region_property_conditions,
              box_boundary_conditions,
              boundary_conditions,
              well_settings,
              computational_settings );

  cout << "\nInputDataManager<" << dim << ">::ConfigureFromFile: Configuration completed." << endl;
  return true;

} // end ConfigureFromFile (computational settings)


/**

Generic function which reads blocks of data marked by flags

@author Roman, 2014, cleaned up by SKM 28/3/2016.

*/

template<uint32_t dim>
bool InputDataManager<dim>
::ReadBlocks( Model<dim>& model,
              std::ifstream& ifs,
              std::set<std::string>& groups,
              std::map<std::string,std::vector<double> >& well_data,
              ComputationalSettings& settings,
              bool region_specifications,        ///< groupname from parameter range
              bool default_property_values,      ///< default property values
              bool region_property_values,       ///< regional property values
              bool region_property_conditions,   ///< regional property conditions
              bool box_boundary_conditions,      ///< boundary conditions for box-shaped model
              bool boundary_conditions,          ///< boundary conditions for arbitrary-shaped model
              bool well_settings,                ///< well names, locations, rates, ratios
              bool computational_settings        ///< computational settings
            )
{
    ErrorHandler& csmp_error ( ErrorHandler::Instance() );

    size_t line_length( 256 );
    char   text_line[256];

    // 1. Reading Region specifications
    if ( region_specifications ) {

        ifs.getline( text_line, line_length );
        while ( isBlankLine(text_line) ) {
            ifs.getline( text_line, line_length );
            if ( ifs.eof() )
            {
                ifs.close();
                return true;
            }
        }
        // SKM fix 3/11/24
        // (putting the new regions into unique regions and moving "Model" to non-unique regions if it is nt there already)
        size_t n_unique_regions = groups.size();
        buildRegionsBasedOnPropertyRange<dim>( model, groups,
                                               ifs, text_line, line_length, csmp_error.Verbose() );
        // if new regions were created
        if ( groups.size() > n_unique_regions )
          if ( model.IsUnique("Model") )
            model.MoveToNonUniqueRegions("Model");
    }

    // 2. Global model properties
    if ( default_property_values ) {

        ifs.getline( text_line, line_length );
        while ( isBlankLine(text_line) ) {
            ifs.getline( text_line, line_length );
            if ( ifs.eof() )
            {
                ifs.close();
                return true;
            }
        }

        readDefaultPropertyValues<dim>( model,
                                        ifs, text_line, line_length, csmp_error.Verbose() );
    }


    // 3. Properties assigned to regions
    if ( region_property_values ) {

        ifs.getline( text_line, line_length );
        while ( isBlankLine(text_line) ) {
            ifs.getline( text_line, line_length );
            if ( ifs.eof() )
            {
                ifs.close();
                return true;
            }
        }

        readRegionPropertyValues<dim>( model,
                                       ifs, text_line, line_length, csmp_error.Verbose() );
    }


    // 4. Essential conditions for box-shaped model
    if ( box_boundary_conditions ) {

        ifs.getline( text_line, line_length );
        while ( isBlankLine(text_line) ) {
            ifs.getline( text_line, line_length );
            if ( ifs.eof() )
            {
                ifs.close();
                return true;
            }
        }

        readBoxBoundaryPropertyValuesAndConditions<dim>( model,
                                                         ifs, text_line, line_length, csmp_error.Verbose() );
    }


    // 5. Conditional flags assigned to regions
    if ( region_property_conditions ) {

        ifs.getline( text_line, line_length );
        while ( isBlankLine(text_line) ) {
            ifs.getline( text_line, line_length );
            if ( ifs.eof() )
            {
                ifs.close();
                return true;
            }
        }

        readRegionPropertyConditions<dim>( model,
                                           ifs, text_line, line_length, csmp_error.Verbose() );
    }

    // 6. Boundary settings
    if ( boundary_conditions ) {

        ifs.getline( text_line, line_length );
        while ( isBlankLine(text_line) ) {
            ifs.getline( text_line, line_length );
            if ( ifs.eof() )
            {
                ifs.close();
                return true;
            }
        }

        readBoundaryPropertyValuesAndConditions<dim>( model,
                                                      ifs, text_line, line_length, csmp_error.Verbose() );
    }

    // 7. Well names, locations, rates, and ratios
    if ( well_settings ) {

        ifs.getline( text_line, line_length );
        while ( isBlankLine(text_line) ) {
            ifs.getline( text_line, line_length );
            if ( ifs.eof() )
            {
                ifs.close();
                return true;
            }
        }

        readPointData<dim>( well_data, 2,
                            ifs, text_line, line_length, csmp_error.Verbose() );
    }

    // 8. Computational settings
    if ( computational_settings ) {

        ifs.getline( text_line, line_length );
        while ( isBlankLine(text_line) ) {
            ifs.getline( text_line, line_length );
            if ( ifs.eof() )
            {
                ifs.close();
                return true;
            }
        }

        readComputationalSettings<dim>( settings,
                                        ifs, text_line, line_length, csmp_error.Verbose() );
    }

    ifs.close();

    return true;
}




template class InputDataManager<1U>;
template class InputDataManager<2U>;
template class InputDataManager<3U>;


} // end namespace csmp

