#ifndef ANSYS_ELEMENT_SPECIFICATIONS_H
#define ANSYS_ELEMENT_SPECIFICATIONS_H

#include "CSMP_definitions.h"
#include "FiniteElement.h"
#include "Box.h"
#include "CSMP_global_enumerations.h"

namespace csmp {

/// types generated by ANSYS Tetra mesher
enum ANSYS_FEM_TYPE { TRI_3    =8, 
                     TRI_3_X   =9, 
                     TRI_6    =10, 
                     TRI_6_X  =11,
                     TETRA_4   =4, 
                     TETRA_10  =5,
                     PYRA_5   =18, 
                     PYRA_13  =24, 
                     PYRA_14  =22, 
                     PENTA_6  =12, 
                     PENTA_15 =13, 
                     PENTA_18 =21,
                     QUAD_4   =14, 
                     QUAD_4_X =15, 
                     QUAD_8   =16, 
                     QUAD_8_X =17, 
                     QUAD_9   =19,
                     HEXA_8    =6, 
                     HEXA_20   =7, 
                     HEXA_27   =5,
                     BAR_2     =2, 
                     BAR_3     =3, 
                     POLYGON  =23 };

/**
 
@brief Represents ANSYS element type specifications that are needed 
prior to model construction in order to identify corresponding
element types in CSMP++.

@author S.K. Matthai
@date 2003

 
@section motivation Motivation
 
Relates the ANSYS finite element types to the generic finite element 
names that are used inside of CSP. Also additional diagnostics are 
obtained as to whether the element is a line, surface, or volume, and
whether the element uses linear, quadratic or cubic basis functions.
Furthermore the element can be queried for the number of neighbors 
and its minimum spatial dimension.
 

@section implementation Implementation

ANSYS definitions of element types and their identification
numbers are the following. They are only partially mapped to
CSP and incorporated into enumerations to avoid the pollution of 
the csp namespace.  

@code
#ifndef MAX_NODES_ELEMENT
#define MIXED		0
#define NODE		1
#define BAR_2		2
#define BAR_3		3
#define TETRA_4		4
#define TETRA_10	5
#define HEXA_8		6
#define HEXA_20		7
#define TRI_3		8
#define TRI_3_X		9
#define TRI_6		10
#define TRI_6_X		11
#define PENTA_6		12 // prism elements 
#define PENTA_15	13
#define PENTA_18	21 // quadratic prisms with face nodes on sides
#define QUAD_4		14
#define QUAD_4_X	15
#define QUAD_8		16
#define QUAD_8_X	17
#define PYRA_5		18

#define QUAD_9		19
#define HEXA_27		20
#define PYRA_14		22

#define PYRA_13		24

#define POLYGON		23

#define N_ELEMENT_TYPES	25

#define MAX_NODES_ELEMENT	27
#define MAX_EDGES_ELEMENT   12
#define MAX_FACES_ELEMENT    6
#define MAX_FACE_SIDES		10

Element masks are defined in terms of member functions which
recognize line-, surface-, and volumetric elements:

#define EDGE_ELEMENT_MASK      ((1 << BAR_2) | (1 << BAR_3))
#define SURFACE_ELEMENT_MASK   ((1 << TRI_3) | (1 << TRI_6) | \
				(1 << QUAD_4) | (1 << QUAD_8))
#define VOLUME_ELEMENT_MASK    ((1 << TETRA_4) | (1 << TETRA_10) | \
				(1 << HEXA_8) | (1 << HEXA_20) | \
				(1 << PENTA_6) | (1 << PENTA_15) | \
				(1 << PYRA_5) | (1 << HEXA_27) | \
				(1 << PENTA_18) | (1 << PYRA_14) | \
				(1 << PYRA_13))

			
#define LINEAR_ELEMENT_MASK    ((1 << NODE) | (1 << BAR_2) | \
				(1 << TETRA_4) | (1 << HEXA_8) | \
				(1 << TRI_3) | (1 << PENTA_6) | \
				(1 << QUAD_4) | (1 << PYRA_5))

#define QUADRATIC_ELEMENT_MASK ((1 << BAR_3) | (1 << TETRA_10) | \
				(1 << HEXA_20) | (1 << TRI_6) | \
				(1 << PENTA_15) | (1 << QUAD_8) | \
				(1 << QUAD_9) | (1 << HEXA_27) |  \
				(1 << PENTA_18) | (1 << PYRA_14) | \
				(1 << PYRA_13))
@endcode

TODO: make all the member functions static so this becomes a trait like numeric_limits<>()
 
*/
class ANSYS_ElementSpecifications {
  public:
    ANSYS_ElementSpecifications() = delete;
    ~ANSYS_ElementSpecifications() = delete;

    static CSMP_FEM_TYPE  CSMP_TypeFrom_ANSYS_Type( int32 ANSYS_finite_element_type, bool isoparametric, uint32 dim );
    static CSMP_FEM_TYPE  CSMP_TypeFrom_ANSYS_TypeName( const std::string& ANSYS_finite_element_type, bool isoparametric, uint32 dim );
    static std::string    CSMP_TypeNameFrom_ANSYS_Type( int32 ANSYS_finite_element_type, bool isoparametric, uint32 dim );
    static std::string    CSMP_TypeNameFrom_ANSYS_TypeName( const std::string& ANSYS_finite_element_type, bool isoparametric, uint32 dim );

    static int32         ANSYS_Type( const std::string& FEtype );
    static size_t        NodesPerElementOfType( int32 ANSYS_finite_element_type );
    static size_t        FacesPerElementOfType( int32 ANSYS_finite_element_type );
    static size_t        NeighborsPerElementOfType( int32 ANSYS_finite_element_type );
    static size_t        NodesPerFaceForElementOfType( int32 ANSYS_finite_element_type, size_t face );
    static size_t        FaceNodeForElementOfType( int32 ANSYS_finite_element_type, size_t face, size_t face_node );

    static bool          LineElement( int32 ANSYS_finite_element_type );
    static bool          SurfaceElement( int32 ANSYS_finite_element_type );
    static bool          VolumeElement( int32 ANSYS_finite_element_type );

    static size_t        MinimumSpatialDimension( const std::string& ANSYS_finite_element_type );
    static bool          LineElement( const std::string& ANSYS_finite_element_type );
    static bool          SurfaceElement( const std::string& ANSYS_finite_element_type );
    static bool          VolumeElement( const std::string& ANSYS_finite_element_type );

    static void          LineElements( std::list<std::string>& line_elements );
    static void          SurfaceElements( std::list<std::string>& surf_elements );
    static void          VolumeElements( std::list<std::string>& vol_elements );

    static size_t        InterpolationOrder( const std::string& etype );
    static size_t        InterpolationOrder( int32 etype );
    static bool          LinearElement( int32 etype );
    static bool          QuadraticElement( int32 etype );
    static bool          CubicElement( int32 etype );
};

std::string    parse_ANSYS_BoundaryFlag( int i );

} // csmp


#endif
