if (CMAKE_HOST_APPLE)
    # OS X is a Unix, but it's not a normal Unix as far as search paths go.
    message(STATUS "This is an Apple platform")
    set(PLATFORM_FLAGS "-DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES -DSAMG_UNIX_LINUX -DSAMG_LCASE_USCORE")
    set(PLATFORM_LDFLAGS)
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/build/macosx/)
    set(PLATFORM_INCLUDES)
    set(PLATFORM_SPECIAL_DEPENDENCIES amg_mult ifcoremt ifportmt imf intlc iomp5 irc svml)
elseif (CMAKE_HOST_UNIX)
    message(STATUS "This is a Unix-like platform")
    set(PLATFORM_FLAGS "-DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES -DSAMG_UNIX_LINUX -DSAMG_LCASE_USCORE")
    set(PLATFORM_LDFLAGS "-L/lib64 -L/usr/lib/x86_64-linux-gnu/ -lpthread")
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/build/linux/)
    set(PLATFORM_SPECIAL_DEPENDENCIES amg_mult iomp5)
elseif (CMAKE_HOST_WIN32)
    set(PLATFORM_FLAGS "-DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES")
    message(STATUS "This is a Windows platform")
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/build/windows/)
    set(PLATFORM_LDFLAGS)
    set(PLATFORM_LIBS)
    set(PLATFORM_SPECIAL_DEPENDENCIES amg_mult_dyn iomp5md gems3k)
else ()
    message(WARNING "The build system has not yet been tested on this platform")
    set(PLATFORM_FLAGS "/EHsc")
    set(PLATFORM_LDFLAGS)
    set(GOSS_SEARCH_PATHS)
    set(PLATFORM_LIBS)
endif ()

if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    message(STATUS "The compiler is Clang")
    set(COMPILER_VENDOR "-DGOSS_COMPILER_CLANG")
    set(PLATFORM_CXX_FLAGS
	    "-std=c++11 -stdlib=libc++ -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-float-equal"
	)
    set(COMPILER_LDFLAGS "-stdlib=libc++")
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    message(STATUS "The compiler is GNU")
    set(COMPILER_VENDOR "-DGOSS_COMPILER_GNU")
    set(PLATFORM_CXX_FLAGS "-Winline -Wall -fomit-frame-pointer -ffast-math -std=c++11 ${PLATFORM_GLIBCXX_ABI_FLAG}")
    set(COMPILER_LDFLAGS)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
    message(STATUS "The compiler is Intel")
    set(COMPILER_VENDOR "-DGOSS_COMPILER_INTEL")
    message(WARNING "This build has not yet been tested with ICC")
    set(PLATFORM_CXX_FLAGS)
    set(COMPILER_LDFLAGS)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    message(STATUS "The compiler is Microsoft")
    set(COMPILER_VENDOR "-DGOSS_COMPILER_MSVC")
    message(WARNING "This build has not yet been tested with MSVC")
    set(PLATFORM_CXX_FLAGS)
    set(COMPILER_LDFLAGS)
else()
    message(WARNING "The build system has not yet been ported to this compiler")
endif()

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${PLATFORM_FLAGS} ${COMPILER_VENDOR} ${PLATFORM_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${PLATFORM_LDFLAGS} ${COMPILER_LDFLAGS}")

