if (CMAKE_HOST_APPLE)
    # OS X is a Unix, but it's not a normal Unix as far as search paths go.
    message(STATUS "This is an Apple platform")
    set(PLATFORM_FLAGS "-DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES -DSAMG_UNIX_LINUX -DSAMG_LCASE_USCORE -DPYRAMID_TRIANGULAR_FACETS")
    set(PLATFORM_LDFLAGS)
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/build/macosx ${CMAKE_SOURCE_DIR}/bin/macosx)
    set(PLATFORM_INCLUDES)
    set(PLATFORM_SPECIAL_DEPENDENCIES amg_mult ifcoremt ifportmt imf intlc iomp5 irc svml)
elseif (CMAKE_HOST_UNIX)
    message(STATUS "This is a Unix-like platform")
    set(PLATFORM_FLAGS "-DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES -DSAMG_UNIX_LINUX -DSAMG_LCASE_USCORE -DPYRAMID_TRIANGULAR_FACETS")
    link_directories("/lib64" "/usr/lib/x64_64-linux-gnu")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lm -lpthread")
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/build/linux ${CMAKE_SOURCE_DIR}/bin/linux)
    set(PLATFORM_SPECIAL_DEPENDENCIES amg_mult iomp5)
elseif (CMAKE_HOST_WIN32)
    set(PLATFORM_FLAGS "-DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES -DPYRAMID_TRIANGULAR_FACETS")
    message(STATUS "This is a Windows platform")
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/build/windows ${CMAKE_SOURCE_DIR}/bin/windows)
    set(PLATFORM_LDFLAGS)
    set(PLATFORM_LIBS)
    set(PLATFORM_SPECIAL_DEPENDENCIES libamg_mult_dyn libiomp5md gems3k meshach)
else ()
    message(WARNING "The build system has not yet been tested on this platform")
    set(PLATFORM_FLAGS)
    set(PLATFORM_LDFLAGS)
    set(GOSS_SEARCH_PATHS)
    set(PLATFORM_LIBS)
endif ()

if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    message(STATUS "The compiler is Clang")
    if (CMAKE_HOST_APPLE)
	# MacBooks are a little behind other platforms
	set(PLATFORM_ARCH "-march=core2")
    else()
	set(PLATFORM_ARCH "-march=corei7-avx")
    endif()
    if (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(PLATFORM_CXX_FLAGS
	    "-std=c++14 -stdlib=libc++ -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-float-equal ${PLATFORM_ARCH} -O3"
	)
    else()
        set(PLATFORM_CXX_FLAGS
	    "-std=c++14 -stdlib=libc++ -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-float-equal ${PLATFORM_ARCH} -O0"
	)
    endif()
    set(COMPILER_LDFLAGS)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    message(STATUS "The compiler is GNU")
    if (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(PLATFORM_CXX_FLAGS "-Winline -Wall -fomit-frame-pointer -march=sandybridge -std=c++14 ${PLATFORM_GLIBCXX_ABI_FLAG}")
    else()
        set(PLATFORM_CXX_FLAGS "-Winline -Wall -march=sandybridge -std=c++14 ${PLATFORM_GLIBCXX_ABI_FLAG}")
    endif()
    set(COMPILER_LDFLAGS)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
    message(STATUS "The compiler is Intel")
    if (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(PLATFORM_CXX_FLAGS "-fomit-frame-pointer -march=corei7-avx -std=c++14 ${PLATFORM_GLIBCXX_ABI_FLAG}")
    else()
        set(PLATFORM_CXX_FLAGS "-march=corei7-avx -std=c++14 ${PLATFORM_GLIBCXX_ABI_FLAG}")
    endif()
    set(COMPILER_LDFLAGS)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    message(STATUS "The compiler is Microsoft")
    if (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(PLATFORM_CXX_FLAGS "/EHsc /O2 /Oi /Ot")
    else()
        set(PLATFORM_CXX_FLAGS "/EHsc /O0")
    endif()
    set(COMPILER_LDFLAGS)
else()
    message(WARNING "The build system has not yet been ported to this compiler")
endif()

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${PLATFORM_FLAGS} ${COMPILER_VENDOR} ${PLATFORM_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${PLATFORM_LDFLAGS} ${COMPILER_LDFLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS}")
set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS}")

set(CMAKE_DEBUG_POSTFIX "_debug")
