set(PLATFORM_EXTERNAL_LIBRARIES)

if (CMAKE_HOST_APPLE)
    # OS X is a Unix, but it's not a normal Unix as far as search paths go.
    message(STATUS "This is an Apple platform")
    #set(PLATFORM_FLAGS "-DCSMP_WITH_MESCHACH -DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES -DSAMG_UNIX_LINUX -DSAMG_LCASE_USCORE -DPYRAMID_TRIANGULAR_FACETS")
    #E.P Changed for Mac M1 where SAMG doesnt compile
    set(PLATFORM_FLAGS "-DPYRAMID_TRIANGULAR_FACETS")
    set(PLATFORM_LDFLAGS)
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/thirdparty/samg/macosx ${CMAKE_SOURCE_DIR}/build/macosx ${CMAKE_SOURCE_DIR}/bin/macosx)
    set(PLATFORM_INCLUDES)
    list(APPEND PLATFORM_EXTERNAL_LIBRARIES amg_mult ifcoremt ifportmt imf intlc iomp5 irc svml)
elseif (CMAKE_HOST_UNIX)
    message(STATUS "This is a Unix-like platform")
    set(PLATFORM_FLAGS "-DCSMP_WITH_MESCHACH -DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES -DSAMG_UNIX_LINUX -DSAMG_LCASE_USCORE -DPYRAMID_TRIANGULAR_FACETS")
    link_directories("/lib64" "/usr/lib/x64_64-linux-gnu")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lm -lpthread")
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/thirdparty/samg/linux ${CMAKE_SOURCE_DIR}/build/linux ${CMAKE_SOURCE_DIR}/bin/linux)
    list(APPEND PLATFORM_EXTERNAL_LIBRARIES amg_mult iomp5)
elseif (CMAKE_HOST_WIN32)
    set(PLATFORM_FLAGS "-DCSMP_WITH_MESCHACH -DCSMP_WITH_SAMG_SOLVER -DSAMG_MULTIPLE_INSTANCES -DPYRAMID_TRIANGULAR_FACETS -D_CRT_SECURE_NO_WARNINGS")
    message(STATUS "This is a Windows platform")
    set(PLATFORM_LIBS ${CMAKE_SOURCE_DIR}/thirdparty/samg/windows ${CMAKE_SOURCE_DIR}/build/windows ${CMAKE_SOURCE_DIR}/bin/windows)
    set(PLATFORM_LDFLAGS)
    set(PLATFORM_INCLUDES)
    list(APPEND PLATFORM_EXTERNAL_LIBRARIES libamg_mult_dyn amg_mult_dyn gems3k meschach)
else ()
    message(WARNING "The build system has not yet been tested on this platform")
    set(PLATFORM_FLAGS)
    set(PLATFORM_LDFLAGS)
    set(PLATFORM_LIBS)
endif ()

if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    message(STATUS "The compiler is Clang")
    set(COMMON_CXX_FLAGS "-fno-common -fshort-enums -funroll-loops -fvisibility-inlines-hidden -std=c++17 -stdlib=libc++ -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-float-equal")
     if (CMAKE_HOST_APPLE)
	# MacBooks are a little behind other platforms
        #E.P Changed
        #set(PLATFORM_ARCH "-march=core2")
    else()
	set(PLATFORM_ARCH "-march=corei7 -msse4.2")
    endif()
    if (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(PLATFORM_CXX_FLAGS
	    "${COMMON_CXX_FLAGS} ${PLATFORM_ARCH} -O3 -DNDEBUG"
	)
    elseif (CMAKE_BUILD_TYPE STREQUAL "Profile")
        set(PLATFORM_CXX_FLAGS
	    "${COMMON_CXX_FLAGS} ${PLATFORM_ARCH} -O3 -DNDEBUG"
	)
    else()
        set(PLATFORM_CXX_FLAGS
	    "${COMMON_CXX_FLAGS} ${PLATFORM_ARCH} -O0 -DDEBUG"
	)
    endif()
    set(COMPILER_LDFLAGS)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    message(STATUS "The compiler is GNU")
    if (CMAKE_BUILD_TYPE STREQUAL "Release")
        #set(PLATFORM_CXX_FLAGS "-fshort-enums -Winline -Wall -fomit-frame-pointer -march=nehalem -std=c++17 -lstdc++fs ${PLATFORM_GLIBCXX_ABI_FLAG} -DNDEBUG")
        set(PLATFORM_CXX_FLAGS "-fshort-enums -Winline -Wall -fomit-frame-pointer -march=nehalem -std=c++17 ${PLATFORM_GLIBCXX_ABI_FLAG} -DNDEBUG")
    elseif (CMAKE_BUILD_TYPE STREQUAL "Profile")
        #set(PLATFORM_CXX_FLAGS "-fshort-enums -Winline -Wall -fomit-frame-pointer -march=nehalem -std=c++17 -lstdc++fs ${PLATFORM_GLIBCXX_ABI_FLAG} -DNDEBUG -pg")
        set(PLATFORM_CXX_FLAGS "-fshort-enums -Winline -Wall -fomit-frame-pointer -march=nehalem -std=c++17 ${PLATFORM_GLIBCXX_ABI_FLAG} -DNDEBUG -pg")
    else()
	set(PLATFORM_CXX_FLAGS "-fshort-enums -Winline -Wall -march=nehalem -std=c++17 -fpic -fdiagnostics-color=always ${PLATFORM_GLIBCXX_ABI_FLAG} -DDEBUG")
    endif()
    set(COMPILER_LDFLAGS)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
    message(STATUS "The compiler is Intel")
    if (CMAKE_BUILD_TYPE STREQUAL "Release")
	set(PLATFORM_CXX_FLAGS "-fshort-enums -fomit-frame-pointer -xSSE4.2 -std=c++14 -O3 -ipo-separate ${PLATFORM_GLIBCXX_ABI_FLAG} -DNDEBUG")
        set(COMPILER_LDFLAGS)
    else()
	set(PLATFORM_CXX_FLAGS "-fshort-enums -xSSE4.2 -std=c++17 -O0 ${PLATFORM_GLIBCXX_ABI_FLAG} -DNDEBUG")
        set(COMPILER_LDFLAGS)
    endif()
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    message(STATUS "The compiler is Microsoft")
    if (CMAKE_BUILD_TYPE STREQUAL "Release")
	set(PLATFORM_CXX_FLAGS "/bigobj /EHsc /O2 /Ob2 /Oi /Ot /GL /GS- /Gy /arch:AVX2 /fp:strict /fp:except /DNDEBUG")
    else()
	set(PLATFORM_CXX_FLAGS "/bigobj /EHsc /O0 /DDEBUG")
    endif()
    set(COMPILER_LDFLAGS)
else()
    message(WARNING "The build system has not yet been ported to this compiler")
endif()

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${PLATFORM_FLAGS} ${COMPILER_VENDOR} ${PLATFORM_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${PLATFORM_LDFLAGS} ${COMPILER_LDFLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS}")
set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS}")

set(CMAKE_DEBUG_POSTFIX "_debug")
