//
//  SKUA_FiniteElementMeshInterface_Test.cpp
//  CSMP_GitHub_UnitTests
//
//  Created by Stephan Matthai on 2/12/20.
//  Copyright © 2020 Stephan Matthai. All rights reserved.
//

#include "SKUA_FiniteElementMeshInterface_Test.h"
#include "SplitBoundaryInterFace.h"
#include "SplitBoundary.h"
#include "VSet.h"
#include "ModelTopology.h"
#include "MeshManagementUtilities.h"
#include "CSMP_highLevelUtilities.h"
#include "SKUA_Model.h"
#include "Region.h"
#include "Element.h"
#include "VTK_Interface.h"

using namespace std;

namespace csmp {

void SKUA_FiniteElementMeshInterface_Test::run()
 {
    //const string model_name{"skua_cross_bedded_xsmall"};
    const string model_name{"SKUA_box_shaped_with_split_boundary"};

    // Read VSet binary file generated by SKUA
    VSet<3U> vset;
    double   time = 0.;
    vset.InputFrom( model_name.c_str(), time );

    // Read ModelTopology file generated by SKUA
    ModelTopology model_topology(true);
    model_topology.InputFromTextFile( model_name.c_str() );
    
    // Build Model using variables file generated by SKUA
    const string variables_file = model_name + "-variables.txt";
    Model<3U>  model( model_topology, vset, variables_file.c_str(), false );

    // Checks...
    printModelDimensions( model, true );
    model.BoundariesOut();
    model.SplitBoundariesOut();
    
    // Basic testing
    Test_NodeManifolds( model );
    Test_InterfaceNodes( model );
    
    // painting the node manifolds
    VTK_Interface<3U>  vtk_output;
    const csmp::Index  var_key = model.Database().StorageKey("node variable");
    csmp::Region<3U>&  model_domain = model.Region("Model");
    for ( auto nit=model_domain.NodesBegin(); nit!=model_domain.NodesEnd(); ++nit ) {
          if ( (*nit)->IsManifold() )
            // there should be as many branches as materials come together
            (*nit)->Store( var_key, makeScalar(PLAIN,(*nit)->Manifold()->Branches()));
          else
            (*nit)->Store( var_key, makeScalar(PLAIN,0.));
      }
     _test( printRangeOfVariable( model, "node variable" ) > 1U );

      vtk_output.OutputDataToVTK( model, "node-manifolds", "node variable", 0 );


    // checking model boundary flagging
    boxFlagsToVariable( model, "node variable", "element variable" );
    
//    vtk_output.OutputDataToVTK( model, "porosity", "porosity", 1 );
    vtk_output.OutputDataToVTK( model, "node-flag", "node variable", 1 );
    vtk_output.OutputDataToVTK( model, "element-flag", "element variable", 1 );
    vtk_output.OutputDataToVTK( model, "porosity", "porosity", 1 );

    // creating 'permeability' variable if it does not already exist
    if ( !model.Database().IsDefined("permeability") ) {
         model.CreateProperty( "permeability", "m2", SCALAR, ELEMENT );
      }
    OutputRegionsToVTK( model, "permeability" );
    
    // 1. basic testing
    /// consecutive numbering of nodes and elements
    /// mesh consistency (Jacobians, element volume range, non-manifold vertices, triangle boxes
    /// pfverts, disambiguated neighbors of lower-dimensional elements
    /// consistent facing directions of surface elements
    /// consecutive numbering of series of line elements
    /// material IDs
    /// test assignment of box boundary flags (sides, edges, corners)
    /// property assignment
    /// use of regions file (is this still needed?)
    // 2. advanced testing
    /// generation of boundaries  
    /// generation of split boundaries                      

 } // end run




  /// Manifolds: 1) are they present at all split boundaries, 2) do they have the right number of entries
void SKUA_FiniteElementMeshInterface_Test::Test_NodeManifolds( const Model<3U>& model )
 {
    // 1. are all the nodes on the SplitBoundaries manifolds
    bool all_nodes_are_manifolds{true};
    for ( auto split=model.SplitBoundariesBegin(); split!=model.SplitBoundariesEnd(); split++ )
      for ( auto nit=(*split).second.NodesBegin(); nit!=(*split).second.NodesEnd(); nit++ )
        if ( (*nit)->IsManifold() == false ) {
             all_nodes_are_manifolds = false;
             break;
          }
    _test( all_nodes_are_manifolds == true );
 
    // 2. consistency check
    size_t n_splitboundary_manifolds{0U};
    for ( auto split=model.SplitBoundariesBegin(); split!=model.SplitBoundariesEnd(); split++ )
      n_splitboundary_manifolds += (*split).second.Nodes(); // all should be manifolds in this model
      
    size_t n_model_manifolds{0U};
    for ( auto nit=model.Mesh().NodesBegin(); nit!=model.Mesh().NodesEnd(); nit++ )
      if ( nit->IsManifold() )
        n_model_manifolds++;
        
    _test( n_model_manifolds == n_splitboundary_manifolds );
    
 } // end Test_NodeManifolds
 
 
 
  
  /// Interface nodes: 1) are they collocated, 2) do they have the right mapping
void SKUA_FiniteElementMeshInterface_Test::Test_InterfaceNodes( const Model<3U>& model )
 {
    double tolerance{1.0e-3};
    
    for ( auto it=model.Mesh().InterFacesBegin(); it!=model.Mesh().InterFacesEnd(); it++ )
      {
          const auto n_nodes{ (*it).FE()->Nodes() };
          for ( auto i{0U}; i<n_nodes; i++ ) {
              // are the nodes co-located?
              _test( (*it).N(i,INSIDE)->Coordinate().DistanceTo((*it).N(n_nodes-i-1U,OUTSIDE)->Coordinate()) <= tolerance );
            }
      }
      
 } // end Test_InterfaceNodes





/* TESTS WITH THOMAS JEROME's INTERFAXE

    // 0. creating box-shaped test model with nodes on the side surfaces
    SKUA_Model  model( "V6_SOLID2_withwells_BINARY",   // V6_SOLID2_with_wells, "V6_SOLID2", ,"V1_SOLID2_ASCII", "V6_SOLID2_withwells_ASCII", "EW01_100ftBAND_10ft"
                       "CSMP-variables.txt",
                       true,   ///< true = binary, false = ascii
                       true );  ///< isoparametric is the only option if model does not only consist of simplex elements

    printModelDimensions( model, true );
    model.RegionsOut();

    // Testing
    _test( model.Mesh().Elements() == 21116/4 );
    _test( model.Mesh().Nodes() == 1262 );

//    _test( TestNeighborConnectivity( model ) );
    const Region<3U>&  unit_A(model.Region("UNIT_A"));
    _test( unit_A.Cells() == 1775 );

    const Region<3U>&  unit_B(model.Region("UNIT_B"));
    _test( unit_B.Elements() == 1743 );

    const Region<3U>&  unit_C(model.Region("UNIT_C"));
    _test( unit_C.Elements() == 1761 );
    
    // are the property values assigned in the correct sequence?
    _test( TestNodePropertyAssignment( model ) );
*/




// TODO: such a method must already exist somewhere else
void SKUA_FiniteElementMeshInterface_Test::OutputRegionsToVTK( const Model<3U>& model, const char* var_name ) const
 {
     std::cout <<"\n\nSKUA_FiniteElementMeshInterface_Test::OutputRegionsToVTK:\n";
     std::cout <<"\n\tUnique regions of model:\n";
     for ( auto rit=model.UniqueRegionsBegin(); rit!=model.UniqueRegionsEnd(); ++rit ) {
          std::cout <<"\t\t"<< (*rit).first;
          std::cout <<" "<< (*rit).second.Cells() <<" elements,";
          std::pair<int32_t, int32_t> rdim = (*rit).second.ElementSpatialDimensions();
          if ( rdim.second == 3 )
            std::cout <<" volume (m3): "<< (*rit).second.Volume() <<", surface area (m2): "<< (*rit).second.SurfaceArea();
          else if ( rdim.second == 2 )
            std::cout <<" surface area (m2): "<< (*rit).second.Volume() <<", perimeter length (m): "<< (*rit).second.SurfaceArea();
          std::cout <<", range of spatial dimensions: "<< rdim.first <<", highest spatial dimension "<< rdim.second << std::endl;
       }

     // writing all regions with model name - region name and variable name
     VTK_Interface<3U>().OutputRegionByRegionToVTK( model, "SKUA_CSMP_test_", var_name, 0 );

 } // end OutputRegionsToVTK



/**
   Checks whethe the assignment of element neighbors from SKUA is identical with that done by CSMP; the side boundary flags are not considered.
   
      TODO: also check neighbor connectivity of Face and InterFace objects
*/
bool SKUA_FiniteElementMeshInterface_Test::TestNeighborConnectivity( Model<3U>& model, bool verbose )
 {
    const csmp::Index eidx = model.Database().StorageKey("element number");
    const csmp::Index nidx = model.Database().StorageKey("node number");
    Region<3U>& domain(model.Region("Model"));
    // recording connectivity from SKUA in an element neighbor vector
    vector<vector<Element<3U>*> > pfverts;
    pfverts.reserve( domain.Cells() );
    for ( auto it=domain.CellsBegin(); it!=domain.CellsEnd(); ++it ) {
         vector<Element<3U>*> nbors( (*it)->Neighbors(), nullptr );
         for ( auto i{0}; i<(*it)->Neighbors(); ++i )
           if ( (*it)->Neighbor(i) != nullptr )
             nbors[i] = (*it)->Neighbor(i);
         pfverts.emplace_back( nbors );    
      }
      
   if ( verbose ) PrintOriginalNeighborIDs( model );
      
    // recreating the connectivity in CSMP
    model.Mesh().UpdateConnectivity();
    if ( verbose ) PrintOriginalNeighborIDs( model );
    
    // comparing SKUA with CSMP connectivity
    size_t failed_comparisons(0U);
    vector<vector<Element<3U>*> >::const_iterator pfit(pfverts.begin());
    for ( auto it=domain.CellsBegin(); it!=domain.CellsEnd(); ++it, ++pfit ) {
         for ( auto i{0}; i<(*it)->Neighbors(); ++i )
           if ( (*it)->Neighbor(i) != (*pfit)[i] ) {
                if ( verbose ) {
                     //(*it)->Out();
                     cerr <<"\nelement neighbor "<< (*it)->Read(eidx) <<":"<< i <<": ";
                     cerr << (*it)->Neighbor(i)->Idx() <<" vs. "<< (*pfit)[i]->Read(eidx) <<" ";
                  }
                failed_comparisons++;
             }
      }
    if ( verbose && failed_comparisons > 0 ) cerr << endl;
      
    if ( failed_comparisons > 0U ) return false;  
    return true;
    
 } // end TestNeighborConnectivity
 
 
 
bool SKUA_FiniteElementMeshInterface_Test::TestNodePropertyAssignment( const Model<3>& model )
 {
    // if the element number is known so that the material IDs can be assigned correctly
    if ( model.Database().IsDefined("node number") ) {
         const csmp::Index nn_key = model.Database().StorageKey("node number");
         const csmp::Index nu_key = model.Database().StorageKey("number");
         // creating a mapping between current elements in region 'Model' and the VSet from the element number
         const Region<3U>& domain = model.Region("Model");
         vector<const Node<3U>*> ordered_nodes(domain.Nodes());

         for ( auto nit=domain.NodesBegin(); nit!=domain.NodesEnd(); ++nit ) {
              if ( fabs((*nit)->Read(nn_key) - (*nit)->Read(nu_key)) > numeric_limits<double>::epsilon() ) { 
                   cerr <<"\n\tnode number vs. number: "<< (*nit)->Read(nn_key) <<" vs. "<< (*nit)->Read(nu_key);
                   _equal( (*nit)->Read(nn_key), (*nit)->Read(nu_key), numeric_limits<double>::epsilon() );
                }
              ordered_nodes[ static_cast<uint32_t>((*nit)->Read(nn_key)) ] = (*nit);
           }
           
         bool problem_found(false);  
         for ( auto i{0}; i<ordered_nodes.size(); ++i ) {
              if ( ordered_nodes[i] == nullptr ) {
                  cerr <<"\nordered nodes map contains nullptr for node "<< i; 
                  problem_found = true;
                }
              else if ( i != static_cast<uint32_t>(ordered_nodes[i]->Read(nu_key)) ) {
                  cerr <<"\nmismatch: node "<< i <<": vs 'number' "<< ordered_nodes[i]->Read(nu_key);
                  problem_found = true;
                }
            }
         if ( problem_found == true ) return false;  
      }       
    return true;

 } // TestNodePropertyAssignment



void SKUA_FiniteElementMeshInterface_Test::PrintOriginalNeighborIDs( const Model<3U>& model ) const
 {
    // if the element number is known so that the material IDs can be assigned correctly
    if ( model.Database().IsDefined("element number") ) {
         const csmp::Index eid_key = model.Database().StorageKey("element number");
         // creating a mapping between current elements in region 'Model' and the VSet from the element number
         const Region<3U>& domain = model.Region("Model");
         vector<const Element<3U>*> ordered_elmts(domain.Cells());
         for ( auto it=domain.CellsBegin(); it!=domain.CellsEnd(); ++it )
           ordered_elmts[ static_cast<uint32_t>((*it)->Read(eid_key)) ] = (*it);
           
         // reading the VSet material record
         for ( auto it=ordered_elmts.begin(); it!=ordered_elmts.end(); ++it ) {
              cerr <<"\nelmt "<< (*it)->Read( eid_key ) <<": ";
              // printing the neighbors of this element
              for ( auto i{0}; i<(*it)->Neighbors(); ++i )
                if ( (*it)->Neighbor(i) != nullptr )
                  cerr << (*it)->Neighbor(i)->Read( eid_key ) <<" ";
                else 
                  cerr << parseBoundary( (*it)->AtBoundary(i) ) <<" ";
           }
         cerr << endl;
      }
    
  } // end PrintOriginalNeighborIDs


} // end csmp
