//
//  SKUA_FiniteElementMeshInterface_Test.cpp
//  CSMP_GitHub_UnitTests
//
//  Created by Stephan Matthai on 2/12/20.
//  Copyright © 2020 Stephan Matthai. All rights reserved.
//

#include "SKUA_FiniteElementMeshInterface_Test.h"
#include "Model.h"
#include "Boundary.h"
#include "SplitBoundary.h"
#include "VSet.h"
#include "ModelTopology.h"
#include "MeshManagementUtilities.h"
#include "ConsecutiveSequenceChecker.h"
#include "Region.h"
#include "Element.h"
#include "VTK_Interface.h"

using namespace std;

namespace csmp {

void SKUA_FiniteElementMeshInterface_Test::run()
 {
    const string model_name{"skua_cross_bedded_xsmall"};
    // const string model_name{"SKUA_box_shaped_with_split_boundary"};

    // Read VSet binary file generated by SKUA
    VSet<3U> vset;
    double   time = 0.;
    vset.InputFrom( model_name.c_str(), time );
    
    // connectivity checks before VSet is turned into csmp::Model
    Test_NodeNumberingConsistencyBetweenTetrahedraAndInterFaces( vset );
    
    // adding node and element numbering to it
    {
      PropertyData elmt_numbers( ELEMENT, SCALAR, 3U );
      PropertyData node_numbers( NODE, SCALAR, 3U );
      elmt_numbers.Reserve( vset.Elements() );
      node_numbers.Reserve( vset.Vertices() );
      for ( size_t i{0U}; i<vset.Elements(); i++ ) pushBack( elmt_numbers, makeScalar(ANY,i) );
      for ( size_t i{0U}; i<vset.Vertices(); i++ ) pushBack( node_numbers, makeScalar(ANY,i) );
      vset.AddData( "element number", elmt_numbers );
      vset.AddData( "node number", node_numbers );
    }

    // Read ModelTopology file generated by SKUA
    ModelTopology model_topology(true);
    model_topology.InputFromTextFile( model_name.c_str() );
    
    // Build Model using variables file generated by SKUA
    // TODO: variable file needs to contain the variables 'node number' , 'node variable', 'element number' and 'element variable'
    const string variables_file = model_name + "-variables.txt";
    Model<3U>  model( model_topology, vset, variables_file.c_str(), false );

    // Checks...
    if ( verbose_ ) {
         printModelDimensions( model, true );
         model.BoundariesOut();
         model.SplitBoundariesOut();
      }
    
    // =======================================================================
    //      TESTING STARTS HERE
    // =======================================================================
    // 1. basic testing
    /// consecutive numbering of nodes and elements
    /// mesh consistency (Jacobians, element volume range, non-manifold vertices, triangle boxes
    /// pfverts, disambiguated neighbors of lower-dimensional elements
    /// consistent facing directions of surface elements
    /// consecutive numbering of series of line elements
    /// material IDs
    /// test assignment of box boundary flags (sides, edges, corners)
    /// property assignment
    /// use of regions file (is this still needed?)
    // 2. advanced testing
    /// generation of boundaries
    /// generation of split boundaries
  
    // basics
    TestElementNeighborConnectivity( model );
    
    // Check consecutive numbering (if the node numbers from within the VSet have been preserved)
    set<size_t> node_numbers;
    for ( auto nit=model.Mesh().NodesBegin(); nit!=model.Mesh().NodesEnd(); nit++ )
      node_numbers.insert( (*nit).Idx() );
    const bool check_whether_max_value_is_size_minus1{true};
    _test( ConsecutiveSequenceChecker::IsRangeOfUnsignedIntConsecutive( node_numbers, check_whether_max_value_is_size_minus1 ) );
  
    // Testing split boundary functionality
    Test_NodesAndTheirManifolds( model );
    Test_InterfaceNodes( model );
    
    // Testing box-boundary flags under the assumption that neighbor connectivity is correct and the Boundaries were created correctly
    // assuming that the model is box-shaped
    if ( isStrictlyBoxShaped( model ) ) {
        _test( Test_Boundary_BoxBoundary_FlagConsistency( model, "LEFT" ) );
        _test( Test_Boundary_BoxBoundary_FlagConsistency( model, "RIGHT" ) );
        _test( Test_Boundary_BoxBoundary_FlagConsistency( model, "BOTTOM" ) );
        _test( Test_Boundary_BoxBoundary_FlagConsistency( model, "TOP" ) );
        _test( Test_Boundary_BoxBoundary_FlagConsistency( model, "BACK" ) );
        _test( Test_Boundary_BoxBoundary_FlagConsistency( model, "FRONT" ) );
      }
    
    // painting the node manifolds
    if ( verbose_ &&
         model_name == "SKUA_cross_bedded_xsmall" ) {
        VTK_Interface<3U>  vtk_output;
        const csmp::Index  var_key = model.Database().StorageKey("node variable");
        csmp::Region<3U>&  model_domain = model.Region("Model");
        for ( auto nit=model_domain.NodesBegin(); nit!=model_domain.NodesEnd(); ++nit ) {
              if ( (*nit)->IsManifold() )
                // there should be as many branches as materials come together
                (*nit)->Store( var_key, makeScalar(PLAIN,(*nit)->Manifold()->Branches()));
              else
                (*nit)->Store( var_key, makeScalar(PLAIN,0.));
          }
         _test( printRangeOfVariable( model, "node variable" ) > 1U );

          vtk_output.OutputDataToVTK( model, "node-manifolds", "node variable", 0 );

        // checking model boundary flagging
        boxFlagsToVariable( model, "node variable", "element variable" );
    
    //    vtk_output.OutputDataToVTK( model, "porosity", "porosity", 1 );
        vtk_output.OutputDataToVTK( model, "node-flag", "node variable", 1 );
        vtk_output.OutputDataToVTK( model, "element-flag", "element variable", 1 );
        vtk_output.OutputDataToVTK( model, "porosity", "porosity", 1 );

        // creating 'permeability' variable if it does not already exist
        if ( !model.Database().IsDefined("permeability") ) {
             model.CreateProperty( "permeability", "m2", SCALAR, ELEMENT );
          }
        OutputRegionsToVTK( model, "permeability" );
      }
    
 } // end run



// Testing box-boundary flags under the assumption that neighbor connectivity is correct and the Boundaries were created correctly
bool SKUA_FiniteElementMeshInterface_Test::Test_Boundary_BoxBoundary_FlagConsistency( const Model<3U>& model, const string& boundary_name )
 {
    if ( model.ContainsBoundary(boundary_name) ) {
         const Boundary<3U>& boundary = model.Boundary(boundary_name);
         BOX_BOUNDARY        bflag    = parseBoundary( boundary_name );
         // interior nodes
         for ( auto nit=boundary.NodesBegin(); nit!=boundary.PerimeterNodesBegin(); nit++ )
           _test( bflag == (*nit)->AtBoundary() );
         // perimeter nodes
         for ( auto nit=boundary.PerimeterNodesBegin(); nit!=boundary.NodesEnd(); nit++ )
           _test( belongsToSide( bflag, (*nit)->AtBoundary() ) );
           
         // the test was done
         return true;
      }
    return false; // no testing performed
}



  /// Manifolds: 1) are they present at all split boundaries, 2) do they have the right number of entries
void SKUA_FiniteElementMeshInterface_Test::Test_NodesAndTheirManifolds( const Model<3U>& model )
 {
    // 1. are internal or box boundary nodes in SplitBoundaries manifolds
    // ------------------------------------------------------------------
    // 1a. internal split boundary nodes must be manifolds
    bool all_interior_nodes_are_manifolds{true};
    for ( auto split=model.SplitBoundariesBegin(); split!=model.SplitBoundariesEnd(); split++ )
      for ( auto nit=(*split).second.NodesBegin(); nit!=(*split).second.PerimeterNodesBegin(); nit++ )
        if ( (*nit)->IsManifold() == false ) {
             all_interior_nodes_are_manifolds = false;
             break;
          }
    _test( all_interior_nodes_are_manifolds == true );

    // 1b. perimeter nodes on Box boundaries must also be manifolds
    bool box_boundary_nodes_are_manifolds{true};
    for ( auto split=model.SplitBoundariesBegin(); split!=model.SplitBoundariesEnd(); split++ )
      for ( auto nit=(*split).second.PerimeterNodesBegin(); nit!=(*split).second.NodesEnd(); nit++ )
        if ( ((*nit)->AtBoundary() != NOT && (*nit)->AtBoundary() != INTERNAL) &&
               (*nit)->IsManifold() == false ) {
             box_boundary_nodes_are_manifolds = false;
             break;
          }
    _test( box_boundary_nodes_are_manifolds == true );


    // 2. are all manifold nodes collocated? - initially they must be
    // --------------------------------------------------------------
    size_t not_collocated_nodes{0U};
    for ( auto nit=model.Mesh().NodeManifoldsBegin(); nit!=model.Mesh().NodeManifoldsEnd(); nit++ )
        if ( (*nit).AreNodesCollocated() == false ) {
             if ( verbose_ ) {
                  cout <<"\n"<<"detected manifold the nodes in which are not collocated:";
                  (*nit).Out();
               }
             not_collocated_nodes++;
          }
    _test( not_collocated_nodes == 0U );
     
 } // end Test_NodesAndTheirManifolds
 
 
 
  
/**
     Tests whether INSIDE Interface nodes match those on the outside.
     
     @attention will work also for perimeter InterFace objects where INSIDE and OUTSIDE nodes may be the same.
 */
void SKUA_FiniteElementMeshInterface_Test::Test_InterfaceNodes( const Model<3U>& model )
 {
    for ( auto it=model.Mesh().InterFacesBegin(); it!=model.Mesh().InterFacesEnd(); it++ )
      {
          const auto n_nodes{ (*it).FE()->Nodes() };
          for ( auto i{0U}; i<n_nodes; i++ ) {
              const Point<3U> pt_inside  = (*it).N(i,INSIDE)->Coordinate();
              // the outside nodes must be numbered counter-clockwise and
              // the convention adopted in CSMP is that the last outside node matches the first inside node
              const Point<3U> pt_outside = (*it).N(n_nodes-i-1U,OUTSIDE)->Coordinate();
              // are the nodes co-located? - this uses essentiallyEqual method from compareFloats.h
              _test( pt_inside == pt_outside );
              if ( verbose_ && pt_inside != pt_outside ) {
                   cout <<"\nSKUA_FiniteElementMeshInterface_Test::Test_InterfaceNodes: Interface "<< it->Idx();
                   cout <<": outside nodes do not match inside nodes."<< endl;
                }
            }
      }
      
 } // end Test_InterfaceNodes










// TODO: such a method must already exist somewhere else
void SKUA_FiniteElementMeshInterface_Test::OutputRegionsToVTK( const Model<3U>& model, const char* var_name ) const
 {
     std::cout <<"\n\nSKUA_FiniteElementMeshInterface_Test::OutputRegionsToVTK:\n";
     std::cout <<"\n\tUnique regions of model:\n";
     for ( auto rit=model.UniqueRegionsBegin(); rit!=model.UniqueRegionsEnd(); ++rit ) {
          std::cout <<"\t\t"<< (*rit).first;
          std::cout <<" "<< (*rit).second.Cells() <<" elements,";
          std::pair<int32_t, int32_t> rdim = (*rit).second.ElementSpatialDimensions();
          if ( rdim.second == 3 )
            std::cout <<" volume (m3): "<< (*rit).second.Volume() <<", surface area (m2): "<< (*rit).second.SurfaceArea();
          else if ( rdim.second == 2 )
            std::cout <<" surface area (m2): "<< (*rit).second.Volume() <<", perimeter length (m): "<< (*rit).second.SurfaceArea();
          std::cout <<", range of spatial dimensions: "<< rdim.first <<", highest spatial dimension "<< rdim.second << std::endl;
       }

     // writing all regions with model name - region name and variable name
     VTK_Interface<3U>().OutputRegionByRegionToVTK( model, "SKUA_CSMP_test_", var_name, 0 );

 } // end OutputRegionsToVTK



/**
   Checks whethe the assignment of element neighbors from SKUA is identical with that done by CSMP; the side boundary flags are not considered.
   
      TODO: also check neighbor connectivity of Face and InterFace objects
*/
bool SKUA_FiniteElementMeshInterface_Test::TestElementNeighborConnectivity( Model<3U>& model )
 {
    const csmp::Index eidx = model.Database().StorageKey("element number");
    const csmp::Index nidx = model.Database().StorageKey("node number");
    Region<3U>& domain(model.Region("Model"));
    // recording connectivity from SKUA in an element neighbor vector
    vector<vector<Element<3U>*> > pfverts;
    pfverts.reserve( domain.Cells() );
    for ( auto it=domain.CellsBegin(); it!=domain.CellsEnd(); ++it ) {
         vector<Element<3U>*> nbors( (*it)->Neighbors(), nullptr );
         for ( auto i{0}; i<(*it)->Neighbors(); ++i )
           if ( (*it)->Neighbor(i) != nullptr )
             nbors[i] = (*it)->Neighbor(i);
         pfverts.push_back( nbors );
      }
      
   if ( verbose_ ) PrintOriginalNeighborIDs( model );
      
    // recreating the connectivity in CSMP
    model.Mesh().UpdateConnectivity();
    if ( verbose_ ) PrintOriginalNeighborIDs( model );
    
    // comparing SKUA with CSMP connectivity
    size_t failed_comparisons(0U);
    vector<vector<Element<3U>*> >::const_iterator pfit(pfverts.begin());
    for ( auto it=domain.CellsBegin(); it!=domain.CellsEnd(); ++it, ++pfit ) {
         for ( auto i{0}; i<(*it)->Neighbors(); ++i )
           if ( (*it)->Neighbor(i) != (*pfit)[i] ) {
                if ( verbose_ ) {
                     //(*it)->Out();
                     cerr <<"\nelement neighbor "<< (*it)->Read(eidx) <<":"<< i <<": ";
                     cerr << (*it)->Neighbor(i)->Idx() <<" vs. "<< (*pfit)[i]->Read(eidx) <<" ";
                  }
                failed_comparisons++;
             }
      }
    if ( verbose_ && failed_comparisons > 0 ) cerr << endl;
      
    if ( failed_comparisons > 0U ) return false;  
    return true;
    
 } // end TestElementNeighborConnectivity
 
 
 
 
/** tests whether the number of nodes in InterFace cells is consistent with their parent tetrahedral Element cells
 
        Uses the VSet 'pfvert' record to recover the necessary information for each InterFace: this record is expect to contain:
        interface neighbors(entries 0..2), inner-parent elmt(3), outer-parent elmt(4), inner-face idx(5), outer-face idx(6), intervening-elmt idx(7) or INTERNAL (see OutputMeshToVSet)
 */
void SKUA_FiniteElementMeshInterface_Test::Test_NodeNumberingConsistencyBetweenTetrahedraAndInterFaces( const VData& vdata )
 {
    assert( vdata.HybridElementTypeMesh() );
    assert( vdata.IsoparametricElementMesh() );
    assert( vdata.Interfaces() > 0U );
    
     // looping over the InterFace records in VSet
     for ( size_t i{ vdata.Elements() + vdata.Faces() }; i<vdata.TotalNumberOfCells(); i++ )
       {
          assert( vdata.ElementType(i) == ISOPARAMETRIC_LINEAR_TRIANGLE );
          assert( vdata.PfvertsSize(i) == 8U );
          
          // checking inside element first
          // -----------------------------
          // - the nodes of the INSIDE parent face touching the interface must be exactly the same
          //   (for the linear tet, these are: face 0: 1 2 3, face 1: 0 3 2, 2: 0 1 3, and face 3: 0 2 1)
          const size_t inner_elmt     = vdata.Pfvert(i,3);
          const size_t inner_face_idx = vdata.Pfvert(i,5);
          const size_t node0(vdata.Plist(i,0)), node1(vdata.Plist(i,1)), node2(vdata.Plist(i,2));
          switch( inner_face_idx ) {
              case 0:
                  // first 3 nodes of interface must match those of face 1 of the tetrahedron
                  _test( node0 == vdata.Plist(inner_elmt,1) );
                  _test( node1 == vdata.Plist(inner_elmt,2) );
                  _test( node2 == vdata.Plist(inner_elmt,3) );
                break;
              case 1:
                  _test( node0 == vdata.Plist(inner_elmt,0) );
                  _test( node1 == vdata.Plist(inner_elmt,3) );
                  _test( node2 == vdata.Plist(inner_elmt,2) );
                break;
              case 2:
                  _test( node0 == vdata.Plist(inner_elmt,0) );
                  _test( node1 == vdata.Plist(inner_elmt,1) );
                  _test( node2 == vdata.Plist(inner_elmt,3) );
                break;
              case 3:
                  _test( node0 == vdata.Plist(inner_elmt,0) );
                  _test( node1 == vdata.Plist(inner_elmt,2) );
                  _test( node2 == vdata.Plist(inner_elmt,1) );
            }
          // checking outside element
          // ------------------------
          // - the nodes of the INSIDE parent face touching the interface must be exactly the same
          //   (for the linear tet, these are: face 0: 1 2 3, face 1: 0 3 2, 2: 0 1 3, and face 3: 0 2 1)
          const size_t outer_elmt     = vdata.Pfvert(i,4);
          const size_t outer_face_idx = vdata.Pfvert(i,6);
          const size_t node3(vdata.Plist(i,3)), node4(vdata.Plist(i,4)), node5(vdata.Plist(i,5));
          switch( outer_face_idx ) {
              case 0:
                  // for the outside, these nodes must be listed in reverse order
                  _test( node5 == vdata.Plist(outer_elmt,1) );
                  _test( node4 == vdata.Plist(outer_elmt,2) );
                  _test( node3 == vdata.Plist(outer_elmt,3) );
                break;
              case 1:
                  _test( node5 == vdata.Plist(outer_elmt,0) );
                  _test( node4 == vdata.Plist(outer_elmt,3) );
                  _test( node3 == vdata.Plist(outer_elmt,2) );
                break;
              case 2:
                  _test( node5 == vdata.Plist(outer_elmt,0) );
                  _test( node4 == vdata.Plist(outer_elmt,1) );
                  _test( node3 == vdata.Plist(outer_elmt,3) );
                break;
              case 3:
                  _test( node5 == vdata.Plist(outer_elmt,0) );
                  _test( node4 == vdata.Plist(outer_elmt,2) );
                  _test( node3 == vdata.Plist(outer_elmt,1) );
            }
       }
       
 } // end Test_NodeNumberingConsistencyBetweenTetrahedraAndInterFaces
  
 
 
 
 
 
bool SKUA_FiniteElementMeshInterface_Test::TestNodePropertyAssignment( const Model<3>& model )
 {
    // if the element number is known so that the material IDs can be assigned correctly
    if ( model.Database().IsDefined("node number") ) {
         const csmp::Index nn_key = model.Database().StorageKey("node number");
         const csmp::Index nu_key = model.Database().StorageKey("number");
         // creating a mapping between current elements in region 'Model' and the VSet from the element number
         const Region<3U>& domain = model.Region("Model");
         vector<const Node<3U>*> ordered_nodes(domain.Nodes());

         for ( auto nit=domain.NodesBegin(); nit!=domain.NodesEnd(); ++nit ) {
              if ( fabs((*nit)->Read(nn_key) - (*nit)->Read(nu_key)) > numeric_limits<double>::epsilon() ) { 
                   cerr <<"\n\tnode number vs. number: "<< (*nit)->Read(nn_key) <<" vs. "<< (*nit)->Read(nu_key);
                   _equal( (*nit)->Read(nn_key), (*nit)->Read(nu_key), numeric_limits<double>::epsilon() );
                }
              ordered_nodes[ static_cast<uint32_t>((*nit)->Read(nn_key)) ] = (*nit);
           }
           
         bool problem_found(false);  
         for ( auto i{0}; i<ordered_nodes.size(); ++i ) {
              if ( ordered_nodes[i] == nullptr ) {
                  cerr <<"\nordered nodes map contains nullptr for node "<< i; 
                  problem_found = true;
                }
              else if ( i != static_cast<uint32_t>(ordered_nodes[i]->Read(nu_key)) ) {
                  cerr <<"\nmismatch: node "<< i <<": vs 'number' "<< ordered_nodes[i]->Read(nu_key);
                  problem_found = true;
                }
            }
         if ( problem_found == true ) return false;  
      }       
    return true;

 } // TestNodePropertyAssignment



/**
    This method assumes that the original element numbering was stored in the variable "element number"
*/
void SKUA_FiniteElementMeshInterface_Test::PrintOriginalNeighborIDs( const Model<3U>& model ) const
 {
    // if the element number is known so that the material IDs can be assigned correctly
    if ( model.Database().IsDefined("element number") ) {
         const csmp::Index eid_key = model.Database().StorageKey("element number");
         // creating a mapping between current elements in region 'Model' and the VSet from the element number
         const Region<3U>& domain = model.Region("Model");
         vector<const Element<3U>*> ordered_elmts(domain.Cells());
         for ( auto it=domain.CellsBegin(); it!=domain.CellsEnd(); ++it )
           ordered_elmts[ static_cast<uint32_t>((*it)->Read(eid_key)) ] = (*it);
           
         // reading the VSet material record
         for ( auto it=ordered_elmts.begin(); it!=ordered_elmts.end(); ++it ) {
              cerr <<"\nelmt "<< (*it)->Read( eid_key ) <<": ";
              // printing the neighbors of this element
              for ( auto i{0}; i<(*it)->Neighbors(); ++i )
                if ( (*it)->Neighbor(i) != nullptr )
                  cerr << (*it)->Neighbor(i)->Read( eid_key ) <<" ";
                else 
                  cerr << parseBoundary( (*it)->AtBoundary(i) ) <<" ";
           }
         cerr << endl;
      }
    
  } // end PrintOriginalNeighborIDs



/* TESTS WITH THOMAS JEROME's SKUA-CSMP INTERFACE

    // 0. creating box-shaped test model with nodes on the side surfaces
    SKUA_Model  model( "V6_SOLID2_withwells_BINARY",   // V6_SOLID2_with_wells, "V6_SOLID2", ,"V1_SOLID2_ASCII", "V6_SOLID2_withwells_ASCII", "EW01_100ftBAND_10ft"
                       "CSMP-variables.txt",
                       true,   ///< true = binary, false = ascii
                       true );  ///< isoparametric is the only option if model does not only consist of simplex elements

    printModelDimensions( model, true );
    model.RegionsOut();

    // Testing
    _test( model.Mesh().Elements() == 21116/4 );
    _test( model.Mesh().Nodes() == 1262 );

//    _test( TestNeighborConnectivity( model ) );
    const Region<3U>&  unit_A(model.Region("UNIT_A"));
    _test( unit_A.Cells() == 1775 );

    const Region<3U>&  unit_B(model.Region("UNIT_B"));
    _test( unit_B.Elements() == 1743 );

    const Region<3U>&  unit_C(model.Region("UNIT_C"));
    _test( unit_C.Elements() == 1761 );
    
    // are the property values assigned in the correct sequence?
    _test( TestNodePropertyAssignment( model ) );
*/

} // end csmp
