#include "SplitBoundary_Test.h"
#include "Boundary.h"
#include "VTU_Interface.h"
#include "ANSYS_Model2D.h"
#include "ANSYS_Model3D.h"
//#include "EclipseModel.h"
#include "meshManagementUtilities.h"
#include "VTK_Interface.h"
#include "ModelTopology.h"
#include "InputDataManager.h"
#include "compareFloats.h"

using namespace std;

// TODO: when the new nodes and elements are created, are the property values from the old nodes mapped to them? - would this help a user?

namespace csmp {

void SplitBoundary_Test::run()
{
    //E.P Test Splitboundary members
    //linear 2d tests
    Test_InputNodePropertyValue("InternalBoundary_test");
    Test_Area_and_SurfaceIntegral("InternalBoundary_test");

    // TODO: needs new binary input files from Anne-Laure Tertois (AspenTech)
    //Test_InitialiseSKUA_Model();

    //quadratic 2d tests
    Test_InputNodePropertyValue("InternalBoundary_Test_quadratic"); 
    Test_Area_and_SurfaceIntegral("InternalBoundary_Test_quadratic");
}


/*
    Uses various models to test the SKUA - CSMP VSet transfer capabilities:
    
    1) SKUA_split_boundary_surface
    2) SKUA_snowflake
*/
void SplitBoundary_Test::Test_InitialiseSKUA_Model()
 {
    // Test 1: box with single rectangular split boundary that does not touch model boundaries
    // ---------------------------------------------------------------------------------------
    {
        const string model_name1{"SKUA_split_boundary_surface"};
        if ( verbose_ )
          cout <<"\n\n\n"<<"SplitBoundary_Test: running compatibility test for model '"<< model_name1 <<"'"<< endl;
          
        double   model_time{ 0. };
        VSet<3U> vset;
        vset.InputFrom( model_name1.c_str(), model_time );

        // Read ModelTopology file generated by SKUA
        ModelTopology model_topology(true);
        model_topology.InputFromTextFile( model_name1.c_str() );
        
        // Assign box boundary flags TODO: remove this once Anne-Laure automated the creation of this info
    /*
    model_topology.AssignBoxShapedModelFlags( vset );
    cout <<"\n bflags created by ModelTopology:"<< endl;
    for ( size_t i{0U}; i<vset.Vertices(); i++ )
      cout << static_cast<int>(vset.BFlag(i)) <<" ";
    */

        // assigning element and node numbers needed for VSet comparison
        // element numbers
        const uint32_t dim{3};
        PropertyData elmt_nums( ELEMENT, SCALAR, dim );
        elmt_nums.Reserve( vset.Elements() );
        for ( size_t i{0U}; i<vset.Elements(); ++i ) pushBack( elmt_nums, makeScalar( ANY, i ) );
        vset.AddData( "element number", elmt_nums );
        // face numbers
        PropertyData face_nums( FACE, SCALAR, dim );
        face_nums.Reserve( vset.Faces() );
        for ( size_t i{0U}; i<vset.Faces(); ++i ) pushBack( face_nums, makeScalar( ANY, i ) );
        vset.AddData( "face number", face_nums );
        // interface numbers
        PropertyData iface_nums( INTER_FACE, SCALAR, dim );
        iface_nums.Reserve( vset.Interfaces() );
        for ( size_t i{0U}; i<vset.Interfaces(); ++i ) pushBack( iface_nums, makeScalar( ANY, i ) );
        vset.AddData( "interface number", iface_nums );
        // node numbers
        PropertyData node_nums( NODE, SCALAR, dim );
        node_nums.Reserve( vset.Vertices() );
        for ( size_t i{0U}; i<vset.Vertices(); ++i ) pushBack( node_nums, makeScalar( ANY, i ) );
        vset.AddData( "node number", node_nums );
        
        // Build Model using variables file generated by SKUA
        const string variables_file = model_name1 + "-variables.txt";
        Model<3U>    model( model_topology, vset, variables_file.c_str(), false );
        model.Name( model_name1.c_str() );

        // Checks...
        printModelDimensions( model, true );
        // are the manifolds there?
        size_t manifold_count{0U};
        const Region<3U>& model_domain( model.Region("Model"));
        for ( const auto& nit : model_domain.NodeVector() )
          if ( nit->IsManifold() ) manifold_count++;
        _test( vset.NodeManifolds() == manifold_count/2 ); // since there are 2 distinct 1nodes connected to each manifold
        
        // Creating property values
        model.CreateProperty( "compressibility", "c", "Pa-1", SCALAR, ELEMENT );
        model.InputPropertyValue( "compressibility",  makeScalar(PLAIN,5.0e-10) ); // for fluid and rock, in Pa-1
        
        // Adding required properties which are not read from SKUA exported file
        model.CreateProperty( "fluid volume source", "Qv", "m3 m-2 s-1", SCALAR, ELEMENT );
        model.CreateProperty( "fluid pressure", "pf", "Pa", SCALAR, NODE );
        
        // Using 'node variable' to see whether perimeter nodes are discovered correctly
        model.InputPropertyValue( "node variable",  makeScalar(PLAIN,0.) );
        // assigning values at inside, outside and perimeter
        SplitBoundary<3U>& split_boundary( model.SplitBoundary("split_boundary_inside"));
        split_boundary.InputNodePropertyValue( "node variable", makeScalar(PLAIN,1.), INTERIOR, INSIDE );
        split_boundary.InputNodePropertyValue( "node variable", makeScalar(PLAIN,2.), INTERIOR, OUTSIDE );
        split_boundary.InputNodePropertyValue( "node variable", makeScalar(PLAIN,3.), PERIMETER, INSIDE );

        if ( verbose_ ) {
            VTK_Interface<3U>  vtk_output;
            vtk_output.OutputDataToVTK( model, "SKUA_porosity", "porosity", 0 );
            vtk_output.OutputDataToVTK( model, "SKUA_permeability", "permeability", 0 );
            vtk_output.OutputDataToVTK( model, "SKUA_compressibility", "compressibility", 0 );
            // specially flagged split boundary (O.K.)
            vtk_output.OutputDataToVTK( model, "inside_outside_perimeter", "node variable", 0 );
          }
        
    /*
        InputDataManager<3U>  model_configuration;
        model_configuration.ConfigureFromFile(  model, model_name.c_str(),
                                                false,   // region name from parameter range
                                                true,    // default property values
                                                true,    // regional property values
                                                true,    // boundary conditions for box-shaped model
                                                false,   // essential conditions for regions
                                                false );
    */
        // TESTING
        // -------
        // comparing original VSet with one that was output from model
        VSet<3U> vset_restored;
        const bool get_indices_from_stored_variables{false}; // no need because the model was not saved to disk in between
        model.OutputMeshTo( vset_restored, get_indices_from_stored_variables );
        
        _test( vset_restored == vset );
    } // end Test1
   
   
   // Test 2: "SKUA_snowflake" box with multiple T- and intersecting split boundaries in a box
   // ----------------------------------------------------------------------------------------
   {
        const string model_name2{"SKUA_snowflake"};
        if ( verbose_ )
          cout <<"\n\n\n"<<"SplitBoundary_Test: running compatibility test for model '"<< model_name2 <<"'"<< endl;
          
        double   model_time{ 0. };
        VSet<3U> vset;
        vset.InputFrom( model_name2.c_str(), model_time );

        // Read ModelTopology file generated by SKUA
        ModelTopology model_topology(true);
        model_topology.InputFromTextFile( model_name2.c_str() );

        // assigning element and node numbers needed for VSet comparison
        // element numbers
        const uint32_t dim{3};
        PropertyData elmt_nums( ELEMENT, SCALAR, dim );
        elmt_nums.Reserve( vset.Elements() );
        for ( size_t i{0U}; i<vset.Elements(); ++i ) pushBack( elmt_nums, makeScalar( ANY, i ) );
        vset.AddData( "element number", elmt_nums );
        // face numbers
        PropertyData face_nums( FACE, SCALAR, dim );
        face_nums.Reserve( vset.Faces() );
        for ( size_t i{0U}; i<vset.Faces(); ++i ) pushBack( face_nums, makeScalar( ANY, i ) );
        vset.AddData( "face number", face_nums );
        // interface numbers
        PropertyData iface_nums( INTER_FACE, SCALAR, dim );
        iface_nums.Reserve( vset.Interfaces() );
        for ( size_t i{0U}; i<vset.Interfaces(); ++i ) pushBack( iface_nums, makeScalar( ANY, i ) );
        vset.AddData( "interface number", iface_nums );
        // node numbers
        PropertyData node_nums( NODE, SCALAR, dim );
        node_nums.Reserve( vset.Vertices() );
        for ( size_t i{0U}; i<vset.Vertices(); ++i ) pushBack( node_nums, makeScalar( ANY, i ) );
        vset.AddData( "node number", node_nums );
        
        // Build Model using variables file generated by SKUA
        const string variables_file = "SKUA_split_boundary_surface-variables.txt";
        Model<3U>    model( model_topology, vset, variables_file.c_str(), false );
        model.Name( model_name2.c_str() );

        // Checks...
        printModelDimensions( model, true );
        // are the manifolds there?
        size_t manifold_count{0U};
        const Region<3U>& model_domain( model.Region("Model"));
        for ( const auto& nit : model_domain.NodeVector() )
          if ( nit->IsManifold() ) manifold_count++;
        _test( vset.NodeManifolds() == manifold_count/2 ); // since there are 2 distinct 1nodes connected to each manifold
        
        // Creating property values
        model.CreateProperty( "compressibility", "c", "Pa-1", SCALAR, ELEMENT );
        model.InputPropertyValue( "compressibility",  makeScalar(PLAIN,5.0e-10) ); // for fluid and rock, in Pa-1
        
        // Adding required properties which are not read from SKUA exported file
        model.CreateProperty( "fluid volume source", "Qv", "m3 m-2 s-1", SCALAR, ELEMENT );
        model.CreateProperty( "fluid pressure", "pf", "Pa", SCALAR, NODE );
        
        // Using 'node variable' to see whether perimeter nodes are discovered correctly
        model.InputPropertyValue( "node variable",  makeScalar(PLAIN,0.) );
        // assigning values at inside, outside and perimeter
        SplitBoundary<3U>& split_boundary1( model.SplitBoundary("main_split_boundary_1"));
        split_boundary1.InputNodePropertyValue( "node variable", makeScalar(PLAIN,1.), INTERIOR, INSIDE );
        split_boundary1.InputNodePropertyValue( "node variable", makeScalar(PLAIN,2.), INTERIOR, OUTSIDE );
        split_boundary1.InputNodePropertyValue( "node variable", makeScalar(PLAIN,3.), PERIMETER, INSIDE );

        SplitBoundary<3U>& split_boundary2( model.SplitBoundary("secondary_split_boundary_1"));
        split_boundary2.InputNodePropertyValue( "node variable", makeScalar(PLAIN,1.), INTERIOR, INSIDE );
        split_boundary2.InputNodePropertyValue( "node variable", makeScalar(PLAIN,2.), INTERIOR, OUTSIDE );
        split_boundary2.InputNodePropertyValue( "node variable", makeScalar(PLAIN,3.), PERIMETER, INSIDE );

        if ( verbose_ ) {
            VTK_Interface<3U>  vtk_output;
            vtk_output.OutputDataToVTK( model, "SKUA_porosity", "porosity", 0 );
            vtk_output.OutputDataToVTK( model, "SKUA_permeability", "permeability", 0 );
            vtk_output.OutputDataToVTK( model, "SKUA_compressibility", "compressibility", 0 );
            // specially flagged split boundary (O.K.)
            vtk_output.OutputDataToVTK( model, "inside_outside_perimeter", "node variable", 0 );
          }

        // TESTING
        // -------
        // comparing original VSet with one that was output from model
        VSet<3U> vset_restored;
        const bool get_indices_from_stored_variables{false}; // no need because the model was not saved to disk in between
        model.OutputMeshTo( vset_restored, get_indices_from_stored_variables );
        
        _test( vset_restored == vset );
    } // end Test2

    
 } // end Test_InitialiseSKUA_Model
        





/**
    Tests that properties are indeed defined on the node side they should be on (perimiter option not tested)
    
    @author Eddi & SKM

*/
bool SplitBoundary_Test::Test_InputNodePropertyValue(const char* mesh_file /* InternalBoundary_Test */ )
 {
    enum {dim=2U};
    
    // Model initialization
    //const char* mesh_file_lin("InternalBoundary_Test");
    //const char* mesh_file_quad("InternalBoundary_Test_quadratic");
    const char* variables_file("SplitBoundary_Test-variables.txt");
    const char* regions_file("InternalBoundary_Test");

    ANSYS_Model2D  model(mesh_file, regions_file, variables_file, true, true );
    const size_t   n_elmts_in_model    = model.Region("Model").Cells();
    const size_t   n_elmts_in_fracture = model.Region("FRACTURE").Cells();

    const bool retain_elmts_as_intervening_elmts{ false };
    pair<set<string>,bool> sb_name = model.CreateSplitBoundaryFrom("FRACTURE",retain_elmts_as_intervening_elmts); // only a single patch
    SplitBoundary<dim>&   splitbdr = model.SplitBoundary( (*sb_name.first.begin()) );
    _test( splitbdr.Cells() == n_elmts_in_fracture );
    _test( model.ContainsRegion("FRACTURE") == false );

// tested flags: OK
boundaryAndTopoTypeFlagsToVTU( model, model.Region("Model") );
boundaryAndTopoTypeFlagsToVTU( model, splitbdr );

    int32_t material_id = 1;
    set<string>  dimM1_regions = model.InsertLowerDimensionalRegionsIntoSplitBoundaries(material_id);
    _test( model.Mesh().Elements() == n_elmts_in_model ); // back to the original number of elements
    _test( dimM1_regions.size() == 1 );
    _test( model.Region( (*dimM1_regions.begin()) ).Cells() == n_elmts_in_fracture );

// testing flags: OK
boundaryAndTopoTypeFlagsToVTU( model, model.Region( (*dimM1_regions.begin()) ) );
    
    model.CreateProperty( "inside", "is",  "none",  SCALAR, NODE, 1, 0.0, 100);
    model.CreateProperty( "outside", "os", "none",  SCALAR, NODE, 1, 0.0, 100);
    model.CreateProperty( "middle", "mid", "none",  SCALAR, NODE, 1, 0.0, 100);

    ScalarVariable val1(PLAIN, 1.0);
    ScalarVariable val2(PLAIN, 2.0);
    ScalarVariable val3(PLAIN, 3.0);
    splitbdr.InputNodePropertyValue( "inside",   val1, COMPLETE, INSIDE);
    splitbdr.InputNodePropertyValue( "outside",  val2, COMPLETE, OUTSIDE);
    splitbdr.InputNodePropertyValue( "middle",   val3, COMPLETE, MIDDLE);

    // testing: are the assigned not values correct
    for ( auto ifit = splitbdr.CellsBegin(); ifit != splitbdr.CellsEnd(); ++ifit ){
        for ( uint32_t i{0U}; i < (*ifit)->FE()->Nodes(); i++ ){
            _test( (*ifit)->N(i, INSIDE)->Read(model.Database().StorageKey("inside"))   == 1.0);
            _test( (*ifit)->N(i, OUTSIDE)->Read(model.Database().StorageKey("outside")) == 2.0);
            _test( (*ifit)->N(i, MIDDLE)->Read(model.Database().StorageKey("middle"))   == 3.0);
        }
    }

    return true;
}





//Tests that properties are indeed defined on the node side they should be on (perimiter option not tested)
bool SplitBoundary_Test::Test_Area_and_SurfaceIntegral(const char* mesh_file){

    enum {dim=2U};
    // Model initialization
    //const char* mesh_file_lin("InternalBoundary_Test");
    //const char* mesh_file_quad("InternalBoundary_Test_quadratic");
    const char* variables_file("SplitBoundary_Test-variables.txt");
    const char* regions_file("InternalBoundary_Test");

    //model construction
    ANSYS_Model2D model(mesh_file, regions_file, variables_file, true, true);

    //split boundary construction
    const bool retain_elmts_as_intervening_elmts{ false };
    pair<set<string>,bool> sb_name  = model.CreateSplitBoundaryFrom( "FRACTURE", retain_elmts_as_intervening_elmts );

    int32_t material_id{ 1U };
    model.InsertLowerDimensionalRegionsIntoSplitBoundaries( material_id );


    model.Database().Out();
    //property construction
    model.CreateProperty("inside", "IN", "SI",  SCALAR, NODE, 1, 0.0, 100);
    model.CreateProperty("outside", "OUT", "SI",  SCALAR, NODE, 1, 0.0, 100);
    model.CreateProperty("middle", "MID", "SI",  SCALAR, NODE, 1, 0.0, 100);

    SplitBoundary<dim>& s_ref = model.SplitBoundary( (*sb_name.first.begin()) );

    ScalarVariable val1(PLAIN, 1.0);
    ScalarVariable val2(PLAIN, 2.0);
    ScalarVariable val3(PLAIN, 3.0);
    s_ref.InputNodePropertyValue( "inside",   val1, COMPLETE, INSIDE);
    s_ref.InputNodePropertyValue( "outside",  val2, COMPLETE, OUTSIDE);
    s_ref.InputNodePropertyValue( "middle",   val3, COMPLETE, MIDDLE);

    double area_inside  =  s_ref.Area(INSIDE);
    double area_outside =  s_ref.Area(OUTSIDE);
    double area_middle  =  s_ref.Area(MIDDLE);

    _test(area_inside == area_outside);
    _test(area_middle == area_inside);
    _equal(area_inside, 2.12121, 0.0001); //actual area of crack not pulled apart should be 2.12121 for mesh InternalBoundary_Test & InternalBoundary_Test_quadratic

    double int_inside  = s_ref.SurfaceIntegral(model.Database(), "inside", INSIDE);
    double int_outside = s_ref.SurfaceIntegral(model.Database(), "outside", OUTSIDE);
    double int_middle  = s_ref.SurfaceIntegral(model.Database(), "middle", MIDDLE);

    _equal(     area_inside , int_inside,  0.0001);
    _equal( 2.0*area_outside, int_outside, 0.0001);
    _equal(  3.0*area_middle, int_middle , 0.0001);

    for ( auto ifp : s_ref.CellVector() ){
      _test( ifp->UnitNormal(INSIDE)  == ifp->UnitNormal(MIDDLE)  );
      _test( ifp->UnitNormal(INSIDE)  == Point<dim>(0, 1) );
      _test( ifp->UnitNormal(OUTSIDE) == Point<dim>(0,-1) );
    }

    // SplitBoundaryInterface_Test<2U>  vis_method;
    //    vis_method.PullApartSplitboundaries(model, 1.0);
    s_ref.PullApartSplitBoundary(1.0);

    //spltting boundaries and testing area again
    area_inside  =  s_ref.Area(INSIDE);
    area_outside =  s_ref.Area(OUTSIDE);
    double new_area_middle  =  s_ref.Area(MIDDLE);
    _test(area_inside > area_middle);
    _test(area_outside > area_middle);
    _test(area_middle == new_area_middle);    //not changed area of middle element

    return true;
}

    
    




template<uint32_t dim>
void SplitBoundary_Test::LoadModel( const string& model_name )
{
  // Model initialization
  const string variables_file("SplitBoundary_Test-variables.txt");
  Model<dim>* model = NULL;
  if constexpr ( dim == 2U )
    model = dynamic_cast<Model<dim>*>(new ANSYS_Model2D( model_name.c_str(), model_name.c_str(), variables_file.c_str(), true ));
  else if constexpr ( dim == 3U )
    model = dynamic_cast<Model<dim>*>(new ANSYS_Model3D( model_name.c_str(), model_name.c_str(), variables_file.c_str(), true ));

  // visualization
  VTU_Interface<dim> vtu( *model );
  vtu.OmitZeroInFileName( false );
  list<string> outputProps;
  outputProps.push_back( "element variable" );
  ScalarVariable regionValue( ANY, 0.0 );

  if ( verbose_ ) cout << "\n\n\nSplitBoundary_Test::PrepareModel: the following interface / interface(s) sets will be considered:\n\n";
  model->InputPropertyValue( "element variable", regionValue );
  for ( typename Model<dim>::regionIterator it = model->RegionsBegin(); it != model->RegionsEnd(); it++ )
  {
    regionValue += 1.0;
    (*it).second.InputPropertyValue( "element variable", regionValue );
    vtu.OutputDataToVTU( model_name.c_str(), outputProps, (*it).first.c_str(), 0.0 );
  }
  if ( verbose_ ) vtu.OutputDataToVTU( model_name.c_str(), outputProps, "Model", 0.0 );

  model->OutputToBinaryFile( model_name.c_str() );
}





template<uint32_t dim>
void SplitBoundary_Test::LoadModel( const string& model_name,
                                    vector<string>& regions )
{
  // Model initialization
  const string variables_file("SplitBoundary_Test-variables.txt");
  Model<dim>* model = NULL;
  if constexpr ( dim == 2U )
    model = dynamic_cast<Model<dim>*>(new ANSYS_Model2D( model_name.c_str(), model_name.c_str(), variables_file.c_str(), true ));
  else if constexpr ( dim == 3U )
    model = dynamic_cast<Model<dim>*>(new ANSYS_Model3D( model_name.c_str(), model_name.c_str(), variables_file.c_str(), true ));

  // visualization
  VTU_Interface<dim> vtu( *model );
  vtu.OmitZeroInFileName( false );
  list<string> outputProps;
  outputProps.push_back( "element variable" );
  ScalarVariable regionValue( ANY, 0.0 );

  string  spliboundary_regions_file( model_name );

  // load regions from the input file
  InputFromFile( string( spliboundary_regions_file + "-disconnected-interface-regions.txt" ).c_str(), regions );

  if ( verbose_ ) cout << "\n\n\nSplitBoundary_Test::PrepareModel: the following interface / interface(s) sets will be considered:\n\n";
  model->InputPropertyValue( "element variable", regionValue );
  for ( vector<string>::const_iterator it = regions.begin(); it != regions.end(); it++ )
  {
    regionValue += 1.0;
    model->Region( (*it).c_str() ).InputPropertyValue( "element variable", regionValue );
    vtu.OutputDataToVTU( model_name.c_str(), outputProps, (*it).c_str(), 0.0 );
  }
  if ( verbose_ ) vtu.OutputDataToVTU( model_name.c_str(), outputProps, "Model", 0.0 );

  model->OutputToBinaryFile( model_name.c_str() );
}





template<uint32_t dim>
void SplitBoundary_Test::LoadContiguousModel( const string& model_name,
                                              vector<string>& interfaces )
{
  // 0. Model initialization
  const string variables_file("SplitBoundary_Test-variables.txt");
  Model<dim>* model(nullptr);
  if constexpr ( dim == 2U )
    model = dynamic_cast<Model<dim>*>(new ANSYS_Model2D( model_name.c_str(), model_name.c_str(), variables_file.c_str(), true ));
  else if constexpr ( dim == 3U )
    model = dynamic_cast<Model<dim>*>(new ANSYS_Model3D( model_name.c_str(), model_name.c_str(), variables_file.c_str(), true ));

  string  splitboundary_regions_file( model_name );

  // 1. InterFace sets
  set<string> interface_basic_sets;
  set<string> interface_sets;
  InputFromFile( string( splitboundary_regions_file + "-disconnected-interface-regions.txt" ).c_str(), interface_basic_sets );

  // 2. splitting input regions if they are discontigouos
  bool discontiguous_regions( false );
  for ( set<string>::const_iterator it = interface_basic_sets.begin(); it != interface_basic_sets.end(); ++it )
    if ( !model->IsContiguous( (*it).c_str() ) ) {
      if ( verbose_ ) cerr << "\n\tSplitBoundary_Test::PrepareModel: discovered discontiguous region: " << (*it);
      discontiguous_regions = true;
    }
  if ( discontiguous_regions ) {
    set<string>  original_region_names;
    for ( typename RegionInterface<dim, Region>::regionIterator it = model->UniqueRegionsBegin(); it != model->UniqueRegionsEnd(); ++it )
      if ( (*it).first != "Model" )
        original_region_names.insert( (*it).first.c_str() );

    // partitioning regions without revisiting new partitions that can inserted into region map
    for ( set<string>::const_iterator it = original_region_names.begin(); it != original_region_names.end(); ++it )
      model->PartitionRegionIntoContiguousSubRegions( (*it).c_str() );
  }

  // 2. preparing lower dimensional regions for making SplitBoundaries around
  etablishContiguosRegionsList( *model, interface_basic_sets, interface_sets );

  model->MergeRegions( interface_sets, "interfaces" );

  for ( auto& name : interface_sets )
    model->RemoveRegion( name.c_str(), false );

  interfaces.clear();
  interfaces.push_back( "interfaces" );
  OutputToFile( string( splitboundary_regions_file + "-connected-interface-regions.txt" ).c_str(), interfaces );

  if ( verbose_ ) cout << "\n\n\nSplitBoundary_Test::PrepareModel: the following interface(s) / interface sets will be considered:\n\n";

  // 3. creating SplitBoundaries
  for ( vector<string>::const_iterator it = interfaces.begin(); it != interfaces.end(); it++ ) {
       cerr <<"\nRecode this so that it does the right thing!\n";
       model->CreateInternalBoundaryFrom( (*it).c_str() );
       Boundary<dim>& bdry = model->Boundary( (*it).c_str() );
       model->CreateSplitBoundaryFrom( bdry, false );
    }

  // 4. creating lower-dimensional stand-alone meshes from SplitBoundary objects, and 
  //    insert them into a new sub-region (simply named by 'SPLITBOUNDARY_SURFACE')
  set<string> new_regions = model->RegionsFromSplitBoundaries();

  // 5. Writing it 
  model->OutputToBinaryFile( model_name.c_str() );
}





/// Input name of regions to split
void SplitBoundary_Test::InputFromFile( const char* file_name,
                                        set<string>& interface_basic_set )
{
  assert( file_name != NULL );

  ifstream ifs( file_name );
  if ( !ifs.is_open() )
    throw csmp::Exception( ERROR, "SplitBoundary_Test::inputFromFile",
                           file_name,
                           "file specifying regions is missing" );
  if ( !interface_basic_set.empty() )
    interface_basic_set.clear();

  // reading header line printing it to screen and swallowing empty line thereafter
  char text[256];
  ifs.getline( text, 256 );
  if ( verbose_ ) cout << "\nSplitBoundary_Test::inputFromFile: file header: " << text << endl;
  ifs.getline( text, 256 );

  int n_interfaces( 0 );
  ifs >> n_interfaces;
  assert( n_interfaces > 0 );
  assert( n_interfaces < 10000 );

  string  interface_name;
  for ( int n = 0; n<n_interfaces; n++ ) {
    ifs >> interface_name;
    if ( !interface_name.empty() )
      interface_basic_set.insert( interface_name );
    else
      throw csmp::Exception( ERROR, "SplitBoundary_Test::inputFromFile:", "encountered empty region name." );
  }

  ifs.close();

  if ( verbose_ ) cout << "\nSplitBoundary_Test::inputFromFile: region names stored in '" << file_name << "' read successfully." << endl;

} // end inputFromFile




/// Input name of regions to split
template<uint32_t dim>
void SplitBoundary_Test::EstablishContiguousRegionsList( Model<dim>& model,
                                                         const set<string>& interface_basic_set,
                                                         set<string>& interface_sets )
{
  if ( verbose_ ) cout << "\nSplitBoundary_Test::EstablishContiguousRegionsList:" << endl;

  if ( !interface_sets.empty() )
    interface_sets.clear();
  bool first_call( true );
  for ( typename map<string, csmp::Region<dim> >::const_iterator
        git = model.UniqueRegionsBegin(); git != model.UniqueRegionsEnd(); git++ )
  {
    for ( set<string>::const_iterator it = interface_basic_set.begin(); it != interface_basic_set.end(); ++it )
      if ( (*git).first.find( *it ) != string::npos )
      {
        interface_sets.insert( (*git).first );
        if ( first_call ) {
          cout << "\n\tregion(s) incorporated into the input list: ";
          first_call = false;
        }
        cout << (*git).first << " ";
        break;
      }
  }
  if ( verbose_ ) cout << "\n\n";

} // end inputFromFile




/// Input name of regions to split
void SplitBoundary_Test::InputFromFile( const char* file_name,
                                        vector<string>& interfaces )
{
  assert( file_name != NULL );

  ifstream ifs( file_name );
  if ( !ifs.is_open() )
    throw csmp::Exception( ERROR, "SplitBoundary_Test::inputFromFile",
                           file_name,
                           "file specifying regions is missing" );
  if ( !interfaces.empty() )
    interfaces.clear();

  // reading header line printing it to screen and swallowing empty line thereafter
  char text[256];
  ifs.getline( text, 256 );
  if ( verbose_ ) cout << "\nSplitBoundary_Test::inputFromFile: file header: " << text << endl;
  ifs.getline( text, 256 );

  int n_interfaces( 0 );
  ifs >> n_interfaces;
  assert( n_interfaces > 0 );
  assert( n_interfaces < 10000 );

  string  interface_name;
  for ( int n = 0; n<n_interfaces; n++ ) {
    ifs >> interface_name;
    if ( !interface_name.empty() )
      interfaces.push_back( interface_name );
    else
      throw csmp::Exception( ERROR, "SplitBoundary_Test::inputFromFile:", "encountered empty region name." );
  }

  ifs.close();

  if ( verbose_ ) cout << "\nSplitBoundary_Test::inputFromFile: region names stored in '" << file_name << "' read successfully." << endl;

} // end inputFromFile





/// Write contiguous regions
void SplitBoundary_Test::OutputToFile( const char* file_name,
                                       const vector<string>& interfaces )
{
  assert( file_name != NULL );

  ofstream ofs( file_name );
  if ( !ofs.is_open() )
    throw csmp::Exception( ERROR, "SplitBoundary_Test::outputToFile",
                           file_name, "file specifying permeability-model input variables is missing" );

  ofs << "'" << file_name << "' interface regions to be included.\n\n";

  ofs << interfaces.size() << " ";
  for ( vector<string>::const_iterator it = interfaces.begin(); it != interfaces.end(); ++it )
    ofs << (*it) << " ";

  ofs << "\n";
  ofs.close();

  if ( verbose_ ) cout << "\nSplitBoundary_Test::outputToFile: '" << file_name << "' written successfully." << endl;

} // end outputToFile




/// Write interface regions
void SplitBoundary_Test::OutputToFile( const char* file_name,
                                       const set<string>& interfaces )
{
  assert( file_name != NULL );

  ofstream ofs( file_name );
  if ( !ofs.is_open() )
    throw csmp::Exception( ERROR, "SplitBoundary_Test::outputToFile",
                           file_name, "file specifying permeability-model input variables is missing" );

  ofs << "'" << file_name << "' interface regions to be included.\n\n";

  ofs << interfaces.size() << " ";
  for ( set<string>::const_iterator it = interfaces.begin(); it != interfaces.end(); ++it )
    ofs << (*it) << " ";

  ofs << "\n";
  ofs.close();

  if ( verbose_ ) cout << "\nSplitBoundary_Test::outputToFile: '" << file_name << "' written successfully." << endl;

} // end outputToFile


} // csmp
