#include "UG4_UGX_FileExport_Test.h"
#include "UG4_UGX_FileExport.h"
#include "compareFloats.h"

#include "Model.h"
#include "Region.h"
#include "Boundary.h"
#include "ErrorHandler.h"
#include "InputDataManager.h"
#include "ModelTopology.h"
#include "SplitBoundary.h"
#include "Standard_IO_Handler.h"
#include "VTK_Interface.h"
#include "VTU_Interface.h"

#include "ANSYS_Model3D.h"
#include "vsetMakers.h"


using namespace std;

namespace csmp {

/**
    This test that belongs into the category of CSMP-Interface (to other software) tests  is not automated!
    Instead, one needs to run the test code which writes UGX files in ASCII format.
    These output files must then be checked with ProMesh for whether all the desired features of the CSMP model
    that is output (2D and 3D examples used here) are captured by the UG version of these models.
    
    @todo Currently the UG subsets in the subsethandler for CSMP Boundary objects are not visible in UG,
    upon visual examination the file-based output looks the same as for the successful output of Region objects.
*/
void UG4_UGX_FileExport_Test::Run()
 {
    // 2D Test case without SplitBoundary objects
    // ------------------------------------------
    VSet<2U> mesh;
    ModelTopology topo = test_Create_MeshPatchWithLineElements_VSet( mesh );
    const bool treat_domains_as_regions{true}; // model does not contain any Face objects!
    Model<2U> model2D( topo, mesh, "UG4_UGX_FileExport-variables.txt", treat_domains_as_regions );

    // intialising the variables 'element variable' and 'element vector'
    //model.InputPropertyValue( "element variable", makeScalar(ANY,1.0) ); - done already in VSet
    model2D.InputPropertyValue( "element vector", makeVector(ANY,ANY,1.0,2.0) );
    
    // creating another region called quadrilaterals pretending it is unique.
    // This extra output is needed because Promesh does not show the property attachments
    const bool unique_region{ true };
    model2D.FormRegionFrom( "quads", "element variable", 3.5, 5.0, unique_region );

    VTU_Interface<2U>  vtu(model2D);
    list<string> output_props{ "node number", "element number", "element variable" };
    vtu.OutputDataToVTU( "test_Create_MeshPatchWithLineElements_VSet", output_props, "Model", static_cast<int>(0) );
    
    // OUTPUTS MODEL TO UG (name will be the model name)
    UG4_UGX_FileExport<2U> ug4_exporter2D( model2D );
    ug4_exporter2D.Write_UGX_FileASCII( model2D, model2D.Name() );
    
    
    // 3D Test case using model the ANSYS model 'prism_mesh'
    // -----------------------------------------------------
    ANSYS_Model3D  model3D( "prism_test", "UG4_UGX_FileExport-variables.txt",
                             false, /* irregular_mesh */
                             true   /* binary_file */
                          );
    printRangeOfVariable( model3D, "element number" );
    printRangeOfVariable( model3D, "face number" );
    printRangeOfVariable( model3D, "node number" );
    
    // assigning the number of nodes to 'element variable' so that this array can be tested for correctness
    Region<3U>& model_domain = model3D.Region("Model");
    const csmp::Index evar_key = model3D.Database().StorageKey("element variable");
    for ( auto& it : model_domain.CellVector() )
      it->Store( evar_key, makeScalar(ANY,it->Nodes()) );
      
    model3D.InputPropertyValue( "element vector", makeVector(ANY,ANY,ANY,1.,2.,3.) );
  
    UG4_UGX_FileExport<3U> ug4_exporter3D( model3D );
    ug4_exporter3D.Write_UGX_FileASCII( model3D, model3D.Name() );

    cout << endl << endl << "Run() finished." << endl;
}





bool UG4_UGX_FileExport_Test::ImportModelAndRunChecks( const string& model_name,
                                                       const string& variables_file ) const {
  
  // Build Model using variables file generated by SKUA
  Model<3U>  model( model_name, variables_file );

  if( !RunChecks( model ) ) {
      return false;
  }

  cout << endl << "Checks successful!" << endl;
  return true;
} // end ImportModelAndRunChecks





bool UG4_UGX_FileExport_Test::RunChecks( const Model<3U>& model ) const {

  // Checks...
  printModelDimensions( model, true );

  size_t nb_things = model.Regions();
  if( nb_things == 0 ) {
      cout << endl << "Model does not have any Regions" << endl;
  } else {
      cout << endl << "Model has " << nb_things << " Regions:" << endl;
      for(
          std::map<std::string,Region<3U> >::const_iterator
          it  = model.UniqueRegionsBegin();
          it != model.UniqueRegionsEnd();
          it++
      ) {
          cout <<"\n\t"<< (*it).first;
      }
  }

  nb_things = model.Boundaries();
  if( nb_things == 0 ) {
      cout << endl << "Model does not have any Boundaries" << endl;
  } else {
      cout << endl << "Model has " << nb_things << " Boundaries:" << endl;
      for(
          BoundaryInterface<3U,Boundary>::boundaryConstIterator
          it  = model.BoundariesBegin();
          it != model.BoundariesEnd();
          it++
      ) {
          (*it).second.Out();
      }
  }
  
  nb_things = model.SplitBoundaries();
  if( nb_things == 0 ) {
      cout << endl << "Model does not have any SplitBoundaries" << endl;
  } else {
      cout << endl << "Model has " << nb_things << " SplitBoundaries:" << endl;
      for(
          SplitBoundaryInterface<3U,SplitBoundary>::splitBoundaryConstIterator
          it  = model.SplitBoundariesBegin();
          it != model.SplitBoundariesEnd();
          it++
      ) {
          (*it).second.Out();
      }
  }

  // Testing NodeManifolds
  nb_things = model.Mesh().NodeManifolds();
  bool result = true;
  if( nb_things == 0 ) {
      cout << "Model does not have any NodeManifolds" << endl;
  } else {
      cout << "Model has " << nb_things << " NodeManifolds:" << endl;

      uint32_t matched(0), unmatched(0);
      for(auto mit = model.Mesh().NodeManifoldsBegin(); mit!=model.Mesh().NodeManifoldsEnd(); mit++) {
          const NodeManifold<3U>& md = *mit;
          const uint32_t branches = md.Branches();
          for(auto n{0U}; n<branches; n++) {
              const Node<3U>* node = md.N(n);
              const NodeManifold<3U>* retrieved_md = node->Manifold();
              if(retrieved_md == &md) {
                  matched++;
                  continue;
              }
              cout << "Node " << node->Idx() << " at coordinates " << node->Coordinate() << " is inconsistent" << endl;
              cout<<"  retrieved_md size = "<<retrieved_md->Branches();
              retrieved_md->Out();
              cout<<endl;
              cout<<"  original_md size = "<<md.Branches();
              md.Out();
              cout<<endl<<endl;
              unmatched++;
        }
      }
      if( unmatched != 0 ) {
          cout << endl << unmatched <<" nodes do not retrieve the manifolds "
              "that contain them" << endl;
          result = false;
      } else {
          cout << "All manifolds are consistent" << endl;
      }
  }

  cout << "RunChecks: That's it..." << endl;
  return result;
} // end RunChecks


} // csmp
